### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by ImHimawariJP** [dmulloy2/ProtocolLib#1003]
**Describe the bug**
Startup Bug - Creates Config
java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:153)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Caused by: java.lang.NullPointerException
        at com.comphenix.protocol.reflect.FuzzyReflection.getConstructors(FuzzyReflection.java:655)
        at com.comphenix.protocol.reflect.FuzzyReflection.getConstructorList(FuzzyReflection.java:588)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:219)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        ... 9 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@17ef9af[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@188c20b
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@b83fc8
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@21ef7b
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1.7.9-R0.2-208-ge0f2e95,minecraftVersion=1.7.10}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1b84884
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@6fdd8f
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@893a2c
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    1.8.0_271
  Server:
    git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)
**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
4.5.1

**Comment by dmulloy2** [comment]
Use 3.7.0 for 1.7: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
