### ISSUE TITLE
Error when launching server

### ISSUE THREAD

**Issue by j0ach1mmall3** [dmulloy2/ProtocolLib#101]
I get this error when running the latest version of protocollib every time the server launches.
Using Tekkit Classic (MC 1.2.5)

2015-07-16 09:25:38 | [WARNING] [ProtocolLib] [ProtocolLibrary] Unable to retrieve current Minecraft version. Assuming (MC: 1.8.7)
2015-07-16 09:25:38 | [RAW] java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
2015-07-16 09:25:38 | [RAW]     at com.comphenix.protocol.ProtocolConfig.getIgnoreVersionCheck(ProtocolConfig.java:167)
2015-07-16 09:25:38 | [RAW]     at com.comphenix.protocol.ProtocolLibrary.verifyMinecraftVersion(ProtocolLibrary.java:461)
2015-07-16 09:25:38 | [RAW]     at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:206)
2015-07-16 09:25:38 | [RAW]     at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:242)
2015-07-16 09:25:38 | [RAW]     at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:213)
2015-07-16 09:25:38 | [RAW]     at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:59)
2015-07-16 09:25:38 | [RAW]     at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:167)
2015-07-16 09:25:38 | [RAW]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:428)
2015-07-16 09:25:38 | [RAW]     at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2015-07-16 09:25:38 | [ProtocolLib] Falling back to Guava 10 compat

**Comment by dmulloy2** [comment]
Can you paste your config using pastebin?

**Comment by j0ach1mmall3** [comment]
global:
  # Settings for the automatic version updater
  auto updater:
    notify: false
    download: false
    
    # Number of seconds to wait until a new update is downloaded
    delay: 43200 # 12 hours
 
  metrics: false
  
  # Automatically compile structure modifiers 
  background compiler: true
  
  # Disable version checking for the given Minecraft version. Backup your world first!
  ignore version check: true
  
  # Override the starting injecting method
  injection method: 
  
  # Whether or not to enable the filter command
  debug: false
  
  # Whether or not to print a stack trace for every warning
  detailed error: false
  
  # The engine used by the filter command
  script engine: JavaScript
  
  suppressed reports:
  - REPORT_UNSUPPORTED_CLIENT_PACKET_ID
  - REPORT_DETECTED_CUSTOM_SERVER_HANDLER
  - REPORT_CANNOT_FIND_MINECRAFT_SERVER
  - REPORT_INSUFFICIENT_SERVER_PACKETS
  - REPORT_INSUFFICIENT_CLIENT_PACKETS
  - REPORT_CANNOT_LOAD_PACKET_LIST

**Comment by dmulloy2** [comment]
````ignore version check```` must be a String, in your case it should be 1.2.5.
