### ISSUE TITLE
Unable to find NetworkManager in ...

### ISSUE THREAD

**Issue by xVorttex** [dmulloy2/ProtocolLib#1042]
Error stacktrace:
[21:49:57 INFO]: Error Unable to inject incoming channel [id: 0x8319eda8, L:/XXX:25565 - R:/XXX:63562]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x8319eda8, L:/XXX:25565 - R:/XXX:63562]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@25744cb.
[21:49:57 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x8319eda8, L:/XXX:25565 - R:/XXX:63562].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x8319eda8, L:/XX:25565 - R:/XXX:63562]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:157)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:171)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@20a464e9[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@77195f1
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@40c5c074
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7ac7ac07
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@79c70c9a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7212d04e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1c3a6818
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@3892c5df
        reporter=com.comphenix.protocol.ProtocolLib$1@1ab82c31
        server=CraftServer{serverName=CraftBukkit,serverVersion=VSpigot,minecraftVersion=1.8.8}
        library=ProtocolLib v4.5.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@31f9c2f1
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@25744cb
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6de53f4d
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@4ac9250f
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@25744cb[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@38f25661
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@267460d9, container=net.minecraft.server.v1_8_R3.ServerConnection@c1f7b28, previous=[AbstractBootstrap$PendingRegistrationPromise@3849b9ef(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@1af58afe, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@1f0243d1, container=net.minecraft.server.v1_8_R3.ServerConnection@c1f7b28, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@6833bd22
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1d40e70a
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@2bd43c26
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@26c5ee46
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@536a9d11
      invoker=com.comphenix.protocol.injector.PacketFilterManager@20a464e9
      reporter=com.comphenix.protocol.ProtocolLib$1@1ab82c31
      debug=false
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    11.0.9
  Server:
    VSpigot (MC: 1.8.8)

My NetworkManager.class
https://hastebin.com/qakidafebi.kotlin

**Comment by dmulloy2** [comment]
Try the latest dev build. We fixed an issue with newer Java versions recently

**Comment by mechoriet** [comment]
this issue seems to experience the same issue as above #1002
I tried to upgrade the netty networking from paper 1.8.8 base version(4.0.23.Final) to 4.1.56.Final logging in to the server works fine I can do everything
but I get the same error on the same lines as above
my testing was done with ProtocolLib v4.6.0-SNAPSHOT-b1
in both java 8 and java 11

I don't know if the issuer did the same to his spigot or the one on the referenced issue

maybe this is some helpful information

**Comment by MacacoLew** [comment]
The error is present in Netty 4.1.50.Final, is a issue from ProtocolLib end i think

**Comment by MacacoLew** [comment]
https://github.com/aadnk/ProtocolLib/pull/175/commits/2e213338ecba4383ec28ac9f48d54e3d624cf3d5

This pull request fix's the issue, im not getting the spam in console with that patch
