### ISSUE TITLE
Chat extensions 1.16.4  warnings after update 486

### ISSUE THREAD

**Issue by RavenskyPaul** [dmulloy2/ProtocolLib#1045]
`[04:05:11] [Netty Epoll Server IO #1/ERROR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.ChatMessageType.a()" because "this.b" is null
[04:05:11] [Netty Epoll Server IO #1/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.v1_16_R3.ChatMessageType.a()" because "this.b" is null
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayOutChat.b(PacketPlayOutChat.java:44)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:42)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:12)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.util.PipelineUtil.callEncode(PipelineUtil.java:71)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:49)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:525)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:67)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:265)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:271)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:76)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:109)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:409)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:348)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[04:05:11] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)`

Server version 1.16.4
Java 15.0.1
Protocollib the latest build 486

Here is the protocol dump:
https://pastebin.com/C9bdpYyZ

**Comment by RavenskyPaul** [comment]
Here is the protocol dump:
https://pastebin.com/C9bdpYyZ
