### ISSUE TITLE
Bug...

### ISSUE THREAD

**Issue by MinecraftLEAD** [dmulloy2/ProtocolLib#1048]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

[22:37:42] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib]: [ProtocolLib] Enabling ProtocolLib v4.5.1
[22:37:42] [Server thread/INFO] []: Error Cannot enable ProtocolLib. (java.lang.ExceptionInInitializerError) occured in ProtocolLib v4.5.1.
[22:37:42] [Server thread/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:420)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:379)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:256)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
        at java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.entity.EntityLivingBase}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.entity.EntityLivingBase instanceof input, Index: 2}, {Type: class net.minecraft.server.MinecraftServer instanceof input, Index: 0}], paramCount=3}]
  }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        ... 9 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@7ed705d7[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1b4f4174
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@38bd6b4e
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@79a7d73f
      server=CraftServer{serverName=Kettle,serverVersion=git-HEAD-a8543ec,minecraftVersion=1.12.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6f7e9c8e
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1fe1edb3
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@5d6fd97a
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    1.8.0_251
  Server:
    git-HEAD-a8543ec (MC: 1.12.2)

i use kettle

**Comment by dmulloy2** [comment]
Try one of the latest dev builds
