### ISSUE TITLE
Cannot load ProtocolLib at arclight server.

### ISSUE THREAD

**Issue by VeroFess** [dmulloy2/ProtocolLib#1072]
**Describe the bug**
Cannot load ProtocolLib at arclight (https://github.com/IzzelAliz/Arclight) server.

**To Reproduce**
1. Download  the latest dev build of arclight server (https://ci.appveyor.com/project/IzzelAliz/arclight-16)
2. Download  the latest dev build of ProtocolLib
3. Put the ProtocolLib plugin in the plugins folder

**Expected behavior**
`[04:01:57] [Server thread/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.`

**Screenshots**
NONE

**Version Info**
  - **ProtocolLib Version**: ProtocolLib v4.6.0-SNAPSHOT-b492
  - **Java Version**: 11.0.9
  - **Server**: arclight-1.16.5-1.0.12-SNAPSHOT-f0b4f82 (MC: 1.16.5)

**Additional context**
```
[04:01:57] [Server thread/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:68)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:388)
        at net.minecraft.server.dedicated.DedicatedServer.handler$bbk000$arclight$loadPlugins(DedicatedServerMixin.java:630)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1857)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: java.lang.ClassLoader$ByteBuddyAccessor$UsqJLOUY.defineClass(java.lang.ClassLoader, java.lang.String, [B, int, int, java.security.ProtectionDomain)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:409)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 11 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@15bdb03f[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@746b4ab
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@60746d45
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@76dcfe4
      server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.16.5-1.0.12-SNAPSHOT-f0b4f82,minecraftVersion=1.16.5}
      file=plugins/[前置]ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4d78bbdc
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@4ec8643b
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=io.izzel.arclight.common.mod.util.log.ArclightPluginLogger@675e05ac
    ]
  Version:
    ProtocolLib v4.6.0-SNAPSHOT-b492
  Java Version:
    11.0.9
  Server:
    arclight-1.16.5-1.0.12-SNAPSHOT-f0b4f82 (MC: 1.16.5)

```

**Comment by VeroFess** [comment]
Duplicate of #1057
