### ISSUE TITLE
NoSuchMethodError Problem?

### ISSUE THREAD

**Issue by Splitrox** [dmulloy2/ProtocolLib#1076]
> java.lang.NoSuchMethodError: 'java.util.Set com.comphenix.protocol.injector.packet.PacketRegistry.toPacketTypes(java.util.Set)'
>         at com.comphenix.protocol.events.ListeningWhitelist.<init>(ListeningWhitelist.java:96) ~[?:?]
>         at com.comphenix.protocol.events.ListeningWhitelist.<clinit>(ListeningWhitelist.java:41) ~[?:?]
>         at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:44) ~[?:?]
>         at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:52) ~[?:?]
>         at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:104) ~[?:?]
>         at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:64) ~[?:?]

![image](https://user-images.githubusercontent.com/49073687/106274568-62c39500-622c-11eb-89d7-2efbc8a778f9.png)

I had this code at 1.14 and it worked without problems, I tried at 1.16 and it gave an error ...
I have already updated my server's protocol to the latest version and even then it still fails, am I doing something wrong or is it really a problem on your side?

**Comment by Splitrox** [comment]
Lel pom issue sry
