### ISSUE TITLE
When a player tries joining

### ISSUE THREAD

**Issue by KeanoPlaysYT** [dmulloy2/ProtocolLib#1077]
[13:49:51] [Netty IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xfe953944, L:/127.0.0.1:25565 - R:/127.0.0.1:53238].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xfe953944, L:/127.0.0.1:25565 - R:/127.0.0.1:53238]
  	at com.comphenix.protocol.compat.netty.shaded.ShadedInjectionFactory.findNetworkManager(ShadedInjectionFactory.java:212)
  	at com.comphenix.protocol.compat.netty.shaded.ShadedInjectionFactory.fromChannel(ShadedInjectionFactory.java:145)
  	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector$1.initChannel(ShadedProtocolInjector.java:154)
  	at net.minecraft.util.io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at net.minecraft.util.io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:590)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:389)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:376)
  	at com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector$2.initChannel(ShadedProtocolInjector.java:168)
  	at net.minecraft.util.io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at net.minecraft.util.io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:590)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1355)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1090)
  	at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:640)
  	at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:456)
  	at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:378)
  	at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:428)
  	at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
  	at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
  	at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
  	at java.lang.Thread.run(Thread.java:748)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@24fd5f6e[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@38367246
        packetListeners=[PacketAdapter[plugin=SkQuery, sending=ListeningWhitelist{priority=HIGH, packets=[PacketPlayOutSetSlot[47, legacy: 103], PacketPlayOutWindowItems[48, legacy: 104]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutSpawnEntityLiving[15, legacy: 24], PacketPlayOutSpawnEntity[14, legacy: 23], PacketPlayOutEntityMetadata[28, legacy: 40]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInChat[1, legacy: 3]], gamephase=PLAYING, options=[]}]]
        packetInjector=com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector$5@5064b938
        playerInjection=com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector$4@5bcb5530
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@6dc713fc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@178c4c0b
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@62548abb
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@230a02b
        reporter=com.comphenix.protocol.ProtocolLibrary$1@63372114
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-mSpigot-unknown,minecraftVersion=1.7.10}
        library=ProtocolLib v3.6.4
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@432378a5
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector@6554d0ba
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@410dc25b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.7.10)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@12b7367e
        debug=false
      ]
  Sender:
    com.comphenix.protocol.compat.netty.shaded.ShadedProtocolInjector@6554d0ba[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@7c3c202b
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@26117e2c, container=net.minecraft.server.v1_7_R4.ServerConnection@6e07fab6, previous=[AbstractBootstrap$PendingRegistrationPromise@91bf0b8(success)], current=com.comphenix.protocol.compat.netty.shaded.ShadedBootstrapList@3bf8d4e6, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@16353dab, container=net.minecraft.server.v1_7_R4.ServerConnection@6e07fab6, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@47b6b791, container=net.minecraft.server.v1_7_R4.ServerConnection@6e07fab6, previous=[], current=com.comphenix.protocol.compat.netty.shaded.ShadedBootstrapList@11fe01ef, previousLoaded=true, currentSet=true, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.compat.netty.shaded.ShadedInjectionFactory@6cdcb8d2
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@533b0887
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@2143374e
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@4053bbf0
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@49c09100
      invoker=com.comphenix.protocol.injector.PacketFilterManager@24fd5f6e
      reporter=com.comphenix.protocol.ProtocolLibrary$1@63372114
      debug=false
    ]
  Version:
    ProtocolLib v3.6.4
  Server:
    git-mSpigot-unknown (MC: 1.7.10)

**Comment by dmulloy2** [comment]
Oof 3.6.4 is old. You could try 3.7.0, but MC 1.7.10 is unsupported by a good 5 years at this point

https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
