### ISSUE TITLE
Encountered a LinkageError.（Using translation）

### ISSUE THREAD

**Issue by gzx7301** [dmulloy2/ProtocolLib#1097]
**Describe the bug**

>[06:35:28 WARN]: [ProtocolLib] Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!
> [06:35:28 WARN]: [ProtocolLib] If you're getting this error for other reasons, please report it!
> [06:35:28 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:297)
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
> [06:35:28 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
> [06:35:28 WARN]: at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:249)
> [06:35:28 WARN]: at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:181)
> [06:35:28 WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1324)
> [06:35:28 WARN]: at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:213)
> [06:35:28 WARN]: at net.minecraft.entity.EntityTrackerEntry.func_151261_b(EntityTrackerEntry.java:379)
> [06:35:28 WARN]: at net.minecraft.entity.EntityTrackerEntry.func_111190_b(EntityTrackerEntry.java:343)
> [06:35:28 WARN]: at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:292)
> [06:35:28 WARN]: at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:295)
> [06:35:28 WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:916)
> [06:35:28 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467)
> [06:35:28 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
> [06:35:28 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
> [06:35:28 WARN]: at java.lang.Thread.run(Thread.java:748)`

**To Reproduce**
1Enter the game and report an error.
2. 'open the backpack'
3. Click on 'ESC'
4.Game display
 `Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer`

**Expected behavior**
Close the backpack

**Screenshots**

**Version Info**
````
ProtocolLib Dump
Timestamp: 02/19/21 06:58:56

ProtocolLib Version: ProtocolLib v4.5.0
Bukkit Version: 1.12.2-R0.1-SNAPSHOT
Server Version: git-Mohist-1.12.2-185 (MC: 1.12.2)
Java Version: 1.8.0_275

ProtocolLib: com.comphenix.protocol.ProtocolLib@52eead07[
  statistics=com.comphenix.protocol.metrics.Statistics@4d1cda55
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@65fc7374
  packetTask=194
  tickCounter=314684
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4b9287be
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.BukkitUpdater@ebdde0d
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@25d873fd
  commandProtocol=com.comphenix.protocol.CommandProtocol@2339c3e1
  commandPacket=com.comphenix.protocol.CommandPacket@7c490f4f
  commandFilter=com.comphenix.protocol.CommandFilter@1c64fb7d
  packetLogging=com.comphenix.protocol.PacketLogging@7ac52497
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@178ed6e5
  server=CraftServer{serverName=Mohist,serverVersion=git-Mohist-1.12.2-185,minecraftVersion=1.12.2}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@180d3833
  dataFolder=plugins/ProtocolLib
  classLoader=org.bukkit.plugin.java.PluginClassLoader@5a89c5a3
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=org.bukkit.plugin.PluginLogger@2ae79845
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@34bd81f6[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4b9287be
  packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=3], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VirtualMenu, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=VirtualMenu, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@58287c6
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@13311283
  interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@51dde37d
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@9377a81
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@189a60d6
  hasClosed=false
  classLoader=org.bukkit.plugin.java.PluginClassLoader@5a89c5a3
  reporter=com.comphenix.protocol.ProtocolLib$1@324dc4c
  server=CraftServer{serverName=Mohist,serverVersion=git-Mohist-1.12.2-185,minecraftVersion=1.12.2}
  library=ProtocolLib v4.5.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3ddc015e
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=3
  packetCreation=false
  spigotInjector=<null>
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3c329302
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5fe496a5
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.12.2)
  loginPackets=com.comphenix.protocol.injector.LoginPackets@4dfbd2fa
  debug=false
]

Listeners:
com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1@e0fd24c[
  plugin=HolographicDisplays v2.2.6
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=3], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]]
]
com.blzeecraft.virtualmenu.packet.PacketCloseWindowHandler@5ecbd40e[
  manager=com.blzeecraft.virtualmenu.packet.PacketManager@186b49d9
  plugin=VirtualMenu v0.0.16-dev
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.blzeecraft.virtualmenu.packet.PacketWindowClickHandler@7e3bbc34[
  manager=com.blzeecraft.virtualmenu.packet.PacketManager@186b49d9
  plugin=VirtualMenu v0.0.16-dev
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
VirtualMenu by []
HolographicDisplays by []
```
**Additional context**
Add any other context about the problem here.

**Comment by gzx7301** [comment]
sorry  I think this is Version error  now  i ues Version 4.3.0 There is no exception
