### ISSUE TITLE
Plugin dont start

### ISSUE THREAD

**Issue by Daniellainand** [dmulloy2/ProtocolLib#1124]
If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:395)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:106)
        at org.bukkit.scheduler.BukkitRunnable.runTaskLater(BukkitRunnable.java:64)
        at com.comphenix.protocol.PacketType.scheduleRegister(PacketType.java:887)
        at com.comphenix.protocol.PacketType.fromCurrent(PacketType.java:798)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.associatePackets(NettyProtocolRegistry.java:207)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:94)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:308)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:211)
        at net.minecraft.server.v1_8_R3.MinecraftServer.startTickloop(MinecraftServer.java:871)
        at net.minecraft.server.v1_8_R3.MinecraftServer.<init>(MinecraftServer.java:169)
        at net.minecraft.server.v1_8_R3.DedicatedServer.<init>(DedicatedServer.java:46)
        at net.minecraft.server.v1_8_R3.MinecraftServer.main(MinecraftServer.java:1490)
        at org.bukkit.craftbukkit.Main.main(Main.java:368)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@37596b44[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@29ec5005
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@42ceb67f
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@52e44f71
      server=CraftServer{serverName=CraftBukkit,serverVersion=1.8.8-R0.2-RELEASE,minecraftVersion=1.8.8}
      file=plugins/ProtocolLib-4.6.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@653c0c9c
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@7cdb05aa
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@221961f2
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    1.8.0_282
  Server:
    1.8.8-R0.2-RELEASE (MC: 1.8.8)

**Comment by Daniellainand** [comment]
pls help me :C!

**Comment by dmulloy2** [comment]
Which CraftBukkit fork are you using?
