### ISSUE TITLE
ProtocolLib not loading

### ISSUE THREAD

**Issue by Inxity** [dmulloy2/ProtocolLib#1134]
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.PacketType$Play$Client
  	at com.comphenix.protocol.PacketType.getLookup(PacketType.java:602)
  	at com.comphenix.protocol.PacketType.fromCurrent(PacketType.java:786)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.associatePackets(NettyProtocolRegistry.java:207)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initializeNew(NettyProtocolRegistry.java:184)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:49)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
  	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:263)
  	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061)
  	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
  	at java.base/java.lang.Thread.run(Thread.java:834)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1f79a551[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2964c925
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6006a29b
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@59e19645
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1053,minecraftVersion=1.16.5}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4c23ead
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0-SNAPSHOT-b483, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@483a10f
    ]
  Version:
    ProtocolLib v4.6.0-SNAPSHOT-b483
  Java Version:
    11.0.10
  Server:
    git-Purpur-1053 (MC: 1.16.5)

**Comment by Inxity** [comment]
Forgot to update to latest version of ProtocolLib
