### ISSUE TITLE
Erro since last compile...of 1.8.8 2 days ago

### ISSUE THREAD

**Issue by CloudeLecaw** [dmulloy2/ProtocolLib#114]
Sinc ethat i get this error:
ProtocolLib is lastest jenkins...

[13:37:31] [Server thread/ERROR]: null
com.comphenix.protocol.reflect.FieldAccessException: No field with type [B exists in class PacketPlayOutCustomPayload.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:347) ~[ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:327) ~[ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at ru.mcreation.proxwian.hideitemattributes.Main$1.onPacketSending(Main.java:111) [HideItemAttributes_0.7.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:415) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:381) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:349) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.EntityPlayer.openTrade(EntityPlayer.java:720) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.EntityVillager.a(EntityVillager.java:136) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at me.austinlm.multitrade.VillagerTradeListener.fakeTrade(VillagerTradeListener.java:43) [Multitrade_1.0.1.jar:?]
        at me.austinlm.multitrade.VillagerTradeListener.handleRightClick(VillagerTradeListener.java:27) [Multitrade_1.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
[13:37:31] [Server thread/ERROR]: null
com.comphenix.protocol.reflect.FieldAccessException: No field with type [B exists in class PacketPlayOutCustomPayload.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:347) ~[ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:327) ~[ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at ru.mcreation.proxwian.hideitemattributes.Main$1.onPacketSending(Main.java:111) [HideItemAttributes_0.7.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:638) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:614) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:312) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:415) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:381) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:349) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib_3.6.5-Build196.jar:3.6.5-SNAPSHOT-b196]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.EntityPlayer.openTrade(EntityPlayer.java:720) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at com.nisovin.shopkeepers.compat.v1_8_R3.NMSHandler.openTradeWindow(NMSHandler.java:67) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.compat.v1_8_R3.NMSHandler.openTradeWindow(NMSHandler.java:79) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.ui.defaults.TradingHandler.openWindow(TradingHandler.java:54) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.ui.UIManager.requestUI(UIManager.java:67) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.Shopkeeper.openWindow(Shopkeeper.java:388) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.Shopkeeper.openTradingWindow(Shopkeeper.java:412) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.Shopkeeper.onPlayerInteraction(Shopkeeper.java:456) [Shopkeepers_1.63.jar:?]
        at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:53) [Shopkeepers_1.63.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]

**Comment by dmulloy2** [comment]
This is an error with
