### ISSUE TITLE
NoSuchMethodError java.util.Set com.comphenix.protocol.injector.packet.PacketRegistry.toPacketTypes(java.util.Set)

### ISSUE THREAD

**Issue by Xemorr** [dmulloy2/ProtocolLib#1145]
**Make sure you're doing the following**
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.
How do I fix this error?
`
java.lang.NoSuchMethodError: 'java.util.Set com.comphenix.protocol.injector.packet.PacketRegistry.toPacketTypes(java.util.Set)'
    at com.comphenix.protocol.events.ListeningWhitelist.<init>(ListeningWhitelist.java:96) ~[?:?]
    at com.comphenix.protocol.events.ListeningWhitelist.<clinit>(ListeningWhitelist.java:41) ~[?:?]
    at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:44) ~[?:?]
    at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:52) ~[?:?]
    at com.comphenix.protocol.events.PacketAdapter.<init>(PacketAdapter.java:104) ~[?:?]
    at me.xemor.itemglider.ItemGlider$1.<init>(ItemGlider.java:61) ~[?:?]
    at me.xemor.itemglider.ItemGlider.onEnable(ItemGlider.java:61) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-439]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-439]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-439]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-439]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-439]
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-439]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-439]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-439]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-439]
    at java.lang.Thread.run(Thread.java:834) [?:?]
`

**API method(s) used**
List what API method(s) you're using
ProtocolLibrary.getProtocolManager();
protocolManager.addPacketListener(PacketAdapter())
new PacketAdapter(this, ListenerPriority.NORMAL, PacketType.Play.Server.ENTITY_LOOK)

**Expected behavior**
My code would be executed and listen for the packets

**Code**
If applicable, add relevant code from your project
https://pastebin.com/giPa4Uvc

**Additional context**
I am writing this for 1.16.5, using a 1.16.5 paper server with ProtocolLib version 4.6.0

**Comment by Xemorr** [comment]
caused by another one of my plugins
