### ISSUE TITLE
(Fabric 1.16.5 with Cardboard) Error while loading

### ISSUE THREAD

**Issue by flaw9** [dmulloy2/ProtocolLib#1146]
**Describe the bug**
I got an error while loading the plugin

**To Reproduce**
1. I started my server running fabric 1.16.5 with the last version of the mod Cardboard.

**Expected behavior**
I expected the plugin to load ?! I don't know if this happend because of the mod or the plugin, but I think it's because the mod doesn't support everything Bukkit does atm. So if there's any way to fix this it would be very helpful.

**Version Info**
I used the last version (4.6.0)

Here is the error:
```
Stack Trace:
  java.lang.RuntimeException: Failed to find CraftBukkit class: entity.CraftPlayer
        at com.comphenix.protocol.utility.MinecraftReflection.lambda$getCraftBukkitClass$0(MinecraftReflection.java:2014)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:2014)
        at com.comphenix.protocol.utility.MinecraftReflection.getEntityPlayerClass(MinecraftReflection.java:588)
        at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1047)
        at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:375)
        at net.minecraft.class_3176.handler$zzb000$init(class_3176.java:741)
        at net.minecraft.class_3176.method_3823(class_3176.java:155)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@321632d[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1ee0b961
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@487cf60f
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@486e1377
      server=CraftServer{serverName=CardboardPowered.org,serverVersion=git-Bukkit4Fabric-1dd53b8,minecraftVersion=1.16.5}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5beeab97
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.javazilla.bukkitfabric.BukkitLogger@4cc0a226
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    11.0.9.1
  Server:
    git-Bukkit4Fabric-1dd53b8 (MC: 1.16.5)
```
Thanks.

**Comment by seymourgFF** [comment]
Hi, did you figure out what the problem was?
Share your solution how to run a server with plugins on fabric

**Comment by lukalt** [comment]
ProtocolLib is not designed to be run as a Fabric plugin. While the cardboard plugins enables loading of bukkit plugins (https://github.com/CardboardPowered/cardboard), it does not support the use of NMS code on which ProtocolLib heavily relies on. 
So you need to find another solution for accessing the Minecraft Protocol on Fabric
