### ISSUE TITLE
Java Version: 16.0.1

### ISSUE THREAD

**Issue by Chypik** [dmulloy2/ProtocolLib#1149]
An error occurred when starting the server for the first time

```
[22:00:04] [ProtocolLib-StructureCompiler 0/INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2e1aee2a) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1dc63586.
[22:00:04] [ProtocolLib-StructureCompiler 0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2e1aee2a
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@78885b93[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=float
      data=[public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3a20c5b6[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32da73d9
        packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=18], FLYING[class=PacketPlayInFlying, id=21], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WitherAC, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION[class=PacketPlayInPosition, id=18], FLYING[class=PacketPlayInFlying, id=21], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=TownyMenu, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WitherAC, sending=ListeningWhitelist[priority=NORMAL, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7], POSITION[class=PacketPlayInPosition, id=18], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], FLYING[class=PacketPlayInFlying, id=21], TRANSACTION[class=PacketPlayOutTransaction, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7], POSITION[class=PacketPlayInPosition, id=18], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], FLYING[class=PacketPlayInFlying, id=21], TRANSACTION[class=PacketPlayOutTransaction, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@b5b6c74
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3135ea4f
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@d0484aa
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6ca16a68
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@3cc99344
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-626,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@b389028
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=13
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@726100d5
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@74825aa5
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@1dc63586[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@d364f5c6=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@1ba34337], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@9f11ef55=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@61be9f3e], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@c95531e8=[com.comphenix.protocol.injector.StructureCache$1@70fa6de], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@764f7d20=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@2b49c9bc]}
      listenerLock=java.lang.Object@2a728d19
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@3f20b006
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@4563c86a
      reporter=com.comphenix.protocol.ProtocolLib$1@3cc99344
      unknownPermGenBean=java.lang.Object@2002fd53
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-626 (MC: 1.16.5)
```

**Comment by Chypik** [comment]
addition: after updating the plug-in, the error that was above disappeared, but when leaving the server it remained, maybe it's something from another opera, I'm not good at plugins, but when the player leaves the server, then the error goes to the console:

```
[21:06:32] [Craft Scheduler Thread - 10/INFO]: [AuthMe] Chypik logged in!
[21:06:44] [Server thread/INFO]: Chypik lost connection: Disconnected
[21:06:44] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.threadLocals accessible: module java.base does not "opens java.lang" to unnamed module @70e723f
[21:06:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[21:06:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[21:06:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[21:06:44] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[21:06:44] [Server thread/WARN]: 	at com.boydti.fawe.object.collection.CleanableThreadLocal.iterate(CleanableThreadLocal.java:94)
[21:06:44] [Server thread/WARN]: 	at com.boydti.fawe.object.collection.CleanableThreadLocal.getAll(CleanableThreadLocal.java:61)
[21:06:44] [Server thread/WARN]: 	at com.sk89q.worldedit.session.request.Request.getAll(Request.java:55)
[21:06:44] [Server thread/WARN]: 	at com.sk89q.worldedit.extension.platform.Actor.cancel(Actor.java:235)
[21:06:44] [Server thread/WARN]: 	at com.sk89q.worldedit.entity.Player.unregister(Player.java:403)
[21:06:44] [Server thread/WARN]: 	at com.sk89q.worldedit.bukkit.BukkitPlayer.unregister(BukkitPlayer.java:417)
[21:06:44] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:267)
[21:06:44] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor558.execute(Unknown Source)
[21:06:44] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:06:44] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:06:44] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:06:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:597)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1842)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:520)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:178)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1511)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
[21:06:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[21:06:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:06:44] [Server thread/INFO]: Chypik left the game
```

  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b499
  Java Version:
    16.0.1
  Server:
    git-Paper-626 (MC: 1.16.5)

**Comment by PimvanderLoos** [comment]
The second stacktrace is not related to ProtocolLib, as it is caused by FAWE, specifically this issue: IntellectualSites/FastAsyncWorldEdit#396

**Comment by Chypik** [comment]
> Вторая трассировка стека не связана с ProtocolLib, поскольку вызывается FAWE, а именно этой проблемой: [IntellectualSites / FastAsyncWorldEdit # 396](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/396)

Thank you. we will look for the legs of the problem there.
