### ISSUE TITLE
German? Wenn ich auf den Server draufgehe, werde ich gekickt für "Disconnected", ich weiß nicht wieso..

### ISSUE THREAD

**Issue by YTLolooo** [dmulloy2/ProtocolLib#1159]
[14:07:50] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.6.0
[14:07:50] [Server thread/INFO]: [ServerAPI] Disabling ServerAPI v1.0
[14:07:50] [Server thread/INFO]: [ServerAPI] Loading ServerAPI v1.0
[14:07:50] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.0
[14:07:50] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.0
[14:07:50] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[14:07:50] [Server thread/INFO]: [ServerAPI] Enabling ServerAPI v1.0
[14:07:50] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:07:50] [Server thread/INFO]: CONSOLE: [0;32;1mReload complete.[m
[14:07:55] [Netty Server IO #3/WARN]: Failed to initialize a channel. Closing: [id: 0x44cd26d1, /127.0.0.1:57242 => /127.0.0.1:25566]
java.lang.ExceptionInInitializerError
	at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:205) ~[?:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:155) ~[?:?]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.RuntimeException: Encountered an error caused by a reload! Please properly restart your server!
	at com.comphenix.protocol.injector.netty.ChannelInjector.<clinit>(ChannelInjector.java:96) ~[?:?]
	... 20 more
Caused by: java.lang.IllegalArgumentException: 'PROTOCOL-0' is already in use
	at io.netty.util.UniqueName.<init>(UniqueName.java:53) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.comphenix.protocol.injector.netty.ChannelInjector.<clinit>(ChannelInjector.java:94) ~[?:?]
	... 20 more
[14:07:55] [Netty Server IO #3/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
	at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:245) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:105) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[14:07:55] [Netty Server IO #0/WARN]: Failed to initialize a channel. Closing: [id: 0x271be361, /127.0.0.1:57243 => /127.0.0.1:25566]
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
	at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:205) ~[?:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:155) ~[?:?]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:412) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:251) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$3.channelRead(ProtocolInjector.java:181) [ProtocolLib.jar:4.6.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:92) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[14:07:55] [Netty Server IO #0/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
	at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:245) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:105) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[14:07:55] [Netty Server IO #1/WARN]: Failed to initialize a channel. Closing: [id: 0x23d641ae, /127.0.0.1:57244 => /127.0.0.1:25566]
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.injector.netty.ChannelInjector
	at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:205) ~[?:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:155) ~[?:?]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[14:07:55] [Netty Server IO #1/WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
	at net.minecraft.server.v1_8_R3.NetworkManager.close(NetworkManager.java:245) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.channelInactive(NetworkManager.java:105) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

**Comment by dmulloy2** [comment]
In general, reloading is not supported
