### ISSUE TITLE
TinyProtocol not working with late-bind

### ISSUE THREAD

**Issue by j0ach1mmall3** [dmulloy2/ProtocolLib#116]
Hey,
When turning late-bind on in the spigot.yml config (https://www.spigotmc.org/wiki/bbcode.397/archive), TinyProtocol will stop functioning.
Full error stacktrace:
java.lang.IllegalArgumentException: Cannot find field with type interface java.util.List
	at com.comphenix.tinyprotocol.Reflection.getField(Reflection.java:117) ~[?:?]
	at com.comphenix.tinyprotocol.Reflection.getField(Reflection.java:115) ~[?:?]
	at com.comphenix.tinyprotocol.Reflection.getField(Reflection.java:61) ~[?:?]
	at com.comphenix.tinyprotocol.TinyProtocol.registerChannelHandler(TinyProtocol.java:173) ~[?:?]
	at com.comphenix.tinyprotocol.TinyProtocol.<init>(TinyProtocol.java:81) ~[?:?]
TinyProtocol Class: http://pastebin.com/XwJcafsu
Reflection Class: http://pastebin.com/Rws3UJQZ
It would be greatly appreciated if you could fix this issue :)

**Comment by dmulloy2** [comment]
Interesting, I wonder if this is a problem in ProtocolLib too. I'll look into it.
