### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by darklightpuppet** [dmulloy2/ProtocolLib#1175]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [yes ] You're using the latest build for your server version
- [no] This isn't an issue caused by another plugin
- [ yes] You've checked for duplicate issues
- [ yes] You didn't use `/reload`

[19:08:51 INFO]: Darklightpuppet[/150.195.94.122:60335] logged in with entity id 409 at (536.595, 74, -518.868)
[19:08:51 INFO]: Syncing config to Darklightpuppet (937097fa-9257-48a5-946b-fdabc1c205b7)
[19:08:51 FATAL]: Preparing crash report with UUID 01f9942b-0121-4f72-af5f-3d0da6322c91
[19:08:51 ERROR]: Exception caught during firing event: Sending packet
        Index: 10
        Listeners:
                0: NORMAL
                1: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: ASM: class com.tiviacz.travelersbackpack.handlers.ForgeEventHandler playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                3: net.minecraftforge.eventbus.EventBus$$Lambda$2906/0x0000000800c15840@4fa70920
                4: ASM: class tictim.paraglider.event.ParagliderEventHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                5: ASM: net.minecraftforge.common.ForgeInternalHandler@65fc01fe playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                6: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: class twilightforest.TFEventListener playerLogsIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                9: ASM: class twilightforest.TFEventListener onClientConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                10: ASM: class harmonised.pmmo.events.EventHandler PlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                11: ASM: class corgitaco.enchancedcelestials.EnhancedCelestials$EnhancedCelestialsEvents onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                12: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                13: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@165b6a2c playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
net.minecraft.crash.ReportedException: Sending packet
        at net.minecraft.network.play.ServerPlayNetHandler.func_211148_a(ServerPlayNetHandler.java:1590)
        at net.minecraft.network.play.ServerPlayNetHandler.func_147359_a(ServerPlayNetHandler.java:1557)
        at net.minecraft.entity.player.ServerPlayerEntity.func_146105_b(ServerPlayerEntity.java:1411)
        at harmonised.pmmo.events.PlayerConnectedHandler.handlePlayerConnected(PlayerConnectedHandler.java:61)
        at harmonised.pmmo.events.EventHandler.PlayerLogin(EventHandler.java:75)
        at net.minecraftforge.eventbus.ASMEventHandler_278_EventHandler_PlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:339)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:171)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:73)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1055)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:301)
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434)
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71)
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374)
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344)
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:207)
        at net.minecraft.network.NetworkManager.func_201058_a(NetworkManager.java:179)
        at net.minecraft.network.play.ServerPlayNetHandler.func_211148_a(ServerPlayNetHandler.java:1583)
        ... 20 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 32 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayOutChat
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_server_SChatPacket$java_lang_Object.<init>(Unknown Source)
        ... 37 more

[19:08:51 WARN]: Failed to handle packet for /150.195.94.122:60335
[19:08:51 INFO]: Darklightpuppet lost connection: Internal server error
[19:08:51 INFO]: Darklightpuppet left the game

**Comment by dmulloy2** [comment]
Which Bukkit derivative are you using?
