### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by CormacZ** [dmulloy2/ProtocolLib#1180]
java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:237)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:312)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:221)
        ... 37 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInFlying$PacketPlayInPosition
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPlayerPacket_PositionPacket$java_lang_Object.<init>(Unknown Source)
        ... 41 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@23299957[
      memoryAddress=140585704861712
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@4bfa79d9
      chunk=Chunk(6ee5718d: 3%, 434176/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@5c3e1552
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3bfd1d1d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@25f44d54
        packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20], FLYING[class=PacketPlayInFlying, id=21]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20], FLYING[class=PacketPlayInFlying, id=21]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6f00721e
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3857f69a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6b911178
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6c087fb3
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@67575fe
        reporter=com.comphenix.protocol.ProtocolLib$1@790a50c
        server=CraftServer{serverName=Mohist,serverVersion=unknown,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4bb3709e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=7
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@150887fa
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@75cb8e35
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@54be6aad[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@78f4ba4a
      player=CraftPlayer{name=Abrar123456}
      updated=CraftPlayer{name=Abrar123456}
      playerName=Abrar123456
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@6901be54
      originalChannel=[id: 0x717261f1, L:/172.18.0.232:25768 - R:/46.19.139.106:33174]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@6901be54, previous=[id: 0x717261f1, L:/172.18.0.232:25768 - R:/46.19.139.106:33174], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@3694074c, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1aac0049
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@3d60eab3
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@da509a1
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@150887fa
      processor=com.comphenix.protocol.injector.NetworkProcessor@61c9245c
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@121d4976
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    11.0.9
  Server:
    unknown (MC: 1.16.5)

**Comment by dmulloy2** [comment]
Which Bukkit derivative are you using? It says unknown
