### ISSUE TITLE
Java 16 Problems Already

### ISSUE THREAD

**Issue by kiloRs** [dmulloy2/ProtocolLib#1190]
I am getting this:

`[23:30:24] [ProtocolLib-StructureCompiler 0/INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1854ff5c) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@7a0add73.
[23:30:24] [ProtocolLib-StructureCompiler 0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1854ff5c
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@71e5493e[
      targetType=class net.minecraft.server.v1_16_R3.NBTTagCompound
      target=<null>
      converter=<null>
      fieldType=interface java.util.Map
      data=[public final java.util.Map net.minecraft.server.v1_16_R3.NBTTagCompound.map]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7e302cca[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5c6f1d59
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=HIGH, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=88], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ANIMATION[class=PacketPlayOutAnimation, id=5], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7180353
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@d0c38a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7f79e926
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5bd8a645
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0-SNAPSHOT-b494, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@1c9d24f6
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1149,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0-SNAPSHOT-b494
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2ad782d9
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@768e48ef
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5d9cdcd5
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@7a0add73[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@9cd8da1=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@540617b2]}
      listenerLock=java.lang.Object@50cbe4ed
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@6b0ae055
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@47c75902
      reporter=com.comphenix.protocol.ProtocolLib$1@1c9d24f6
      unknownPermGenBean=java.lang.Object@23187dcf
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0-SNAPSHOT-b494
  Java Version:
    16.0.1
  Server:
    git-Purpur-1149 (MC: 1.16.5)
`

**Comment by molor** [comment]
If you would try to search for "Disabing compiler" in [closed] issues before posting this, you would save time for yourself and the developers..

**Comment by dmulloy2** [comment]
Been meaning to do a full release, but in the meantime, grab the latest dev build
