### ISSUE TITLE
Internal Error: Cannot compile Structure. Disabling Compiler

### ISSUE THREAD

**Issue by TheBudderBomb** [dmulloy2/ProtocolLib#1197]
Title of this issue pretty much explains what im looking at, it hasnt really caused an issue so far on my server but im sure with this being disabled its going to funk up my anticheat. 

The stacktrace just opens in my chat when I first log into the server after a restart

Heres the stacktrace:

[Tue, 8. Jun 2021 12:53:31 UTC ERROR] [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     If this problem hasn't already been reported, please open a ticket
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     Stack Trace:
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @198a6c59
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[Tue, 8. Jun 2021 12:53:31 UTC ERROR]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

And heres the link to the dump: 
http://dump-2021-06-08_13.15.31.txt

**Comment by TheBudderBomb** [comment]
sorry, im stupid, the link to the dump is : https://pastebin.com/txxvGGuH
