### ISSUE TITLE
I was on java 11 and switch to java 16 now im getting this issue

### ISSUE THREAD

**Issue by redrozay** [dmulloy2/ProtocolLib#1198]
**Make sure you're doing the following**
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

**Describe the question**
I was running 59 plugins on java 11 with protocol lib working great, then I switch to java 16 because my paper version and viaverision/viabackwards/viarewind all need the update to work. after I switched to java 16 and removed 1 unrelated plugin I got this console error saying to make a thread here. 

**API method(s) used**
not sure what this means 

**Expected behavior**
I didn't expect anything to happen but I got an error. maybe it was on my end but im not sure

**Code**
[19:07:51 INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @112400db) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@797a532c.
[19:07:51 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @112400db
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@4784bda7[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.EnumHand net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a, public long net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.timestamp]
      defaultFields={private net.minecraft.server.v1_16_R3.EnumHand net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a=0}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3483eead[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@34bb7be0
        packetListeners=[PacketAdapter[plugin=Spartan, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], TRANSACTION[class=PacketPlayInTransaction, id=7]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31], TRANSACTION[class=PacketPlayInTransaction, id=7]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WildStacker, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicExtension, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@632552
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6268c97c
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4935b51a
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@263eb3a7
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@3f6e5b87
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-769,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7f90ad2d
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=8
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4a159ec3
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@620a3270
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@797a532c[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@e6f59315=[com.comphenix.protocol.injector.StructureCache$1@7c480746]}
      listenerLock=java.lang.Object@1acd7d8a
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@29674511
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@2af8022
      reporter=com.comphenix.protocol.ProtocolLib$1@3f6e5b87
      unknownPermGenBean=java.lang.Object@3e61d506
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-769 (MC: 1.16.5)

**Additional context**

**Comment by Tiippex** [comment]
Try using the latest dev build:
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

That solved the same issue for me :)

**Comment by redrozay** [comment]
thank you it worked, I only have this error in console now, does anyone know what it means 



[02:26:07 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "org.inventivetalent.packetlistener.channel.ChannelAbstract.serverConnection" is null
[02:26:07 WARN]:        at org.inventivetalent.packetlistener.channel.ChannelAbstract.addServerChannel(ChannelAbstract.java:66)
[02:26:07 WARN]:        at org.inventivetalent.packetlistener.ChannelInjector.addServerChannel(ChannelInjector.java:55)
[02:26:07 WARN]:        at org.inventivetalent.packetlistener.PacketListenerAPI.load(PacketListenerAPI.java:32)
[02:26:07 WARN]:        at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:46)
[02:26:07 WARN]:        at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:117)
[02:26:07 WARN]:        at net.shortninja.staffplus.StaffPlus.onEnable(StaffPlus.java:144)
[02:26:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:26:07 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[02:26:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[02:26:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[02:26:07 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[02:26:07 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[02:26:07 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[02:26:07 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[02:26:07 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[02:26:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Schneidertm** [comment]
#1190
