### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by ALufkin24** [dmulloy2/ProtocolLib#1199]
This is the error I get when I added a 'negativity anti-cheat' plugin. It keeps saying disabling complier. Is there a way to fix this or is this a bug that the dev would have to fix?

 INFO Version: ProtocolLib v4.6.0
 INFO Java Version:16.0.1
 INFO Server: git-Paper-775 (MC: 1.16.5)

10.06 01:01:45 [Server] INFO Fetching all due players...
10.06 01:01:45 [Server] INFO Fetched due players (0 found).
10.06 01:02:15 [Server] INFO Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @73edb67a) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@52b71041.
10.06 01:02:15 [Server] ERROR INTERNAL ERROR: Cannot compile structure. Disabing compiler.
10.06 01:02:15 [Server] INFO If this problem hasn't already been reported, please open a ticket
10.06 01:02:15 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
10.06 01:02:15 [Server] INFO Stack Trace:
10.06 01:02:15 [Server] INFO java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @73edb67a
10.06 01:02:15 [Server] INFO at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
10.06 01:02:15 [Server] INFO at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
10.06 01:02:15 [Server] INFO at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
10.06 01:02:15 [Server] INFO at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
10.06 01:02:15 [Server] INFO at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
10.06 01:02:15 [Server] INFO at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
10.06 01:02:15 [Server] INFO at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
10.06 01:02:15 [Server] INFO at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10.06 01:02:15 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
10.06 01:02:15 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
10.06 01:02:15 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:831)
10.06 01:02:15 [Server] INFO Dump:
10.06 01:02:15 [Server] INFO Parameters: 
10.06 01:02:15 [Server] INFO com.comphenix.protocol.reflect.StructureModifier@7a5784cb[
10.06 01:02:15 [Server] INFO targetType=class net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol
10.06 01:02:15 [Server] INFO target=<null>
10.06 01:02:15 [Server] INFO converter=<null>
10.06 01:02:15 [Server] INFO fieldType=class java.lang.Object
10.06 01:02:15 [Server] INFO data=[private int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a, public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname, public int net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.port, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d]
10.06 01:02:15 [Server] INFO defaultFields={public java.lang.String net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.hostname=1, private net.minecraft.server.v1_16_R3.EnumProtocol net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.d=3}
10.06 01:02:15 [Server] INFO subtypeCache={}
10.06 01:02:15 [Server] INFO customConvertHandling=false
10.06 01:02:15 [Server] INFO useStructureCompiler=true
10.06 01:02:15 [Server] INFO ]
10.06 01:02:15 [Server] INFO manager:
10.06 01:02:15 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@495bd099[
10.06 01:02:15 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@59063e7f
10.06 01:02:15 [Server] INFO packetListeners=[PacketAdapter[plugin=Negativity, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], STRUCT[class=PacketPlayInStruct, id=42], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], SPECTATE[class=PacketPlayInSpectate, id=45], USE_ITEM[class=PacketPlayInUseItem, id=46], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], START[class=PacketStatusInStart, id=0], PING[class=PacketStatusInPing, id=1], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=25], ABILITIES[class=PacketPlayInAbilities, id=26], BOAT_MOVE[class=PacketPlayInBoatMove, id=23], PICK_ITEM[class=PacketPlayInPickItem, id=24], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=29], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], ITEM_NAME[class=PacketPlayInItemName, id=32], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], TR_SEL[class=PacketPlayInTrSel, id=35], BEACON[class=PacketPlayInBeacon, id=36], WINDOW_CLICK[class=PacketPlayInWindowClick, id=9], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10], TRANSACTION[class=PacketPlayInTransaction, id=7], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=8], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=13], USE_ENTITY[class=PacketPlayInUseEntity, id=14], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=11], B_EDIT[class=PacketPlayInBEdit, id=12], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=17], POSITION[class=PacketPlayInPosition, id=18], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=15], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16], FLYING[class=PacketPlayInFlying, id=21], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], LOOK[class=PacketPlayInLook, id=20], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], SETTINGS[class=PacketPlayInSettings, id=5], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], CHAT[class=PacketPlayInChat, id=3], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], START[class=PacketLoginInStart, id=0], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Negativity, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]]]
10.06 01:02:15 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@70ff6619
10.06 01:02:15 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@36c8d511
10.06 01:02:15 [Server] INFO inputBufferedPackets=[]
10.06 01:02:15 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@21800449
10.06 01:02:15 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@491d33c0
10.06 01:02:15 [Server] INFO hasClosed=false
10.06 01:02:15 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
10.06 01:02:15 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@42d95b54
10.06 01:02:15 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-775,minecraftVersion=1.16.5}
10.06 01:02:15 [Server] INFO library=ProtocolLib v4.6.0
10.06 01:02:15 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@13ca960f
10.06 01:02:15 [Server] INFO knowsServerPackets=true
10.06 01:02:15 [Server] INFO knowsClientPackets=true
10.06 01:02:15 [Server] INFO phaseLoginCount=1
10.06 01:02:15 [Server] INFO phasePlayingCount=5
10.06 01:02:15 [Server] INFO packetCreation=false
10.06 01:02:15 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@51d0cbb
10.06 01:02:15 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7f2a4d81
10.06 01:02:15 [Server] INFO hasRecycleDistance=true
10.06 01:02:15 [Server] INFO minecraftVersion=(MC: 1.16.5)
10.06 01:02:15 [Server] INFO debug=false
10.06 01:02:15 [Server] INFO ]
10.06 01:02:15 [Server] INFO Sender:
10.06 01:02:15 [Server] INFO com.comphenix.protocol.reflect.compiler.BackgroundCompiler@52b71041[
10.06 01:02:15 [Server] INFO listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@8c9c49cb=[com.comphenix.protocol.injector.StructureCache$1@14d1daf9], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@7fc725ce=[com.comphenix.protocol.injector.StructureCache$1@79c4740c]}
10.06 01:02:15 [Server] INFO listenerLock=java.lang.Object@542f78f0
10.06 01:02:15 [Server] INFO compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@3ef04f2c
10.06 01:02:15 [Server] INFO enabled=false
10.06 01:02:15 [Server] INFO shuttingDown=false
10.06 01:02:15 [Server] INFO executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@246c5c19
10.06 01:02:15 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@42d95b54
10.06 01:02:15 [Server] INFO unknownPermGenBean=java.lang.Object@7e52388c
10.06 01:02:15 [Server] INFO permGenBean=<null>
10.06 01:02:15 [Server] INFO disablePermGenFraction=0.65
10.06 01:02:15 [Server] INFO ]
10.06 01:02:15 [Server] INFO Version:
10.06 01:02:15 [Server] INFO ProtocolLib v4.6.0
10.06 01:02:15 [Server] INFO Java Version:
10.06 01:02:15 [Server] INFO 16.0.1
10.06 01:02:15 [Server] INFO Server:
10.06 01:02:15 [Server] INFO git-Paper-775 (MC: 1.16.5)

**Comment by ALufkin24** [comment]
I had to use another jar file which was a snapshot to fix it. I found the fix on another bug issue that was solved.
