### ISSUE TITLE
a little issue with the latest 1.17 version

### ISSUE THREAD

**Issue by CloudeLecaw** [dmulloy2/ProtocolLib#1202]
```
[08:35:09] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b499
[08:35:09] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.17.0) has not yet been tested! Proceed with caution.
[08:35:11] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.EntityLiving}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.EntityLiving instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@28904ec[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@57005017
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@72aaf8df
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@2f843d9
      server=CraftServer{serverName=CraftBukkit,serverVersion=3100-Spigot-c9cea60-5182f92,minecraftVersion=1.17}
      file=plugins\ProtocolLib_4.6.0-Build499.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1d49e8f2
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@7a2abcce
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@7826fdc6
    ]
  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b499
  Java Version:
    16.0.1
  Server:
    3100-Spigot-c9cea60-5182f92 (MC: 1.17)
```

**Comment by bigfinfrank** [comment]
Same thing with b505
```[09:33:32] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b505
[09:33:32] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.17.0) has not yet been tested! Proceed with caution.
[09:33:33] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@16ea28d6[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2b6a355f
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@b8acef2
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@1bb36a3c
      server=CraftServer{serverName=CraftBukkit,serverVersion=3109-Spigot-191e497-74575d4,minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@26e25b1d
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@55627378
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@7b209bb3
    ]
  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b505
  Java Version:
    16.0.1
  Server:
    3109-Spigot-191e497-74575d4 (MC: 1.17)
```

**Comment by Zao-chen** [comment]
me too!minecraft 1.17 and jdk16
use b505
[21:57:42] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at pw.yumc.Yum.managers.PluginsManager.load(PluginsManager.java:348)
        at pw.yumc.Yum.managers.PluginsManager.load(PluginsManager.java:406)
        at pw.yumc.Yum.managers.PluginsManager.reload(PluginsManager.java:441)
        at pw.yumc.Yum.commands.YumCommand.reload(YumCommand.java:323)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at pw.yumc.Yum.commands.info.CommandInfo.lambda$execute$0(CommandInfo.java:135)
        at pw.yumc.Yum.commands.info.CommandInfo.execute(CommandInfo.java:148)
        at pw.yumc.Yum.commands.CommandSub.onCommand(CommandSub.java:193)
        at pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:749)
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:473)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:437)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1199)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1026)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@ff521cb[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@784388be
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3a4b1801
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@6bcd2e5e
      server=CraftServer{serverName=CraftBukkit,serverVersion=3111-Spigot-66f9d3c-cbf2f67,minecraftVersion=1.17}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6221512
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@3ae42ee2
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@441dfdad
    ]
  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b505
  Java Version:
    16.0.1
  Server:
    3111-Spigot-66f9d3c-cbf2f67 (MC: 1.17)
[21:57:42] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.1-SNAPSHOT-b505

**Comment by Carbuino** [comment]
Same issue here Spigot 1.17, JDK 16
```
[12:13:10] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b505
[12:13:10] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.17.0) has not yet been tested! Proceed with caution.
[12:13:11] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1d053183[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@63457cfe
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@40999413
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@66d45ad6
      server=CraftServer{serverName=CraftBukkit,serverVersion=3111-Spigot-66f9d3c-cbf2f67,minecraftVersion=1.17}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1a83d299
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@4957e83c
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@52f00e3c
    ]
  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b505
  Java Version:
    16
  Server:
    3111-Spigot-66f9d3c-cbf2f67 (MC: 1.17)
    ```

**Comment by 4drian3d** [comment]
ProtocolLib is NOT yet compatible with Minecraft/Spigot 1.17. Please, before upgrading your servers, check that ALL your plugins are compatible and working properly. For the supposed Java 16 issue, yes it is compatible.

**Comment by CloudeLecaw** [comment]
This is the reason why we ask for a S1.17 version^^

**Comment by 4drian3d** [comment]
So, it is not some "bug" as described. It is lack of patience, ProtocolLib has not yet updated to version 1.17, and you should know that before upgrading to a very early version of 1.17 which is still quite unstable.
It clearly indicates: [ProtocolLib] Version (MC: 1.17.0) has not yet been tested! Proceed with caution.

**Comment by Rothes** [comment]
Actually it's caused by JAVA16 reflection, however, ProtocolLib is not compatible it. yes.

**Comment by AxlRose-RX** [comment]
can it be made compatible? :D pretty please

**Comment by CloudeLecaw** [comment]
> can it be made compatible? :D pretty please

Well we all Hope for a little patch ;)
It was more as information at migt help the devs to see where they need to do something.

**Comment by Kiryu144** [comment]
> Actually it's caused by JAVA16 reflection, however, ProtocolLib is not compatible it. yes.

The error sounds more like some internal code changes of minecraft.

**Comment by bigfinfrank** [comment]
> Actually it's caused by JAVA16 reflection, however, ProtocolLib is not compatible it. yes.

Still happens with `--illegal-access=debug`.

**Comment by dmulloy2** [comment]
See #1209

**Comment by CloudeLecaw** [comment]
Roses are red. reflection may hit. you shall not use. --illegal-access=permit  ;D

**Comment by CloudeLecaw** [comment]
There is a build 507 outsite for spigot 1.17 :)
