### ISSUE TITLE
Minecraft 1.17 support

### ISSUE THREAD

**Issue by dmulloy2** [dmulloy2/ProtocolLib#1209]
Hi all!

The initial part of updating to 1.17 is complete. 1.17 contained a lot of changes to NMS, which required a lot of changes in ProtocolLib. Note that, although the unit tests are passing and things seemed to work well in my testing, there still may be bugs. Please report them on GitHub. Make sure to search first and 👍 any issues you also have.

Developers: I tried to keep the public API as consistent as possible, but I would strongly recommend changing any uses of `packet.getDimensions()` with `packet.getDimensionTypes()`. The version was also bumped to `4.7.0-SNAPSHOT`. Maven will hopefully start downloading source and javadoc jars with this release as well.

Lastly, thank you all for the support and patience. As you're probably aware, new MC updates are tough. Thanks to all my sponsors (there's somehow 8 of y'all which is insane) and all the one-time donors. I really appreciate y'all.

With all that said, here's the download: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by AxlRose-RX** [comment]
I will be the first one to download 🗡️

**Comment by TNTUP** [comment]
> I will be the first one to download 🗡️

Are you sure? 😉 Bots might hop on them first :(

**Comment by SlimeDog** [comment]
My automagical update-checker is pretty fast, but I don't care about first. Same minute is good enough.

**Comment by AxlRose-RX** [comment]
is it possible to release it today for a good donation? 👯‍♀️

**Comment by SlimeDog** [comment]
Donate anyway, then wait for the unit tests to pass. Why would you want it at 52/113 ?

**Comment by AxlRose-RX** [comment]
just so my global chat work on the 1.17 server :D Venture plugin depends on ProtocolLib and is the only server isolated right now :D and not switching chat plugin again lol

**Comment by SlimeDog** [comment]
We have 10 plugins that depend on ProtocolLib, plus 7 soft depend.

**Comment by dmulloy2** [comment]
Sadly I wouldn't expect anything super quickly. Mojang has been at work cleaning up their code, so I'm gonna have to get creative with stuff

**Comment by SlimeDog** [comment]
Good luck.

**Comment by retrooper** [comment]
Just wait till you start updating some of the packet-wrappers 💀

**Comment by retrooper** [comment]
some might be nightmares..

**Comment by retrooper** [comment]
Just a heads up, PacketPlayInUseEntity is painful to support

**Comment by VanillaChan6571** [comment]
Oh boy. Here we are at windows update for 95% complete and it's gonna take forever lol. For real tho very nice and good luck!

**Comment by EuanM199** [comment]
much love to @dmulloy2 for dealing with the pain of the MC updates. cannot wait for it to be out

**Comment by TMKCRepo** [comment]
Can't WAIT until 1.17 release. I really wanna make that 1.17 SMP server, but most of the plugins I use requires ProtocolLib.


> My automagical update-checker is pretty fast, but I don't care about first. Same minute is good enough.

My automatic update-checker is pretty fast, but I don't care, same minute is good enough.
(fixed grammar issues)

**Comment by SlimeDog** [comment]
`automagical` was intended. Leave my language alone.

**Comment by Effendil** [comment]
Do the 1.17-Update of Protocollib as Premium and the Dev can feel like Scrooge McDuck XD.

**Comment by Intriguing-RC** [comment]
Thank you so much for your hard work! <3

**Comment by libraryaddict** [comment]
Is this version supposed to be backwards compatible?

Getting an error with ProtocolLib trying to access the 1.17 mappings on a 1.12 server.

https://gist.github.com/559996aa1a329663b8b88de4c02a4f90

**Comment by dmulloy2** [comment]
@libraryaddict Not currently. Going to work on that in the next few days

**Comment by LOOHP** [comment]
Using boardcast packet (packet, entity, filter) seems to throw errors related to not being able to find a method or field of the EntityTracker.

sendServerPacket has no problems.

**Comment by dmulloy2** [comment]
@LOOHP can you make a separate issue for that? I'll take a look

**Comment by ErythroCraft** [comment]
[17:25:31] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0-SNAPSHOT-b507

[17:25:36] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0-SNAPSHOT-b507
[17:25:36] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.

works fine

**Comment by retrooper** [comment]
Hey dmulloy2, is there anything you need help with while upgrading to 1.17? I don't just wanna start working on a PR and realize you've been working on the same thing.

**Comment by dmulloy2** [comment]
@retrooper only things i can think of:
* bug with entity tracker
* backwards compat
* improve cloning speed 

if any of those sound interesting

**Comment by retrooper** [comment]
Curious, have you managed to find a solution for getting entities by their id asynchronously on 1.17?

**Comment by retrooper** [comment]
NMS has a map and we could use a method to access entities by their ID. If the entity hadn’t been cached by their ID, I would iterate through all entities on the server.(rare) On 1.17 it seems like its NEVER cached, and they throw an exception when you call getEntities() asynchronously.

**Comment by LOOHP** [comment]
It seems to be possible by getting invoking what `getEntities()` would invoke by yourself, tho not sure if it is safe.

**Comment by retrooper** [comment]
I deleted my previous message as I saw he updated his entity tracker, I might check it out.

**Comment by retrooper** [comment]
Didnt expect such a quick response lol

**Comment by AxlRose-RX** [comment]
awesome! fastutil on #510! now I get less errors on other plugins 🗡️ 

[18:35:38 ERROR]: Error occurred while enabling VentureChat v2.22.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedChatComponent
        at mineverse.Aust1n46.chat.utilities.Format.createPacketPlayOutChat(Format.java:471) ~[?:?]
        at mineverse.Aust1n46.chat.command.chat.Edit.<init>(Edit.java:24) ~[?:?]
        at mineverse.Aust1n46.chat.command.VentureCommandExecutor.initialize(VentureCommandExecutor.java:85) ~[?:?]
        at mineverse.Aust1n46.chat.MineverseChat.onEnable(MineverseChat.java:152) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:642) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:303) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.WrappedChatComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[Paper-Server-1.17-R0.1-SNAPSHOT-all.jar:git-Paper-"cd8f24d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 14 more
[18:35:38 INFO]: [VentureChat] Disabling VentureChat v2.22.8

**Comment by AxlRose-RX** [comment]
wow with latest build tons of my plugins are working now! thank you so much @dmulloy2!

**Comment by MaksymSemenykhin** [comment]
Is there are ticker for `Error Cannot enable ProtocolLib` or i can post problem right here?
