### ISSUE TITLE
No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutBoss

### ISSUE THREAD

**Issue by Rothes** [dmulloy2/ProtocolLib#1219]
**Describe the bug**
ProtocolLib has some problem with getChatComponents in Packet.Play.Out.Boss

**To Reproduce**
1. Use ProtocolLib v4.7.0-SNAPSHOT-b507
2. Use the same plugins that runs in 1.16 with no exception and listens on PacketType.Play.Server.BOSS
3. See error

**Expected behavior**
It should get the ChatComponents, not size 0.

**Screenshots**
N/A

**Version Info**
https://paste.ubuntu.com/p/JcKdHmkN6v/

**Additional context**
StackTrace:
```
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.network.chat.IChatBaseComponent exists in class PacketPlayOutBoss.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at me.Rothes.ProtocolStringReplacer.PacketListeners.Server.BossBar$1.onPacketSending(BossBar.java:22) ~[ProtocolStringReplacer%20v1.1.12-beta.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib_1.17.jar:4.7.0-SNAPSHOT-b507]
	at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1708) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1694) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.BossBattleServer.sendUpdate(SourceFile:88) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.BossBattleServer.setProgress(SourceFile:29) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.boss.wither.EntityWither.mobTick(EntityWither.java:249) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.EntityInsentient.doTick(EntityInsentient.java:812) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.EntityLiving.movementTick(EntityLiving.java:3076) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.EntityInsentient.movementTick(EntityInsentient.java:607) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.monster.EntityMonster.movementTick(SourceFile:43) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.boss.wither.EntityWither.movementTick(EntityWither.java:185) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.EntityLiving.tick(EntityLiving.java:2805) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.entity.EntityInsentient.tick(EntityInsentient.java:375) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:815) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.WorldServer$$Lambda$5662/0x00000000f6b9ec08.accept(Unknown Source) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.level.World.a(World.java:692) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.WorldServer.lambda$11(WorldServer.java:527) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.WorldServer$$Lambda$5661/0x00000000f6b9e940.accept(Unknown Source) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:508) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1297) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at net.minecraft.server.MinecraftServer$$Lambda$3789/0x00000000e668d940.run(Unknown Source) [spigot-1.17.jar:3145-Spigot-9472b09-f992ce6]
	at java.lang.Thread.run(Thread.java:853) [?:?]
```

**Comment by dmulloy2** [comment]
The underlying packet changed, this isn’t a PL issue
