### ISSUE TITLE
1.17 console starting warnings

### ISSUE THREAD

**Issue by comonier** [dmulloy2/ProtocolLib#1220]
[14:44:23] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.0
[14:44:23] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.17.0) has not yet been tested! Proceed with caution.
[14:44:25] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.EntityLiving}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.EntityLiving instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@6ef3c498[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3438a53e
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4e1063e6
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@34adc5fe
      server=CraftServer{serverName=CraftBukkit,serverVersion=3145-Spigot-9472b09-f992ce6,minecraftVersion=1.17}
      file=plugins/ProtocolLib#4.6.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@356a5c1d
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@3c20dfc3
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@2270becb
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    3145-Spigot-9472b09-f992ce6 (MC: 1.17)

**Comment by dmulloy2** [comment]
Update to the latest dev build
