### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by BinJankoDE** [dmulloy2/ProtocolLib#1240]
[23:14:34] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@6848b3d6[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6261151a
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@567eec76
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@64b06b13
      server=CraftServer{serverName=CraftBukkit,serverVersion=3145-Spigot-9472b09-f992ce6,minecraftVersion=1.17}
      file=plugins/ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@23e8a7b6
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@12e7bd4b
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@655be94b
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    3145-Spigot-9472b09-f992ce6 (MC: 1.17)
    
    
    
    What is the Problem?

**Comment by Redlnn** [comment]
Same with Paperclip Sever

```
[12:42:23 INFO]: This server is running Paper version git-Paper-"ce66102" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
[12:42:28 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to find network.EnumProtocol (EnumProtocol)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2083)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:759)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@4a9e66f[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7521fd34
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2c1ee6a2
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@168d332c
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"ce66102",minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@27eebbde
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0-SNAPSHOT-b507, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@3753a8b
    ]
  Version:
    ProtocolLib v4.7.0-SNAPSHOT-b507
  Java Version:
    16.0.1
  Server:
    git-Paper-"ce66102" (MC: 1.17)

[12:42:30 INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0-SNAPSHOT-b507
[12:42:30 ERROR]: ******************************************************
[12:42:30 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[12:42:30 ERROR]: *** Please use the built-in reload command!        ***
[12:42:30 ERROR]: ******************************************************
[12:42:30 INFO]: [ProtocolLib] Disabling ProtocolLib v4.7.0-SNAPSHOT-b507
```

**Comment by derklaro** [comment]
Does it still happen with build 516?

**Comment by Redlnn** [comment]
> Does it still happen with build 516?

No, it won't happen anymore, thanks
