### ISSUE TITLE
Spreadning a big chunk of error/warning in console when player joins

### ISSUE THREAD

**Issue by TheJoshue** [dmulloy2/ProtocolLib#1243]
**Describe the bug**
Joining the server spreads a big chunk of error/warning in console and spams even more if BlockParticles is used on server (infinite console spam).

**To Reproduce**
1. Start 1.8.8 server
2. Join 1.8.8 server
3. See error

**Expected behavior**
Work without these spams

**Version Info**
ProtocolLib latest release on spigotmc (4.6.0 for 1.8-1.16)

**Additional context**
```[14:23:42 INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5393678c) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6ea18e68.
[14:23:42 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5393678c
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@61ab5e55[
      targetType=class net.minecraft.server.v1_8_R3.PacketPlayOutChat
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_8_R3.IChatBaseComponent net.minecraft.server.v1_8_R3.PacketPlayOutChat.a, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_8_R3.PacketPlayOutChat.components, private byte net.minecraft.server.v1_8_R3.PacketPlayOutChat.b]
      defaultFields={public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_8_R3.PacketPlayOutChat.components=1}
      subtypeCache={class java.util.UUID=StructureModifier[fieldType=class java.util.UUID, data=[]]}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3167d12f[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3bbce921
        packetListeners=[PacketAdapter[plugin=ChatControl, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicExtension, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ChatControl, sending=ListeningWhitelist[priority=LOW, packets=[CHAT[class=PacketPlayOutChat, id=14]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@de51f5
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@44aa5f3
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@babf2fc
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5702f749
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@3f57b6eb
        reporter=com.comphenix.protocol.ProtocolLib$1@252145a5
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-"dc9ec3fd",minecraftVersion=1.8.8}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@207d29b3
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5ad867be
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1346d1c5
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6ea18e68[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@bb6b19bf=[com.comphenix.protocol.injector.StructureCache$1@723ab0d0], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@b80d89da=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@6b46dcbe]}
      listenerLock=java.lang.Object@4eabe0ea
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@2c9bf599
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@b006cea
      reporter=com.comphenix.protocol.ProtocolLib$1@252145a5
      unknownPermGenBean=java.lang.Object@56fef218
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-PaperSpigot-"dc9ec3fd" (MC: 1.8.8)```

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
