### ISSUE TITLE
Cannot load at all

### ISSUE THREAD

**Issue by CoderStone** [dmulloy2/ProtocolLib#1248]
**Describe the bug**
Cannot even load protocolib, throws error on load

**To Reproduce**
Install latest version of PaperSpigot and install the latest version of protocolib
**Expected behavior**
Loads and works.

**Screenshots**
 java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
  }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@336fcbb1[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4e13475e
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6c00d740
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@1263b8e1
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"6dfe049",minecraftVersion=1.17}
      file=plugins/ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@be14e45
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins/ProtocolLib (1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@6e9a2ac9
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-"6dfe049" (MC: 1.17)

**Version Info**
4.6.0, plugin doesn't even load

**Comment by derklaro** [comment]
Please use the latest build from the ci for 1.17 compat

**Comment by Foenixe** [comment]
Already posted #1247

**Comment by LoneDev6** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
