### ISSUE TITLE
Could not use StreamSerializer in 1.8.8

### ISSUE THREAD

**Issue by a810587921** [dmulloy2/ProtocolLib#125]
Could not use deserializeItemStack(String input)

ProtocolLib Version: 3.6.4

[18:15:43] [Server thread/WARN]: java.lang.RuntimeException: An internal error occured.
[18:15:43] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[18:15:43] [Server thread/WARN]: 	at com.comphenix.protocol.utility.StreamSerializer.deserializeItemStack(StreamSerializer.java:115)
[18:15:43] [Server thread/WARN]: 	at com.comphenix.protocol.utility.StreamSerializer.deserializeItemStack(StreamSerializer.java:241)
[18:15:43] [Server thread/WARN]: 	at com.github.a810587921.ItemSql.Mysql.getItem(Mysql.java:212)
[18:15:43] [Server thread/WARN]: 	at com.github.a810587921.ItemSql.ItemSql.onCommand(ItemSql.java:118)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[18:15:43] [Server thread/WARN]: 	at org.digiplex.bukkitplugin.commander.scripting.lines.ScriptCommandLine.execute(ScriptCommandLine.java:38)
[18:15:43] [Server thread/WARN]: 	at org.digiplex.bukkitplugin.commander.replacement.ReplacementCommand.executeEffects(ReplacementCommand.java:33)
[18:15:43] [Server thread/WARN]: 	at org.digiplex.bukkitplugin.commander.module.PlayerCommandModule.onPlayerCommandPreprocess(PlayerCommandModule.java:62)
[18:15:43] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:43] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:15:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:15:43] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[18:15:43] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[18:15:43] [Server thread/WARN]: Caused by: java.io.IOException: Root tag must be a named compound tag
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:58)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDataSerializer.h(PacketDataSerializer.java:162)
[18:15:43] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketDataSerializer.i(PacketDataSerializer.java:197)
[18:15:43] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:43] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:15:43] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[18:15:43] [Server thread/WARN]: 	... 31 more

**Comment by themazim** [comment]
I Think this is realted to https://github.com/dmulloy2/ProtocolLib/issues/31

**Comment by dmulloy2** [comment]
Yeah it's basically the same issue. I can't seem to figure out a good solution for it though :/
