### ISSUE TITLE
1.17 - PotionEffectType error "Unable to find method fromId"

### ISSUE THREAD

**Issue by LoneDev6** [dmulloy2/ProtocolLib#1250]
```
java.lang.IllegalArgumentException: Unable to find method fromId ([int]) in class net.minecraft.world.effect.MobEffectList.
        at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:87) ~[?:?]
        at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:86) ~[?:?]
        at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:70) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.Accessors.getMethodAccessor(Accessors.java:243) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$20.getGeneric(BukkitConverters.java:1211) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$20.getGeneric(BukkitConverters.java:1200) ~[?:?]
        at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:47) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
```

Code:
```java
PacketContainer container = new PacketContainer(PacketType.Play.Server.REMOVE_ENTITY_EFFECT);
        container.getIntegers().write(0, player.getEntityId());
        container.getEffectTypes().write(0, PotionEffectType.SLOW_DIGGING); // <---- exception here
```

`This server is running Paper version git-Paper-"10e9c5a" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`

`ProtocolLib version 4.7.0-SNAPSHOT-b520`

**Comment by LoneDev6** [comment]
On normal Spigot seems to work fine
