### ISSUE TITLE
A little issues with the plugin wraith in 1.17

### ISSUE THREAD

**Issue by CloudeLecaw** [dmulloy2/ProtocolLib#1255]
The plugin wraith does not load. The issues is shown onnstartup.
It might need some uodate for 1.17, but because of the longer error with protocollib i also post it here, may some code is missing?
Well the error also suggest me to report here, so i do :)

**To Reproduce**
Start the plguin wraith in 1.17 papermc
```
14:52:24] [Server thread/INFO]: [Wraith] Enabling Wraith v2.2.3
[14:52:25] [Server thread/INFO]: ???????
[14:52:25] [Server thread/INFO]: ???????
[14:52:25] [Server thread/INFO]: ??????? Wraith > haunts every hacker
[14:52:25] [Server thread/INFO]: ??????? Version: 2.2.3
[14:52:25] [Server thread/INFO]: ???????
[14:52:25] [Server thread/WARN]: [Wraith] It's advised to install PacketLimiter to block packet spam and lag (nuke, crashers...). Download: https://bit.ly/wrpacklim
[14:52:25] [Thread-15/WARN]: [PermissionsEx] The updater could not find any files for the project id 31279
[14:52:25] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [Wraith] Unsupported client packet in current Minecraft version: TRANSACTION[PLAY, CLIENT, 255, classNames: [net.minecraft.network.protocol.game.PacketPlayInTransaction, net.minecraft.network.protocol.game.ServerboundTransactionPacket, net.minecraft.network.play.client.CPacketConfirmTransaction] (unregistered)]
[14:52:25] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [Wraith] Unsupported server packet in current Minecraft version: TRANSACTION[PLAY, SERVER, 246, classNames: [net.minecraft.network.protocol.game.PacketPlayOutTransaction, net.minecraft.network.protocol.game.ClientboundTransactionPacket, net.minecraft.network.play.server.SPacketConfirmTransaction] (unregistered)]
[14:52:25] [Server thread/INFO]: [Wraith] Found version v1_17_R1
[14:52:25] [Server thread/ERROR]: Error occurred while enabling Wraith v2.2.3 (Is it up to date?)
java.lang.RuntimeException: Failed to find EntityPlayer class
	at dev.lone.wraith.OtherPlugins.net.badlion.blcmodapibukkit.a.a.<init>(SourceFile:79) ~[?:?]
	at dev.lone.wraith.OtherPlugins.net.badlion.blcmodapibukkit.a.a(SourceFile:44) ~[?:?]
	at dev.lone.wraith.b.a.b.f.<init>(SourceFile:119) ~[?:?]
	at dev.lone.wraith.b.d.a(SourceFile:77) ~[?:?]
	at dev.lone.wraith.Main.onEnable(SourceFile:359) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"1830de5"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[14:52:25] [Server thread/INFO]: [Wraith] Disabling Wraith v2.2.3
[14:52:25] [Server thread/INFO]: Error Unable to handle disabled plugin. (java.lang.IllegalArgumentException: value already present: null) occured in com.comphenix.protocol.injector.PacketFilterManager@13003970.
[14:52:25] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to handle disabled plugin.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: value already present: null
  	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287)
  	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry._associate(ProtocolRegistry.java:118)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:177)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:139)
  	at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82)
  	at com.comphenix.protocol.concurrency.PacketTypeSet.removeType(PacketTypeSet.java:58)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.removePacketHandler(ProtocolInjector.java:399)
  	at com.comphenix.protocol.injector.PacketFilterManager.disablePacketFilters(PacketFilterManager.java:601)
  	at com.comphenix.protocol.injector.PacketFilterManager.removePacketListener(PacketFilterManager.java:486)
  	at com.comphenix.protocol.injector.PacketFilterManager.removePacketListeners(PacketFilterManager.java:498)
  	at com.comphenix.protocol.injector.PacketFilterManager.onPluginDisabled(PacketFilterManager.java:957)
  	at com.comphenix.protocol.injector.PacketFilterManager.access$600(PacketFilterManager.java:71)
  	at com.comphenix.protocol.injector.PacketFilterManager$3.onPluginDisabled(PacketFilterManager.java:913)
  	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
  	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
  	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
  	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
  	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
  	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
  	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:303)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    org.bukkit.event.server.PluginDisableEvent@62ffa698[
      plugin=Wraith v2.2.3
      name=<null>
      async=false
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@13003970[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@c5496ee
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5c241192
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@20c5091a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@321c6fcb
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1ad77c80
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0-SNAPSHOT-b520, pluginEnabled=true, url=plugins\ProtocolLib_4.6.0-Build520.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@668346c9
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-"1830de5",minecraftVersion=1.17}
        library=ProtocolLib v4.7.0-SNAPSHOT-b520
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3fb556f6
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@29d7e73e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@fa1dc16
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.17.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.PacketFilterManager@13003970[
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@c5496ee
      packetListeners=[]
      packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5c241192
      playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@20c5091a
      inputBufferedPackets=[]
      recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@321c6fcb
      sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1ad77c80
      hasClosed=false
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0-SNAPSHOT-b520, pluginEnabled=true, url=plugins\ProtocolLib_4.6.0-Build520.jar}
      reporter=com.comphenix.protocol.ProtocolLib$1@668346c9
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"1830de5",minecraftVersion=1.17}
      library=ProtocolLib v4.7.0-SNAPSHOT-b520
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3fb556f6
      knowsServerPackets=true
      knowsClientPackets=true
      phaseLoginCount=0
      phasePlayingCount=0
      packetCreation=false
      nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@29d7e73e
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@fa1dc16
      hasRecycleDistance=true
      minecraftVersion=(MC: 1.17.0)
      debug=false
    ]
  Version:
    ProtocolLib v4.7.0-SNAPSHOT-b520
  Java Version:
    16.0.1
  Server:
    git-Paper-"1830de5" (MC: 1.17)
```

**Expected behavior**
Well the plguin should load or not throw this error about protocollib..

**Version Info**
4.7.0 Build 520

**Additional context**

**Comment by dmulloy2** [comment]
Wraith is out of date, but there's also a ProtocolLib issue in there. I'll get a fix for that tomorrow

**Comment by ChrissW-R1** [comment]
I have a similar, but not the same error:

`[Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:275)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@6453e732[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4530e25f
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@5bceb16a
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@2c33096b
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"f110140",minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@15423319
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@fe5ab75
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-"f110140" (MC: 1.17)`

**Comment by CloudeLecaw** [comment]
Your notnusing Build 521 from the Jenkins
Go to spigot, klick on the links for the dev builds for 1.17 and try it aggain.

**Comment by ChrissW-R1** [comment]
Thanks. With the newest build 522 it works fine.
