### ISSUE TITLE
 Error Cannot enable ProtocolLib. (java.lang.RuntimeException: Unable to inject channel futures.) occured in ProtocolLib v4.6.0.

### ISSUE THREAD

**Issue by KungfuEpt** [dmulloy2/ProtocolLib#1262]
**Describe the bug**
Im just download ProtocolLib for IllegalStack

**To Reproduce**
[13:11:18 INFO]: Error Cannot enable ProtocolLib. (java.lang.RuntimeException: Unable to inject channel futures.) occured in ProtocolLib v4.6.0.
[13:11:18 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to inject channel futures.
        at com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:223)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:887)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:285)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1121)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
  }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
        at com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1416)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:120)
        ... 11 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5d87b33b[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7804eb7c
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5ad261d4
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@459052f3
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@256e2f11
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7a6e6fcb
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@74bba6c5
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1182,minecraftVersion=1.17}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@29e02a17
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@287df676
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1737b381
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.17.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@f672f4e[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@486eb692
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7804eb7c
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@62efafa5
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@19b230f1
      commandProtocol=com.comphenix.protocol.CommandProtocol@2f1971d6
      commandPacket=com.comphenix.protocol.CommandPacket@12fe9881
      commandFilter=com.comphenix.protocol.CommandFilter@d739ffc
      packetLogging=com.comphenix.protocol.PacketLogging@5ce031b
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@613d55b5
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1182,minecraftVersion=1.17}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@761f383
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@635f0ff3
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Purpur-1182 (MC: 1.17)

**Comment by NicoStraube** [comment]
Hi, seems you're on 1.17.x, try using the latest build. [url](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)
