### ISSUE TITLE
Error when a player is connected (1.17)

### ISSUE THREAD

**Issue by AlexTheKing14** [dmulloy2/ProtocolLib#1263]
Hello, when a player join my server (and me too), I have a BIG error : 
 `> [11:47:17] [User Authenticator #1/INFO]: UUID of player AlexTheKing is 0be01b47-0c08-482f-b1f3-7f19fdb35f51
> [11:47:17] [Server thread/INFO]: AlexTheKing[/90.79.225.238:51169] logged in with entity id 242 at ([world]-76.83188704454412, 80.0, 91.40316285841914)
> [11:47:18] [pool-10-thread-3/INFO]: (Reflex/INFO) | AlexTheKing joined with MC WTF (locale: en_US) (game: Java Edition)
>2021-06-24 11:47:18,792 Netty Epoll Server IO #2 ERROR Recursive call to appender File
[11:47:18] [Netty Epoll Server IO #2/WARN]: [ProtocolLib] Loaded class rip.reflex.bz from Reflex v11.3-2U-9261ca9 which is not a depend, softdepend or loadbefore of this plugin.
> [11:47:18] [Netty Epoll Server IO #2/ERROR]: [Reflex] Unhandled exception occured in onPacketReceiving(PacketEvent) for Reflex
java.lang.NullPointerException: Cannot invoke "rip.reflex.util.c1.a(com.comphenix.protocol.events.PacketContainer)" because "<local116>" is null
at rip.reflex.aH.b(aH.java:131) ~[Reflex-11.3-2U-9261ca9.jar:?]
at rip.reflex.bz.onPacketReceiving(bz.java:19) ~[Reflex-11.3-2U-9261ca9.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.7.0-SNAPSHOT-b521]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.7.0-SNAPSHOT-b521]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.7.0-SNAPSHOT-b521]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.7.0-SNAPSHOT-b521]`

I have installed Reflex (Anticheat).

Can you help me ?

**Comment by dmulloy2** [comment]
I need some more information. Run ````/protocol dump```` and paste the output using [pastebin](http://pastebin.com/).

**Comment by AlexTheKing14** [comment]
https://pastebin.com/QmpXLApR

**Comment by dmulloy2** [comment]
I'd file this with the Reflex people; the code is obfuscated so it's hard to say anything useful

**Comment by KillsT3aler69** [comment]
I found a solution: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by AlexTheKing14** [comment]
I tried with the new build, but I still get the same error, Reflex admins told me that they fixed the problem on their end.

**Comment by dmulloy2** [comment]
This seems to be an issue on Reflex's end; there isn't anything we can do PL-side
