### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler

### ISSUE THREAD

**Issue by NotThatUwU** [dmulloy2/ProtocolLib#1266]
**Describe the bug**

```
[13:48:33 INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5aaf6ac7) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@66e0f3af.

[13:48:33 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5aaf6ac7
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters:
    com.comphenix.protocol.reflect.StructureModifier@67141f86[
      targetType=class net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public long net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.timestamp]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4911c949[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32bca9c8
        packetListeners=[PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[TRANSACTION[class=PacketPlayOutTransaction, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[ABILITIES[class=PacketPlayInAbilities, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[ABILITIES[class=PacketPlayOutAbilities, id=48]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ITEM[PLAY, CLIENT, 46, classNames: [net.minecraft.server.v1_8_R3.PacketPlayInUseItem, net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock] (unregistered)]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=31]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=UwUAnticheat, sending=ListeningWhitelist[priority=HIGHEST, packets=[OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=45]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3c14db9c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7b3b0bb7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3c27de18
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6b82c2bd
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@15c7160
        reporter=com.comphenix.protocol.ProtocolLib$1@5295e744
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-db6de12-18fbb24,minecraftVersion=1.8.8}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2daa938f
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=23
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@8c5a9e4
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1ff23179
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@66e0f3af[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@73347609=[com.comphenix.protocol.injector.StructureCache$1@441dd2b0]}
      listenerLock=java.lang.Object@61b2d95e
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@6f4555e8
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@ed9be24
      reporter=com.comphenix.protocol.ProtocolLib$1@5295e744
      unknownPermGenBean=java.lang.Object@24fb651d
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/72650902/123382848-9d9fde00-d5bc-11eb-972b-76badd95c324.png)

**Version Info**
https://pastebin.com/1PPuRtU4

**Comment by jusobreira** [comment]
Same here. But i'm on 1.16 and you are on 1.8.

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
