### ISSUE TITLE
ProtocolLib could not load [1.17]

### ISSUE THREAD

**Issue by Atrixss** [dmulloy2/ProtocolLib#1269]
**Describe the bug**
For some reason when I try to load in protocllib it just doesn't want to load

**Console**
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:274)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@206091df[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@71e824b4
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@32368e86
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@12786e69
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"47605b8",minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6cfb466
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@51d165d9
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-"47605b8" (MC: 1.17)

**Expected behavior**
To load up

**Comment by KillsT3aler69** [comment]
I have the exact same issue

**Comment by Lezurex** [comment]
I also get the exact same issue with the latest Paper version for 1.17

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
