### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.

### ISSUE THREAD

**Issue by SkyWatcher2019** [dmulloy2/ProtocolLib#1280]
Console shows this error when player joins to the server.

Stack Trace:
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5103322e
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
Dump:
Parameters:
com.comphenix.protocol.reflect.StructureModifier@418ed5a0[
targetType=class net.minecraft.server.v1_16_R3.PacketPlayOutChat
target=<null>
converter=<null>
fieldType=class java.lang.Object
data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a, public net.kyori.adventure.text.Component net.minecraft.server.v1_16_R3.PacketPlayOutChat.adventure$message, public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]
defaultFields={public net.md_5.bungee.api.chat.BaseComponent[] net.minecraft.server.v1_16_R3.PacketPlayOutChat.components=2, private net.minecraft.server.v1_16_R3.ChatMessageType net.minecraft.server.v1_16_R3.PacketPlayOutChat.b=3, private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c=4}
subtypeCache={interface net.minecraft.server.v1_16_R3.IChatBaseComponent=StructureModifier[fieldType=interface net.minecraft.server.v1_16_R3.IChatBaseComponent, data=[private net.minecraft.server.v1_16_R3.IChatBaseComponent net.minecraft.server.v1_16_R3.PacketPlayOutChat.a]], class java.util.UUID=StructureModifier[fieldType=class java.util.UUID, data=[private java.util.UUID net.minecraft.server.v1_16_R3.PacketPlayOutChat.c]]}
customConvertHandling=false
useStructureCompiler=true
manager:
com.comphenix.protocol.injector.PacketFilterManager@4bbc2c9a[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7ca8c398
packetListeners=[PacketAdapter[plugin=eco, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=PacketPlayOutChat, id=14]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=MONITOR, packets=[OPEN_WINDOW_MERCHANT[class=PacketPlayOutOpenWindowMerchant, id=38]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=eco, sending=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=47]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@51c201ff
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1760ff69
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3d92d9e3
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@79c69ca
hasClosed=false
classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
reporter=com.comphenix.protocol.ProtocolLib$1@46904d3f
server=CraftServer{serverName=Airplane-Purpur,serverVersion=git-Airplane-2,minecraftVersion=1.16.5}
library=ProtocolLib v4.6.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7dedffd2
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=7
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@42389af9
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@37e7ec9
hasRecycleDistance=true
minecraftVersion=(MC: 1.16.5)
debug=false
Sender:
com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6cd60527[
listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@cdec1154=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@7392378a], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@1531f9f8=[com.comphenix.protocol.injector.StructureCache$1@75fb8453], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@e852d82f=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@5832413]}
listenerLock=java.lang.Object@59a0e6b9
compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@3b6cb460
enabled=false
shuttingDown=false
executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@129c7642
reporter=com.comphenix.protocol.ProtocolLib$1@46904d3f
unknownPermGenBean=java.lang.Object@e236bbe
permGenBean=<null>
disablePermGenFraction=0.65
Version:
ProtocolLib v4.6.0
Java Version:
16.0.1
Server:
git-Airplane-2 (MC: 1.16.5)

**Comment by SkyWatcher2019** [comment]
completed
