### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib

### ISSUE THREAD

**Issue by DevAmiyo** [dmulloy2/ProtocolLib#1283]
https://pastebin.com/ZnbWk0i9

**Version:**
    ProtocolLib v4.6.0
  **Java Version:**
    16.0.1
  **Server:**
    git-Purpur-1204 (MC: 1.17)

`[22:57:44 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
  }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:54)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:112)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:285)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5e10d638[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3ed0d124
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@19e177ef
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@4d7e8064
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1204,minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2de68490
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@66e1aed
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Purpur-1204 (MC: 1.17)`

**Comment by DevAmiyo** [comment]
I updated to ProtocolLib v4.7.0-SNAPSHOT and now its fixed.
