### ISSUE TITLE
Crash:  Exception on first player join

### ISSUE THREAD

**Issue by MilesBHuff** [dmulloy2/ProtocolLib#1291]
The following stack trace appears on the first player join after server load:
```
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @45da602f
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@50e7e764[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5c7a1de0[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@52304677
        packetListeners=[com.comphenix.protocol.async.NullPacketListener@489f6feb, com.comphenix.protocol.async.NullPacketListener@2d48e4d0, com.comphenix.protocol.async.NullPacketListener@729a72b3]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@76b45b08
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@19874e7d
        inputBufferedPackets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=29], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28]]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@151ed5b0
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@454d3a9a
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@11f55520
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-779,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5172f574
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2211a37b
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@63f6cddf
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@21439474[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@26266ae6=[com.comphenix.protocol.injector.StructureCache$1@34c66bec]}
      listenerLock=java.lang.Object@1b630c74
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@4e2ea2f2
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@73736f77
      reporter=com.comphenix.protocol.ProtocolLib$1@11f55520
      unknownPermGenBean=java.lang.Object@746df3fe
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.1
  Server:
    git-Paper-779 (MC: 1.16.5)
```

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)

**Comment by MilesBHuff** [comment]
Oh, awesome -- thanks!
Question, though:  the latest dev builds seem to be only for 1.17.  My server is running 1.16.5.  Am I able to run the latest dev builds in 1.16?
> v4.7.0-SNAPSHOT for Spigot 1.17
v4.6.1 for MC 1.8 thru 1.15 and Spigot 1.16

**Comment by dmulloy2** [comment]
you should be good. i think we fixed all the backwards compat stuff. if there are any issues, open an issue

**Comment by MilesBHuff** [comment]
Okay, will do.  Thanks!
