### ISSUE TITLE
Error Magma 1.12.2

### ISSUE THREAD

**Issue by Xotwot** [dmulloy2/ProtocolLib#1302]
[21:09:47] [Netty Server IO #2/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:237)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:312)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:221)
        ... 40 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketPlayInFlying$PacketPlayInPositionLook
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPacketPlayer_PositionRotation$java_lang_Object.<init>(Unknown Source)
        ... 45 more
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@711a7b95[
      memoryAddress=2227284553840
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1515e3c4
      chunk=Chunk(30699683: 9%, 1474560/16777216)
      handle=4611686022722357252
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=32816
      length=34
      maxLength=48
      cache=io.netty.buffer.PoolThreadCache@5c4c1d86
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@14430ae1[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@285f85c2
        packetListeners=[PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=29]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[ABILITIES[class=PacketPlayInAbilities, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[ABILITIES[class=PacketPlayOutBed, id=48]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=18]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=MONITOR, packets=[POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=45]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[SPECTATE[class=PacketPlayInSpectate, id=45]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ITEM[class=PacketPlayInUseItem, id=46]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=ListeningWhitelist[priority=HIGHEST, packets=[TRANSACTION[class=PacketPlayOutTransaction, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=10]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=9]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=KizukiAC, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6677981a
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1c4815f0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1050109a
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4475e6c7
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1d39d0d8
        reporter=com.comphenix.protocol.ProtocolLib$1@1e98011b
        server=CraftServer{serverName=Magma,serverVersion=99be8c5-STABLE,minecraftVersion=1.12.2}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@52677ca3
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=25
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5795e640
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@11c3a71f
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@7b004177[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@358a4d18
      player=CraftPlayer{name=Xotwot}
      updated=CraftPlayer{name=Xotwot}
      playerName=Xotwot
      playerConnection=net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@4dd51a0f
      networkManager=net.minecraft.network.NetworkManager@4122b7f5
      originalChannel=[id: 0xeff3d72c, L:/26.216.91.160:25565 - R:/26.216.91.160:50538]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@4122b7f5, previous=[id: 0xeff3d72c, L:/26.216.91.160:25565 - R:/26.216.91.160:50538], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@54fc5ede, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@22f11aa4
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@321e10dc
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@3a0d8960
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5795e640
      processor=com.comphenix.protocol.injector.NetworkProcessor@263f3549
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@646549a2
      singleDecode=false
      decodeWasNull=false
      first=true
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    1.8.0_291
  Server:
    99be8c5-STABLE (MC: 1.12.2)

[21:09:49] [Netty Server IO #2/INFO] []: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@7b004177.

**Comment by dmulloy2** [comment]
Currently no plans to support Magma
