### ISSUE TITLE
ProtocolLib 3.7.0 Error

### ISSUE THREAD

**Issue by RickyLaChow** [dmulloy2/ProtocolLib#1313]
I have this error in console when i start the server

[13:36:20 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at http://dev.bukkit.org/server-mods/protocollib/ with the following data:
            ===== STACK TRACE =====
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:355)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:276)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.RuntimeException: Cannot find class net.minecraft.world.entity.MinecraftServer
        at com.comphenix.protocol.utility.MinecraftReflection.getClass(MinecraftReflection.java:1885)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1906)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftServerClass(MinecraftReflection.java:945)
        at com.comphenix.protocol.utility.MinecraftReflection.getNetServerHandlerClass(MinecraftReflection.java:1041)
        at com.comphenix.protocol.utility.MinecraftReflection.getPacketClass(MinecraftReflection.java:714)
        at com.comphenix.protocol.injector.packet.LegacyPacketRegistry.getPacketRegistry(LegacyPacketRegistry.java:188)
        at com.comphenix.protocol.injector.packet.LegacyPacketRegistry.initialize(LegacyPacketRegistry.java:64)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initializeLegacy(PacketRegistry.java:111)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:83)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:356)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:56)
        ... 10 more
  Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.MinecraftServer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at com.comphenix.protocol.utility.MinecraftReflection.getClass(MinecraftReflection.java:1883)
        ... 21 more
            ===== DUMP =====
  Sender:
    com.comphenix.protocol.ProtocolLibrary@30255c24[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2d45bfbd
      configExpectedMod=-1
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@4fa98523
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@488cdc12
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-79,minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4084baba
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v3.7.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@4fa98523
    ]
  Version:
    ProtocolLib v3.7.0
  Server:
    git-Paper-79 (MC: 1.17)

**Comment by IllusionTheDev** [comment]
ProtocolLib's main release is 4.6.0 iirc (might be 4.7.0 by now). Consider updating the plugin.

**Comment by dmulloy2** [comment]
I kinda love this actually. 3.7.0 supports 1.7 and 4.7.0 supports 1.17.

Go ahead and grab a dev build: https://ci.dmulloy2.net/job/ProtocolLib
