### ISSUE TITLE
Cannot load Protocollib

### ISSUE THREAD

**Issue by Gezellligheid** [dmulloy2/ProtocolLib#1330]
When loading the newest version of protocollib, i'm greeted with thes beatrifull error message:

Protocollib v4.7.0
Paper build 984591c
Minecraft version: 1.17

```
[12:06:05 INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0
[12:06:05 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.RuntimeException: Unable to find network.EnumProtocol (EnumProtocol)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2143)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:760)
        at com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:88)
        ... 9 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@548435e6[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@bc22e4c
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@245416f9
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@6bc4e23f
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"984591c",minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4b02c65
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@4ccedefb
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    16.0.1
  Server:
    git-Paper-"984591c" (MC: 1.17)
```

**Comment by dmulloy2** [comment]
Are you using normal paper? That error implies it's missing one of the important NMS classes

**Comment by DebaveyeEliasProjects** [comment]
@dmulloy2 yes. This is just normal paper

**Comment by AoElite** [comment]
Getting the same error

**Comment by MrTommyt** [comment]
Bump? I'm currently having the same issue.

**Comment by michcie** [comment]
Bump
same error:
[21:40:41 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:416)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.RuntimeException: Unable to find network.EnumProtocol (EnumProtocol)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2143)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:760)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:88)
  	... 9 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@55dc2030[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1537d971
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@582a98e7
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@1fc87e60
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"f905057",minecraftVersion=1.17.1}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@f6a84d
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@50f0b198
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    17
  Server:
    git-Paper-"f905057" (MC: 1.17.1)
