### ISSUE TITLE
[ProtocolLib] Exception registering converter

### ISSUE THREAD

**Issue by Samaine** [dmulloy2/ProtocolLib#1333]
```
[00:28:08 WARN]: [ProtocolLib] [Debug] Exception registering converter
java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 0, banned: 0], params=[{Type: class name of net\.minecraft\.(\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*\.)+\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*, Index: null}, {Type: Exact class java.lang.String, Index: 0}, {Type: Exact class java.lang.String, Index: 1}, {Type: Exact class java.lang.String, Index: 4}], paramCount=5}
	at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getWorldTypeClass(MinecraftReflection.java:1175) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.addConverter(BukkitConverters.java:1197) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1176) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1217) ~[?:?]
	at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:63) ~[?:?]
	at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:46) ~[?:?]
	at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:376) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:920) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.access$200(PacketFilterManager.java:71) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager$3.onPlayerLogin(PacketFilterManager.java:893) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-780]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-780]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-780]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.PlayerList.attemptLogin(PlayerList.java:768) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:170) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:87) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:403) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by dmulloy2** [comment]
That's safe to ignore. It's a debug message, so if you want to stop seeing them, set `debug: false` in your `config.yml`
