### ISSUE TITLE
[Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by Trippyx87** [dmulloy2/ProtocolLib#1360]
Stack Trace:
  FieldAccessException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.EntityLiving}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.EntityLiving instanceof input, Index: 2}], paramCount=3}]
  }}. Workaround failed too.
  	at com.comphenix.protocol.injector.packet.ProxyPacketInjector.initialize(ProxyPacketInjector.java:191)
  	at com.comphenix.protocol.injector.packet.ProxyPacketInjector.<init>(ProxyPacketInjector.java:164)
  	at com.comphenix.protocol.injector.packet.PacketInjectorBuilder.buildInjector(PacketInjectorBuilder.java:94)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:259)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:387)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:226)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:964)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:297)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.EntityLiving}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.EntityLiving instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPacketClass(MinecraftReflection.java:729)
  	at com.comphenix.protocol.injector.packet.ProxyPacketInjector$ArrayLookup.initialize(ProxyPacketInjector.java:115)
  	at com.comphenix.protocol.injector.packet.ProxyPacketInjector$ArrayLookup.<init>(ProxyPacketInjector.java:106)
  	at com.comphenix.protocol.injector.packet.ProxyPacketInjector.initialize(ProxyPacketInjector.java:188)
  	... 11 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@48681025[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@602c35ee
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.BukkitUpdater@4f083098
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@244575f2
      server=CraftServer{serverName=CraftBukkit,serverVersion=3170-Bukkit-ec116f6,minecraftVersion=1.17}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5313e04f
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@a50e545
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@5c935abc
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    16.0.1
  Server:
    3170-Bukkit-ec116f6 (MC: 1.17)

**Comment by Trippyx87** [comment]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.EntityLiving}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.EntityLiving instanceof input, Index: 2}], paramCount=3}]
  }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at com.comphenix.protocol.utility.MinecraftReflection.getNetworkListenThreadClass(MinecraftReflection.java:1576)
  	at com.comphenix.protocol.injector.player.InjectedServerConnection.initializeListenerField(InjectedServerConnection.java:194)
  	at com.comphenix.protocol.injector.player.InjectedServerConnection.injectListenerThread(InjectedServerConnection.java:232)
  	at com.comphenix.protocol.injector.player.InjectedServerConnection.injectList(InjectedServerConnection.java:181)
  	at com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler.<init>(ProxyPlayerInjectionHandler.java:150)
  	at com.comphenix.protocol.injector.player.PlayerInjectorBuilder.buildHandler(PlayerInjectorBuilder.java:139)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:253)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:387)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:226)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:964)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:297)
  	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by PimvanderLoos** [comment]
The version you are using does not support either Java 16 or Minecraft 1.17. If you want to run on 1.17, you'll have to upgrade to version 4.7.0: https://github.com/dmulloy2/ProtocolLib/releases/tag/4.7.0
