### ISSUE TITLE
Unable to apply potion effect to entities

### ISSUE THREAD

**Issue by grahhnt** [dmulloy2/ProtocolLib#1376]
**Describe the bug**
I am unable to apply a potion effect to an entity

**To Reproduce**
1. Recreate the code below
2. Run code, receive error

**Expected behavior**
To be able to apply a potion effect to entities

**Screenshots**
![image](https://user-images.githubusercontent.com/46821216/129522084-0ea8931a-f7c0-48a9-81cf-5527e2c9828a.png)
greyed out line, when used, doesn't create error and doesn't apply effect

**Version Info**
https://pastebin.com/3CpCQMxP (plugin replaced with MyPlugin)
I have tried using a previous version of protocollib and have tried paper & spigot 1.16.5

**Additional context**

```
Caused by: com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_16_R3.MobEffectList exists in class PacketPlayOutEntityEffect.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
```

**Comment by grahhnt** [comment]
I ended up having to use NMS using the example from [this plugin](https://github.com/JordanOsterberg/InvisiblePlayerItems/tree/087de6c4a1bea3ca76926b01c9e5d460d7ad4464)
