### ISSUE TITLE
Minecraft Forge Server software implementing for Mohist https://mohistmc.com/

### ISSUE THREAD

**Issue by mapleandtree** [dmulloy2/ProtocolLib#1377]
[02:17:49 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 128!
[02:17:49 INFO]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@37b3ae9f.
[02:17:49 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
>  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
>  Stack Trace:
>  java.lang.RuntimeException: Error occured while instancing generated class.
   at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
   at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
   at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
   at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
   at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
   at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
   at java.base/java.lang.Thread.run(Thread.java:831)
>  Caused by: java.lang.reflect.InvocationTargetException
   at jdk.internal.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
   at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
   ... 37 more
>  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInFlying$PacketPlayInPosition
   at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPlayerPacket_PositionPacket$java_lang_Object.<init>(Unknown Source)
   ... 42 more
>  Dump:
>  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@1d5234c6[
      memoryAddress=139676581154832
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@7064e31c
      chunk=Chunk(41292fb7: 2%, 286720/16777216)
      handle=4611686018427389960
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=65536
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@6bb48e50
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
>    manager:
      com.comphenix.protocol.injector.PacketFilterManager@383bc53e[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@77320a67
        packetListeners=[PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=92]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[LOOK[class=PacketPlayInLook, id=19], POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], FLYING[class=PacketPlayInFlying, id=254]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@73e51436
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7b0a7d48
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1dfe4522
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7af815c8
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@7117525
        reporter=com.comphenix.protocol.ProtocolLib$1@9af234c
        server=CraftServer{serverName=Mohist,serverVersion=1.16.5-758,minecraftVersion=1.16.5}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5c7bbf41
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=10
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@685b551d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@38519b86
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
>  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@37b3ae9f[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@376d3552
      player=CraftPlayer{name=Mapleandtree}
      updated=CraftPlayer{name=Mapleandtree}
      playerName=Mapleandtree
      playerConnection=net.minecraft.network.play.ServerPlayNetHandler@3d41592
      networkManager=net.minecraft.network.NetworkManager@29b98421
>      originalChannel=[id: 0x9e85d1bc, L:/192.168.0.104:25565 - R:/113.73.24.100:8129]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@29b98421, previous=[id: 0x9e85d1bc, L:/192.168.0.104:25565 - R:/113.73.24.100:8129], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@551d9515, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4f25edfb
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@76a96c37
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@247eb7cb
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@685b551d
      processor=com.comphenix.protocol.injector.NetworkProcessor@77b11a53
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4a440846
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
>  Version:
    ProtocolLib v4.7.0
>  Java Version:
    16.0.1
>  Server:
    1.16.5-758 (MC: 1.16.5)

[02:19:57 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 256!
[02:19:57 INFO]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@37b3ae9f.
[02:19:57 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
>  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
>  Stack Trace:
>  java.lang.RuntimeException: Error occured while instancing generated class.
   at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
   at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
   at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
   at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
   at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
   at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
   at java.base/java.lang.Thread.run(Thread.java:831)
>  Caused by: java.lang.reflect.InvocationTargetException
   at jdk.internal.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
   at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
   ... 37 more
>  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInFlying$PacketPlayInPosition
   at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPlayerPacket_PositionPacket$java_lang_Object.<init>(Unknown Source)
   ... 42 more
>  Dump:
>  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@1d5234c6[
      memoryAddress=139676581154864
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@7064e31c
      chunk=Chunk(41292fb7: 2%, 286720/16777216)
      handle=4611686022722357256
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=65568
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@6bb48e50
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
>    manager:
      com.comphenix.protocol.injector.PacketFilterManager@383bc53e[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@77320a67
        packetListeners=[PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=92]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[LOOK[class=PacketPlayInLook, id=19], POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], FLYING[class=PacketPlayInFlying, id=254]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@73e51436
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7b0a7d48
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1dfe4522
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7af815c8
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@7117525
        reporter=com.comphenix.protocol.ProtocolLib$1@9af234c
        server=CraftServer{serverName=Mohist,serverVersion=1.16.5-758,minecraftVersion=1.16.5}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5c7bbf41
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=10
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@685b551d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@38519b86
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
>  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@37b3ae9f[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@376d3552
      player=CraftPlayer{name=Mapleandtree}
      updated=CraftPlayer{name=Mapleandtree}
      playerName=Mapleandtree
      playerConnection=net.minecraft.network.play.ServerPlayNetHandler@3d41592
      networkManager=net.minecraft.network.NetworkManager@29b98421
>      originalChannel=[id: 0x9e85d1bc, L:/192.168.0.104:25565 - R:/113.73.24.100:8129]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@29b98421, previous=[id: 0x9e85d1bc, L:/192.168.0.104:25565 - R:/113.73.24.100:8129], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@551d9515, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4f25edfb
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@76a96c37
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@247eb7cb
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@685b551d
      processor=com.comphenix.protocol.injector.NetworkProcessor@77b11a53
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4a440846
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
>  Version:
    ProtocolLib v4.7.0
>  Java Version:
    16.0.1
>  Server:
    1.16.5-758 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
There are currently no plans to add support for mohist
