### ISSUE TITLE
Look

### ISSUE THREAD

**Issue by HarnesHa12** [dmulloy2/ProtocolLib#1385]
**Describe the bug**
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:297)
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[15:34:43 WARN]:  at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[15:34:43 WARN]:  at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:249)
[15:34:43 WARN]:  at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:181)
[15:34:43 WARN]:  at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1325)
[15:34:43 WARN]:  at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:213)
[15:34:43 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:334)
[15:34:43 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:341)
[15:34:43 WARN]:  at org.bukkit.command.defaults.PluginsCommand.execute(PluginsCommand.java:25)
[15:34:43 WARN]:  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:154)
[15:34:43 WARN]:  at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752)
[15:34:43 WARN]:  at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1589)
[15:34:43 WARN]:  at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1428)
[15:34:43 WARN]:  at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46)
[15:34:43 WARN]:  at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9)
[15:34:43 WARN]:  at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16)
[15:34:43 WARN]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:34:43 WARN]:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:34:43 WARN]:  at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[15:34:43 WARN]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840)
[15:34:43 WARN]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[15:34:43 WARN]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[15:34:43 WARN]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[15:34:43 WARN]:  at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
Run server
Go to the server
Boom bug in console

**Expected behavior**
I was on the server

**Screenshots**

**Version Info**
4.7.0

**Additional context**
None

**Comment by HarnesHa12** [comment]
[dump-2021-08-29_15.40.19.txt](https://github.com/dmulloy2/ProtocolLib/files/7073130/dump-2021-08-29_15.40.19.txt)

**Comment by HarnesHa12** [comment]
Engine: Mohist
