### ISSUE TITLE
Hello, can you help me? I have a mohist server and I have the latest version of this plugin but this always appears and it is constant.

### ISSUE THREAD

**Issue by Bercouli10** [dmulloy2/ProtocolLib#1389]
[00:20:11 INFO]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@3ba628f4.
[00:20:11 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at net.minecraft.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:85)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 36 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_CHandshakePacket$java_lang_Object.<init>(Unknown Source)
        ... 42 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@7f6a075d[
      memoryAddress=140392834007072
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@12b379a3
      chunk=Chunk(33412497: 1%, 16384/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=20
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@14d995dd
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=20
      writerIndex=20
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@672ff8b6[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4dd684af
        packetListeners=[PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IllegalStack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@51c3e543
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6dfd7bd2
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@758fd493
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@c85c571
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@503b0329
        reporter=com.comphenix.protocol.ProtocolLib$1@4222d05f
        server=CraftServer{serverName=Mohist,serverVersion=1.16.5-764,minecraftVersion=1.16.5}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4f276f6d
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@318d42a0
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3aff09
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@3ba628f4[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@77a79304
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@32513042
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@88edf03
      originalChannel=[id: 0x9dabd872, L:/172.18.0.14:25631 - R:/66.70.173.71:46900]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@88edf03, previous=[id: 0x9dabd872, L:/172.18.0.14:25631 - R:/66.70.173.71:46900], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5acaa7ca, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@61224ff1
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@1f2ae211
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@41703102
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@318d42a0
      processor=com.comphenix.protocol.injector.NetworkProcessor@3da5b9e6
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 20)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@73bc2013
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    16.0.2
  Server:
    1.16.5-764 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
There are currently no plans to support Mohist.
