### ISSUE TITLE
console debug?

### ISSUE THREAD

**Issue by illudota** [dmulloy2/ProtocolLib#1396]
why does this showup in my console?

[13:35:55 WARN]: java.lang.NoSuchMethodException: java.util.Arrays$ArrayList.<init>()
[13:35:55 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[13:35:55 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2238)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[13:35:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[13:35:55 WARN]:        at com.nickuc.login.δσζΦηινννφς.i(äFswdXkNHJwwGNQvIa2IrPiHXK9pFn5gL0n5E/Zwuz9BkEVKzCt8dcpAwDKFUKwug==9öbxFqHöü:100)
[13:35:55 WARN]:        at com.nickuc.login.εβχπΔφκημ.i(äTwoqHmqodiVToLpn27mVTKN0WivpY4aEqdQWYUHpXI2f26+zVceyjvhxNEO6lYrqcn3Gf62NUucyDVSzYpbD3rf/4=13öNWQLKöFLRgsqbgPOyqfrqxrCYzB2fsoKl4qakpLZyu5r3Kxn7wM9iBiw7jw2PhJCht7GC6XYnHb9Fdgm1eLbnxbaZA=8öqceXwöFALkNLZbobHGce5s+1lVP6v5rhCjA59mEDADmR9KD8k0qurzYtrRVAxEeGS6m1vjJM2FWX0dTm4Z9WqFx8qykcwA7bbkib2aR6qd2lifCDmcZh5IIE091YgiRx1DQYog==9öOnluKöTTsCsJXsiFHHkkjS3yFIzHvnRgZ2vqTgLl8WHRGaSuCzQXa5jhoPRjOGPWaqHX/IHjPLnF9QVT5r1APh6DLkjeUuJqhn0O74CHTn21wfp+PUzKxM2lE0sspLg=13ötLrMlöü:79)
[13:35:55 WARN]:        at com.nickuc.login.ΩγξληααςυοςΠυΛλ.a(ä䪘䪗䫁䫍䪠䪛䫝䫞䪵䫁䫦䫪䫈䫁䫋䫛䫠䪪䫜䫡䫆䫬䪬䪴䫍䫩䫩䫂䫰䫫䫹䫰䪻䫋䫕䫂䫘䫻䫗䫚䫼䫐䬃䫎öjMRODööZVlzeöTiyXTwZXqdPLJsb1hs2IICEcnpkrlolQpToXnMUkFKB3KxI6odS9nZUdhAJd4/ENcC4AjvXgWCyjFdpiaP99NptlzO+6giVQQjclOsWwMGdb5oX2whUGEfrKWUesX6g/dn7kPySl07oUICXiG4Tp5q2/TnpnKZRHM0pomf3z7qEeimkp484+esOpQ=13öqWzxiöü:293)
[13:35:55 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source)
[13:35:55 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:35:55 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:35:55 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:35:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[13:35:55 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607)
[13:35:55 WARN]:        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592)
[13:35:55 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1887)
[13:35:55 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1867)
[13:35:55 WARN]:        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:566)
[13:35:55 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:216)
[13:35:55 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1593)
[13:35:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[13:35:55 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[13:35:55 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1203)
[13:35:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:35:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
