### ISSUE TITLE
[WARN] io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 512

### ISSUE THREAD

**Issue by joex92** [dmulloy2/ProtocolLib#1402]
Hi, at this point idk where to find help for this problem, but ProtocolLib is mentioned here, everytime I try to rejoin, I get this warn:
```yaml
[00:33:09 INFO]: UUID of player joex92 is e4362f3a-c8a7-3d76-8d93-9ac2953b6cdf
[00:33:09 WARN]: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 512
[00:33:09 WARN]:        at app//net.minecraft.network.CompressionDecoder.decode(CompressionDecoder.java:41)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:33:09 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[00:33:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[00:33:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[00:33:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[00:33:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:33:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[00:33:09 WARN]: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 8712712 is larger than protocol maximum of 8388608
[00:33:09 WARN]:        at app//net.minecraft.network.CompressionDecoder.decode(CompressionDecoder.java:45)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:33:09 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:33:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:33:09 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[00:33:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[00:33:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[00:33:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[00:33:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:33:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[00:33:09 WARN]: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 1 is below server threshold of 512
[00:33:09 WARN]:        at net.minecraft.network.PacketDecompressor.decode(PacketDecompressor.java:41)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[00:33:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[00:33:09 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[00:33:09 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[00:33:09 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[00:33:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[00:33:09 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
[00:33:09 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[00:33:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[00:33:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[00:33:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[00:33:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:33:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[00:33:09 INFO]: [DiscordSRV] Player joex92 joined with silent joining permission, not sending a join message
[00:33:09 INFO]: joex92 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 8712712 is larger than protocol maximum of 8388608
[00:33:09 INFO]: [DiscordSRV] Player joex92 quit with silent quitting permission, not sending a quit message
[00:33:09 INFO]: [voicechat] Disconnecting client joex92
[00:33:09 WARN]: [BookShelf] Task #3466634 for Bookshelf v3.0.6.3 generated an exception
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[patched_1.17.1.jar:git-Purpur-1392]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[patched_1.17.1.jar:git-Purpur-1392]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[patched_1.17.1.jar:git-Purpur-1392]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:313) ~[ProtocolLib.jar:?]
        at com.loohp.bookshelf.listeners.PacketListenerEvents.lambda$onJoin$2(PacketListenerEvents.java:101) ~[Bookshelf-3.0.6.3.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1392]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1392]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1392]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1392]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1392]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1392]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1392]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:33:10 ERROR]: [Scoreboard] Error in group owners: The group-weight needs to be smaller than the amount of groups!
[00:33:10 ERROR]: [Scoreboard] Read the wiki to see which weights you have to set: https://wiki.xitma.de/plugin.php?name=scoreboard#ranks
[00:33:12 INFO]: [mcMMO] Aborting profile loading recovery for joex92 - player logged out
```
I can only join fine the first time after a server restart...
this is the list of Plugins (112): 
`3DItems (1.6.0), AdvancedArmorStands (1.17.3.0), AdvancedRegionMarket (3.3.5), ajStartCommands (2.0.3), AnnouncerPlus (1.2.5), ArmorSetEffects (2.2.4), AutoPickup (1.3.4-SNAPSHOT), BetterConcrete (1.7.0), BetterGiants (2.7), BetterNav (1.0.7), BKCommonLib (1.17.1-v3), BloodNight (0.10.7), Bookshelf (3.0.6.3), Carz (7.2), ChestSort (11.5.1), Citizens (2.0.28-SNAPSHOT (build 2359)), ClientDetector (2.1.2), CMILib (1.0.3.9), Coins (1.10.8), CoreProtect (20.1), CustomCrafting (1.7.1.3), CustomTime (2.1.1), DailyRewards (1.1.0), DamageIndicator (1.2.12), DangerousCaves (2.2.14-SNAPSHOT), DeadSouls (1.6), Dimensions (2.0.1), DiscordSRV (1.24.0), DiscordSRV-Staff-Chat (1.4.0), DoorsReloaded (1.1.2), EasyUnsafeEnchants (1.2), EconomyShopGUI (3.8.1), Elevator (3.11.4), EnchantGui (3.5.1), Enchantssquared (1.6), Essentials (2.19.0), EssentialsGeoIP (2.19.0), EssentialsSpawn (2.19.0), Evolutions (1.1.8), ExtraContexts (2.0-SNAPSHOT), ExtractableEnchantments (8.4), FastAsyncWorldEdit (1.17-167;df8b280), Geyser-Spigot (1.4.3-SNAPSHOT), GriefPrevention (16.17.1-2b69191), GSit ([6.0.2.1]), HeadDB (2.4.3), HealthBar (1.6.3), HolographicDisplays (2.4.9), IdleBot (1.2.1), Images (2.2.3), InfiniteVouchers (2.2.1), InteractionVisualizer (1.16.3.12), Jobs (5.0.0.8), LevelledMobs (3.1.7 b508), LuckPerms (5.3.55), Maintenance (3.0.7), Maplands (1.1), mcMMO (2.1.201-SNAPSHOT), MineChess (1.12.1), MobsToEggs (1.5.5_5), MoreArmour (2.0.6), MoreMobHeads (1.15_1.0.21), MoreOres (1.12.3), Multiverse-CommandDestination (1.2.2), Multiverse-Core (4.3.1-b861), Multiverse-EssentialsSupport (2.5-b3), Multiverse-Inventories (4.2.2-SNAPSHOT-bUNKNOWN), Multiverse-NetherPortals (4.2.2-SNAPSHOT-b804), Multiverse-Portals (4.2.2-SNAPSHOT-b850), MusicBox (2.0.5), MyCommand (5.7.1), NexEngine (2.0.7.4), NoteBlockAPI (1.6.2-SNAPSHOT), Oh_the_dungeons_youll_go (15.4), Oneblock (0.9.2f), Pl3xMap (1.0.0-BETA-162), PlaceholderAPI (2.10.10), PlugMan (2.2.5), PortalGun (2.2.2), ProtocolLib (4.7.1-SNAPSHOT-b531), RealLogin (24-8-2021 Build 1), Relics (2.2), Scoreboard (3.4.4), Shopkeepers (2.13.3), ShulkerPacks (1.5.16), SignBoard (1.6.10), SkinsRestorer (14.1.5), SmoothTimber (1.17.8), SpigotDash (0.3.9 BETA), StayPut (1.2.1), StreamingDrops (7.2), TabTPS (1.3.10), Tamablefoxes (2.1.5-SNAPSHOT), Terra (5.4.1-BETA+efd1665c), TerraformGenerator (4.6.4), Tweakin (3.3.2), Vault (1.7.3-b131), ViaBackwards (4.0.2-SNAPSHOT), ViaVersion (4.0.2-SNAPSHOT), voicechat (1.17.1-1.1.2), VoidGen (2.0), VoidSpawn (1.19.4), Wardrobe (1.4.2), Waterex (1.1.2), WebPlugin (1.4R), Wild (2.29-7da6164), WolfyUtilities (1.7.3.0), WorldBorder (2.1.4), WorldEditSelectionVisualizer (2.1.0), WorldGuard (7.0.5+3827266), WowSuchCleaner (1.9.2), ZombieApocalypse (1.4.2)`

[here's timings report](https://timings.pl3x.net/?id=8320ccfeb6cb4573a0aa62ca565b8db9)

**Comment by dmulloy2** [comment]
I don't see anything indicating this is a ProtocolLib issue. Seems to be something with BookShelf.

**Comment by joex92** [comment]
It's not bookshelf... I already tried to disable that plugin, the bookshelf error there is because my data  wasn't completely loaded, so bookshelf couldn't load itself either...

**Comment by joex92** [comment]
It's a `io.netty` problem, but I don't know where to have an answer to this...
