### ISSUE TITLE
Packet encoding of packet ID 77 threw (skippable? false)

### ISSUE THREAD

**Issue by Gu-f** [dmulloy2/ProtocolLib#1404]
**Describe the bug**
[11:55:53 ERROR]: Packet encoding of packet ID 77 threw (skippable? false)  

**To Reproduce**
There is a certain chance when quickly excavating blocks.  
This will cause the player to leave the game.
Display: xxxxx lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.ConcurrentModificationException

**Expected behavior**
No Error and do not lost connection  

**Version Info**
https://paste.ubuntu.com/p/Yb3w6t4dR2/  

**Error message**
```
[11:55:53 ERROR]: Packet encoding of packet ID 77 threw (skippable? false)
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at net.minecraft.network.syncher.DataWatcher.a(DataWatcher.java:166) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.a(PacketPlayOutEntityMetadata.java:34) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:44) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[patched_1.17.1.jar:git-Paper-266]
        at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268) ~[ProtocolLib.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.17.1.jar:git-Paper-266]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274) ~[ProtocolLib.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[patched_1.17.1.jar:git-Paper-266]
        at com.comphenix.protocol.injector.netty.ChannelProxy.write(ChannelProxy.java:312) ~[ProtocolLib.jar:?]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:450) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.NetworkManager.lambda$writePacket$7(NetworkManager.java:419) ~[patched_1.17.1.jar:git-Paper-266]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Paper-266]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Paper-266]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[11:55:53 INFO]: xxxxx lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.ConcurrentModificationException```

**Comment by iSeitan** [comment]
i have the same issue, player mining fast and then getting this error with packet id error 20

**Comment by Uharn** [comment]
Can confirm i also have that issue with id error 20

**Comment by molor** [comment]
Packet 33 too, happened while I was AFK for ~1 hour
I'm unsure if it's related to this plugin, but this is not the first time I'm getting it

```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at net.minecraft.network.PacketDataSerializer.a(PacketDataSerializer.java:142) ~[paper-1.18.1.jar:git-Paper-141]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.a(ClientboundLevelChunkPacketData.java:94) ~[paper-1.18.1.jar:git-Paper-141]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.a(ClientboundLevelChunkWithLightPacket.java:53) ~[paper-1.18.1.jar:git-Paper-141]
	at net.minecraft.network.PacketEncoder.a(PacketEncoder.java:44) ~[paper-1.18.1.jar:git-Paper-141]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:16) ~[paper-1.18.1.jar:git-Paper-141]
	at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.comphenix.protocol.injector.netty.ChannelProxy.write(ChannelProxy.java:312) ~[?:?]
	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:428) ~[paper-1.18.1.jar:git-Paper-141]
	at net.minecraft.network.NetworkManager.lambda$writePacket$7(NetworkManager.java:397) ~[paper-1.18.1.jar:git-Paper-141]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
