### ISSUE TITLE
ProtocolLib Error

### ISSUE THREAD

**Issue by NIKO4685** [dmulloy2/ProtocolLib#1410]
[08:52:29 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 43 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketPlayInFlying$PacketPlayInPositionLook
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPacketPlayer_PositionRotation$java_lang_Object.<init>(Unknown Source)
        ... 47 more
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@5f591de7[
      memoryAddress=2309812555888
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@75de008c
      chunk=Chunk(38ff9e63: 3%, 335872/16777216)
      handle=4611686022722357256
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=65584
      length=34
      maxLength=48
      cache=io.netty.buffer.PoolThreadCache@62ea89c3
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@fadc32c[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@39bff78b
        packetListeners=[PacketAdapter[plugin=Alice, sending=ListeningWhitelist[priority=MONITOR, packets=[RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=60], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], POSITION[class=PacketPlayOutPosition, id=56], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], TRANSACTION[class=PacketPlayOutTransaction, id=246], SPECTATE[class=PacketPlayInSpectate, id=45], USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], ABILITIES[class=PacketPlayOutAbilities, id=50], EXPLOSION[class=PacketPlayOutExplosion, id=28], CHAT[class=PacketPlayInChat, id=3], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], SETTINGS[class=PacketPlayInSettings, id=5], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], HELD_ITEM_SLOT[class=PacketPlayOutHeldItemSlot, id=72], ABILITIES[class=PacketPlayInAbilities, id=25], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], USE_ENTITY[class=PacketPlayInUseEntity, id=13], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=MONITOR, packets=[RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=60], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], POSITION[class=PacketPlayOutPosition, id=56], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], TRANSACTION[class=PacketPlayOutTransaction, id=246], SPECTATE[class=PacketPlayInSpectate, id=45], USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], ABILITIES[class=PacketPlayOutAbilities, id=50], EXPLOSION[class=PacketPlayOutExplosion, id=28], CHAT[class=PacketPlayInChat, id=3], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], SETTINGS[class=PacketPlayInSettings, id=5], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], HELD_ITEM_SLOT[class=PacketPlayOutHeldItemSlot, id=72], ABILITIES[class=PacketPlayInAbilities, id=25], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], USE_ENTITY[class=PacketPlayInUseEntity, id=13], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2000d5a1
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4181c9fc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2054c643
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@66117e6d
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@4f4729d3
        reporter=com.comphenix.protocol.ProtocolLib$1@401a12d3
        server=CraftServer{serverName=Mohist,serverVersion=git-Mohist-1.12.2-258,minecraftVersion=1.12.2}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@97b547b
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@77c0d3db
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@36fc69c5
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@77a3319[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7f54cef8
      player=CraftPlayer{name=NIKO4685}
      updated=CraftPlayer{name=NIKO4685}
      playerName=NIKO4685
      playerConnection=net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@e7b94c2
      networkManager=net.minecraft.network.NetworkManager@5b1c6689
      originalChannel=[id: 0xa8b25eb7, L:/127.0.0.1:25565 - R:/127.0.0.1:59062]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@5b1c6689, previous=[id: 0xa8b25eb7, L:/127.0.0.1:25565 - R:/127.0.0.1:59062], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@708b260e, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@365d28d4
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@58329cab
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@ec6f083
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@77c0d3db
      processor=com.comphenix.protocol.injector.NetworkProcessor@78908bb5
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@340b97c8
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    1.8.0_252
  Server:
    git-Mohist-1.12.2-258 (MC: 1.12.2)

**Comment by dmulloy2** [comment]
The official stance of ProtocolLib is to not use Mohist. They've done some shady stuff with plugin jars which you can read more about here: https://essentialsx.net/do-not-use-mohist.html
