### ISSUE TITLE
Internal error; Cannot execute code in channel thread

### ISSUE THREAD

**Issue by LauraRussels** [dmulloy2/ProtocolLib#1414]
[12.10 19:13:01] [Server] [ERROR]   [ProtocolLib] INTERNAL ERROR: Cannot execute code in channel thread.
[12.10 19:13:01] [Server]   If this problem hasn't already been reported, please open a ticket
[12.10 19:13:01] [Server]   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[12.10 19:13:01] [Server]   Stack Trace:
[12.10 19:13:01] [Server]   java.lang.IllegalArgumentExceptionDuplicate handler name: protocol_lib_decoder
[12.10 19:13:01] [Server]   	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055)
[12.10 19:13:01] [Server]   	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284)
[12.10 19:13:01] [Server]   	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247)
[12.10 19:13:01] [Server]   	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
[12.10 19:13:01] [Server]   	at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61)
[12.10 19:13:01] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:313)
[12.10 19:13:01] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:295)
[12.10 19:13:01] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector.lambda$executeInChannelThread$3(ChannelInjector.java:917)
[12.10 19:13:01] [Server]   	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12.10 19:13:01] [Server]   	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12.10 19:13:01] [Server]   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12.10 19:13:01] [Server]   	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12.10 19:13:01] [Server]   	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12.10 19:13:01] [Server]   	at java.base/java.lang.Thread.run(Thread.java:834)
[12.10 19:13:01] [Server]   Dump:
[12.10 19:13:01] [Server]     manager:
[12.10 19:13:01] [Server]       com.comphenix.protocol.injector.PacketFilterManager@5158ca50[
[12.10 19:13:01] [Server]         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4e349edf
[12.10 19:13:01] [Server]         packetListeners=[PacketAdapter[plugin=Plank-Digital, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]]]
[12.10 19:13:01] [Server]         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@16affb66
[12.10 19:13:01] [Server]         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1c3405b7
[12.10 19:13:01] [Server]         inputBufferedPackets=[]
[12.10 19:13:01] [Server]         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@ba9562b
[12.10 19:13:01] [Server]         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6181f3e7
[12.10 19:13:01] [Server]         hasClosed=false
[12.10 19:13:01] [Server]         classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.1-SNAPSHOT-b533, pluginEnabled=true, url=plugins/ProtocolLib.jar}
[12.10 19:13:01] [Server]         reporter=com.comphenix.protocol.ProtocolLib$1@89c507a
[12.10 19:13:01] [Server]         server=CraftServer{serverName=Paper,serverVersion=git-Paper-788,minecraftVersion=1.16.5}
[12.10 19:13:01] [Server]         library=ProtocolLib v4.7.1-SNAPSHOT-b533
[12.10 19:13:01] [Server]         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@34b9e563
[12.10 19:13:01] [Server]         knowsServerPackets=true
[12.10 19:13:01] [Server]         knowsClientPackets=true
[12.10 19:13:01] [Server]         phaseLoginCount=0
[12.10 19:13:01] [Server]         phasePlayingCount=1
[12.10 19:13:01] [Server]         packetCreation=false
[12.10 19:13:01] [Server]         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@a8cd36b
[12.10 19:13:01] [Server]         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@78b07186
[12.10 19:13:01] [Server]         hasRecycleDistance=true
[12.10 19:13:01] [Server]         minecraftVersion=(MC1.16.5)
[12.10 19:13:01] [Server]         debug=false
[12.10 19:13:01] [Server]       ]
[12.10 19:13:01] [Server]   Sender:
[12.10 19:13:01] [Server]     com.comphenix.protocol.injector.netty.ChannelInjector@62482af7[
[12.10 19:13:01] [Server]       decodeBuffer=protected void net.minecraft.server.v1_16_R3.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
[12.10 19:13:01] [Server]       encodeBuffer=protected void net.minecraft.server.v1_16_R3.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
[12.10 19:13:01] [Server]       factory=com.comphenix.protocol.injector.netty.InjectionFactory@3ee7af1d
[12.10 19:13:01] [Server]       player=CraftPlayer{name=LauraRussels}
[12.10 19:13:01] [Server]       updated=<null>
[12.10 19:13:01] [Server]       playerName=<null>
[12.10 19:13:01] [Server]       playerConnection=<null>
[12.10 19:13:01] [Server]       networkManager=net.minecraft.server.v1_16_R3.NetworkManager@62d77982
[12.10 19:13:01] [Server]       originalChannel=com.comphenix.protocol.injector.netty.ChannelInjector$3@1130c095
[12.10 19:13:01] [Server]       channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_16_R3.NetworkManager.channel], container=net.minecraft.server.v1_16_R3.NetworkManager@62d77982, previous=null, current=null, previousLoaded=false, currentSet=false, forceAccess=true]
[12.10 19:13:01] [Server]       packetMarker={}
[12.10 19:13:01] [Server]       currentEvent=<null>
[12.10 19:13:01] [Server]       finalEvent=<null>
[12.10 19:13:01] [Server]       unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@29db43b5
[12.10 19:13:01] [Server]       vanillaDecoder=net.minecraft.server.v1_16_R3.PacketDecoder@5781becc
[12.10 19:13:01] [Server]       vanillaEncoder=net.minecraft.server.v1_16_R3.PacketEncoder@40a2f8c1
[12.10 19:13:01] [Server]       finishQueue=[]
[12.10 19:13:01] [Server]       channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@a8cd36b
[12.10 19:13:01] [Server]       processor=com.comphenix.protocol.injector.NetworkProcessor@97b12ed
[12.10 19:13:01] [Server]       injected=false
[12.10 19:13:01] [Server]       closed=false
[12.10 19:13:01] [Server]       cumulation=<null>
[12.10 19:13:01] [Server]       cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@360f4913
[12.10 19:13:01] [Server]       singleDecode=false
[12.10 19:13:01] [Server]       first=false
[12.10 19:13:01] [Server]       firedChannelRead=false
[12.10 19:13:01] [Server]       decodeState=0
[12.10 19:13:01] [Server]       discardAfterReads=16
[12.10 19:13:01] [Server]       numReads=0
[12.10 19:13:01] [Server]       added=true
[12.10 19:13:01] [Server]     ]
[12.10 19:13:01] [Server]   Version:
[12.10 19:13:01] [Server]     ProtocolLib v4.7.1-SNAPSHOT-b533
[12.10 19:13:01] [Server]   Java Version:
[12.10 19:13:01] [Server]     11.0.10
[12.10 19:13:01] [Server]   Server:
[12.10 19:13:01] [Server]     git-Paper-(MC: 1.16.5)

-------

Also side note, is the PacketType.Play.Client.UPDATE_SIGN not supported in 1.16.5 Java 11? When there are no issues with ProtocolLib loading, it throws an error when this packet is received.

Thanks in advance

**Comment by dmulloy2** [comment]
Are you reloading the server? Only reason I can think of for duplicated decoders
