### ISSUE TITLE
Cannot load ProtocolLib - Please help...

### ISSUE THREAD

**Issue by ljboxf** [dmulloy2/ProtocolLib#1425]
Stack Trace:
  java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:386)
  	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:244)
  	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:826)
  	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286)
  	at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: java.lang.RuntimeException: Unable to find network.EnumProtocol (EnumProtocol)
  	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2143)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:760)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:88)
  	... 9 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@132c0dba[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@58a782af
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4a10b78d
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@4ff37f0a
      server=CraftServer{serverName=Magma,serverVersion=git-Magma-1.16.5-36.2.8-5faa5ec-DEV,minecraftVersion=1.16.5}
      file=plugins/protocollib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5817a55e
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@e823a98
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@43abebc5
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    11.0.10
  Server:
    git-Magma-1.16.5-36.2.8-5faa5ec-DEV (MC: 1.16.5)

**Comment by dmulloy2** [comment]
These types of issues appear with non-standard servers, i.e. those not in the Paper/Spigot ecosystem. Unfortunately due to their wide variety, ProtocolLib cannot support all of them and sometimes these issues appear. You are welcome open a pull request to try to address it.
