### ISSUE TITLE
Error when the player quits the server

### ISSUE THREAD

**Issue by AdixeMC** [dmulloy2/ProtocolLib#1428]
When a player leaves the server, I sometimes see this error in the console:

`[21:42:41] [Server thread/WARN]: java.lang.NoSuchMethodException: java.util.Arrays$ArrayList.<init>()
[21:42:41] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[21:42:41] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor(Class.java:2238)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.getGenericList(BukkitConverters.java:277)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters.access$100(BukkitConverters.java:88)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:367)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:359)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:48)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372)
[21:42:41] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[21:42:41] [Server thread/WARN]: 	at com.nickuc.login.ΣιυΦΨΩξχΨο.h(:100)
[21:42:41] [Server thread/WARN]: 	at com.nickuc.login.βθσπψλΓωυΨλω.h(:79)
[21:42:41] [Server thread/WARN]: 	at com.nickuc.login.ωΛΛτεηΛΣςκγΛΨΦ.a(:293)
[21:42:41] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source)
[21:42:41] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:42:41] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:42:41] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:42:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1962)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1942)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:743)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:221)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1648)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[21:42:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[21:42:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)`

Plugin version: 4.7.0

**Comment by dmulloy2** [comment]
This can safely be ignored. The error message was silenced in a dev build: https://ci.dmulloy2.net/job/ProtocolLib/
