### ISSUE TITLE
AT

### ISSUE THREAD

**Issue by cian1203099189** [dmulloy2/ProtocolLib#1437]
Stack Trace:
java.lang.RuntimeException: Error occured while instancing generated class.
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
... 38 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_server_v1_16_R3_PacketHandshakingInSetProtocol$java_lang_Object.<init>(Unknown Source)
... 44 more
Dump:
Parameters:
io.netty.buffer.PooledUnsafeDirectByteBuf@60badaee[
memoryAddress=140042626404368
recyclerHandle=io.netty.util.Recycler$DefaultHandle@12dfc5e
chunk=Chunk(78e918bd: 1%, 16384/16777216)
handle=4611686018427389953
memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
offset=8192
length=24
maxLength=32
cache=io.netty.buffer.PoolThreadCache@17b367e9
tmpNioBuf=<null>
allocator=PooledByteBufAllocator(directByDefault: true)
refCnt=1
readerIndex=24
writerIndex=24
markedReaderIndex=0
markedWriterIndex=0
maxCapacity=2147483647
manager:
com.comphenix.protocol.injector.PacketFilterManager@182c659a[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@755c984
packetListeners=[PacketAdapter[plugin=CatSeedLogin, sending=ListeningWhitelist[priority=HIGHEST, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=OhTheWorld, sending=ListeningWhitelist[priority=NORMAL, packets=[LOGIN[class=PacketPlayOutLogin, id=38], RESPAWN[class=PacketPlayOutRespawn, id=61]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]]]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7b2243f5
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1d00dd7e
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@667b7bf1
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4fcb9753
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@56aac2a0
reporter=com.comphenix.protocol.ProtocolLib$1@3d6f9a24
server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.16.5-1.0.19-abf9928,minecraftVersion=1.16.5}
library=ProtocolLib v4.7.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1394b4c9
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=4
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@efde165
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@51976961
hasRecycleDistance=true
minecraftVersion=(MC: 1.16.5)
debug=false
Sender:
com.comphenix.protocol.injector.netty.ChannelInjector@21e8b25b[
decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
factory=com.comphenix.protocol.injector.netty.InjectionFactory@270d4983
player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@4f496534
updated=<null>
playerName=<null>
playerConnection=<null>
networkManager=net.minecraft.network.NetworkManager@7f55a090
originalChannel=[id: 0x01d6b3ec, L:/172.18.0.5:8412 - R:/220.177.204.118:22231]
channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@7f55a090, previous=[id: 0x01d6b3ec, L:/172.18.0.5:8412 - R:/220.177.204.118:22231], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@174b12f7, previousLoaded=true, currentSet=true, forceAccess=true]
packetMarker={}
currentEvent=<null>
finalEvent=<null>
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@13afb5ef
vanillaDecoder=net.minecraft.network.NettyPacketDecoder@41acd62a
vanillaEncoder=net.minecraft.network.NettyPacketEncoder@1ac7025f
finishQueue=[]
channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@efde165
processor=com.comphenix.protocol.injector.NetworkProcessor@3bbab0d2
injected=true
closed=false
cumulation=PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 24)
cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4c5bd59f
singleDecode=false
decodeWasNull=false
first=true
decodeState=1
discardAfterReads=16
numReads=0
added=true
Version:
ProtocolLib v4.7.0
Java Version:
16.0.1
Server:
arclight-1.16.5-1.0.19-abf9928 (MC: 1.16.5)
>.... [10:20:02] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player Touch is 0fb956b2-71d0-371d-b8a3-a71d1fc4a00a
>.... [10:20:03] [Server thread/INFO] [forge/AdvancementLoadFix]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@473b547c
>.... [10:20:03] [Server thread/INFO] [minecraft/PlayerList]: Touch[/220.177.204.118:22231] logged in with entity id 363 at (-267.3248661841451, 81.0, -65.15885146871956)
>.... [10:20:04] [Server thread/INFO] [Console/]: [DriveBackupV2] Enabling automatic backups
>.... [10:20:04] [Server thread/ERROR] [c.s.w.b.BukkitWorld/]: No TreeType mapping for TreeGenerator.TreeType.AZALEA
>.... [10:20:04] [Server thread/INFO] [c.s.w.b.BukkitWorld/]: The above message is displayed because your FAWE version is newer than arclight-1.16.5-1.0.19-abf9928 (MC: 1.16.5) and contains features of future minecraft versions which do not exist in arclight-1.16.5-1.0.19-abf9928 (MC: 1.16.5), hence the tree type AZALEA is not available. This is not an error. This version will work on your version of Minecraft. This is an informative message only
>.... [10:20:04] [Craft Scheduler Thread - 10/INFO] [CatSeedLogin/]: 缓存加载 5 个数据
>.... [10:20:32] [Netty Epoll Server IO #4/INFO] [Console/]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@7c50c012.
>.... [10:20:32] [Netty Epoll Server IO #4/ERROR] [Minecraft/]: [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.RuntimeException: Error occured while instancing generated class.
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
... 36 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_server_v1_16_R3_PacketHandshakingInSetProtocol$java_lang_Object.<init>(Unknown Source)
... 42 more
Dump:
Parameters:
io.netty.buffer.PooledUnsafeDirectByteBuf@20a65b97[
memoryAddress=140042597044240
recyclerHandle=io.netty.util.Recycler$DefaultHandle@5d95835f
chunk=Chunk(55dc4d41: 1%, 16384/16777216)
handle=4611686018427389953
memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
offset=8192
length=24
maxLength=32
cache=io.netty.buffer.PoolThreadCache@6e3854a1
tmpNioBuf=<null>
allocator=PooledByteBufAllocator(directByDefault: true)
refCnt=1
readerIndex=24
writerIndex=24
markedReaderIndex=0
markedWriterIndex=0
maxCapacity=2147483647
manager:
com.comphenix.protocol.injector.PacketFilterManager@182c659a[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@755c984
packetListeners=[PacketAdapter[plugin=CatSeedLogin, sending=ListeningWhitelist[priority=HIGHEST, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=OhTheWorld, sending=ListeningWhitelist[priority=NORMAL, packets=[LOGIN[class=PacketPlayOutLogin, id=38], RESPAWN[class=PacketPlayOutRespawn, id=61]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]]]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7b2243f5
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1d00dd7e
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@667b7bf1
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4fcb9753
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@56aac2a0
reporter=com.comphenix.protocol.ProtocolLib$1@3d6f9a24
server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.16.5-1.0.19-abf9928,minecraftVersion=1.16.5}
library=ProtocolLib v4.7.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1394b4c9
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=4
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@efde165
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@51976961
hasRecycleDistance=true
minecraftVersion=(MC: 1.16.5)
debug=false
Sender:
com.comphenix.protocol.injector.netty.ChannelInjector@7c50c012[
decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
factory=com.comphenix.protocol.injector.netty.InjectionFactory@270d4983
player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@dae3bbc
updated=<null>
playerName=<null>
playerConnection=<null>
networkManager=net.minecraft.network.NetworkManager@3a2fc90d
originalChannel=[id: 0xd9b13a8a, L:/172.18.0.5:8412 - R:/117.43.223.193:58951]
channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@3a2fc90d, previous=[id: 0xd9b13a8a, L:/172.18.0.5:8412 - R:/117.43.223.193:58951], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6cb41d34, previousLoaded=true, currentSet=true, forceAccess=true]
packetMarker={}
currentEvent=<null>
finalEvent=<null>
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@10bbb8c5
vanillaDecoder=net.minecraft.network.NettyPacketDecoder@54987c7e
vanillaEncoder=net.minecraft.network.NettyPacketEncoder@329db2ff
finishQueue=[]
channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@efde165
processor=com.comphenix.protocol.injector.NetworkProcessor@33bca6b1
injected=true
closed=false
cumulation=PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 24)
cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4c5bd59f
singleDecode=false
decodeWasNull=false
first=true
decodeState=1
discardAfterReads=16
numReads=0
added=true
Version:
ProtocolLib v4.7.0
Java Version:
16.0.1
Server:
arclight-1.16.5-1.0.19-abf9928 (MC: 1.16.5)
>.... [10:20:32] [User Authenticator #2/INFO] [minecraft/ServerLoginNetHandler]: UUID of player MrLI is b68e33ff-92da-31ff-9cde-548b8c1d7116
>.... [10:20:34] [Server thread/INFO] [forge/AdvancementLoadFix]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@23d4b2b4
>.... [10:20:34] [Server thread/INFO] [minecraft/PlayerList]: MrLI[/117.43.223.193:58951] logged in with entity id 388 at (-199.20382498575938, 41.0, 190.30655119287132)
>.... [10:20:34] [Server thread/INFO] [c.g.c.b.i.Finalizer/]: Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.
>.... [10:20:34] [Craft Scheduler Thread - 2/INFO] [CatSeedLogin/]: 缓存加载 5 个数据
>.... [10:20:37] [Thread-7/WARN] [NBTAPI/]: [NBTAPI] Error while checking for updates!
java.net.ConnectException: Connection timed out
at sun.nio.ch.Net.connect0(Native Method) ~[?:?] {}
at sun.nio.ch.Net.connect(Net.java:576) ~[?:?] {}
at sun.nio.ch.Net.connect(Net.java:565) ~[?:?] {}
at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?] {}
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?] {}
at java.net.Socket.connect(Socket.java:645) ~[?:?] {}
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290) ~[?:?] {}
at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?] {}
at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?] {}
at sun.net.www.http.HttpClient.openServer(HttpClient.java:497) ~[?:?] {}
at sun.net.www.http.HttpClient.openServer(HttpClient.java:600) ~[?:?] {}
at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?] {}
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379) ~[?:?] {}
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?] {}
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?] {}
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120) ~[?:?] {}
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?] {}
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[?:?] {}
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?] {}
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?] {}
at de.tr7zw.nbtapi.utils.VersionChecker.checkForUpdates(VersionChecker.java:34) ~[?:?] {re:classloading,re:classloading}
at de.tr7zw.nbtapi.utils.MinecraftVersion.lambda$init$0(MinecraftVersion.java:105) ~[?:?] {re:classloading,re:classloading}
at java.lang.Thread.run(Thread.java:831) [?:?] {}

**Comment by dmulloy2** [comment]
These types of issues appear with non-standard servers, i.e. those not in the Paper/Spigot ecosystem. Unfortunately due to their wide variety, ProtocolLib cannot support all of them and sometimes these issues appear. You are welcome open a pull request to try to address it.
