### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib

### ISSUE THREAD

**Issue by imp87** [dmulloy2/ProtocolLib#1450]
**Make sure you're doing the following**
- [y ] You're using the latest build for your server version
- [y ] This isn't an issue caused by another plugin
- [y ] You've checked for duplicate issues
- [y ] You didn't use `/reload`

I get this error by every start.

**Code**
[22:01:48 ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.ExceptionInInitializerError
at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399)
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269)
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unsupported class file major version 61
at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:409)
at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
... 10 more
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@e95d22[
statistics=<null>
backgroundCompiler=<null>
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2fa20440
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@60f56c2d
redirectHandler=<null>
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=org.bukkit.plugin.java.JavaPluginLoader@650c94a9
server=CraftServer{serverName=Paper,serverVersion=git-Paper-790,minecraftVersion=1.16.5}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@107944db
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.1-SNAPSHOT-b501, pluginEnabled=false, url=plugins/ProtocolLib.jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@5a8eb8ec
]
Version:
ProtocolLib v4.6.1-SNAPSHOT-b501
Java Version:
17.0.1
Server:
git-Paper-790 (MC: 1.16.5)

Hope you guys can help me!

**Comment by derklaro** [comment]
Try updating to the latest version
