### ISSUE TITLE
ProtocolLib error

### ISSUE THREAD

**Issue by Fonyks** [dmulloy2/ProtocolLib#1455]
Hi, im getting this error randomly in my server, do you know why?

[17:21:00] [Netty Epoll Server IO #2/INFO] []: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@2c39f3a9.
[17:21:00] [Netty Epoll Server IO #2/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor431.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 35 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketHandshakingInSetProtocol
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_C00Handshake$java_lang_Object.<init>(Unknown Source)
        ... 39 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@13581211[
      memoryAddress=140222603935760
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@2d996c6b
      chunk=Chunk(4ce37eb9: 1%, 73728/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=21
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@7993a21a
      tmpNioBuf=java.nio.DirectByteBuffer[pos=8210 lim=8210 cap=16777216]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=21
      writerIndex=21
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@18ff91cb[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@36d4b3ba
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54], ABILITIES[class=PacketPlayOutAbilities, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1a1c1b07
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@54291ee9
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@303cbc6e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@23e680b0
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@399f568a
        reporter=com.comphenix.protocol.ProtocolLib$1@595863e8
        server=CraftServer{serverName=Magma,serverVersion=788465c-DEV,minecraftVersion=1.12.2}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1090eb7d
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=3
        phasePlayingCount=8
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@186ebdbb
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3f7bee8b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2c39f3a9[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@75ec6bc1
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@8e7d58f
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@56306213
      originalChannel=[id: 0x654cb976, L:/172.18.0.2:25565 - R:/51.38.230.69:33368]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@56306213, previous=[id: 0x654cb976, L:/172.18.0.2:25565 - R:/51.38.230.69:33368], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@7d73bcc1, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4b0e454d
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@1efb86c5
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@25f42987
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@186ebdbb
      processor=com.comphenix.protocol.injector.NetworkProcessor@7c9c0d8c
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 21, widx: 21, cap: 21)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1d12d7ca
      singleDecode=false
      decodeWasNull=false
      first=true
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    1.8.0_312
  Server:
    788465c-DEV (MC: 1.12.2)

**Comment by derklaro** [comment]
This is a magma naming inconsistency, please report that to them. It's not a ProtocolLib issue.
