### ISSUE TITLE
Cannot enable ProtocolLib.

### ISSUE THREAD

**Issue by GalaxyMCNT** [dmulloy2/ProtocolLib#1465]
[05:59:29 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to inject channel futures.
        at com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:196)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:991)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:415)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:390)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:349)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:208)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:562)
        at java.base/java.lang.Thread.run(Thread.java:829)
  Caused by: java.lang.IllegalArgumentException: Unable to find getNetworkManagers in net.minecraft.server.v1_8_R3.ServerConnection
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:283)
        at com.comphenix.protocol.reflect.FuzzyReflection.invokeMethod(FuzzyReflection.java:331)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:176)
        ... 10 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7f36db31[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2f0aa191
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@25020ba7
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@58923e90
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@11b499e0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6bc8b46e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5e22d583
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@67919f99
        reporter=com.comphenix.protocol.ProtocolLib$1@170d1669
        server=CraftServer{serverName=NachoSpigot,serverVersion=git-NachoSpigot-"3faab47",minecraftVersion=1.8.8}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@c864d03
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3898d102
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7ce28f2b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@48eccda2
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@740a22f7[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@35078758
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2f0aa191
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@12c02b12
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@3d6206bd
      commandProtocol=com.comphenix.protocol.CommandProtocol@60d5a38b
      commandPacket=com.comphenix.protocol.CommandPacket@69e1d58e
      commandFilter=com.comphenix.protocol.CommandFilter@7a6afb1b
      packetLogging=com.comphenix.protocol.PacketLogging@57904d05
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@50211071
      server=CraftServer{serverName=NachoSpigot,serverVersion=git-NachoSpigot-"3faab47",minecraftVersion=1.8.8}
      file=plugins/ProtocolLib (7).jar
      description=org.bukkit.plugin.PluginDescriptionFile@58c8715
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@67919f99
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@35cdc26f
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    11.0.13
  Server:
    git-NachoSpigot-"3faab47" (MC: 1.8.8)

**Comment by dmulloy2** [comment]
yeah that version is a few years old at this point
