### ISSUE TITLE
ProtocolLib tell me to report this bug :V

### ISSUE THREAD

**Issue by SussyBob** [dmulloy2/ProtocolLib#1480]
Doesnt know what the bug is but ProtocolLib tell me to report this bug :V

[11:11:04 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to inject channel futures.
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:225)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:970)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:402)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:286)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
  }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1418)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:122)
  	... 11 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4b6a4b24[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@531d2a8b
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5a002c11
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@54f408a
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@1ce5086c
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@26163009
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7dade07e
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@368b6a16
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-133,minecraftVersion=1.18.1}
        library=ProtocolLib v4.5.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@33b638f9
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@666d9596
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@f893d00
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.18.1)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@3bf472d0
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@40c18d36[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@2fbed35a
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@531d2a8b
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@25f5221e
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@63d27a9d
      commandProtocol=com.comphenix.protocol.CommandProtocol@7ba8e6c5
      commandPacket=com.comphenix.protocol.CommandPacket@22d5cee9
      commandFilter=com.comphenix.protocol.CommandFilter@2ebcfd7f
      packetLogging=com.comphenix.protocol.PacketLogging@5e4a7ca7
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@62e82765
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-133,minecraftVersion=1.18.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6ec60f57
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@2a7abfed
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    17.0.1
  Server:
    git-Paper-133 (MC: 1.18.1)

ProtocolLib V4.5.1
Minecraft V1.18.1
Paper-Bukkit

**Comment by johnfriedrich** [comment]
Your ProtocolLib version is ancient, try the latest from the build server
