### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by LuckyBastar12** [dmulloy2/ProtocolLib#1490]
java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 36 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketHandshakingInSetProtocol
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_C00Handshake$java_lang_Object.<init>(Unknown Source)
        ... 41 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@641633b8[
      memoryAddress=139649485987856
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@4dae1108
      chunk=Chunk(59b1443f: 1%, 90112/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=27
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@321826a0
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=27
      writerIndex=27
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3394c346[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@19c8df61
        packetListeners=[PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicExtension, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2f2f0e20
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1a7cede0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@f67831a
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@500b6640
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2d759aa5
        reporter=com.comphenix.protocol.ProtocolLib$1@7023c6f
        server=CraftServer{serverName=Mohist,serverVersion=git-Mohist-1.12.2-298,minecraftVersion=1.12.2}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4920e186
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e34e66
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@519a77a9
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false

**Comment by derklaro** [comment]
Mohist is not supported
