### ISSUE TITLE
a server error

### ISSUE THREAD

**Issue by Opensitoo** [dmulloy2/ProtocolLib#1493]
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.utility.ChatExtensions
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62)
        at com.rylinaux.plugman.util.PluginUtil.enableAll(PluginUtil.java:72)
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:101)
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:751)
        at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:344)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:308)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:642)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:548)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@2245c052[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@71bdaf5b
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@1a660acc
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@7d6de645
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-ea452ce,minecraftVersi
on=1.7.10}
      file=plugins/ProtocolLib-4.5.0 (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@3294190a
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@38120162
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@73eed41a
    ]
  Version:
    ProtocolLib v4.5.0
  Java Version:
    1.8.0_312
  Server:
    git-PaperSpigot-ea452ce (MC: 1.7.10)

**Comment by derklaro** [comment]
This is too historic to support, from the protocol version and the server version side. Please update to get support...

**Comment by dmulloy2** [comment]
if you're still using 1.7.10, give 3.7.0 a try: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
