### ISSUE TITLE
INTERNAL ERROR: Cannot enable ProtocolLib.

### ISSUE THREAD

**Issue by Aditya8Prakash** [dmulloy2/ProtocolLib#1498]
I don't know why is this happening ...

ERROR :

[07:45:43 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to inject channel futures.
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:225)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:970)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:402)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:286)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
  }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1418)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:122)
        ... 11 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1c7d9abf[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@44408d42
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@36bec05b
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1c2043ff
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@6cf89aa6
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2c9230e6
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6c6e8137
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5aca91ab
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-167,minecraftVersion=1.18.1}
        library=ProtocolLib v4.5.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7f1ddde6
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@195c169f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@155fb01d
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.18.1)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@5bd14046
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@17eaf59c[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@524b33b5
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@44408d42
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3afcaeb9
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@6b7e1ad0
      commandProtocol=com.comphenix.protocol.CommandProtocol@11db00d8
      commandPacket=com.comphenix.protocol.CommandPacket@1a865fcd
      commandFilter=com.comphenix.protocol.CommandFilter@4550b342
      packetLogging=com.comphenix.protocol.PacketLogging@5ee389a2
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@17779f66
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-167,minecraftVersion=1.18.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@3f27d272
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@3dc194a9
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    17.0.1
  Server:
    git-Paper-167 (MC: 1.18.1)

**Comment by derklaro** [comment]
Please update to the latest ProtocolLib dev version (4.8.0, see readme for instructions) to get 1.18 support

**Comment by Aditya8Prakash** [comment]
thanks
