### ISSUE TITLE
INTERNAL ERROR: Cannot enable ProtocolLib

### ISSUE THREAD

**Issue by X00LA** [dmulloy2/ProtocolLib#151]
Got this error when I start my server.
My Server-Setup:
forge-1.8.9-11.15.1.1732-universal
&
spongeforge-1.8.9-1732-3.1.0-BETA-1159
&
Pore-1.0.0-SNAPSHOT

`[Server thread/ERROR] [pore]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:388)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
  	at blue.lapis.pore.impl.PoreServer.loadPlugin(PoreServer.java:170)
  	at blue.lapis.pore.impl.PoreServer.enablePlugins(PoreServer.java:187)
  	at blue.lapis.pore.Pore.onAboutToStart(Pore.java:114)
  	at blue.lapis.pore.launch.PoreBootstrap.onAboutToStart(PoreBootstrap.java:81)
  	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_PoreBootstrap_onAboutToStart8.handle(Unknown Source)
  	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86)
  	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238)
  	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:282)
  	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:184)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
  	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
  	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
  	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
  	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:857)
  	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:279)
  	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:252)
  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.RuntimeException: Cannot find class blue.lapis.pore.impl.entity.CraftPlayer
  	at com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:78)
  	at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:1912)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEntityPlayerClass(MinecraftReflection.java:559)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1014)
  	at com.comphenix.protocol.utility.MinecraftReflection.getPacketClass(MinecraftReflection.java:701)
  	at com.comphenix.protocol.injector.packet.LegacyPacketRegistry.getPacketRegistry(LegacyPacketRegistry.java:188)
  	at com.comphenix.protocol.injector.packet.LegacyPacketRegistry.initialize(LegacyPacketRegistry.java:64)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initializeLegacy(PacketRegistry.java:118)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:90)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:365)
  	at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
  	at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
  	... 40 more
  Caused by: java.lang.ClassNotFoundException: blue.lapis.pore.impl.entity.CraftPlayer
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at com.comphenix.protocol.utility.ClassSource$1.loadClass(ClassSource.java:37)
  	at com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:69)
  	... 51 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLibrary@701dbf0[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6e9b0670
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.BukkitUpdater@67dfbbb1
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@1fe63072
      server=blue.lapis.pore.impl.PoreServer@4ac3908f
      file=./bukkit-plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@785f2683
      dataFolder=./bukkit-plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@531d310e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=./bukkit-plugins/ProtocolLib/config.yml
      logger=java.util.logging.Logger@2395f0d7
    ]
  Version:
    ProtocolLib v3.7-SNAPSHOT-b229
  Java Version:
    1.8.0_72
  Server:
    1.0.0-SNAPSHOT-git(master-7b6e647)-jnks286@DEV

[10:03:02] [Server thread/INFO] [pore.ProtocolLib]: Disabling ProtocolLib v3.7-SNAPSHOT-b229`

**Comment by games647** [comment]
Sponge doesn't support packet manipulation.

**Comment by dmulloy2** [comment]
We currently do not support Sponge.
