### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Freshtana** [dmulloy2/ProtocolLib#1514]
Find this in my backend server when restart.

```
[11:22:41 INFO]: Error Cannot compile structure. Disabing compiler. (java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @22de5a) occured in com.comphenix.protocol.reflect.compiler.BackgroundCompiler@36be258b.
[11:22:41 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @22de5a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@1d2bd696[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public net.minecraft.server.v1_16_R3.MinecraftKey net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.tag, public net.minecraft.server.v1_16_R3.PacketDataSerializer net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.data]
      defaultFields={public net.minecraft.server.v1_16_R3.MinecraftKey net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.tag=0, public net.minecraft.server.v1_16_R3.PacketDataSerializer net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.data=1}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1a331a69[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2dcd6c36
        packetListeners=[PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=11]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=nLogin, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19], SET_SLOT[class=PacketPlayOutSetSlot, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6e11807f
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2d3ad964
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2f587ef8
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@69320bf9
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins/ProtocolLib (3).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@70c8652d
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-794,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@659fc7d9
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1254a437
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@718c2ed0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@36be258b[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@2647a5e8=[com.comphenix.protocol.injector.StructureCache$1@4ff768fb]}
      listenerLock=java.lang.Object@78b5182e
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@685f5346
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@2f8aa1bb
      reporter=com.comphenix.protocol.ProtocolLib$1@70c8652d
      unknownPermGenBean=java.lang.Object@5b4eb401
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16.0.2
  Server:
    git-Paper-794 (MC: 1.16.5)
```

**Comment by derklaro** [comment]
Try updating to ProtocolLib 4.8.0 (this is a dev build, see the readme for instructions) and comment again if the issue persists.
