### ISSUE TITLE
Error starting ProtocolLib on Magma Server

### ISSUE THREAD

**Issue by Electronprod** [dmulloy2/ProtocolLib#1516]
Error:

[11:43:46] [Server thread/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/compiler/StructureCompiler
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler.initializeCompiler(BackgroundCompiler.java:131)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler.<init>(BackgroundCompiler.java:109)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:159)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:410)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:349)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:417)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: Failed to remap class com.comphenix.protocol.reflect.compiler.StructureCompiler
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:208)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 12 more
  Caused by: java.lang.NoClassDefFoundError: org/magmafoundation/magma/remapper/proxy/ProxyClassWriter
        at org.magmafoundation.magma.remapper.remappers.ReflectionMethodRemapper.redirectVirtual(ReflectionMethodRemapper.java:150)
        at org.magmafoundation.magma.remapper.remappers.ReflectionMethodRemapper.visitMethodInsn(ReflectionMethodRemapper.java:114)
        at org.objectweb.asm.tree.MethodInsnNode.accept(Unknown Source)
        at org.objectweb.asm.tree.InsnList.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
        at org.magmafoundation.magma.remapper.utils.RemappingUtils.remapFindClass(RemappingUtils.java:113)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:196)
        ... 16 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@76ef63ce[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@23e345be
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@301cdea4
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@520fb11a
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@5f734986
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@66843963
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@303b22e9
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@3c18450c
        reporter=com.comphenix.protocol.ProtocolLib$1@1f13c295
        server=CraftServer{serverName=Magma,serverVersion=88f081a-DEV,minecraftVersion=1.12.2}
        library=ProtocolLib v4.4.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1de1f297
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@71067b99
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@204e0be6
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@43a95760
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@17970574[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@23e345be
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.BukkitUpdater@4e4790a
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@1d14bd00
      commandProtocol=com.comphenix.protocol.CommandProtocol@4ed27d8
      commandPacket=com.comphenix.protocol.CommandPacket@3831d1e5
      commandFilter=com.comphenix.protocol.CommandFilter@1f3ac3c0
      packetLogging=com.comphenix.protocol.PacketLogging@277e919a
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@4a40a14a
      server=CraftServer{serverName=Magma,serverVersion=88f081a-DEV,minecraftVersion=1.12.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7cc8ff1e
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@3c18450c
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@6684a2eb
    ]
  Version:
    ProtocolLib v4.4.0
  Java Version:
    1.8.0_282
  Server:
    88f081a-DEV (MC: 1.12.2)

**Comment by Electron696** [comment]
![image](https://user-images.githubusercontent.com/80621922/154026845-baf34526-f61a-418c-b8ba-457e6a3a244f.png)
Version of magma

**Comment by derklaro** [comment]
Magma, Mohist etc are not supported.
