### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.

### ISSUE THREAD

**Issue by Leaziurd** [dmulloy2/ProtocolLib#1527]
Just don't load :(

09:17:03 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Unable to inject channel futures.
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:225)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:970)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:402)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:1016)
  	at org.bukkit.Bukkit.reload(Bukkit.java:897)
  	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
  	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:907)
  	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:870)
  	at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
  	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
  	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1471)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
  }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1418)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:122)
  	... 19 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@496fc5e9[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@214d3246
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7a249f8
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1d3ecfe2
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@2ac91121
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@62dec93c
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@77a6b116
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@1c8c21df
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-207,minecraftVersion=1.18.1}
        library=ProtocolLib v4.5.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7eae7b76
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@58c602e0
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5cba0b34
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.18.1)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@7b9bce8f
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@a6ad91c[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@5b322ef0
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@214d3246
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@338be674
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@3fe4b89a
      commandProtocol=com.comphenix.protocol.CommandProtocol@1aaee65f
      commandPacket=com.comphenix.protocol.CommandPacket@50a11e54
      commandFilter=com.comphenix.protocol.CommandFilter@3cf5fa72
      packetLogging=com.comphenix.protocol.PacketLogging@26cfb51e
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@4bbe3386
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-207,minecraftVersion=1.18.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1335c71b
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@38f64aca
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    17.0.2
  Server:
    git-Paper-207 (MC: 1.18.1)

[09:17:03 INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.1

**Comment by derklaro** [comment]
Please update to v4.8.0 (latest release) for Minecraft 1.18 support

**Comment by Leaziurd** [comment]
thanks
