### ISSUE TITLE
5.0.0 refuses a plugin to load. - INTERCEPT_INPUT_BUFFER

### ISSUE THREAD

**Issue by CloudeLecaw** [dmulloy2/ProtocolLib#1536]
Well in the new 5.0.0 Build 551 i noticed that one of our plugin is not longer loading on startup
With 4.8.0 Build 547 it is loading

Error from console
```
[02:17:18 INFO]: [PacketLimiter] Enabling PacketLimiter v1.0.0
[02:17:18 ERROR]: [Minecraft] Error occurred while enabling PacketLimiter v1.0.0 (Is it up to date?)
java.lang.NoSuchFieldError: INTERCEPT_INPUT_BUFFER
        at ca.spottedleaf.packetlimiter.PacketListener.<init>(PacketListener.java:34) ~[PacketLimiter_1.0.1.jar:?]
        at ca.spottedleaf.packetlimiter.PacketLimiter.onEnable(PacketLimiter.java:53) ~[PacketLimiter_1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-241]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:17:18 INFO]: [PacketLimiter] Disabling PacketLimiter v1.0.0
```

**Comment by derklaro** [comment]
Hi,

Thanks for the report! It looks like they enabled buffer interception which is no longer a thing. I just went through the source code and there is no reason to do so at all...
Here are two things you can do:
 - remove the buffer interception option from the source
 - use the inbuild packet limiter of paper instead (https://docs.papermc.io/paper/reference/paper-global-configuration#incoming-packet-spam-threshold)
