### ISSUE TITLE
INTERNAL ERROR: Cannot enable ProtocolLib.

### ISSUE THREAD

**Issue by MuzafferKaya** [dmulloy2/ProtocolLib#1537]
[13:01:47 INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.1
[13:01:47 INFO]: [ProtocolLib] Started structure compiler thread.
[13:01:47 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalAccessError: tried to access class com.comphenix.protocol.injector.netty.ProtocolInjector$1 from class com.comphenix.protocol.injector.netty.ProtocolInjector
        at com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:146)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:970)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:402)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:382)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:341)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:801)
        at org.bukkit.Bukkit.reload(Bukkit.java:565)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:694)
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1260)
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1072)
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:55)
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:718)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:615)
        at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1dcf95f5[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@661bc319
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@68965253
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@488a2d6c
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@290b79b5
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@11b06486
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4beea829
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@6e18b1a8
        reporter=com.comphenix.protocol.ProtocolLib$1@52160d75
        server=CraftServer{serverName=NachoSpigot,serverVersion=1.8.8,minecraftVersion=1.8.8}
        library=ProtocolLib v4.5.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3224c485
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4a2e86fe
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6a539f7e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@56672e5e
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@2cf04266[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@5bdaf523
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@661bc319
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@65fd81d0
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@13235a7e
      commandProtocol=com.comphenix.protocol.CommandProtocol@7c59839a
      commandPacket=com.comphenix.protocol.CommandPacket@702602df
      commandFilter=com.comphenix.protocol.CommandFilter@79dcee0a
      packetLogging=com.comphenix.protocol.PacketLogging@70a5abe5
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@40d0b338
      server=CraftServer{serverName=NachoSpigot,serverVersion=1.8.8,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@207107
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@6e18b1a8
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@43351903
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    1.8.0_321
  Server:
    1.8.8 (MC: 1.8.8)

[13:01:47 INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.1

**Comment by derklaro** [comment]
Hi,

can you try updating to 4.8.0 (latest release) and see if the error still persists?
