### ISSUE TITLE
Commands do not work and says cannot enable.

### ISSUE THREAD

**Issue by DilanPlayz** [dmulloy2/ProtocolLib#1540]
<html>
<body>

Stack Trace:
--
253 | java.lang.ExceptionInInitializerError
254 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
255 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
256 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
257 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
258 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
259 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
260 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
261 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
262 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
263 | at java.base/java.lang.Thread.run(Thread.java:833)
264 | Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
265 | fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}],
266 | methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
267 | constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
268 | }}
269 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
270 | at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
271 | at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
272 | at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
273 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
274 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
275 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
276 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
277 | at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
278 | at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
279 | ... 10 more
280 | Dump:
281 | Sender:
282 | com.comphenix.protocol.ProtocolLib@7d7921a[
283 | statistics=<null>
284 | backgroundCompiler=<null>
285 | packetTask=-1
286 | tickCounter=0
287 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@25355375
288 | configExpectedMod=-1
289 | updater=com.comphenix.protocol.updater.SpigotUpdater@308a00eb
290 | redirectHandler=<null>
291 | commandProtocol=<null>
292 | commandPacket=<null>
293 | commandFilter=<null>
294 | packetLogging=<null>
295 | skipDisable=false
296 | isEnabled=true
297 | loader=org.bukkit.plugin.java.JavaPluginLoader@873a8e3
298 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-247,minecraftVersion=1.18.2}
299 | file=plugins/ProtocolLib.jar
300 | description=org.bukkit.plugin.PluginDescriptionFile@74b38de2
301 | dataFolder=plugins/ProtocolLib
302 | classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
303 | naggable=true
304 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
305 | configFile=plugins/ProtocolLib/config.yml
306 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@1b7f1c3b
307 | ]
308 | Version:
309 | ProtocolLib v4.5.1
310 | Java Version:
311 | 17.0.1
312 | Server:
313 | git-Paper-247 (MC: 1.18.2)

</body>
</html>Stack Trace:
  java.lang.ExceptionInInitializerError
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
  	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
  	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
  }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
  	... 10 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@7d7921a[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@[253](https://aternos.org/log/#L253)55375
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@[308](https://aternos.org/log/#L308)a00eb
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@873a8e3
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-247,minecraftVersion=1.18.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@74b38de2
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@1b7f1c3b
    ]
  Version:
    ProtocolLib v4.5.1

I was told to copy paste this by my server log.
    17.0.1
  Server:
    git-Paper-247 (MC: 1.18.2)

**Comment by derklaro** [comment]
Hi,
please update to the latest release of ProtocolLib (v4.8.0) for 1.18 support.
