### ISSUE TITLE
ProtocolLib error on Magma 1.16.5 server (impacts Citizens NPCs, other impacts unknown)

### ISSUE THREAD

**Issue by scarlettcloud** [dmulloy2/ProtocolLib#1542]
**Description**
ProtocolLib is throwing errors in the console for my server. Running a Magma 1.16.5 server with Forge version 26.2.5; I understand if this server type is not supported just want to make sure you were aware! I'm still setting up the server so I'm not exactly sure what the impacts are, but I do notice it every time that Citizens NPC tries to load it's save file. NPCs I have created since installing ProtocolLib do not spawn, but are saved in the Citizens config.

**To Reproduce**
1. Create Citizens NPC (/npc create Test --type villager)
2. /citizens save
3. Restart server

**Expected behavior**
The villager NPC should always spawn in the location created. Console reads a WARN at task 23 in Citizens NPC, but thrown by ProtocolLib.

**Version Info**
/home/mch/multicraft/servers/server139395/plugins/ProtocolLib/dump-2022-03-14_12.57.57.txt

**Additional context**
[14.03 13:53:32] [Server] [Netty Epoll Server IO #0/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
[14.03 13:53:32] [Server]   If this problem hasn't already been reported, please open a ticket
[14.03 13:53:32] [Server]   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[14.03 13:53:32] [Server]   Stack Trace:
[14.03 13:53:32] [Server]   java.lang.RuntimeExceptionError occured while instancing generated class.
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[14.03 13:53:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14.03 13:53:32] [Server]   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[14.03 13:53:32] [Server]   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[14.03 13:53:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[14.03 13:53:32] [Server]   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[14.03 13:53:32] [Server]   	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[14.03 13:53:32] [Server]   	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[14.03 13:53:32] [Server]   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[14.03 13:53:32] [Server]   	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[14.03 13:53:32] [Server]   	at java.lang.Thread.run(Thread.java:748)
[14.03 13:53:32] [Server]   Caused byjava.lang.reflect.InvocationTargetException
[14.03 13:53:32] [Server]   	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14.03 13:53:32] [Server]   	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14.03 13:53:32] [Server]   	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14.03 13:53:32] [Server]   	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
[14.03 13:53:32] [Server]   	... more
[14.03 13:53:32] [Server]   Caused byjava.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
[14.03 13:53:32] [Server]   	at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_CHandshakePacket$java_lang_Object.<init>(Unknown Source)
[14.03 13:53:32] [Server]   	... more
[14.03 13:53:32] [Server]   Dump:
[14.03 13:53:32] [Server]   Parameters
[14.03 13:53:32] [Server]     io.netty.buffer.PooledUnsafeDirectByteBuf@334d64a6[
[14.03 13:53:32] [Server]       memoryAddress=140633050189840
[14.03 13:53:32] [Server]       recyclerHandle=io.netty.util.Recycler$DefaultHandle@5ce1fc32
[14.03 13:53:32] [Server]       chunk=Chunk(113b21c1%, 16384/16777216)
[14.03 13:53:32] [Server]       handle=4611686018427389953
[14.03 13:53:32] [Server]       memory=java.nio.DirectByteBuffer[pos=lim=16777216 cap=16777216]
[14.03 13:53:32] [Server]       offset=8192
[14.03 13:53:32] [Server]       length=21
[14.03 13:53:32] [Server]       maxLength=32
[14.03 13:53:32] [Server]       cache=io.netty.buffer.PoolThreadCache@4385f7f4
[14.03 13:53:32] [Server]       tmpNioBuf=<null>
[14.03 13:53:32] [Server]       allocator=PooledByteBufAllocator(directByDefaulttrue)
[14.03 13:53:32] [Server]       refCnt=1
[14.03 13:53:32] [Server]       readerIndex=21
[14.03 13:53:32] [Server]       writerIndex=21
[14.03 13:53:32] [Server]       markedReaderIndex=0
[14.03 13:53:32] [Server]       markedWriterIndex=0
[14.03 13:53:32] [Server]       maxCapacity=2147483647
[14.03 13:53:32] [Server]     ]
[14.03 13:53:32] [Server]     manager:
[14.03 13:53:32] [Server]       com.comphenix.protocol.injector.PacketFilterManager@9cbb602[
[14.03 13:53:32] [Server]         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@420c21ab
[14.03 13:53:32] [Server]         packetListeners=[PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
[14.03 13:53:32] [Server]         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f65827c
[14.03 13:53:32] [Server]         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@32b57c4d
[14.03 13:53:32] [Server]         inputBufferedPackets=[]
[14.03 13:53:32] [Server]         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@669aa7bf
[14.03 13:53:32] [Server]         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4538d3be
[14.03 13:53:32] [Server]         hasClosed=false
[14.03 13:53:32] [Server]         classLoader=org.bukkit.plugin.java.PluginClassLoader@4a823f60
[14.03 13:53:32] [Server]         reporter=com.comphenix.protocol.ProtocolLib$1@76fddf07
[14.03 13:53:32] [Server]         server=CraftServer{serverName=Magma,serverVersion=git-Magma-1.16.5-36.2.27-ffa3128-DEV,minecraftVersion=1.16.5}
[14.03 13:53:32] [Server]         library=ProtocolLib v4.8.0
[14.03 13:53:32] [Server]         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5c277787
[14.03 13:53:32] [Server]         knowsServerPackets=true
[14.03 13:53:32] [Server]         knowsClientPackets=true
[14.03 13:53:32] [Server]         phaseLoginCount=2
[14.03 13:53:32] [Server]         phasePlayingCount=2
[14.03 13:53:32] [Server]         packetCreation=false
[14.03 13:53:32] [Server]         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5334f427
[14.03 13:53:32] [Server]         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@331b1d5
[14.03 13:53:32] [Server]         hasRecycleDistance=true
[14.03 13:53:32] [Server]         minecraftVersion=(MC1.16.5)
[14.03 13:53:32] [Server]         debug=false
[14.03 13:53:32] [Server]       ]
[14.03 13:53:32] [Server]   Sender:
[14.03 13:53:32] [Server]     com.comphenix.protocol.injector.netty.ChannelInjector@1b35d376[

**Comment by scarlettcloud** [comment]
I can provide more information if needed!

**Comment by derklaro** [comment]
Hi,
Magma is not officially supported. But it seems like `net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol` is missing... Maybe we can take a look in v5 to support Mojang Mappings and Magma but I don't see the benifit in doing that 🤔

**Comment by scarlettcloud** [comment]
No worries! I understand. If my players ever give up their modded biomes and mobs I will absolutely be getting rid of it but I'm stuck for now unfortunately.
