### ISSUE TITLE
Problems with Modded Server

### ISSUE THREAD

**Issue by TimeLessHD** [dmulloy2/ProtocolLib#1547]
It always happens if a Player changes something in his/her settings like deactivate Clouds or anything in the Settings, everything still works fine but the error is very annoying everytime someone changes something.

**Ingame Error**
https://i.imgur.com/mbXvIUs.png

**Console Error**
[INFO] Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@2cc13b75.
[24.03 14:21:27] [Server] [ERROR]   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
[24.03 14:21:27] [Server]   If this problem hasn't already been reported, please open a ticket
[24.03 14:21:27] [Server]   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[24.03 14:21:27] [Server]   Stack Trace:
[24.03 14:21:27] [Server]   java.lang.RuntimeExceptionError occured while instancing generated class.
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[24.03 14:21:27] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[24.03 14:21:27] [Server]   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[24.03 14:21:27] [Server]   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[24.03 14:21:27] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[24.03 14:21:27] [Server]   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[24.03 14:21:27] [Server]   	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[24.03 14:21:27] [Server]   	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[24.03 14:21:27] [Server]   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[24.03 14:21:27] [Server]   	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[24.03 14:21:27] [Server]   	at java.base/java.lang.Thread.run(Thread.java:832)
[24.03 14:21:27] [Server]   Caused byjava.lang.reflect.InvocationTargetException
[24.03 14:21:27] [Server]   	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[24.03 14:21:27] [Server]   	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[24.03 14:21:27] [Server]   	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[24.03 14:21:27] [Server]   	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[24.03 14:21:27] [Server]   	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
[24.03 14:21:27] [Server]   	... more
[24.03 14:21:27] [Server]   Caused byjava.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInSettings
[24.03 14:21:27] [Server]   	at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CClientSettingsPacket$java_lang_Object.<init>(Unknown Source)
[24.03 14:21:27] [Server]   	... more
[24.03 14:21:27] [Server]   Dump:
[24.03 14:21:27] [Server]   Parameters
[24.03 14:21:27] [Server]     io.netty.buffer.PooledUnsafeDirectByteBuf@94b3750[
[24.03 14:21:27] [Server]       memoryAddress=140649571402400
[24.03 14:21:27] [Server]       recyclerHandle=io.netty.util.Recycler$DefaultHandle@11dfd190
[24.03 14:21:27] [Server]       chunk=Chunk(3a9dc7cf2%, 270336/16777216)
[24.03 14:21:27] [Server]       handle=4611686194521049090
[24.03 14:21:27] [Server]       memory=java.nio.DirectByteBuffer[pos=lim=16777216 cap=16777216]
[24.03 14:21:27] [Server]       offset=17040
[24.03 14:21:27] [Server]       length=12
[24.03 14:21:27] [Server]       maxLength=16
[24.03 14:21:27] [Server]       cache=io.netty.buffer.PoolThreadCache@db8ae78
[24.03 14:21:27] [Server]       tmpNioBuf=<null>
[24.03 14:21:27] [Server]       allocator=PooledByteBufAllocator(directByDefaulttrue)
[24.03 14:21:27] [Server]       refCnt=1
[24.03 14:21:27] [Server]       readerIndex=12
[24.03 14:21:27] [Server]       writerIndex=12
[24.03 14:21:27] [Server]       markedReaderIndex=0
[24.03 14:21:27] [Server]       markedWriterIndex=0
[24.03 14:21:27] [Server]       maxCapacity=2147483647
[24.03 14:21:27] [Server]     ]
[24.03 14:21:27] [Server]     manager:
[24.03 14:21:27] [Server]       com.comphenix.protocol.injector.PacketFilterManager@32a5e04a[
[24.03 14:21:27] [Server]         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6652ea6e
[24.03 14:21:27] [Server]         packetListeners=[com.guillaumevdn.gcore.lib.legacy_npc.NPCPacketListener@60861206, PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DiscordDeathMessages, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]]]
[24.03 14:21:27] [Server]         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2e5153b2
[24.03 14:21:27] [Server]         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3c93aff9
[24.03 14:21:27] [Server]         inputBufferedPackets=[]
[24.03 14:21:27] [Server]         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@21a9af91
[24.03 14:21:27] [Server]         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@50d93050
[24.03 14:21:27] [Server]         hasClosed=false
[24.03 14:21:27] [Server]         classLoader=org.bukkit.plugin.java.PluginClassLoader@703d43e1
[24.03 14:21:27] [Server]         reporter=com.comphenix.protocol.ProtocolLib$1@74b1353a
[24.03 14:21:27] [Server]         server=CraftServer{serverName=Mohist,serverVersion=1.16.5-818,minecraftVersion=1.16.5}
[24.03 14:21:27] [Server]         library=ProtocolLib v4.8.0
[24.03 14:21:27] [Server]         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@39c5482b
[24.03 14:21:27] [Server]         knowsServerPackets=true
[24.03 14:21:27] [Server]         knowsClientPackets=true
[24.03 14:21:27] [Server]         phaseLoginCount=0
[24.03 14:21:27] [Server]         phasePlayingCount=4
[24.03 14:21:27] [Server]         packetCreation=false
[24.03 14:21:27] [Server]         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7e38921c
[24.03 14:21:27] [Server]         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@63850104
[24.03 14:21:27] [Server]         hasRecycleDistance=true
[24.03 14:21:27] [Server]         minecraftVersion=(MC1.16.5)

**Comment by derklaro** [comment]
Hi, Mohist is not supported. Please stick to Spigot (or a fork) to get support.
