### ISSUE TITLE
causing ERROR - 

### ISSUE THREAD

**Issue by sussybukaa** [dmulloy2/ProtocolLib#1548]
**Make sure you're doing the following**
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

**Describe the question**
protocolLIB not enabling (coming in red when I do /pl)

**API method(s) used**
I tried -
restarting the server multiple times
redownloading protocolLIB
deleted the older files of protocolLIB

**Expected behavior**

**Code**
this is the error 

java.lang.RuntimeException: Unable to inject channel futures.
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:229)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:887)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:392)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:288)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
  }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1416)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:121)
  	... 11 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@684a528[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@27cb8a39
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@63909e2a
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@28bfd54a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@bb18890
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@70d0519d
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.1-SNAPSHOT-b501, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@41157246
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-409,minecraftVersion=1.17.1}
        library=ProtocolLib v4.6.1-SNAPSHOT-b501
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@34497a14
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7b156594
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@9533f01
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.17.1)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@6218b9ba[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@327159a8
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@27cb8a39
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@224ad3d0
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@5e5e4a7c
      commandProtocol=com.comphenix.protocol.CommandProtocol@79acfd64
      commandPacket=com.comphenix.protocol.CommandPacket@412857e0
      commandFilter=com.comphenix.protocol.CommandFilter@3588d846
      packetLogging=com.comphenix.protocol.PacketLogging@19297921
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@770f0bd
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-409,minecraftVersion=1.17.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4e420e4
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.1-SNAPSHOT-b501, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@25ef1d7d
    ]
  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b501
  Java Version:
    16.0.2
  Server:
    git-Paper-409 (MC: 1.17.1)

[19:41:43] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.6.1-SNAPSHOT-b501

**Additional context**
already gave :)

**Comment by derklaro** [comment]
Hi, can you please update your version of protocol lib and see if the issue persists?

**Comment by sussybukaa** [comment]
okay let me try ,it worked thanks :)
