### ISSUE TITLE
New error in #236

### ISSUE THREAD

**Issue by Rockslide** [dmulloy2/ProtocolLib#155]
`[01:46:46] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v9.0.0 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_71]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_71]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.initializeMethods(WrappedDataWatcher.java:836) ~[?:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.initialize(WrappedDataWatcher.java:742) ~[?:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:255) ~[?:?]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.getEntityWatcher(WrappedDataWatcher.java:691) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.registerValues(LibsDisguises.java:225) ~[?:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:76) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
`

**Comment by dmulloy2** [comment]
Welp I guess my brilliant plan to use the fallbacks didn't work. Hopefully the latest builds fixed the data watcher issue.
