### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiaoyaoyuawa** [dmulloy2/ProtocolLib#1550]
[19:21:44 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x747c16cc, L:/127.0.0.1:25565 - R:/127.0.0.1:14558].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x747c16cc, L:/127.0.0.1:25565 - R:/127.0.0.1:14558]
        at com.comphenix.protocol.compat.netty.independent.NettyInjectionFactory.findNetworkManager(NettyInjectionFactory.java:212)
        at com.comphenix.protocol.compat.netty.independent.NettyInjectionFactory.fromChannel(NettyInjectionFactory.java:145)
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:154)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$2.initChannel(NettyProtocolInjector.java:168)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@48f65af8[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1db18fa7
        packetListeners=[net.andylizi.colormotd.bukkit.listener.abstract@14a67527]
        packetInjector=com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$5@16b78836
        playerInjection=com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$4@7b4441eb
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@11fe5e1
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@10428ed2
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3a1e42d4
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@708c85ae
        reporter=com.comphenix.protocol.ProtocolLibrary$1@1dc2d618
        server=CraftServer{serverName=BurritoSpigot,serverVersion=git-BurritoSpigot-"700f01e",minecraftVersion=1.8.8}
        library=ProtocolLib v3.6.4
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@51b21664
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector@16385a27
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@70783abc
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@56f343bf
        debug=false
      ]
  Sender:
    com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector@16385a27[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@42a33acc
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@6b209d9c, container=net.minecraft.server.v1_8_R3.ServerConnection@308eaf6e, previous=[AbstractBootstrap$PendingRegistrationPromise@53bd38e3(success)], current=com.comphenix.protocol.compat.netty.independent.NettyBootstrapList@626ddf60, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@d4e62cc, container=net.minecraft.server.v1_8_R3.ServerConnection@308eaf6e, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.compat.netty.independent.NettyInjectionFactory@48fe59d4
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@72be1a08
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@7e244de0
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@8208ea
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@3a88c1d7
      invoker=com.comphenix.protocol.injector.PacketFilterManager@48f65af8
      reporter=com.comphenix.protocol.ProtocolLibrary$1@1dc2d618
      debug=false
    ]
  Version:
    ProtocolLib v3.6.4
  Server:
    git-BurritoSpigot-"700f01e" (MC: 1.8.8)

**Comment by derklaro** [comment]
Hi, please update to ProtocolLib 4.8.0 (latest release) and see if the issue persists
