### ISSUE TITLE
Problem while booting the server

### ISSUE THREAD

**Issue by Coffister** [dmulloy2/ProtocolLib#1554]
Hi, everyone

I have this problem with few plugins past days.
I don't know what's wrong so I can't give you ways to reproduce the error, so I will just paste a console output here.

Hope someone had the same problem and could help me with it.

**Console Output** 

`[16:32:03 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:288)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        ... 10 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@368106df[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1d3b8033
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3b081500
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@1923e401
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-409,minecraftVersion=1.17.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@88589f8
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@32a516e9
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    16.0.1
  Server:
    git-Paper-409 (MC: 1.17.1)
`

Version: 1.17.1 PaperMC (+ ViaVersion)

Plugin list:
 AuthMe 
 UTitleAuth
 DiscordSRV
 Essentials
 LuckPerms
 niSlots
 ViaVersion
 

Best regards, Coffister.

**Comment by derklaro** [comment]
Hi, please try updating ProtocolLib to v4.8.0 (latest release) and see if the issue persists

**Comment by Coffister** [comment]
I managed to fix it minutes after posting a issue, sorry for opening a issue without reading other issues.

Version I used: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
