### ISSUE TITLE
WrappedVillagerData cannot resolve Vanilla VillagerType

### ISSUE THREAD

**Issue by kennytv** [dmulloy2/ProtocolLib#1557]
**Describe the bug**
On a 1.18.2 server, WrappedVillagerData cannot get the nms VillagerType (and profession?) from the Bukkit counterpart

**To Reproduce**
```java
final WrappedVillagerData wrappedVillagerData = WrappedVillagerData.fromValues(WrappedVillagerData.Type.PLAINS, WrappedVillagerData.Profession.NONE, 1);
```

```
Unable to find field PLAINS in class net.minecraft.world.entity.npc.VillagerType.
java.lang.IllegalArgumentException: Unable to find field PLAINS in class net.minecraft.world.entity.npc.VillagerType.
        at com.comphenix.protocol.reflect.ExactReflection.getField(ExactReflection.java:115) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.ExactReflection.getField(ExactReflection.java:114) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.ExactReflection.getField(ExactReflection.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:87) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.EnumWrappers$FauxEnumConverter.getGeneric(EnumWrappers.java:912) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.EnumWrappers$FauxEnumConverter.getGeneric(EnumWrappers.java:893) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedVillagerData.fromValues(WrappedVillagerData.java:53) ~[ProtocolLib.jar:?]
```

**Version Info**
https://paste.gg/p/anonymous/97703081f9ae43d7996a3c5efe238069

**Comment by derklaro** [comment]
ftr: I took a quick look over the problem and it seems like that the field names are no longer matching the enum field names. I think accessing them via the registry rather than using direct field access will be the best way to keep up for future updates 🤔
