### ISSUE TITLE
ProtocolLib Load Error

### ISSUE THREAD

**Issue by Matehearlrr** [dmulloy2/ProtocolLib#1567]
**Describe the bug**

So basically protolib says it cannot load it's own files

**To Reproduce**

**Expected behavior**

The files should load but it dosn't because... i dont know why.

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

Here's all the information about the error. Hope you have a nice day i didnt know how to recreate this on another server.

[20:58:26 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:68)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:198)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unsupported class file major version 61
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:409)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 9 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@440b8f5b[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@74165fc8
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6e6bf967
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@6b089843
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-db6de12-18fbb24,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1c3716f7
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1cbc5c53
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@4dcc9bfc
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    17.0.2
  Server:
    git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
[Log.txt](https://github.com/dmulloy2/ProtocolLib/files/8422808/Log.txt)
[Log.txt](https://github.com/dmulloy2/ProtocolLib/files/8422810/Log.txt)

**Comment by derklaro** [comment]
Please upgrade ProtocolLib to 4.8.0
