### ISSUE TITLE
Killed server by ProtocolLib

### ISSUE THREAD

**Issue by GabrielSTF** [dmulloy2/ProtocolLib#1572]
Stack Trace:
java.lang.RuntimeException: Unable to inject channel futures.
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:225)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:970)
at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:402)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1, banned: 0], return={
methods=[{modifiers=[required: 0, banned: 0], params=[{Type: input instanceof class java.net.InetAddress, Index: 0}, {Type: input instanceof int, Index: 1}], paramCount=2}],
constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class net.minecraft.server.dedicated.DedicatedServer, Index: null}], paramCount=1}]
}}
at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getServerConnectionClass(MinecraftReflection.java:1418)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.inject(ProtocolInjector.java:122)
... 11 more
Dump:
manager:
com.comphenix.protocol.injector.PacketFilterManager@34465a9f[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@b903a05
packetListeners=[]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2729f26e
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@25add172
interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@23b9f5fa
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2973a39a
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@41a18e58
hasClosed=false
classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
reporter=com.comphenix.protocol.ProtocolLib$1@66b6c3c9
server=CraftServer{serverName=Paper,serverVersion=git-Paper-283,minecraftVersion=1.18.2}
library=ProtocolLib v4.5.1
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1ff344bd
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=0
packetCreation=false
spigotInjector=<null>
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1bbd4901
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2d137243
hasRecycleDistance=true
minecraftVersion=(MC: 1.18.2)
loginPackets=com.comphenix.protocol.injector.LoginPackets@abcaab8
debug=false
]
Sender:
com.comphenix.protocol.ProtocolLib@16651314[
statistics=<null>
backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@14bfa39d
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@b903a05
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@22085a23
redirectHandler=com.comphenix.protocol.ProtocolLib$2@4d8ecdb0
commandProtocol=com.comphenix.protocol.CommandProtocol@7053ff20
commandPacket=com.comphenix.protocol.CommandPacket@199919fc
commandFilter=com.comphenix.protocol.CommandFilter@79a081ae
packetLogging=com.comphenix.protocol.PacketLogging@42f83067
skipDisable=false
isEnabled=true
loader=org.bukkit.plugin.java.JavaPluginLoader@2dbd6de7
server=CraftServer{serverName=Paper,serverVersion=git-Paper-283,minecraftVersion=1.18.2}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@7c3ad755
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@292e7cf
]
Version:
ProtocolLib v4.5.1
Java Version:
17.0.2
Server:
git-Paper-283 (MC: 1.18.2)

**Comment by CloudeLecaw** [comment]
ProtocolLib v4.5.1  with 1.18.2?... you should use the version fopr 1.18,x that is 4.8.0
https://github.com/dmulloy2/ProtocolLib/releases/tag/4.8.0
