### ISSUE TITLE
[1.16.5]Console asks me to report this.It happens when I use the client to Ping the server. After inspection, it is because it is installed ServerListPlus and ProtocolLib at the same time.Is there any way to fix the bug while keeping the two plugins?

### ISSUE THREAD

**Issue by 470014599zzp** [dmulloy2/ProtocolLib#1582]
[22:08:02][Netty Server IO #4][ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:237)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:128)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:312)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at net.minecraft.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:84)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:221)
        ... 40 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketHandshakingInSetProtocol
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_CHandshakePacket$java_lang_Object.<init>(Unknown Source)
        ... 45 more
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@238d4a3[
      memoryAddress=2172264742976
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@3f77153c
      chunk=Chunk(ef5684d: 1%, 16384/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=24
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@50e5f0a5
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=24
      writerIndex=24
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4cc9ae93[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1777f05e
        packetListeners=[PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1dfd47a9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3c6368f5
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3ddff4dc
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@15821639
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2428f69d
        reporter=com.comphenix.protocol.ProtocolLib$1@62b5db2f
        server=CraftServer{serverName=LoliServer,serverVersion=1.16.5-ccb19cf,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@70d4622
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@57927f0f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@82f8c52
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@14bcbbd6[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@3ff6762d
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@13659288
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@367727a9
      originalChannel=[id: 0x278d91ea, L:/192.168.1.105:10051 - R:/14.125.58.107:3373]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@367727a9, previous=[id: 0x278d91ea, L:/192.168.1.105:10051 - R:/14.125.58.107:3373], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@387be9fa, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@7b5ddaf
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@8f0e89f
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@55d00c2
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@57927f0f
      processor=com.comphenix.protocol.injector.NetworkProcessor@4b7ffce1
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 24)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@42ec97f4
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    11.0.2
  Server:
    1.16.5-ccb19cf (MC: 1.16.5)

**Comment by HarperV** [comment]
Same issue!
