### ISSUE TITLE
Getting entity by id causing error

### ISSUE THREAD

**Issue by Jalau11** [dmulloy2/ProtocolLib#159]
The method ProtocolLibrary.getProtocolManager().getEntityFromID(...) is currently broken for me. It throws errors because the tracker field was not found, which seems, after checking, to have vanished from the entity class.

There error broadcasted in the console is this one:
`[19:37:18] [Server thread/WARN]: FieldAccessException: Cannot find entity from ID 31.
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:243)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982)
[19:37:18] [Server thread/WARN]: 	at me.jalau.character.CharacterNPC$4.onPacketSending(CharacterNPC.java:277)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1059)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTracker.a(EntityTracker.java:258)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerChunk.b(PlayerChunk.java:153)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerChunkMap.flush(PlayerChunkMap.java:185)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.WorldServer.doTick(WorldServer.java:253)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:776)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[19:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[19:37:18] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:37:18] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Unable to find a field tracker with the type net.minecraft.server.v1_9_R1.Entity in net.minecraft.server.v1_9_R1.EntityTrackerEntry
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:369)
[19:37:18] [Server thread/WARN]: 	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:228)
[19:37:18] [Server thread/WARN]: 	... 27 more`

**Comment by dmulloy2** [comment]
What build of ProtocolLib are you using?

**Comment by Jalau11** [comment]
v.3.6.5. I downloaded it yesterday from the jenkins build server.

**Comment by dmulloy2** [comment]
Use the latest 3.7 builds, this issue has been fixed.

**Comment by NoChanceSD** [comment]
@dmulloy2 Is your website down? I can't access the dev builds

**Comment by dmulloy2** [comment]
Should be back up, sometimes it randomly goes down
