### ISSUE TITLE
Error loading the plugin

### ISSUE THREAD

**Issue by mariocr4ft** [dmulloy2/ProtocolLib#1604]
This is what it says when i boot it. I tried to change the version of the plugin, but still the same issue. If the problem is mine, im sorry for disturbing, 
===== STACK TRACE =====
  java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.utility.MinecraftReflection
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:78)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:356)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:56)
        at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:377)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:369)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:328)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:191)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:526)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'com.google.common.cache.Cache com.google.common.cache.CacheBuilder.build(com.google.common.cache.CacheLoader)' [in thread "Server thread"]
        at com.comphenix.protocol.utility.MinecraftReflection.<clinit>(MinecraftReflection.java:155)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:259)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:308)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:190)
        ... 2 more
            ===== DUMP =====
  Sender:
    com.comphenix.protocol.ProtocolLibrary@772232fb[
      statistisc=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7c11acd3
      configExpectedMod=-1
      updater=com.comphenix.protocol.metrics.Updater@6575a1d1
      logger=org.bukkit.plugin.PluginLogger@a4467b1
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@440f86d3
      server=CraftServer{serverName=Spigot,serverVersion=1.8.8-R0.1-SNAPSHOT,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib-3.4.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2f4193d3
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@27df5f6f
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@a4467b1
    ]
  Version:
    ProtocolLib v3.4.0
  Server:
    1.8.8-R0.1-SNAPSHOT (MC: 1.8.8)

**Comment by derklaro** [comment]
Please update to a more recent version of ProtocolLib (https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar) to get support (v3.4 is very old and unsupported)
