### ISSUE TITLE
[1.16.5] BUG

### ISSUE THREAD

**Issue by viminio** [dmulloy2/ProtocolLib#1605]
https://mclo.gs/wOZR0GF

OR

[00:37:50 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 32!
[00:37:50 INFO]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@3ea67bc8.
[00:37:50 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.base/java.lang.Thread.run(Thread.java:831)
  Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedConstructorAccessor123.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 39 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInSettings
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CClientSettingsPacket$java_lang_Object.<init>(Unknown Source)
        ... 44 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@48291e6d[
      memoryAddress=281468970539040
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@61813a16
      chunk=Chunk(1218fc4: 2%, 294912/16777216)
      handle=4611686572478171145
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=75792
      length=12
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@3efcc00c
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=12
      writerIndex=12
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3008eee1[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5b14507c
        packetListeners=[PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=nLogin, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[]]], com.comphenix.protocol.async.NullPacketListener@327e2325, PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=nLogin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@46642308
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@426663fe
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35eef2b5
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4c80c3c4
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@56553382
        reporter=com.comphenix.protocol.ProtocolLib$1@2b9bd53f
        server=CraftServer{serverName=Mohist,serverVersion=1.16.5-1021,minecraftVersion=1.16.5}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@182a109c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=7
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2cde4dfc
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@df4cd57
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@3ea67bc8[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1b752604
      player=CraftPlayer{name=EnergeticOoak32}
      updated=CraftPlayer{name=EnergeticOoak32}
      playerName=EnergeticOoak32
      playerConnection=net.minecraft.network.play.ServerPlayNetHandler@569fa780
      networkManager=net.minecraft.network.NetworkManager@5bcd5d38
      originalChannel=[id: 0xd75b85f7, L:/172.18.0.2:25565 - R:/189.45.207.104:50603]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@5bcd5d38, previous=[id: 0xd75b85f7, L:/172.18.0.2:25565 - R:/189.45.207.104:50603], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@e1c4973, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@25144c97
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@1401e190
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@5f74af9f
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2cde4dfc
      processor=com.comphenix.protocol.injector.NetworkProcessor@34b8b0c9
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 12)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@19469911
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    16.0.2
  Server:
    1.16.5-1021 (MC: 1.16.5)

**Comment by derklaro** [comment]
Mohist is not supported. Please use Spigot (or a fork of Spigot like Paper) to get support.

**Comment by Rothes** [comment]
Try [CatServer](https://catmc.org/) instead.

**Comment by derklaro** [comment]
Don't use any "hybrid" server at all...

**Comment by young1112** [comment]
Please I want to buy script

**Comment by young1112** [comment]
@Rothes please I want to buy script

**Comment by viminio** [comment]
> Try [CatServer](https://catmc.org/) instead. (if you insist)

this catserver has a bad reputation in the spigot&forge hybrids
