### ISSUE TITLE
Client Packet Issues on Spigot 1.19

### ISSUE THREAD

**Issue by frontlinegeek** [dmulloy2/ProtocolLib#1609]
After updating my server to 1.19 (Test copy), I get the error below when clients connect to the server:

**To Reproduce**
Simply refresh against the server in a server list in the 1.19 client

**ERROR**
[11:08:52] [Netty Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@49b325.[m
[11:08:52] [Netty Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@4955e3f6[
      memoryAddress=1391716249664
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6f638f8a
      chunk=Chunk(2f46c6df: 2%, 57344/4194304)
      handle=562980018192384
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8192
      length=9
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@d7fa593
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=9
      writerIndex=9
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@423a58e6[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5bd30e40
        packetListeners=[PacketAdapter[plugin=SpleefX, sending=ListeningWhitelist[priority=NORMAL, packets=[CAMERA[class=PacketPlayOutCamera, id=71]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2bf06b94
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@178685e0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@76b029e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4409bd3d
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@261155c
        reporter=com.comphenix.protocol.ProtocolLib$1@6c0dd2e3
        server=CraftServer{serverName=CraftBukkit,serverVersion=3499-Spigot-87c4d13-64c1527,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@10a7678b
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4009ed92
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2fafc41c
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@49b325[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@2e19e8f0
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@7fc7560b
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@32da024d
      originalChannel=[id: 0x42758a55, L:/127.0.0.1:25565 - R:/127.0.0.1:56179]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@32da024d, previous=[id: 0x42758a55, L:/127.0.0.1:25565 - R:/127.0.0.1:56179], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@73c8c52a, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@65aab354
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@50fedb5e
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@761b9363
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4009ed92
      processor=com.comphenix.protocol.injector.NetworkProcessor@2b6821fa
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@dea2be2
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    3499-Spigot-87c4d13-64c1527 (MC: 1.19)

**Version Info**
I am using the 4.8.0 version of ProtocolLib

**Additional context**
I have stripped any plugins that were erroring that haven't had updates yet and the problem persists.

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

**Comment by frontlinegeek** [comment]
Thanks!  Working better now.
