### ISSUE TITLE
[Bungee/Waterfall] 1.19 Minecraft SMP Server ERROR

### ISSUE THREAD

**Issue by Hax100** [dmulloy2/ProtocolLib#1619]
**Describe the bug**
A lot of errors 

**To Reproduce**
1. Go into a 1.19 Minecraft Server FTP
2. Install https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710 AND ProtocolLib
3. Restart the server
4. See errors in console

**Expected behavior**
to work without erroring

**Screenshots**
not applicable

**Version Info**
PasteBin Of Version info: https://pastebin.com/jyupRm93
PasteBin Password: NcMsdCv09k
PasteBin Details: Expires in 1 weeks ; unlisted

**Additional context**
PasteBin Of Error: https://pastebin.com/1c43LSmS
PasteBin Password: 7nYNZhTmKy
PasteBin Details: Expires in 1 weeks ; unlisted

**Comment by Hax100** [comment]
UPDATE/CORRECTION
i got something wrong up there, its not a "ProtocolLib + Orebfuscator" issue, its actually a ProtocolLib + Bungeeguard issue. sorry.

**To Reproduce [ CORRECTION ]**
Steps to reproduce the behavior:
1. Go into a 1.19 Minecraft Server FTP
2. Install https://www.spigotmc.org/resources/bungeeguard.79601 AND ProtocolLib
3. Restart the server
4. See errors in the console 

Other information above should be accurate I hope lol, if not I will post another comment.

**Comment by Hax100** [comment]
**UPDATE/CORRECTION AGAINNNNN**
I disabled both plugin... The error is still persisting.... 

**To Reproduce [ CORRECTION AGAIN ]**
Steps to reproduce the behavior:
1. Set up a 1.19 spigot server with no plugins
2. Configure it to work with a bungee server and install ProtocolLib
3. Restart the server
4. See errors in the console

**i am confused, scared, emotional, crying, flying, all at the same time, I don't understand this error/its-cause please send help lol**

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

**Comment by Hax100** [comment]
> lease use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

thx, I updated, BUT it's still not working fully, I am trying to connect from the lobby server to the 1.19 survival server and its not connecting. 

`[10.06 13:14:16] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)`

**Comment by derklaro** [comment]
That exception is not related to protocollib as no changes to the incoming byte data are made

**Comment by Hax100** [comment]
> That exception is not related to protocollib as no changes to the incoming byte data are made
```
[10.06 13:14:16] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)
[10.06 13:17:17] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)
[10.06 13:17:23] [Server] [Netty Epoll Server IO #1/WARN]: [BungeeGuard] Denying connection from xxx.xxx.xxx.108 - MTA0LjIyMy4zMC44NA== - reason: INVALID_HANDSHAKE
[10.06 13:17:23] [Server] 2022-06-10:17:23,628 Netty Epoll Server IO #1 ERROR Recursive call to appender File
[10.06 13:17:23] [Server] [Netty Epoll Server IO #1/WARN]: [ProtocolLib] Loaded class me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter from BungeeGuard v1.3-SNAPSHOT which is not a depend or softdepend of this plugin.
[10.06 13:17:23] [Server] [Netty Epoll Server IO #1/ERROR]: [BungeeGuard] Unhandled exception occurred in onPacketReceiving(PacketEvent) for BungeeGuard
[10.06 13:17:23] [Server] java.lang.NoClassDefFoundErrorcom/comphenix/protocol/injector/server/TemporaryPlayerFactory
[10.06 13:17:23] [Server] 	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.closeConnection(ProtocolHandshakeListener.java:130) ~[BungeeGuard.jar:?]
[10.06 13:17:23] [Server] 	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.access$300(ProtocolHandshakeListener.java:54) ~[BungeeGuard.jar:?]
[10.06 13:17:23] [Server] 	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter.onPacketReceiving(ProtocolHandshakeListener.java:103) ~[BungeeGuard.jar:?]
[10.06 13:17:23] [Server] 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:5.0.0-SNAPSHOT-b560]
[10.06 13:17:23] [Server] 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:5.0.0-SNAPSHOT-b560]
[10.06 13:17:23] [Server] 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:554) [ProtocolLib.jar:5.0.0-SNAPSHOT-b560]
[10.06 13:17:23] [Server] 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519) [ProtocolLib.jar:5.0.0-SNAPSHOT-b560]
[10.06 13:17:23] [Server] 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:113) [ProtocolLib.jar:5.0.0-SNAPSHOT-b560]
[10.06 13:17:23] [Server] 	at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:31) [ProtocolLib.jar:5.0.0-SNAPSHOT-b560]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90) [spigot-1.19-R0.1-SNAPSHOT.jar:3521-Spigot-1dffefb-cc7edd6]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
[10.06 13:17:23] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[10.06 13:17:23] [Server] Caused byjava.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayerFactory
[10.06 13:17:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
[10.06 13:17:23] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
[10.06 13:17:23] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[10.06 13:17:23] [Server] 	... more
[10.06 13:17:23] [Server] [Netty Epoll Server IO #1/ERROR]: Parameters: 
[10.06 13:17:23] [Server]   net.minecraft.network.protocol.handshake.PacketHandshakingInSetProtocol@2258f7d8[
[10.06 13:17:23] [Server]     b=758
[10.06 13:17:23] [Server]     c=xxx.xxx.xxx
[10.06 13:17:23] [Server]     d=25565
[10.06 13:17:23] [Server]     e=LOGIN
[10.06 13:17:23] [Server]   ]
[10.06 13:17:57] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)
```
Here are some more details: I did '/server [server-name]' from the lobby server, that's supposed to teleport me to the 1.19 server but it gives that short 'Internal Exception' error. I tried directly connecting to the server with its IP, but 'bungeeguard' plugin prevented me from joining {as it should}. i don't understand why its not letting me go from the lobby server to 1.19 survival with the command '/server [server-name]', do you have any solutions to my issue? or is the solution to wait for an official ProtocolLib 1.19 release?

**Comment by derklaro** [comment]
This seems to be an issue with BungeeGuard trying to access a class which no longer exists (`com.comphenix.protocol.injector.server.TemporaryPlayerFactory`). Please report it to them

**Comment by Hax100** [comment]
> This seems to be an issue with BungeeGuard trying to access a class which no longer exists (`com.comphenix.protocol.injector.server.TemporaryPlayerFactory`). Please report it to them

Ok I reported it, I also posted additional details there, you can take a look and see if you have solutions based on the additional details: https://github.com/lucko/BungeeGuard/issues/78

**Comment by Hax100** [comment]
> This seems to be an issue with BungeeGuard trying to access a class which no longer exists (`com.comphenix.protocol.injector.server.TemporaryPlayerFactory`). Please report it to them

Do you know how to solve this error? @derklaro 
`[12.06 11:03:12] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)`

**Comment by derklaro** [comment]
Semms like an packet decoding issue - something tries to read more bytes than the client actually sent in the message. Without further stack trace I cannot give you any advise here unfortunately.
