### ISSUE TITLE
getEntityFromId Citizens error

### ISSUE THREAD

**Issue by Jalau11** [dmulloy2/ProtocolLib#162]
After the normal getEntityFromId issues seem to be resolved, the next one is happening with citizens:
`[23:55:35] [Server thread/WARN]: FieldAccessException: Cannot find entity from ID 495.
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:254)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:982)
[23:55:35] [Server thread/WARN]: 	at me.jalau.utils.BasicUtils.getEntityFromID(BasicUtils.java:57)
[23:55:35] [Server thread/WARN]: 	at me.jalau.protocollib.MobPlayerFaker$1.onPacketSending(MobPlayerFaker.java:92)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1060)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:292)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:298)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.d(EntityTrackerEntry.java:265)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:220)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:809)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[23:55:35] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[23:55:35] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:55:35] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_9_R1.Entity field net.citizensnpcs.util.nms.PlayerlistTrackerEntry.tracker to net.minecraft.server.v1_9_R1.EntityTrackerEntry
[23:55:35] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[23:55:35] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[23:55:35] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
[23:55:35] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(Unknown Source)
[23:55:35] [Server thread/WARN]: 	at java.lang.reflect.Field.get(Unknown Source)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.FieldUtils.readField(FieldUtils.java:281)
[23:55:35] [Server thread/WARN]: 	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:244)
[23:55:35] [Server thread/WARN]: 	... 28 more`

**Comment by dmulloy2** [comment]
That's odd, does this only happen with citizens NPCS?

**Comment by Jalau11** [comment]
This error happens as soon as I try to get an entity from an id. Probably because it goes through all entities and that means also through the citizens ones?

**Comment by MyzelYam** [comment]
My customers have experienced the exact same issue, Citizens seems to mess around with their custom players' trackers.

**Comment by dmulloy2** [comment]
Is this still an issue in the latest build?

**Comment by dmulloy2** [comment]
Should be fixed in the latest builds of ProtocolLib and Citizens.
