### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet. - 1.19 on Bisect Hosting using Spigot 1.19 Java 17 jar

### ISSUE THREAD

**Issue by LordBezoar** [dmulloy2/ProtocolLib#1626]
[10.06 19:03:32] [Server] [Netty Epoll Server IO #3/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@276a165c.
[10.06 19:03:32] [Server] [Netty Epoll Server IO #3/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
[10.06 19:03:32] [Server]   If this problem hasn't already been reported, please open a ticket
[10.06 19:03:32] [Server]   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
[10.06 19:03:32] [Server]   Stack Trace:
[10.06 19:03:32] [Server]   java.lang.IllegalArgumentExceptionUnable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
[10.06 19:03:32] [Server]   	at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
[10.06 19:03:32] [Server]   	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
[10.06 19:03:32] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
[10.06 19:03:32] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10.06 19:03:32] [Server]   	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[10.06 19:03:32] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10.06 19:03:32] [Server]   	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10.06 19:03:32] [Server]   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[10.06 19:03:32] [Server]   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[10.06 19:03:32] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[10.06 19:03:32] [Server]   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[10.06 19:03:32] [Server]   	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[10.06 19:03:32] [Server]   	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[10.06 19:03:32] [Server]   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[10.06 19:03:32] [Server]   	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[10.06 19:03:32] [Server]   	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10.06 19:03:32] [Server]   	at java.base/java.lang.Thread.run(Thread.java:833)
[10.06 19:03:32] [Server]   Dump:
[10.06 19:03:32] [Server]   Parameters
[10.06 19:03:32] [Server]     io.netty.buffer.PooledUnsafeDirectByteBuf@3529ca9f[
[10.06 19:03:32] [Server]       memoryAddress=139786668994576
[10.06 19:03:32] [Server]       recyclerHandle=NOOP_HANDLE
[10.06 19:03:32] [Server]       chunk=Chunk(6ac3b1%, 32768/4194304)
[10.06 19:03:32] [Server]       handle=562980018192384
[10.06 19:03:32] [Server]       memory=java.nio.DirectByteBuffer[pos=lim=4194304 cap=4194304]
[10.06 19:03:32] [Server]       offset=8192
[10.06 19:03:32] [Server]       length=19
[10.06 19:03:32] [Server]       maxLength=32
[10.06 19:03:32] [Server]       cache=io.netty.buffer.PoolThreadCache@7216c353
[10.06 19:03:32] [Server]       tmpNioBuf=<null>
[10.06 19:03:32] [Server]       allocator=PooledByteBufAllocator(directByDefaulttrue)
[10.06 19:03:32] [Server]       refCnt=2
[10.06 19:03:32] [Server]       readerIndex=19
[10.06 19:03:32] [Server]       writerIndex=19
[10.06 19:03:32] [Server]       markedReaderIndex=0
[10.06 19:03:32] [Server]       markedWriterIndex=0
[10.06 19:03:32] [Server]       maxCapacity=2147483647
[10.06 19:03:32] [Server]     ]
[10.06 19:03:32] [Server]     manager:
[10.06 19:03:32] [Server]       com.comphenix.protocol.injector.PacketFilterManager@5ec89b5e[
[10.06 19:03:32] [Server]         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@14fbd8a8
[10.06 19:03:32] [Server]         packetListeners=[PacketAdapter[plugin=HiddenArmor, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=80]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HiddenArmor, sending=ListeningWhitelist[priority=HIGH, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
[10.06 19:03:32] [Server]         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1870b18
[10.06 19:03:32] [Server]         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@66661e44
[10.06 19:03:32] [Server]         inputBufferedPackets=[]
[10.06 19:03:32] [Server]         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7c6e6bbd
[10.06 19:03:32] [Server]         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@361ac200
[10.06 19:03:32] [Server]         hasClosed=false
[10.06 19:03:32] [Server]         classLoader=org.bukkit.plugin.java.PluginClassLoader@48bdc6a
[10.06 19:03:32] [Server]         reporter=com.comphenix.protocol.ProtocolLib$1@59be6b85
[10.06 19:03:32] [Server]         server=CraftServer{serverName=CraftBukkit,serverVersion=3521-Spigot-1dffefb-cc7edd6,minecraftVersion=1.19}
[10.06 19:03:32] [Server]         library=ProtocolLib v4.8.0
[10.06 19:03:32] [Server]         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3668129e
[10.06 19:03:32] [Server]         knowsServerPackets=true
[10.06 19:03:32] [Server]         knowsClientPackets=true
[10.06 19:03:32] [Server]         phaseLoginCount=0
[10.06 19:03:32] [Server]         phasePlayingCount=2
[10.06 19:03:32] [Server]         packetCreation=false
[10.06 19:03:32] [Server]         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@43f93272
[10.06 19:03:32] [Server]         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7176373e
[10.06 19:03:32] [Server]         hasRecycleDistance=true
[10.06 19:03:32] [Server]         minecraftVersion=(MC1.19.0)
[10.06 19:03:32] [Server]         debug=false
[10.06 19:03:32] [Server]       ]
[10.06 19:03:32] [Server]   Sender:
[10.06 19:03:32] [Server]     com.comphenix.protocol.injector.netty.ChannelInjector@276a165c[
[10.06 19:03:32] [Server]       decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
[10.06 19:03:32] [Server]       encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
[10.06 19:03:32] [Server]       factory=com.comphenix.protocol.injector.netty.InjectionFactory@4aea9706
[10.06 19:03:32] [Server]       player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@33da236a
[10.06 19:03:32] [Server]       updated=<null>
[10.06 19:03:32] [Server]       playerName=<null>

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support
