### ISSUE TITLE
Issue with KCauldron

### ISSUE THREAD

**Issue by Yann151924** [dmulloy2/ProtocolLib#163]
I use on my server VentureChat plugin and Protocollib and i have this error when i write something in chat, i find that is protocollib error :
http://pastebin.com/CLSbrH1u

KCauldron-1.7.10-1566
Protocollib : 3.6.5

**Comment by dmulloy2** [comment]
Looks to be an issue with VentureChat, although I vaguely remember this problem popping up a while ago.

**Comment by Yann151924** [comment]
I search on internet and i find no solution. Do you have one or a specific build ?

**Comment by games647** [comment]
Try to update it. I believe it's fixed

**Comment by Yann151924** [comment]
I update VentureChat and Protocollib is in last version and I have the same error.

**Comment by games647** [comment]
@Yann151924 Could you post the new error?

**Comment by Yann151924** [comment]
If you want but it's the same :
http://pastebin.com/r2xfkUdd

**Comment by games647** [comment]
You are using 2.8.2 right? Because there is no line 56 for me.

**Comment by Yann151924** [comment]
I don't use the latest version of venturechat on this version, but it's the same error. I found on internet that the two line is when protocollib has an error :
 at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[14:58:58] [Server thread/WARN]:    at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[14:58:58] [Server thread/WARN]:    at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637)
[14:58:58] [Server thread/WARN]:    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613)

For better information the server is in 1.7.10 and it's modded pack.

**Comment by dmulloy2** [comment]
This is an issue with VentureChat, those lines are just ProtocolLib passing it on to VentureChat.
