### ISSUE TITLE
i have big error run in my server

### ISSUE THREAD

**Issue by prabhu8680** [dmulloy2/ProtocolLib#1641]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:884)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@cf576ccb[
      memoryAddress=139739176924304
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@88d11f17
      chunk=Chunk(aac32ab1: 3%, 90112/4194304)
      handle=562980018192384
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8192
      length=20
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@d90dfe16
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=20
      writerIndex=20
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@50481743[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5f598c61
        packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LoginSecurity, sending=ListeningWhitelist[priority=LOW, packets=[WINDOW_DATA[class=PacketPlayOutWindowData, id=21], SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@897db134
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@88d551cc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@846143aa
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@b1495425
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@54becc2e
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1657,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@c0b3ecea
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@372b4f4d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@52265f7e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@84922404[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@f7730b3c
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@7971e62
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@4bd12b2a
      originalChannel=[id: 0x12965e15, L:/172.18.0.27:25595 - R:/103.25.44.74:51219]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@4bd12b2a, previous=[id: 0x12965e15, L:/172.18.0.27:25595 - R:/103.25.44.74:51219], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@177c1f1f, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@3fb698cc
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@bda56b19
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@24c5cadc
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@372b4f4d
      processor=com.comphenix.protocol.injector.NetworkProcessor@1e7fc34a
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 20)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@5f9e098a
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Purpur-1657 (MC: 1.19)

**Comment by derklaro** [comment]
Please use the latest development build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

**Comment by prabhu8680** [comment]
Thank you so much, let me update the same.
