### ISSUE TITLE
INTERNAL ERROR: Cannot enable ProtocolLib.

### ISSUE THREAD

**Issue by Cristiandgamer** [dmulloy2/ProtocolLib#1648]
Error Cannot enable ProtocolLib. (java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/compiler/StructureCompiler) occured in ProtocolLib v4.5.1

**To Reproduce**
1.download magma 1.12.2-c24c6905
2. download protocolLib
3. start server
[23:42:31] [Server thread/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/compiler/StructureCompiler
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler.initializeCompiler(BackgroundCompiler.java:131)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler.<init>(BackgroundCompiler.java:109)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:159)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:410)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:349)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:353)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: Failed to remap class com.comphenix.protocol.reflect.compiler.StructureCompiler
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:216)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 12 more
  Caused by: java.lang.NoClassDefFoundError: org/magmafoundation/magma/remapper/proxy/ProxyClassWriter
        at org.magmafoundation.magma.remapper.remappers.ReflectionMethodRemapper.redirectVirtual(ReflectionMethodRemapper.java:150)
        at org.magmafoundation.magma.remapper.remappers.ReflectionMethodRemapper.visitMethodInsn(ReflectionMethodRemapper.java:114)
        at org.objectweb.asm.tree.MethodInsnNode.accept(Unknown Source)
        at org.objectweb.asm.tree.InsnList.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
        at org.magmafoundation.magma.remapper.utils.RemappingUtils.remapFindClass(RemappingUtils.java:113)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:202)
        ... 16 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@71340dc7[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7b511a6f
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@19aeef31
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@672609c3
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@36ad6ad5
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@455c9c0d
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2be534f0
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1ee2fca6
        reporter=com.comphenix.protocol.ProtocolLib$1@7cda585e
        server=CraftServer{serverName=Magma,serverVersion=1.12.2-c24c6905,minecraftVersion=1.12.2}
        library=ProtocolLib v4.5.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@613214
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@67a7fb1d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6ba85091
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@7c0f698e
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@64397c90[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7b511a6f
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6e68964a
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@364ff789
      commandProtocol=com.comphenix.protocol.CommandProtocol@1fca0509
      commandPacket=com.comphenix.protocol.CommandPacket@180e4c67
      commandFilter=com.comphenix.protocol.CommandFilter@32fe53ea
      packetLogging=com.comphenix.protocol.PacketLogging@7b441983
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@3469b9af
      server=CraftServer{serverName=Magma,serverVersion=1.12.2-c24c6905,minecraftVersion=1.12.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5e6eb631
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1ee2fca6
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@451c454e
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    1.8.0_312
  Server:
    1.12.2-c24c6905 (MC: 1.12.2)

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

  -ProtocolLib v4.5.1

**Additional context**

-The problem is that when I start the server I get this error, I already tried with the latest version it solves it for me but when I enter the server I get another error

**Comment by Targex25** [comment]
same
