### ISSUE TITLE
Error Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by User4716** [dmulloy2/ProtocolLib#1651]
A message keeps randomly popping up on my chat: 
Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector"1e0313
And i don't know what it means.
I am using Aternos host.
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-17 (MC: 1.19)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
*I use SuperVanish 6.2.7 (1.18) So it can be the reason why i get the error. And also there is an error in the logs that
SuperVanish does not work propely. I think it might be that. The problem might be solved jus't by waiting for SuperVanish 1.19 and replacing 1.18 version with that.*
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
This message is popping up in to console:
[18:26:06 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@21173faf[
      memoryAddress=140586157962000
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1b33bbb
      chunk=Chunk(7a62f564: 19%, 770048/4194304)
      handle=562980018192385
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8224
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@73cad641
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@13698f08[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1965e693
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54], ABILITIES[class=PacketPlayOutAbilities, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@318ea94f
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@17c8a913
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4886652d
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7ee153d0
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@68b3efec
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-17,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@676cfea5
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@99bf49e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@56852a20
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@6bb875d0[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@114be49b
      player=CraftPlayer{name=PROMCMASTER4716}
      updated=<null>
      playerName=PROMCMASTER4716
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@73cee5ff
      originalChannel=[id: 0x4f98e080, L:/172.20.0.31:41415 - R:/88.114.60.134:60629]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@73cee5ff, previous=[id: 0x4f98e080, L:/172.20.0.31:41415 - R:/88.114.60.134:60629], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@3b375265, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1309a626
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@176c48a5
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@5ef64620
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@99bf49e
      processor=com.comphenix.protocol.injector.NetworkProcessor@1b536bb
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@96335c2
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-17 (MC: 1.19)

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

ProtocolLib Dump
Timestamp: 06/15/22 18:31:48

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19-R0.1-SNAPSHOT
Server Version: git-Paper-17 (MC: 1.19)
Java Version: 17.0.2

ProtocolLib: com.comphenix.protocol.ProtocolLib@710491f[
  statistics=com.comphenix.protocol.metrics.Statistics@4ba51241
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@2e46690
  packetTask=3
  tickCounter=25429
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1965e693
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@4f51a6aa
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@4a0c56ee
  commandProtocol=com.comphenix.protocol.CommandProtocol@29d862f4
  commandPacket=com.comphenix.protocol.CommandPacket@82951b9
  commandFilter=com.comphenix.protocol.CommandFilter@4a0fc2e0
  packetLogging=com.comphenix.protocol.PacketLogging@621c5669
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@839471c
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-17,minecraftVersion=1.19}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@4adf7b3b
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@7e5c16eb
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@13698f08[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1965e693
  packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54], ABILITIES[class=PacketPlayOutAbilities, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@318ea94f
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@17c8a913
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4886652d
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7ee153d0
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@68b3efec
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-17,minecraftVersion=1.19}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@676cfea5
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=1
  phasePlayingCount=4
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@99bf49e
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@56852a20
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.0)
  debug=false
]

Listeners:
de.myzelyam.supervanish.features.VanishIndication$1@74a3bc52[
  plugin=SuperVanish v6.2.7
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]]
]
de.myzelyam.supervanish.visibility.hiders.modules.PlayerInfoModule@4c1acee8[
  hider=de.myzelyam.supervanish.visibility.hiders.PreventionHider@312db758
  plugin=SuperVanish v6.2.7
  errorLogged=true
  plugin=SuperVanish v6.2.7
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]]
]
de.myzelyam.supervanish.features.SilentOpenChestPacketAdapter@30c0c977[
  silentOpenChest=de.myzelyam.supervanish.features.SilentOpenChest@6de573d8
  suppressErrors=true
  plugin=SuperVanish v6.2.7
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54], ABILITIES[class=PacketPlayOutAbilities, id=50]], gamephase=PLAYING, options=[]]
]
de.myzelyam.supervanish.visibility.ServerListPacketListener@7d358d3a[
  plugin=SuperVanish v6.2.7
  plugin=SuperVanish v6.2.7
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
SuperVanish by [MyzelYam]
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Plz help. Or at least tell how to fix this.
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

**Comment by derklaro** [comment]
This is fixed in the latest dev builds, download them from here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by User4716** [comment]
Unfortunately i cant download that file to my aternos server, because all plugins needs to be downloaded directly from Spigot. So i'll just wait for new Supervanish version or new ProtocolLib version.
