### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet on player login

### ISSUE THREAD

**Issue by sovtec** [dmulloy2/ProtocolLib#1656]
[21:53:53 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@37dc8201[
      memoryAddress=139821588353696
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(6df13cda: 1%, 32768/4194304)
      handle=562980018192385
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8224
      length=27
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@4876b42f
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=27
      writerIndex=27
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5b25b64c[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3f56461e
        packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=MyCommand, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6945152f
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2fa618ca
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@59475ca4
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@54ac8724
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@15011cf3
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-18,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@69bfe946
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@29316a30
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@261384b2
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@4f058718[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@60712d01
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@196a10c4
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@4a754562
      originalChannel=[id: 0x65004746, L:/172.18.0.7:25646 - R:/51.174.246.43:55612]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@4a754562, previous=[id: 0x65004746, L:/172.18.0.7:25646 - R:/51.174.246.43:55612], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@54012b6b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1d24ed1f
      vanillaDecoder=net.minecraft.network.PacketDecoder@7d9ae58c
      vanillaEncoder=net.minecraft.network.PacketEncoder@3036b4df
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@29316a30
      processor=com.comphenix.protocol.injector.NetworkProcessor@57c7df7d
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 27, widx: 27, cap: 27)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@738b66c6
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-18 (MC: 1.19)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)

**Comment by sovtec** [comment]
> This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)

Sorry for the epic long error code and badly presented error. 

But thanks 😀
