### ISSUE TITLE
Setting data in a WrappedDataWatcher causes an error

### ISSUE THREAD

**Issue by andrewchi12345** [dmulloy2/ProtocolLib#166]
`Caused by: java.lang.IllegalArgumentException: handle cannot be NULL.
        at com.comphenix.protocol.wrappers.AbstractWrapper.setHandle(AbstractWrapper.java:29) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Serializer.<init>(WrappedDataWatcher.java:560) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject.getSerializer(WrappedDataWatcher.java:534) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:331) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:299) ~[?:?]
        at city.smash.legendsofmc.commands.Commands.onCommand(Commands.java:65) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b39373b-249c5f0]`

**Comment by andrewchi12345** [comment]
`			PacketContainer packet = new PacketContainer(PacketType.Play.Server.ENTITY_METADATA);
			packet.getIntegers().write(0, player.getEntityId());

			WrappedDataWatcher watcher = new WrappedDataWatcher();
			watcher.setObject(0, Entity_Glowing);
			packet.getDataWatcherModifier().write(0, watcher);
			
			try {
				ProtocolLibrary.getProtocolManager().sendServerPacket(player, packet);
			} catch (InvocationTargetException e) {
				e.printStackTrace();
			}`

**Comment by Paulomart** [comment]
Same as #166

**Comment by dmulloy2** [comment]
Resolved in 160.

**Comment by Scrayos** [comment]
Still unresolved as you can see from my comments in your commit: https://github.com/dmulloy2/ProtocolLib/commit/5115bcaf98ca0a53497096bcf1e924f39dd62ca6

Of course I tested it before.
