### ISSUE TITLE
Missing net.minecraft.network.protocol.game.PacketPlayOutChat 

### ISSUE THREAD

**Issue by Artzert2215** [dmulloy2/ProtocolLib#1662]
**Describe the bug**
The plugin MessageHider (1.8.3) uses the class `net.minecraft.network.protocol.game.PacketPlayOutChat`.
Was this class removed in 5.0.0?

**To Reproduce**
1. Download MessageHider 
2. Download the latest dev build
3. Run server

**Expected behavior**
The class should exist?

**Log**
```
[16:10:55] [Netty Epoll Server IO #0/WARN]: java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutChat
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at MessageHider_1.8.3.jar//de.rapha149.messagehider.util.ReflectionUtil.getClass(ReflectionUtil.java:60)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at MessageHider_1.8.3.jar//de.rapha149.messagehider.Events$1.write(Events.java:66)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib_DEV-BUILD.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib_DEV-BUILD.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:10:55] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Version Info**
Latest dev build (june 14th) running purpurMC 1.19 build 1666

**Comment by derklaro** [comment]
This seems to be an issue with message hider and is not related to ProtocolLib

**Comment by derklaro** [comment]
Yea, because it's 1.18, not because it's 4.8 ;)

**Comment by Artzert2215** [comment]
I guess I'll be on the lookout for a similar plugin
