### ISSUE TITLE
 [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by EverydayHero2022** [dmulloy2/ProtocolLib#1663]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@764c75ee[
      memoryAddress=140653685848672
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6265747e
      chunk=Chunk(75e8ffe5: 22%, 917504/4194304)
      handle=37154795710054401
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=540832
      length=137
      maxLength=160
      cache=io.netty.buffer.PoolThreadCache@4dbc7fc9
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=137
      writerIndex=137
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5caa58aa[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@17056a09
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@598ddae2
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@c0ad9a5
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2ebbf86
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3e02d8f0
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@96f4f18
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-20,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@c3aea16
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4c738377
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@538ac26e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@38389d5d[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@4956d68e
      player=CraftPlayer{name=PrinceTom}
      updated=<null>
      playerName=PrinceTom
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@15d5252b
      originalChannel=[id: 0xabed2860, L:/185.7.32.16:25965 - R:/185.7.32.16:34183]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@15d5252b, previous=[id: 0xabed2860, L:/185.7.32.16:25965 - R:/185.7.32.16:34183], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@44fbbd4e, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@7f08124f
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@43c88cf8
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@53e65790
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4c738377
      processor=com.comphenix.protocol.injector.NetworkProcessor@754b6807
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 137, widx: 137, cap: 137)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@597f7842
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    18.0.1.1
  Server:
    git-Paper-20 (MC: 1.19)

**Comment by St3llarYT** [comment]
is this on 1.19, because i have the same error

**Comment by EverydayHero2022** [comment]
Yes, om 1.19 error is seen

**Comment by SpLayzDK** [comment]
Wild guess, but this might be because ProtocolLib isn't supported on 1.19? The latest release' support goes up to 1.18.2.

**Comment by Cube-Box-391** [comment]
i have exact same problem

**Comment by t-a-g-o** [comment]
i got the same issue

**Comment by srnyx** [comment]
Guys, don't just keep commenting you have the same thing.
Either just react to the initial comment with 👍, or don't say anything and just Subscribe to the issue.

**Comment by derklaro** [comment]
This is fixed in the latest dev builds. Please search through the open and closed issue before filing a new one the next time you think you found an issue. There are like 20 Issues with the same error already! Find the dev build here: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by EverydayHero2022** [comment]
Thanks derklaro for sharing the solution: https://ci.dmulloy2.net/job/ProtocolLib/
Much appreciated!
