### ISSUE TITLE
Errors that only administrators can see

### ISSUE THREAD

**Issue by HoronLee** [dmulloy2/ProtocolLib#1675]
**Describe the bug**
Only administrators will see this error continuously on the server

**To Reproduce**
I didn't do anything
**Expected behavior**

**Screenshots**
[00:33:18 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@473aa19b[
      memoryAddress=1127525744736
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@cb8da22
      chunk=Chunk(12fdbeba: 26%, 1081344/4194304)
      handle=23080978155044865
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=335904
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@5591bdf2
      tmpNioBuf=java.nio.DirectByteBuffer[pos=335922 lim=335922 cap=4194304]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7fc0652[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2dec7953
        packetListeners=[PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3ef891d0
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@28493626
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4fe07beb
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@108a5a5
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@7b84c245
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-3,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@566e3c8e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1b1f36b7
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@758d9f69
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@7ff414d1[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@4d24f163
      player=CraftPlayer{name=Horon_Lee}
      updated=<null>
      playerName=Horon_Lee
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@9f95622
      originalChannel=[id: 0x471d385c, L:/127.0.0.1:25565 - R:/127.0.0.1:50976]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@9f95622, previous=[id: 0x471d385c, L:/127.0.0.1:25565 - R:/127.0.0.1:50976], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@e52c0b4, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@9aa38df
      vanillaDecoder=net.minecraft.network.PacketDecoder@4a21378e
      vanillaEncoder=net.minecraft.network.PacketEncoder@6371c31c
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1b1f36b7
      processor=com.comphenix.protocol.injector.NetworkProcessor@230a5bde
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@5fb1330a
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.3.1
  Server:
    git-Paper-3 (MC: 1.19)

**Comment by HoronLee** [comment]
> 这在最新的开发版本中已修复。请先搜索未解决和已解决的问题，然后再提交新问题，下次您认为自己发现了问题。已经有20个问题具有相同的错误！在此处查找开发版本：https://ci.dmulloy2.net/job/ProtocolLib/

Thanks!
