### ISSUE TITLE
ProtocolLib 4.80 Error Magma 1.12.2

### ISSUE THREAD

**Issue by Cheminsky953** [dmulloy2/ProtocolLib#1679]
How I can fix this? I'm using Magma 1.12.2 and ProtocolLib 4.80
![imagen_2022-06-22_093543597](https://user-images.githubusercontent.com/74625219/174971203-b92ecd10-4edb-4421-8eea-7b291c3be4c7.png)

 If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 37 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketHandshakingInSetProtocol
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_C00Handshake$java_lang_Object.<init>(Unknown Source)
        ... 42 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@42e6d221[
      memoryAddress=140566777819152
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@60b0c1fc
      chunk=Chunk(11ac83bb: 1%, 106496/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=19
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@5e7c0b2f
      tmpNioBuf=java.nio.DirectByteBuffer[pos=8208 lim=8208 cap=16777216]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=19
      writerIndex=19
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@117eb66d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@740a918c
        packetListeners=[PacketAdapter[plugin=LoginSecurity, sending=ListeningWhitelist[priority=LOW, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_DATA[class=PacketPlayOutWindowData, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@6eb74447
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@119a91dc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7533905c
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5515f987
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1ab2ff1d
        reporter=com.comphenix.protocol.ProtocolLib$1@1d41a1e
        server=CraftServer{serverName=Magma,serverVersion=1.12.2-866f4a2c,minecraftVersion=1.12.2}
        library=ProtocolLib v4.8.0-b547
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2d5db635
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@59e1eeb4
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7be3be3b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@205a340d[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@262bd6a7
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@220ebfa0
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@1dd0e0f9
      originalChannel=[id: 0xfff094e5, L:/172.18.0.10:25573 - R:/104.243.38.184:34936]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@1dd0e0f9, previous=[id: 0xfff094e5, L:/172.18.0.10:25573 - R:/104.243.38.184:34936], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@32f36795, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@65d72dd4
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@7f9acebf
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@7a2a6576
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@59e1eeb4
      processor=com.comphenix.protocol.injector.NetworkProcessor@fa94459
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 19, widx: 19, cap: 19)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4876a78d
      singleDecode=false
      decodeWasNull=false
      first=true
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0-b547
  Java Version:
    1.8.0_312
  Server:
    1.12.2-866f4a2c (MC: 1.12.2)

**Comment by derklaro** [comment]
We are currently not supporting magma, and there are no plans to support magma in the near future. Please use a fork of craftbukkit (like spigot or paper) to get support.
