### ISSUE TITLE
Field index out of bounds

### ISSUE THREAD

**Issue by RoboMWM** [dmulloy2/ProtocolLib#168]
My guess is this is a ProtocolLib issue.

Plugin for reference: https://github.com/RoboMWM/AntiAura (I've updated the packetWrapper to see if that might help anything, unfortunately no dice.)

```log
>auracheck robo                                                                                                                         
[03:08:36 WARN]: Unexpected exception while parsing console command "auracheck robo"                                                    
org.bukkit.command.CommandException: Unhandled exception executing command 'auracheck' in plugin AntiAura v0.4-SNAPSHOT                 
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.jar:git-Paper-465]                             
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.jar:git-Paper-465]                     
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:662) ~[patched_1.9.jar:git-Paper-465]            
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:625) [patched_1.9.jar:git-Paper-465]       
        at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:442) [patched_1.9.jar:git-Paper-465]                    
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:405) [patched_1.9.jar:git-Paper-465]                     
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-465]                     
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-465]                   
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]                                                                           
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)                          
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:351) ~[?:?]                            
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:327) ~[?:?]                                    
        at com.comphenix.packetwrapper.WrapperPlayServerNamedEntitySpawn.setX(WrapperPlayServerNamedEntitySpawn.java:131) ~[?:?]        
        at com.comphenix.packetwrapper.WrapperPlayServerNamedEntitySpawn.setPosition(WrapperPlayServerNamedEntitySpawn.java:111) ~[?:?] 
        at tk.maciekmm.antiaura.AuraCheck.getSpawnWrapper(AuraCheck.java:120) ~[?:?]                                                    
        at tk.maciekmm.antiaura.AuraCheck.invoke(AuraCheck.java:67) ~[?:?]                                                              
        at tk.maciekmm.antiaura.AntiAura.onCommand(AntiAura.java:154) ~[?:?]                                                            
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.jar:git-Paper-465]                             
        ... 8 more
```

**Comment by games647** [comment]
PacketWrapper isn't updated yet. Location positions are now doubles instead of integers.

**Comment by dmulloy2** [comment]
Your best bet is just to use ProtocolLib directly until PacketWrapper is updated.

**Comment by dmulloy2** [comment]
Should be fixed in https://github.com/dmulloy2/PacketWrapper/commit/22b866872c91cb5c40d758c870a05a3f2b6c6879
