### ISSUE TITLE
Massive Error Dump in Console

### ISSUE THREAD

**Issue by NIGHTMVRE** [dmulloy2/ProtocolLib#1685]
**Describe the bug**
Massive error spam in console. Plugin says its working but plugins that depend on it down work.

**To Reproduce**
1. Update from 1.18.2 to 1.19
2. Install latest protocol lib
3. Update other plugins
4. Start server

**Expected behavior**
Server starts normally, massive dumps to consol

**Screenshots**
[18:48:37 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 32!
[18:48:37 INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@5a591dc5.
[18:48:37 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@5190851b[
      memoryAddress=140659440861248
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@5c075a55
      chunk=Chunk(16b18159: 1%, 32768/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=1
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@1428903b
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5421827f[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4a7c6471
        packetListeners=[PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@45252999
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3277744a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6a1d2a01
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@43eb84df
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@2f6e04da
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-36,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@25fc9bac
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1558f1ed
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1ea5a1ef
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@5a591dc5[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@31575223
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@43c1c1c8
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@16ac2cf6
      originalChannel=[id: 0x2116a013, L:/172.18.0.3:25566 - R:/172.18.0.1:37332]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@16ac2cf6, previous=[id: 0x2116a013, L:/172.18.0.3:25566 - R:/172.18.0.1:37332], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@623a8577, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@2fb8c779
      vanillaDecoder=net.minecraft.network.PacketDecoder@588495e4
      vanillaEncoder=net.minecraft.network.PacketEncoder@505f6449
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1558f1ed
      processor=com.comphenix.protocol.injector.NetworkProcessor@f92d2a1
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@40e4624e
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-36 (MC: 1.19)

**Version Info**
ProtocolLib Dump
Timestamp: 06/24/22 18:53:54

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19-R0.1-SNAPSHOT
Server Version: git-Paper-36 (MC: 1.19)
Java Version: 17.0.2

ProtocolLib: com.comphenix.protocol.ProtocolLib@1fc5976c[
  statistics=com.comphenix.protocol.metrics.Statistics@1a493cb2
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6e90f6e9
  packetTask=8
  tickCounter=6762
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4a7c6471
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@777209ae
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@443f8edb
  commandProtocol=com.comphenix.protocol.CommandProtocol@17c08642
  commandPacket=com.comphenix.protocol.CommandPacket@7e8e1ded
  commandFilter=com.comphenix.protocol.CommandFilter@195654eb
  packetLogging=com.comphenix.protocol.PacketLogging@21a7584c
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@324638ac
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-36,minecraftVersion=1.19}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@3c292a7c
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@c8d8f94
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@5421827f[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4a7c6471
  packetListeners=[PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@45252999
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3277744a
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6a1d2a01
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@43eb84df
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@2f6e04da
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-36,minecraftVersion=1.19}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@25fc9bac
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=1
  phasePlayingCount=3
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1558f1ed
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1ea5a1ef
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.0)
  debug=false
]

Listeners:
com.bencodez.votingplugin.advancedcore.api.valuerequest.sign.SignMenu$1@7ae1ddc0[
  plugin=VotingPlugin v6.9
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
litebans.bN@125602a1[
  a=LiteBans v2.8.13
  b=litebans.cf@76ae155d
  plugin=LiteBans v2.8.13
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
litebans.je@5838dc41[
  c=LiteBans v2.8.13
  h=litebans.cr@2decad26
  a=litebans.ch@759d891f
  b=litebans.cf@76ae155d
  f=litebans.cU@731f7e0c
  plugin=LiteBans v2.8.13
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
VotingPlugin by [BenCodez]
LiteBans by [Ruan]

**Comment by derklaro** [comment]
This is fixed in the latest dev builds. Please search through the open and closed issue before filing a new one the next time you think you found an issue. There are like 20 Issues with the same error already! Find the dev build here: https://ci.dmulloy2.net/job/ProtocolLib/
