### ISSUE TITLE
Error when combined with Supervanish v 6.2.7

### ISSUE THREAD

**Issue by Darxit** [dmulloy2/ProtocolLib#1703]
I have been getting this error when running the /vanish command in a 1.19 purpur server, any idea on how to fix this? 

Version: Protocol Lib Dev Build version 570

[22:52:58 ERROR]: Could not pass event PlayerJoinEvent to SuperVanish v6.2.7
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 2, Size: 2)
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:371) ~[ProtocolLib (2).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:347) ~[ProtocolLib (2).jar:?]
        at de.myzelyam.supervanish.features.NightVision.sendAddPotionEffect(NightVision.java:115) ~[SuperVanish-6.2.7.jar:?]
        at de.myzelyam.supervanish.features.NightVision.onJoin(NightVision.java:69) ~[SuperVanish-6.2.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:git-Purpur-1685]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:365) ~[purpur-1.19.jar:git-Purpur-1685]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307) ~[purpur-1.19.jar:git-Purpur-1685]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:341) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:577) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[purpur-1.19.jar:git-Purpur-1685]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1685]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1685]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1685]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1685]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by derklaro** [comment]
Looks like SuperVanish has not yet updated to 1.19 correctly, please report that issue to them.
