### ISSUE TITLE
Sending entity MedataData packet is broken

### ISSUE THREAD

**Issue by andrewchi12345** [dmulloy2/ProtocolLib#171]
http://pastebin.com/CsBbDLT6

_No other information provided_

**Comment by dmulloy2** [comment]
Can you provide the code you're using?

**Comment by andrewchi12345** [comment]
'			PacketContainer packet = new PacketContainer(PacketType.Play.Server.ENTITY_METADATA);
			packet.getIntegers().write(0, player.getEntityId());

			WrappedDataWatcher watcher = new WrappedDataWatcher(player);
			Serializer serializer = WrappedDataWatcher.Registry.get(Byte.class);
			WrappedDataWatcherObject thing = new WrappedDataWatcherObject(0, serializer);
			byte value = (byte) ((((byte) watcher.getObject(thing)) & (Entity_Glowing)) | (Entity_Glowing));
			
			watcher.setObject(thing, value);
			packet.getDataWatcherModifier().write(0, watcher);
			
			try {
				ProtocolLibrary.getProtocolManager().sendServerPacket(player, packet);
			} catch (InvocationTargetException e) {
				e.printStackTrace();
			}'

**Comment by dmulloy2** [comment]
There wouldn't be an object at index 0 in a newly created data watcher. If you want to modify the player's data watcher, you should use WrappedDataWatcher#getEntityWatcher(Entity)

**Comment by andrewchi12345** [comment]
[21:51:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ex' in plugin LegendsOfMC v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1314) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1149) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-8e91ba2-dd745e8]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_9_R1.DataWatcher exists in class PacketPlayOutEntityMetadata.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:347) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:327) ~[?:?]
        at city.smash.legendsofmc.commands.Commands.onCommand(Commands.java:71) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-8e91ba2-dd745e8]
        ... 15 more

**Comment by andrewchi12345** [comment]
PacketContainer packet = new PacketContainer(PacketType.Play.Server.ENTITY_METADATA);
			packet.getIntegers().write(0, player.getEntityId());

			WrappedDataWatcher watcher = WrappedDataWatcher.getEntityWatcher(player);
			Serializer serializer = WrappedDataWatcher.Registry.get(Byte.class);
			WrappedDataWatcherObject thing = new WrappedDataWatcherObject(0, serializer);
			byte value = (byte) ((((byte) watcher.getObject(thing)) & (Entity_Glowing)) | (Entity_Glowing));
			
			watcher.setObject(thing, value);
			packet.getDataWatcherModifier().write(0, watcher);
			
			try {
				ProtocolLibrary.getProtocolManager().sendServerPacket(player, packet);
			} catch (InvocationTargetException e) {
				e.printStackTrace();
			}

**Comment by dmulloy2** [comment]
There's no data watcher in the entity metadata packet. Rather, it's a list of data watcher items.

**Comment by andrewchi12345** [comment]
So how would I set that?

**Comment by dmulloy2** [comment]
````java
packet.getWatchableCollectionModifier().write(0, watcher.getWatchableObjects());
````
Alternatively you could skip the watcher entirely and just do
````java
WrappedWatchableObject item = new WrappedWatchableObject(thing, value);
packet.getWatchableCollectionModifier().write(0, Lists.newArrayList(item));
````

**Comment by andrewchi12345** [comment]
Ah. I see. Thanks so much!
