### ISSUE TITLE
error protocollib how can i solve this error

### ISSUE THREAD

**Issue by iTzSebas195** [dmulloy2/ProtocolLib#1716]
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:243)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:132)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:214)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:316)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at net.minecraft.network.LegacyPingHandler.channelRead(SourceFile:94)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor137.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:227)
        ... 35 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketHandshakingInSetProtocol
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_handshake_client_C00Handshake$java_lang_Object.<init>(Unknown Source)
        ... 39 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2f842b2c[
      memoryAddress=140197008203792
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1c4ea844
      chunk=Chunk(7953fa9c: 1%, 57344/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=20
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@6523230a
      tmpNioBuf=java.nio.DirectByteBuffer[pos=8209 lim=8209 cap=16777216]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=20
      writerIndex=20
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@53d51bff[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@65f73620
        packetListeners=[PacketAdapter[plugin=LoginSecurity, sending=ListeningWhitelist[priority=LOW, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_DATA[class=PacketPlayOutWindowData, id=21]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3d7be521
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2819dc1a
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@53e82005
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@f725a6e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6d42f44c
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@250f08c8
        reporter=com.comphenix.protocol.ProtocolLib$1@bdd1cf2
        server=CraftServer{serverName=Magma,serverVersion=1.12.2-efb9116e,minecraftVersion=1.12.2}
        library=ProtocolLib v4.3.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@49b75e4
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@645e5b24
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@12242269
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@4a64088c
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@20b2be00[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@4ebd19dc
      player=com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$714f05d6@70e8ee3e
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@7ebb6644
      originalChannel=[id: 0xd22c9e8b, L:/172.18.0.11:25566 - R:/104.243.38.184:33786]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@7ebb6644, previous=[id: 0xd22c9e8b, L:/172.18.0.11:25566 - R:/104.243.38.184:33786], current=com.comphenix.protocol.injector.netty.ChannelInjector$5@2229131a, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@1507807f
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@302b4ddd
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@507ffa92
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@645e5b24
      processor=com.comphenix.protocol.injector.NetworkProcessor@1309e907
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 20)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@331db96f
      singleDecode=false
      decodeWasNull=false
      first=true
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.3.0
  Java Version:
    1.8.0_312
  Server:
    1.12.2-efb9116e (MC: 1.12.2)

**Comment by derklaro** [comment]
We're not supporting (and are not planning) to support Magma in the near Future. Please use Spigot (or a fork like Paper) to get support.
