### ISSUE TITLE
Issue on server startup caused by ProtocolLib

### ISSUE THREAD

**Issue by PanetiX** [dmulloy2/ProtocolLib#1718]
- [X] This issue is not solved in a development build

**Describe the bug**
Error on Startup on 2 plugins caused by ProtocolLib

CloudNetNPCs:
`[11:26:52] [Server thread/ERROR]: Error occurred while enabling CloudNet-NPCs v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null
	at com.github.juliarn.npc.NPCPool.addInteractListener(NPCPool.java:148) ~[cloudnet-npcs.jar:?]
	at com.github.juliarn.npc.NPCPool.<init>(NPCPool.java:113) ~[cloudnet-npcs.jar:?]
	at com.github.juliarn.npc.NPCPool$Builder.build(NPCPool.java:450) ~[cloudnet-npcs.jar:?]
	at eu.cloudnetservice.cloudnet.ext.npcs.bukkit.BukkitNPCManagement.<init>(BukkitNPCManagement.java:84) ~[cloudnet-npcs.jar:?]
	at eu.cloudnetservice.cloudnet.ext.npcs.bukkit.BukkitCloudNetNPCPlugin.onEnable(BukkitCloudNetNPCPlugin.java:36) ~[cloudnet-npcs.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:26:52] [Server thread/INFO]: [CloudNet-NPCs] Disabling CloudNet-NPCs v1.0`

LiteBans:
`[11:26:53] [Server thread/INFO]: [LiteBans] Enabling LiteBans v2.9.5
[11:26:53] [Server thread/WARN]: [LiteBans] Failed to add ProtocolLib packet listener.
[11:26:53] [Server thread/WARN]: [LiteBans] java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.bY.b(bY.java:27)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.gF.a(gF.java:986)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.gz.a(gz.java:388)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.eQ.c(eQ.java:70)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.eQ.d(eQ.java:61)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.BukkitPlugin.r(BukkitPlugin.java:155)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at LiteBans.jar//litebans.BukkitPlugin.onEnable(BukkitPlugin.java:195)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[11:26:53] [Server thread/WARN]: [LiteBans] 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:26:53] [Server thread/INFO]: [LiteBans] Loading SQL driver: mysql 8.0.18 (com.mysql.cj.jdbc.Driver)
[11:26:53] [Server thread/INFO]: [LiteBans] Connecting to database...
[11:26:53] [Server thread/INFO]: [LiteBans] litebans-pool - Starting...
[11:26:53] [Server thread/INFO]: [LiteBans] litebans-pool - Start completed.
[11:26:53] [Server thread/INFO]: [LiteBans] Connected to MySQL database successfully (78.3 ms).
[11:26:53] [Server thread/INFO]: [LiteBans] [Sync] Server name: Lobby
[11:26:53] [Server thread/INFO]: [LiteBans] [Sync] Server UUID: 45d3a1589f344a01a1e34a497f7bdc0f <8>
[11:26:53] [Server thread/INFO]: [LiteBans] Database connection fully initialized (91.4 ms).
[11:26:53] [Server thread/INFO]: [LiteBans] v2.9.5 enabled. Startup took 188 ms.`

**Version Info**
https://pastebin.com/P7eLwzNk

**Additional context**
All Plugins are up-to-date i tried with latest stable version from ProtocolLib (spigot download) and the latest dev version.

**Comment by derklaro** [comment]
Seems like some plugin is shading ProtocolLib into the jar, please find that plugin and remove it from your server (or fix the shading issue)
