### ISSUE TITLE
Bug combatlogx packet protocolib

### ISSUE THREAD

**Issue by omgloer** [dmulloy2/ProtocolLib#1728]
[CombatLogX] Unhandled exception number 64 occurred in onPacketSending(PacketEvent) for CombatLogX
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayer
        at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.onPacketSending(ForceFieldAdapter.java:80) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[?:?]
        at net.minecraft.server.v1_8_R3.NetworkManager.dispatchPacket(NetworkManager.java:347) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:237) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:1193) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1013) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:74) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7) ~[Spigot.jar:]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[Spigot.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[Spigot.jar:]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by Olivoz** [comment]
This is not a Protocollib issue. Update CombatLogX to beta builds
