### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by CaioSIllv17** [dmulloy2/ProtocolLib#1764]
java.lang.IllegalStateException: Failed to obtain login start packet. Did you build Spigot with BuildTools?
  	at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:654)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:80)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.lang.Thread.run(Thread.java:748)
  Dump:
  Parameters: 
    io.netty.buffer.PooledSlicedByteBuf@59bf7ad7[
      adjustment=2
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@632bbfad
      rootParent=PooledUnsafeDirectByteBuf(ridx: 1348, widx: 1357, cap: 2048)
      parent=PooledUnsafeDirectByteBuf(ridx: 1348, widx: 1357, cap: 2048)
      refCnt=2
      readerIndex=1346
      writerIndex=1346
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=1346
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@bebb432[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@78f47a46
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@461c7422
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6f458e70
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3959ed8e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@62a486a9
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@5297bc4
        reporter=com.comphenix.protocol.ProtocolLib$1@47bc43bb
        server=CraftServer{serverName=TacoSpigot,serverVersion=git-NachoSpigot-"74ed0ea",minecraftVersion=1.8.8}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@720adbb8
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7a35d0a4
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@22643c16
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@7e504e61[
      decodeBuffer=protected void net.minecraft.server.v1_8_R3.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.server.v1_8_R3.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@10c6561b
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@44a21457
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.server.v1_8_R3.NetworkManager@47a50459
      originalChannel=[id: 0x0c75668c, L:/172.18.0.18:5003 - R:/172.18.0.1:50250]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_8_R3.NetworkManager.channel], container=net.minecraft.server.v1_8_R3.NetworkManager@47a50459, previous=[id: 0x0c75668c, L:/172.18.0.18:5003 - R:/172.18.0.1:50250], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@22926b94, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4accf075
      vanillaDecoder=net.minecraft.server.v1_8_R3.PacketDecoder@27bc72da
      vanillaEncoder=net.minecraft.server.v1_8_R3.PacketEncoder@3b1788ca
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7a35d0a4
      processor=com.comphenix.protocol.injector.NetworkProcessor@278a9c87
      injected=true
      closed=false
      cumulation=PooledSlicedByteBuf(ridx: 1346, widx: 1346, cap: 1346/1346, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1348, widx: 1357, cap: 2048))
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@6364100e
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    1.8.0_312
  Server:
    git-NachoSpigot-"74ed0ea" (MC: 1.8.8)

**Comment by derklaro** [comment]
Try to use an official fork, not one of these forks which are pulling 500 different patches and modifying stuff they better shouldn't...
