### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by 79kz** [dmulloy2/ProtocolLib#1767]
[22:14:50 INFO]: Error Unable to inject player. (java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.minecraft.server.v1_7_R4.NetworkManager) occured in com.comphenix.protocol.injector.PacketFilterManager@5ba65be3.
[22:14:50 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject player.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.minecraft.server.v1_7_R4.NetworkManager
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldValue(FuzzyReflection.java:104)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:90)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:381)
        at com.comphenix.protocol.injector.PacketFilterManager.onPlayerJoin(PacketFilterManager.java:931)
        at com.comphenix.protocol.injector.PacketFilterManager.access$400(PacketFilterManager.java:71)
        at com.comphenix.protocol.injector.PacketFilterManager$3.onPlayerJoin(PacketFilterManager.java:903)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494)
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:303)
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:186)
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119)
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44)
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:192)
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:809)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:340)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:657)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:546)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Dump:
  Parameters:
    org.bukkit.event.player.PlayerJoinEvent@28b30073[
      joinMessage=┬ºeVisarap joined the game.
      player=CraftPlayer{name=Visarap}
      name=PlayerJoinEvent
      async=false
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5ba65be3[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32131ec8
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2133061
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@12f2f29e
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7b62ca60
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@512d6e9a
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@6191b4b4
        reporter=com.comphenix.protocol.ProtocolLib$1@4aa6cce6
        server=CraftServer{serverName=NitroSpigot,serverVersion=git-NitroSpigot-cff8808,minecraftVersion=1.7.10}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2299436c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e83befb
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@23b43148
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.7.10)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.PacketFilterManager@5ba65be3[
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32131ec8
      packetListeners=[]
      packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2133061
      playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@12f2f29e
      inputBufferedPackets=[]
      recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7b62ca60
      sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@512d6e9a
      hasClosed=false
      classLoader=org.bukkit.plugin.java.PluginClassLoader@6191b4b4
      reporter=com.comphenix.protocol.ProtocolLib$1@4aa6cce6
      server=CraftServer{serverName=NitroSpigot,serverVersion=git-NitroSpigot-cff8808,minecraftVersion=1.7.10}
      library=ProtocolLib v4.8.0
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2299436c
      knowsServerPackets=true
      knowsClientPackets=true
      phaseLoginCount=0
      phasePlayingCount=0
      packetCreation=false
      nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e83befb
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@23b43148
      hasRecycleDistance=true
      minecraftVersion=(MC: 1.7.10)
      debug=false
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    1.8.0_51
  Server:
    git-NitroSpigot-cff8808 (MC: 1.7.10)

[22:14:50 INFO]: Visarap[/127.0.0.1:14069] logged in with entity id 31 at ([world] 13.610776541470393, 106.0, 19.574431626263745)
[22:15:43 INFO]: UUID of player cabru is 5895850f-642e-3977-a273-a9217fd5677c
[22:15:43 ERROR]: Could not pass event PlayerJoinEvent to ProtocolLib v4.8.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[vSpigot.jar:git-NitroSpigot-cff8808]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[vSpigot.jar:git-NitroSpigot-cff8808]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [vSpigot.jar:git-NitroSpigot-cff8808]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:303) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:186) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:192) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:809) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:340) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:657) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:546) [vSpigot.jar:git-NitroSpigot-cff8808]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [vSpigot.jar:git-NitroSpigot-cff8808]
Caused by: java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.minecraft.server.v1_7_R4.NetworkManager
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57) ~[?:?]
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldValue(FuzzyReflection.java:104) ~[?:?]
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:90) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:376) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.onPrePlayerJoin(PacketFilterManager.java:924) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.access$300(PacketFilterManager.java:71) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager$3.onPrePlayerJoin(PacketFilterManager.java:898) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[vSpigot.jar:git-NitroSpigot-cff8808]
        ... 14 more
[22:15:43 INFO]: Error Unable to inject player. (java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.minecraft.server.v1_7_R4.NetworkManager) occured in com.comphenix.protocol.injector.PacketFilterManager@5ba65be3.
[22:15:43 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject player.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.minecraft.server.v1_7_R4.NetworkManager
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldValue(FuzzyReflection.java:104)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:90)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:381)
        at com.comphenix.protocol.injector.PacketFilterManager.onPlayerJoin(PacketFilterManager.java:931)
        at com.comphenix.protocol.injector.PacketFilterManager.access$400(PacketFilterManager.java:71)
        at com.comphenix.protocol.injector.PacketFilterManager$3.onPlayerJoin(PacketFilterManager.java:903)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494)
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:303)
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:186)
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119)
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44)
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:192)
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:809)
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:340)
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:657)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:546)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Dump:
  Parameters:
    org.bukkit.event.player.PlayerJoinEvent@43ff4621[
      joinMessage=┬ºecabru joined the game.
      player=CraftPlayer{name=cabru}
      name=PlayerJoinEvent
      async=false
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5ba65be3[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32131ec8
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2133061
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@12f2f29e
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7b62ca60
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@512d6e9a
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@6191b4b4
        reporter=com.comphenix.protocol.ProtocolLib$1@4aa6cce6
        server=CraftServer{serverName=NitroSpigot,serverVersion=git-NitroSpigot-cff8808,minecraftVersion=1.7.10}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2299436c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e83befb
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@23b43148
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.7.10)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.PacketFilterManager@5ba65be3[
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32131ec8
      packetListeners=[]
      packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2133061
      playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@12f2f29e
      inputBufferedPackets=[]
      recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7b62ca60
      sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@512d6e9a
      hasClosed=false
      classLoader=org.bukkit.plugin.java.PluginClassLoader@6191b4b4
      reporter=com.comphenix.protocol.ProtocolLib$1@4aa6cce6
      server=CraftServer{serverName=NitroSpigot,serverVersion=git-NitroSpigot-cff8808,minecraftVersion=1.7.10}
      library=ProtocolLib v4.8.0
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2299436c
      knowsServerPackets=true
      knowsClientPackets=true
      phaseLoginCount=0
      phasePlayingCount=0
      packetCreation=false
      nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6e83befb
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@23b43148
      hasRecycleDistance=true
      minecraftVersion=(MC: 1.7.10)
      debug=false
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    1.8.0_51
  Server:
    git-NitroSpigot-cff8808 (MC: 1.7.10)

**Comment by derklaro** [comment]
ProtocolLib only supports 1.8+ (which is old enough)
