### ISSUE TITLE
pluginnot loaded

### ISSUE THREAD

**Issue by adriango18** [dmulloy2/ProtocolLib#1768]
the plugin arnet loaded and idk why.

[24jul2022 14:04:58.949] [Server thread/INFO] [com.djrapitops.plan.Plan/]: [Plan] Loading Plan v5.4 build 1722
[24jul2022 14:04:58.951] [Server thread/INFO] [me.wikmor.lpc.LPC/]: [LPC] Loading LPC v3.6.0
[24jul2022 14:04:58.951] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib/]: [ProtocolLib] Loading ProtocolLib v4.8.0
[24jul2022 14:04:59.566] [Server thread/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at TRANSFORMER/forge@40.1.54/org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:328)
  	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:214)
  	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:757)
  	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.RuntimeException: Unable to find network.EnumProtocol (EnumProtocol)
  	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2159)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:776)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:88)
  	... 9 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3b3cbe37[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@69e2bc62
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6acdbd17
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@65cc50f4
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Magma-57004891,minecraftVersion=1.18.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@47a23dd9
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1d374b60
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@47ccb63b
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.3.1
  Server:
    git-Magma-57004891 (MC: 1.18.2)

[24jul2022 14:04:59.567] [Server thread/INFO] [me.lokka30.levelledmobs.LevelledMobs/]: [LevelledMobs] Loading LevelledMobs v3.6.5 b665
[24jul2022 14:04:59.569] [Server thread/INFO] [dev._2lstudios.cleanmotd.bukkit.Main/]: [CleanMOTD] Loading CleanMOTD v0.2.7
[24jul2022 14:04:59.569] [Server thread/INFO] [com.rylinaux.plugman.PlugMan/]: [PlugManX] Loading PlugManX v2.3.0
[24jul2022 14:04:59.569] [Server thread/INFO] [/]: true
[24jul2022 14:04:59.572] [Server thread/INFO] [com.neomechanical.neoperformance.NeoPerformance/]: [NeoPerformance] Enabling NeoPerformance v1.9.8
[24jul2022 14:04:59.717] [Server thread/INFO] [Minecraft/]: [NeoPerformance] NeoPerformance (By KyTDK) is enabled and using bStats!
[24jul2022 14:04:59.724] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Enabling LuckPerms v5.4.30
[24jul2022 14:04:59.938] [Server thread/INFO] [/]: [0;36;1m       [0;36;22m __    [m
[24jul2022 14:04:59.939] [Server thread/INFO] [/]: [0;36;1m  |    [0;36;22m|__)   [0;32;22mLuckPerms[m [0;36;1mv5.4.30[m
[24jul2022 14:04:59.939] [Server thread/INFO] [/]: [0;36;1m  |___ [0;36;22m|      [0;30;1mRunning on Bukkit - CraftBukkit[m
[24jul2022 14:04:59.939] [Server thread/INFO] [/]: [m
[24jul2022 14:04:59.941] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading configuration...
[24jul2022 14:05:00.041] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading storage provider... [H2]
[24jul2022 14:05:00.310] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading internal permission managers...
[24jul2022 14:05:00.359] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Performing initial data load...
[24jul2022 14:05:00.420] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Successfully enabled. (took 695ms)
[24jul2022 14:05:00.421] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib/]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[24jul2022 14:05:00.422] [Server thread/ERROR] [Minecraft/]: ******************************************************
[24jul2022 14:05:00.422] [Server thread/ERROR] [Minecraft/]: *** ProtocolLib does not support plugin reloaders! ***
[24jul2022 14:05:00.422] [Server thread/ERROR] [Minecraft/]: *** Please use the built-in reload command!        ***
[24jul2022 14:05:00.422] [Server thread/ERROR] [Minecraft/]: ******************************************************
[24jul2022 14:05:00.423] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib/]: [ProtocolLib] Disabling ProtocolLib v4.8.0

**Comment by derklaro** [comment]
We only support spigot and forks, like Paper. Please use one of these forks to get support.
