### ISSUE TITLE
Build 580 throws errors in console with some plugins

### ISSUE THREAD

**Issue by CloudeLecaw** [dmulloy2/ProtocolLib#1779]
we uodated from build 577 to Build 580 yesterday

one of our used plugins seems not to like the new build.
i informed them allready, but may you can do something from your side too.
here is the report:

When using latest Wraith with Latest Protocollib version (580 Recommaent download on spigot page for 1.19 server)

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

The console spams many errors with wraith
https://www.toptal.com/developers/hastebin/apoqofufuz.properties

**Comment by derklaro** [comment]
The MethodUtils and FieldUtils classes were both removed from the latest development build. Please use Fuzzy or the Accessors/ExactReflection class instead.

**Comment by Spiritheart95** [comment]
where do I get Fuzzy or Accessors/ExactReflection class

**Comment by derklaro** [comment]
It's available in ProtocolLib?

**Comment by Spiritheart95** [comment]
java.lang.ExceptionInInitializerError
        at ProtocolLib (2).jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:279)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
        at ProtocolLib (2).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at ProtocolLib (2).jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at ProtocolLib (2).jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at ProtocolLib (2).jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at ProtocolLib (2).jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at ProtocolLib (2).jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        ... 10 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@79274392[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@56f6734f
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6ecdb48
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@5633c907
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-70,minecraftVersion=1.19}
      file=plugins/ProtocolLib (2).jar
      description=org.bukkit.plugin.PluginDescriptionFile@62a9662b
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib (2).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@6776b00d
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    17.0.2
  Server:
    git-Paper-70 (MC: 1.19)

**Comment by derklaro** [comment]
You are using version 4.5.1, please update to the latest builds available at https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

**Comment by XionioXMaster** [comment]
> You are using version 4.5.1, please update to the latest builds available at https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ to get 1.19 support

Don't work

**Comment by CloudeLecaw** [comment]
thank you. the dev updated to the last protocil
