### ISSUE TITLE
Field Access Exception

### ISSUE THREAD

**Issue by RocketManKian** [dmulloy2/ProtocolLib#1792]
- [ true ] This issue is not solved in a development build

**Describe the bug**
When a Player joins the game the following message is spammed.
`[22:44:31 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[22:44:31 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket.lambda$static$0(OutMessagePacket.java:90)
[22:44:31 WARN]:        at InteractiveChat-4.2.2.6.jar//com.loohp.interactivechat.listeners.OutMessagePacket$1.onPacketSending(OutMessagePacket.java:363)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:94)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:527)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:469)
[22:44:31 WARN]:        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220)
[22:44:31 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[22:44:31 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[22:44:31 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2141)
[22:44:31 WARN]:        at net.minecraft.network.chat.OutgoingPlayerChatMessage$b.a(OutgoingPlayerChatMessage.java:72)
[22:44:31 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1889)
[22:44:31 WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:1435)
[22:44:31 WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:1414)
[22:44:31 WARN]:        at net.minecraft.server.commands.CommandSay.a(CommandSay.java:19)
[22:44:31 WARN]:        at net.minecraft.commands.arguments.ArgumentChat$a.a(ArgumentChat.java:94)
[22:44:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[22:44:31 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[22:44:31 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:44:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:44:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[22:44:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[22:44:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1195)
[22:44:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[22:44:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**To Reproduce**
1. Use Paper 1.19.1-88
2. Update to ProtocolLib#584
3. Join the Game, perform a command or send a message in chat.

**Expected behaviour**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/47107486/181847284-ca828745-1267-4778-bf02-7e53eeb8e8b3.png)

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://pastebin.com/EnfJRbYA)

**Additional context**
N/A

**Comment by RocketManKian** [comment]
I may have found the culprit for this, InteractiveChat. Once I disabled this, the errors went away

**Comment by derklaro** [comment]
👍 This issue is caused by InteractiveChat, please report it to them (but I guess you only need to update the plugin to get 1.19.1 support)
