### ISSUE TITLE
Unable to intercept a read client packet

### ISSUE THREAD

**Issue by Basik01** [dmulloy2/ProtocolLib#1795]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [ ] This isn't fixed in a recent development build
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

Debug paste link:
Stack Trace: java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397) at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57) at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:651)
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:584) at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at java.base/java.lang.Thread.run(Thread.java:833) Dump: Parameters: io.netty.buffer.PooledUnsafeDirectByteBuf@f37b609[ memoryAddress=22996834021392 recyclerHandle=io.netty.util.Recycler$DefaultHandle@4a8db30e chunk=Chunk(50c8f3c9: 15%, 622592/4194304) handle=563014377930752 memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304] offset=8192 length=34 maxLength=48 cache=io.netty.buffer.PoolThreadCache@4bc735f8 tmpNioBuf=
allocator=PooledByteBufAllocator(directByDefault: true) refCnt=2 readerIndex=34 writerIndex=34 markedReaderIndex=0 markedWriterIndex=0 maxCapacity=2147483647 ] manager: com.comphenix.protocol.injector.PacketFilterManager@30ce8313[ unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@42540807 packetListeners=[PacketAdapter[plugin=MyCommand, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]]] packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@ed502dc playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@52d232ec inputBufferedPackets=[] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@16c0f5be sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7436c351
hasClosed=false classLoader=org.bukkit.plugin.java.PluginClassLoader@5a8aa937 reporter=com.comphenix.protocol.ProtocolLib$1@5253ece9 server=CraftServer{serverName=CraftBukkit,serverVersion=3558-Spigot-2183145-401f1ad,minecraftVersion=1.19.1} library=ProtocolLib v4.8.0-SNAPSHOT-b538 asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@298b9c knowsServerPackets=true knowsClientPackets=true phaseLoginCount=0 phasePlayingCount=1 packetCreation=false nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7d64b9b9 pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3a7172 hasRecycleDistance=true minecraftVersion=(MC: 1.19.1) debug=false ] Sender: com.comphenix.protocol.injector.netty.ChannelInjector@7c5c3f37[ decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception factory=com.comphenix.protocol.injector.netty.InjectionFactory@2bc5ec95 player=CraftPlayer{name=Basik_1} updated= playerName=Basik_1 playerConnection= networkManager=net.minecraft.network.NetworkManager@25460aad originalChannel=[id: 0x7cfbd435, L:/51.161.197.124:25905 - R:/58.84.145.94:7069] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@25460aad, previous=[id: 0x7cfbd435, L:/51.161.197.124:25905 - R:/58.84.145.94:7069], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2d499ff6, previousLoaded=true, currentSet=true, forceAccess=true] packetMarker={} currentEvent= finalEvent=
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@24b2ec85 vanillaDecoder=net.minecraft.network.PacketDecoder@456571ca vanillaEncoder=net.minecraft.network.PacketEncoder@46fce427 finishQueue=[] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7d64b9b9 processor=com.comphenix.protocol.injector.NetworkProcessor@76dfc16a injected=true closed=false cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34) cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@185a055a singleDecode=false first=true firedChannelRead=false selfFiredChannelRead=true decodeState=1 discardAfterReads=16 numReads=0 added=true ] Version:
rate limit exceeded
Description and relevant errors:

**Comment by derklaro** [comment]
Please use the builds from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ for 1.19+ support
