### ISSUE TITLE
StreamSerializer compatible issues

### ISSUE THREAD

**Issue by caoli5288** [dmulloy2/ProtocolLib#1813]
- [x] This issue is not solved in a development build

**Describe the bug**
ItemStack serialized by 4.x's cannot deserialize by 5.0.0

**To Reproduce**
1. Serialize ItemStack by StreamSerializer.serializeItemStack on ProtocolLib-4.8.0
2. Deserialize on ProtocolLib-5.0.0 from CI
3. You got an exception

**Expected behavior**
:-)

**Screenshots**
None

**Version Info**
4.8.0

**Additional context**
None

**Comment by derklaro** [comment]
> You got an exception

Please attach the exception.

**Comment by caoli5288** [comment]
> 

```
[11:08:14] [pool-31-1/0/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Illegal base64 character a
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[11:08:14] [pool-31-1/0/WARN]: Caused by: java.lang.IllegalArgumentException: Illegal base64 character a
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
[11:08:14] [pool-31-1/0/WARN]: 	at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
[11:08:14] [pool-31-1/0/WARN]: 	at com.comphenix.protocol.utility.StreamSerializer.deserializeItemStack(StreamSerializer.java:188)
```

**Comment by caoli5288** [comment]
@dmulloy2 Seems related to https://github.com/dmulloy2/ProtocolLib/pull/1561/files#diff-d29a47768619219ac20f622b8e142c205b68a2edbe41396fab46b9280e61dbf4 changed the Base64 codec
