### ISSUE TITLE
On server start error

### ISSUE THREAD

**Issue by Gorodlilov** [dmulloy2/ProtocolLib#1817]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
        at ProtocolLib.jar//com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:82)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1369)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:721)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.findNetworkManager(InjectionFactory.java:255)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromChannel(InjectionFactory.java:168)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.InjectionChannelInboundHandler.channelActive(InjectionChannelInboundHandler.java:36)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:522)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@211f408e[
        plugin=ProtocolLib v5.0.0-SNAPSHOT-b580
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-81,minecraftVersion=1.19}
        reporter=com.comphenix.protocol.ProtocolLib$1@4d170fa0
        minecraftVersion=(MC: 1.19.0)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2c91366e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@77510842
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@73964c43
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@689279e
        registeredListeners=[PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=17], SET_SLOT[class=PacketPlayOutSetSlot, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@238e4367
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@5c624c4c
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@1d57f7d7
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@1d57f7d7[
      inboundListeners=com.comphenix.protocol.concurrency.PacketTypeSet@369727d
      outboundListeners=com.comphenix.protocol.concurrency.PacketTypeSet@4da75e70
      mainThreadListeners=com.comphenix.protocol.concurrency.PacketTypeSet@6fece15c
      overriddenLists=[com.comphenix.protocol.wrappers.Pair@9b3b9245]
      errorReporter=com.comphenix.protocol.ProtocolLib$1@4d170fa0
      listenerInvoker=com.comphenix.protocol.injector.PacketFilterManager@211f408e
      injectionFactory=com.comphenix.protocol.injector.netty.channel.InjectionFactory@51cec6a3
      packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@238e4367
      playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@5c624c4c
      pipelineInjectorHandler=com.comphenix.protocol.injector.netty.manager.InjectionChannelInitializer@197cac7d
      debug=false
      closed=false
      injected=true
    ]
  Version:
    ProtocolLib v5.0.0-SNAPSHOT-b580
  Java Version:
    17.0.2
  Server:
    git-Paper-81 (MC: 1.19)

**Comment by derklaro** [comment]
Update ProtocolLib, that issue was fixed a few builds ago
