### ISSUE TITLE
Unhandled exception occured in onPacket

### ISSUE THREAD

**Issue by Draigo1984** [dmulloy2/ProtocolLib#1818]
[00:33:21 ERROR]: [HolographicExtension] Unhandled exception occured in onPacket
Sending(PacketEvent) for HolographicExtension
java.lang.RuntimeException: Unable to clone object PacketContainer[type=ENTITY_M
ETADATA[class=PacketPlayOutEntityMetadata, id=77], structureModifier=StructureMo
difier[fieldType=class java.lang.Object, data=[private final int net.minecraft.n
etwork.protocol.game.PacketPlayOutEntityMetadata.a, private final java.util.List
 net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.b]]] (com.comph
enix.protocol.events.PacketContainer)
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(Seria
lizableCloner.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContain
er.java:256) ~[ProtocolLib.jar:?]
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacke
tSending(PacketPlaceholderListener.java:56) ~[HolographicExtension-1.10.9.jar:?]

        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendin
gListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket
Sending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(Pack
etFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSendi
ng(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(P
rotocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSendin
g(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(
ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(Chan
nelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleSchedul
ed(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageSche
duled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnab
le(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoo
pProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[a
pp:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(Server
GamePacketListenerImpl.java:1997) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(Server
GamePacketListenerImpl.java:1983) ~[app:?]
        at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.
java:285) ~[app:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:
268) ~[app:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkM
ap.java:2403) ~[app:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(Chunk
Map.java:2314) ~[app:?]
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:2010) ~[p
atched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCach
e.java:1166) ~[app:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStar
t(ServerLevel.java:2381) ~[app:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.
java:2337) ~[app:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.start
Tracking(PersistentEntitySectionManager.java:227) ~[patched_1.17.1.jar:git-Paper
-408]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEn
tity(PersistentEntitySectionManager.java:187) ~[patched_1.17.1.jar:git-Paper-408
]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNe
wEntity(PersistentEntitySectionManager.java:166) ~[patched_1.17.1.jar:git-Paper-
408]
        at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:14
04) ~[app:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.jav
a:1306) ~[app:?]
        at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2192)
~[app:?]
        at net.minecraft.world.entity.player.Player.drop(Player.java:693) ~[app:
?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractC
ontainerMenu.java:638) ~[app:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractC
ontainerMenu.java:371) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleConta
inerClick(ServerGamePacketListenerImpl.java:2815) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.h
andle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.h
andle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSame
Thread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.
jar:git-Paper-408]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEvent
Loop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(Reent
rantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1
426) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java
:192) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventL
oop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer
.java:1404) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:13
97) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEv
entLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServe
r.java:1375) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1
286) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.ja
va:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matc
hes {modifiers=[required: 1000, banned: 0], return=Exact class net.minecraft.net
work.protocol.game.PacketPlayOutEntityMetadata, params=[{Type: Exact class net.m
inecraft.network.PacketDataSerializer, Index: 0}], paramCount=1}
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflect
ion.java:174) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.readObject(PacketContai
ner.java:330) ~[ProtocolLib.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor192.invoke(Unknown Source
) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMe
thodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:123
1) ~[?:?]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434)
 ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2
268) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744) ~[
?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:
?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:
?]
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(Seria
lizableCloner.java:42) ~[ProtocolLib.jar:?]
        ... 52 more
[00:33:21 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@296f5767[
    a=8036
    b=[net.minecraft.network.syncher.DataWatcher$Item@35b0d0f, net.minecraft.net
work.syncher.DataWatcher$Item@4a213a36, net.minecraft.network.syncher.DataWatche
r$Item@3fc5e2fe, net.minecraft.network.syncher.DataWatcher$Item@749728d5, net.mi
necraft.network.syncher.DataWatcher$Item@2fff603d, net.minecraft.network.syncher
.DataWatcher$Item@6c4c1f7e, net.minecraft.network.syncher.DataWatcher$Item@7c8ed
21b, net.minecraft.network.syncher.DataWatcher$Item@31928cdf, net.minecraft.netw
ork.syncher.DataWatcher$Item@65b8ec58]
  ]

**Comment by derklaro** [comment]
Please update ProtocolLib to the dev build (available here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) as there were some improvements made to packet cloning which might either resolve your issue or give us more context on what went wrong.

**Comment by balatamoghna** [comment]
I am running Snapshot-b588 and also face this issue.
Context (In my case): I installed CustomCrafting for 1.19.2 and while the plugins seem to work fine, there are sometimes when the console is swamped with the above error message (but for CustomCrafting)
Running Purpur, on a raspberrypi4 8GB ram and there were no issues before this.

Issue seems to show up at: https://github.com/PaperMC/Paper/issues/5220 too

`[07:57:49 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutRecipes@2dd635df[
    a=ADD
    b=[minecraft:deepslate_tile_wall_from_cobbled_deepslate_stonecutting]
    c=[]
    d=net.minecraft.stats.RecipeBookSettings@a57fd46c
  ]

[07:57:49 ERROR]: [CustomCrafting] Unhandled exception occurred in onPacketSendi                                                                                                                                                             ng(PacketEvent) for CustomCrafting
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier c                                                                                                                                                             om.comphenix.protocol.reflect.StructureModifier.modify(int, com.google.common.ba                                                                                                                                                             se.Function)'
        at me.wolfyscript.customcrafting.utils.other_plugins.ProtocolLib$1.onPac                                                                                                                                                             ketSending(ProtocolLib.java:94) ~[customcrafting-spigot-3.16.6.2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendin                                                                                                                                                             gListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacket                                                                                                                                                             Sending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListe                                                                                                                                                             ners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSendi                                                                                                                                                             ng(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.                                                                                                                                                             onPacketSending(NetworkManagerInjector.java:94) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.pr                                                                                                                                                             ocessOutbound(NettyChannelInjector.java:527) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.                                                                                                                                                             proxyRunnable(NettyChannelInjector.java:469) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.exe                                                                                                                                                             cute(NettyEventLoopProxy.java:220) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:                                                                                                                                                             ?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(Server                                                                                                                                                             GamePacketListenerImpl.java:2258) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(Server                                                                                                                                                             GamePacketListenerImpl.java:2244) ~[?:?]
        at net.minecraft.stats.ServerRecipeBook.sendRecipes(ServerRecipeBook.jav                                                                                                                                                             a:76) ~[?:?]
        at net.minecraft.stats.ServerRecipeBook.addRecipes(ServerRecipeBook.java                                                                                                                                                             :50) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.awardRecipes(ServerPlayer.jav                                                                                                                                                             a:1688) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.awardRecipesByKey(ServerPlaye                                                                                                                                                             r.java:1705) ~[?:?]
        at net.minecraft.advancements.AdvancementRewards.grant(AdvancementReward                                                                                                                                                             s.java:69) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.PlayerAdvancements.award(PlayerAdvancements.java                                                                                                                                                             :298) ~[?:?]
        at net.minecraft.advancements.CriterionTrigger$Listener.run(CriterionTri                                                                                                                                                             gger.java:35) ~[?:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(S                                                                                                                                                             impleCriterionTrigger.java:73) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.lambda$tr                                                                                                                                                             igger$0(InventoryChangeTrigger.java:57) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(I                                                                                                                                                             nventoryChangeTrigger.java:53) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$2.slotChanged(ServerPlayer.ja                                                                                                                                                             va:320) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListen                                                                                                                                                             ers(AbstractContainerMenu.java:305) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(                                                                                                                                                             AbstractContainerMenu.java:242) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.take(ServerPlayer.java:1322)                                                                                                                                                              ~[?:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.jav                                                                                                                                                             a:492) ~[?:?]
        at net.minecraft.world.entity.player.Player.touch(Player.java:671) ~[?:?                                                                                                                                                             ]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:637) ~[?:                                                                                                                                                             ?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3034)                                                                                                                                                              ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:308) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:695)                                                                                                                                                              ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(Server                                                                                                                                                             GamePacketListenerImpl.java:383) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:588) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConn                                                                                                                                                             ectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.jav                                                                                                                                                             a:1611) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(Dedicated                                                                                                                                                             Server.java:485) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:                                                                                                                                                             1443) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1                                                                                                                                                             213) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.ja                                                                                                                                                             va:310) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by derklaro** [comment]
That's not related to ProtocolLib, custom crafting used an older version of PLib to compile against and needs to update.

**Comment by balatamoghna** [comment]
Alright, thanks!

**Comment by Draigo1984** [comment]
> Please update ProtocolLib to the dev build (available here: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) as there were some improvements made to packet cloning which might either resolve your issue or give us more context on what went wrong.

more error gives I change and

**Comment by derklaro** [comment]
Then please attach the new stacktrace which you saw after updating...
