### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by sammikinsrox** [dmulloy2/ProtocolLib#1837]
I am using plugins: 
 * AngelChestFree 9.6.3
 * CommandTool 2.2.0
 * Discord Integration 2.4.7
 * EssentialsX 2.20.0
 * [Exalted Economy](https://www.spigotmc.org/resources/exaltedeconomy-all-in-one-economy-system-bungee-support.92207/) 2.6.2
 * [Exalted Core](https://www.spigotmc.org/resources/exaltedcore.96535/) 1.3.2
 * GeyserMC with Floodgate build-1164
 * [GriefDefender](https://www.spigotmc.org/resources/1-12-2-1-19-1-griefdefender-claim-plugin-grief-prevention-protection.68900/) 2.2.2
 * LuckPerms 5.3.89
 * [Lumberjack](https://www.spigotmc.org/resources/lumberjack-tree-gravity-leaf-decay-custom-tree-drops.60306/) 5.2.1
 * [Markets](https://www.spigotmc.org/resources/markets-the-ultimate-player-shop.92178/) 1.31.0
 * [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/) 4.8.0
 * Vault 1.7.3
 
This is a fresh install of ProtocolLib. I am performing a server update to add GriefDefender, ExaltedEconomy, ExaltedCore, ProtocolLib Markets. None of these plugins have been configured yet. This was the second startup after the first start to initialize the plugins and create necessary config files; I run startup twice to let everything configure and then a second startup to locate errors in the console. These errors popped up.
 
 The error reads:
`[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.`

Stacktrace:
```
12.08 22:08:26 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
12.08 22:08:26 [Server] INFO If this problem hasn't already been reported, please open a ticket
12.08 22:08:26 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
12.08 22:08:26 [Server] INFO Stack Trace:
12.08 22:08:26 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
12.08 22:08:26 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
12.08 22:08:26 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
12.08 22:08:26 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
12.08 22:08:26 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
12.08 22:08:26 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
12.08 22:08:26 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:833)
12.08 22:08:26 [Server] INFO Dump:
12.08 22:08:26 [Server] INFO Parameters: 
12.08 22:08:26 [Server] INFO io.netty.buffer.PooledUnsafeDirectByteBuf@40fd9623[
12.08 22:08:26 [Server] INFO memoryAddress=140359734987152
12.08 22:08:26 [Server] INFO recyclerHandle=NOOP_HANDLE
12.08 22:08:26 [Server] INFO chunk=Chunk(5050724d: 1%, 16384/4194304)
12.08 22:08:26 [Server] INFO handle=562980018192384
12.08 22:08:26 [Server] INFO memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
12.08 22:08:26 [Server] INFO offset=8192
12.08 22:08:26 [Server] INFO length=21
12.08 22:08:26 [Server] INFO maxLength=32
12.08 22:08:26 [Server] INFO cache=io.netty.buffer.PoolThreadCache@106e4120
12.08 22:08:26 [Server] INFO tmpNioBuf=<null>
12.08 22:08:26 [Server] INFO allocator=PooledByteBufAllocator(directByDefault: true)
12.08 22:08:26 [Server] INFO refCnt=2
12.08 22:08:26 [Server] INFO readerIndex=21
12.08 22:08:26 [Server] INFO writerIndex=21
12.08 22:08:26 [Server] INFO markedReaderIndex=0
12.08 22:08:26 [Server] INFO markedWriterIndex=0
12.08 22:08:26 [Server] INFO maxCapacity=2147483647
12.08 22:08:26 [Server] INFO ]
12.08 22:08:26 [Server] INFO manager:
12.08 22:08:26 [Server] INFO com.comphenix.protocol.injector.PacketFilterManager@24b6105a[
12.08 22:08:26 [Server] INFO unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@463322ad
12.08 22:08:26 [Server] INFO packetListeners=[]
12.08 22:08:26 [Server] INFO packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@e79b97a
12.08 22:08:26 [Server] INFO playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4720b6c2
12.08 22:08:26 [Server] INFO inputBufferedPackets=[]
12.08 22:08:26 [Server] INFO recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@53005abc
12.08 22:08:26 [Server] INFO sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@cf92c3b
12.08 22:08:26 [Server] INFO hasClosed=false
12.08 22:08:26 [Server] INFO classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
12.08 22:08:26 [Server] INFO reporter=com.comphenix.protocol.ProtocolLib$1@4f88f6b7
12.08 22:08:26 [Server] INFO server=CraftServer{serverName=Paper,serverVersion=git-Paper-118,minecraftVersion=1.19.2}
12.08 22:08:26 [Server] INFO library=ProtocolLib v4.8.0
12.08 22:08:26 [Server] INFO asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5cd8b19f
12.08 22:08:26 [Server] INFO knowsServerPackets=true
12.08 22:08:26 [Server] INFO knowsClientPackets=true
12.08 22:08:26 [Server] INFO phaseLoginCount=0
12.08 22:08:26 [Server] INFO phasePlayingCount=0
12.08 22:08:26 [Server] INFO packetCreation=false
12.08 22:08:26 [Server] INFO nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@63b35c40
12.08 22:08:26 [Server] INFO pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@54377d63
12.08 22:08:26 [Server] INFO hasRecycleDistance=true
12.08 22:08:26 [Server] INFO minecraftVersion=(MC: 1.19.2)
12.08 22:08:26 [Server] INFO debug=false
12.08 22:08:26 [Server] INFO ]
12.08 22:08:26 [Server] INFO Sender:
12.08 22:08:26 [Server] INFO com.comphenix.protocol.injector.netty.ChannelInjector@40a35141[
12.08 22:08:26 [Server] INFO decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
12.08 22:08:26 [Server] INFO encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
12.08 22:08:26 [Server] INFO factory=com.comphenix.protocol.injector.netty.InjectionFactory@310bc392
12.08 22:08:26 [Server] INFO player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@5e387cb5
12.08 22:08:26 [Server] INFO updated=<null>
12.08 22:08:26 [Server] INFO playerName=<null>
12.08 22:08:26 [Server] INFO playerConnection=<null>
12.08 22:08:26 [Server] INFO networkManager=net.minecraft.network.NetworkManager@44b176a
12.08 22:08:26 [Server] INFO originalChannel=[id: 0x4a23cc7c, L:/147.135.72.197:25565 - R:/154.21.20.207:40740]
12.08 22:08:26 [Server] INFO channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@44b176a, previous=[id: 0x4a23cc7c, L:/147.135.72.197:25565 - R:/154.21.20.207:40740], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@3e2d6508, previousLoaded=true, currentSet=true, forceAccess=true]
12.08 22:08:26 [Server] INFO packetMarker={}
12.08 22:08:26 [Server] INFO currentEvent=<null>
12.08 22:08:26 [Server] INFO finalEvent=<null>
12.08 22:08:26 [Server] INFO unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@68bb6684
12.08 22:08:26 [Server] INFO vanillaDecoder=net.minecraft.network.PacketDecoder@3d6b5bbe
12.08 22:08:26 [Server] INFO vanillaEncoder=net.minecraft.network.PacketEncoder@5544ed6e
12.08 22:08:26 [Server] INFO finishQueue=[]
12.08 22:08:26 [Server] INFO channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@63b35c40
12.08 22:08:26 [Server] INFO processor=com.comphenix.protocol.injector.NetworkProcessor@746adecd
12.08 22:08:26 [Server] INFO injected=true
12.08 22:08:26 [Server] INFO closed=false
12.08 22:08:26 [Server] INFO cumulation=PooledUnsafeDirectByteBuf(ridx: 21, widx: 21, cap: 21)
12.08 22:08:26 [Server] INFO cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@13bbcd55
12.08 22:08:26 [Server] INFO singleDecode=false
12.08 22:08:26 [Server] INFO first=true
12.08 22:08:26 [Server] INFO firedChannelRead=false
12.08 22:08:26 [Server] INFO selfFiredChannelRead=true
12.08 22:08:26 [Server] INFO decodeState=1
12.08 22:08:26 [Server] INFO discardAfterReads=16
12.08 22:08:26 [Server] INFO numReads=0
12.08 22:08:26 [Server] INFO added=true
12.08 22:08:26 [Server] INFO ]
12.08 22:08:26 [Server] INFO Version:
12.08 22:08:26 [Server] INFO ProtocolLib v4.8.0
12.08 22:08:26 [Server] INFO Java Version:
12.08 22:08:26 [Server] INFO 17.0.3
12.08 22:08:26 [Server] INFO Server:
12.08 22:08:26 [Server] INFO git-Paper-118 (MC: 1.19.2)
12.08 22:08:26 [Server] INFO Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@40a35141.
```

Stacktrace 2 (Another set of errors from the same startup and plugin initialization):
```
12.08 22:08:26 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
12.08 22:08:26 [Server] INFO If this problem hasn't already been reported, please open a ticket
12.08 22:08:26 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
12.08 22:08:26 [Server] INFO Stack Trace:
12.08 22:08:26 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
12.08 22:08:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.08 22:08:26 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
12.08 22:08:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.08 22:08:31 [Multicraft] Skipped 104 lines due to rate limit (160/s)
```

**Comment by Peng1104** [comment]
Have you tested this problem with the [DEV](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) version? I the spigot website says that for MC 1.19 the DEV one should be used

**Comment by sammikinsrox** [comment]
Nope! Thank you, I didn't see that mentioned, I must have overlooked it. Thank you for your help!

**Comment by sammikinsrox** [comment]
Yes, this resolved my issue. Updating to the DEV version has made these errors stop cropping up.
