### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by McuPvP** [dmulloy2/ProtocolLib#1849]
When the server starts it rapidly sends error message FOREVER!

protocolib 4.8

**Additional context**
[14:16:49 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 64!
[14:16:49 INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@1af6574.
[14:16:49 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib (2).jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib (2).jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:651)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:584)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@569c1f1f[
      memoryAddress=140699504772832
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@931c817
      chunk=Chunk(9b66a1c: 1%, 32768/4194304)
      handle=1688879925035009
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=24592
      length=1
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@623d5f59
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4b3a9256[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4ffb5767
        packetListeners=[me.galaxyeater.protocolfirewall.d.c.g.a@45f1f111, me.galaxyeater.a.b.b@842ee26, me.galaxyeater.protocolfirewall.d.b.a@7557f9f2, me.galaxyeater.protocolfirewall.d.d.a@54e85e2, me.galaxyeater.protocolfirewall.d.g.b@5265e309, me.galaxyeater.a.b.e@69b243dd, me.galaxyeater.protocolfirewall.d.c.d.a@1066c36, me.galaxyeater.protocolfirewall.b.c.b@144fa37f, me.galaxyeater.protocolfirewall.d.n.c@3c601313, me.galaxyeater.protocolfirewall.b.c.a@31522e81, me.galaxyeater.protocolfirewall.d.k.a.a@3e35aa62, me.galaxyeater.protocolfirewall.d.p.a@62a2d75, me.galaxyeater.a.b.a@3d97eba8]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5bbdc177
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@56be7997
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4909e934
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5cdcdf1d
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.7.0, pluginEnabled=true, url=plugins/ProtocolLib (2).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@695f1b88
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-127,minecraftVersion=1.19.2}
        library=ProtocolLib v4.7.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4acea509
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=5
        phasePlayingCount=13
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5735599a
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@22eb0779
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@1af6574[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@5d254755
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@68bd0e6b
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@59915bd5
      originalChannel=[id: 0xbb1fdf3e, L:/172.18.0.35:25592 - R:/168.119.13.250:35024]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@59915bd5, previous=[id: 0xbb1fdf3e, L:/172.18.0.35:25592 - R:/168.119.13.250:35024], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@100a04c1, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@10449efd
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@435830d3
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@b25a5ae
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5735599a
      processor=com.comphenix.protocol.injector.NetworkProcessor@7f4e48e5
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@6942798c
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    17.0.2
  Server:
    git-Paper-127 (MC: 1.19.2)

**Comment by Peng1104** [comment]
@McuPvP  Update ProtocolLib to latest dev version, read spigot page.
