### ISSUE TITLE
Some kind of console error

### ISSUE THREAD

**Issue by shadow0316** [dmulloy2/ProtocolLib#1855]
- [x] This issue is not solved in a development build

**Describe the bug**

I don't know what the bug is but ill tell you what it's doing, it's giving me random errors and told me to report it here so here it is

Stack Trace:
[16.08 16:22:54] [Server]   java.lang.IllegalArgumentExceptionUnable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
[16.08 16:22:54] [Server]   	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
[16.08 16:22:54] [Server]   	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
[16.08 16:22:54] [Server]   	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
[16.08 16:22:54] [Server]   	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16.08 16:22:54] [Server]   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16.08 16:22:54] [Server]   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16.08 16:22:54] [Server]   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16.08 16:22:54] [Server]   	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[16.08 16:22:54] [Server]   	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[16.08 16:22:54] [Server]   	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[16.08 16:22:54] [Server]   	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[16.08 16:22:54] [Server]   	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16.08 16:22:54] [Server]   	at java.base/java.lang.Thread.run(Thread.java:833)
[16.08 16:22:54] [Server]   Dump:
[16.08 16:22:54] [Server]   Parameters
[16.08 16:22:54] [Server]     io.netty.buffer.PooledUnsafeDirectByteBuf@4fa5bbdf[
[16.08 16:22:54] [Server]       memoryAddress=140063044354864
[16.08 16:22:54] [Server]       recyclerHandle=io.netty.util.Recycler$DefaultHandle@44c4b8ea
[16.08 16:22:54] [Server]       chunk=Chunk(721a9f18%, 737280/4194304)
[16.08 16:22:54] [Server]       handle=562980018192384
[16.08 16:22:54] [Server]       memory=java.nio.DirectByteBuffer[pos=lim=4194304 cap=4194304]
[16.08 16:22:54] [Server]       offset=8192
[16.08 16:22:54] [Server]       length=26
[16.08 16:22:54] [Server]       maxLength=32
[16.08 16:22:54] [Server]       cache=io.netty.buffer.PoolThreadCache@637d677a
[16.08 16:22:54] [Server]       tmpNioBuf=<null>
[16.08 16:22:54] [Server]       allocator=PooledByteBufAllocator(directByDefaulttrue)
[16.08 16:22:54] [Server]       refCnt=2
[16.08 16:22:54] [Server]       readerIndex=26
[16.08 16:22:54] [Server]       writerIndex=26
[16.08 16:22:54] [Server]       markedReaderIndex=0
[16.08 16:22:54] [Server]       markedWriterIndex=0
[16.08 16:22:54] [Server]       maxCapacity=2147483647
[16.08 16:22:54] [Server]     ]
[16.08 16:22:54] [Server]     manager:
[16.08 16:22:54] [Server]       com.comphenix.protocol.injector.PacketFilterManager@27444c34[
[16.08 16:22:54] [Server]         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@44f94f9d
[16.08 16:22:54] [Server]         packetListeners=[]
[16.08 16:22:54] [Server]         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@469f76a6
[16.08 16:22:54] [Server]         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@30c9a0ff
[16.08 16:22:54] [Server]         inputBufferedPackets=[]
[16.08 16:22:54] [Server]         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35e97f3e
[16.08 16:22:54] [Server]         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3be24bb9
[16.08 16:22:54] [Server]         hasClosed=false
[16.08 16:22:54] [Server]         classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
[16.08 16:22:54] [Server]         reporter=com.comphenix.protocol.ProtocolLib$1@6f52025
[16.08 16:22:54] [Server]         server=CraftServer{serverName=Paper,serverVersion=git-Paper-130,minecraftVersion=1.19.2}
[16.08 16:22:54] [Server]         library=ProtocolLib v4.8.0
[16.08 16:22:54] [Server]         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5283695
[16.08 16:22:54] [Server]         knowsServerPackets=true
[16.08 16:22:54] [Server]         knowsClientPackets=true
[16.08 16:22:54] [Server]         phaseLoginCount=0
[16.08 16:22:54] [Server]         phasePlayingCount=0
[16.08 16:22:54] [Server]         packetCreation=false
[16.08 16:22:54] [Server]         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@15942453
[16.08 16:22:54] [Server]         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@27dc522b
[16.08 16:22:54] [Server]         hasRecycleDistance=true
[16.08 16:22:54] [Server]         minecraftVersion=(MC1.19.2)
[16.08 16:22:54] [Server]         debug=false
[16.08 16:22:54] [Server]       ]

**Comment by Peng1104** [comment]
@shadow0316 Have you tested this problem with the [DEV](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) version? I the spigot website says that for MC 1.19+ the dev one should be used and you are using the latest stable one (4.8.0)
