### ISSUE TITLE
mojang.authlib.GameProfile

### ISSUE THREAD

**Issue by 502milk** [dmulloy2/ProtocolLib#1860]
[12:19:39 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@736c98dc[
      memoryAddress=2436496490560
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@2ee79e95
      chunk=Chunk(775725a9: 1%, 32768/4194304)
      handle=562980018192384
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8192
      length=9
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@697d1393
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=9
      writerIndex=9
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@66765f32[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6d03402e
        packetListeners=[cn.jiongjionger.log4jfixer.listener.ChatPacketListener@48d8343a]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1a938470
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@59c2eab0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@d99b175
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7aec82d8
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@7c5a39f1
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1725,minecraftVersion=1.19}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@72d1d68c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@11661a45
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@56963f25
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.0)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@6fd06eb1[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@28ab85a8
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@3aa1cdcb
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@58868d0d
      originalChannel=[id: 0xf35fd9a2, L:/127.0.0.1:1314 - R:/127.0.0.1:2335]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@58868d0d, previous=[id: 0xf35fd9a2, L:/127.0.0.1:1314 - R:/127.0.0.1:2335], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5eb2b1b6, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@6ac9f03e
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@6cbf68f
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@6b78bcec
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@11661a45
      processor=com.comphenix.protocol.injector.NetworkProcessor@561c30b
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@9d2a771
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    git-Purpur-1725 (MC: 1.19)

**Comment by LeGeek01** [comment]
same error with PaperMC 1.19.2 (Java 17)

**Comment by Peng1104** [comment]
@502milk / @LeGeek01 Have you tested this problem with the [DEV](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) version? I the spigot website says that for MC 1.19+ the dev one should be used and you are using the latest stable one (4.8.0)

**Comment by Peng1104** [comment]
#1837
#1838
#1845
#1855
#1859
#1860

**Comment by LeGeek01** [comment]
Good idea, I try the dev version as soon as I can
