### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by RihardKeegi** [dmulloy2/ProtocolLib#1893]
[15:55:15 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at protocollib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at protocollib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at protocollib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at protocollib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at protocollib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@380f5be0[
      memoryAddress=139903862565312
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6c2cd9fc
      chunk=Chunk(3d693cc0: 21%, 868352/4194304)
      handle=20829178341359616
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=303104
      length=10
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@2d82ceec
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=10
      writerIndex=10
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@545a4164[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@31fc96eb
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@57cfda9e
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@182add14
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1e7dee14
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4be368fe
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/protocollib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@2c5de305
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-138,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@dd58206
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@57d04667
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5faec984
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@20324881[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@b540bd7
      player=CraftPlayer{name=Eestimangur}
      updated=<null>
      playerName=Eestimangur
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@23a9574
      originalChannel=[id: 0x32708e4d, L:/172.18.0.9:3304 - R:/81.90.124.253:27458]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@23a9574, previous=[id: 0x32708e4d, L:/172.18.0.9:3304 - R:/81.90.124.253:27458], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@23e59f8, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@50249460
      vanillaDecoder=net.minecraft.network.PacketDecoder@2025f605
      vanillaEncoder=net.minecraft.network.PacketEncoder@12d47d80
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@57d04667
      processor=com.comphenix.protocol.injector.NetworkProcessor@773a9a68
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 10, widx: 10, cap: 10)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@7820cf54
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-138 (MC: 1.19.2)
    
    I get this when im joining the server

**Comment by SkyLicks** [comment]
Use Protocol Lib 5.0 (dev build)
![image](https://user-images.githubusercontent.com/34877092/188282973-966b9294-3411-4ff3-bb24-8453baa87de3.png)

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
