### ISSUE TITLE
Error 1.19.2

### ISSUE THREAD

**Issue by ShadowJaypeeBeast** [dmulloy2/ProtocolLib#1895]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib4.8.0.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib4.8.0.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib4.8.0.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib4.8.0.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib4.8.0.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@75b1520d[
      memoryAddress=140176055882704
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@65d2ca49
      chunk=Chunk(410fed18: 2%, 65536/4194304)
      handle=562980018192384
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8192
      length=19
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@4e8a50a9
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=19
      writerIndex=19
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@6f7129ff[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3e1f305a
        packetListeners=[PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=HoloMobHealth, sending=ListeningWhitelist[priority=HIGHEST, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54], ABILITIES[class=ClientboundPlayerChatHeaderPacket, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=HoloMobHealth, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=IllegalStack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AureliumSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[PLAY, SERVER, 15, classNames: [net.minecraft.network.protocol.game.PacketPlayOutChat, net.minecraft.network.protocol.game.ClientboundChatPacket, net.minecraft.network.play.server.SPacketChat] (unregistered)]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AureliumSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=65]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7c9ca5de
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@362a141
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@653a5e03
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@22603f1e
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib4.8.0.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@3b4bdcd9
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-138,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1a4883ab
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=3
        phasePlayingCount=14
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7d2da8e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@203fdf08
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@1633127d[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7b77f56c
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@14b0e807
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@6b6ef1a6
      originalChannel=[id: 0x98d3af92, L:/172.18.0.27:20148 - R:/65.21.122.36:52134]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@6b6ef1a6, previous=[id: 0x98d3af92, L:/172.18.0.27:20148 - R:/65.21.122.36:52134], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@16b3b784, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@5d09585
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@19afa758
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@6e352783
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7d2da8e
      processor=com.comphenix.protocol.injector.NetworkProcessor@64cc6fd8
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 19, widx: 19, cap: 19)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@7d9421da
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Paper-138 (MC: 1.19.2)

[09:56:44 INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@1633127d.
[09:56:44 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

**Comment by Gregoryxnmasd** [comment]
+1

**Comment by hehe1005566889** [comment]
+1
