### ISSUE TITLE
acc error in combo with protocollib

### ISSUE THREAD

**Issue by mechoriet** [dmulloy2/ProtocolLib#190]
i dunno if aac or protocollib is the issue 

Spigot 1.9 latest 2:00pm 14/4/2016 build

```
[14:34:08 WARN]: [AAC] Task #2261 for AAC v1.9.8 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:352) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:328) ~[?:?]
        at me.konsolas.aac.g.a.l.a(l.java) ~[?:?]
        at me.konsolas.aac.g.a.l.a(l.java) ~[?:?]
        at me.konsolas.aac.i.k.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.i.l.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.2-R0.1-20160414.114405-195.jar:git-Spigot-5a40365-f631379]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2-R0.1-20160414.114405-195.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.2-R0.1-20160414.114405-195.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2-R0.1-20160414.114405-195.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2-R0.1-20160414.114405-195.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2-R0.1-20160414.114405-195.jar:git-Spigot-5a40365-f631379]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
```

protocol dump:
https://paste.projectdev.org/irukiqoyuy.sm

is this aac fault cuz 1.9 or is this protocollib related?

if fixable Thanks Allready

if not also Thanks for taking a look :+1:

**Comment by games647** [comment]
I think it's plugin related, because according to the plugin page the plugin is only compatible with 1.8. 

>AAC 2.0.x for MC 1.9 is experimental.

>1.9 patch coming soon

I don't know which packet AAC is modifying here, but I assume the protocol definition of this packet changed and therefore there is no field at the requested position.

**Comment by dmulloy2** [comment]
Issues involving FieldAccessExceptions are _usually_ plugin-specific. The plugin is trying to access a field that doesn't exist.
