### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by REDKING-11** [dmulloy2/ProtocolLib#1906]
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/submitData/bukkit
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at com.comphenix.protocol.metrics.Metrics.sendData(Metrics.java:306) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.metrics.Metrics.lambda$submitData$0(Metrics.java:262) ~[ProtocolLib.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TheKrafter** [comment]
this isn't an error with ProtocolLib, rather bstats is receiving too many requests. (this is seen where your log says `Server returned HTTP response code: 429`)
Please check online before posting errors. This documentation from mozilla tells you about the 429 http response code:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
