### ISSUE TITLE
[ProtocolLib] INTERNAL [ERROR]: Unable to intercept a read client packet

### ISSUE THREAD

**Issue by rjscdev** [dmulloy2/ProtocolLib#1909]
this is what i get on the console and it says that i need to report this and it sends it in a loop and is quite annoying.
```java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
14.09 06:36:28 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
14.09 06:36:28 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
14.09 06:36:28 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
14.09 06:36:28 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
14.09 06:36:28 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
14.09 06:36:28 [Server] [INFO] at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
14.09 06:36:28 [Server] [INFO] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
14.09 06:36:28 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
14.09 06:36:28 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
14.09 06:36:28 [Server] [INFO] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
14.09 06:36:28 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:831)
14.09 06:36:28 [Server] [INFO] Dump:
14.09 06:36:28 [Server] [INFO] Parameters: 
14.09 06:36:28 [Server] [INFO] io.netty.buffer.PooledUnsafeDirectByteBuf@62817d04[
14.09 06:36:28 [Server] [INFO] memoryAddress=139948221298608
14.09 06:36:28 [Server] [INFO] recyclerHandle=io.netty.util.Recycler$DefaultHandle@71283cb0
14.09 06:36:28 [Server] [INFO] chunk=Chunk(45543f57: 1%, 40960/4194304)
14.09 06:36:28 [Server] [INFO] handle=1125929971613696
14.09 06:36:28 [Server] [INFO] memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
14.09 06:36:28 [Server] [INFO] offset=16384
14.09 06:36:28 [Server] [INFO] length=1
14.09 06:36:28 [Server] [INFO] maxLength=16
14.09 06:36:28 [Server] [INFO] cache=io.netty.buffer.PoolThreadCache@32fe547e
14.09 06:36:28 [Server] [INFO] tmpNioBuf=<null>
14.09 06:36:28 [Server] [INFO] allocator=PooledByteBufAllocator(directByDefault: true)
14.09 06:36:28 [Server] [INFO] refCnt=2
14.09 06:36:28 [Server] [INFO] readerIndex=1
14.09 06:36:28 [Server] [INFO] writerIndex=1
14.09 06:36:28 [Server] [INFO] markedReaderIndex=0
14.09 06:36:28 [Server] [INFO] markedWriterIndex=0
14.09 06:36:28 [Server] [INFO] maxCapacity=2147483647
14.09 06:36:28 [Server] [INFO] ]
14.09 06:36:28 [Server] [INFO] manager:
14.09 06:36:28 [Server] [INFO] com.comphenix.protocol.injector.PacketFilterManager@a9ee965[
14.09 06:36:28 [Server] [INFO] unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@52dbbbd1
14.09 06:36:28 [Server] [INFO] packetListeners=[com.r4g3baby.simplescore.scoreboard.listeners.PacketListener@5780ad34, PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]]]
14.09 06:36:28 [Server] [INFO] packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@4285c324
14.09 06:36:28 [Server] [INFO] playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6827438a
14.09 06:36:28 [Server] [INFO] inputBufferedPackets=[]
14.09 06:36:28 [Server] [INFO] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@158f4a2a
14.09 06:36:28 [Server] [INFO] sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1a056e79
14.09 06:36:28 [Server] [INFO] hasClosed=false
14.09 06:36:28 [Server] [INFO] classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
14.09 06:36:28 [Server] [INFO] reporter=com.comphenix.protocol.ProtocolLib$1@76f512fe
14.09 06:36:28 [Server] [INFO] server=CraftServer{serverName=Paper,serverVersion=git-Paper-"ef0e5a6",minecraftVersion=1.19.2}
14.09 06:36:28 [Server] [INFO] library=ProtocolLib v4.8.0
14.09 06:36:28 [Server] [INFO] asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4b2de40a
14.09 06:36:28 [Server] [INFO] knowsServerPackets=true
14.09 06:36:28 [Server] [INFO] knowsClientPackets=true
14.09 06:36:28 [Server] [INFO] phaseLoginCount=0
14.09 06:36:28 [Server] [INFO] phasePlayingCount=4
14.09 06:36:28 [Server] [INFO] packetCreation=false
14.09 06:36:28 [Server] [INFO] nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@450346a5
14.09 06:36:28 [Server] [INFO] pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@6eaf6408
14.09 06:36:28 [Server] [INFO] hasRecycleDistance=true
14.09 06:36:28 [Server] [INFO] minecraftVersion=(MC: 1.19.2)
14.09 06:36:28 [Server] [INFO] debug=false
14.09 06:36:28 [Server] [INFO] ]
14.09 06:36:28 [Server] [INFO] Sender:
14.09 06:36:28 [Server] [INFO] com.comphenix.protocol.injector.netty.ChannelInjector@56aa8e54[
14.09 06:36:28 [Server] [INFO] decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
14.09 06:36:28 [Server] [INFO] encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
14.09 06:36:28 [Server] [INFO] factory=com.comphenix.protocol.injector.netty.InjectionFactory@389554e
14.09 06:36:28 [Server] [INFO] player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@40fdc9f5
14.09 06:36:28 [Server] [INFO] updated=<null>
14.09 06:36:28 [Server] [INFO] playerName=<null>
14.09 06:36:28 [Server] [INFO] playerConnection=<null>
14.09 06:36:33 [Server] [INFO] networkManager=net.minecraft.network.NetworkManager@5b06b580
14.09 06:36:33 [Server] [INFO] originalChannel=[id: 0x844c9800, L:/172.17.0.17:25581 - R:/15.235.80.143:53584]
14.09 06:36:33 [Server] [INFO] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@5b06b580, previous=[id: 0x844c9800, L:/172.17.0.17:25581 - R:/15.235.80.143:53584], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@35151913, previousLoaded=true, currentSet=true, forceAccess=true]
14.09 06:36:33 [Server] [INFO] packetMarker={}
14.09 06:36:33 [Server] [INFO] currentEvent=<null>
14.09 06:36:33 [Server] [INFO] finalEvent=<null>
14.09 06:36:33 [Server] [INFO] unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@1b09dc25
14.09 06:36:33 [Server] [INFO] vanillaDecoder=net.minecraft.network.PacketDecoder@754dc071
14.09 06:36:33 [Server] [INFO] vanillaEncoder=net.minecraft.network.PacketEncoder@3d0634b1
14.09 06:36:33 [Server] [INFO] finishQueue=[]
14.09 06:36:33 [Server] [INFO] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@450346a5
14.09 06:36:33 [Server] [INFO] processor=com.comphenix.protocol.injector.NetworkProcessor@757b774a
14.09 06:36:33 [Server] [INFO] injected=true
14.09 06:36:33 [Server] [INFO] closed=false
14.09 06:36:33 [Server] [INFO] cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
14.09 06:36:33 [Server] [INFO] cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@796b8b6d
14.09 06:36:33 [Server] [INFO] singleDecode=false
14.09 06:36:33 [Server] [INFO] first=true
14.09 06:36:33 [Server] [INFO] firedChannelRead=true
14.09 06:36:33 [Server] [INFO] selfFiredChannelRead=true
14.09 06:36:33 [Server] [INFO] decodeState=1
14.09 06:36:33 [Server] [INFO] discardAfterReads=16
14.09 06:36:33 [Server] [INFO] numReads=0
14.09 06:36:33 [Server] [INFO] added=true
14.09 06:36:33 [Server] [INFO] ]
14.09 06:36:33 [Server] [INFO] Version:
14.09 06:36:33 [Server] [INFO] ProtocolLib v4.8.0
14.09 06:36:33 [Server] [INFO] Java Version:
14.09 06:36:33 [Server] Startup17
14.09 06:36:33 [Server] [INFO] Server:
14.09 06:36:33 [Server] [INFO] git-Paper-"ef0e5a6" (MC: 1.19.2)```

**Comment by XxRafaeloxX** [comment]
Same problem
