### ISSUE TITLE
Slimefun (Galactifun) / PaperMC issue?!

### ISSUE THREAD

**Issue by C1rm0ska** [dmulloy2/ProtocolLib#1913]
I get errors like this everytime I open my minecraft server.

[11:30:26] [Worker-Main-3/ERROR]: Failed to schedule load callback for chunk [11, 5]
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:51) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1294) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.2.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1275) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
Caused by: java.lang.NullPointerException: Addon is not enabled!
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at io.github.addoncommunity.galactifun.infinitylib.core.AbstractAddon.instance(AbstractAddon.java:307) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at io.github.addoncommunity.galactifun.infinitylib.common.Scheduler.run(Scheduler.java:21) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at io.github.addoncommunity.galactifun.api.worlds.populators.relics.FallenSatellitePopulator.setSlimefunBlock(FallenSatellitePopulator.java:49) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at io.github.addoncommunity.galactifun.api.worlds.populators.relics.FallenSatellitePopulator.populate(FallenSatellitePopulator.java:33) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:668) ~[paper-1.19.2.jar:git-Paper-153]
	at org.bukkit.craftbukkit.v1_19_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:287) ~[paper-1.19.2.jar:git-Paper-153]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.19.2.jar:git-Paper-153]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:275) ~[paper-1.19.2.jar:git-Paper-153]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1277) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.2.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1275) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
[11:30:26] [Worker-Main-3/ERROR]: Failed to light chunk [11, 6]
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:51) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1294) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.2.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1275) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
Caused by: java.lang.NullPointerException: Addon is not enabled!
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at io.github.addoncommunity.galactifun.infinitylib.core.AbstractAddon.instance(AbstractAddon.java:307) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at io.github.addoncommunity.galactifun.infinitylib.common.Scheduler.run(Scheduler.java:21) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at io.github.addoncommunity.galactifun.api.worlds.populators.relics.FallenSatellitePopulator.setSlimefunBlock(FallenSatellitePopulator.java:49) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at io.github.addoncommunity.galactifun.api.worlds.populators.relics.FallenSatellitePopulator.populate(FallenSatellitePopulator.java:33) ~[Galactifun - DEV 70 (git c6930).jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:668) ~[paper-1.19.2.jar:git-Paper-153]
	at org.bukkit.craftbukkit.v1_19_R1.generator.CustomChunkGenerator.a(CustomChunkGenerator.java:287) ~[paper-1.19.2.jar:git-Paper-153]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.19.2.jar:git-Paper-153]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:275) ~[paper-1.19.2.jar:git-Paper-153]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1277) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.2.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1275) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more

**Comment by C1rm0ska** [comment]
And when my friends or I place a block, this warning shows up in the console.

[11:45:33 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
[11:45:33 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[11:45:33 WARN]:        at SchematicsPlus.jar//schematicplus.core.nbt.NBTStack.getTag(NBTStack.java:22)
[11:45:33 WARN]:        at SchematicsPlus.jar//schematicplus.core.gui.item.BItem.getNBTString(BItem.java:81)
[11:45:33 WARN]:        at SchematicsPlus.jar//schematicplus.core.logic.schematics.SchematicsManager.oninteraction(SchematicsManager.java:136)
[11:45:33 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor341.execute(Unknown Source)
[11:45:33 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[11:45:33 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:45:33 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:45:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[11:45:33 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[11:45:33 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:525)
[11:45:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1968)
[11:45:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[11:45:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[11:45:33 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[11:45:33 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:45:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:45:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1361)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[11:45:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1338)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1331)
[11:45:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1309)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1197)
[11:45:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[11:45:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:45:33 ERROR]: Could not pass event PlayerInteractEvent to SchematicsPlus v1.2.2
java.lang.NullPointerException: Cannot invoke "schematicplus.core.nbt.MainNBTTag.hasTag(String)" because "tag" is null
        at schematicplus.core.gui.item.BItem.getNBTString(BItem.java:82) ~[SchematicsPlus.jar:?]
        at schematicplus.core.logic.schematics.SchematicsManager.oninteraction(SchematicsManager.java:136) ~[SchematicsPlus.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor341.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-153]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:525) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1968) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-153]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-153]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
