### ISSUE TITLE
Issue on join / update check

### ISSUE THREAD

**Issue by SkyTryX** [dmulloy2/ProtocolLib#1914]
<html>
<body>

Stack Trace:
--
257 | java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
258 | at com.comphenix.protocol.ProtocolConfig.isAutoNotify(ProtocolConfig.java:244)
259 | at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:589)
260 | at com.comphenix.protocol.ProtocolLib.access$600(ProtocolLib.java:59)
261 | at com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:555)
262 | at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
263 | at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
264 | at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
265 | at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
266 | at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
267 | at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
268 | at java.lang.Thread.run(Thread.java:750)
269 | Dump:
270 | manager:
271 | com.comphenix.protocol.injector.PacketFilterManager@1be70ccf[
272 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@145cb2dc
273 | packetListeners=[PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[FLYING[class=PacketPlayInFlying, id=254]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IcePractice, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_EVENT[class=PacketPlayOutWorldEvent, id=35]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IcePractice, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=36]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[FLYING[class=PacketPlayInFlying, id=254]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IcePractice, sending=ListeningWhitelist[priority=NORMAL, packets=[BED[class=PacketPlayOutBed, id=251], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], COLLECT[class=PacketPlayOutCollect, id=97], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], SPAWN_ENTITY_PAINTING[class=PacketPlayOutSpawnEntityPainting, id=3], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=101], ANIMATION[class=PacketPlayOutAnimation, id=6], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=9], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=78], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=80]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
274 | packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5ba70fa0
275 | playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3546ac05
276 | inputBufferedPackets=[]
277 | recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@16e44f16
278 | sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@675fc544
279 | hasClosed=false
280 | classLoader=org.bukkit.plugin.java.PluginClassLoader@2f5c3e8
281 | reporter=com.comphenix.protocol.ProtocolLib$1@4660c00
282 | server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-445,minecraftVersion=1.8.8}
283 | library=ProtocolLib v4.8.0
284 | asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@30e8dd7c
285 | knowsServerPackets=true
286 | knowsClientPackets=true
287 | phaseLoginCount=0
288 | phasePlayingCount=24
289 | packetCreation=false
290 | nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6af21c50
291 | pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@61239085
292 | hasRecycleDistance=true
293 | minecraftVersion=(MC: 1.8.8)
294 | debug=false
295 | ]
296 | Sender:
297 | com.comphenix.protocol.ProtocolLib@4e1db9f9[
298 | statistics=<null>
299 | backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6bb38282
300 | packetTask=2
301 | tickCounter=20
302 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@145cb2dc
303 | configExpectedMod=1
304 | updater=com.comphenix.protocol.updater.SpigotUpdater@11d91338
305 | redirectHandler=com.comphenix.protocol.ProtocolLib$2@6c831e3e
306 | commandProtocol=com.comphenix.protocol.CommandProtocol@4ff2b026
307 | commandPacket=com.comphenix.protocol.CommandPacket@38229cc8
308 | commandFilter=com.comphenix.protocol.CommandFilter@613b1827
309 | packetLogging=com.comphenix.protocol.PacketLogging@153d98d0
310 | skipDisable=false
311 | isEnabled=true
312 | loader=org.bukkit.plugin.java.JavaPluginLoader@4f1479d1
313 | server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-445,minecraftVersion=1.8.8}
314 | file=plugins/ProtocolLib.jar
315 | description=org.bukkit.plugin.PluginDescriptionFile@637c7827
316 | dataFolder=plugins/ProtocolLib
317 | classLoader=org.bukkit.plugin.java.PluginClassLoader@2f5c3e8
318 | naggable=true
319 | ebean=<null>
320 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
321 | configFile=plugins/ProtocolLib/config.yml
322 | logger=org.bukkit.plugin.PluginLogger@233d46d0
323 | ]
324 | Version:
325 | ProtocolLib v4.8.0
326 | Java Version:
327 | 1.8.0_345
328 | Server:
329 | git-PaperSpigot-445 (MC: 1.8.8)

</body>
</html>Stack Trace:
  java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
  	at com.comphenix.protocol.ProtocolConfig.isAutoNotify(ProtocolConfig.java:244)
  	at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:589)
  	at com.comphenix.protocol.ProtocolLib.access$600(ProtocolLib.java:59)
  	at com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:555)
  	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
  	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
  	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
  	at java.lang.Thread.run(Thread.java:750)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1be70ccf[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@145cb2dc
        packetListeners=[PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[FLYING[class=PacketPlayInFlying, id=254]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IcePractice, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_EVENT[class=PacketPlayOutWorldEvent, id=35]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IcePractice, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=36]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[FLYING[class=PacketPlayInFlying, id=254]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ThotPatrol, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_ACTION[class=PacketPlayInEntityAction, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=IcePractice, sending=ListeningWhitelist[priority=NORMAL, packets=[BED[class=PacketPlayOutBed, id=251], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], COLLECT[class=PacketPlayOutCollect, id=97], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], SPAWN_ENTITY_PAINTING[class=PacketPlayOutSpawnEntityPainting, id=3], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=101], ANIMATION[class=PacketPlayOutAnimation, id=6], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=9], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=78], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=80]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5ba70fa0
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3546ac05
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@16e44f16
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@675fc544
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2f5c3e8
        reporter=com.comphenix.protocol.ProtocolLib$1@4660c00
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-445,minecraftVersion=1.8.8}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@30e8dd7c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=24
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6af21c50
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@61239085
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@4e1db9f9[
      statistics=<null>
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6bb38[282](https://aternos.org/log/#L282)
      packetTask=2
      tickCounter=20
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@145cb2dc
      configExpectedMod=1
      updater=com.comphenix.protocol.updater.SpigotUpdater@11d91338
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@6c831e3e
      commandProtocol=com.comphenix.protocol.CommandProtocol@4ff2b026
      commandPacket=com.comphenix.protocol.CommandPacket@38229cc8
      commandFilter=com.comphenix.protocol.CommandFilter@613b1827
      packetLogging=com.comphenix.protocol.PacketLogging@153d98d0
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@4f1479d1
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-445,minecraftVersion=1.8.8}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@637c7827
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2f5c3e8
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@233d46d0
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    1.8.0_345
  Server:
    git-PaperSpigot-445 (MC: 1.8.8)

**Comment by SkyTryX** [comment]
Alright 👍🏻 
Thanks for the help!
