### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.Packet

### ISSUE THREAD

**Issue by cherylbourke** [dmulloy2/ProtocolLib#1925]
- >....
26/09/2022 [15:16:05 WARN: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 512!]
>....
26/09/2022 [15:16:05]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib
.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@5714346f.
26/09/2022 [15:16:05 ERROR:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.]
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
26/09/2022   java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.Packet
LoginInStart
    at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
    at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@146dab91[
 memoryAddress=140617497760128
 recyclerHandle=io.netty.util.Recycler$DefaultHandle@651633bb
 chunk=Chunk(5717c19e: 27%, 1130496/4194304)
 handle=3377729785298944
 memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
 offset=49152
 length=26
 maxLength=32
26/09/2022  cache=io.netty.buffer.PoolThreadCache@3815f8c9
 tmpNioBuf=<null>
 allocator=PooledByteBufAllocator(directByDefault: true)
 refCnt=2
 readerIndex=26
 writerIndex=26
 markedReaderIndex=0
 markedWriterIndex=0
 maxCapacity=2147483647
    ]
    manager:
 com.comphenix.protocol.injector.PacketFilterManager@65a87bfa[
   unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1efef5b1
   packetListeners=[PacketAdapter[plugin=KenshinsHideAndSeek, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43], RE
L_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=9], ENTITY_EFFECT[class=PacketPlayOutEntityEffe
ct, id=101], ANIMATION[class=PacketPlayOutAnimation, id=6], SPAWN_ENTITY_PAINTING[PLAY, SERVER, 3, classNames: [net.minecraft.network.protocol.game.PacketPlayOutSpawnEn
tityPainting, net.minecraft.network.protocol.game.ClientboundSpawnEntityPaintingPacket, net.minecraft.network.play.server.SPacketSpawnPainting] (unregistered)], NAMED_E
NTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], COLLECT[class=PacketPlayOutCollect, id=97], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperience
Orb, id=1], SPAWN_ENTITY_LIVING[PLAY, SERVER, 2, classNames: [net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityLiving, net.minecraft.network.protocol.game.Cl
ientboundSpawnEntityLivingPacket, net.minecraft.network.play.server.SPacketSpawnMob] (unregistered)], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], SPAWN_E
NTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27], 
REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], ENTITY_EQUIPMENT[class=PacketPlayOutEntit
yEquipment, id=80], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=78]], gamephase=PLAYING, options=[]], r
eceiving=EMPTY_WHITELIST], PacketAdapter[plugin=KenshinsHideAndSeek, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=Pa
cketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]]]
   packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3caa5e4
   playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4442316c
   inputBufferedPackets=[]
   recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@350c2f51
   sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@483b7719
   hasClosed=false
   classLoader=PluginClassLoader-plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar-
   reporter=com.comphenix.protocol.ProtocolLib$1@644bb7e2
   server=CraftServer-serverName=Paper,serverVersion=git-Paper-161,minecraftVersion=1.19.2-
   library=ProtocolLib v4.8.0
   asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@14291f08
   knowsServerPackets=true
   knowsClientPackets=true
   phaseLoginCount=0
   phasePlayingCount=2
   packetCreation=false
   nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3547d62f
   pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5832dd32
   hasRecycleDistance=true
   minecraftVersion=(MC: 1.19.2)
   debug=false
 ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@5714346f[
 decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.
Exception
 encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lan
g.Exception
 factory=com.comphenix.protocol.injector.netty.InjectionFactory@1831e0fc
 player=CraftPlayer-name=bourkie-
 updated=<null>
 playerName=bourkie
 playerConnection=<null>
 networkManager=net.minecraft.network.NetworkManager@2b6249f4
 originalChannel=[id: 0x4c1306ed, L:/117.120.12.155:25567 - R:/58.96.14.8:1762]
 channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.netwo
rk.NetworkManager@2b6249f4, previous=[id: 0x4c1306ed, L:/117.120.12.155:25567 - R:/58.96.14.8:1762], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@f15
c8f, previousLoaded=true, currentSet=true, forceAccess=true]
 packetMarker=--
 currentEvent=<null>
 finalEvent=<null>
 unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@7630a7b2
 vanillaDecoder=net.minecraft.network.PacketDecoder@4fa46d69
 vanillaEncoder=net.minecraft.network.PacketEncoder@3e673489
 finishQueue=[]
 channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@3547d62f
 processor=com.comphenix.protocol.injector.NetworkProcessor@47062ef4
 injected=true
 closed=false
 cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
 cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4fc07b19
 singleDecode=false
 first=true
 firedChannelRead=false
 selfFiredChannelRead=true
 decodeState=1
 discardAfterReads=16
 numReads=0
 added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4
  Server:
    git-Paper-161 (MC: 1.19.2)
 ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by Aseeef** [comment]
Please use protocol lib 5.0 on 1.19+. This is on the protocol lib spigot home page.
![image](https://user-images.githubusercontent.com/74121396/192523213-3ff1ab26-9b9c-4347-bae5-379037ebb540.png)
