### ISSUE TITLE
important plugin error

### ISSUE THREAD

**Issue by rafi67000** [dmulloy2/ProtocolLib#1930]
- [x] This issue is not solved in a development build

**Describe the bug**
when I'm trying to start server protocollib can't load
latest paper 1.8.8 445(build)

EDIT: I've installed protocollib 5.0 on my bedwars server with swm and everything works so I don't know what's wrong....
4.8.0 works but 5.0 don't (I need 5.0)
ANOTHER EDIT: I changed version to 5.0.0-SNAPSHOT-b556 and now works

**To Reproduce**
1. install 1.8.8 server (this problem  occurs on differents fork's and clear paper too)
2. install protocollib 5.0
3. start server
enjoy bug 😛 

**Expected behavior**
protocollib will load

**Screenshots**
nah

**Version Info**
I can't cause plugin can't load

**Additional context**
[15:54:59] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b600
[15:54:59] [Server thread/WARN]: java.lang.IllegalStateException: Unable to access field private final org.bukkit.craftbukkit.v1_8_R3.CraftWorld net.minecraft.server.v1_8_R3.World.world
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:103)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:56)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.wrappers.BukkitConverters.<clinit>(BukkitConverters.java:126)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.instances.MinecraftGenerator.<clinit>(MinecraftGenerator.java:30)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.instances.DefaultInstances.<clinit>(DefaultInstances.java:40)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.getDefaultGenerator(StructureModifier.java:129)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.<clinit>(StructureModifier.java:52)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:115)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:283)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:314)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:117)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120)
[15:54:59] [Server thread/WARN]: 	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175)
[15:54:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[15:54:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[15:54:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[15:54:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[15:54:59] [Server thread/ERROR]: null initializing ProtocolLib v5.0.0-SNAPSHOT-b600 (Is it up to date?)
java.lang.NullPointerException: null
	at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:394) ~[?:?]
	at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63) ~[?:?]
	at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87) ~[?:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:186) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by Wackgamer** [comment]
me too!

**Comment by isaaclepes** [comment]
I found the answer on the Spigot page, it was easy to overlook.

Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19

**Comment by Wackgamer** [comment]
The build #600 are you trying to say?

**Comment by isaaclepes** [comment]
Yes, switching to build #600 stopped these errors on my servers.

**Comment by Wackgamer** [comment]
> 

It doesn't works for me

**Comment by isaaclepes** [comment]
That's unfortunate. I guess I lucked out with it.

¯\_(ツ)_/¯

**Comment by derklaro** [comment]
@rafi67000 which Java version + vendor are you using? (Please provide the output of `java -version`)

**Comment by derklaro** [comment]
And were there any additional errors while starting the server?

**Comment by derklaro** [comment]
Let me test on openj9, might be that there are conflicts with our reflection handling there.

**Comment by derklaro** [comment]
> And were there any additional errors while starting the server?

Were there?

**Comment by Wackgamer** [comment]
so.. it's jre 18 compatible with minecraft 1.8.8?

**Comment by Wackgamer** [comment]
https://prnt.sc/VxgPCW-ZLVS-
check this part in your pastebin

**Comment by Wackgamer** [comment]
I have recently tried with the recent compilation #602 and it doesn't work.

**Comment by pabloalba16** [comment]
> bro I had problem with #600 so I went back to b556 and now works....

Are you still using build 556? I have the same issue and build 556 can't be downloaded anymore
