### ISSUE TITLE
unable to intercept read client packet

### ISSUE THREAD

**Issue by pizzaNugget** [dmulloy2/ProtocolLib#1934]
tried installing a few plugins that required ProtocolLib to run on a server hosted on aternos.org
the log kept spamming that it couldnt intercept the packet(s).
the server has online-mode=false
can it not run on 1.19.2?

Stack trace:

java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
  	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
  	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
  	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
  	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
  	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@3a2c4cb1[
      memoryAddress=140258532616784
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1c8f28bd
      chunk=Chunk(67f17971: 1%, 8192/4194304)
      handle=30064771072
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=0
      length=18
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@e3eea15
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=18
      writerIndex=18
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5f56abff[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@26418c42
        packetListeners=[PacketAdapter[plugin=Orebfuscator, sending=ListeningWhitelist[priority=NORMAL, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CheatGuard, sending=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ABILITIES[class=PacketPlayInAbilities, id=25], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], HELD_ITEM_SLOT[class=PacketPlayOutHeldItemSlot, id=72], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], POSITION[class=PacketPlayOutPosition, id=56], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], TRANSACTION[PLAY, SERVER, 246, classNames: [net.minecraft.network.protocol.game.PacketPlayOutTransaction, net.minecraft.network.protocol.game.ClientboundTransactionPacket, net.minecraft.network.play.server.SPacketConfirmTransaction] (unregistered)], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], ABILITIES[class=ClientboundPlayerChatHeaderPacket, id=50], OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=46], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], CHAT[class=PacketPlayInChat, id=3], FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], TRANSACTION[PLAY, CLIENT, 255, classNames: [net.minecraft.network.protocol.game.PacketPlayInTransaction, net.minecraft.network.protocol.game.ServerboundTransactionPacket, net.minecraft.network.play.client.CPacketConfirmTransaction] (unregistered)], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], SETTINGS[class=PacketPlayInSettings, id=5], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=19], POSITION[class=PacketPlayInPosition, id=17], LOOK[class=PacketPlayInLook, id=19], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ABILITIES[class=PacketPlayInAbilities, id=25], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], HELD_ITEM_SLOT[class=PacketPlayOutHeldItemSlot, id=72], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], POSITION[class=PacketPlayOutPosition, id=56], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], TRANSACTION[PLAY, SERVER, 246, classNames: [net.minecraft.network.protocol.game.PacketPlayOutTransaction, net.minecraft.network.protocol.game.ClientboundTransactionPacket, net.minecraft.network.play.server.SPacketConfirmTransaction] (unregistered)], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], ABILITIES[class=ClientboundPlayerChatHeaderPacket, id=50], OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=46], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], CHAT[class=PacketPlayInChat, id=3], FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], TRANSACTION[PLAY, CLIENT, 255, classNames: [net.minecraft.network.protocol.game.PacketPlayInTransaction, net.minecraft.network.protocol.game.ServerboundTransactionPacket, net.minecraft.network.play.client.CPacketConfirmTransaction] (unregistered)], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], SETTINGS[class=PacketPlayInSettings, id=5], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=19], POSITION[class=PacketPlayInPosition, id=17], LOOK[class=PacketPlayInLook, id=19], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], com.comphenix.protocol.async.NullPacketListener@1884af7d]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@b76dc63
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3bf6e30c
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5115aede
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7b1c1b22
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@4ad630af
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-191,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2d17dc95
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5f347b94
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@53edb251
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@64310697[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@4d7405d5
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@211da752
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@25db9576
      originalChannel=org.geysermc.geyser.network.netty.ChannelWrapper@4bb31e2a
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@25db9576, previous=org.geysermc.geyser.network.netty.ChannelWrapper@4bb31e2a, current=com.comphenix.protocol.injector.netty.ChannelInjector$3@1176347b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@56c3dd4d
      vanillaDecoder=net.minecraft.network.PacketDecoder@76b6fe02
      vanillaEncoder=net.minecraft.network.PacketEncoder@422e7a42
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5f347b94
      processor=com.comphenix.protocol.injector.NetworkProcessor@d9acce8
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 18, widx: 18, cap: 18)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4c1d65b7
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    git-Paper-191 (MC: 1.19.2)

**Comment by isaaclepes** [comment]
I also have this issue.

**Comment by isaaclepes** [comment]
I found the answer on the Spigot page, it was easy to overlook.

Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for Minecraft 1.19
