### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by BlackNigel7** [dmulloy2/ProtocolLib#1935]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib-LATEST.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib-LATEST.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib-LATEST.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib-LATEST.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib-LATEST.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2d4e670e[
      memoryAddress=140370109227024
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@2e5018f1
      chunk=Chunk(7f6eff9b: 29%, 1196032/4194304)
      handle=2251829878456320
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=32768
      length=3
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@571f247c
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=3
      writerIndex=3
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@651fe0a4[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6d0559bb
        packetListeners=[PacketAdapter[plugin=Matrix, sending=ListeningWhitelist[priority=HIGH, packets=[POSITION[class=PacketPlayOutPosition, id=56], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ABILITIES[class=PacketPlayInAbilities, id=25], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=63], POSITION[class=PacketPlayInPosition, id=17], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], ANIMATION[class=PacketPlayOutAnimation, id=6], BLOCK_CHANGE[class=ClientboundChatPreviewPacket, id=12], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], WINDOW_DATA[class=ClientboundCustomChatCompletionsPacket, id=21], CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=19], EXPLOSION[class=PacketPlayOutExplosion, id=28], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=93], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], USE_ENTITY[class=PacketPlayInUseEntity, id=13], B_EDIT[class=PacketPlayInBEdit, id=11], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], SETTINGS[class=PacketPlayInSettings, id=5], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=46], CHAT[class=PacketPlayInChat, id=3], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=HIGH, packets=[POSITION[class=PacketPlayOutPosition, id=56], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ABILITIES[class=PacketPlayInAbilities, id=25], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=63], POSITION[class=PacketPlayInPosition, id=17], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], ANIMATION[class=PacketPlayOutAnimation, id=6], BLOCK_CHANGE[class=ClientboundChatPreviewPacket, id=12], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], WINDOW_DATA[class=ClientboundCustomChatCompletionsPacket, id=21], CLOSE_WINDOW[class=PacketPlayOutCloseWindow, id=19], EXPLOSION[class=PacketPlayOutExplosion, id=28], NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=93], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], USE_ENTITY[class=PacketPlayInUseEntity, id=13], B_EDIT[class=PacketPlayInBEdit, id=11], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], SETTINGS[class=PacketPlayInSettings, id=5], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], OPEN_WINDOW[class=PacketPlayOutOpenWindow, id=46], CHAT[class=PacketPlayInChat, id=3], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0]], gamephase=PLAYING, options=[ASYNC]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@65f04bf
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7f090a06
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6589df83
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@22868a08
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib-LATEST.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5c82081b
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-194,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4032df8e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=3
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4405820d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@46d394c
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@48430994[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@2bf830
      player=CraftPlayer{name=NabNab}
      updated=<null>
      playerName=NabNab
      playerConnection=net.minecraft.server.network.PlayerConnection@4c2c2995
      networkManager=net.minecraft.network.NetworkManager@207ebdf4
      originalChannel=[id: 0x4b9e053e, L:/172.18.0.28:10585 - R:/51.182.23.104:51043]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@207ebdf4, previous=[id: 0x4b9e053e, L:/172.18.0.28:10585 - R:/51.182.23.104:51043], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@7df9d33e, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@2da66abc
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@78e2f3e1
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@2a4926f7
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4405820d
      processor=com.comphenix.protocol.injector.NetworkProcessor@7771ab6
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 3)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@50c04209
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17
  Server:
    git-Paper-194 (MC: 1.19.2)

**Comment by LiteCat0905** [comment]
同样遇到了 （

**Comment by kappa243** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/issues/1860.
Please use the latest [dev version](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) that supports 1.19.
