### ISSUE TITLE
HELP PLS ERROR:

### ISSUE THREAD

**Issue by MrYsquoTR** [dmulloy2/ProtocolLib#1952]
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib 4.8.0.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib 4.8.0.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib 4.8.0.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib 4.8.0.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib 4.8.0.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@62a60734[
      memoryAddress=2017917259840
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@742d6750
      chunk=Chunk(60cf7af1: 1%, 32768/4194304)
      handle=1688879925035008
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=24576
      length=9
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@168f9a99
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=9
      writerIndex=9
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@767d2ce0[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1c4c3be4
        packetListeners=[PacketAdapter[plugin=AdvancedNMotd, sending=ListeningWhitelist[priority=NORMAL, packets=[SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedNMotd, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperiorSkyblock2, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@35376065
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2e887934
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@318d4a29
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4ce3c4e7
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib 4.8.0.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@4259a156
        server=CraftServer{serverName=Pufferfish,serverVersion=git-Pufferfish-34,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@74f2ea35
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4c0430d2
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4c8564be
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2101c6d7[
      decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@224613f3
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@d5e5e12
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@55284917
      originalChannel=[id: 0x7d4bcdde, L:/192.168.1.100:25565 - R:/192.168.1.100:53620]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@55284917, previous=[id: 0x7d4bcdde, L:/192.168.1.100:25565 - R:/192.168.1.100:53620], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@877bc5b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@dd9da8
      vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@357d6c8c
      vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@4f5dac3a
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4c0430d2
      processor=com.comphenix.protocol.injector.NetworkProcessor@22f1fd61
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@7c36ecbf
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    git-Pufferfish-34 (MC: 1.19.2)

**Comment by kappa243** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/issues/1860.
Please use the latest [dev version](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) that supports 1.19.
