### ISSUE TITLE
I got error, pls help 

### ISSUE THREAD

**Issue by Pandziorak** [dmulloy2/ProtocolLib#1955]
i got this error: 

[18:07:52 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 32768!
[18:07:52 INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@2f56cd48.
[18:07:52 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@3e526650[
      memoryAddress=140343358116320
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@168b30a8
      chunk=Chunk(399c6fe2: 27%, 1130496/4194304)
      handle=562980018192385
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8224
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@3a4d047a
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@220ade99[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@664e0dc1
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@607ae268
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@18e6790a
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6cec8299
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7a5aaac0
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@4d847e41
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-97,minecraftVersion=1.19.1}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@660170d2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@42a00fb3
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@22c7d6f0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.1)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2f56cd48[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@cb174d8
      player=CraftPlayer{name=kacper2137ezzz}
      updated=<null>
      playerName=kacper2137ezzz
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@2867e291
      originalChannel=[id: 0x8b8e8024, L:/142.132.254.44:27653 - R:/46.77.151.114:22558]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@2867e291, previous=[id: 0x8b8e8024, L:/142.132.254.44:27653 - R:/46.77.151.114:22558], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@4a6b0f46, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@534eb7ce
      vanillaDecoder=net.minecraft.network.PacketDecoder@442aa45c
      vanillaEncoder=net.minecraft.network.PacketEncoder@125f36cb
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@42a00fb3
      processor=com.comphenix.protocol.injector.NetworkProcessor@268a2dfb
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@20f5a4bb
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    git-Paper-97 (MC: 1.19.1)
    
    and its get spamming at console

mc: 1.19.1
v: 4.8.0

+ 

i cant delete plugin from plugin folder

**Comment by kappa243** [comment]
Fixed in https://github.com/dmulloy2/ProtocolLib/issues/1860.
Please use the latest [dev version](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) that supports 1.19.
