### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by iammb1** [dmulloy2/ProtocolLib#1958]
[12:12:34] [Netty Server IO #2/WARN] [Minecraft/]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 128!
[12:12:34] [Netty Server IO #2/INFO] [/]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@4225ed06.
[12:12:34] [Netty Server IO #2/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
  	at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
  	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.reflect.InvocationTargetException
  	at jdk.internal.reflect.GeneratedConstructorAccessor95.newInstance(Unknown Source)
  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
  	... 39 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInFlying$PacketPlayInPosition
  	at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPlayerPacket_PositionPacket$java_lang_Object.<init>(Unknown Source)
  	... 44 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@c12376[
      memoryAddress=2033716772928
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@7bc92c36
      chunk=Chunk(65b34262: 3%, 401408/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@695cbdb9
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2dca29be[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2177f8cb
        packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@300e8887, PacketAdapter[plugin=RoyaleEconomy, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], com.guillaumevdn.gcore.lib.legacy_npc.NPCPacketListener@5930d7aa, PacketAdapter[plugin=SCore, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=36]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@63aaaea6, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@730d6990, PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@17fa5304, PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3e2c79c3
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@424bc46b
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3e309245
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@209f94e8
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@3957506
        reporter=com.comphenix.protocol.ProtocolLib$1@7d200359
        server=CraftServer{serverName=Mohist,serverVersion=1.16.5-1085,minecraftVersion=1.16.5}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5bccecdf
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=12
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2be04e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@47984f1a
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@4225ed06[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@4bf0f257
      player=CraftPlayer{name=IAMMB_}
      updated=CraftPlayer{name=IAMMB_}
      playerName=IAMMB_
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@2d8edb42
      originalChannel=[id: 0xd4d2d143, L:/25.39.68.224:25567 - R:/25.50.122.8:49714]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@2d8edb42, previous=[id: 0xd4d2d143, L:/25.39.68.224:25567 - R:/25.50.122.8:49714], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2ba1a30b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@20724bff
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@4b722aa4
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@1d24a521
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2be04e
      processor=com.comphenix.protocol.injector.NetworkProcessor@9246d5e
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@53d951d4
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    1.16.5-1085 (MC: 1.16.5)

**Comment by dedmuus** [comment]
what did you do?
