### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet

### ISSUE THREAD

**Issue by MikeNolann** [dmulloy2/ProtocolLib#1971]
- [ ] This issue is not solved in a development build

**Describe the bug**
[17:10:29 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@474bf121[
      memoryAddress=140301415049968
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6dc5b0f2
      chunk=Chunk(299be2f8: 1%, 32768/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=1
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@1ab85185
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7a1665b5[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1ab0927d
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5336b83c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@43a38458
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@ad16a54
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@14ec2209
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@727d9ff0
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-263,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2ca10899
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@54c464f4
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@492ae6e9
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@263f570a[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1da1cb18
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@2a904fdf
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@3f3bb4df
      originalChannel=[id: 0x5b309792, L:/172.18.0.56:11055 - R:/65.108.199.164:5082]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@3f3bb4df, previous=[id: 0x5b309792, L:/172.18.0.56:11055 - R:/65.108.199.164:5082], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@1222c46d, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@3a649f41
      vanillaDecoder=net.minecraft.network.PacketDecoder@589b599e
      vanillaEncoder=net.minecraft.network.PacketEncoder@5c0bf307
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@54c464f4
      processor=com.comphenix.protocol.injector.NetworkProcessor@460e5790
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@b0ed0ad
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17
  Server:
    git-Paper-263 (MC: 1.19.2)

**To Reproduce**
1. Start BungeeCorde Server
2. Start The Main Server
3. Get This Error In The Console

**Expected behavior**
I Just Started The Server

**Screenshots**
I Dont Have

**Version Info**
Generated: November 7, 2022 at 5:08:28 PM UTC

PlaceholderAPI: 2.11.2

Expansions Registered:
  itemedit   [Author: emanon, Version: 1.0]
  playerkits [Author: Ajneb97, Version: 2.24.3]
  pvpmanager [Author: [ChanceSD], Version: 3.10.6]

Expansions Directory:

Server Info: 1.19.2-R0.1-SNAPSHOT/git-Paper-263 (MC: 1.19.2)
Java Version: 17

Plugin Info:
  AdvancedBan         [Version: 2.3.0]
  AdvancedPortals     [Version: 0.9.2]
  AdvancedTeleport    [Version: 5.6.4]
  Essentials          [Version: 2.19.7]
  EssentialsChat      [Version: 2.19.7]
  HolographicDisplays [Version: 3.0.0-SNAPSHOT-b205]
  ItemEdit            [Version: 2.19]
  LaggRemover         [Version: 2.0.6]
  Legendchat          [Version: 1.0]
  LuckPerms           [Version: 5.4.18]
  Multiverse-Core     [Version: 4.3.1-b861]
  NametagEdit         [Version: 4.5.11]
  PlaceholderAPI      [Version: 2.11.2]
  PlayerKits          [Version: 2.24.3]
  ProtocolLib         [Version: 4.8.0]
  PvPManager          [Version: 3.10.6]
  RHLeafDecay         [Version: 1.18_R2]
  ServersNPC          [Version: 3.9]
  SkinsRestorer       [Version: 14.1.15]
  TAB                 [Version: 3.1.4]
  Vault               [Version: 1.7.3-b131]
  WorldEdit           [Version: 7.2.12+6240-87f4ae1]
  WorldGuard          [Version: 7.0.7+216b061]
  nChat               [Version: 5.6.1]
 bin.

**Additional context**
I Just Started The Server I I Gent This Error

**Comment by rackgaming** [comment]
same 1.19

**Comment by ZhangMouQWQ** [comment]
same 1.16

**Comment by White55Tiger** [comment]
same 1.19

**Comment by luucay** [comment]
Fixed using the lastes DEV versions

**Comment by rackgaming** [comment]
I see, guess he needs to like put it somewhere better for others to see.

**Comment by Gaming-YT-Offcial** [comment]
Same issue here with my server

**Comment by YummyCoin5155** [comment]
yeah i have the same problem and the plugin seems required for me to use interactivechat which sucks! it also spams my chat and breaks interactive chat and interactivechat discordsrv addon which messes so much stuff up on my server
