### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by RidroWalt** [dmulloy2/ProtocolLib#1979]
- [Yes] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
1. Go to 'server folder'
2. Click on 'bat/sh file'
3. Scroll down to 'error'

**Screenshots**
![image](https://user-images.githubusercontent.com/96520857/201480254-4e9eb02a-e9ab-4918-bc6e-faad2b3f69c5.png)

**Version Info**
Last

`[16:57:26 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@84552c8[
      memoryAddress=2247161454848
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6353d4a9
      chunk=Chunk(153f7f87: 30%, 1228800/4194304)
      handle=24206878061887494
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=352448
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@315be0f2
      tmpNioBuf=java.nio.DirectByteBuffer[pos=352479 lim=352479 cap=4194304]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@10d8c061[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7e7546ba
        packetListeners=[PacketAdapter[plugin=ItemFixer, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PacketBookFixer, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10]], gamephase=PLAYING, options=[INTERCEPT_INPUT_BUFFER]]], PacketAdapter[plugin=FiguresFix, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=FiguresFix, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[WINDOW_CLICK[class=PacketPlayInWindowClick, id=8]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@104765f6
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@573633aa
        inputBufferedPackets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], FLYING[PLAY, CLIENT, 254, classNames: [net.minecraft.network.protocol.game.PacketPlayInFlying, net.minecraft.network.protocol.game.ServerboundFlyingPacket, net.minecraft.network.play.client.CPacketPlayer] (unregistered)], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10]]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@13b3ae5
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@55afecee
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@7eec4b78
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1839,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4015719f
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@978305e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5a337ccb
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@4c9bd543[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@76e480da
      player=CraftPlayer{name=TurtleWalter}
      updated=<null>
      playerName=TurtleWalter
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@9fd1387
      originalChannel=[id: 0x096752e1, L:/127.0.0.1:25565 - R:/127.0.0.1:50138]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@9fd1387, previous=[id: 0x096752e1, L:/127.0.0.1:25565 - R:/127.0.0.1:50138], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@5324f279, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@6f58a1d
      vanillaDecoder=net.minecraft.network.PacketDecoder@6f768a83
      vanillaEncoder=net.minecraft.network.PacketEncoder@65f3e602
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@978305e
      processor=com.comphenix.protocol.injector.NetworkProcessor@3bbfb2b6
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@60c615d0
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    git-Purpur-1839 (MC: 1.19.2)`

**Comment by s3tupw1zard** [comment]
Same issue here on Purpur ver. git-Purpur-1838

**Comment by FlyMC1** [comment]
having same issues on my server
