### ISSUE TITLE
java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.network.ServerConnectionListener.f_9703_

### ISSUE THREAD

**Issue by NickJi2019** [dmulloy2/ProtocolLib#1997]
[19:41:25 INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-b602
[19:41:25 INFO]: Error Cannot enable ProtocolLib. (java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.network.ServerConnectionListener.f_9703_) occurred in ProtocolLib v5.0.0-SNAPSHOT-b602.
[19:41:25 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.network.ServerConnectionListener.f_9703_
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:103)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.inject(NetworkManagerInjector.java:202)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:451)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:336)
        at TRANSFORMER/forge@43.1.52/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at TRANSFORMER/forge@43.1.52/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
        at TRANSFORMER/forge@43.1.52/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
        at TRANSFORMER/forge@43.1.52/org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:490)
        at TRANSFORMER/forge@43.1.52/org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:416)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:187)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:737)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3a2ee435[
        plugin=ProtocolLib v5.0.0-SNAPSHOT-b602
        server=CraftServer{serverName=Mohist,serverVersion=1.19.2-69,minecraftVersion=1.19.2}
        reporter=com.comphenix.protocol.ProtocolLib$1@66df69ee
        minecraftVersion=(MC: 1.19.2)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@8f1d979
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@45339b1e
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1e51c129
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35c5b14
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@5e07017
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@5c52e0de
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@4c1a2af4
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@2b99e1e8[
      statistics=<null>
      packetTask=-1
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7dd66b3b
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@2a1ae395
      commandProtocol=com.comphenix.protocol.CommandProtocol@4ee8d19f
      commandPacket=com.comphenix.protocol.CommandPacket@1b39c40f
      commandFilter=com.comphenix.protocol.CommandFilter@55f8ebe0
      packetLogging=com.comphenix.protocol.PacketLogging@2803bc81
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@206ff437
      server=CraftServer{serverName=Mohist,serverVersion=1.19.2-69,minecraftVersion=1.19.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@75235589
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@79be95b4
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@524448e1
    ]
  Version:
    ProtocolLib v5.0.0-SNAPSHOT-b602
  Java Version:
    19.0.1
  Server:
    1.19.2-69 (MC: 1.19.2)

[19:41:25 INFO]: [ProtocolLib] Disabling ProtocolLib v5.0.0-SNAPSHOT-b602

**Comment by l3nnartt** [comment]
any news?
