### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by forVmin** [dmulloy2/ProtocolLib#2001]
Hello! Help me please!

ERROR:

[18:01:02] [Netty Server IO #1/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor143.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 38 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/PacketPlayInFlying$PacketPlayInPosition
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPacketPlayer_Position$java_lang_Object.<init>(Unknown Source)
        ... 42 more
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@722b2bc1[
      memoryAddress=2750617768000
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@38d905ef
      chunk=Chunk(6af1efae: 2%, 303104/16777216)
      handle=4611686018427389953
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8192
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@4f04d751
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@243d6093[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4dea951a
        packetListeners=[PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=93]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION[class=PacketPlayInPosition, id=17], FLYING[class=PacketPlayInFlying, id=254], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@29c5665c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4bafd0d7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d908c9
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1d021f0d
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@204f7d48
        reporter=com.comphenix.protocol.ProtocolLib$1@1ff76d77
        server=CraftServer{serverName=Magma,serverVersion=1.12.2-3e8d3acf,minecraftVersion=1.12.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@66b8e5f2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=6
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1d2051c6
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@d5d23b1
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@7bd8d10e[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7261429a
      player=CraftPlayer{name=_MonsterKill_}
      updated=CraftPlayer{name=_MonsterKill_}
      playerName=_MonsterKill_
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@6d509371
      originalChannel=[id: 0xbeae6373, L:/192.168.50.148:25565 - R:/192.168.50.1:54125]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@6d509371, previous=[id: 0xbeae6373, L:/192.168.50.148:25565 - R:/192.168.50.1:54125], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@f468e39, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@770db994
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@18d0a982
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@81fd01e
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1d2051c6
      processor=com.comphenix.protocol.injector.NetworkProcessor@29c86e9d
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@34c94e9f
      singleDecode=false
      decodeWasNull=false
      first=true
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    1.8.0_341
  Server:
    1.12.2-3e8d3acf (MC: 1.12.2)
    
    
    
![image](https://user-images.githubusercontent.com/119062856/204012487-bc6b8165-25fc-4588-82e7-83280eb646b4.png)

**Comment by forVmin** [comment]
> > И если есть кто из Российского комьюнити, просьба помочь на русском языке =)
> 
> У меня та же проблема на любительском сервере друзей. Если ты решил проблему, можешь подсказать как? Стоит ли у тебя geyser для bedrock и java или нет? Гейзер в смысле плагина, который позволяет играть на разных платформах вместе

Нет, такого плагина у меня не стоит. Перестал работать внезапно. Почему - не понятно. java разумеется есть.
