### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Dagbaster** [dmulloy2/ProtocolLib#2018]
[22:59:07 INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0
[22:59:08 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unsupported class file major version 63
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:435)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:251)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:144)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 9 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@54ea0e8e[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6f1665c6
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6b8c98d4
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@46d22625
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-21fe707-741a1bd,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1eb4d808
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@11e97c43
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@24b49b1d
    ]
  Version:
    ProtocolLib v4.7.0
  Java Version:
    19.0.1
  Server:
    git-Spigot-21fe707-741a1bd (MC: 1.8.8)

[22:59:08 INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0
[22:59:08 ERROR]: ******************************************************
[22:59:08 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[22:59:08 ERROR]: *** Please use the built-in reload command!        ***
[22:59:08 ERROR]: ******************************************************
[22:59:08 INFO]: [ProtocolLib] Disabling ProtocolLib v4.7.0

**Comment by Dagbaster** [comment]
What is this?

**Comment by Dagbaster** [comment]
Not working?
