### ISSUE TITLE
Unable to intercept a read client packet

### ISSUE THREAD

**Issue by SmashTR** [dmulloy2/ProtocolLib#203]
java.lang.NullPointerException
        at com.comphenix.protocol.reflect.FuzzyReflection.getFields(FuzzyReflection.java:553)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldListByType(FuzzyReflection.java:384)
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:363)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.handleLogin(NettyChannelInjector.java:599)
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.decode(NettyChannelInjector.java:539)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Unknown Source)

**Comment by SmashTR** [comment]
Help Please

**Comment by dmulloy2** [comment]
Are you using PaperSpigot 1.8?

**Comment by SmashTR** [comment]
No Normal Spigot :(

2016-05-08 2:55 GMT+03:00 Dan Mulloy <notifications@github.com>:

**Comment by dmulloy2** [comment]
So this is an issue with normal Spigot 1.8? What version of ProtocolLib are you using?

**Comment by dmulloy2** [comment]
Tracking this in #208
