### ISSUE TITLE
error text

### ISSUE THREAD

**Issue by sudapeople** [dmulloy2/ProtocolLib#2042]
# paper-1.19.3-338
# ubuntu 22.04.1

# java 17 
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)

error message ::

FieldAccessException: Field index 0 is out of bounds for length 0
at ProtocolLib-607-193.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
at ProtocolLib-607-193.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
at TabList-bukkit-5.6.6.jar//hu.montlikadani.tablist.ProtocolPackets.onPacketSending(ProtocolPackets.java:53)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
at ProtocolLib-607-193.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:430)
at net.minecraft.network.NetworkManager.processQueue(NetworkManager.java:547)
at net.minecraft.network.NetworkManager.flushQueue(NetworkManager.java:503)
at net.minecraft.network.NetworkManager.a(NetworkManager.java:398)
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2161)
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2147)
at net.minecraft.server.level.PlayerChunkMap$EntityTracker.a(PlayerChunkMap.java:1562)
at net.minecraft.server.level.EntityTrackerEntry.a(EntityTrackerEntry.java:195)
at net.minecraft.server.level.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:1267)
at net.minecraft.server.level.PlayerChunkMap.l(PlayerChunkMap.java:1278)
at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:818)
at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:649)
at net.minecraft.server.level.WorldServer.a(WorldServer.java:688)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1535)
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by lokka30** [comment]
This may be a TabList issue.
