### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by FazziCLAY** [dmulloy2/ProtocolLib#2067]
```logs
[18:11:59] [Netty Epoll Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@dfb7b99.
[18:11:59] [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@5698a52a[
      memoryAddress=140278262641392
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(29c5916c: 1%, 16384/4194304)
      handle=562980018192384
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8192
      length=28
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@12d8e244
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=28
      writerIndex=28
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2e8b4f37[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7a033282
        packetListeners=[PacketAdapter[plugin=emotecraft, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7b996617
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@22926be7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@56147a75
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35e0d517
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@34853a79
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@72cc0412
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4dee14dc
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4ddebf0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@dfb7b99[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7962224
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@5167b6fc
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@536e8fd1
      originalChannel=[id: 0x92c81cc8, L:/185.211.170.191:25565 - R:/31.163.79.196:60873]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@536e8fd1, previous=[id: 0x92c81cc8, L:/185.211.170.191:25565 - R:/31.163.79.196:60873], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6d811e37, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@19e64043
      vanillaDecoder=net.minecraft.network.PacketDecoder@7cf395ee
      vanillaEncoder=net.minecraft.network.PacketEncoder@20545b47
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4dee14dc
      processor=com.comphenix.protocol.injector.NetworkProcessor@531ad0e1
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 28, widx: 28, cap: 28)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@33a67389
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.5
  Server:
    git-Paper-307 (MC: 1.19.2)

[18:12:00] [Netty Epoll Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@dfb7b99.
[18:12:00] [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@ce918d9[
      memoryAddress=140278262649584
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(29c5916c: 1%, 24576/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=1
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@12d8e244
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2e8b4f37[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7a033282
        packetListeners=[PacketAdapter[plugin=emotecraft, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7b996617
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@22926be7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@56147a75
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35e0d517
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@34853a79
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@72cc0412
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4dee14dc
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4ddebf0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@dfb7b99[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7962224
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@5167b6fc
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@536e8fd1
      originalChannel=[id: 0x92c81cc8, L:/185.211.170.191:25565 - R:/31.163.79.196:60873]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@536e8fd1, previous=[id: 0x92c81cc8, L:/185.211.170.191:25565 - R:/31.163.79.196:60873], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6d811e37, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@19e64043
      vanillaDecoder=net.minecraft.network.PacketDecoder@7cf395ee
      vanillaEncoder=net.minecraft.network.PacketEncoder@20545b47
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4dee14dc
      processor=com.comphenix.protocol.injector.NetworkProcessor@531ad0e1
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@33a67389
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.5
  Server:
    git-Paper-307 (MC: 1.19.2)

[18:12:01] [Netty Epoll Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@dfb7b99.
[18:12:01] [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@1c47181d[
      memoryAddress=140278262649584
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(29c5916c: 1%, 32768/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=9
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@12d8e244
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=9
      writerIndex=9
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@2e8b4f37[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7a033282
        packetListeners=[PacketAdapter[plugin=emotecraft, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7b996617
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@22926be7
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@56147a75
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@35e0d517
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@34853a79
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@72cc0412
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=1
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@4dee14dc
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4ddebf0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@dfb7b99[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7962224
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@5167b6fc
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@536e8fd1
      originalChannel=[id: 0x92c81cc8, L:/185.211.170.191:25565 - R:/31.163.79.196:60873]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@536e8fd1, previous=[id: 0x92c81cc8, L:/185.211.170.191:25565 - R:/31.163.79.196:60873], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6d811e37, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@19e64043
      vanillaDecoder=net.minecraft.network.PacketDecoder@7cf395ee
      vanillaEncoder=net.minecraft.network.PacketEncoder@20545b47
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@4dee14dc
      processor=com.comphenix.protocol.injector.NetworkProcessor@531ad0e1
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@33a67389
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.5
  Server:
    git-Paper-307 (MC: 1.19.2)
```

**Comment by FazziCLAY** [comment]
1.19.2 paper

**Comment by GavinGoGaming** [comment]
Same issue, 1.19.3 purpur.
https://mclo.gs/Pa2gIe5
^^ Full logs

**Comment by GavinGoGaming** [comment]
Nevermind, here are my full logs. The host i use cuts off 90% of logs so
[latest.log file](https://github.com/dmulloy2/ProtocolLib/files/10315740/latest.log)

**Comment by NeotenySS** [comment]
Damn it.... 
Do you even read what you download from the Spigot website?! 
The 4.8.0 PL supports versions 1.18 and below. 
To use PL for versions 19, you need to download dev builds.

**Comment by NeotenySS** [comment]
@FazziCLAY @GavinGoGaming

**Comment by NeotenySS** [comment]
Don't forget close issue

**Comment by GavinGoGaming** [comment]
omg im dumb sorry

**Comment by NeotenySS** [comment]
Close ticket bro
@GavinGoGaming

**Comment by GavinGoGaming** [comment]
> Close ticket bro
> 
> @GavinGoGaming 

It's not my ticket.

**Comment by GavinGoGaming** [comment]
@FazziCLAY close the issue, install the Dev build
