### ISSUE TITLE
Error Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by GYF0814** [dmulloy2/ProtocolLib#2068]
[09:16:41 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 1024!
[09:16:41 INFO]: Error Unable to intercept a read client packet. (java.lang.RuntimeException: Error occured while instancing generated class.) occured in com.comphenix.protocol.injector.netty.ChannelInjector@707e9ec5.
[09:16:41 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.RuntimeException: Error occured while instancing generated class.
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:249)
        at com.comphenix.protocol.reflect.compiler.CompiledStructureModifier.withTarget(CompiledStructureModifier.java:130)
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:139)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:324)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:750)
  Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor51.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:233)
        ... 37 more
  Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PacketPlayInFlying$PacketPlayInPosition
        at com.comphenix.protocol.reflect.compiler.CompiledStructure$net_minecraft_network_play_client_CPlayerPacket_PositionPacket$java_lang_Object.<init>(Unknown Source)
        ... 41 more
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@4cdf7099[
      memoryAddress=139893627945008
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@3149d1cf
      chunk=Chunk(74e8aa38: 3%, 401408/16777216)
      handle=4611686022722357249
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=8224
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@12289a4a
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7c7d6f9a[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@db8e8c9
        packetListeners=[PacketAdapter[plugin=AntiAttack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiAttack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiAttack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[PING[class=PacketStatusInPing, id=1]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiAttack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AntiAttack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[START[class=PacketStatusInStart, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiAttack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], STRUCT[class=PacketPlayInStruct, id=42], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], SPECTATE[class=PacketPlayInSpectate, id=45], USE_ITEM[class=PacketPlayInUseItem, id=46], B_EDIT[class=PacketPlayInBEdit, id=11], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=12], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=16], USE_ENTITY[class=PacketPlayInUseEntity, id=13], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=14], LOOK[class=PacketPlayInLook, id=19], POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], PICK_ITEM[class=PacketPlayInPickItem, id=23], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], BOAT_MOVE[class=PacketPlayInBoatMove, id=22], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], ABILITIES[class=PacketPlayInAbilities, id=25], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], ITEM_NAME[class=PacketPlayInItemName, id=32], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], START[class=PacketLoginInStart, id=0], TR_SEL[class=PacketPlayInTrSel, id=35], BEACON[class=PacketPlayInBeacon, id=36], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], START[class=PacketStatusInStart, id=0], PING[class=PacketStatusInPing, id=1], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], TRANSACTION[class=PacketPlayInTransaction, id=255], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], FLYING[class=PacketPlayInFlying, id=254], CHAT[class=PacketPlayInChat, id=3], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], SETTINGS[class=PacketPlayInSettings, id=5], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3db3242d
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@c65a826
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1b73178f
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@51c74a88
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@20d4d40b
        reporter=com.comphenix.protocol.ProtocolLib$1@75f19ed1
        server=CraftServer{serverName=Mohist,serverVersion=1.16.5-1095,minecraftVersion=1.16.5}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@57b886af
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=3
        phasePlayingCount=7
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2347d80d
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1f95e77a
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@707e9ec5[
      decodeBuffer=protected void net.minecraft.network.NettyPacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.NettyPacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@57cc5eb4
      player=CraftPlayer{name=GYF0814}
      updated=CraftPlayer{name=GYF0814}
      playerName=GYF0814
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@65dde3b3
      originalChannel=[id: 0xc919a87a, L:/172.18.0.20:26630 - R:/61.152.197.76:12965]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.field_150746_k], container=net.minecraft.network.NetworkManager@65dde3b3, previous=[id: 0xc919a87a, L:/172.18.0.20:26630 - R:/61.152.197.76:12965], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@377de795, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4a8605e3
      vanillaDecoder=net.minecraft.network.NettyPacketDecoder@404ca77b
      vanillaEncoder=net.minecraft.network.NettyPacketEncoder@7d7c3d75
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2347d80d
      processor=com.comphenix.protocol.injector.NetworkProcessor@5fb69c42
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@35268f9b
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    1.8.0_345
  Server:
    1.16.5-1095 (MC: 1.16.5)

**Comment by NeotenySS** [comment]
server=CraftServer{serverName=Mohist,serverVersion=1.16.5-1095,minecraftVersion=1.16.5}
library=ProtocolLib v4.8.0

Another request... Oh... 
Read what it says on the Spigot website. 
PL 4.8.0 doesn't support mintcraft 1.16.5.
Please read what is written in plugin updates, you have eyes for a reason... 
You need PL 4.6.0 for compatibility with your server 1.16.5
@GYF0814

**Comment by NeotenySS** [comment]
Don't forget close issue

**Comment by GYF0814** [comment]
> server=CraftServer{serverName=Mohist,serverVersion=1.16.5-1095,minecraftVersion=1.16.5} library=ProtocolLib v4.8.0
> 
> Another request... Oh... Read what it says on the Spigot website. PL 4.8.0 doesn't support mintcraft 1.16.5. Please read what is written in plugin updates, you have eyes for a reason... You need PL 4.6.0 for compatibility with your server 1.16.5 @GYF0814

thank you so much and this works!
