### ISSUE TITLE
Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by StoredData** [dmulloy2/ProtocolLib#2069]
If this problem hasn't already been reported, please open a ticket
31.12 21:31:34 [Server] [INFO] at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
31.12 21:31:34 [Server] [INFO] Stack Trace:
31.12 21:31:34 [Server] [INFO] java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
31.12 21:31:34 [Server] [INFO] at ProtocolLib (4).jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
31.12 21:31:34 [Server] [INFO] at ProtocolLib (4).jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
31.12 21:31:34 [Server] [INFO] at ProtocolLib (4).jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
31.12 21:31:34 [Server] [INFO] at ProtocolLib (4).jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at ProtocolLib (4).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
31.12 21:31:34 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
31.12 21:31:34 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
31.12 21:31:34 [Server] [INFO] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
31.12 21:31:34 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:831)
31.12 21:31:34 [Server] [INFO] Dump:
31.12 21:31:34 [Server] [INFO] Parameters: 
31.12 21:31:34 [Server] [INFO] io.netty.buffer.PooledUnsafeDirectByteBuf@61f952e6[
31.12 21:31:34 [Server] [INFO] memoryAddress=140011035610256
31.12 21:31:34 [Server] [INFO] recyclerHandle=NOOP_HANDLE
31.12 21:31:34 [Server] [INFO] chunk=Chunk(11690ad5: 1%, 24576/4194304)
31.12 21:31:34 [Server] [INFO] handle=1125929971613696
31.12 21:31:34 [Server] [INFO] memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
31.12 21:31:34 [Server] [INFO] offset=16384
31.12 21:31:34 [Server] [INFO] length=256
31.12 21:31:34 [Server] [INFO] maxLength=256
31.12 21:31:34 [Server] [INFO] cache=io.netty.buffer.PoolThreadCache@4f6bf187
31.12 21:31:34 [Server] [INFO] tmpNioBuf=<null>
31.12 21:31:34 [Server] [INFO] allocator=PooledByteBufAllocator(directByDefault: true)
31.12 21:31:34 [Server] [INFO] refCnt=2
31.12 21:31:34 [Server] [INFO] readerIndex=18
31.12 21:31:34 [Server] [INFO] writerIndex=18
31.12 21:31:34 [Server] [INFO] markedReaderIndex=0
31.12 21:31:34 [Server] [INFO] markedWriterIndex=0
31.12 21:31:34 [Server] [INFO] maxCapacity=2147483647
31.12 21:31:34 [Server] [INFO] ]
31.12 21:31:34 [Server] [INFO] manager:
31.12 21:31:34 [Server] [INFO] com.comphenix.protocol.injector.PacketFilterManager@7482f830[
31.12 21:31:34 [Server] [INFO] unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2d647bd7
31.12 21:31:34 [Server] [INFO] packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]]]
31.12 21:31:34 [Server] [INFO] packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3d935035
31.12 21:31:34 [Server] [INFO] playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2e095aed
31.12 21:31:34 [Server] [INFO] inputBufferedPackets=[]
31.12 21:31:34 [Server] [INFO] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4da96464
31.12 21:31:34 [Server] [INFO] sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@431d04c5
31.12 21:31:34 [Server] [INFO] hasClosed=false
31.12 21:31:34 [Server] [INFO] classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (4).jar}
31.12 21:31:34 [Server] [INFO] reporter=com.comphenix.protocol.ProtocolLib$1@64a8f66b
31.12 21:31:34 [Server] [INFO] server=CraftServer{serverName=Paper,serverVersion=git-Paper-359,minecraftVersion=1.19.3}
31.12 21:31:34 [Server] [INFO] library=ProtocolLib v4.8.0
31.12 21:31:34 [Server] [INFO] asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@61ed803
31.12 21:31:34 [Server] [INFO] knowsServerPackets=true
31.12 21:31:34 [Server] [INFO] knowsClientPackets=true
31.12 21:31:34 [Server] [INFO] phaseLoginCount=0
31.12 21:31:34 [Server] [INFO] phasePlayingCount=1
31.12 21:31:34 [Server] [INFO] packetCreation=false
31.12 21:31:34 [Server] [INFO] nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6eabceb7
31.12 21:31:34 [Server] [INFO] pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3587a3dc
31.12 21:31:34 [Server] [INFO] hasRecycleDistance=true
31.12 21:31:34 [Server] [INFO] minecraftVersion=(MC: 1.19.3)
31.12 21:31:34 [Server] [INFO] debug=false
31.12 21:31:34 [Server] [INFO] ]
31.12 21:31:34 [Server] [INFO] Sender:
31.12 21:31:34 [Server] [INFO] com.comphenix.protocol.injector.netty.ChannelInjector@8766e36[
31.12 21:31:34 [Server] [INFO] decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
31.12 21:31:34 [Server] [INFO] encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
31.12 21:31:34 [Server] [INFO] factory=com.comphenix.protocol.injector.netty.InjectionFactory@21e0bc
31.12 21:31:34 [Server] [INFO] player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@3b1d3950
31.12 21:31:34 [Server] [INFO] updated=<null>
31.12 21:31:34 [Server] [INFO] playerName=<null>
31.12 21:31:34 [Server] [INFO] playerConnection=<null>
31.12 21:31:34 [Server] [INFO] networkManager=net.minecraft.network.NetworkManager@77282ba0
31.12 21:31:34 [Server] [INFO] originalChannel=[id: 0xec2aa8ba, L:/172.17.0.5:25565 - R:/129.159.242.197:58596]
31.12 21:31:34 [Server] [INFO] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@77282ba0, previous=[id: 0xec2aa8ba, L:/172.17.0.5:25565 - R:/129.159.242.197:58596], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@292a38a4, previousLoaded=true, currentSet=true, forceAccess=true]
31.12 21:31:34 [Server] [INFO] packetMarker={}
31.12 21:31:34 [Server] [INFO] currentEvent=<null>
31.12 21:31:34 [Server] [INFO] finalEvent=<null>
31.12 21:31:34 [Server] [INFO] unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@4303ba43
31.12 21:31:34 [Server] [INFO] vanillaDecoder=net.minecraft.network.PacketDecoder@50d07e6c
31.12 21:31:34 [Server] [INFO] vanillaEncoder=net.minecraft.network.PacketEncoder@6f3bceac
31.12 21:31:34 [Server] [INFO] finishQueue=[]
31.12 21:31:34 [Server] [INFO] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@6eabceb7
31.12 21:31:34 [Server] [INFO] processor=com.comphenix.protocol.injector.NetworkProcessor@492355f3
31.12 21:31:34 [Server] [INFO] injected=true
31.12 21:31:34 [Server] [INFO] closed=false
31.12 21:31:34 [Server] [INFO] cumulation=PooledUnsafeDirectByteBuf(ridx: 18, widx: 18, cap: 256)
31.12 21:31:34 [Server] [INFO] cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1ad371a5
31.12 21:31:34 [Server] [INFO] singleDecode=false
31.12 21:31:34 [Server] [INFO] first=true
31.12 21:31:34 [Server] [INFO] firedChannelRead=false
31.12 21:31:34 [Server] [INFO] selfFiredChannelRead=true
31.12 21:31:34 [Server] [INFO] decodeState=1
31.12 21:31:34 [Server] [INFO] discardAfterReads=16
31.12 21:31:34 [Server] [INFO] numReads=0
31.12 21:31:34 [Server] [INFO] added=true
31.12 21:31:34 [Server] [INFO] ]
31.12 21:31:34 [Server] [INFO] Version:
31.12 21:31:34 [Server] [INFO] ProtocolLib v4.8.0
31.12 21:31:34 [Server] [INFO] Java Version:
31.12 21:31:34 [Server] Startup17
31.12 21:31:34 [Server] [INFO] Server:
31.12 21:31:34 [Server] [INFO] git-Paper-359 (MC: 1.19.3)
31.12 21:31:34 [Server] [INFO] Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@8766e36.

**Comment by NeotenySS** [comment]
Damn it.
Don't tell me you can't read...
Stupid "issues" like this littering GitHub makes it harder to find the real cause of bugs.
But you can put the developer out of his misery.
I'm very surprised how people try to create servers and don't read what they download... God... Yes even in the error you can see what's wrong, just read it, cool, right? Just start reading.
You are using Paper 1.19.3
You are using PL 4.8.0 which only supports versions 1.17.x-1.18.x.
Now do you realize that you have created a bug for yourself?
The 1.19 version requires the use of dev builds, but they are not stable builds, although they can work well.
Just learn to read please and don't create such silly issues again.
Close the Issue and download the dev build.
![IMG_20230102_224836](https://user-images.githubusercontent.com/11386982/210274063-b34a7840-d377-48a6-98c7-ea699a45dc48.jpg)
@StoredData

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
