### ISSUE TITLE
Unable to read client packet

### ISSUE THREAD

**Issue by DontSharee** [dmulloy2/ProtocolLib#2070]
[01:48:33 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2bcf1b80[
      memoryAddress=140629803080768
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@23658314
      chunk=Chunk(4e8be527: 23%, 958464/4194304)
      handle=14636728853725185
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=213024
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@5885914d
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@38cf444f[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4a4a2b7
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@67392be3
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@ebf9bba
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4c105b1e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6d00e931
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@31d880c9
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-215,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@157dc2fc
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@15ff4f96
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4fc1daf1
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@38daf803[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@8c5c208
      player=CraftPlayer{name=DontShare}
      updated=<null>
      playerName=DontShare
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@36a6fda5
      originalChannel=[id: 0x2828d058, L:/240.4.89.23:25575 - R:/240.4.0.13:56996]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@36a6fda5, previous=[id: 0x2828d058, L:/240.4.89.23:25575 - R:/240.4.0.13:56996], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6ff4efe5, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@16ad727c
      vanillaDecoder=net.minecraft.network.PacketDecoder@437ee107
      vanillaEncoder=net.minecraft.network.PacketEncoder@436a99ba
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@15ff4f96
      processor=com.comphenix.protocol.injector.NetworkProcessor@766a706e
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@42a8d17d
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    git-Paper-215 (MC: 1.19.2)

**Comment by NeotenySS** [comment]
Damn it.
Don't tell me you can't read...
Stupid "issues" like this littering GitHub makes it harder to find the real cause of bugs.
But you can put the developer out of his misery.
I'm very surprised how people try to create servers and don't read what they download... God... Yes even in the error you can see what's wrong, just read it, cool, right? Just start reading.
You are using Paper 1.19.2
You are using PL 4.8.0 which only supports versions 1.17.x-1.18.x.
Now do you realize that you have created a bug for yourself?
The 1.19 version requires the use of dev builds, but they are not stable builds, although they can work well.
Just learn to read please and don't create such silly issues again.
Close the Issue and download the dev build.
![IMG_20230102_224836](https://user-images.githubusercontent.com/11386982/210273942-5bd03384-cd6e-4d90-abd5-33e15c8ce789.jpg)
@DontSharee

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
