### ISSUE TITLE
Console Error spamming

### ISSUE THREAD

**Issue by hillbilly1911** [dmulloy2/ProtocolLib#2073]
on the newest version and it keeps throwing this error. Purpur git-Purpur-1858 (MC: 1.19.2)

Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@33e7fed8[
      memoryAddress=140492608142240
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(1e690e4: 1%, 24576/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=1
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@2605ee0
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@208e6a85[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@23288223
        packetListeners=[PacketAdapter[plugin=HolographicExtension, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemJoin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], PICK_ITEM[class=PacketPlayInPickItem, id=23], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@71f9da72
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6d07e2ff
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3e8e6798
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@59d0d3f0
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@66c5a8f2
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1858,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7978ad70
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@58f60890
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3b0a523c
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@5033bcfb[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@72c72ff6
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@2ca72d9a
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@19f3f95a
      originalChannel=[id: 0x0e7be74a, L:/172.18.0.9:24452 - R:/23.139.82.49:53004]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@19f3f95a, previous=[id: 0x0e7be74a, L:/172.18.0.9:24452 - R:/23.139.82.49:53004], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@547d8069, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@41a3ac81
      vanillaDecoder=net.minecraft.network.PacketDecoder@471ca4c6
      vanillaEncoder=net.minecraft.network.PacketEncoder@7fdeb51c
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@58f60890
      processor=com.comphenix.protocol.injector.NetworkProcessor@1b836790
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@6e9df4d0
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.2
  Server:
    git-Purpur-1858 (MC: 1.19.2)

[01:00:36 INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@3312bb9.

**Comment by NeotenySS** [comment]
Damn it.
Don't tell me you can't read...
Stupid "issues" like this littering GitHub makes it harder to find the real cause of bugs.
But you can put the developer out of his misery.
I'm very surprised how people try to create servers and don't read what they download... God... Yes even in the error you can see what's wrong, just read it, cool, right? Just start reading.
You are using Purpur 1.19.2
You are using PL 4.8.0 which only supports versions 1.17.x-1.18.x.
Now do you realize that you have created a bug for yourself?
The 1.19 version requires the use of dev builds, but they are not stable builds, although they can work well.
Just learn to read please and don't create such silly issues again.
Close the Issue and download the dev build.
![IMG_20230102_224836](https://user-images.githubusercontent.com/11386982/210273759-c92de1b0-2d45-4f11-bf6a-49f151a66aef.jpg)
@hillbilly1911

**Comment by dmulloy2** [comment]
Try build 606: https://ci.dmulloy2.net/job/ProtocolLib/606/
