### ISSUE TITLE
on 1.12.2

### ISSUE THREAD

**Issue by mcxiedidi** [dmulloy2/ProtocolLib#2077]
The reason for not being able to inject an inbound channel is that the NetworkManager cannot be found in the channel.

`[13:13:06] [Netty Server IO #2/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xf1b984cf, L:/10.2.8.5:55044 - R:/42.235.32.218:4611].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xf1b984cf, L:/10.2.8.5:55044 - R:/42.235.32.218:4611]
  	at com.comphenix.protocol.compat.netty.independent.NettyInjectionFactory.findNetworkManager(NettyInjectionFactory.java:212)
  	at com.comphenix.protocol.compat.netty.independent.NettyInjectionFactory.fromChannel(NettyInjectionFactory.java:145)
  	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:154)
  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitial`

**Comment by TheFaik** [comment]
Пробовали обновить ProtocolLib?
