### ISSUE TITLE
getEntityUseActions() Dont works with Latest dev Version

### ISSUE THREAD

**Issue by Snowiiii** [dmulloy2/ProtocolLib#2081]
- [X] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
I use PacketType.Play.Client.USE_ENTITY and want to read the Entity use actions enum
but then i get Errors in the console that field is not exists

**Expected behavior**
No errors and to get the right enum

**Version Info**
https://pastebin.com/pPg2wBtE

**Additional context**
Console log:
```
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218) ~[ProtocolLib.jar:?]
        at de.snowii.com.vent.processors.CombatProcessor.onPacketReceiving(CombatProcessor.java:25) ~[VAC.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:549) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:514) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:117) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:505) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[ProtocolLib.jar:?]
```

**Comment by Snowiiii** [comment]
I should use getEnumEntityUseActions() understand
