### ISSUE TITLE
Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

### ISSUE THREAD

**Issue by spookymgmt** [dmulloy2/ProtocolLib#2083]
- [ ] This issue is not solved in a development build

I'm on the latest protocollib & viaversion dev builds. Any plugin displayed in the bellow error, I've tried running my server with them unloaded, with it still occuring.

```
[11:08:21] [Netty Epoll Server IO #4/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[11:08:21] [Netty Epoll Server IO #4/WARN]: Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[11:08:21] [Netty Epoll Server IO #4/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(51) + length(1) exceeds writerIndex(51): PooledUnsafeDirectByteBuf(ridx: 51, widx: 51, cap: 256)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:146)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:60)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:38)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at eGlow 3.2.1 1.9.4-1.19.3 (1).jar//me.MrGraycat.eGlow.Util.Packets.PipelineInjector$1.write(PipelineInjector.java:92)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at FartherViewDistance-9.7.4 (1).jar//xuan.cat.fartherviewdistance.code.branch.v19.Branch_19_Minecraft$1.write(Branch_19_Minecraft.java:109)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

```

At random times, this above error will occur. It seems like it's always caused by a bedrock player. But maybe not.

When a player triggers this error, NOBODY can join the server until the player who triggered it leaves the server.

Once the player who caused / received / sent the malformed packet leaves the server, everything goes back to normal. With this information,

This issue has been occurring since 1.19.3 viaversion released, when that released I updated protocollib same time. 

I'm lost, don't know what to do.

Please don't just close this, I have no where else to go. At minimum, how can I diagnose the issue if it some how happens not to be protocollib?

**Comment by DimaSergeew** [comment]
I have the same problem for a long time and thought it was ViaVersion, but after a deep study and disabling other plugins, it's still the fault ProtocolLib you also GEyserMC?

**Comment by spookymgmt** [comment]
> I have the same problem for a long time and thought it was ViaVersion, but after a deep study and disabling other plugins, it's still the fault ProtocolLib you also GeyserMC?

Yup I use geyser, could you send  a /viaver dump here?

**Comment by DimaSergeew** [comment]
> > У меня такая же проблема в течение длительного времени, и я думал, что это ViaVersion, но после глубокого изучения и отключения других плагинов, это все еще ошибка ProtocolLib вы также GeyserMC?
> 
> Да, я использую geyser, не могли бы вы отправить дамп / viaver сюда?

Listen I removed Viaversion, and even without it after a while people could not log on to the server and there were no errors in the console 0_0

**Comment by DimaSergeew** [comment]
> > У меня такая же проблема в течение длительного времени, и я думал, что это ViaVersion, но после глубокого изучения и отключения других плагинов, это все еще ошибка ProtocolLib вы также GeyserMC?
> 
> Да, я использую geyser, не могли бы вы отправить дамп / viaver сюда?

Write to me on the discord and we'll try to find a solution together, since it's not a fact that Protocollib is to blame, my discord is BeDePaY#4680
