### ISSUE TITLE
help pls idk what to do :D INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by AS0ZIAL** [dmulloy2/ProtocolLib#2085]
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2b695719[
      memoryAddress=140293630533504
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@71858e6
      chunk=Chunk(3c750225: 27%, 1105920/4194304)
      handle=562980018192385
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=8224
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@739ea859
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@98ed90c[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1d7e9632
        packetListeners=[PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=ClientboundDeleteChatPacket, id=22], WINDOW_ITEMS[class=ClientboundCustomChatCompletionsPacket, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1b2439a4
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@c01c3f4
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@73383dc1
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1a9efa92
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@204d097c
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-371,minecraftVersion=1.19.3}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1035975c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=8
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@20101e03
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@48470016
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.3)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@1f6094f6[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@3c2d792b
      player=CraftPlayer{name=Addiction}
      updated=<null>
      playerName=Addiction
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@57466359
      originalChannel=[id: 0xc9de2112, L:/172.20.0.5:56539 - R:/77.180.97.129:54812]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@57466359, previous=[id: 0xc9de2112, L:/172.20.0.5:56539 - R:/77.180.97.129:54812], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@583d191d, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@450a540d
      vanillaDecoder=net.minecraft.network.PacketDecoder@1415eb6e
      vanillaEncoder=net.minecraft.network.PacketEncoder@66461bfe
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@20101e03
      processor=com.comphenix.protocol.injector.NetworkProcessor@413e8f3b
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@7acb52e9
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.4.1
  Server:
    git-Paper-371 (MC: 1.19.3)

[18:17:20] [Server thread/ERROR]: [Citizens] Unhandled exception occured in onPacketSending(PacketEvent) for Citizens
java.lang.RuntimeException: Unable to find network.protocol.game.PacketPlayOutPlayerInfo$PlayerInfoData (PacketPlayOutPlayerInfo$PlayerInfoData, PlayerInfoData)
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2159) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getPlayerInfoDataClass(MinecraftReflection.java:1809) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.isPlayerInfoData(MinecraftReflection.java:1865) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.PlayerInfoData$1.getSpecific(PlayerInfoData.java:135) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.PlayerInfoData$1.getSpecific(PlayerInfoData.java:96) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.getSpecificList(BukkitConverters.java:318) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters.access$000(BukkitConverters.java:88) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:362) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$3.getSpecific(BukkitConverters.java:359) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:43) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:260) ~[ProtocolLib.jar:?]
	at net.citizensnpcs.ProtocolLibListener$1.onPacketSending(ProtocolLibListener.java:55) ~[Citizens-2.0.30-b2888.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2157) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2143) ~[?:?]
	at net.minecraft.server.players.PlayerList.tick(PlayerList.java:967) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-371]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-371]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[18:17:20] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@4b3c2b6c[
    a=[UPDATE_LATENCY]
    b=[b[profileId=be736478-5868-3297-b1fb-f041f843a309, profile=com.mojang.authlib.GameProfile@51a723b7[id=be736478-5868-3297-b1fb-f041f843a309,name=Addiction,properties={textures=[com.mojang.authlib.properties.Property@583a77be]},legacy=false], listed=true, latency=14, gameMode=CREATIVE, displayName=empty[siblings=[literal{ }[style={!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{O}[style={color=#FF00FF,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{w}[style={color=#CC33FF,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{n}[style={color=#9966FF,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{e}[style={color=#6699FF,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{r }[style={color=#33CCFF,!bold,!italic,!underlined,!strikethrough,!obfuscated}], literal{Addiction}[style={!italic}]]], chatSession=null]]

**Comment by Batchicken** [comment]
I am getting this error as well. It even appears in the in-game chat. I have attached a screenshot of the chat as well as my latest log file.
![Chat Screenshot](https://user-images.githubusercontent.com/24801979/211212846-9721c2a2-caa7-4de9-9ffb-947e85c4fc8a.png)
[2023-01-08-4.log](https://github.com/dmulloy2/ProtocolLib/files/10369195/2023-01-08-4.log)

**Comment by Jeppa** [comment]
Serious?
> ProtocolLib v4.8.0 ???
Please read the ProtocolLib homepage again...

**Comment by Batchicken** [comment]
> Please read the ProtocolLib homepage again...
With all due respect, this was unnecessary and didn't help at all. Would you mind explaining what you mean?

**Comment by Jeppa** [comment]
Have a look at all this... it has been mentioned many times before.
50% of the error reports the last few weeks are useless!

And when starting a new report you are asked:
> You're using the latest build for your server version
and
> You've checked for duplicate issues

The solution was always there:
https://github.com/dmulloy2/ProtocolLib/issues/2075
https://github.com/dmulloy2/ProtocolLib/issues/2074
https://github.com/dmulloy2/ProtocolLib/issues/2073
https://github.com/dmulloy2/ProtocolLib/issues/2070
https://github.com/dmulloy2/ProtocolLib/issues/2069
https://github.com/dmulloy2/ProtocolLib/issues/2051
https://github.com/dmulloy2/ProtocolLib/issues/2046
https://github.com/dmulloy2/ProtocolLib/issues/2080
https://github.com/dmulloy2/ProtocolLib/issues/2087
https://github.com/dmulloy2/ProtocolLib/issues/2036

**Comment by NeotenySS** [comment]
> Извините, но взгляните на все это... это уже упоминалось много раз. 50% сообщений об ошибках за последние несколько недель бесполезны!
> 
> И при запуске нового отчета вас спрашивают:
> 
> > Вы используете последнюю сборку для своей версии сервера
> 
> и возможно
> 
> > Вы проверили повторяющиеся проблемы
> 
> Решение всегда было рядом: [#2075 ](https://github.com/dmulloy2/ProtocolLib/issues/2075) [#2074 ](https://github.com/dmulloy2/ProtocolLib/issues/2074) [#2073 ](https://github.com/dmulloy2/ProtocolLib/issues/2073) [#2070 ](https://github.com/dmulloy2/ProtocolLib/issues/2070) [#2069 ](https://github.com/dmulloy2/ProtocolLib/issues/2069) [#2051 ](https://github.com/dmulloy2/ProtocolLib/issues/2051) [#2046 ](https://github.com/dmulloy2/ProtocolLib/issues/2046) [#2080 ](https://github.com/dmulloy2/ProtocolLib/issues/2080) [#2087 ](https://github.com/dmulloy2/ProtocolLib/issues/2087) #2036
> 
> и даже в закрытом разделе: [#2068 ](https://github.com/dmulloy2/ProtocolLib/issues/2068) #2067 и т.д.

I am also surprised by such an issue, I would advise such people not to try to create a server, because they do not understand even basic things lol

**Comment by NeotenySS** [comment]
> Sorry, but have a look at all this... it has been mentioned many times before. 50% of the error reports the last few weeks are useless!
> 
> And when starting a new report you are asked:
> 
> > You're using the latest build for your server version
> 
> and maybe
> 
> > You've checked for duplicate issues
> 
> The solution was always there: #2075 #2074 #2073 #2070 #2069 #2051 #2046 #2080 #2087 #2036
> 
> and even in the 'closed' section: #2068 #2067 etc.

I am also surprised by such an issue, I would advise such people not to try to create a server, because they do not understand even basic things lol

**Comment by dmulloy2** [comment]
you are ultimately correct that this has been fixed in a recent development build (available at https://ci.dmulloy2.net/job/ProtocolLib), though it's understandable that not everyone is familiar with that dynamic
