### ISSUE TITLE
Error on start latest dev build on 1.8 server

### ISSUE THREAD

**Issue by l3nnartt** [dmulloy2/ProtocolLib#2096]
**Describe the bug**
Error on Server start:
https://paste.lennartloesche.de/izizemowuw

ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b608
[22:42:44 WARN]: java.lang.IllegalStateException: Unable to access field private final org.bukkit.craftbukkit.v1_8_R3.CraftWorld net.minecraft.server.v1_8_R3.World.world

**To Reproduce**
1. Start 1.8.8 Server
2. install latest dev build

**Comment by derklaro** [comment]
Can you attach the new stack trace?

**Comment by SplotyCode** [comment]
I can confirm that this happens when upgrading from 4.6 to latest dev build. Core problem is likely openj9.
Here is the exception
`Caused by: java.lang.IllegalAccessException: Class java/lang/invoke/MethodHandle illegally accessing "private" member of class net/minecraft/server/v1_8_R3/IChatBaseComponent$ChatSerializer
	at java.lang.invoke.FieldHandle.finishFieldInitialization(Unknown Source) ~[?:?]
	at java.lang.invoke.FieldHandle.<init>(Unknown Source) ~[?:?]
	at java.lang.invoke.StaticFieldGetterHandle.<init>(Unknown Source) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findStaticGetter(Unknown Source) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:89) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84) ~[?:?]`
