### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by pentarh** [dmulloy2/ProtocolLib#2100]
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[15:58:35 INFO]: Building unoptimized datafixer
[15:58:36 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:58:38 INFO]: Loaded 7 recipes
[15:58:39 INFO]: Starting minecraft server version 1.19.2
[15:58:39 INFO]: Loading properties
[15:58:39 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
[15:58:39 INFO]: Server Ping Player Sample Count: 12
[15:58:39 INFO]: Using 4 threads for Netty based IO
[15:58:39 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[15:58:39 INFO]: Default game type: SURVIVAL
[15:58:39 INFO]: Generating keypair
[15:58:40 INFO]: Starting Minecraft server on *:25565
[15:58:40 INFO]: Using default channel type
[15:58:40 INFO]: Paper: Using Java compression from Velocity.
[15:58:40 INFO]: Paper: Using Java cipher from Velocity.
[15:58:41 INFO]: [Stratos] Loading Stratos v1.15.3
[15:58:41 INFO]: [Vault] Loading Vault v1.7.3-b131
[15:58:41 INFO]: [UltraRegions] Loading UltraRegions v1.7.7
[15:58:41 INFO]: [Multiverse-Core] Loading Multiverse-Core v4.3.1-b861
[15:58:41 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[15:58:41 WARN]: [ProtocolLib] Version (MC: 1.19.2) has not yet been tested! Proceed with caution.
[15:58:41 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @28615292
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 10 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@971dde9[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@fe2eeb
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7673588
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@3b596fea
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@288cb889
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@52dd6e45
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    19.0.1
  Server:
    git-Paper-307 (MC: 1.19.2)

**Comment by Jeppa** [comment]
and again.....
>ProtocolLib v4.8.0
>git-Paper-307 (MC: 1.19.2)

--> that doesn't fit...

**Comment by Minionguyjpro** [comment]
> Starting org.bukkit.craftbukkit.Main *** Warning, you've not updated in a while! *** *** Please download a new build as per instructions from https://papermc.io/downloads *** System Info: Java 19 (Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21) Host: Windows 10 10.0 (amd64) Loading libraries, please wait... [15:58:35 INFO]: Building unoptimized datafixer [15:58:36 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [15:58:38 INFO]: Loaded 7 recipes [15:58:39 INFO]: Starting minecraft server version 1.19.2 [15:58:39 INFO]: Loading properties [15:58:39 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25) [15:58:39 INFO]: Server Ping Player Sample Count: 12 [15:58:39 INFO]: Using 4 threads for Netty based IO [15:58:39 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads [15:58:39 INFO]: Default game type: SURVIVAL [15:58:39 INFO]: Generating keypair [15:58:40 INFO]: Starting Minecraft server on *:25565 [15:58:40 INFO]: Using default channel type [15:58:40 INFO]: Paper: Using Java compression from Velocity. [15:58:40 INFO]: Paper: Using Java cipher from Velocity. [15:58:41 INFO]: [Stratos] Loading Stratos v1.15.3 [15:58:41 INFO]: [Vault] Loading Vault v1.7.3-b131 [15:58:41 INFO]: [UltraRegions] Loading UltraRegions v1.7.7 [15:58:41 INFO]: [Multiverse-Core] Loading Multiverse-Core v4.3.1-b861 [15:58:41 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0 [15:58:41 WARN]: [ProtocolLib] Version (MC: 1.19.2) has not yet been tested! Proceed with caution. [15:58:41 ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib. If this problem hasn't already been reported, please open a ticket at https://github.com/dmulloy2/ProtocolLib/issues with the following data: Stack Trace: java.lang.ExceptionInInitializerError at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.(ProtocolInjector.java:69) at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.(PacketFilterManager.java:202) at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185) at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177) at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203) at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:429) at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278) at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100) at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) at java.base/java.lang.Thread.run(Thread.java:1589) Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @28615292 at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161) at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187) at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.(TemporaryPlayerFactory.java:51) ... 10 more Dump: Parameters: [NULL] Sender: com.comphenix.protocol.ProtocolLib@971dde9[ statistics= backgroundCompiler= packetTask=-1 tickCounter=0 unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@fe2eeb configExpectedMod=-1 updater=com.comphenix.protocol.updater.SpigotUpdater@7673588 redirectHandler= commandProtocol= commandPacket= commandFilter= packetLogging= skipDisable=false isEnabled=false loader=org.bukkit.plugin.java.JavaPluginLoader@3b596fea server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2} file=plugins\ProtocolLib.jar description=org.bukkit.plugin.PluginDescriptionFile@288cb889 dataFolder=plugins\ProtocolLib classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib.jar} naggable=true newConfig=YamlConfiguration[path='', root='YamlConfiguration'] configFile=plugins\ProtocolLib\config.yml logger=com.destroystokyo.paper.utils.PaperPluginLogger@52dd6e45 ] Version: ProtocolLib v4.8.0 Java Version: 19.0.1 Server: git-Paper-307 (MC: 1.19.2)

I have the exact same issue on my device:
``

``

**Comment by Jeppa** [comment]
>I have the exact same issue on my device:

8O

**Comment by IllegalTempo** [comment]
Use a development version of protocollib fix this for me
