### ISSUE TITLE
Paper/Purpur incompatibility on 1.19.3

### ISSUE THREAD

**Issue by ElKayMa** [dmulloy2/ProtocolLib#2126]
It works on 1.19.2  but when I run my server with the latest dev build (and any 1.19.3 version) my server crash when starting, I'll be waiting for an update before decembrer but don't arrive and I'm so sad XD so maybe I have to request for compatibility for paper. My most important plugin only works on paper or purpur DX and a lot of plugins works with protocollib so I'm dying v,:. Save Me Please.

**Comment by Jeppa** [comment]
What's the issue? 
Any errors in log?
Using latest dev build 612 ?

**Comment by davispuh** [comment]
```
[03:58:57 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[03:58:57 WARN]: [ProtocolLib] Version (MC: 1.19.3) has not yet been tested! Proceed with caution.
[03:58:58 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.ExceptionInInitializerError
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:442)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @63e09213
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
... 10 more
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@47593076[
statistics=<null>
backgroundCompiler=<null>
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@526f9fa8
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@5cbbcf13
redirectHandler=<null>
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=org.bukkit.plugin.java.JavaPluginLoader@c355708
server=CraftServer{serverName=Paper,serverVersion=git-Paper-314,minecraftVersion=1.19.3}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@40506f85
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@399eb37b
]
Version:
ProtocolLib v4.8.0
Java Version:
19.0.2
Server:
git-Paper-314 (MC: 1.19.3)
```

**Comment by Jeppa** [comment]
ProtocolLib v4.8.0 is NOT the latest dev build...

**Comment by ElKayMa** [comment]
Sorry, the "latest dev build" on the  spigot link  take me to the 4.8.0 DX, I guess the compatibility with paper doesn't exist so I don't add the log report. My server still crash but now is for lonelibs plugin, I'm going to report to his dev. Thanks!

**Comment by Jeppa** [comment]
"latest dev build" is not the same like "latest release"...
Latest dev is build 612 (at this moment).
