### ISSUE TITLE
1.19.3 Errors

### ISSUE THREAD

**Issue by Gregoryxnmasd** [dmulloy2/ProtocolLib#2134]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib (21).jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib (21).jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib (21).jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib (21).jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at ProtocolLib (21).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@73e203dc[
      memoryAddress=137158037267008
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@25587ec8
      chunk=Chunk(697cdb35: 28%, 1138688/4194304)
      handle=49539625965846536
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=722944
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@12116645
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=13
      writerIndex=13
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@6fac36f4[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@57bd71b9
        packetListeners=[PacketAdapter[plugin=SCore, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=36]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[PONG[class=ServerboundPongPacket, id=29]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54], ABILITIES[class=PacketPlayOutAbilities, id=50], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17], GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@377fd06b, PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=PlayerWarps, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@473d2f65, PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DeluxeCombat, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=36]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DeluxeCombat, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=MyCommand, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=UltimateClans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=GPS, sending=ListeningWhitelist[priority=NORMAL, packets=[ANIMATION[class=PacketPlayOutAnimation, id=6], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=101], SPAWN_ENTITY_LIVING[PLAY, SERVER, 2, classNames: [net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityLiving, net.minecraft.network.protocol.game.ClientboundSpawnEntityLivingPacket, net.minecraft.network.play.server.SPacketSpawnMob] (unregistered)], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], SPAWN_ENTITY_PAINTING[PLAY, SERVER, 3, classNames: [net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityPainting, net.minecraft.network.protocol.game.ClientboundSpawnEntityPaintingPacket, net.minecraft.network.play.server.SPacketSpawnPainting] (unregistered)], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], COLLECT[class=PacketPlayOutCollect, id=97], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=78], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=9], COMBAT_EVENT[PLAY, SERVER, 247, classNames: [net.minecraft.network.protocol.game.PacketPlayOutCombatEvent, net.minecraft.network.protocol.game.ClientboundCombatEventPacket] (unregistered)], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=80], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=DeluxeCombat, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=93]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@b90f0e0, PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=25]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17], GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@14570bb
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@21ce194d
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2f5b9016
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@13570cfd
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (21).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@39bd7684
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-386,minecraftVersion=1.19.3}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1b40f2a4
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=30
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@56ad4e85
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3f313c18
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.3)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2432f001[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@adcbc8b
      player=CraftPlayer{name=PepitoGrillo}
      updated=<null>
      playerName=PepitoGrillo
      playerConnection=net.minecraft.server.network.PlayerConnection@2366a40a
      networkManager=net.minecraft.network.NetworkManager@45fe01c
      originalChannel=[id: 0x2ea2b295, L:/172.18.0.5:25612 - R:/103.195.103.233:41617]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@45fe01c, previous=[id: 0x2ea2b295, L:/172.18.0.5:25612 - R:/103.195.103.233:41617], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2e64d4d9, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@c8a9a26
      vanillaDecoder=net.minecraft.network.PacketDecoder@772ec4ab
      vanillaEncoder=net.minecraft.network.PacketEncoder@46163ebf
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@56ad4e85
      processor=com.comphenix.protocol.injector.NetworkProcessor@165f00ff
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 13, widx: 13, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@15df6dc5
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.5
  Server:
    git-Paper-386 (MC: 1.19.3)

**Comment by GIF68GAMiNG** [comment]
My server is like that too

**Comment by Jeppa** [comment]
>ProtocolLib v4.8.0
>git-Paper-386 (MC: 1.19.3)

**8(**
