### ISSUE TITLE
error message in console 

### ISSUE THREAD

**Issue by Sentientcat** [dmulloy2/ProtocolLib#2145]
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@4ffd54f7[
      memoryAddress=140479186405232
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@408d6870
      chunk=Chunk(71a4c7b: 27%, 1097728/4194304)
      handle=2251829878456327
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=34560
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@72419fbf
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@46490fa1[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7bf9e28b
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54], ABILITIES[class=ClientboundPlayerChatHeaderPacket, id=50]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@48fda01b
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@44988971
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4a22a244
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7e7bfc31
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5b23669d
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-215,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@49f0631
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@47f3b54b
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@45920e82
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@57be37ec[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@3075d8b
      player=CraftPlayer{name=Ishig250}
      updated=<null>
      playerName=Ishig250
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@7c5b1b83
      originalChannel=[id: 0xe2cf8c6e, L:/240.4.69.158:25575 - R:/240.4.6.90:49382]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@7c5b1b83, previous=[id: 0xe2cf8c6e, L:/240.4.69.158:25575 - R:/240.4.6.90:49382], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@57b53701, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@71126b4c
      vanillaDecoder=net.minecraft.network.PacketDecoder@5531f1ee
      vanillaEncoder=net.minecraft.network.PacketEncoder@431f026e
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@47f3b54b
      processor=com.comphenix.protocol.injector.NetworkProcessor@5fc66cc9
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@67e5d2b5
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    git-Paper-215 (MC: 1.19.2)

**Comment by Jeppa** [comment]
>ProtocolLib v4.8.0
git-Paper-215 (MC: 1.19.2)

**8(**

**Comment by Espiiii-debug** [comment]
Use build [606](https://ci.dmulloy2.net/job/ProtocolLib/606/) for Minecraft 1.19-1.19.2
