### ISSUE TITLE
Error in console, cant find field GameProfile

### ISSUE THREAD

**Issue by LUPLUV** [dmulloy2/ProtocolLib#2146]
- [ ] This issue is not solved in a development build

**Describe the bug**
Theres a error in the console when i join. I guess its a Reflections issue, it cant find the GameProfile field in PacketLoginInStart

**Expected behavior**
The player should join without any errors in console

**Error**

<code>
[19:25:57] [Netty Epoll Server IO #2/WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 256!
[19:25:57] [Netty Epoll Server IO #2/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@131f729c.
[19:25:57] [Netty Epoll Server IO #2/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@434bc288[
      memoryAddress=139747834028288
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@64e9e92b
      chunk=Chunk(42893961: 27%, 1114112/4194304)
      handle=2814779831877632
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=40960
      length=5
      maxLength=16
      cache=io.netty.buffer.PoolThreadCache@643635dc
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=5
      writerIndex=5
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@117a3[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@701d92bc
        packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=CosmeticsCore, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[RESPAWN[class=PacketPlayOutRespawn, id=61]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CosmeticsCore, sending=ListeningWhitelist[priority=HIGHEST, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=49], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=49], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=CosmeticsCore, sending=ListeningWhitelist[priority=HIGHEST, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[RECIPE_UPDATE[class=PacketPlayOutRecipeUpdate, id=102]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[MOUNT[class=PacketPlayOutMount, id=84]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CosmeticsCore, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=80]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=LOWEST, packets=[RECIPES[class=PacketPlayOutRecipes, id=57]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Roulette, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=CosmeticsCore, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=CosmeticsCore, sending=ListeningWhitelist[priority=HIGHEST, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=65]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=MONITOR, packets=[RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=60]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CosmeticsCore, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=CosmeticsCore, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Roulette, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Roulette, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@156d7d9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7c62d41f
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@74d6783f
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@68c29c6b
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@5f9d66b5
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@72e5027c
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=25
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@793f9cc5
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3002e6fc
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@131f729c[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@14d8ef2c
      player=CraftPlayer{name=LUPLUV}
      updated=<null>
      playerName=LUPLUV
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@2a7f4384
      originalChannel=[id: 0xa12e7320, L:/85.10.193.9:44956 - R:/85.10.193.9:60474]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@2a7f4384, previous=[id: 0xa12e7320, L:/85.10.193.9:44956 - R:/85.10.193.9:60474], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@17510d2a, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@750ba86
      vanillaDecoder=net.minecraft.network.PacketDecoder@5763aa8b
      vanillaEncoder=net.minecraft.network.PacketEncoder@386057ae
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@793f9cc5
      processor=com.comphenix.protocol.injector.NetworkProcessor@25c13f31
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1cf88e4a
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-307 (MC: 1.19.2)
</code>

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
