### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by cchhaarroonn** [dmulloy2/ProtocolLib#2153]
`Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739)
        at org.bukkit.Bukkit.reload(Bukkit.java:535)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @1558a61b
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 17 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@4038d0e2[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1d06187d
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@1bbf74ff
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@77d82a51
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-21fe707-741a1bd,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib (8).jar
      description=org.bukkit.plugin.PluginDescriptionFile@1f058f6f
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1d29603e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@3b05401e
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    19.0.2
  Server:
    git-Spigot-21fe707-741a1bd (MC: 1.8.8)`

**Comment by Espiiii-debug** [comment]
Try to switch your java version to 1.8

**Comment by cchhaarroonn** [comment]
> Try to switch your java version to 8

Actaully using this plugin for my plugin and plugin is being written in 1.8 but i believe im running my server with 19 so ill try to change that a bit and ill let you know

**Comment by DeniedJesus** [comment]
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:433)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.reload(CraftServer.java:936)
        at org.bukkit.Bukkit.reload(Bukkit.java:802)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:847)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:832)
        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:413)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1201)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @33010131
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 18 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@407745af[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1edfd13b
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@647fa572
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@64c2355a
      server=CraftServer{serverName=CraftBukkit,serverVersion=3652-Spigot-19641c7-6aeb5e4,minecraftVersion=1.19.3}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2440968a
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@77318c11
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@56ab9758
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    19.0.1
  Server:
    3652-Spigot-19641c7-6aeb5e4 (MC: 1.19.3)

**Comment by Espiiii-debug** [comment]
> [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib. Stack Trace: java.lang.ExceptionInInitializerError at com.comphenix.protocol.injector.netty.ProtocolInjector.(ProtocolInjector.java:69) at com.comphenix.protocol.injector.PacketFilterManager.(PacketFilterManager.java:202) at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185) at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177) at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203) at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:433) at org.bukkit.craftbukkit.v1_19_R2.CraftServer.reload(CraftServer.java:936) at org.bukkit.Bukkit.reload(Bukkit.java:802) at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:847) at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:832) at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:413) at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:389) at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1201) at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) at java.base/java.lang.Thread.run(Thread.java:1589) Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @33010131 at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471) at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283) at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117) at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243) at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150) at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101) at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161) at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187) at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.(TemporaryPlayerFactory.java:51) ... 18 more Dump: Parameters: [NULL] Sender: com.comphenix.protocol.ProtocolLib@407745af[ statistics= backgroundCompiler= packetTask=-1 tickCounter=0 unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1edfd13b configExpectedMod=-1 updater=com.comphenix.protocol.updater.SpigotUpdater@647fa572 redirectHandler= commandProtocol= commandPacket= commandFilter= packetLogging= skipDisable=false isEnabled=false loader=org.bukkit.plugin.java.JavaPluginLoader@64c2355a server=CraftServer{serverName=CraftBukkit,serverVersion=3652-Spigot-19641c7-6aeb5e4,minecraftVersion=1.19.3} file=plugins\ProtocolLib.jar description=org.bukkit.plugin.PluginDescriptionFile@2440968a dataFolder=plugins\ProtocolLib classLoader=org.bukkit.plugin.java.PluginClassLoader@77318c11 naggable=true newConfig=YamlConfiguration[path='', root='YamlConfiguration'] configFile=plugins\ProtocolLib\config.yml logger=org.bukkit.plugin.PluginLogger@56ab9758 ] Version: ProtocolLib v4.8.0 Java Version: 19.0.1 Server: 3652-Spigot-19641c7-6aeb5e4 (MC: 1.19.3)

Invalid plugin version, read spigot page to get the correct build 👀
