### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by silkypanda** [dmulloy2/ProtocolLib#2155]
<html>
<body>

Stack Trace:
--
278 | java.lang.ExceptionInInitializerError
279 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
280 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
281 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
282 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
283 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
284 | at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
285 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
286 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
287 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
288 | at java.base/java.lang.Thread.run(Unknown Source)
289 | Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
290 | fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}],
291 | methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
292 | constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
293 | }}
294 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
295 | at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
296 | at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
297 | at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
298 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
299 | at ProtocolLib.jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
300 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
301 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
302 | at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
303 | at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
304 | ... 10 more
305 | Dump:
306 | Sender:
307 | com.comphenix.protocol.ProtocolLib@78f9008c[
308 | statistics=<null>
309 | backgroundCompiler=<null>
310 | packetTask=-1
311 | tickCounter=0
312 | unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@282130d9
313 | configExpectedMod=-1
314 | updater=com.comphenix.protocol.updater.SpigotUpdater@7a351273
315 | redirectHandler=<null>
316 | commandProtocol=<null>
317 | commandPacket=<null>
318 | commandFilter=<null>
319 | packetLogging=<null>
320 | skipDisable=false
321 | isEnabled=true
322 | loader=org.bukkit.plugin.java.JavaPluginLoader@2d61e17e
323 | server=CraftServer{serverName=Paper,serverVersion=git-Paper-386,minecraftVersion=1.19.3}
324 | file=plugins/ProtocolLib.jar
325 | description=org.bukkit.plugin.PluginDescriptionFile@349617d1
326 | dataFolder=plugins/ProtocolLib
327 | classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
328 | naggable=true
329 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
330 | configFile=plugins/ProtocolLib/config.yml
331 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@47646039
332 | ]
333 | Version:
334 | ProtocolLib v4.5.1
335 | Java Version:
336 | 17.0.4.1
337 | Server:
338 | git-Paper-386 (MC: 1.19.3)
339 |  
340 | [11:09:56] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.1

</body>
</html>Stack Trace:
  java.lang.ExceptionInInitializerError
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
  	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
  	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}], 
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}], 
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
  }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
  	at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
  	... 10 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@78f9008c[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@[282](https://aternos.org/log/#L282)130d9
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7a351273
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@2d61e17e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-386,minecraftVersion=1.19.3}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@349617d1
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@47646039
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    17.0.4.1
  Server:
    git-Paper-386 (MC: 1.19.3)

[11:09:56] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.1

**Comment by Jeppa** [comment]
> ProtocolLib v4.5.1

Serious????
Even latest release 4.8.0 is NOT working with 1.19.3 !
You need to update to latest dev build! (612)
