### ISSUE TITLE
Getting connection lost when typing into chat.

### ISSUE THREAD

**Issue by hotrog2** [dmulloy2/ProtocolLib#2166]
- [ ] This issue is not solved in a development build

**Describe the bug**
When I type into chat I instantly get connection lost and get an error in my console. I put the error in the **Additional context** spot

**To Reproduce**
1. Log in
2. Type anything into chat

**Expected behavior**
To be able to chat?

**Screenshots**

**Version Info**
ProtocolLib Dump
Timestamp: 02/11/23 13:38:25

ProtocolLib Version: ProtocolLib v5.0.0-SNAPSHOT-b612
Bukkit Version: 1.19.3-R0.1-SNAPSHOT
Server Version: git-Purpur-1912 (MC: 1.19.3)
Java Version: 18.0.2.1

ProtocolLib: com.comphenix.protocol.ProtocolLib@24b47a43[
  statistics=com.comphenix.protocol.metrics.Statistics@58e5f86a
  packetTask=9
  tickCounter=7620
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@63e87d34
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@58262326
  commandProtocol=com.comphenix.protocol.CommandProtocol@2f77b6e0
  commandPacket=com.comphenix.protocol.CommandPacket@fd67fe7
  commandFilter=com.comphenix.protocol.CommandFilter@69100a36
  packetLogging=com.comphenix.protocol.PacketLogging@c62b21
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@12144d6f
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1912,minecraftVersion=1.19.3}
  file=plugins\ProtocolLib-5.0.0-SNAPSHOT.jar
  description=org.bukkit.plugin.PluginDescriptionFile@4729cfd1
  dataFolder=plugins\ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.0.0-SNAPSHOT-b612, pluginEnabled=true, url=plugins\ProtocolLib-5.0.0-SNAPSHOT.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins\ProtocolLib\config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@46482fac
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@616273b1[
  plugin=ProtocolLib v5.0.0-SNAPSHOT-b612
  server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1912,minecraftVersion=1.19.3}
  reporter=com.comphenix.protocol.ProtocolLib$1@68bc6f0b
  minecraftVersion=(MC: 1.19.3)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@25aff7f1
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@229d99a7
  inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@501089be
  outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5bdf6080
  registeredListeners=[PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=RealisticSeasons, sending=ListeningWhitelist[priority=NORMAL, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=32]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Spartan, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=50]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@1151475
  playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@4f0be551
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@1b02c877
  debug=false
  closed=false
  injected=true
]

Listeners:
net.citizensnpcs.ProtocolLibListener$2@6a229033[
  plugin=Citizens v2.0.30-SNAPSHOT (build 2888)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41]], gamephase=PLAYING, options=[]]
]
me.casperge.realisticseasons.event.ChunkPacketEventProtocolLib1_19_R2$1@be7293f[
  plugin=RealisticSeasons v10.3.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=32]], gamephase=PLAYING, options=[]]
]
net.citizensnpcs.ProtocolLibListener$1@2adc5696[
  plugin=Citizens v2.0.30-SNAPSHOT (build 2888)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]]
]
me.vagdedes.spartan.f.a.n$1@3d9dcac3[
  bi=9=packets
  plugin=Spartan vPhase 494
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_PLACE[class=PacketPlayInBlockPlace, id=50]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
RealisticSeasons by []
Spartan by [Evangelos Dedes @Vagdedes]
Citizens by [fullwall]

**Additional context**
[13:34:38 ERROR]: Packet encoding of packet ID 78 threw (skippable? false)
java.lang.ClassCastException: class net.minecraft.network.syncher.DataWatcher$Item cannot be cast to class net.minecraft.network.syncher.DataWatcher$b (net.minecraft.network.syncher.DataWatcher$Item and net.minecraft.network.syncher.DataWatcher$b are in unnamed module of loader java.net.URLClassLoader @66cd51c3)
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:17) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[purpur-1.19.3.jar:git-Purpur-1912]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[purpur-1.19.3.jar:git-Purpur-1912]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:428) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by hotrog2** [comment]
After some testing. I have figured out the issue. If you use messageoverhead make sure you update it....
