### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by Rustxzz** [dmulloy2/ProtocolLib#2169]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

Nothing really to click on, when i restart the server this happens:
|
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)

  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)

  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)

  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)

  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)

  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)

  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)

  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)

  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)

  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)

  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

  	at java.base/java.lang.Thread.run(Thread.java:833)

  Dump:

  Parameters: 

    io.netty.buffer.PooledUnsafeDirectByteBuf@4c066827[

      memoryAddress=140648703374752

      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1b20d194

      chunk=Chunk(2d9af7b7: 24%, 966656/4194304)

      handle=2814779831877632

      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]

      offset=40960

      length=26

      maxLength=32

      cache=io.netty.buffer.PoolThreadCache@277c1d62

      tmpNioBuf=<null>

      allocator=PooledByteBufAllocator(directByDefault: true)

      refCnt=2

      readerIndex=26

      writerIndex=26

      markedReaderIndex=0

      markedWriterIndex=0

      maxCapacity=2147483647

    ]

    manager:

      com.comphenix.protocol.injector.PacketFilterManager@19970db7[

        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@69cf86f3

        packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]]]

        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@4fee7d3f

        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5bce715f

        inputBufferedPackets=[]

        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7a153524

        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6f78dc8b

        hasClosed=false

        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}

        reporter=com.comphenix.protocol.ProtocolLib$1@53c343de

        server=CraftServer{serverName=Paper,serverVersion=git-Paper-346,minecraftVersion=1.19.3}

        library=ProtocolLib v4.8.0

        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@28c02234

        knowsServerPackets=true

        knowsClientPackets=true

        phaseLoginCount=0

        phasePlayingCount=1

        packetCreation=false

        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@66128a53

        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4e36bd85

        hasRecycleDistance=true

        minecraftVersion=(MC: 1.19.3)

        debug=false

      ]

  Sender:

    com.comphenix.protocol.injector.netty.ChannelInjector@762b670e[

      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception

      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception

      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1cfe776e

      player=CraftPlayer{name=Rustxz}

      updated=<null>

      playerName=Rustxz

      playerConnection=<null>

      networkManager=net.minecraft.network.NetworkManager@41524176

      originalChannel=[id: 0x2591f22e, L:/240.4.16.106:25575 - R:/240.4.92.79:45892]

      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@41524176, previous=[id: 0x2591f22e, L:/240.4.16.106:25575 - R:/240.4.92.79:45892], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@7cdfacba, previousLoaded=true, currentSet=true, forceAccess=true]

      packetMarker={}

      currentEvent=<null>

      finalEvent=<null>

      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@51e1a738

      vanillaDecoder=net.minecraft.network.PacketDecoder@26b0583

      vanillaEncoder=net.minecraft.network.PacketEncoder@402b966b

      finishQueue=[]

      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@66128a53

      processor=com.comphenix.protocol.injector.NetworkProcessor@1d94ffd5

      injected=true

      closed=false

      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)

      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@5ac62fed

      singleDecode=false

      first=true

      firedChannelRead=false

      selfFiredChannelRead=true

      decodeState=1

      discardAfterReads=16

      numReads=0

      added=true

    ]

  Version:

    ProtocolLib v4.8.0

  Java Version:

    17.0.1

  Server:

    git-Paper-346 (MC: 1.19.3)

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
