### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by XLEBXT** [dmulloy2/ProtocolLib#2171]
When installing the plugin on the server, an error came out

File dump:
ProtocolLib Dump
Timestamp: 02/15/23 10:42:39

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.2-R0.1-SNAPSHOT
Server Version: git-Paper-307 (MC: 1.19.2)
Java Version: 17.0.6

ProtocolLib: com.comphenix.protocol.ProtocolLib@7746efb9[
  statistics=com.comphenix.protocol.metrics.Statistics@6887a511
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@73605251
  packetTask=7
  tickCounter=49764
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1db17136
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@7dcba8b1
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@3db0ab96
  commandProtocol=com.comphenix.protocol.CommandProtocol@684a3e1c
  commandPacket=com.comphenix.protocol.CommandPacket@19490b9e
  commandFilter=com.comphenix.protocol.CommandFilter@3967a626
  packetLogging=com.comphenix.protocol.PacketLogging@1b34687
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@38b03273
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@69f4db00
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@76baf2d3
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@36008e6d[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1db17136
  packetListeners=[PacketAdapter[plugin=emotecraft, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=MyCommand, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1b05ee4
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@738b6939
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@414af2c3
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@57e4131d
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@5420207b
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6a8070d7
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=2
  phasePlayingCount=6
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@fbd999f
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4da732fb
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.2)
  debug=false
]

Listeners:
io.github.kosmx.emotes.bukkit.BukkitWrapper$1@14a04cd0[
  plugin=emotecraft v2.2.5
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]]
]
litebans.iA@78005d32[
  e=litebans.dj@30c3beda
  c=LiteBans v2.10.4
  plugin=LiteBans v2.10.4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
litebans.fk@5e80b866[
  g=litebans.dl@2c432fab
  c=litebans.dx@1209a1de
  d=litebans.dj@30c3beda
  f=litebans.d1@676d4067
  b=LiteBans v2.10.4
  plugin=LiteBans v2.10.4
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
it.emmerrei.mycommand.signmenu.SignMenuFactory$1@6f158bc2[
  plugin=MyCommand v5.7.3
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.myzelyam.supervanish.visibility.hiders.modules.TabCompleteModule@24edcc25[
  hider=de.myzelyam.supervanish.visibility.hiders.PreventionHider@7ffe57ac
  plugin=SuperVanish v6.2.15
  errorLogged=false
  plugin=SuperVanish v6.2.15
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]]
]
de.myzelyam.supervanish.visibility.ServerListPacketListener@59d75faf[
  plugin=SuperVanish v6.2.15
  plugin=SuperVanish v6.2.15
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
SuperVanish by [MyzelYam]
LiteBans by [Ruan]
emotecraft by [KomsX]
MyCommand by [emmerrei (ivanfromitaly)]

We will be glad if you help

**Comment by XLEBXT** [comment]
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@4bb911aa[
      memoryAddress=140735475678352
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@3201ad61
      chunk=Chunk(199646b1: 35%, 1441792/4194304)
      handle=23643962468204544
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=344064
      length=34
      maxLength=48
      cache=io.netty.buffer.PoolThreadCache@4fdb9ea8
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@19a74be9[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@70ce2acd
        packetListeners=[PacketAdapter[plugin=emotecraft, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=MyCommand, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Images, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2c9a67e4
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@376f36f4
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@14b4dbf3
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@152d13ea
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@6af7e3ec
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-300,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@16b89cfc
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=7
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@458968da
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@15529496
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@15e51459[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@41f06a72
      player=CraftPlayer{name=its_Darik}
      updated=<null>
      playerName=its_Darik
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@8918890
      originalChannel=[id: 0x76837476, L:/172.18.0.4:49159 - R:/172.18.0.1:42750]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@8918890, previous=[id: 0x76837476, L:/172.18.0.4:49159 - R:/172.18.0.1:42750], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@34f332d9, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@909afc2
      vanillaDecoder=net.minecraft.network.PacketDecoder@d58637b
      vanillaEncoder=net.minecraft.network.PacketEncoder@3121930d
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@458968da
      processor=com.comphenix.protocol.injector.NetworkProcessor@585ad1ea
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@42c3922b
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-300 (MC: 1.19.2)

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
