### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JustSomeDude69** [dmulloy2/ProtocolLib#2191]
Version:
    ProtocolLib v4.8.0
  Java Version:
    18.0.2
  Server:
    git-Paper-220 (MC: 1.19.2)

[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@5dd6e631[
      memoryAddress=3062809047136
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@667a72e9
      chunk=Chunk(1bbeb078: 28%, 1146880/4194304)
      handle=21392128294780929
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=311328
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@48f229bd
      tmpNioBuf=java.nio.DirectByteBuffer[pos=311360 lim=311360 cap=4194304]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@5a8faf28[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@aab22b6
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=LOW, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], ABILITIES[class=ClientboundPlayerChatHeaderPacket, id=50], PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@7c33ee48, PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Orebfuscator, sending=ListeningWhitelist[priority=NORMAL, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2e3cc082
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@60c6ddfa
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5c0a063e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@af52948
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@3c3322f7
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-220,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@38a4dae0
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=8
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@74c7d95b
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2fecf658
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@5cb23497[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@6719dc14
      player=CraftPlayer{name=Random_Dude46}
      updated=<null>
      playerName=Random_Dude46
      playerConnection=net.minecraft.server.network.PlayerConnection@1589380c
      networkManager=net.minecraft.network.NetworkManager@aa17dad
      originalChannel=[id: 0x7c6a3614, L:/127.0.0.1:25568 - R:/127.0.0.1:1239]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@aa17dad, previous=[id: 0x7c6a3614, L:/127.0.0.1:25568 - R:/127.0.0.1:1239], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@10dc7a4b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@654e6fdd
      vanillaDecoder=net.minecraft.network.PacketDecoder@452b773a
      vanillaEncoder=net.minecraft.network.PacketEncoder@eec3a40
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@74c7d95b
      processor=com.comphenix.protocol.injector.NetworkProcessor@75bb87e7
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1aea9d2a
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
Appears whenever i open my server

**Comment by Jeppa** [comment]
Could not copy 'plugins\update\ProtocolLib.jar' to 'plugins\ProtocolLib.jar'

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
