### ISSUE TITLE
cant connect to database

### ISSUE THREAD

**Issue by soapchan** [dmulloy2/ProtocolLib#2192]
- [ ] This issue is not solved in a development build

**Describe the bug**
The plugin cannot connect to the database, ive messed around with configs alot. it keeps saying datasync in progress whenever i try to do ANYTHING on my servers.
the console said to open a support ticket here, so i did

my full bug report is 
[04:31:28 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at 1997 - ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at 1997 - ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at 1997 - ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at 1997 - ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at 1997 - ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2db09cb4[
      memoryAddress=140486550327904
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@11a13b19
      chunk=Chunk(476990f1: 1%, 32768/4194304)
      handle=1125929971613696
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16384
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@4df714bd
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@608a38c4[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@6840e7d9
        packetListeners=[PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=54]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedEnchantments, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AdvancedEnchantments, sending=ListeningWhitelist[priority=HIGHEST, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@12037e77
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3888e4f3
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@9f5b73e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6664e7f6
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/1997 - ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@6f9dcd8b
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-384,minecraftVersion=1.19.3}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@34a51a87
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1008cff7
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1dbff7c4
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.3)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@338f6dff[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@6425bb6c
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@66350747
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@31659bdc
      originalChannel=[id: 0xe59e5eda, L:/172.31.1.4:25565 - R:/172.31.1.1:10412]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@31659bdc, previous=[id: 0xe59e5eda, L:/172.31.1.4:25565 - R:/172.31.1.1:10412], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@361ee846, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@78dfdefd
      vanillaDecoder=net.minecraft.network.PacketDecoder@65f90141
      vanillaEncoder=net.minecraft.network.PacketEncoder@2f126e46
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1008cff7
      processor=com.comphenix.protocol.injector.NetworkProcessor@68a1ec20
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@6c5dfdb8
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    18.0.2.1
  Server:
    git-Paper-384 (MC: 1.19.3)

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189
