### ISSUE TITLE
File is already in use

### ISSUE THREAD

**Issue by condblock** [dmulloy2/ProtocolLib#2193]
```
[17:45:35` ERROR]: [io.papermc.paper.plugin.provider.source.DirectoryProviderSource] Error loading plugin: Directory 'plugins\ProtocolLib.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins\ProtocolLib.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$2(DirectoryProviderSource.java:32) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:30) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.Main.main(Main.java:119) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Could not copy 'plugins\update\ProtocolLib.jar' to 'plugins\ProtocolLib.jar' in update plugin process
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:95) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[purpur-1.19.3.jar:git-Purpur-1920]
        ... 19 more
Caused by: java.lang.RuntimeException: Could not copy 'plugins\update\ProtocolLib.jar' to 'plugins\ProtocolLib.jar' in update plugin process
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:85) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[purpur-1.19.3.jar:git-Purpur-1920]
        ... 19 more
Caused by: java.nio.file.FileSystemException: plugins\ProtocolLib.jar: 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:171) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:284) ~[?:?]
        at java.nio.file.Files.copy(Files.java:1305) ~[?:?]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:83) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[purpur-1.19.3.jar:git-Purpur-1920]
        ... 19 more
```
it saids ProtocolLib.jar is already in use but other plugins are working. 

ProtocolLib version: #614
Bukkit version: git-Purpur-1920 (MC: 1.19.3)

I restarted my computer and tried again, but it still not working.

**Comment by Jeppa** [comment]
>..Could not copy 'plugins\update\ProtocolLib.jar' to 'plugins\ProtocolLib.jar'

maybe copy it by hand?
