### ISSUE TITLE
Didn't work.

### ISSUE THREAD

**Issue by windy664** [dmulloy2/ProtocolLib#2195]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**
1. Go to 'get least plugin'
2. Click on 'cardboard'
3. Scroll down to 'coosle'

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
the least

**Additional context**

` Loading ProtocolLib v4.8.0
[23:29:19] [Server thread/FATAL]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3434)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2536)
        at com.comphenix.net.bytebuddy.description.method.MethodList$ForLoadedMethods.<init>(MethodList.java:148)
        at com.comphenix.net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredMethods(TypeDescription.java:8801)
        at com.comphenix.net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.getDeclaredMethods(TypeDescription.java:3635)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:717)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:715)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:715)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:715)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:715)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:715)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:679)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:715)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:637)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:519)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:472)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:213)
        at com.comphenix.net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3661)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3899)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:186)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:403)
        at net.minecraft.class_3176.handler$zza000$init(class_3176.java:760)
        at net.minecraft.class_3176.method_3823(class_3176.java:160)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.ClassNotFoundException: class net.md_5.bungee.api.chat.BaseComponent is currently restricted from being loaded
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:306)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 39 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5d4a6328[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@48c568e1
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@461801f2
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@59bd7db5
      server=CraftServer{serverName=Cardboard,serverVersion=git-Cardboard-UNKNOWN,minecraftVersion=1.18.1}
      file=plugins\ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@53e2d5c3
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@15f656b2
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.javazilla.bukkitfabric.BukkitLogger@61460b63
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    18.0.2.1
  Server:
    git-UNKNOWN (MC: 1.18.1)

[23:29:19] [Server thread/INFO]: Loading TrMenu v3.1.18
[23:29:19] [Server thread/INFO]: 搂r
[23:29:19] [Server thread/INFO]: 搂7姝ｅ湪鍔犺浇 搂3Tr搂bMenu 搂f搂lPremium... 搂8git-UNKNOWN (MC: 1.18.1)
[23:29:19] [Server thread/INFO]: 搂r
[23:29:19] [Server thread/INFO]: Enabling ProtocolLib v4.8.0
2月 25, 2023 11:29:19 下午 com.comphenix.protocol.ProtocolLib onEnable
严重: ******************************************************
2月 25, 2023 11:29:19 下午 com.comphenix.protocol.ProtocolLib onEnable
严重: *** ProtocolLib does not support plugin reloaders! ***
2月 25, 2023 11:29:19 下午 com.comphenix.protocol.ProtocolLib onEnable
严重: *** Please use the built-in reload command!        ***
2月 25, 2023 11:29:19 下午 com.comphenix.protocol.ProtocolLib onEnable
严重: ******************************************************
[23:29:19] [Server thread/INFO]: Disabling ProtocolLib v4.8.0
[23:29:19] [Server thread/INFO]:
[23:29:19] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:29:19] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:29:19] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.`

**Comment by Jeppa** [comment]
What is the server version?
>git-UNKNOWN (MC: 1.18.1)

looks a little strange to me...

**Comment by suiheng** [comment]
> What is the server version?
> 
> > git-UNKNOWN (MC: 1.18.1)
> 
> looks a little strange to me...

That's cardboard :
https://cardboardpowered.org/download/

**Comment by Jeppa** [comment]
That's the problem... cardboard is not spigot/paper... only ca. 60% ready...
You should ask @ cardboard to fix this bug...
