### ISSUE TITLE
Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart

### ISSUE THREAD

**Issue by ezTxmMC** [dmulloy2/ProtocolLib#2204]
- [ ] This issue is not solved in a development build

**Describe the bug**
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)

**Version Info**
https://pastebin.com/keb9DBCy

**Comment by Witheredpicaxe** [comment]
im getting this same issue

**Comment by Witheredpicaxe** [comment]
04.03 08:13:30 [Server] Netty Epoll Server IO #0/[WARN] [ProtocolLib] [DetailedErrorReporter] Internal exception count: 2048!
04.03 08:13:30 [Server] Netty Epoll Server IO #0/[INFO] Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@339f0981.
04.03 08:13:30 [Server] Netty Epoll Server IO #0/[ERROR] [ProtocolLib] INTERNAL [ERROR]: Unable to intercept a read client packet.
04.03 08:13:30 [Server] [INFO] If this problem hasn't already been reported, please open a ticket
04.03 08:13:30 [Server] [INFO] at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
04.03 08:13:30 [Server] [INFO] Stack Trace:
04.03 08:13:30 [Server] [INFO] java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
04.03 08:13:30 [Server] [INFO] at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
04.03 08:13:30 [Server] [INFO] at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
04.03 08:13:30 [Server] [INFO] at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
04.03 08:13:30 [Server] [INFO] at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
04.03 08:13:30 [Server] [INFO] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
04.03 08:13:30 [Server] [INFO] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
04.03 08:13:30 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
04.03 08:13:30 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
04.03 08:13:30 [Server] [INFO] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
04.03 08:13:30 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:831)
04.03 08:13:30 [Server] [INFO] Dump:
04.03 08:13:30 [Server] [INFO] Parameters: 
04.03 08:13:30 [Server] [INFO] io.netty.buffer.PooledUnsafeDirectByteBuf@abc3a44[
04.03 08:13:30 [Server] [INFO] memoryAddress=140259874711456
04.03 08:13:30 [Server] [INFO] recyclerHandle=io.netty.util.Recycler$DefaultHandle@4dec6111
04.03 08:13:30 [Server] [INFO] chunk=Chunk(314c3e24: 15%, 589824/4194304)
04.03 08:13:30 [Server] [INFO] handle=4503629692141568
04.03 08:13:30 [Server] [INFO] memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
04.03 08:13:30 [Server] [INFO] offset=65536
04.03 08:13:30 [Server] [INFO] length=26
04.03 08:13:30 [Server] [INFO] maxLength=32
04.03 08:13:30 [Server] [INFO] cache=io.netty.buffer.PoolThreadCache@500fb450
04.03 08:13:30 [Server] [INFO] tmpNioBuf=<null>
04.03 08:13:30 [Server] [INFO] allocator=PooledByteBufAllocator(directByDefault: true)
04.03 08:13:30 [Server] [INFO] refCnt=2
04.03 08:13:30 [Server] [INFO] readerIndex=26
04.03 08:13:30 [Server] [INFO] writerIndex=26
04.03 08:13:30 [Server] [INFO] markedReaderIndex=0
04.03 08:13:30 [Server] [INFO] markedWriterIndex=0
04.03 08:13:30 [Server] [INFO] maxCapacity=2147483647
04.03 08:13:30 [Server] [INFO] ]
04.03 08:13:30 [Server] [INFO] manager:
04.03 08:13:30 [Server] [INFO] com.comphenix.protocol.injector.PacketFilterManager@2ac1d340[
04.03 08:13:30 [Server] [INFO] unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@196a91b6
04.03 08:13:30 [Server] [INFO] packetListeners=[PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[RESPAWN[class=PacketPlayOutRespawn, id=61]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], AUTO_RECIPE[class=ClientboundPlayerChatPacket, id=49]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], AUTO_RECIPE[class=ClientboundPlayerChatPacket, id=49]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[MOUNT[class=PacketPlayOutMount, id=84]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[RECIPE_UPDATE[class=PacketPlayOutRecipeUpdate, id=102]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=LOWEST, packets=[RECIPES[class=PacketPlayOutRecipes, id=57]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=MONITOR, packets=[RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=60]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]]]
04.03 08:13:30 [Server] [INFO] packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@58795891
04.03 08:13:30 [Server] [INFO] playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6a4866c6
04.03 08:13:30 [Server] [INFO] inputBufferedPackets=[]
04.03 08:13:30 [Server] [INFO] recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4e37f31c
04.03 08:13:30 [Server] [INFO] sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@31d2c4d
04.03 08:13:30 [Server] [INFO] hasClosed=false
04.03 08:13:30 [Server] [INFO] classLoader=org.bukkit.plugin.java.PluginClassLoader@10781063
04.03 08:13:30 [Server] [INFO] reporter=com.comphenix.protocol.ProtocolLib$1@38e57bd9
04.03 08:13:30 [Server] [INFO] server=CraftServer{serverName=CraftBukkit,serverVersion=3668-Spigot-454acb7-e8010dc,minecraftVersion=1.19.3}
04.03 08:13:30 [Server] [INFO] library=ProtocolLib v4.8.0
04.03 08:13:30 [Server] [INFO] asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@23aef2e4
04.03 08:13:30 [Server] [INFO] knowsServerPackets=true
04.03 08:13:30 [Server] [INFO] knowsClientPackets=true
04.03 08:13:30 [Server] [INFO] phaseLoginCount=0
04.03 08:13:30 [Server] [INFO] phasePlayingCount=13
04.03 08:13:30 [Server] [INFO] packetCreation=false
04.03 08:13:30 [Server] [INFO] nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@70fb2e26
04.03 08:13:30 [Server] [INFO] pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@775e4c20
04.03 08:13:30 [Server] [INFO] hasRecycleDistance=true
04.03 08:13:30 [Server] [INFO] minecraftVersion=(MC: 1.19.3)
04.03 08:13:30 [Server] [INFO] debug=false
04.03 08:13:30 [Server] [INFO] ]
04.03 08:13:30 [Server] [INFO] Sender:
04.03 08:13:30 [Server] [INFO] com.comphenix.protocol.injector.netty.ChannelInjector@339f0981[
04.03 08:13:30 [Server] [INFO] decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
04.03 08:13:30 [Server] [INFO] encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
04.03 08:13:30 [Server] [INFO] factory=com.comphenix.protocol.injector.netty.InjectionFactory@197604b9
04.03 08:13:32 [Server] [INFO] player=CraftPlayer{name=WrecklessVR}
04.03 08:13:32 [Server] [INFO] updated=<null>
04.03 08:13:32 [Server] [INFO] playerName=WrecklessVR
04.03 08:13:32 [Server] [INFO] playerConnection=<null>
04.03 08:13:32 [Server] [INFO] networkManager=net.minecraft.network.NetworkManager@76151ec3
04.03 08:13:32 [Server] [INFO] originalChannel=[id: 0xdd039f49, L:/172.17.0.23:25565 - R:/198.178.119.204:53679]
04.03 08:13:32 [Server] [INFO] channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@76151ec3, previous=[id: 0xdd039f49, L:/172.17.0.23:25565 - R:/198.178.119.204:53679], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@108d5097, previousLoaded=true, currentSet=true, forceAccess=true]
04.03 08:13:32 [Server] [INFO] packetMarker={}
04.03 08:13:32 [Server] [INFO] currentEvent=<null>
04.03 08:13:32 [Server] [INFO] finalEvent=<null>
04.03 08:13:32 [Server] [INFO] unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@73df6aa9
04.03 08:13:32 [Server] [INFO] vanillaDecoder=net.minecraft.network.PacketDecoder@2de29117
04.03 08:13:32 [Server] [INFO] vanillaEncoder=net.minecraft.network.PacketEncoder@5acbeb6f
04.03 08:13:32 [Server] [INFO] finishQueue=[]
04.03 08:13:32 [Server] [INFO] channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@70fb2e26
04.03 08:13:32 [Server] [INFO] processor=com.comphenix.protocol.injector.NetworkProcessor@28babdc5
04.03 08:13:32 [Server] [INFO] injected=true
04.03 08:13:32 [Server] [INFO] closed=false
04.03 08:13:32 [Server] [INFO] cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
04.03 08:13:32 [Server] [INFO] cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@2743f36e
04.03 08:13:32 [Server] [INFO] singleDecode=false
04.03 08:13:32 [Server] [INFO] first=true
04.03 08:13:32 [Server] [INFO] firedChannelRead=false
04.03 08:13:32 [Server] [INFO] selfFiredChannelRead=true
04.03 08:13:32 [Server] [INFO] decodeState=1
04.03 08:13:32 [Server] [INFO] discardAfterReads=16
04.03 08:13:32 [Server] [INFO] numReads=0
04.03 08:13:32 [Server] [INFO] added=true
04.03 08:13:32 [Server] [INFO] ]
04.03 08:13:32 [Server] [INFO] Version:
04.03 08:13:32 [Server] [INFO] ProtocolLib v4.8.0
04.03 08:13:32 [Server] [INFO] Java Version:
04.03 08:13:32 [Server] Startup17
04.03 08:13:32 [Server] [INFO] Server:
04.03 08:13:32 [Server] Startup3668-Spigot-454acb7-e8010dc (MC: 1.19.3)
04.03 08:37:10 [Disconnect] User WrecklessVR has disconnected, reason: Disconnected
04.03 08:37:10 [Server] Server thread/[INFO] WrecklessVR left the game
04.03 22:17:22 [PebbleHost] Itswrecklessvr@gmail.com ran command: iazip
04.03 22:17:23 [Server] Server thread/[WARN] [ItemsAdder] Plugin is still loading... Please wait before using /iazip
