### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by DreamMeA** [dmulloy2/ProtocolLib#2216]
How do I fix this?
About 3-4 months ago I was able to use it normally.
but this time it's a bug
I use : paper-1.10.2-918
Java : 8
ProtocolLib : Version 4.8.0

[22:59:03] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[22:59:04] [Server thread/ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
   If this problem hasn't already been reported, please open a ticket
   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
   Stack Trace:
   java.lang.ExceptionInInitializerError
   at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
   at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
   at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
   at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
   at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
   at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:304)
   at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:207)
   at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590)
   at java.base/java.lang.Thread.run(Thread.java:1589)
   Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java. lang" to unnamed module @6b380060
   at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
   at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
   at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
   at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
   at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
   at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
   at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
   at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
   at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
   ... 9 more
   Dump:
   Parameters:
     [NULL]
   Sender:
     com.comphenix.protocol.ProtocolLib@37564ad9[
       statistics=<null>
       backgroundCompiler=<null>
       packetTask=-1
       tickCounter=0
       unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@560c4b9f
       configExpectedMod=-1
       updater=com.comphenix.protocol.updater.SpigotUpdater@5389d305
       redirectHandler=<null>
       commandProtocol=<null>
       commandPacket=<null>
       commandFilter=<null>
       packetLogging=<null>
       skipDisable=false
       isEnabled=false
       loader=org.bukkit.plugin.java.JavaPluginLoader@72af611d
       server=CraftServer{serverName=Paper,serverVersion=git-Paper-918,minecraftVersion=1.10.2}
       file=plugins\ProtocolLib (1).jar
       description=org.bukkit.plugin.PluginDescriptionFile@64248323
       dataFolder=plugins\ProtocolLib
       classLoader=org.bukkit.plugin.java.PluginClassLoader@3ca89aa6
       naggable=true
       ebean=<null>
       newConfig=YamlConfiguration[path='', root='YamlConfiguration']
       configFile=plugins\ProtocolLib\config.yml
       logger=org.bukkit.plugin.PluginLogger@619112e8
     ]
   Version:
     ProtocolLib v4.8.0
   Java Version:
     19.0.2
   Server:
     git-paper-918 (MC: 1.10.2)

**Comment by SnowY4you** [comment]
It seems everyone that is using paper and 1.19.3 is having this issue, but no solution yet. I think we have to start thinking of alternatives. As it is not only ProtocolLib, but also, BKCommonLib or any kind of Lib that is bugging out.

**Comment by Jeppa** [comment]
He is not using 1.19.3.
But Java 19 might be the problem...

**Comment by SnowY4you** [comment]
I don't know, I checked my Java and it is: (build 1.8.0_351-b10)

**Comment by Jeppa** [comment]
@SnowY4you: If your Java is 1.8 and MC is 1.19.3... i hope you are NOT using ProtocolLib 4.8.0... 
Btw: paper 1.19.3 and Java 1.8.x ? That's not possible...

**Comment by SnowY4you** [comment]
@Jeppa Yes, sorry. Acting like a dumb blond! Don't know why I even looked at Java on my pc when the server is actually not there :p
