### ISSUE TITLE
Error: Unable to intercept a read client packet

### ISSUE THREAD

**Issue by RocciPix** [dmulloy2/ProtocolLib#2222]
Hello,

since a Serverrestart today at 4 p.m., I've been getting the following Error-Message via ProtocolLib, which spams the Console:

[16:18:29 ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Thread.java:833)
Dump:
Parameters:
io.netty.buffer.PooledUnsafeDirectByteBuf@62373bcc[
memoryAddress=23120551742496
recyclerHandle=NOOP_HANDLE
chunk=Chunk(42a1f79d: 1%, 24576/4194304)
handle=1125929971613696
memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
offset=16384
length=256
maxLength=256
cache=io.netty.buffer.PoolThreadCache@7147865a
tmpNioBuf=<null>
allocator=PooledByteBufAllocator(directByDefault: true)
refCnt=2
readerIndex=20
writerIndex=20
markedReaderIndex=0
markedWriterIndex=0
maxCapacity=2147483647
]
manager:
com.comphenix.protocol.injector.PacketFilterManager@1264904b[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@d35e7d8
packetListeners=[PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@621fe4cc, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@457192e2, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@15f4ba4c, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@189be503, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@fed7ba4, PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@6f42118e]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@4b49ec31
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4cc0a7a0
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7a9090bb
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5839b316
hasClosed=false
classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
reporter=com.comphenix.protocol.ProtocolLib$1@5c95e444
server=CraftServer{serverName=Paper,serverVersion=git-Paper-442,minecraftVersion=1.19.3}
library=ProtocolLib v4.8.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6b4afa96
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=9
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@298fdc97
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@25528d49
hasRecycleDistance=true
minecraftVersion=(MC: 1.19.3)
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ChannelInjector@740766f4[
decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
factory=com.comphenix.protocol.injector.netty.InjectionFactory@53c2ef10
player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@2f35dae3
updated=<null>
playerName=<null>
playerConnection=<null>
networkManager=net.minecraft.network.NetworkManager@6265cd87
channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@6265cd87, current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6022111e, previousLoaded=true, currentSet=true, forceAccess=true]
packetMarker={}
currentEvent=<null>
finalEvent=<null>
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@61c12d3b
vanillaDecoder=net.minecraft.network.PacketDecoder@2d04cd71
vanillaEncoder=net.minecraft.network.PacketEncoder@6d8fc9dc
finishQueue=[]
channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@298fdc97
processor=com.comphenix.protocol.injector.NetworkProcessor@7595c1e6
injected=true
closed=false
cumulation=PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 256)
cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@6b1b7f87
singleDecode=false
first=true
firedChannelRead=false
selfFiredChannelRead=true
decodeState=1
discardAfterReads=16
numReads=0
added=true
]
Version:
ProtocolLib v4.8.0
Java Version:
17.0.1
Server:
git-Paper-442 (MC: 1.19.3)

Does anyone know this error and what it can be?

**Comment by Jeppa** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2165#issuecomment-1426880189

**Comment by RocciPix** [comment]
Thanks Jeppa, i'll try it at next Restart
