### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Bud82jp** [dmulloy2/ProtocolLib#2225]
```
[15:38:52 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:651)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:584)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@e7868e1[
      memoryAddress=2499801075776
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6d228e4e
      chunk=Chunk(4ae26c35: 15%, 589824/4194304)
      handle=2251829878456320
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=32768
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@54fa994f
      tmpNioBuf=java.nio.DirectByteBuffer[pos=32949 lim=32949 cap=4194304]
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=171
      writerIndex=171
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4147089[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5dce37fa
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ServerListPlus, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=SecuredNetwork, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=62], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Negativity, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ABILITIES[class=PacketPlayInAbilities, id=25], ITEM_NAME[class=PacketPlayInItemName, id=32], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], PONG[class=ServerboundPongPacket, id=29], BEACON[class=PacketPlayInBeacon, id=36], TR_SEL[class=PacketPlayInTrSel, id=35], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], STRUCT[class=PacketPlayInStruct, id=42], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], SPECTATE[class=PacketPlayInSpectate, id=45], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], PING[class=PacketStatusInPing, id=1], START[class=PacketStatusInStart, id=0], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], Dynamic-ae2fe521-3d50-4393-ac74-37e719a2e40d[class=PacketPlayInClientCommand, id=4], Dynamic-2f1fcca0-760c-41b6-887a-1eb294a7a8a1[class=PacketPlayInChat, id=3], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], Dynamic-55199577-04c1-49dc-9717-5a5c3ea31683[class=PacketPlayInTabComplete, id=6], SETTINGS[class=PacketPlayInSettings, id=5], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=12], B_EDIT[class=PacketPlayInBEdit, id=11], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=16], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=14], USE_ENTITY[class=PacketPlayInUseEntity, id=13], GROUND[class=d, id=20], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayInPosition, id=17], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], PICK_ITEM[class=PacketPlayInPickItem, id=23], BOAT_MOVE[class=PacketPlayInBoatMove, id=22], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SCore, sending=ListeningWhitelist[priority=NORMAL, packets=[WORLD_PARTICLES[class=PacketPlayOutWorldParticles, id=36]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Negativity, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=101], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5dfeeded
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@25b58b86
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2823781
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2edfa1cc
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0-SNAPSHOT-b539, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@4e4b07f
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1858,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0-SNAPSHOT-b539
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1e29e2c0
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=4
        phasePlayingCount=9
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@173b9f23
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@50a0f6d
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@759d941[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@20bf9021
      player=CraftPlayer{name=Bud82jp}
      updated=<null>
      playerName=Bud82jp
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@3c41de0f
      originalChannel=[id: 0xf354609f, L:/127.0.0.1:25566 - R:/127.0.0.1:52196]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@3c41de0f, previous=[id: 0xf354609f, L:/127.0.0.1:25566 - R:/127.0.0.1:52196], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2c8ddc5a, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@6fd09539
      vanillaDecoder=net.minecraft.network.PacketDecoder@1a670f49
      vanillaEncoder=net.minecraft.network.PacketEncoder@45d044d6
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@173b9f23
      processor=com.comphenix.protocol.injector.NetworkProcessor@6cef0ba1
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 171, widx: 171, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4e505c32
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0-SNAPSHOT-b539
  Java Version:
    17.0.4
  Server:
    git-Purpur-1858 (MC: 1.19.2)

```

My console is being spammed with that

**Comment by Bud82jp** [comment]
AdvancedBan, Citizens, DeluxeHub, DeluxeTags, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GSit, HolographicDisplays, Insights, LuckPerms, mcMMO, Multiverse-Core, Negativity, OpenInv, PL-Hide, PlaceholderAPI, PlugManX (PlugMan), ProtocolLib, SCore, SecuredNetwork, ServerListPlus*, SimpleRename, Skulls, spark, SuperVanish, TAB, TerraformGenerator, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, WorldGuard

Version: ProtocolLib v4.8.0
    b=net.minecraft.network.protocol.status.ServerPing@7eb46c3a

**Comment by Jeppa** [comment]
And why are you using V4.8.0 with 1.19.x?
Since you run a snapshot, you should know how to update that to latest snapshot (or to a version that fit's your needs (buld 606 for 1.19.2) ....

**Comment by Bud82jp** [comment]
Because I'm using it from a server set up and they they clearly got it wrong srry for any inconvenience 😃 ---- On Fri, 10 Mar 2023 19:07:33 +0000  ***@***.***  wrote ----
And why are you using V4.8.0 with 1.19.x?
Since you run a snapshot, you should know how to update that to latest snapshot (or to a version that fit's your needs (buld 606 for 1.19.2) ....

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



If you use email or spam filter rules, be sure to add theprettys.co.uk to your safe list.



This email cannot be used to create a legal binding contract. Unauthorized use of it, its contents or attachments is prohibited. If you reply to this email, we may intercept emails to detect or protect against unauthorized use. We use proprietary software to encrypt and decrypt emails, and routinely monitor them and associated metadata (e.g. addresses and subject headings) to protect against the risk of misaddressed emails and to improve the accuracy of those decisions. This email is sent on behalf of The Pretty's if you’re anywhere else in the world. All rights reserved.

**Comment by Bud82jp** [comment]
Because I downloaded it from a server setup! So I didn't actually do it wrong 

Sorry for any inconvenience 😀
