### ISSUE TITLE
ProtocolLib v4.8.0

### ISSUE THREAD

**Issue by KageRyo** [dmulloy2/ProtocolLib#2237]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at net.minecraft.server.network.ServerConnection$1$1.channelRead(ServerConnection.java:150)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1122)
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417)
        at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.channelRead(HAProxyMessageDecoder.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@2f4dd21a[
      memoryAddress=140191021086688
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@5e07f0bb
      chunk=Chunk(55142b98: 1%, 32768/4194304)
      handle=1125929971613697
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16640
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@6c33b03a
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3582702c[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4441a4c6
        packetListeners=[PacketAdapter[plugin=ChatItem, sending=ListeningWhitelist[priority=LOWEST, packets=[CHAT[PLAY, SERVER, 15, classNames: [net.minecraft.network.protocol.game.PacketPlayOutChat, net.minecraft.network.protocol.game.ClientboundChatPacket, net.minecraft.network.play.server.SPacketChat] (unregistered)]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CraftGUI, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=ClientboundCustomChatCompletionsPacket, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ChatItem, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Negativity, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=101]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Negativity, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[B_EDIT[class=PacketPlayInBEdit, id=11], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=12], USE_ENTITY[class=PacketPlayInUseEntity, id=13], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=14], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=16], POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], Dynamic-cb7c1de9-3817-490e-985b-cf5da1fcfa7e[class=PacketPlayInChat, id=3], Dynamic-fa55afbb-4c4e-400d-a4f1-9df4170298b4[class=PacketPlayInClientCommand, id=4], SETTINGS[class=PacketPlayInSettings, id=5], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], START[class=PacketLoginInStart, id=0], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], PING[class=PacketStatusInPing, id=1], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], SPECTATE[class=PacketPlayInSpectate, id=45], USE_ITEM[class=PacketPlayInUseItem, id=46], START[class=PacketStatusInStart, id=0], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], TR_SEL[class=PacketPlayInTrSel, id=35], BEACON[class=PacketPlayInBeacon, id=36], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], STRUCT[class=PacketPlayInStruct, id=42], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], PONG[class=ServerboundPongPacket, id=29], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], Dynamic-3448108b-48b4-4bdc-823c-f355d3939253[class=PacketPlayInItemName, id=32], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], LOOK[class=PacketPlayInLook, id=19], GROUND[class=d, id=20], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], BOAT_MOVE[class=PacketPlayInBoatMove, id=22], PICK_ITEM[class=PacketPlayInPickItem, id=23], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], ABILITIES[class=PacketPlayInAbilities, id=25], BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@438030
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3711fe4b
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1134fb95
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@581a1ae1
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@44c443d2
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-448,minecraftVersion=1.19.3}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4ac1bae2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=6
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@67079d4c
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@600c3c1
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.3)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@61372e24[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@2b704794
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@73ee0ad0
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@4748d735
      originalChannel=[id: 0xb11f19a4, L:/172.18.0.3:25565 - R:/51.79.156.24:53260]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@4748d735, previous=[id: 0xb11f19a4, L:/172.18.0.3:25565 - R:/51.79.156.24:53260], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@1f0fc9f0, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@37cad63b
      vanillaDecoder=net.minecraft.network.PacketDecoder@45cd10c2
      vanillaEncoder=net.minecraft.network.PacketEncoder@327fb832
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@67079d4c
      processor=com.comphenix.protocol.injector.NetworkProcessor@3244c89a
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1f229510
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-448 (MC: 1.19.3)

**Comment by molor** [comment]
:/
> ProtocolLib v4.8.0

![image](https://user-images.githubusercontent.com/19989717/225833292-d3f3732d-5dc9-4800-9826-0cc9a9e74c37.png)
