### ISSUE TITLE
Error I get in console.

### ISSUE THREAD

**Issue by ecLipseTV** [dmulloy2/ProtocolLib#2243]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@69101a51[
      memoryAddress=139810849261440
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@19d5b4d0
      chunk=Chunk(652e0dc7: 25%, 1024000/4194304)
      handle=3377729785298956
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=52224
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@6088a050
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=2
      writerIndex=2
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@42474475[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2e89b78
        packetListeners=[PacketAdapter[plugin=ChatItem, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ChatItem, sending=ListeningWhitelist[priority=LOWEST, packets=[CHAT[PLAY, SERVER, 15, classNames: [net.minecraft.network.protocol.game.PacketPlayOutChat, net.minecraft.network.protocol.game.ClientboundChatPacket, net.minecraft.network.play.server.SPacketChat] (unregistered)]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@27f9dc7d
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5a1cef8b
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@22007c51
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@64f50032
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@d8622e5
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-307,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1198e4d7
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=2
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@587239b1
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@119b25b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@349fe12d[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@55a9edea
      player=CraftPlayer{name=ecLipsePlayssMC}
      updated=<null>
      playerName=ecLipsePlayssMC
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@5e23087a
      originalChannel=[id: 0x78b7f84b, L:/240.4.69.116:25575 - R:/240.4.94.31:56438]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@5e23087a, previous=[id: 0x78b7f84b, L:/240.4.69.116:25575 - R:/240.4.94.31:56438], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@30d1b91b, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@48f83aa3
      vanillaDecoder=net.minecraft.network.PacketDecoder@ede8b1e
      vanillaEncoder=net.minecraft.network.PacketEncoder@100291d2
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@587239b1
      processor=com.comphenix.protocol.injector.NetworkProcessor@2482e18d
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4ce1c07b
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    git-Paper-307 (MC: 1.19.2)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by lukalt** [comment]
You are using an outdated version of ProtocolLib. Use https://ci.dmulloy2.net/job/ProtocolLib/606/ for 1.19.2
