### ISSUE TITLE
error server

### ISSUE THREAD

**Issue by sdawd2q3e** [dmulloy2/ProtocolLib#2245]
[15:10:39 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	
  	
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	

  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)	  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	
        handle=1125929971613696	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@601a518e[
      memoryAddress=140637764744608
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(e884c96: 1%, 24576/4194304)

      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]        inputBufferedPackets=[]
      offset=16384
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@3217a687
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=19
      writerIndex=19
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@6e3df029[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1e96c4cf
        packetListeners=[PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AdvancedGUI, sending=ListeningWhitelist[priority=NORMAL, packets=[MAP[class=PacketPlayOutMap, id=39]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=FakeBlock, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[USE_ITEM[class=PacketPlayInUseItem, id=46]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=FakeBlock, sending=ListeningWhitelist[priority=HIGH, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=34]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=FakeBlock, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGH, packets=[ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@37b0392c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5d374dd2

        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5c8a52e5
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@74124507
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@42dd7bf0
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1858,minecraftVersion=1.19.2}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2b709487
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=7
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7118d029      vanillaDecoder=net.minecraft.network.PacketDecoder@2af2aee1        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5aab98c7
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.2)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@7e12e205[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@73d05c2a
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@4c365a68
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@965384
      originalChannel=[id: 0x1b42f7f4, L:/31.220.93.62:5001 - R:/169.148.5.24:64948]      closed=false

      vanillaEncoder=net.minecraft.network.PacketEncoder@72e463b6
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7118d029
      processor=com.comphenix.protocol.injector.NetworkProcessor@53434bcd
      injected=true

      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@965384, previous=[id: 0x1b42f7f4, L:/31.220.93.62:5001 - R:/169.148.5.24:64948], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@665127b7, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      finalEvent=<null>      currentEvent=<null>

      cumulation=PooledUnsafeDirectByteBuf(ridx: 19, widx: 19, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@6034aeb7
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true      added=true
      decodeState=1
      discardAfterReads=16
      numReads=0

    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@18cad40f
  Server:
    git-Purpur-1858 (MC: 1.19.2)

**Comment by Illyrius666** [comment]
I have the same problem
try reverting back to an older version of protocolLib
