### ISSUE TITLE
Server ERROR

### ISSUE THREAD

**Issue by PuttipongM** [dmulloy2/ProtocolLib#2249]
[18:13:09 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:442)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @3dc29044
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at ProtocolLib (1).jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 14 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5d0699a7[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@63f009cb
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@ad27fb3
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@70fe11f9
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1933,minecraftVersion=1.19.3}
      file=plugins\ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@5f29a641
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5f29a641
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib (1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@439eecbf
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    19.0.1
  Server:
    git-Purpur-1933 (MC: 1.19.3)

**Comment by Jeppa** [comment]
Please read the project page and/or the hundreds of other post with the same issue ...
