### ISSUE TITLE
Java 20 

### ISSUE THREAD

**Issue by SlimeDog** [dmulloy2/ProtocolLib#2251]
- [x] This issue is not solved in a development build

**Describe the bug**
Java 20
Spigot1.19.4-3692 or Paper 1.19.4-466
ProtocolLib 5.0.0-b616

Java 20 has just been released, so early days. Unfortunately, ProtocolLib does not play well with Java 20. Java 19 is fine.

**To Reproduce**
1. Install [Java 20](https://www.oracle.com/java/technologies/downloads/)
2. Start server
3. See log error

**Expected behavior**
Java 20 compatibility

**Log errors**
```
[08:32:23] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b616
[08:32:23] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.19.4) has not yet been tested! Proceed with caution.
[08:32:24] [Server thread/ERROR]: null initializing ProtocolLib v5.0.0-SNAPSHOT-b616 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.<clinit>(NetworkManagerInjector.java:39) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:108) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120) ~[?:?]
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:427) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3692-Spigot-6ad4b93-40b87e1]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3692-Spigot-6ad4b93-40b87e1]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3692-Spigot-6ad4b93-40b87e1]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3692-Spigot-6ad4b93-40b87e1]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @22b6b844
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:472) ~[?:?]
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:284) ~[?:?]
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118) ~[?:?]
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:241) ~[?:?]
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148) ~[?:?]
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101) ~[?:?]
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166) ~[?:?]
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:159) ~[?:?]
        at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:47) ~[?:?]
        ... 9 more
```

**protocol dump**
[(https://whitedog.straight8.com/drops/protocollib-dump-2023-03-21_09.11.06.txt)](https://whitedog.straight8.com/drops/protocollib-dump-2023-03-21_09.11.06.txt)

**Comment by derklaro** [comment]
That's a Bytebuddy issue and as far as I am aware there is no version with j20 support released yet

**Comment by SlimeDog** [comment]
Not likely. As noted, it's early days. Please post a heads-up issue over there.

**Comment by derklaro** [comment]
Can you try this and provide feedback? https://github.com/raphw/byte-buddy/issues/1396#issuecomment-1405066509

**Comment by andrewkm** [comment]
Same here on Java 20.

```
[11:56:14] [Server thread/ERROR]: [ProtocolLib] Error initializing plugin 'ProtocolLib.jar' in folder 'plugins' (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.<clinit>(NetworkManagerInjector.java:39) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:108) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175) ~[ProtocolLib.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @66f99c7
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:472) ~[ProtocolLib.jar:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:284) ~[ProtocolLib.jar:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118) ~[ProtocolLib.jar:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:241) ~[ProtocolLib.jar:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148) ~[ProtocolLib.jar:?]
	at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101) ~[ProtocolLib.jar:?]
	at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:159) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:47) ~[ProtocolLib.jar:?]
	... 13 more
```

**Comment by 1eminozlu** [comment]
[01:06:32] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b617
[01:06:33] [Server thread/ERROR]: null initializing ProtocolLib v5.0.0-SNAPSHOT-b617 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.<clinit>(NetworkManagerInjector.java:39) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:108) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120) ~[?:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:427) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3693-Spigot-6ad4b93-388d458]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3693-Spigot-6ad4b93-388d458]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3693-Spigot-6ad4b93-388d458]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3693-Spigot-6ad4b93-388d458]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @152605eb
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:472) ~[?:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:284) ~[?:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118) ~[?:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:241) ~[?:?]
	at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148) ~[?:?]
	at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101) ~[?:?]
	at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6166) ~[?:?]
	at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:159) ~[?:?]
	at com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:47) ~[?:?]
	... 9 more

**Comment by SlimeDog** [comment]
ProtocolLib 5.0.0-SNAPSHOT-b626 looks great on Paper 1.19.4-477 and Spigot 1.19.4-3699 with Java 20. Thanks.

**Comment by SlimeDog** [comment]
FWIW, ByteBuddy was update to 1.14.3 earlier today.

**Comment by dmulloy2** [comment]
> FWIW, ByteBuddy was update to 1.14.3 earlier today.

yup, that's what we were waiting on
