### ISSUE TITLE
Error after fix my error

### ISSUE THREAD

**Issue by F3F5** [dmulloy2/ProtocolLib#2263]
old issues: https://github.com/dmulloy2/ProtocolLib/issues/2255

[org.bukkit.craftbukkit.v1_12_R1.CraftServer] null initializing ProtocolLib v5.0.0-SNAPSHOT-b621 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:117) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120) ~[?:?]
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[patched_1.12.2.jar:git-Reaper-a5f3c34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) ~[patched_1.12.2.jar:git-Reaper-a5f3c34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:638) ~[patched_1.12.2.jar:git-Reaper-a5f3c34]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to find network.EnumProtocol (network.ConnectionProtocol, EnumProtocol)
        at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$3(MinecraftReflection.java:1446) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1446) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:620) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:86) ~[?:?]
        ... 7 more

**Comment by Jeppa** [comment]
The way i read the plugins page and the dev page servers 1.12.x should not (yet) run latest dev build...

**Comment by F3F5** [comment]
> The way i read the plugin's page and the dev page servers 1.12.x should not (yet) run latest dev build...

i know but protocollib has legacy  code + more servers needs last

**Comment by F3F5** [comment]
+ b14 works very good dev-build

**Comment by F3F5** [comment]
THAAAAAAAAAANKS, IT WORKS
