### ISSUE TITLE
Latest ProtocolLib stopped working on 1.12.2

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#2267]
Latest dev builds have stopped working on 1.12.2

```
[14:54:48] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b14
[14:54:48] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] null initializing ProtocolLib v5.0.0-SNAPSHOT-b14 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:117) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:120) ~[?:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:175) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: Unable to find network.EnumProtocol (network.ConnectionProtocol, EnumProtocol)
	at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$3(MinecraftReflection.java:1446) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1446) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:620) ~[?:?]
	at com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:86) ~[?:?]
	... 7 more
```

Last working build: https://github.com/dmulloy2/ProtocolLib/commit/365bb66d2a1525227d7a1b609a6bfb614b0dd200
Latest broken: https://github.com/dmulloy2/ProtocolLib/commit/1912a9c871003696c072e44a3dcbc8f047d60c20
Paper Build 1619 (1.12.2)

**Comment by dmulloy2** [comment]
Should be fixed in build 624

**Comment by andrewkm** [comment]
Fixed confirmed.
