### ISSUE TITLE
What is it ?

### ISSUE THREAD

**Issue by Dylex-dll** [dmulloy2/ProtocolLib#2279]
[21:12:35 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)        at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at ProtocolLib (2).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:1623)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @3f7d7581
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at ProtocolLib (2).jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at ProtocolLib (2).jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 10 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@66fb6191[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4d6c1fd7
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@70261802
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@3d7f7a19
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-388,minecraftVersion=1.18.2}
      file=plugins\ProtocolLib (2).jar
      description=org.bukkit.plugin.PluginDescriptionFile@4af398c3
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib (2).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@5982b03b
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    20
  Server:
    git-Paper-388 (MC: 1.18.2)

**Comment by dmulloy2** [comment]
use latest dev build for java 20

**Comment by Dylex-dll** [comment]
I'm already using the java 20 version

**Comment by Dylex-dll** [comment]
![Screenshot 2023-03-30 044105](https://user-images.githubusercontent.com/121286308/228706807-69e3afb1-9078-4f6d-b35e-f73f105bcfdb.png)


> use latest dev build for java 20
