### ISSUE TITLE
trying to log in to a locahost server and get this error 

### ISSUE THREAD

**Issue by iRazvan2745** [dmulloy2/ProtocolLib#2282]
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    io.netty.buffer.PooledUnsafeDirectByteBuf@38d043c9[
      memoryAddress=2486896366528
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(224c458e: 10%, 417792/4194304)
      handle=24769931094523905
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=361344
      length=835
      maxLength=896
      cache=io.netty.buffer.PoolThreadCache@707b797
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=835
      writerIndex=835
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3024d4d7[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@33089dd9
        packetListeners=[PacketAdapter[plugin=PacketLimiter, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], BEACON[class=PacketPlayInBeacon, id=36], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], STRUCT[class=PacketPlayInStruct, id=42], SPECTATE[class=PacketPlayInSpectate, id=45], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], GROUND[class=d, id=20], PICK_ITEM[class=PacketPlayInPickItem, id=23], BOAT_MOVE[class=PacketPlayInBoatMove, id=22], ABILITIES[class=PacketPlayInAbilities, id=25], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], PONG[class=ServerboundPongPacket, id=29], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ITEM_NAME[class=PacketPlayInItemName, id=32], TR_SEL[class=PacketPlayInTrSel, id=35], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], SETTINGS[class=PacketPlayInSettings, id=5], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], B_EDIT[class=PacketPlayInBEdit, id=11], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], USE_ENTITY[class=PacketPlayInUseEntity, id=13], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=12], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=14], POSITION[class=PacketPlayInPosition, id=17], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=16], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], CHAT[class=PacketPlayInChat, id=3], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2]], gamephase=PLAYING, options=[INTERCEPT_INPUT_BUFFER, ASYNC]]], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=BPS-Premium, sending=ListeningWhitelist[priority=HIGHEST, packets=[CUSTOM_PAYLOAD[class=ClientboundDamageEventPacket, id=24]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@399e5086
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@49a15d82
        inputBufferedPackets=[SETTINGS[class=PacketPlayInSettings, id=5], CLIENT_COMMAND[class=PacketPlayInClientCommand, id=4], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], TAB_COMPLETE[class=PacketPlayInTabComplete, id=6], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], B_EDIT[class=PacketPlayInBEdit, id=11], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], USE_ENTITY[class=PacketPlayInUseEntity, id=13], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=12], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=14], POSITION[class=PacketPlayInPosition, id=17], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=16], LOOK[class=PacketPlayInLook, id=19], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], CHAT[class=PacketPlayInChat, id=3], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], BEACON[class=PacketPlayInBeacon, id=36], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], STRUCT[class=PacketPlayInStruct, id=42], SPECTATE[class=PacketPlayInSpectate, id=45], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], USE_ITEM[class=PacketPlayInUseItem, id=46], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], GROUND[class=d, id=20], PICK_ITEM[class=PacketPlayInPickItem, id=23], BOAT_MOVE[class=PacketPlayInBoatMove, id=22], ABILITIES[class=PacketPlayInAbilities, id=25], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], PONG[class=ServerboundPongPacket, id=29], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ITEM_NAME[class=PacketPlayInItemName, id=32], TR_SEL[class=PacketPlayInTrSel, id=35], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34]]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5fb5ba0d
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@28241277
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@63757d95
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-478,minecraftVersion=1.19.4}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@526cc2e4
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=4
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@5d44a7ec
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@19f8a155
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.4)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@45565b1[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@be7e4dc
      player=CraftPlayer{name=iRazvan2745}
      updated=<null>
      playerName=iRazvan2745
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@3948ef80
      originalChannel=[id: 0x3cd46248, L:/127.0.0.1:25565 - R:/127.0.0.1:1265]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@3948ef80, previous=[id: 0x3cd46248, L:/127.0.0.1:25565 - R:/127.0.0.1:1265], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2c1ed904, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@10621904
      vanillaDecoder=net.minecraft.network.PacketDecoder@6ea8c067
      vanillaEncoder=net.minecraft.network.PacketEncoder@27c93147
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@5d44a7ec
      processor=com.comphenix.protocol.injector.NetworkProcessor@7d6f96c6
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 835, widx: 835, cap: 835)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4f30177b
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-478 (MC: 1.19.4)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
