### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by Blackbooster372** [dmulloy2/ProtocolLib#2283]
I am getting this error

java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399)
  	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269)
  	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
  	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
  	at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @6625de8f
  	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
  	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
  	at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
  	at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
  	at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
  	at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
  	at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
  	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
  	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
  	... 10 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@40d2ae63[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3e06eb9d
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6bf2eb88
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@1bc85eb9
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-794,minecraftVersion=1.16.5}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@862c9b6
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@75af1115
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    19.0.2
  Server:
    git-Paper-794 (MC: 1.16.5)

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
