### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Alecvien** [dmulloy2/ProtocolLib#2295]
I don’t really understand this myself, and I can’t understand what the problem is, the files seem to be installed correctly

 [ProtocolLib] INTERNAL ERROR: Cannot find listener thread in MinecraftServer.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkListenThreadClass(MinecraftReflection.java:1576)
        at ProtocolLib.jar//com.comphenix.protocol.injector.player.InjectedServerConnection.initializeListenerField(InjectedServerConnection.java:194)
        at ProtocolLib.jar//com.comphenix.protocol.injector.player.InjectedServerConnection.injectListenerThread(InjectedServerConnection.java:232)
        at ProtocolLib.jar//com.comphenix.protocol.injector.player.InjectedServerConnection.injectList(InjectedServerConnection.java:181)
        at ProtocolLib.jar//com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler.<init>(ProxyPlayerInjectionHandler.java:150)
        at ProtocolLib.jar//com.comphenix.protocol.injector.player.PlayerInjectorBuilder.buildHandler(PlayerInjectorBuilder.java:139)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:253)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Dump:
  Parameters:
    net.minecraft.server.dedicated.DedicatedServer@76a8d29b[
      serverCommandQueue=[]
      v=<null>
      w=net.minecraft.server.rcon.RemoteControlCommandListener@50de2a4e
      x=<null>
      y=net.minecraft.server.dedicated.DedicatedServerSettings@1a4fc584
      z=<null>
      A=<null>
      B=<null>
      l=net.minecraft.world.level.storage.Convertable$ConversionSession@797cd626
      m=net.minecraft.world.level.storage.WorldNBTStorage@6f4ab6cf
      B=[]
      C=net.minecraft.util.profiling.metrics.profiling.InactiveMetricsRecorder@2142bece
      D=net.minecraft.util.profiling.GameProfilerDisabled@306df1ea
      E=net.minecraft.server.MinecraftServer$$Lambda$4112/0x00000008018910d8@2f3fdc27
      F=net.minecraft.server.MinecraftServer$$Lambda$4113/0x00000008018912f8@1579fbc1
      G=false
      H=<null>
      I=false
      J=net.minecraft.server.network.ServerConnection@7e44c41a
      K=net.minecraft.server.Main$$Lambda$4111/0x0000000801890000@2fcbf111
      L=net.minecraft.network.protocol.status.ServerPing@75b6a0da
      M=java.util.Random@18b9aff1
      N=com.mojang.datafixers.DataFixerUpper@4085dce8
      O=26.66.2.32
      P=25565
      Q=net.minecraft.core.IRegistryCustom$b@30b6ee90
      R={}
      S=net.minecraft.server.dedicated.DedicatedPlayerList@7046282c
      T=true
      isRestarting=false
      U=false
      V=0
      n=DIRECT
      W=false
      X=false
      Y=false
      Z=false
      aa=A Minecraft Server
      ab=0
      o={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
      tickTimes5s=net.minecraft.server.MinecraftServer$TickTimes@63be250
      tickTimes10s=net.minecraft.server.MinecraftServer$TickTimes@4099ff6
      tickTimes60s=net.minecraft.server.MinecraftServer$TickTimes@2c78169e
      ac=java.security.KeyPair@770b8561
      ad=<null>
      ae=false
      af=
      ag=
      ah=false
      ai=0
      aj=com.destroystokyo.paper.profile.PaperMinecraftSessionService@2efbc0b2
      ak=com.destroystokyo.paper.profile.PaperGameProfileRepository@66450cb4
      al=net.minecraft.server.players.UserCache@ae53a04
      am=0
      an=Thread[#35,Server thread,7,main]
      ao=19685133
      ap=0
      aq=false
      ar=net.minecraft.server.packs.repository.ResourcePackRepository@21ee86b4
      as=net.minecraft.server.ScoreboardServer@51603c6b
      at=<null>
      au=net.minecraft.server.bossevents.BossBattleCustomData@3c1886b0
      av=net.minecraft.server.CustomFunctionData@69166ca1
      aw=net.minecraft.util.CircularTimer@3945868c
      ax=false
      ay=0.0
      az=java.util.concurrent.ThreadPoolExecutor@20005a35[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 76]
      aA=<null>
      aB=a[resourceManager=net.minecraft.server.packs.resources.ResourceManager@47ef8cc, managers=net.minecraft.server.DataPackResources@5c8ff18b]
      aC=net.minecraft.world.level.levelgen.structure.templatesystem.DefinedStructureManager@a1dce2a
      p=<null>
      aD=false
      datapackconfiguration=net.minecraft.world.level.DataPackConfiguration@64ea0920
      registryreadops=net.minecraft.resources.RegistryOps@ca5c0fa
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-388,minecraftVersion=1.18.2}
      options=joptsimple.OptionSet@42705d7e
      console=com.destroystokyo.paper.console.TerminalConsoleCommandSender@4800a9db
      remoteConsole=<null>
      processQueue=[]
      autosavePeriod=1200
      vanillaCommandDispatcher=net.minecraft.commands.CommandDispatcher@3c4c1977
      forceTicks=false
      recentTps={0.0,0.0,0.0}
      shutdownThread=<null>
      abnormalExit=false
      isIteratingOverLevels=false
      hasStopped=false
      hasFullyShutdown=false
      hasLoggedStop=false
      stopLock=java.lang.Object@3812f4da
      lastTick=0
      catchupTime=0
      tps1=net.minecraft.server.MinecraftServer$RollingAverage@312b0001
      tps5=net.minecraft.server.MinecraftServer$RollingAverage@4c335821
      tps15=net.minecraft.server.MinecraftServer$RollingAverage@66240a44
      isOversleep=false
      b=0
      b=Server
      d=[]
      e=0
    ]
  Sender:
    com.comphenix.protocol.injector.player.InjectedServerConnection@76591a3e[
      listFields=[]
      replacedLists=[]
      netLoginInjector=com.comphenix.protocol.injector.player.NetLoginInjector@30e9589b
      socketInjector=com.comphenix.protocol.injector.server.InputStreamReflectLookup@550248e
      socketType=LISTENER_THREAD
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-388,minecraftVersion=1.18.2}
      reporter=com.comphenix.protocol.ProtocolLib$1@7634fc9c
      hasAttempted=true
      hasSuccess=false
      minecraftServer=net.minecraft.server.dedicated.DedicatedServer@76a8d29b
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    19.0.2
  Server:
    git-Paper-388 (MC: 1.18.2)

[15:05:53 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  FieldAccessException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}. Workaround failed too.
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.ProxyPacketInjector.initialize(ProxyPacketInjector.java:191)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.ProxyPacketInjector.<init>(ProxyPacketInjector.java:164)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketInjectorBuilder.buildInjector(PacketInjectorBuilder.java:94)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:259)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPacketClass(MinecraftReflection.java:729)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.ProxyPacketInjector$ArrayLookup.initialize(ProxyPacketInjector.java:115)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.ProxyPacketInjector$ArrayLookup.<init>(ProxyPacketInjector.java:106)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.ProxyPacketInjector.initialize(ProxyPacketInjector.java:188)
        ... 11 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5956f169[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@134ba59e
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@f0f54a1
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@2431031e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-388,minecraftVersion=1.18.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@197b3c21
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@2ebbd8b9
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    19.0.2
  Server:
    git-Paper-388 (MC: 1.18.2)

 INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:1589)
  Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.Entity}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.Entity instanceof input, Index: 2}], paramCount=3}]
  }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
        at ProtocolLib.jar//com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at ProtocolLib.jar//com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        ... 10 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@5956f169[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@134ba59e
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@f0f54a1
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@2431031e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-388,minecraftVersion=1.18.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@197b3c21
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.5.1, pluginEnabled=true, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@2ebbd8b9
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    19.0.2
  Server:
    git-Paper-388 (MC: 1.18.2)

**Comment by lukalt** [comment]
It looks like you are using an outdated version of ProtocolLib. Please use the latest release from https://www.spigotmc.org/resources/protocollib.1997/ for 1.18.2 support.

**Comment by Alecvien** [comment]
> It looks like you are using an outdated version of ProtocolLib. Please use the latest release from https://www.spigotmc.org/resources/protocollib.1997/ for 1.18.2 support.

Yes, I downloaded the latest version from here, but the problem still remains
