### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by xKrustyz** [dmulloy2/ProtocolLib#2297]
[nLogin] Unexpected error during sending plugin message via ProtocolLib
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b627]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b627]
        at com.nickuc.login.εξνσΔχΣεθθζΔαΠζ.a(:116) ~[?:?]
        at com.nickuc.login.μΛΔθΛτναεαΓ.a(:64) ~[?:?]
        at com.nickuc.login.μΛΔθΛτναεαΓ.d(:102) ~[?:?]
        at com.nickuc.login.μΛΔθΛτναεαΓ.a(:198) ~[?:?]
        at com.nickuc.login.θτζθΦχχβζβθι.c(:138) ~[?:?]
        at com.nickuc.login.θτζθΦχχβζβθι.b(:88) ~[?:?]
        at com.nickuc.login.θτζθΦχχβζβθι.a(:51) ~[?:?]
        at com.nickuc.login.βολμςΦζΓψγτθΔΛ.a(:62) ~[?:?]
        at com.nickuc.login.βολμςΦζΓψγτθΔΛ.b(:94) ~[?:?]
        at com.nickuc.login.οΨτμςκΦθηΩβΩΨηλ.b(:66) ~[?:?]
        at com.nickuc.login.υθποΛςΦτ.a(:127) ~[?:?]
        at com.nickuc.login.υθποΛςΦτ.a(:190) ~[?:?]
        at com.nickuc.login.υθποΛςΦτ.c(:253) ~[?:?]
        at com.nickuc.login.tasks.CommonTask.run(:19) [?:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) [spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**API method(s) used**
List what API method(s) you're using

**Expected behavior**

**Code**
If applicable, add relevant code from your project

**Additional context**

**Comment by MajliTech** [comment]
nLogin error, should be closed.

**Comment by xKrustyz** [comment]
Strange, I spoke with nLogin support and they said it was a ProtocolLib error.

**Comment by MajliTech** [comment]
Well then i dunno

**Comment by lukalt** [comment]
We cant really help you here if you only send us a stack trace with obfuscated code. However, this error usually means that the packet has no field of the requested type. I assume that nLogin is not compatible with 1.19.2

**Comment by NakkiiBrks** [comment]
any updates on this? I have the same error rn

**Comment by lukalt** [comment]
> any updates on this? I have the same error rn

As already mentioned in my previous message, this is no problem of ProtocolLib. Please check if nLogin has a newer version available and update to it. If it does not, please contact the developer of nLogin.
