### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by WANGZIHAOWZ** [dmulloy2/ProtocolLib#2307]
- [ ] This issue is not solved in a development build

**Describe the bug**
ERROR Message are appearing from chat and console.

**To Reproduce**
I added the plugin and joined the server and there were error messages.

**Expected behavior**
It will spam the chat and the console with error:
14:31:23] [Netty Epoll Server IO #2/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@19bc1421[
      memoryAddress=140225314395040
      recyclerHandle=NOOP_HANDLE
      chunk=Chunk(324cf63b: 2%, 57344/4194304)
      handle=30064771073
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=2048
      length=2048
      maxLength=2048
      cache=io.netty.buffer.PoolThreadCache@30a0e1f8
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1219
      writerIndex=1219
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@55ebba22[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3b77ac30
        packetListeners=[PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@53aeaf30
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@286393f0
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@20d10674
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@26412872
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@34f82b40
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-368,minecraftVersion=1.19.3}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@331fd041
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=5
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@27e9fda
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@52590f99
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.3)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@4b9ee34b[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1edd09e8
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@22e535c3
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@717520a0
      originalChannel=[id: 0xd1053dda, L:/10.0.4.11:25565 - R:/43.142.140.22:37801]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@717520a0, previous=[id: 0xd1053dda, L:/10.0.4.11:25565 - R:/43.142.140.22:37801], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@48772950, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@17da13fa
      vanillaDecoder=net.minecraft.network.PacketDecoder@409c7df0
      vanillaEncoder=net.minecraft.network.PacketEncoder@d7311c6
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@27e9fda
      processor=com.comphenix.protocol.injector.NetworkProcessor@3b3d0d2f
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1219, widx: 1219, cap: 2048)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@18ed9445
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-368 (MC: 1.19.3)

**Version Info**
ProtocolLib Dump
Timestamp: 04/06/23 14:50:33

ProtocolLib Version: ProtocolLib v4.8.0
Bukkit Version: 1.19.3-R0.1-SNAPSHOT
Server Version: git-Paper-368 (MC: 1.19.3)
Java Version: 17.0.6

ProtocolLib: com.comphenix.protocol.ProtocolLib@f63c089[
  statistics=com.comphenix.protocol.metrics.Statistics@51f9323d
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@470d4a38
  packetTask=3
  tickCounter=902
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@720a8227
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@637c7367
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@7b8cddef
  commandProtocol=com.comphenix.protocol.CommandProtocol@56fd042c
  commandPacket=com.comphenix.protocol.CommandPacket@7040af6e
  commandFilter=com.comphenix.protocol.CommandFilter@70a71d4a
  packetLogging=com.comphenix.protocol.PacketLogging@6dd9c514
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@53bb60e7
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-368,minecraftVersion=1.19.3}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@6ef09ae8
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@4516ee5c
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@4f187459[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@720a8227
  packetListeners=[PacketAdapter[plugin=AntiCheatReloaded, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AntiCheatReloaded, sending=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@25d59088
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@78b0974e
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@aa6f20a
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@610f5bb
  hasClosed=false
  classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  reporter=com.comphenix.protocol.ProtocolLib$1@733e8871
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-368,minecraftVersion=1.19.3}
  library=ProtocolLib v4.8.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4e3512be
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=5
  packetCreation=false
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6210a880
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@61c509d7
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.19.3)
  debug=false
]

Listeners:
com.rammelkast.anticheatreloaded.util.PacketListener$3@38f50264[
  plugin=AntiCheatReloaded v1.10.3
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.rammelkast.anticheatreloaded.util.PacketListener$2@7317d784[
  plugin=AntiCheatReloaded v1.10.3
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]
]
com.rammelkast.anticheatreloaded.util.PacketListener$1@4bfa1bad[
  plugin=AntiCheatReloaded v1.10.3
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]]
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], POSITION[class=PacketPlayOutPosition, id=56]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
AntiCheatReloaded by [Rammelkast]

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
