### ISSUE TITLE
Console Error - ProtocolLib

### ISSUE THREAD

**Issue by DarkZmaj** [dmulloy2/ProtocolLib#2316]
[ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

This is the error that shows up in my console and many more text i don't understand.
It is the latest version and it shows that it works but other plugins wont work and console spams that.

------------------------------------------------------------------------------

"[21:02:19 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib (10).jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib (10).jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib (10).jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib (10).jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at ProtocolLib (10).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@52005185[
      memoryAddress=140179276911744
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@1104e6fc
      chunk=Chunk(fc1f347: 1%, 32768/4194304)
      handle=1125929971613697
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16640
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@2e0b20cd
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7f73a24d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@176e2463
        packetListeners=[PacketAdapter[plugin=DecentHolograms, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=Negativity, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=101], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Negativity, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[PING[class=PacketStatusInPing, id=1], SET_PROTOCOL[class=PacketHandshakingInSetProtocol, id=0], USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], SET_COMMAND_BLOCK[class=PacketPlayInSetCommandBlock, id=38], SET_COMMAND_MINECART[class=PacketPlayInSetCommandMinecart, id=39], SET_CREATIVE_SLOT[class=PacketPlayInSetCreativeSlot, id=40], SET_JIGSAW[class=PacketPlayInSetJigsaw, id=41], STRUCT[class=PacketPlayInStruct, id=42], UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], SPECTATE[class=PacketPlayInSpectate, id=45], RECIPE_SETTINGS[class=PacketPlayInRecipeSettings, id=30], RECIPE_DISPLAYED[class=PacketPlayInRecipeDisplayed, id=31], ITEM_NAME[class=PacketPlayInItemName, id=32], RESOURCE_PACK_STATUS[class=PacketPlayInResourcePackStatus, id=33], ADVANCEMENTS[class=PacketPlayInAdvancements, id=34], TR_SEL[class=PacketPlayInTrSel, id=35], BEACON[class=PacketPlayInBeacon, id=36], HELD_ITEM_SLOT[class=PacketPlayInHeldItemSlot, id=37], BOAT_MOVE[class=PacketPlayInBoatMove, id=22], PICK_ITEM[class=PacketPlayInPickItem, id=23], AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], ABILITIES[class=PacketPlayInAbilities, id=25], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], PONG[class=ServerboundPongPacket, id=29], JIGSAW_GENERATE[class=PacketPlayInJigsawGenerate, id=14], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], DIFFICULTY_LOCK[class=PacketPlayInDifficultyLock, id=16], POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19], GROUND[class=d, id=20], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=21], Dynamic-b9e8f6d1-db8a-4013-af94-6a923915071b[class=PacketPlayInTabComplete, id=6], ENCHANT_ITEM[class=PacketPlayInEnchantItem, id=7], WINDOW_CLICK[class=PacketPlayInWindowClick, id=8], CLOSE_WINDOW[class=PacketPlayInCloseWindow, id=9], CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10], B_EDIT[class=PacketPlayInBEdit, id=11], ENTITY_NBT_QUERY[class=PacketPlayInEntityNBTQuery, id=12], USE_ENTITY[class=PacketPlayInUseEntity, id=13], TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], TILE_NBT_QUERY[class=PacketPlayInTileNBTQuery, id=1], DIFFICULTY_CHANGE[class=PacketPlayInDifficultyChange, id=2], Dynamic-3cdc3757-c553-44bf-aaa6-d5afff72192e[class=PacketPlayInChat, id=3], Dynamic-73c2acb9-6f61-40a3-905f-2452d2322202[class=PacketPlayInClientCommand, id=4], SETTINGS[class=PacketPlayInSettings, id=5], START[class=PacketStatusInStart, id=0], START[class=PacketLoginInStart, id=0], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], CUSTOM_PAYLOAD[class=PacketLoginInCustomPayload, id=2]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7e73842f
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@490e9a05
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2b0d38a3
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d264c9d
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (10).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@127592af
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-499,minecraftVersion=1.19.4}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2fc29444
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=3
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1981fad2
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3125ee94
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.4)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@a16ce7b[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@32cf2899
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@2ce8ff2b
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@2c336a3a
      originalChannel=[id: 0xd7c02e56, L:/172.18.0.13:25568 - R:/172.18.0.1:57436]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@2c336a3a, previous=[id: 0xd7c02e56, L:/172.18.0.13:25568 - R:/172.18.0.1:57436], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@6710422d, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@c6ae843
      vanillaDecoder=net.minecraft.network.PacketDecoder@3b3f214e
      vanillaEncoder=net.minecraft.network.PacketEncoder@2935dce2
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@1981fad2
      processor=com.comphenix.protocol.injector.NetworkProcessor@17a223fa
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@44f7dbaf
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-499 (MC: 1.19.4)

[21:03:19 INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@19b8d31f."

------------------------------------------------------------------------------

Please help me fix it so i can make it work. I will prob. not see help here so if you are king add me on discord "12kChainz#0501". Thank you.

**Comment by dmulloy2** [comment]
This is fixed in the latest dev builds. Find them here: [https://ci.dmulloy2.net/job/ProtocolLib/](https://ci.dmulloy2.net/job/ProtocolLib/)
