### ISSUE TITLE
Errro with build 632

### ISSUE THREAD

**Issue by huberte** [dmulloy2/ProtocolLib#2322]
Spigot, latest 1.19.4

---

Unbundling libraries to F:\Jeux\Minecraft\serveur\plugins\bundler
Starting server
Loading libraries, please wait...
[16:42:24] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:42:24] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[16:42:26] [ServerMain/INFO]: Loaded 7 recipes
[16:42:24] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:42:24] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[16:42:26] [ServerMain/INFO]: Loaded 7 recipes
>[16:42:26] [Server thread/INFO]: Starting minecraft server version 1.19.4
[16:42:26] [Server thread/INFO]: Loading properties
[16:42:27] [Server thread/INFO]: This server is running CraftBukkit version 3726-Spigot-514cf03-5ee3419 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
[16:42:27] [Server thread/INFO]: Debug logging is disabled
[16:42:27] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:42:27] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:42:27] [Server thread/INFO]: Default game type: SURVIVAL
[16:42:27] [Server thread/INFO]: Generating keypair
[16:42:27] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:42:27] [Server thread/INFO]: Using default channel type
[16:42:28] [Server thread/INFO]: [Chunky] Loading Chunky v1.3.52
[16:42:28] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[16:42:28] [Server thread/WARN]: [ProtocolLib] Debug mode is enabled!
[16:42:28] [Server thread/INFO]: [ProtocolLib] Detected netty version: 4.1.82
[16:42:28] [Server thread/WARN]: [ProtocolLib] Detailed error reporting enabled!
[16:42:28] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.19.4) has not yet been tested! Proceed with caution.
[16:42:29] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:427)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
        at java.base/java.lang.Thread.run(Thread.java:1623)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @9110dca
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 10 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1716ebd3[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@351f8e22
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@15f7a321
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@528648b4
      server=CraftServer{serverName=CraftBukkit,serverVersion=3726-Spigot-514cf03-5ee3419,minecraftVersion=1.19.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4888ed18
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@22e13465
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@42ed8da8
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    20
  Server:
    3726-Spigot-514cf03-5ee3419 (MC: 1.19.4)

**Comment by huberte** [comment]
Worked with https://github.com/dmulloy2/ProtocolLib/issues/2308
