### ISSUE TITLE
A bug occurs when logging in to the server

### ISSUE THREAD

**Issue by XLEBXT** [dmulloy2/ProtocolLib#2325]
[20:39:35 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@52db9122[
      memoryAddress=140296584334512
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@77cbc366
      chunk=Chunk(21a49498: 28%, 1171456/4194304)
      handle=22518062561361921
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=327728
      length=34
      maxLength=48
      cache=io.netty.buffer.PoolThreadCache@1060ec06
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1c4516a2[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3003564d
        packetListeners=[PacketAdapter[plugin=MyCommand, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=HIGH, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=17]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperVanish, sending=ListeningWhitelist[priority=NORMAL, packets=[OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=HackedServer, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CUSTOM_PAYLOAD[class=PacketPlayInCustomPayload, id=10]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=UltimateDrugs, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=93], ENTITY_SOUND[class=PacketPlayOutEntitySound, id=92], CUSTOM_SOUND_EFFECT[class=ClientboundDeleteChatPacket, id=25]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@291ce58c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@46702c4f
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7234c225
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@582f4310
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@16d1ed1c
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-507,minecraftVersion=1.19.4}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5756c22
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=8
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@6444d5e7
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@47c51b40
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.4)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@7051faa7[
      decodeBuffer=protected void it.ytnoos.lpx.i.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@6ac0f65b
      player=CraftPlayer{name=XLEB_XT}
      updated=<null>
      playerName=XLEB_XT
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@1c737e0a
      originalChannel=[id: 0x666b29a1, L:/172.18.0.2:49150 - R:/109.252.25.228:1814]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@1c737e0a, previous=[id: 0x666b29a1, L:/172.18.0.2:49150 - R:/109.252.25.228:1814], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@741fe657, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@5c8ea855
      vanillaDecoder=it.ytnoos.lpx.i@43a02965
      vanillaEncoder=net.minecraft.network.PacketEncoder@75ca2a9e
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@6444d5e7
      processor=com.comphenix.protocol.injector.NetworkProcessor@570994a6
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4d2360d0
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.6
  Server:
    git-Paper-507 (MC: 1.19.4)

Generated: April 10, 2023 at 8:40:25 PM UTC

PlaceholderAPI: 2.11.2

Expansions Registered:
  Vulcan        [Author: [frep, GladUrBad, Joshb_, Elevated, retrooper], Version: 2.7.3]
  activator     [Author: BrainRTP, Nanit, Version: 1.0]
  bungee        [Author: clip, Version: 1.0.1]
  changed       [Author: BrainRTP, Nanit, Version: 1.0]
  chatty        [Author: MrBrikster, Version: 2.19.12]
  cmi           [Author: [Zrips], Version: 9.5.0.4]
  cmil          [Author: [Zrips], Version: 1.2.5.2]
  ctg           [Author: BrainRTP, Nanit, Version: 1.0]
  cwr           [Author: Kihsomray, CroaBeast, Faln', Version: 1.4.6]
  discordsrv    [Author: [Scarsz, Androkai, Vankka], Version: 1.26.1-SNAPSHOT]
  gsit          [Author: [Gecolay], Version: 1.4.3]
  hanim         [Author: BrainRTP, Nanit, Version: 1.0]
  itemedit      [Author: emanon, Version: 1.0]
  localtime     [Author: aBooDyy, Version: 1.2]
  mycommand     [Author: emmerrei, Version: 1.0.0]
  oreannouncer  [Author: AlessioDP, Version: 2.8.3]
  placed        [Author: BrainRTP, Nanit, Version: 1.0]
  plasmovoice   [Author: Apehum, Version: 2.0.3]
  player        [Author: clip, Version: 2.0.3]
  playercontrol [Author: Ajneb97, Version: 3.9.2]
  playerstats   [Author: Artemis, Version: 1.2.0]
  playerstatus  [Author: mirrerror, Version: 1.0]
  server        [Author: clip, Version: 2.6.1]
  spark         [Author: Luck, Version: 1.10.37]
  statistic     [Author: clip, Version: 2.0.1]
  supervanish   [Author: [MyzelYam], Version: 6.2.15]
  taken         [Author: BrainRTP, Nanit, Version: 1.0]
  var           [Author: BrainRTP, Nanit, Version: 1.0]
  varp          [Author: BrainRTP, Nanit, Version: 1.0]
  varpt         [Author: BrainRTP, Nanit, Version: 1.0]
  vart          [Author: BrainRTP, Nanit, Version: 1.0]
  viewdistance  [Author: xuancat0208, Version: FartherViewDistancePlaceholder 0.0.1]

Expansions Directory:
  Expansion-player.jar
  Expansion-bungee.jar
  Expansion-server.jar
  Expansion-localtime.jar
  Expansion-playerstats.jar
  Expansion-statistic.jar

Server Info: 1.19.4-R0.1-SNAPSHOT/git-Paper-507 (MC: 1.19.4)
Java Version: 17.0.6

Plugin Info:
  AbstractMenus         [Version: 1.16.3]
  ArmorStandTools       [Version: 4.4.7-feoz]
  AuxProtect            [Version: 1.2.4]
  Brewery               [Version: 3.1]
  CMI                   [Version: 9.5.0.4]
  CMILib                [Version: 1.2.5.2]
  Chatty                [Version: 2.19.12]
  Chunky                [Version: 1.3.52]
  CommandWhitelist      [Version: 2.5.5]
  CoreProtect           [Version: 21.3]
  CoreProtectTNT        [Version: 2.3]
  CyberWorldReset       [Version: 1.4.6]
  DiscordSRV            [Version: 1.26.1-SNAPSHOT]
  EasyWhitelist         [Version: 1.0.2]
  EntityDetection       [Version: 1.2.0 (build #23)]
  FartherViewDistance   [Version: 9.7.3]
  GSit                  [Version: 1.4.3]
  HackedServer          [Version: 3.0.1]
  InvSeePlusPlus        [Version: 0.16.0-SNAPSHOT]
  InventoryRollbackPlus [Version: 1.6.8]
  ItemEdit              [Version: 3.0.7]
  LPX                   [Version: 3.2.4]
  LiteBans              [Version: 2.10.4]
  LuckPerms             [Version: 5.4.40]
  MyCommand             [Version: 5.7.3]
  OreAnnouncer          [Version: 2.8.3]
  PlaceholderAPI        [Version: 2.11.2]
  PlasmoVoice           [Version: 2.0.3]
  PlayerControlPlus     [Version: 3.9.2]
  PlayerStats           [Version: 1.7.2]
  PlayerStatus          [Version: 1.1]
  ProtocolLib           [Version: 4.8.0]
  SelectionVisualizer   [Version: 3.2.1.0]
  SkinsRestorer         [Version: 14.2.10]
  SuperVanish           [Version: 6.2.15]
  TAB                   [Version: 3.3.1]
  TPWolf                [Version: 2.0-RELEASE]
  TabTPS                [Version: 1.3.16]
  UltimateDrugs         [Version: 2.4.6]
  Vault                 [Version: 1.7.3-b131]
  Vulcan                [Version: 2.7.3]
  WorldEdit             [Version: 7.2.12+6240-87f4ae1]
  WorldGuard            [Version: 7.0.7+216b061]
  emotecraft            [Version: 2.0.6]
  rHideTags             [Version: 1.0]
  rRPChat               [Version: 1.0]
  spark                 [Version: 1.10.37]

**Comment by lukalt** [comment]
The latest stable release of ProtocolLib does not support Minecraft 1.19.4 yet. With Minecraft 1.19.4, you should be using the latest Dev-Build: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
