### ISSUE TITLE
INTERNAL ERROR

### ISSUE THREAD

**Issue by blackxfiied** [dmulloy2/ProtocolLib#2333]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't fixed in a recent development build
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:
[18:53:43 ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Thread.java:833)
Dump:
Parameters:
io.netty.buffer.PooledUnsafeDirectByteBuf@5486ec2a[
memoryAddress=281470748928320
recyclerHandle=io.netty.util.Recycler$DefaultHandle@16589b3a
chunk=Chunk(5adcd601: 1%, 40960/4194304)
handle=562980018192384
memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
offset=8192
length=9
maxLength=16
cache=io.netty.buffer.PoolThreadCache@613fbb53
tmpNioBuf=<null>
allocator=PooledByteBufAllocator(directByDefault: true)
refCnt=2
readerIndex=9
writerIndex=9
markedReaderIndex=0
markedWriterIndex=0
maxCapacity=2147483647
]
manager:
com.comphenix.protocol.injector.PacketFilterManager@19102c58[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@355e9caa
packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=d, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=25]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]], com.comphenix.protocol.async.NullPacketListener@42127e17, PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=79], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=42]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Orebfuscator, sending=ListeningWhitelist[priority=NORMAL, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=29]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[GROUND[class=d, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19], POSITION[class=PacketPlayInPosition, id=17]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[PONG[class=ServerboundPongPacket, id=29]], gamephase=PLAYING, options=[]]]]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@12a85ef2
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@144a8ffa
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@ca013c7
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4d5a7535
hasClosed=false
classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
reporter=com.comphenix.protocol.ProtocolLib$1@5d2084ad
server=CraftServer{serverName=Paper,serverVersion=git-Paper-510,minecraftVersion=1.19.4}
library=ProtocolLib v4.8.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4f7fae3f
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=10
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@539533ee
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@1264209
hasRecycleDistance=true
minecraftVersion=(MC: 1.19.4)
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ChannelInjector@30e24c81[
decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
factory=com.comphenix.protocol.injector.netty.InjectionFactory@e0bd8c4
player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@7b30b04d
updated=<null>
playerName=<null>
playerConnection=<null>
networkManager=net.minecraft.network.NetworkManager@252855eb
originalChannel=[id: 0x5e963133, L:/127.0.1.1:25565 - R:/127.0.0.1:55888]
channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@252855eb, previous=[id: 0x5e963133, L:/127.0.1.1:25565 - R:/127.0.0.1:55888], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@169cc3e7, previousLoaded=true, currentSet=true, forceAccess=true]
packetMarker={}
currentEvent=<null>
finalEvent=<null>
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@6850bba1
vanillaDecoder=net.minecraft.network.PacketDecoder@fb02c4d
vanillaEncoder=net.minecraft.network.PacketEncoder@7b418721
finishQueue=[]
channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@539533ee
processor=com.comphenix.protocol.injector.NetworkProcessor@6652cf31
injected=true
closed=false
cumulation=PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@1bcf7a14
singleDecode=false
first=true
firedChannelRead=false
selfFiredChannelRead=true
decodeState=1
discardAfterReads=16
numReads=0
added=true
]
Version:
ProtocolLib v4.8.0
Java Version:
17.0.6
Server:
git-Paper-510 (MC: 1.19.4)

Description and relevant errors:
idk whats even happening here

**Comment by lukalt** [comment]
Update to the latest dev build (https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).
The version you are using does not support 1.19.4
