### ISSUE TITLE
ProtocolLib 5.0.0 latest version error

### ISSUE THREAD

**Issue by gstio86** [dmulloy2/ProtocolLib#2340]
- [x] This isn't fixed in a recent development build
- [x] You've checked for duplicate issues
- [x] You didn't use /reload

**Describe the bug**
The error comes from BetonQuest v1.12.10 and the latest version of ProtocolLib
and Citizens-2.0.31b3034
This error occurs when I load an NPC with a hidden tag through BetonQuest

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
https://pastebin.com/GFhJq76g

**Additional context**
```
[16Apr2023 02:39:49.365] [Server thread/WARN] [BetonQuest/]: Task #62 for BetonQuest v1.12.10 generated an exception
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], name=\QtrackedEntities\E, type={ type input instanceof interface java.util.Map }}
	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352) ~[ProtocolLib%20635.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:233) ~[ProtocolLib%20635.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:247) ~[ProtocolLib%20635.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:180) ~[ProtocolLib%20635.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.updateEntity(EntityUtilities.java:80) ~[ProtocolLib%20635.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.updateEntity(PacketFilterManager.java:406) ~[ProtocolLib%20635.jar:?]
	at pl.betoncraft.betonquest.compatibility.protocollib.hider.EntityHider.showEntity(EntityHider.java:288) ~[BetonQuest%201.12.10.jar:?]
	at pl.betoncraft.betonquest.compatibility.protocollib.hider.NPCHider.applyVisibility(NPCHider.java:141) ~[BetonQuest%201.12.10.jar:?]
	at pl.betoncraft.betonquest.compatibility.protocollib.hider.NPCHider.applyVisibility(NPCHider.java:180) ~[BetonQuest%201.12.10.jar:?]
	at pl.betoncraft.betonquest.compatibility.protocollib.hider.NPCHider.run(NPCHider.java:114) ~[BetonQuest%201.12.10.jar:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-c7a91c51]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:400) ~[arclight:arclight-1.16.5-1.0.26-SNAPSHOT-c7a91c51]
	at net.minecraft.server.MinecraftServer.handler$bai000$arclight$runScheduler(MinecraftServerMixin.java:2165) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1916) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Koekieezz** [comment]
where do u get the latest version or the beta ones?

**Comment by gstio86** [comment]
> where do u get the latest version or the beta ones?

This https://ci.dmulloy2.net/job/ProtocolLib/
version #635 , but its version number has not changed
I changed it myself

**Comment by dmulloy2** [comment]
> > where do u get the latest version or the beta ones?
> 
> @Koekieezz This https://ci.dmulloy2.net/job/ProtocolLib/ version [#635](https://ci.dmulloy2.net/job/ProtocolLib/635/) , but its version number has not changed I changed it myself

oh interesting...looks like gradle was caching the old build number. should be fixed now

**Comment by gstio86** [comment]
@dmulloy2 
So how can I fix the error I encountered?
