### ISSUE TITLE
Error on enable

### ISSUE THREAD

**Issue by enuxx** [dmulloy2/ProtocolLib#2341]
java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x8e39b88b, L:/XX.XX.XX.XX:25565 - R:/XX.XX.XX.XX:46196]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:157)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:171)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@565c282[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@302dfdfa
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5d0731ae
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5d874663
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@765dee83
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@29401f9f
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4daed158
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1e1177d3
        reporter=com.comphenix.protocol.ProtocolLib$1@2a7d32d0
        server=CraftServer{serverName=Verasity,serverVersion=1.8.8-R0.1-SNAPSHOT,minecraftVersion=1.8.8}
        library=ProtocolLib v4.5.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@1ad8b5fb
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@61117dfd
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@7cd462fd
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.8)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@60523192
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@61117dfd[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@151b81b4
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@2013bee9, container=net.minecraft.server.v1_8_R3.ServerConnection@51bcd5d8, previous=io.github.repooper.packetevents.Vulcan_Tz@18e3f87a, current=com.comphenix.protocol.injector.netty.BootstrapList@182f2719, previousLoaded=true, currentSet=true, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@25f62603
      networkManagers=io.github.repooper.packetevents.Vulcan_Tz@12d33570
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@15742f78
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@7482d520
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@6050338d
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@6b23e242
      invoker=com.comphenix.protocol.injector.PacketFilterManager@565c282
      reporter=com.comphenix.protocol.ProtocolLib$1@2a7d32d0
      debug=false
    ]
  Version:
    ProtocolLib v4.5.0
  Java Version:
    1.8.0_352
  Server:
    1.8.8-R0.1-SNAPSHOT (MC: 1.8.8)

**Comment by lukalt** [comment]
Please try if this problem persists in the latest release (https://www.spigotmc.org/resources/protocollib.1997/download?version=443701)
