### ISSUE TITLE
Internal exception

### ISSUE THREAD

**Issue by rishabhk571** [dmulloy2/ProtocolLib#2347]
- [ ] This issue is not solved in a development build

**Describe the bug**
So before installing ProtocolLib, i was having SimpleScore Plugin, idk what happened to simplescore plugin after i installed protocol lib, some errors started spamming in console

**To Reproduce**
1. Install Latest SimpleScore
2. Install Latest ProtocolLib

**Expected behavior**
No error or warnings

**Screenshots**
**ProtocolLib Side warning** :
```[05:32:38 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 32!
[05:32:38 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 64!
[05:32:43 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 128!
[05:32:48 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 256!
[05:33:01 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 512!
[05:33:30 WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 1024!```

**SimpleScore side error**:
```[05:11:01 ERROR]: Could not pass event PlayerMoveEvent to SimpleScore v3.12.2
java.lang.RuntimeException: An internal error occured.
        at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:22) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$0(StructureCache.java:75) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:83) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:95) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:130) ~[ProtocolLib.jar:?]
        at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard$lambda-0(ProtocolScoreboard.kt:27) ~[SimpleScore-3.12.2.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.createScoreboard(ProtocolScoreboard.kt:26) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.ScoreboardManager.updateScoreboardState$SimpleScore(ScoreboardManager.kt:89) ~[SimpleScore-3.12.2.jar:?]
        at com.r4g3baby.simplescore.scoreboard.listeners.PlayerListener.onPlayerMove(PlayerListener.kt:43) ~[SimpleScore-3.12.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.netty.handler.codec.DecoderException: Received unexpected null component
        at net.minecraft.network.FriendlyByteBuf.readComponent(FriendlyByteBuf.java:494) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetObjectivePacket.<init>(ClientboundSetObjectivePacket.java:33) ~[?:?]
        at jdk.internal.reflect.GeneratedConstructorAccessor76.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultConstrutorAccessor.invoke(DefaultConstrutorAccessor.java:16) ~[ProtocolLib.jar:?]
        ... 33 more```

**Version Info**
(https://pastebin.com/zZrxckHp)< This Pastebin is after i removed simplescore.jar

**Additional context**
Add any other context about the problem here.

**Comment by lukalt** [comment]
The version of ProtocolLib (4.8.0) is incompatible with MC 1.19.3. Try this build: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar

**Comment by rishabhk571** [comment]
Thanks, Fixed!

**Comment by lukalt** [comment]
@rishabhk571 The version is currently not a stable release. But it is linked at the top of https://www.spigotmc.org/resources/protocollib.1997/

**Comment by rishabhk571** [comment]
> @rishabhk571 The version is currently not a stable release. But it is linked at the top of https://www.spigotmc.org/resources/protocollib.1997/

Ok you can close the issue..

**Comment by Jeppa** [comment]
I think he can't, but you can ;)
