### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by anthgodz** [dmulloy2/ProtocolLib#2353]
Protocol lib keeps giving me errors such as

"
[12:37:38 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@42d30ff2[
      memoryAddress=140462946048224
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@553b1cdf
      chunk=Chunk(1d4fc056: 29%, 1179648/4194304)
      handle=2814779831877632
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=40960
      length=26
      maxLength=32
      cache=io.netty.buffer.PoolThreadCache@2d185d8e
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@43860a08[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@30f82521
        packetListeners=[PacketAdapter[plugin=AdvancedReplay, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_DESTROY[class=PacketPlayOutEntityDestroy, id=58], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_DESTROY[class=PacketPlayOutEntityDestroy, id=58], USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AdvancedReplay, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=56], ENTITY_DESTROY[class=PacketPlayOutEntityDestroy, id=58], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=98], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27], BLOCK_DIG[class=PacketPlayInBlockDig, id=26], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=41], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=43], REL_ENTITY_MOVE_LOOK[class=PacketPlayOu
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@40993e0b
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@59de1ccd
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2afb8bb4
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5b5b62e7
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@52bb76e1
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-466,minecraftVersion=1.19.4}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@dfaa2f5
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=8
        packetCreation=true
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7686d626
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4e274c1c
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.4)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@4c065596[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@57d8810a
      player=CraftPlayer{name=anthgodz}
      updated=<null>
      playerName=anthgodz
      playerConnection=net.minecraft.server.network.PlayerConnection@1ab47a44
      networkManager=net.minecraft.network.NetworkManager@5987761a
      originalChannel=[id: 0x341faae7, L:/240.4.14.95:25575 - R:/240.4.92.212:57718]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@5987761a, previous=[id: 0x341faae7, L:/240.4.14.95:25575 - R:/240.4.92.212:57718], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@4848ed39, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@38722acd
      vanillaDecoder=net.minecraft.network.PacketDecoder@5aa7bc7f
      vanillaEncoder=net.minecraft.network.PacketEncoder@94ce35e
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7686d626
      processor=com.comphenix.protocol.injector.NetworkProcessor@2fef8028
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 26, widx: 26, cap: 26)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@607c3b51
      singleDecode=false
      first=true
      firedChannelRead=false
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.1
  Server:
    git-Paper-466 (MC: 1.19.4)
"
And it keeps spamming my chat with them! How do I prevent it from broadcasting errors!?

**Comment by x-exe** [comment]
I have same eror

**Comment by x-exe** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/   just download here
