### ISSUE TITLE
Hi there i need your help

### ISSUE THREAD

**Issue by v3lux** [dmulloy2/ProtocolLib#237]
HI there !
I have a little probleme 
01:16:42] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72]
at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_72]
at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:177) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:809) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-f6feaaa-f326992]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Can you help me ?? 

thx

**Comment by dmulloy2** [comment]
This doesn't appear to be a ProtocolLib issue.
