### ISSUE TITLE
trying to start protocollib on 1.16.5 ghcr.io/pterodactyl/yolks:java_16j9

### ISSUE THREAD

**Issue by walmorhenrique** [dmulloy2/ProtocolLib#2374]
[19:33:34 INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-636
[19:33:34 INFO]: Error Cannot enable ProtocolLib. (java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.v1_16_R3.ServerConnection.listeningChannels) occurred in ProtocolLib v5.0.0-SNAPSHOT-636.
[19:33:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.v1_16_R3.ServerConnection.listeningChannels
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.inject(NetworkManagerInjector.java:203)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:458)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:336)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3175/0x00000000a5e7d7d0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:883)
  Caused by: java.lang.IllegalAccessException: illegal setter on final field
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:1084)
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
        ... 14 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1cdc5db3[
        plugin=ProtocolLib v5.0.0-SNAPSHOT-636
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1171,minecraftVersion=1.16.5}
        reporter=com.comphenix.protocol.ProtocolLib$1@d58f19bf
        minecraftVersion=(MC: 1.16.5)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@94ea6a68
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4f67f2ec
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@beeb1cbd
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@61ae11b5
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@778f6a16
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@f265eb85
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@f6b9fa82
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@bd21d250[
      statistics=<null>
      packetTask=-1
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@e674050d
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@ab4baec0
      commandProtocol=com.comphenix.protocol.CommandProtocol@f7ae009b
      commandPacket=com.comphenix.protocol.CommandPacket@60d7f11c
      commandFilter=com.comphenix.protocol.CommandFilter@e17373a0
      packetLogging=com.comphenix.protocol.PacketLogging@27f08067
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@8dbb1cb2
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1171,minecraftVersion=1.16.5}
      file=plugins/ProtocolLib (3).jar
      description=org.bukkit.plugin.PluginDescriptionFile@a56a03a0
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.0.0-SNAPSHOT-636, pluginEnabled=true, url=plugins/ProtocolLib (3).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@992857b1
    ]
  Version:
    ProtocolLib v5.0.0-SNAPSHOT-636
  Java Version:
    16.0.2
  Server:
    git-Purpur-1171 (MC: 1.16.5)

[19:33:34 INFO]: [ProtocolLib] Disabling ProtocolLib v5.0.0-SNAPSHOT-636

**Comment by walmorhenrique** [comment]
@dmulloy2 help-me please :(

**Comment by lukalt** [comment]
Use ProtocolLib 4.8.0 for now. The problem should not occur there.

**Comment by pabloalba16** [comment]
You can use Java 17 with -DPaper.IgnoreJavaVersion=true on your startup parameters and Protocollib 5.0.0 will work as expected
