### ISSUE TITLE
Bug Report on Puffer core

### ISSUE THREAD

**Issue by panepepan** [dmulloy2/ProtocolLib#2380]
java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Unknown Source)
Dump:
Parameters:
io.netty.buffer.PooledUnsafeDirectByteBuf@fc32996[
memoryAddress=140624477189872
recyclerHandle=NOOP_HANDLE
chunk=Chunk(6c26bb9c: 1%, 24576/4194304)
handle=1125929971613696
memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
offset=16384
length=256
maxLength=256
cache=io.netty.buffer.PoolThreadCache@4416307f
tmpNioBuf=<null>
allocator=PooledByteBufAllocator(directByDefault: true)
refCnt=2
readerIndex=20
writerIndex=20
markedReaderIndex=0
markedWriterIndex=0
maxCapacity=2147483647
]
manager:
com.comphenix.protocol.injector.PacketFilterManager@72741684[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2b57b90d
packetListeners=[PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5eb7f1d0
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7564bc5a
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@27765444
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@31ff1e76
hasClosed=false
classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
reporter=com.comphenix.protocol.ProtocolLib$1@50a750e8
server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1966,minecraftVersion=1.19.4}
library=ProtocolLib v4.8.0
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@15b000e4
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=1
packetCreation=false
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@2e678abd
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5f670e0b
hasRecycleDistance=true
minecraftVersion=(MC: 1.19.4)
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ChannelInjector@154d0e70[
decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
factory=com.comphenix.protocol.injector.netty.InjectionFactory@739b888c
player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@ed82601
upda
ted=<null>
playerName=<null>
playerConnection=<null>
networkManager=net.minecraft.network.NetworkManager@5413ed5b
originalChannel=[id: 0x7574635b, L:/172.19.0.14:52610 - R:/94.112.255.125:46582]
channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@5413ed5b, previous=[id: 0x7574635b, L:/172.19.0.14:52610 - R:/94.
112.255.125:46582], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@685150b0, previousLoaded=true, currentSet=true, forceAccess=true]
packetMarker={}
currentEvent=<null>
finalEvent=<null>
unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@42005cb0
vanillaDecoder=net.minecraft.network.PacketDecoder@20b64090
vanillaEncoder=net.minecraft.network.PacketEncoder@caa6c52
finishQueue=[]
channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@2e678abd
processor=com.comphenix.protocol.injector.NetworkProcessor@6b648422
injected=true
closed=false
cumulation=PooledUnsafeDirectByteBuf(ridx: 20, widx: 20, cap: 256)
cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@79c4eb1e
singleDecode=false

**Comment by lukalt** [comment]
ProtocolLib 4.8.0 does NOT support Minecraft 1.19 or later. Use this version: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1
