### ISSUE TITLE
Bug when starting

### ISSUE THREAD

**Issue by granpacho** [dmulloy2/ProtocolLib#2381]
I am on 1.19.4 and I am getting and issue and it said to post it here so:

Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
  	at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
  	at ProtocolLib (1).jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@67c3d0e3[
      memoryAddress=140110222379952
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@6bf0f4b8
      chunk=Chunk(40b935ae: 1%, 32768/4194304)
      handle=1125929971613698
      memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
      offset=16896
      length=256
      maxLength=256
      cache=io.netty.buffer.PoolThreadCache@584f3cf9
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=2
      readerIndex=1
      writerIndex=1
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@456d394d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@2b99f55b
        packetListeners=[PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[RECIPE_UPDATE[class=PacketPlayOutRecipeUpdate, id=102]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ChatControl, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=49]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[AUTO_RECIPE[class=PacketPlayInAutoRecipe, id=24], AUTO_RECIPE[class=PacketPlayOutAutoRecipe, id=49]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ChatControl, sending=ListeningWhitelist[priority=NORMAL, packets=[CHAT[PLAY, SERVER, 15, classNames: [net.minecraft.network.protocol.game.PacketPlayOutChat, net.minecraft.network.protocol.game.ClientboundChatPacket, net.minecraft.network.play.server.SPacketChat] (unregistered)]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[RESPAWN[class=PacketPlayOutRespawn, id=61]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=HIGHEST, packets=[MOUNT[class=PacketPlayOutMount, id=84]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=MONITOR, packets=[RESOURCE_PACK_SEND[class=PacketPlayOutResourcePackSend, id=60]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemsAdder, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=ItemsAdder, sending=ListeningWhitelist[priority=LOWEST, packets=[RECIPES[class=PacketPlayOutRecipes, id=57]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WildStacker, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=SuperiorSkyblock2, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[SETTINGS[class=PacketPlayInSettings, id=5]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=PlayerAuctions, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f8e8264
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@776d53dc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5b66bb2d
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3f31ae37
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins/ProtocolLib (1).jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@54479617
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-524,minecraftVersion=1.19.4}
        library=ProtocolLib v4.8.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@27f8a92b
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=19
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@180f72e2
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@5a18e745
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.19.4)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@2c3877ec[
      decodeBuffer=protected void net.minecraft.network.PacketDecoder.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
      encodeBuffer=protected void net.minecraft.network.PacketEncoder.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@6bb22a4b
      player=com.comphenix.protocol.injector.server.TemporaryPlayerInvocationHandler@198b4299
      updated=<null>
      playerName=<null>
      playerConnection=<null>
      networkManager=net.minecraft.network.NetworkManager@60b6cd83
      originalChannel=[id: 0xdc77dd09, L:/172.18.0.2:25567 - R:/172.18.0.1:57146]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManager@60b6cd83, previous=[id: 0xdc77dd09, L:/172.18.0.2:25567 - R:/172.18.0.1:57146], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@63672163, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@20bb381c
      vanillaDecoder=net.minecraft.network.PacketDecoder@76b7335d
      vanillaEncoder=net.minecraft.network.PacketEncoder@7494afa
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@180f72e2
      processor=com.comphenix.protocol.injector.NetworkProcessor@24fdb722
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@652ba87b
      singleDecode=false
      first=true
      firedChannelRead=true
      selfFiredChannelRead=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.7
  Server:
    git-Paper-524 (MC: 1.19.4)

**Comment by lukalt** [comment]
The version of ProtocolLib you are using is not compatible with 1.19.4. Use this one: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1
