### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Impzu** [dmulloy2/ProtocolLib#2382]
I don't know what this means, but it told me to report it: 
05.05 05:15:26 [Server] INFO Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@7fbeced7.
05.05 05:15:26 [Server] ERROR [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
05.05 05:15:26 [Server] INFO If this problem hasn't already been reported, please open a ticket
05.05 05:15:26 [Server] INFO at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
05.05 05:15:26 [Server] INFO Stack Trace:
05.05 05:15:26 [Server] INFO java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
05.05 05:15:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
05.05 05:15:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
05.05 05:15:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
05.05 05:15:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
05.05 05:15:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
05.05 05:15:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
05.05 05:15:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
05.05 05:15:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
05.05 05:15:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
05.05 05:15:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
05.05 05:15:26 [Server] INFO at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
05.05 05:15:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
05.05 05:15:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
05.05 05:15:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
05.05 05:15:26 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
05.05 05:15:27 [Multicraft] Skipped 388 lines due to rate limit (160/s)

**Comment by lukalt** [comment]
If you are running Minecraft 1.19 or later, ensure that you are using this version of ProtocolLib: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0-rc1
