### ISSUE TITLE
something wrong with protocolib

### ISSUE THREAD

**Issue by Chalityst** [dmulloy2/ProtocolLib#2398]
Sorry i'm not good at english.

I'm not sure about that.
I downloaded this plugin from spigotmc latest version (5.0.0) and tried to run server.
I got this error 

[07:33:54] [Server thread/ERROR]: Could not load 'plugins\ProtocolLib.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:92) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]

and sometime i got another error

You're using old version we're trying to download new version from https://ci.dmulloy2.net/job/ProtocolLib/ and then error like website that fetch java file is download (protocolib site).

So i check in plugin.yml file with Winrar that 5.0.0 version but now my server working with 5.1.0-SNAPSHOT-644 version that download from https://ci.dmulloy2.net/job/ProtocolLib/.

**Comment by lukalt** [comment]
Please share the whole error and not just the first 4 lines. The relevant part is omitted
