### ISSUE TITLE
As you enter the game gives error again and again.

### ISSUE THREAD

**Issue by Belo213** [dmulloy2/ProtocolLib#242]
`Stack Trace:
  java.lang.IllegalStateException: Failed to obtain login start packet. Did you build Spigot with BuildTools?
        at com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:592)
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:534)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters:
    io.netty.buffer.UnpooledHeapByteBuf@57d45c8b[
      alloc=UnpooledByteBufAllocator(directByDefault: true)
      array={13,64,125,61,49,97,-14,76,116,64,86,79,-113,-119,87,18,-108,64,-121,61,102,-18,-124,-22,2,-63,73,-94,0,64,73,-103,-115,0}
      tmpNioBuf=<null>
      refCnt=1
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
      swappedBuf=<null>
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@a96bfe0[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@65f36aee
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3f67d0d9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@57c2558
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@3aaaf3a8
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@44705a09
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4590bb46
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@207a017e
        reporter=com.comphenix.protocol.ProtocolLib$1@21221049
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-9797151-301db84,minecraftVersion=1.10.2}
        library=ProtocolLib v4.0.2
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@a1e3bf2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@84c3a2e
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@656e6f50
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.10.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@3669d5a0
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@5c4d1e7[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1eda8af3
      player=CraftPlayer{name=MeliksahMELO}
      updated=<null>
      playerName=MeliksahMELO
      playerConnection=<null>
      networkManager=net.minecraft.server.v1_10_R1.NetworkManager@5266c91f
      originalChannel=[id: 0x3ca650e1, /127.0.0.1:58051 => /127.0.0.1:25565]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_10_R1.NetworkManager.channel], container=net.minecraft.server.v1_10_R1.NetworkManager@5266c91f, previous=[id: 0x3ca650e1, /127.0.0.1:58051 => /127.0.0.1:25565], current=com.comphenix.protocol.injector.netty.ChannelInjector$5@1ec01845, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@68fdc713
      vanillaDecoder=net.minecraft.server.v1_10_R1.PacketDecoder@cb7d522
      vanillaEncoder=net.minecraft.server.v1_10_R1.PacketEncoder@7488de07
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@84c3a2e
      processor=com.comphenix.protocol.injector.NetworkProcessor@6cd775fd
      injected=true
      closed=false
      cumulation=UnpooledHeapByteBuf(ridx: 34, widx: 34, cap: 34)
      singleDecode=false
      decodeWasNull=false
      first=true
      added=true
    ]
  Version:
    ProtocolLib v4.0.2
  Java Version:
    1.8.0_101
  Server:
    git-Spigot-9797151-301db84 (MC: 1.10.2)`

It gives that error. What is this? Please help me.

**Comment by games647** [comment]
From the stacktrace:
>Did you build Spigot with BuildTools?

Did you?

**Comment by Belo213** [comment]
Do I need to do? So it makes work, isn't it?

**Comment by Belo213** [comment]
I did but it gives that error again. I built spigot with buildtools.jar.

**Comment by dmulloy2** [comment]
Are you using a non-English locale? Sometimes that causes issues like this.

**Comment by Belo213** [comment]
Yes, what should I do?

**Comment by dmulloy2** [comment]
Your best bet is to just run your servers in English: https://hub.spigotmc.org/jira/browse/BUILDTOOLS-251?focusedCommentId=20176&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20176
