### ISSUE TITLE
I think you will understand everything from the log. Fix this error

### ISSUE THREAD

**Issue by f1ttJK** [dmulloy2/ProtocolLib#2427]
MiniMessageAnywhere ( MMA ) minecraft plugin by [@gepron1x](https://github.com/gepron1x) ( Gepron1x#3982 )

`[23:00:04 ERROR]: [MiniMessageAnywhere] Unhandled exception occurred in onPacketSending(PacketEvent) for MiniMessageAnywhere
java.lang.IllegalStateException: Unable to set value of field private final java.util.EnumSet net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket.a
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:359) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:322) ~[ProtocolLib.jar:?]
        at me.gepron1x.minimessageanywhere.packetlistener.out.PlayerInfoListener.onPacketSending(PlayerInfoListener.java:37) ~[MiniMessageAnywhere-2.2.2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at net.minecraft.server.players.PlayerList.tick(PlayerList.java:978) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1598) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast java.util.ArrayList to java.util.EnumSet
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.set(DefaultFieldAccessor.java:41) ~[ProtocolLib.jar:?]
        ... 25 more
[23:00:04 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@78b55c17[
    a=[UPDATE_LATENCY]
    b=[b[profileId=ef7d272d-7cab-39d5-8873-49a33c49f62e, profile=com.mojang.authlib.GameProfile@782ebf9b[id=ef7d272d-7cab-39d5-8873-49a33c49f62e,name=f1tt,properties={textures=[com.mojang.authlib.properties.Property@158d170b]},legacy=false], listed=true, latency=0, gameMode=CREATIVE, displayName=null, chatSession=null]]
  ]`

**Comment by dmulloy2** [comment]
MMA needs to update their code. Can't pass an ArrayList when it's expecting an EnumSet
