### ISSUE TITLE
[bug][folia]Exception in thread "Timer-0" java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by cgw2023** [dmulloy2/ProtocolLib#2447]
- [✅] This issue is not solved in a development build

**Describe the bug**
error occur

**To Reproduce**
1. start server
2. enter server 

**Expected behavior**
no error

**Screenshots**
![image](https://github.com/dmulloy2/ProtocolLib/assets/61608872/8066a8cb-e70c-4435-9a4c-aa6f64e2203b)

**Version Info**
https://paste.denizenscript.com/View/111366

**Additional context**

**Comment by GeorgeV220** [comment]
The latest dev build also have problems,
in line https://github.com/dmulloy2/ProtocolLib/blob/master/src/main/java/com/comphenix/protocol/async/AsyncListenerHandler.java#L331 it throws 
```
[16:04:27 ERROR]: Error occurred while enabling FastLogin v1.12-SNAPSHOT-c106089 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:257) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:244) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:189) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:158) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at com.comphenix.protocol.async.AsyncListenerHandler.scheduleAsync(AsyncListenerHandler.java:331) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.start(AsyncListenerHandler.java:282) ~[ProtocolLib.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.register(ProtocolLibListener.java:104) ~[FastLoginBukkit.jar:?]
        at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:117) ~[FastLoginBukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[kaiiju-1.20.1.jar:git-Kaiiju-"7303daf"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```
Kaiiju 1.20.1 Folia fork (I know that ProcotolLib is not fully tested/updated to 1.20.1)

**Comment by colinpapa** [comment]
Have you solved the problem you raised? I saw that you also asked a question about a server crash (manifested as being unable to enter, some players' time standing still) so I wanted to ask if you have solved this problem, because my server is also having the same problem, which occurs every few hours
