### ISSUE TITLE
GetEntityTrackers Throws Error on Folia 1.20.1

### ISSUE THREAD

**Issue by LOOHP** [dmulloy2/ProtocolLib#2461]
- [x] This issue is not solved in a development build

**Describe the bug**
When using the `getEntityTrackers` method in ProtocolLib on Folia 1.20.1, an error occurs. Probably due to a field that doesn't exist anymore in Folia.
See `Additional context` for the full error.

**To Reproduce**
1. Execute the method `ProtocolLibrary.getProtocolManager().getEntityTrackers(entity);`

**Expected behavior**
Method executes and returns as normal.

**Screenshots**
N/A

**Version Info**
https://pastebin.com/nTK0nQjT

**Additional context**
Full Error:
```
[19:40:24] [Region Scheduler Thread #0/WARN]: [ImageFrame] Global task for ImageFrame v1.7.4.1 generated an exception
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 1, banned: 1000], type={ type exactly interface it.unimi.dsi.fastutil.ints.Int2ObjectMap }}
	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getNewEntityTracker(EntityUtilities.java:226) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:247) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getTrackedPlayers(EntityUtilities.java:180) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackers(EntityUtilities.java:163) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityTrackers(PacketFilterManager.java:416) ~[ProtocolLib.jar:?]
	at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.tick(AnimatedFakeMapManager.java:92) ~[ImageFrame-1.7.4.1.jar:?]
	at com.loohp.imageframe.objectholders.AnimatedFakeMapManager.lambda$new$0(AnimatedFakeMapManager.java:70) ~[ImageFrame-1.7.4.1.jar:?]
	at com.loohp.imageframe.objectholders.Scheduler.lambda$runTaskTimer$9(Scheduler.java:144) ~[ImageFrame-1.7.4.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:178) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:36) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:283) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"7c6e251"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by retrooper** [comment]
Why are you sending me a ProtocolLib issue? I don't maintain ProtocolLib.
