### ISSUE TITLE
[Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.

### ISSUE THREAD

**Issue by Jlov0** [dmulloy2/ProtocolLib#2468]
[07:38:47] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
        at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:533)
        at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:504)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:77)
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1209)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:375)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1156)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:981)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296)
        at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@7d229492[
        plugin=ProtocolLib v5.0.0
        server=CraftServer{serverName=CraftBukkit,serverVersion=3815-Bukkit-9f64f0d,minecraftVersion=1.20.1}
        reporter=com.comphenix.protocol.ProtocolLib$1@306d925b
        minecraftVersion=(MC: 1.20.1)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2a6ba71f
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@438420c4
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4075b51
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5824fec0
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@2f00f984
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@4de07ea0
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@7383799e
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@c2e4bd0[
      statistics=com.comphenix.protocol.metrics.Statistics@24ca4f08
      packetTask=8
      tickCounter=20
      configExpectedMod=1
      updater=<null>
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@6a91304f
      commandProtocol=com.comphenix.protocol.CommandProtocol@236eb0a
      commandPacket=com.comphenix.protocol.CommandPacket@7cb85057
      commandFilter=com.comphenix.protocol.CommandFilter@afcf2c7
      packetLogging=com.comphenix.protocol.PacketLogging@698ca89f
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@5c57701f
      server=CraftServer{serverName=CraftBukkit,serverVersion=3815-Bukkit-9f64f0d,minecraftVersion=1.20.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6253b92a
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@67cfee4c
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@3109c58
    ]
  Version:
    ProtocolLib v5.0.0
  Java Version:
    17.0.7
  Server:
    3815-Bukkit-9f64f0d (MC: 1.20.1)

**Comment by lukalt** [comment]
Update to the latest dev build for ProtocolLib 5.1.0 (https://ci.dmulloy2.net/job/ProtocolLib/654/artifact/build/libs/ProtocolLib.jar). Version 5.0.0 does not support MC 1.20.1
