### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by KatSleep** [dmulloy2/ProtocolLib#2493]
[03:39:01] [Server thread/ERROR] [Minecraft]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/compiler/StructureCompiler
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler.initializeCompiler(BackgroundCompiler.java:131)
        at com.comphenix.protocol.reflect.compiler.BackgroundCompiler.<init>(BackgroundCompiler.java:109)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:159)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:410)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:349)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:352)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:623)
        at java.lang.Thread.run(Thread.java:750)
  Caused by: java.lang.ClassNotFoundException: Failed to remap class com.comphenix.protocol.reflect.compiler.StructureCompiler
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:216)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 12 more
  Caused by: java.lang.NoClassDefFoundError: org/magmafoundation/magma/remapper/proxy/ProxyClassWriter
        at org.magmafoundation.magma.remapper.remappers.ReflectionMethodRemapper.redirectVirtual(ReflectionMethodRemapper.java:150)
        at org.magmafoundation.magma.remapper.remappers.ReflectionMethodRemapper.visitMethodInsn(ReflectionMethodRemapper.java:114)
        at org.objectweb.asm.tree.MethodInsnNode.accept(Unknown Source)
        at org.objectweb.asm.tree.InsnList.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
        at org.magmafoundation.magma.remapper.utils.RemappingUtils.remapFindClass(RemappingUtils.java:113)
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:202)
        ... 16 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@de1b87e[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4db9c523
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3abda909
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@7f416fdb
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@7fe30a05
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7c705807
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2bd25361
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@5d5cacdb
        reporter=com.comphenix.protocol.ProtocolLib$1@5f99ce77
        server=CraftServer{serverName=Magma,serverVersion=1.12.2-15ea32c3,minecraftVersion=1.12.2}
        library=ProtocolLib v4.4.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@460393dd
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@66f542c6
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@52cc58e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@2b5cd1b9
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@1c77affd[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4db9c523
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.BukkitUpdater@c74a767
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@1fb9f89
      commandProtocol=com.comphenix.protocol.CommandProtocol@5ba811e7
      commandPacket=com.comphenix.protocol.CommandPacket@32990c6c
      commandFilter=com.comphenix.protocol.CommandFilter@1bffdac7
      packetLogging=com.comphenix.protocol.PacketLogging@46a509e6
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@5d990ffc
      server=CraftServer{serverName=Magma,serverVersion=1.12.2-15ea32c3,minecraftVersion=1.12.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2799924f
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@5d5cacdb
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@2cd1960c
    ]
  Version:
    ProtocolLib v4.4.0
  Java Version:
    1.8.0_362
  Server:
    1.12.2-15ea32c3 (MC: 1.12.2)
[03:39:01] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib]: [ProtocolLib] Disabling ProtocolLib v4.4.0

**Comment by KatSleep** [comment]
I need help

**Comment by lukalt** [comment]
ProtocolLib 4.4.0 ist already quite dated. Please try out Protocol Lib 5.0.0: https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0
