### ISSUE TITLE
INTERNAL ERROR: Cannot perform automatic updates.

### ISSUE THREAD

**Issue by PetrovEvgeniy** [dmulloy2/ProtocolLib#2495]
[ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
  	at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:540)
  	at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:511)
  	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:77)
  	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
  	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1209)
  	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:375)
  	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1156)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:981)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296)
  	at java.base/java.lang.Thread.run(Thread.java:1623)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@19f0722f[
        plugin=ProtocolLib v5.1.0-SNAPSHOT-661
        server=CraftServer{serverName=CraftBukkit,serverVersion=3843-Bukkit-4be756e,minecraftVersion=1.20.1}
        reporter=com.comphenix.protocol.ProtocolLib$1@79a33671
        minecraftVersion=(MC: 1.20.1)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7f0c0292
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@65f76656
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@36e84d6a
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5618e578
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@491f75bb
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@17847f18
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@6373f39f
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@7251f9ac[
      statistics=com.comphenix.protocol.metrics.Statistics@40d1f8f0
      packetTask=com.comphenix.protocol.scheduler.DefaultTask@7419234d
      tickCounter=20
      configExpectedMod=1
      updater=<null>
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@756bcd7e
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3a32ad5b
      commandProtocol=com.comphenix.protocol.CommandProtocol@78ce21b
      commandPacket=com.comphenix.protocol.CommandPacket@59122ba9
      commandFilter=com.comphenix.protocol.CommandFilter@72390dc8
      packetLogging=com.comphenix.protocol.PacketLogging@5dce3ea1
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@3db29339
      server=CraftServer{serverName=CraftBukkit,serverVersion=3843-Bukkit-4be756e,minecraftVersion=1.20.1}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@75b5a845
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2aed125c
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@63cfb81a
    ]
  Version:
    ProtocolLib v5.1.0-SNAPSHOT-661
  Java Version:
    20.0.2
  Server:
    3843-Bukkit-4be756e (MC: 1.20.1)

**Comment by PetrovEvgeniy** [comment]
I would really appreciate if somebody could suggest how do I fix this issue 🙂

**Comment by lukalt** [comment]
Hi, I suspect that there is another error before the stack trace you uploaded in the log, probably at "Enabling ProtocolLib" or "Loading ProtcolLib".  The error you send is likely a result of a previous error.
Please check your logs and send us any other errors from the log.

Also, I am not sure how well ProtocolLib is compatible with Java 20. Please try out Java 17 Hotspot and see if this resolves the error.
