### ISSUE TITLE
ProtocolLib cannot be enabled.

### ISSUE THREAD

**Issue by QWQxiaoxiaoSama** [dmulloy2/ProtocolLib#2496]
[ProtocolLib] Enabling ProtocolLib v5.1.0-SNAPSHOT-661
[14:29:39 INFO]: Error Cannot enable ProtocolLib. (java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.v1_16_R3.ServerConnection.listeningChannels) occurred in ProtocolLib v5.1.0-SNAPSHOT-661.
[14:29:39 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.server.v1_16_R3.ServerConnection.listeningChannels
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.inject(NetworkManagerInjector.java:203)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:456)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:344)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3152/0x000000001605cef0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.IllegalAccessException: illegal setter on final field
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(Unknown Source)
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
        ... 14 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@d147bb0b[
        plugin=ProtocolLib v5.1.0-SNAPSHOT-661
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-794,minecraftVersion=1.16.5}
        reporter=com.comphenix.protocol.ProtocolLib$1@d6f283ee
        minecraftVersion=(MC: 1.16.5)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@b3035303
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4512c2dd
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@f7570b63
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@54d6c218
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@cffeaf6
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@1ef75e3a
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@e892d5cc
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@a2c29d24[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@9c7005b0
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@ecf29c7
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@784339d7
      commandProtocol=com.comphenix.protocol.CommandProtocol@624b67a6
      commandPacket=com.comphenix.protocol.CommandPacket@124bb2a3
      commandFilter=com.comphenix.protocol.CommandFilter@8d91594
      packetLogging=com.comphenix.protocol.PacketLogging@d355f321
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@2c2e9ceb
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-794,minecraftVersion=1.16.5}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@3d357031
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0-SNAPSHOT-661, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@d9faf7af
    ]
  Version:
    ProtocolLib v5.1.0-SNAPSHOT-661
  Java Version:
    16.0.2
  Server:
    git-Paper-794 (MC: 1.16.5)

**Comment by QWQxiaoxiaoSama** [comment]
I need help:(((

**Comment by Targex25** [comment]
i have the same issue
