### ISSUE TITLE
Problem with the ProtocolLib (MC 1.8)

### ISSUE THREAD

**Issue by StreetHD** [dmulloy2/ProtocolLib#250]
Stack Trace:
  java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:245)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:206)
  	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
  	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
  	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
  	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelInboundHandler
  	at java.net.URLClassLoader.findClass(Unknown Source)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
  	at java.lang.ClassLoader.loadClass(Unknown Source)
  	at java.lang.ClassLoader.loadClass(Unknown Source)
  	... 8 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@4d732e0d[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3520ba39
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@16e70811
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@5ec4c689
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1.7.9-R0.2-205-g0a049fa,minecraftVersion=1.7.10}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@41100889
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@845cd0e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@179144de
    ]
  Version:
    ProtocolLib v4.1.0-SNAPSHOT-b315
  Java Version:
    1.8.0_60
  Server:
    git-Spigot-1.7.9-R0.2-205-g0a049fa (MC: 1.7.10)

**Comment by dmulloy2** [comment]
Well you're using 1.7.10, not 1.8. Use 3.6.5 until the 3.7 branch is finished.

**Comment by dmulloy2** [comment]
Try the 3.7.0 release: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
