### ISSUE TITLE
"ProtocolLib does not support plugin reloaders" error on server start

### ISSUE THREAD

**Issue by HiddenDeath** [dmulloy2/ProtocolLib#2505]
Hi, I use Magma 1.12.2 server on latest version, and today I got a problem. On server startup I get this error:

```
[20:07:51] [Server thread/ERROR] [Minecraft]: ******************************************************
[20:07:51] [Server thread/ERROR] [Minecraft]: *** ProtocolLib does not support plugin reloaders! ***
[20:07:51] [Server thread/ERROR] [Minecraft]: *** Please use the built-in reload command!        ***
[20:07:51] [Server thread/ERROR] [Minecraft]: ******************************************************
```

I don't have PlugMan installed. I also use nLogin, and I tried to start the server without it, but PL still doesn't work. Please help

**Comment by HiddenDeath** [comment]
Oh, I forgot to say, that I'm using PL version 5.1.0. I also tried to use 4.5.1 and 5.1.1 snapshot versions, but they didn't work as well, and 4.6.0, but then i get timed out

**Comment by lukalt** [comment]
Hello,

by design, ProtocolLib does not support PlugMan. If you do not reload ProtocolLib using PlugMan, everything should work fine though. In this case, you can ignore the error message. It can be understood more as a warning.

**Comment by HiddenDeath** [comment]
After this error message, the plugin disables itself, so I can't ignore this error, and this happens on server startup

**Comment by lukalt** [comment]
I just had a look at the source code and the error message might be misleading and an error might occur previously. Please check your log for other errors related to ProtocolLib.

Also, just for confirmation: You simply put ProtocolLib into the `plugins/` folder and do not load it using PlugMan?

**Comment by HiddenDeath** [comment]
Yes, I have another error:
```
[19:54:28] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_12_R1.CraftServer]: null initializing ProtocolLib v5.1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:327) ~[CraftServer.class:1.12.2-47c7ac0b]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:351) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:623) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
Caused by: java.lang.NullPointerException
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftPackage(MinecraftReflection.java:178) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getOptionalNMS(MinecraftReflection.java:1391) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1445) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:620) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.packet.PacketRegistry.<clinit>(PacketRegistry.java:85) ~[ProtocolLib.jar:?]
	... 8 more
```
And I put ProtocolLib into the plugins/ folder and load the plugin normally. As I said, I don't have PlugMan.

**Comment by lukalt** [comment]
Oh, im sorry. I misread your message and thought you were using PlugMan. 

As far as I understood, Magma is a version of a Forge Server that implements the Bukkit API. Unfortunately, ProtocolLib cannot support this. It only support Spigot/CraftBukkit and forks of it.
