### ISSUE TITLE
ProtocolLib-Error

### ISSUE THREAD

**Issue by ByOuHuang** [dmulloy2/ProtocolLib#2507]
[ProtocolLib] Loading ProtocolLib v5.1.1-SNAPSHOT-665
[15:00:11 WARN]: java.lang.IllegalStateException: Unable to access field private final org.bukkit.craftbukkit.v1_8_R3.CraftWorld net.minecra
ft.server.v1_8_R3.World.world
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:56)
[15:00:11 WARN]:        at com.comphenix.protocol.wrappers.BukkitConverters.<clinit>(BukkitConverters.java:128)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.instances.MinecraftGenerator.<clinit>(MinecraftGenerator.java:30)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.instances.DefaultInstances.<clinit>(DefaultInstances.java:40)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.StructureModifier.getDefaultGenerator(StructureModifier.java:134)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.StructureModifier.<clinit>(StructureModifier.java:57)
[15:00:11 WARN]:        at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:115)
[15:00:11 WARN]:        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:294)
[15:00:11 WARN]:        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
[15:00:11 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
[15:00:11 WARN]:        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
[15:00:11 WARN]:        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
[15:00:11 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:296)
[15:00:11 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[15:00:11 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[15:00:11 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[15:00:11 WARN]: Caused by:
[15:00:11 WARN]: java.lang.IllegalAccessException: illegal setter on final field
[15:00:11 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(Unknown Source)
[15:00:11 WARN]:        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
[15:00:11 WARN]:        ... 17 more
[15:00:12 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Unable to access field private final int net.minecraft.server.v1_8_R3.EnumProtocol.i
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.comphenix.protocol.reflect.StructureModifier.getFields(StructureModifier.java:183)
        at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:116)
        at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:101)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:115)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:294)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:296)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
        at java.base/java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.IllegalAccessException: illegal setter on final field
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(Unknown Source)
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
        ... 23 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@50a2a611[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@65d1b39c
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6aba8cae
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@57932e21
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-f6fba00-9935adc,minecraftVersion=1.8.8}
      file=plugins\[P]ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@ca8bf044
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@abda40cd
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@bb4057ad
    ]
  Version:
    ProtocolLib v5.1.1-SNAPSHOT-665
  Java Version:
    11.0.19
  Server:
    git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8)

Java: https://github.com/ibmruntimes/semeru11-binaries/releases/download/jdk-11.0.19%2B7_openj9-0.38.0/ibm-semeru-open-jre_x64_windows_11.0.19_7_openj9-0.38.0.zip

I need to use version 5.0 or higher, but JDK may not be compatible. Can this issue be resolved

**Comment by lukalt** [comment]
Yes, the OpenJ9 JVM is not supported. I suggest to use OpenJDK 8 or Temurin: https://adoptium.net/de/temurin/archive/?version=8
