### ISSUE TITLE
Failed server start-up on Spigot 1.20.2

### ISSUE THREAD

**Issue by SlimeDog** [dmulloy2/ProtocolLib#2538]
- [x] This issue is not solved in a development build

**Describe the bug**
Failed server start-up with Spigot 1.20.2 and ProtocolLib 5.1.0-662

**To Reproduce**
1. Update to Spigot 1.20.2-3875
2. Start server
3. See error (below)

**Expected behavior**
Clean start-up

**Screenshots**
```
[11:41:27] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.1.0
[11:41:27] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[11:41:29] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:443)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@cb34f49[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6b2e3898
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7df1ebb3
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@7bb71937
      server=CraftServer{serverName=CraftBukkit,serverVersion=3875-Spigot-17ca32d-5dfd33d,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib-5.1.0-b662.jar
      description=org.bukkit.plugin.PluginDescriptionFile@61a90d16
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@3431ceaa
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@49b89f11
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21
  Server:
    3875-Spigot-17ca32d-5dfd33d (MC: 1.20.2)
```

**Version Info**
ProtocolLib 5.1.0-662

**Additional context**

**Comment by lukalt** [comment]
ProtocolLib is not compatible with 1.20.2 yet, which is also indicated by `Version (MC: 1.20.2) has not yet been tested!` in the log

**Comment by SlimeDog** [comment]
I am aware. I thought the error would be useful.

**Comment by CloudeLecaw** [comment]
same here with a lot of plugins. just one example because the error looks eual in most of them.

```
[08:55:10] [Server thread/ERROR]: Error occurred while enabling AdvancedGUI v2.2.7 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at me.leoko.advancedgui.AdvancedGUI.onEnable(AdvancedGUI.java:118) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketAdapter
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 20 more
```

**Comment by derklaro** [comment]
[Build 669](https://ci.dmulloy2.net/job/ProtocolLib/669/) adds support for 1.20.2. Please retry with that version.

**Comment by SlimeDog** [comment]
Confirmed fixed with build 669. Thanks.
