### ISSUE TITLE
Error on WolrdGuardExtraFlags and ConditionalEvents (1.20.1)

### ISSUE THREAD

**Issue by pgprimitz** [dmulloy2/ProtocolLib#2548]
I have these issues on my logs of minecraft and both says its a protocollib problem.

[12:35:31] [Server thread/INFO]: [ConditionalEvents] Enabling ConditionalEvents v4.40.1
[12:35:31] [Server thread/ERROR]: Error occurred while enabling ConditionalEvents v4.40.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null
	at ce.ajneb97.managers.dependencies.ProtocolLibManager.configure(ProtocolLibManager.java:33) ~[ConditionalEvents.jar:?]
	at ce.ajneb97.managers.dependencies.ProtocolLibManager.<init>(ProtocolLibManager.java:29) ~[ConditionalEvents.jar:?]
	at ce.ajneb97.managers.DependencyManager.<init>(DependencyManager.java:36) ~[ConditionalEvents.jar:?]
	at ce.ajneb97.ConditionalEvents.onEnable(ConditionalEvents.java:54) ~[ConditionalEvents.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[12:35:31] [Server thread/INFO]: [ConditionalEvents] Disabling ConditionalEvents v4.40.1
[12:35:31] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling ConditionalEvents v4.40.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "ce.ajneb97.configs.ConfigsManager.getPlayerConfigsManager()" because "this.configsManager" is null
	at ce.ajneb97.ConditionalEvents.onDisable(ConditionalEvents.java:90) ~[ConditionalEvents.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

And

[12:35:40] [Server thread/INFO]: [WorldGuardExtraFlags] Enabling WorldGuardExtraFlags v4.2.1
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnEntryFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.TeleportOnExitFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnEntryFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnEntryFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.ConsoleCommandOnExitFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.WalkSpeedFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.BlockedEffectsFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GiveEffectsFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlyFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlySpeedFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.PlaySoundsFlagHandler
[12:35:40] [Server thread/INFO]: [WorldGuard] Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler
[12:35:41] [Server thread/ERROR]: Error occurred while enabling WorldGuardExtraFlags v4.2.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolManager.addPacketListener(com.comphenix.protocol.events.PacketListener)" because the return value of "com.comphenix.protocol.ProtocolLibrary.getProtocolManager()" is null
	at net.goldtreeservers.worldguardextraflags.protocollib.ProtocolLibHelper.onEnable(ProtocolLibHelper.java:23) ~[WorldGuardExtraFlags.jar:?]
	at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:141) ~[WorldGuardExtraFlags.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-25]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[12:35:41] [Server thread/INFO]: [WorldGuardExtraFlags] Disabling WorldGuardExtraFlags v4.2.1

Im using the last versions of all plugins.

**Comment by lukalt** [comment]
Hi, 

please share the whole log file so we can have a closer look at this. The most likely reason for this to happend is either a problem while enabling ProtocolLib or another Plugin that bundles ProtocolLib incorrectly.

**Comment by pgprimitz** [comment]
Hello, yes there it is https://mclo.gs/emo7HQt

**Comment by pgprimitz** [comment]
So, you know how to solve the error @lukalt or what i can do?

**Comment by lukalt** [comment]
It's kind of difficult to say because you have so many plugins installed but try to remove `plugins/Shopkeepers-2.17.2.jar` and see it works then.
