### ISSUE TITLE
issue on starting protocollib

### ISSUE THREAD

**Issue by Drawksrr** [dmulloy2/ProtocolLib#2556]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
        at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3146/0x000000005df38e08.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:883)
  Caused by: java.lang.IllegalAccessException: illegal setter on final field
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:1084)
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
        ... 14 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@ef90dc7b[
        plugin=ProtocolLib v5.1.0
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1171,minecraftVersion=1.16.5}
        reporter=com.comphenix.protocol.ProtocolLib$1@861a4c1d
        minecraftVersion=(MC: 1.16.5)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@b62a6cb4
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@d8b9a837
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@b9aef31
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1a1b893f
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@d6fc0d7a
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@7a9390dc
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@a7becf0d
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@9ec79703[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@5495e887
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@9c248ffc
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@8b9bf94f
      commandProtocol=com.comphenix.protocol.CommandProtocol@cf3eee50
      commandPacket=com.comphenix.protocol.CommandPacket@a062d9
      commandFilter=com.comphenix.protocol.CommandFilter@31d43d2b
      packetLogging=com.comphenix.protocol.PacketLogging@bec8bd79
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@55d57a79
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1171,minecraftVersion=1.16.5}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@bca30f77
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=true, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@13286410
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    16.0.2
  Server:
    git-Purpur-1171 (MC: 1.16.5)

[22:56:33 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0

**Comment by mok3103** [comment]
[10:05:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:526)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:307)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@652afd57[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@46b2a931
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@700af8d9
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@76097be
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2074,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@663acee2
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@663acee2
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@428f9c3f
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.8.1
  Server:
    git-Purpur-2074 (MC: 1.20.2)
[10:05:35 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[10:05:35 ERROR]: ******************************************************
[10:05:35 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[10:05:35 ERROR]: *** Please use the built-in reload command!        ***
[10:05:35 ERROR]: ******************************************************
[10:05:35 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0

**Comment by lukalt** [comment]
@mok3103 You need to use this development build https://ci.dmulloy2.net/job/ProtocolLib/669/ for Minecraft 1.20.2  support. ProtocolLib 5.1.0 only supports Minecraft 1.20.1
