### ISSUE TITLE
Can't load on 1.20.2? :c

### ISSUE THREAD

**Issue by AzCreep** [dmulloy2/ProtocolLib#2562]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:526)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:307)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7c1f05c5[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@523309cd
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@21c0dd50
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@45c068e6
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2076,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@bc27834
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@bc27834
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@6a8ed466
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.8.1
  Server:
    git-Purpur-2076 (MC: 1.20.2)
![imagem_2023-10-09_025949442](https://github.com/dmulloy2/ProtocolLib/assets/49355027/ac77143f-ecb3-4191-9c12-45d39d283229)

**Comment by lukalt** [comment]
ProtocolLib 5.1.0 only supports Minecraft 1.20.1 or below. Please use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib/669/ for 1.20.2 support.

**Comment by AzCreep** [comment]
ah ok ye it works now thank you for the help!
