### ISSUE TITLE
ProtocolLib cant be loaded on 1.20 waterfall server

### ISSUE THREAD

**Issue by freaki2010** [dmulloy2/ProtocolLib#2564]
- [x] This issue is not solved in a development build

**Describe the bug**
ProtocolLib cant be loaded on 1.20 waterfall server
it fails with following exception: 

```
 Error loading plugin ProtocolLib
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more
```

**To Reproduce**
1. Create a waterfall server with following version waterfall-1.20-545.jar
2. Start the server with the latest ProtocolLib version 5.1.0
3. See the error message in the console 

**Expected behavior**
The plugin should load normally

**Screenshots**
not needed

**Version Info**
Can't do because its not loading. But I am usin version 5.1.0

**Comment by freaki2010** [comment]
here the output with the latest development build from 23.09.2023

```
Error loading plugin ProtocolLib
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-545.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:0e657ed:545]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more
```

**Comment by 0utplay** [comment]
ProtocolLib is made for bukkit.
