### ISSUE TITLE
Not working 1.20.2

### ISSUE THREAD

**Issue by WOLFRAGE99** [dmulloy2/ProtocolLib#2581]
- [ ] This issue is not solved in a development build

**Describe the bug**
Whenever I startup the server, Protocol Lib spits out this bug after downloading the latest version

[06:42:20] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@56ee57c5[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@b7bf760
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@51ebeb3b
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@64fef11d
      server=CraftServer{serverName=CraftBukkit,serverVersion=3917-Spigot-dba3cdc-b590041,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@149efdae
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@54bccd57
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@9c70265
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.7
  Server:
    3917-Spigot-dba3cdc-b590041 (MC: 1.20.2

**Comment by haeLL420** [comment]
same (using purpur 1.20.2)

**Comment by lukalt** [comment]
ProtocolLib 5.1.0, which you are using only support Minecraft 1.20.1. For 1.20.2 support, please use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib/669/
