### ISSUE TITLE
protocollib does not work on 1.20.2 purpur/bukkit

### ISSUE THREAD

**Issue by Epiczhul** [dmulloy2/ProtocolLib#2584]
[12:03:33] [ServerMain/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[12:03:34] [ServerMain/INFO]: Loaded 7 recipes
[12:03:35] [Server thread/INFO]: Starting minecraft server version 1.20.2
[12:03:35] [Server thread/INFO]: Loading properties
[12:03:35] [Server thread/INFO]: This server is running Purpur version git-Purpur-2083 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 6bb7f82 on HEAD)
[12:03:35] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:03:35] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:03:36] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[12:03:36] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[12:03:36] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[12:03:36] [Server thread/WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[12:03:36] [Server thread/WARN]: [Pufferfish] Debug: Java: 17.0.7, test run: true
[12:03:36] [Server thread/INFO]: Default game type: SURVIVAL
[12:03:36] [Server thread/INFO]: Generating keypair
[12:03:36] [Server thread/INFO]: Starting Minecraft server on *:25566
[12:03:36] [Server thread/INFO]: Using epoll channel type
[12:03:36] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[12:03:36] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[12:03:37] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.8.1
[12:03:37] [Server thread/INFO]: [ViaVersion] ViaVersion 4.8.1 is now loaded. Registering protocol transformers and injecting...
[12:03:37] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[12:03:37] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[12:03:37] [Server thread/INFO]: [ViaBackwards] Loading translations...
[12:03:37] [Server thread/INFO]: [ViaBackwards] Registering protocols...
[12:03:38] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[12:03:38] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[12:03:39] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:526)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@324dd5e2[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@c245ea6
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@1edad5dd
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7fcfce94
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2083,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@d0e5dec
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@d0e5dec
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib (1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@4488c8f1
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.7
  Server:
    git-Purpur-2083 (MC: 1.20.2)

[12:03:39] [Server thread/INFO]: [ProtectionLib] Loading server plugin ProtectionLib v1.8
[12:03:39] [Server thread/INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.4
[12:03:39] [Server thread/INFO]: [FurnitureLib] Loading server plugin FurnitureLib v3.1.2
[12:03:39] [Server thread/INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.104
[12:03:39] [Server thread/INFO]: [spark] Loading server plugin spark v1.10.55
[12:03:39] [Server thread/INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.8.1
[12:03:39] [Server thread/INFO]: [WorldEdit] Loading server plugin WorldEdit v7.2.16+6534-2066eb4
[12:03:39] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@19800863]
[12:03:39] [Server thread/INFO]: [Citizens] Loading server plugin Citizens v2.0.33-SNAPSHOT (build 3216)
[12:03:39] [Server thread/INFO]: [DiceFurniture] Loading server plugin DiceFurniture v3.8.1
[12:03:39] [Server thread/INFO]: [TAB] Loading server plugin TAB v4.0.6
[12:03:39] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:03:39] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[12:03:39] [Server thread/ERROR]: ******************************************************
[12:03:39] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[12:03:39] [Server thread/ERROR]: *** Please use the built-in reload command!        ***
[12:03:39] [Server thread/ERROR]: ******************************************************
[12:03:39] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0

Installed plugins are: 
Citizens
DiceFurniture
FurnitureLib
LuckPerms
PlaceholderAPI
ProtectionLib
Tab
ViaBackwards
ViaVersion
worldedit-bukkit

**Comment by Dymeth** [comment]
Use dev build from here; https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Epiczhul** [comment]
> Use dev build from here; https://ci.dmulloy2.net/job/ProtocolLib/

thx
