### ISSUE TITLE
protocol lib 5.1.0 in spigot 1.20.2

### ISSUE THREAD

**Issue by UmaruDoma** [dmulloy2/ProtocolLib#2588]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned:>
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
        at java.base/java.lang.Thread.run(Thread.java:833)
 Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7029c207[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4fea2956
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@192d2c0a
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@383a04ef
      server=CraftServer{serverName=CraftBukkit,serverVersion=3922-Spigot-dba3cdc-75502b6,minecraftVersion=1.2>
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1803e90d
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@477db171
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@cbb7ef
    newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@cbb7ef
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.4
  Server:
    3922-Spigot-dba3cdc-75502b6 (MC: 1.20.2)

- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by TH3N3WN00B** [comment]
Use latest from [here](https://ci.dmulloy2.net/job/ProtocolLib/)
