### ISSUE TITLE
plugin not loading 

### ISSUE THREAD

**Issue by TymekSL** [dmulloy2/ProtocolLib#2605]
18:44:46 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.1-SNAPSHOT-673
[18:44:49 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: ProtocolLib has already been initialized.
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLibrary.init(ProtocolLibrary.java:63)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:184)
        at OllozSays-2.1.6.jar//io.github.ollozsays.bootstrap.OSBukkitBootstrap.download(OSBukkitBootstrap.java:75)
        at OllozSays-2.1.6.jar//io.github.ollozsays.bootstrap.OSBukkitBootstrap.onLoad(OSBukkitBootstrap.java:46)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:430)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    com.comphenix.protocol.injector.PacketFilterManager@694511b7[
      plugin=ProtocolLib v5.1.1-SNAPSHOT-673
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-17,minecraftVersion=1.20}
      reporter=com.comphenix.protocol.ProtocolLib$1@32994aa4
      minecraftVersion=(MC: 1.20.0)
      asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7289e4ec
      pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@33009ba3
      inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@eda8e2d
      outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@766e3938
      registeredListeners=[]
      packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@4b7d0d9d
      playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@7c175ad2
      networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@26e6089b
      debug=false
      closed=false
      injected=false
    ]
  Sender:
    com.comphenix.protocol.ProtocolLib@274b2c6[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@44f3a990
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@52c7c345
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@410669e9
      commandProtocol=com.comphenix.protocol.CommandProtocol@66c3018d
      commandPacket=com.comphenix.protocol.CommandPacket@3f259bec
      commandFilter=com.comphenix.protocol.CommandFilter@5394aaa6
      packetLogging=com.comphenix.protocol.PacketLogging@21afc81c
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@5f1e6acd
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-17,minecraftVersion=1.20}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4cf76039
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4cf76039
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.1-SNAPSHOT-673, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@6570e2f7
    ]
  Version:
    ProtocolLib v5.1.1-SNAPSHOT-673
  Java Version:
    17.0.9
  Server:
    git-Paper-17 (MC: 1.20)

**Comment by Kooperlol** [comment]
same
