### ISSUE TITLE
 [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by Kowismo** [dmulloy2/ProtocolLib#2608]
[12:17:47 WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[12:17:48 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3cd67697[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2dbc9bff
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3c2ef9e6
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@2bb7af5
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-262,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@44fcc7cd
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@44fcc7cd
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@56e348a0
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    git-Paper-262 (MC: 1.20.2)
[12:17:48 INFO]: [Orebfuscator] Loading server plugin Orebfuscator v5.4.2
[12:17:48 INFO]: [TAB] Loading server plugin TAB v4.0.7
[12:17:48 INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:17:48 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[12:17:48 ERROR]: ******************************************************
[12:17:48 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[12:17:48 ERROR]: *** Please use the built-in reload command!        ***
[12:17:48 ERROR]: ******************************************************
[12:17:48 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
[12:17:48 INFO]: Preparing level "world"
[12:17:49 INFO]: Preparing start region for dimension minecraft:overworld
[12:17:49 INFO]: Time elapsed: 246 ms
[12:17:49 INFO]: Preparing start region for dimension minecraft:the_nether
[12:17:49 INFO]: Time elapsed: 58 ms
[12:17:49 INFO]: Preparing start region for dimension minecraft:the_end
[12:17:49 INFO]: Time elapsed: 36 ms

**Comment by sqwkz** [comment]
same error running 1.20.2 Pufferfish

**Comment by DinoFengz** [comment]
Build the latest src, works for me in Paper 1.20.2.

**Comment by AgentSmith888** [comment]
what does build the latest src mean? sorry I have no idea!

**Comment by Dymeth** [comment]
Test with last dev build from here: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by DinoFengz** [comment]
or https://github.com/dmulloy2/ProtocolLib/actions/runs/6640109445

**Comment by frosDfurret** [comment]
Tested with Paper 1.20.2, using latest dev build fixes the issue.
