### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib

### ISSUE THREAD

**Issue by AgentSmith888** [dmulloy2/ProtocolLib#2609]
[10:12:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
at java.base/java.lang.Thread.run(Thread.java:833)
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@7909f8c0[
statistics=<null>
packetTask=<null>
tickCounter=0
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@6af0405a
redirectHandler=<null>
scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@495d9be5
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@5b5878b1
server=CraftServer{serverName=Paper,serverVersion=git-Paper-261,minecraftVersion=1.20.2}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@5bb2b9c
pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5bb2b9c
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@3819632f
]
Version:
ProtocolLib v5.1.0
Java Version:
17.0.8.1
Server:
git-Paper-261 (MC: 1.20.2)

**Comment by AgentSmith888** [comment]
sorry, I sorted it by using the dev build. Thanks!

**Comment by Dymeth** [comment]
> sorry, I sorted it by using the dev build. Thanks!

You can close the issue
