### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by LittleDuck363** [dmulloy2/ProtocolLib#2618]
- This issue is not solved in a development build

**Describe the bug**
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@18527db3[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@63da528c
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@c0ec62e
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3a1bd15e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-"a702a08",minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@50f6c0
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@50f6c0
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@1e60d07f
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.7
  Server:
    git-Paper-"a702a08" (MC: 1.20.2)

**To Reproduce**
1. restart the server

**Expected behavior**
Plugin to load into the server.

**Version Info**
08.11 02:53:27 [Server] [WARN] Unexpected exception while parsing console command "protocol dump"
08.11 02:53:27 [Server] [INFO] org.bukkit.command.CommandException: Cannot execute command 'protocol' in plugin ProtocolLib v5.1.0 - plugin is disabled.
08.11 02:53:27 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
08.11 02:53:27 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
08.11 02:53:27 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:974) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-"a702a08"]
08.11 02:53:27 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by grahhnt** [comment]
Make sure to try [the latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/)

**Comment by LittleDuck363** [comment]
I am currently using the latest one.

**Comment by lukalt** [comment]
You need use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib/673/
not the latest release version
