### ISSUE TITLE
Doesn't work after adding plugin

### ISSUE THREAD

**Issue by Hyobinssyi** [dmulloy2/ProtocolLib#2620]
[ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Unable to access field private final java.util.List net.minecraft.network.NetworkSystem.field_151274_e
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.inject(NetworkManagerInjector.java:204)
        at com.comphenix.protocol.injector.PacketFilterManager.registerEvents(PacketFilterManager.java:456)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:344)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:526)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:405)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:246)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:826)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.NoSuchFieldException: no such field: net.minecraft.network.NetworkSystem.listeningChannels/java.util.List/getField
        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:978)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findGetter(MethodHandles.java:3019)
        at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:95)
        ... 13 more
  Caused by: java.lang.NoSuchFieldError: field resolution failed
        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
        ... 16 more
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@20ee2b48[
        plugin=ProtocolLib v5.1.1-SNAPSHOT-673
        server=CraftServer{serverName=Magma,serverVersion=git-Magma-1.16.5-c1c5a946,minecraftVersion=1.16.5}
        reporter=com.comphenix.protocol.ProtocolLib$1@3aea6a74
        minecraftVersion=(MC: 1.16.5)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@625ca349
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@33b97021
        inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@328003b7
        outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5b506659
        registeredListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@5c91d091
        playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@24519b5a
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@167ea9dc
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@1c8323e5[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3420f064
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@57f39f75
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3ae5a928
      commandProtocol=com.comphenix.protocol.CommandProtocol@3ffc399a
      commandPacket=com.comphenix.protocol.CommandPacket@cec5dd1
      commandFilter=com.comphenix.protocol.CommandFilter@472f630e
      packetLogging=com.comphenix.protocol.PacketLogging@50943e2a
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@efafd4b
      server=CraftServer{serverName=Magma,serverVersion=git-Magma-1.16.5-c1c5a946,minecraftVersion=1.16.5}
      file=plugins\ProtocolLib (6).jar
      description=org.bukkit.plugin.PluginDescriptionFile@60963b90
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@5c85d509
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@2d090358
    ]
  Version:
    ProtocolLib v5.1.1-SNAPSHOT-673
  Java Version:
    17.0.5
  Server:
    git-Magma-1.16.5-c1c5a946 (MC: 1.16.5)

**Make sure you're doing the following**
- [ ] You're using the latest build for your server version
- [ ] This isn't an issue caused by another plugin
- [ ] You've checked for duplicate issues
- [ ] You didn't use `/reload`

**Describe the question**
A clear and concise description of what your question is.

**API method(s) used**
List what API method(s) you're using

**Expected behavior**

**Code**
If applicable, add relevant code from your project

**Additional context**

**Comment by ayush0662** [comment]
you this version for 1.16.5 mc 

https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0
