### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by 1kdani** [dmulloy2/ProtocolLib#2621]
**Describe the bug**
Hi! Every time when I start my server, I get this error. Does anyone know, how to fix it?

My server version is: 1.19.3

**Error**
java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.MinecraftServer
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:63)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
        at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:453)
        at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:173)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366)
        at PlaceholderAPI-2.11.5.jar//me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46)
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
        at java.base/java.lang.Thread.run(Thread.java:833)

**My plugins**
![image](https://github.com/dmulloy2/ProtocolLib/assets/130190432/a6c7bbe7-264f-4b16-ae7f-a290ef7510d7)

**Version Info**
ProtocolLib-5.1.0

**Comment by wasn325** [comment]
I am not eve sure if this is caused by ProtocolLib
Maybe try it here? https://github.com/PlaceholderAPI/PlaceholderAPI/issues

**Comment by Dymeth** [comment]
Try to use dev build of ProtocolLib v5.1.1 from here:
[1.8-1.19.4]: https://ci.dmulloy2.net/job/
[1.20.*+]: https://ci.dmulloy2.net/job/ProtocolLib/669/

Notice for 1.20 and 1.20.1 users:
Please, use 1.20.2 to confirm your issue with ProtocolLib.

Why not the last build for 1.20.2?
Last build (673) have critical issue at this moment; https://github.com/dmulloy2/ProtocolLib/issues/2601

If the problem persists, provide more information about your problem using this form:

- [ ] This issue is not solved in a development build

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Add any other context about the problem here.
