### ISSUE TITLE
ProtocolLib fails to start on 1.20.2 Spigot

### ISSUE THREAD

**Issue by Rasgnarok** [dmulloy2/ProtocolLib#2622]
- [ ] This issue is not solved in a development build

**Describe the bug**
Fails to startup

**To Reproduce**
1. Load up Spigot 1.20.2 and ProcotolLib 5.1.0

**Expected behavior**
Start up properly

**Screenshots**
```
[10Nov2023 23:25:38.161] [Server thread/ERROR] [Minecraft/]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at TRANSFORMER/arclight@1.20.2-1.0.0-SNAPSHOT-0274c29a/org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServerMixin.java:442)
  	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.dedicated.DedicatedServer.handler$zbn000$arclight$loadPlugins(DedicatedServerMixin.java:645)
  	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:158)
  	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2035)
  	at TRANSFORMER/minecraft@1.20.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:249)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@2c9a8cc7[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4e7c8053
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@743d4da4
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@5bf82c0a
      server=CraftServer{serverName=CraftBukkit,serverVersion=arclight-1.20.2-1.0.0-SNAPSHOT-0274c29a,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib-5.1.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@9280d22
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@5fd7b19b
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=io.izzel.arclight.common.mod.util.log.ArclightPluginLogger@de4c744
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    arclight-1.20.2-1.0.0-SNAPSHOT-0274c29a (MC: 1.20.2)
    ```

**Version Info**
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    arclight-1.20.2-1.0.0-SNAPSHOT-0274c29a (MC: 1.20.2)

**Additional context**
N/A, not reproducible in Paper version git-Paper-"bc4a664" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1)

**Comment by Zebrahawk** [comment]
I also have this issue.

**Comment by Zebrahawk** [comment]
Seems to be fixed with:
https://github.com/dmulloy2/ProtocolLib/suites/17615178874/artifacts/1006720717
