### ISSUE TITLE
Error in latest version

### ISSUE THREAD

**Issue by ShreshthTiwari** [dmulloy2/ProtocolLib#2629]
```
[11:29:33 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[11:29:33 WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[11:29:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7c9a26c[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4eac2d52
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@43c3c29
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@21c51bdc
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2090,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4563fed9
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4563fed9
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@1a8dbc42
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    18.0.2.1
  Server:
    git-Purpur-2090 (MC: 1.20.2)
 ```

**Comment by lukalt** [comment]
Please use the latest development build. The version you are using only works with Minecraft 1.20.1:
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar

**Comment by Girollplay** [comment]
> Please use the latest development build. The version you are using only works with Minecraft 1.20.1: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar
Thx you saved me a lot of trouble. <3

**Comment by Dymeth** [comment]
Try to use dev build of ProtocolLib v5.1.1 from here:
[1.8-1.19.4]: https://ci.dmulloy2.net/job/
[1.20.*+]: https://ci.dmulloy2.net/job/ProtocolLib/669/

Notice for 1.20 and 1.20.1 users:
Please, use 1.20.2 to confirm your issue with ProtocolLib.

Why not the last build for 1.20.2?
Last build (673) have critical issue at this moment; https://github.com/dmulloy2/ProtocolLib/issues/2601

If the problem persists, provide more information about your problem using this form:

- [ ] This issue is not solved in a development build

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Add any other context about the problem here.
