### ISSUE TITLE
Pls update to 1.20.2 purpur 

### ISSUE THREAD

**Issue by Linuqsior** [dmulloy2/ProtocolLib#2634]
If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7009ac87[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@11a2d60e
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@5f26e461
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@2738565d
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2091,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1d7d0c5c
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1d7d0c5c
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@107fcc2f
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    git-Purpur-2091 (MC: 1.20.2)

**Comment by EchoPlatinum** [comment]
try download the latest dev build [#673](https://ci.dmulloy2.net/job/ProtocolLib/673/)

**Comment by Dymeth** [comment]
Try to use dev build of ProtocolLib v5.1.1 from here:
[1.8-1.19.4]: https://ci.dmulloy2.net/job/
[1.20.*+]: https://ci.dmulloy2.net/job/ProtocolLib/669/

Notice for 1.20 and 1.20.1 users:
Please, use 1.20.2 to confirm your issue with ProtocolLib.

Why not the last build for 1.20.2?
Last build (673) have critical issue at this moment; https://github.com/dmulloy2/ProtocolLib/issues/2601

If the problem persists, provide more information about your problem using this form:

- [ ] This issue is not solved in a development build

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
Add any other context about the problem here.
