### ISSUE TITLE
Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by BLueIronEye** [dmulloy2/ProtocolLib#2662]
[19:55:33] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7ebedfd4[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3d8895d7
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@35c0adcd
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@3f8da056
      server=CraftServer{serverName=CraftBukkit,serverVersion=3945-Spigot-b60a866-0478e04,minecraftVersion=1.20.2}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@3e641060
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@a208be4
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@1e5ddca7
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    18.0.2.1
  Server:
    3945-Spigot-b60a866-0478e04 (MC: 1.20.2)

Installed Plugins: Plugins (18): LuckPerms, SpigotPing, UltimateTimber, Vault, ProtocolLib, dynmap, WorldEdit, TCPShield, DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn, WorldGuard, CoreProtect, EssentialsProtect, VillagerMarket, Dynmap-WorldGuard, LWC

I just started the server and the above error showed up. Thanks in advance! :)

**Comment by wgaylord** [comment]
Your going to want a dev build from https://ci.dmulloy2.net/job/ProtocolLib/ since 1.20.2 isn't supported in v5.1.0 from what I can tell. (Was released before 1.20.2 came out.)

https://ci.dmulloy2.net/job/ProtocolLib/673/ is the latest dev build.

**Comment by BLueIronEye** [comment]
Ill test it. Thank you :)
