### ISSUE TITLE
Bug Protocolib

### ISSUE THREAD

**Issue by Dorlomonogo** [dmulloy2/ProtocolLib#267]
This is the log, thanks you!
 [20:05:33] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.7.10) is lower than the minimum (MC: 1.9.0)
[20:05:33] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:245)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:206)
  	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
  	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
  	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
  	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelInboundHandler
  	at java.net.URLClassLoader.findClass(Unknown Source)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
  	at java.lang.ClassLoader.loadClass(Unknown Source)
  	at java.lang.ClassLoader.loadClass(Unknown Source)
  	... 8 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1c9ec83f[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@24173ac1
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@780d56bd
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@26268867
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1649,minecraftVersion=1.7.10}
      file=plugins\ProtocolLib (2).jar
      description=org.bukkit.plugin.PluginDescriptionFile@cace534
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2aa9db92
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@cf124a5
    ]
  Version:
    ProtocolLib v4.0.2
  Java Version:
    1.8.0_101
  Server:
    git-Spigot-1649 (MC: 1.7.10)

**Comment by MiniDigger** [comment]
> [ProtocolLib] Version (MC: 1.7.10) is lower than the minimum (MC: 1.9.0)
update spigot. protocollib does not support your way to old and broken version.
if you _really_ need it, search for an old/outdated build of protocollib, but that will only make things worse for you. The resource page has the links https://www.spigotmc.org/resources/protocollib.1997/

**Comment by dmulloy2** [comment]
Use 3.7.0 for the horribly outdated 1.7.10: https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
