### ISSUE TITLE
ProtocolLib Not working On Aternos Server with this data:

### ISSUE THREAD

**Issue by ProSlayerz** [dmulloy2/ProtocolLib#2670]
I just got this data from my Aternos server log:

Stack Trace:
[38](https://aternos.org/log/#L38)	  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
[39](https://aternos.org/log/#L39)	  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
[40](https://aternos.org/log/#L40)	  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
[41](https://aternos.org/log/#L41)	  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
[42](https://aternos.org/log/#L42)	  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
[43](https://aternos.org/log/#L43)	  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
[44](https://aternos.org/log/#L44)	  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
[45](https://aternos.org/log/#L45)	  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
[46](https://aternos.org/log/#L46)	  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
[47](https://aternos.org/log/#L47)	  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
[48](https://aternos.org/log/#L48)	  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
[49](https://aternos.org/log/#L49)	  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[50](https://aternos.org/log/#L50)	  	at java.base/java.lang.Thread.run(Thread.java:840)
[51](https://aternos.org/log/#L51)	  Dump:
[52](https://aternos.org/log/#L52)	  Parameters: 
[53](https://aternos.org/log/#L53)	    [NULL]
[54](https://aternos.org/log/#L54)	  Sender:
[55](https://aternos.org/log/#L55)	    com.comphenix.protocol.ProtocolLib@4d4559e[
[56](https://aternos.org/log/#L56)	      statistics=<null>
[57](https://aternos.org/log/#L57)	      packetTask=<null>
[58](https://aternos.org/log/#L58)	      tickCounter=0
[59](https://aternos.org/log/#L59)	      configExpectedMod=-1
[60](https://aternos.org/log/#L60)	      updater=com.comphenix.protocol.updater.SpigotUpdater@13405c4
[61](https://aternos.org/log/#L61)	      redirectHandler=<null>
[62](https://aternos.org/log/#L62)	      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2feaa04a
[63](https://aternos.org/log/#L63)	      commandProtocol=<null>
[64](https://aternos.org/log/#L64)	      commandPacket=<null>
[65](https://aternos.org/log/#L65)	      commandFilter=<null>
[66](https://aternos.org/log/#L66)	      packetLogging=<null>
[67](https://aternos.org/log/#L67)	      skipDisable=false
[68](https://aternos.org/log/#L68)	      isEnabled=false
[69](https://aternos.org/log/#L69)	      loader=org.bukkit.plugin.java.JavaPluginLoader@76ca7158
[70](https://aternos.org/log/#L70)	      server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Spigot-2888990-d485cde,minecraftVersion=1.20.2}
[71](https://aternos.org/log/#L71)	      file=plugins/ProtocolLib.jar
[72](https://aternos.org/log/#L72)	      description=org.bukkit.plugin.PluginDescriptionFile@71af9749
[73](https://aternos.org/log/#L73)	      dataFolder=plugins/ProtocolLib
[74](https://aternos.org/log/#L74)	      classLoader=org.bukkit.plugin.java.PluginClassLoader@6124a52f
[75](https://aternos.org/log/#L75)	      naggable=true
[76](https://aternos.org/log/#L76)	      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
[77](https://aternos.org/log/#L77)	      configFile=plugins/ProtocolLib/config.yml
[78](https://aternos.org/log/#L78)	      logger=org.bukkit.plugin.PluginLogger@2ed87148
[79](https://aternos.org/log/#L79)	    ]
[80](https://aternos.org/log/#L80)	  Version:
[81](https://aternos.org/log/#L81)	    ProtocolLib v5.1.0
[82](https://aternos.org/log/#L82)	  Java Version:
[83](https://aternos.org/log/#L83)	    17.0.9
[84](https://aternos.org/log/#L84)	  Server:
[85](https://aternos.org/log/#L85)	    3950-Spigot-2888990-d485cde (MC: 1.20.2)

**Comment by dmulloy2** [comment]
Try a dev build: https://ci.dmulloy2.net/job/ProtocolLib

Otherwise, it may just be an incompatibility with Aternos, which we don't plan on addressing
