### ISSUE TITLE
Cannot load ProtocolLib

### ISSUE THREAD

**Issue by hgtoiwr** [dmulloy2/ProtocolLib#2677]
- [ ] This issue is not solved in a development build

**Describe the bug**
When uploading the plugin to the server, it immediately returned an error, although I only downloaded it.

**Expected behavior**
[00:33:13] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[00:33:13] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[00:33:14] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@55d922d1[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6542c8f2
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@70206f2b
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@a09230d
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2095,minecraftVersion=1.20.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1b4a3140
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1b4a3140
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@419fee25
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.1
  Server:
    git-Purpur-2095 (MC: 1.20.2)

**Version Info**
[00:38:02 WARN]: Unexpected exception while parsing console command "protocol dump"
org.bukkit.command.CommandException: Cannot execute command 'protocol' in plugin ProtocolLib v5.1.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:1005) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:990) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Tapwatero** [comment]
I also have this

**Comment by hgtoiwr** [comment]
> 

I think this is a bug in the plugin itself.
