### ISSUE TITLE
[ProtocolLib] Loading server plugin ProtocolLib v5.1.0 Error

### ISSUE THREAD

**Issue by cubanrebelde** [dmulloy2/ProtocolLib#2678]
[09:29:16] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[09:29:16] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[09:29:21] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
  	at java.base/java.lang.Thread.run(Thread.java:1623)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@6dc27b5a[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@601f8899
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6c9e0aea
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1e3140a7
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@60d511dc
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@60d511dc
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@65a7f84e
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    20.0.1
  Server:
    git-Paper-318 (MC: 1.20.2)
________________________________________________________________________________________________
[09:29:34] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[09:29:34] [Server thread/ERROR]: ******************************************************
[09:29:34] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[09:29:34] [Server thread/ERROR]: *** Please use the built-in reload command!        ***
[09:29:34] [Server thread/ERROR]: ******************************************************
[09:29:34] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
_________________________________________________________________________________________________

**_This are the Plugins I use ProtocolLib is in Red everything el is Green:_**
[14:45:51 INFO]: Server Plugins (18):
[14:45:51 INFO]: Bukkit Plugins:
[14:45:51 INFO]:  - BottledExp, ChestSort, CMILib, CoreProtect, dynmap, Essentials, EssentialsGeoIP, EssentialsSpawn, LPC, LuckPerms
[14:45:51 INFO]:  **ProtocolLib**, SilkSpawners_v2, SmoothTimber, spark, Vault, WorldBorder, WorldEdit, WorldGuard

**Comment by Jeppa** [comment]
Update to dev build...

**Comment by CTMOM** [comment]
i have same problem where can i find the dev build?

**Comment by CTMOM** [comment]
https://ci.dmulloy2.net/job/ProtocolLib/
