### ISSUE TITLE
I can't join on my 1.7.2 minecraft with spigot

### ISSUE THREAD

**Issue by MikiBed** [dmulloy2/ProtocolLib#2679]
So i want to instal ProtocoLib and i can't join i'm have version 3.0.1

Here is error:

Failed to initialize a channel. Closing: [id: 0x8d7d8c42, /Here is my ip => /Here is my ip]
java.lang.ExceptionInInitializerError
        at com.comphenix.net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166) ~[?:?]
        at com.comphenix.net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[?:?]
        at com.comphenix.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104) ~[?:?]
        at com.comphenix.net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69) ~[?:?]
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.createTemporaryPlayer(TemporaryPlayerFactory.java:156) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.fromChannel(ChannelInjector.java:176) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:92) ~[?:?]
        at net.minecraft.util.io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:70) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRegistered(DefaultChannelHandlerContext.java:162) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRegistered(DefaultChannelHandlerContext.java:148) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:73) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRegistered(DefaultChannelHandlerContext.java:162) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRegistered(DefaultChannelHandlerContext.java:148) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:730) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:441) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:373) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:417) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [ARNC.jar:git-Spigot-1339]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @74027e6a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at com.comphenix.net.sf.cglib.core.ReflectUtils$2.run(ReflectUtils.java:56) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at com.comphenix.net.sf.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:46) ~[?:?]
        ... 25 more
[20:59:29 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.util.io.netty.channel.Channel.isOpen()" because "this.k" is null
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:161) ~[ARNC.jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.NetworkManager.channelInactive(NetworkManager.java:63) ~[ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:214) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:214) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:143) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:767) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:558) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [ARNC.jar:git-Spigot-1339]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
[20:59:29 WARN]: Failed to initialize a channel. Closing: [id: 0x590b4e03, /192.168.0.9:53894 => /192.168.0.9:25678]
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.net.sf.cglib.proxy.Enhancer
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory.createTemporaryPlayer(TemporaryPlayerFactory.java:156) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.fromChannel(ChannelInjector.java:176) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:92) ~[?:?]
        at net.minecraft.util.io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:70) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRegistered(DefaultChannelHandlerContext.java:162) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRegistered(DefaultChannelHandlerContext.java:148) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:73) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelRegistered(DefaultChannelHandlerContext.java:162) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelRegistered(DefaultChannelHandlerContext.java:148) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:730) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:441) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:373) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:417) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [ARNC.jar:git-Spigot-1339]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Netty IO #1"]
        at com.comphenix.net.sf.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166) ~[?:?]
        at com.comphenix.net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) ~[?:?]
        at com.comphenix.net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108) ~[?:?]
        at com.comphenix.net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104) ~[?:?]
        at com.comphenix.net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69) ~[?:?]
        ... 17 more
[20:59:29 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.util.io.netty.channel.Channel.isOpen()" because "this.k" is null
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:161) ~[ARNC.jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.NetworkManager.channelInactive(NetworkManager.java:63) ~[ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:214) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:214) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:143) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:237) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:223) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:767) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:558) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [ARNC.jar:git-Spigot-1339]
        at net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [ARNC.jar:git-Spigot-1339]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
>

Help

**Comment by dmulloy2** [comment]
1.7.2? can't help ya at this point. been 10 years. but best of luck
