### ISSUE TITLE
Unable to find a field that matches

### ISSUE THREAD

**Issue by rowdyslav** [dmulloy2/ProtocolLib#2700]
- [ ] This issue is not solved in a development build

**Describe the bug**
Error on server startup

**To Reproduce**
1. Run server
2. See error

**Expected behavior**
Load ProtocolLib on server startup

**Screenshots**
https://i.imgur.com/IeRGxzY.png

[10:13:42 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[10:13:44 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:307)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3f178710[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7b49ba15
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2640a26b
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@280491b0
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2107,minecraftVersion=1.20.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1d8732c5
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1d8732c5
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@32f2178b
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.8
  Server:
    git-Purpur-2107 (MC: 1.20.4)

**Comment by CG-Spectre** [comment]
I had the same issue on same java version and Minecraft version as you. My solution was to simply use the version downloaded from here: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/
I don't believe the link was properly updated on the Spigot page.
