### ISSUE TITLE
[09:29:40 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.

### ISSUE THREAD

**Issue by WolfLiSteel** [dmulloy2/ProtocolLib#2702]
[09:29:40 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[09:29:40 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:509)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@722387ec[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2427038
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@28f4e093
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@336ac03
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-329,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7c96395e
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7c96395e
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@450952fd
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    git-Paper-329 (MC: 1.20.4)

**Comment by WolfLiSteel** [comment]
[09:29:46 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[09:29:46 ERROR]: ******************************************************
[09:29:46 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[09:29:46 ERROR]: *** Please use the built-in reload command!        ***
[09:29:46 ERROR]: ******************************************************
[09:29:46 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0

**Comment by Pledix** [comment]
I get same error as you but i don't even use PlugMan etc. something.
` Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.8
  Server:
    git-Leaves-"10acfe9" (MC: 1.20.2)`

**Comment by Hunkarada** [comment]
I also have such problem with paper 1.20.4

**Comment by lukalt** [comment]
As stated in the message, you are using an old version of ProtocolLib that is not compatible with 1.20.4. 

Use this development build instead: https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar
