### ISSUE TITLE
Nlogin having problems with handling login for players for version 1.20.4 with ProtocolLib 5.2.0-SNAPSHOT-679

### ISSUE THREAD

**Issue by LunarTheEngieFox** [dmulloy2/ProtocolLib#2705]
**Describe the bug**
Can't connect to the server because of a bug between Nlogin and ProtocolLib

**To Reproduce**
1.) Setup MC server for version 1.20.4
2.) Include plugins Nlogin and ProtocolLib with version written down in the late section of report
3.) Start server and try to connect to him

**Expected behavior**
Normal connection to the server via localhost or domain-name

**Screenshots**
via Code:
[18:36:07] [Craft Scheduler Thread - 3/ERROR]: [nLogin] [Premium] Could not handle login for UNKNOWN[/127.0.0.1:56934] (probably this is a bug!)
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:244) ~[?:?]
	at com.nickuc.login.υααψψγξΔψεΠαθυκ.a(:110) ~[?:?]
	at com.nickuc.login.ωυββακσδτιΠΣν.a(:239) ~[?:?]
	at com.nickuc.login.ωυββακσδτιΠΣν.H(:175) ~[?:?]
	at com.nickuc.login.ζσεφπαπυςΨΠΦωλ.run(:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3993-Spigot-3e5e22c-7df1851]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3993-Spigot-3e5e22c-7df1851]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[18:36:08] [Server thread/INFO]: /127.0.0.1:56934 lost connection: Disconnected

**Version Info**
MC version: 1.20.4
Nlogin version: 10.2.25
ProtocolLib: 5.2.0-SNAPSHOT-679
Server version: version 3993-Spigot
API implementation for server: version 1.20.4-R0.1-SNAPSHOT

**Additional context**
none

**Comment by lukalt** [comment]
This is not a problem of ProtocolLib. 
NLogin does not seem to be compatible with MC 1.20.4. The author of the plugins needs to update it.

**Comment by LunarTheEngieFox** [comment]
thanks for the info, I appreciate it.
