### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by HealingPotio** [dmulloy2/ProtocolLib#2706]
If this problem hasn't already been reported, please open a ticket

at https://github.com/dmulloy2/ProtocolLib/issues with the following data:

Stack Trace:

java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)

at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)

at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)

at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)

at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)

at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)

at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)

at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)

at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)

at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40)

at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)

at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512)

at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)

at java.base/java.lang.Thread.run(Thread.java:833)

Dump:

Parameters:

[NULL]

Sender:

com.comphenix.protocol.ProtocolLib@4f69e9bc[

statistics=<null>

packetTask=<null>

tickCounter=0

configExpectedMod=-1

updater=com.comphenix.protocol.updater.SpigotUpdater@507a5bcb

redirectHandler=<null>

scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@5d7520ea

commandProtocol=<null>

commandPacket=<null>

commandFilter=<null>

packetLogging=<null>

skipDisable=false

isEnabled=false

loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@19d73988

server=CraftServer{serverName=Paper,serverVersion=git-Paper-243,minecraftVersion=1.20.2}

file=plugins/ProtocolLib.jar

description=org.bukkit.plugin.PluginDescriptionFile@1b55b3f1

pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1b55b3f1

dataFolder=plugins/ProtocolLib

classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}

naggable=true

newConfig=YamlConfiguration[path='', root='YamlConfiguration']

configFile=plugins/ProtocolLib/config.yml

logger=com.destroystokyo.paper.utils.PaperPluginLogger@4fe8cd0a

]

Version:

ProtocolLib v5.1.0

Java Version:

17.0.7

Server:

git-Paper-243 (MC: 1.20.2)

**Comment by Kovalit31** [comment]
Same problem

**Comment by bypassRobin** [comment]
Same: https://pastebin.com/GFgAeKvp
Bug-Report: https://github.com/dmulloy2/ProtocolLib/issues/2707

**Comment by lukalt** [comment]
Please update to the latest development build that supports 1.20.2 to 1.20.4: https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar

**Comment by bypassRobin** [comment]
> Please update to the latest development build that supports 1.20.2 to 1.20.4: https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar

I downloaded the latest ProtocolLib from the official Website (https://github.com/dmulloy2/ProtocolLib/releases) from Aug. 5 ([ProtocolLib v5.1.0])) why i should download any file from a website that i dont know, why is it not on the official github Download Site the newest file? Sorry, but can you tell me this?
