### ISSUE TITLE
ProtocolLibrary.getProtocolManager() is returning null.

### ISSUE THREAD

**Issue by saturn-volv** [dmulloy2/ProtocolLib#2726]
There's no error on startup for initializing a ProtocolManager object with `ProtocolLibrary.getProtocolManager()`, however it is returning null.

This is the code from my `onEnable()` function
```java

        manager = ProtocolLibrary.getProtocolManager();
        System.out.println(manager == null); // Returns true
```
Here is what is currently in my pom.xml as I have a feeling this may be the issue?
```html
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
        
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>5.2.0-SNAPSHOT</version>
        </dependency>
 ```

**Minecraft Version**
1.20.4 Paper

**API Version**
5.2.0-SNAPSHOT-679

**Comment by lukalt** [comment]
Do you shade ProtocolLib into your Jar? This might be the cause for this.
Try excluding `com.comphenix.protocol.ProtocolLib` in the `maven-shade-plugin` or add `<scope>provided</scope>` to the `<dependency>`.

**Comment by saturn-volv** [comment]
I could have sworn I had included the provide scope before. Thanks for the help. Fixed my issue :)

**Comment by lukalt** [comment]
Okay, great to hear!

**Comment by KanCiGamer** [comment]
@saturn-volv. 
Can you help me?
When I add data like this:
`      <dependency>
          <groupId>com.comphenix.protocol</groupId>
          <artifactId>ProtocolLib</artifactId>
          <version>5.2.0-SNAPSHOT</version>
      </dependency>`
      `      <repository>
          <id>dmulloy2-repo</id>
          <url>https://repo.dmulloy2.net/repository/public/</url>
      </repository>`
      protocolManager = ProtocolLibrary.getProtocolManager();
      protocolManager will return null;
      But when I add scope provided it returns the error:
      `[15:23:50 ERROR]: Error occurred while enabling TuTien v1.2.6-Beta (Is it up to date?) java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary at kanci.gamer.tutien.TuTien.onEnable(TuTien.java:32) ~[TuTien-1.2.6-Beta.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496] at net.minecraft.server.MinecraftServer.loadWorld....`
 
 I have added the dependency to my plugin and am using it
 [15:50:05 INFO]: ProtocolLib v5.2.0-SNAPSHOT-679
[15:50:05 INFO]: Authors: dmulloy2 and Comphenix
[15:50:05 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues

I don't know where I went wrong
