### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.  - Minecraft 1.20.4

### ISSUE THREAD

**Issue by TheExotik** [dmulloy2/ProtocolLib#2730]
[12:04:55 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[12:04:55 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[12:04:56 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1148)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@34ced819[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4dff9512
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4f14a2b3
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@301247c0
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2121,minecraftVersion=1.20.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@b91ea9b
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@b91ea9b
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@46aaab26
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.1
  Server:
    git-Purpur-2121 (MC: 1.20.4)

**Comment by BasToTheMax** [comment]
I'm having the same problem. I will notify you when I find a fix

**Comment by xnz233** [comment]
I'm having the same problem,too. How to fix it?  (QAQ)

**Comment by lukalt** [comment]
Use the latest development build: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar
