### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by amongcat** [dmulloy2/ProtocolLib#2734]
**Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type=input instanceof interface java.util.Map}
  	at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:191)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:284)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:317)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@357b0bf5[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@87cde1f
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2edddf48
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4e0a3335
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
      file=plugins\ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@4d2113f3
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4d2113f3
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib (1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@124abb96
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.8
  Server:
    git-Paper-318 (MC: 1.20.2)**

**Comment by Tarluin** [comment]
I am having a similar problem with v5.1.0 on MC 1.20.4

`[22:18:11 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3d448c4e[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@5a4379f8
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@437cb802
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1fe4f51e
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-381,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@3721e1b6
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@3721e1b6
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@3fa68452
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21
  Server:
    git-Paper-381 (MC: 1.20.4)
`

**Comment by lukalt** [comment]
You need to use a version of ProtocolLib, which is compatible with the Minecraft Version you use.

For 1.20.4, use this version: https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar
