### ISSUE TITLE
Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by NeglectDream** [dmulloy2/ProtocolLib#2737]
[22:06:04] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Unable to access field private final int net.minecraft.server.v1_12_R1.EnumProtocol.g
          at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:119)
          at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:84)
          at com.comphenix.protocol.reflect.StructureModifier$$Lambda$209/0x0000000000000000.apply(Unknown Source)
          at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
          at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
          at java.util.Iterator.forEachRemaining(Iterator.java:116)
          at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
          at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
          at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
          at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
          at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
          at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
          at com.comphenix.protocol.reflect.StructureModifier.getFields(StructureModifier.java:183)
          at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:116)
          at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:101)
          at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:115)
          at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:294)
          at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
          at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
          at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
          at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
          at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323)
          at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222)
          at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
          at java.lang.Thread.run(Thread.java:823)
  Caused by: java.lang.IllegalAccessException: illegal setter on final field
          at java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:808)
          at com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getFieldAccessor(MethodHandleHelper.java:96)
          ... 24 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@b444fe80[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@47b0cc35
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@ad029e5f
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=top.iseason.bukkit.model.PLoader@a9a17831
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-1620,minecraftVersion=1.12.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@d13f1f71
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@3d9404cb
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@5aaf2d
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    1.8.0_282
  Server:
    git-Paper-1620 (MC: 1.12.2)

**Comment by Tarluin** [comment]
You prolly need version 4.4.0 for MC 1.12.2 https://github.com/dmulloy2/ProtocolLib/releases/download/4.4.0/ProtocolLib.jar
