### ISSUE TITLE
Doesn't work in 1.20.2

### ISSUE THREAD

**Issue by SeCrEaT999** [dmulloy2/ProtocolLib#2739]
An error occurs when this plugin is built with another plugin. So I tried building ProtocolLib by myself, but I still got an error. The error code is:

`*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
System Info: Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.1+12-LTS-29) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
[20:44:41 INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[20:44:43 INFO]: Loaded 1174 recipes
[20:44:43 INFO]: Loaded 1271 advancements
[20:44:44 INFO]: Starting minecraft server version 1.20.2
[20:44:44 INFO]: Loading properties
[20:44:45 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
[20:44:46 INFO]: Server Ping Player Sample Count: 12
[20:44:46 INFO]: Using 4 threads for Netty based IO
[20:44:46 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[20:44:46 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[20:44:46 INFO]: Default game type: SURVIVAL
[20:44:46 INFO]: Generating keypair
[20:44:47 INFO]: Starting Minecraft server on [It's a secret]
[20:44:47 INFO]: Using default channel type
[20:44:47 INFO]: Paper: Using Java compression from Velocity.
[20:44:47 INFO]: Paper: Using Java cipher from Velocity.
[20:44:47 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[20:44:47 WARN]: [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
[20:44:48 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3e577718[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3368e71b
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4dbe5050
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1fbf93d5
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@417d502d
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@417d502d
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@72fb247a
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.1
  Server:
    git-Paper-318 (MC: 1.20.2)

[20:44:48 INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:44:48 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[20:44:48 ERROR]: ******************************************************
[20:44:48 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[20:44:48 ERROR]: *** Please use the built-in reload command!        ***
[20:44:48 ERROR]: ******************************************************`

**Comment by lukalt** [comment]
Use this build: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar
ProtocolLib 5.1.0 does not with with MC 1.20.2

**Comment by GamingWithJohn12** [comment]
i used that build and it doesnt work

**Comment by hellokimhajun** [comment]
> 이 빌드를 사용하세요: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/artifact/build/libs/ProtocolLib.jar ProtocolLib 5.1.0은 MC 1.20.2와 호환되지 않습니다.

Thank you very much. It works very nicely.
