### ISSUE TITLE
NullPointerException: type cannot be null

### ISSUE THREAD

**Issue by Rollczi** [dmulloy2/ProtocolLib#2741]
version `5.2.0-SNAPSHOT-679`

While joining to server: 

net.minecraft.server.v1_16_R3.ReportedException: Sending packet
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1993) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1958) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:281) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:190) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:87) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:583) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1582) ~[server.jar:git-Hyperium-ca5a177]        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:438) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[server.jar:git-Hyperium-ca5a177]        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[server.jar:git-Hyperium-ca5a177]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[server.jar:git-Hyperium-ca5a177]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[server.jar:git-Hyperium-ca5a177]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[server.jar:git-Hyperium-ca5a177]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1985) ~[server.jar:git-Hyperium-ca5a177]
        ... 12 more

**Comment by qaz197418i** [comment]
I have same issues
