### ISSUE TITLE
Request help plugin error on 1.20.4purpur core

### ISSUE THREAD

**Issue by AssassinOWL** [dmulloy2/ProtocolLib#2747]
[16:49:34 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[16:49:34 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[16:49:36 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:519)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1148)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
        at java.base/java.lang.Thread.run(Thread.java:842)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@45cd1b02[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7eb49f0d
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4387fc18
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@5a1322ba
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2127,minecraftVersion=1.20.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@2dbd92fe
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@2dbd92fe
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@12632201
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    git-Purpur-2127 (MC: 1.20.4)

[16:49:38 ERROR]: ******************************************************
[16:49:38 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[16:49:38 ERROR]: *** Please use the built-in reload command!        ***
[16:49:38 ERROR]: ****************************************************** 

[16:49:46 INFO]: [CMI] Enabling CMI v9.6.9.8
[16:49:46 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[16:49:46 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[16:49:46 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[16:49:46 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[16:49:46 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[16:49:46 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[16:49:46 INFO]: _______________________________________________________
[16:49:46 INFO]:   Integrating PaperSpigot async methods
[16:49:46 INFO]:   Vault found. (Loaded: true)
[16:49:47 INFO]:   59 Enabled and 0 Disabled modules
[16:49:47 INFO]:   ProtocolLib was found but some issues accured while enabling it, check if you have correct ProtocolLib version for your server. Compatability will not be enabled.

Request help Request help Request help Request help Request help

**Comment by CloudeLecaw** [comment]
you allready found the way to github so why dont use the latest jenkons version 679 for 1.20.4?

https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar
