### ISSUE TITLE
[BUG] ProtocolLib 5.1.1 - Failed to find NMS class: WorldType

### ISSUE THREAD

**Issue by Auracio** [dmulloy2/ProtocolLib#2752]
[22:55:28 WARN]: [ProtocolLib] [Debug] Exception registering converter
java.lang.RuntimeException: Failed to find NMS class: WorldType
at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$2(MinecraftReflection.java:1382) ~[ProtocolLib-5.1.1-#673.jar:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1382) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.utility.MinecraftReflection.getWorldTypeClass(MinecraftReflection.java:818) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters.addConverter(BukkitConverters.java:1310) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1289) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1330) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.injector.PacketConstructor.‹init›(PacketConstructor.java:61) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.injector.PacketConstructor.‹clinit›(PacketConstructor.java:46) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:107) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.wrappers.WrappedDataWatcher.fakeEntity(WrappedDataWatcher.java:138) ~[ProtocolLib-5.1.1-#673.jar:?]
at com.comphenix.protocol.wrappers.WrappedDataWatcher.‹init›(WrappedDataWatcher.java:82) ~[ProtocolLib-5.1.1-#673.jar:?]
at org.maxgamer.quickshop.shop.VirtualDisplayItem$PacketFactory.createFakeItemMetaPacket(VirtualDisplayItem.java:443) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.shop.VirtualDisplayItem$PacketFactory.testFakeItem(VirtualDisplayItem.java:359) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.virtualDisplaySupportTest(EnvironmentChecker.java:428) ~[QuickShop-5.1.2.5.jar:?]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:869) ~[QuickShop-5.1.2.5.jar:?]
at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:961) ~[QuickShop-5.1.2.5.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

The server is under Paper 1.20.2 (build 318) with ProtocolLib 5.1.1
It seems to be because of the "QuickShop Reremake 5.1.2.5" plugin
I also tried removing all the plugins that worked with ProtocolLib, and there was still the same error

**Comment by jordoncodes** [comment]
calling `PacketContainer.getWorldTypeModifier().write(0, WorldType)` on a respawn packet seems to cause this error
