### ISSUE TITLE
ProtocolLib not working on paper 1.20.4 server

### ISSUE THREAD

**Issue by TBA-3** [dmulloy2/ProtocolLib#2768]
:33 INFO]: Loading server plugin ProtocolLib v5.1.0
[21:02:33 WARN]: Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[21:02:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1129)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
  	at java.base/java.lang.Thread.run(Thread.java:842)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@4118437b[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3443ac9f
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@55aee795
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@e97b585
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-398,minecraftVersion=1.20.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@24195ece
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@24195ece
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@35a1215a
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-398 (MC: 1.20.4)

**Comment by VapeLite** [comment]
same error

**Comment by Yingyya** [comment]
same error

**Comment by notswedish** [comment]
same error here

**Comment by JakeGBLP** [comment]
same issue here

**Comment by DuckyProgrammer** [comment]
https://github.com/dmulloy2/ProtocolLib/issues/2732#issuecomment-1889625449

**Comment by AyavouyaGR** [comment]
Same error to me

**Comment by JakeGBLP** [comment]
works for me, idk what changed, i suggest updating your server version
