### ISSUE TITLE
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary with 3

### ISSUE THREAD

**Issue by WizTheGreat** [dmulloy2/ProtocolLib#2774]
[15:14:35 ERROR]: Error occurred while enabling PLUGIN v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at PLUGIN ArmorAbilitiesPlugin.onEnable(ArmorAbilitiesPlugin.java:61) ~[Kings' Crowns.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at  #io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/8bdcf3bd-fbe7-407e-9b44-262f265f3cb6)
Ive tried both singularly and together
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/a3fbca2e-8c6e-4d05-8b82-1d617f38a2e7)
code is fine tho, it recognizes it
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/3b90b98d-56c7-4132-b43f-8b31e8a92c6f)
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/109e9e69-5dc0-4711-84d8-315ad232660d)
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/453d81fb-4ac6-4f30-a961-e1fc919935e5)
Three in dependencies, yes ive tried all of them alone before this, with and without their matching counterparts in the artifact/libraries
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/b460a49f-ab67-4965-a28b-d7d482dcd348)
Three more in artifacts, same story
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/c1a65a01-dafe-4fb8-9a44-4e757fb79787)
But some red i dont understand
![image](https://github.com/dmulloy2/ProtocolLib/assets/150665140/0d3cf83f-cd20-4a4a-80d2-f60ef81e7a0f)
and a regular one both in libraries, on the plugin module

**Comment by WizTheGreat** [comment]
> Make sure that
> 
> 1. ProtocoLib is installed as a plugin on your plugin and loads successfully. Furthermore you should add `<scope>provided</scope>` to ProtocolLib in your `pom.xml`
> 2. You have `depend: [ProtocolLib]` in your `plugin.yml`

1. plugin on my plugin? I know i have it when i build the artifact
1.5. Mb I do, didn't get that part
2. I tried that and it said dependency didn't exist

**Comment by lukalt** [comment]
Sorry, that was a typo. You need to install the ProtocolLib plugin on your spigot server. So place the Jar File in your plugins/ Folder https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar
