### ISSUE TITLE
Needs 1.20x support

### ISSUE THREAD

**Issue by KewcheeJuice** [dmulloy2/ProtocolLib#2786]
I got this error message when I installed ProtocolLib (ver 5.1.0) on my server. Im starting a survival Paper 1.20.4 server and the majority of the plugins i need/use require protocollib as a dependency. Here is the error messages in my console:

[13:59:18 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[13:59:21 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@61004885[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3a982447
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2ef14d7
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4eec9131
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-409,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@560a1feb
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@560a1feb
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@67699ee
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-409 (MC: 1.20.4)

AND

[13:59:24 ERROR]: ******************************************************
[13:59:24 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[13:59:24 ERROR]: *** Please use the built-in reload command!        ***
[13:59:24 ERROR]: ******************************************************

**Comment by lukalt** [comment]
Hi, 
please use the latest development build of ProtocolLib. This versions offers 1.20.4 support
https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar

**Comment by KewcheeJuice** [comment]
> Hi, please use the latest development build of ProtocolLib. This versions offers 1.20.4 support https://ci.dmulloy2.net/job/ProtocolLib/679/artifact/build/libs/ProtocolLib.jar

Thank you. Everything is working fine and dandy again
