### ISSUE TITLE
Spigot 1.20.4 unable to load ProtocolLib 5.4.3

### ISSUE THREAD

**Issue by TheBlueVolcano** [dmulloy2/ProtocolLib#2791]
- [x] This issue is not solved in a development build

**Describe the bug**
I was just trying to install ProtocolLib 5.4.3 to my Spigot 1.20.4 server and got the following error

`
[11:27:56] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:435)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1f3cc280[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@25044a6e
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@5cd5b48c
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@6684cfed
      server=CraftServer{serverName=CraftBukkit,serverVersion=4039-Spigot-c198da2-4c687f2,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@62858308
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1bbb20fd
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@aced212
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.1
  Server:
    4039-Spigot-c198da2-4c687f2 (MC: 1.20.4)
`

**To Reproduce**
unsure

**Expected behavior**
I expected it to load properly

**Version Info**
since plugin didnt load command doesnt work

**Comment by lukalt** [comment]
As I see in your log files, you use ProtocolLib 5.1.0, which is not compatible with Minecraft 1.20.4.
Use the latest development build instead: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/
