### ISSUE TITLE
INTERNAL ERROR: Unable to intercept a read client packet.

### ISSUE THREAD

**Issue by Aggroblut** [dmulloy2/ProtocolLib#28]
Hey,
cant find some error like that in the issue here. I also dont find a search bar. 
______________________________
Version
Spigot - BuildTools #19:
```
This server is running CraftBukkit version git-Spigot-f234263-2db3ea2 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
```
ProtocolLib Version
```
[07:10:12] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.6.3-SNAPSHOT
```

______________________________
Errorlog

```
[16:46:58] [User Authenticator #191/INFO]: UUID of player Schneidertm is 91bc7c66-c088-4d3d-b606-6eb3e962c969
[16:46:58] [Server thread/INFO]: [VanishNoPacket] Schneidertm disappeared.
[16:46:58] [Server thread/INFO]: [WorldGuard] Enabled no-drowning mode for Schneidertm (player is in group 'wg-amphibious')
[16:46:58] [Server thread/INFO]: Schneidertm[/-:5593] logged in with entity id 1031377 at ([world] 197.5105700323038, 82.48990476568316, -284.27807016588673)
[16:46:59] [User Authenticator #192/INFO]: UUID of player paul_bachmann is 6d7cd4bd-7e1d-443d-a27b-536ae83cffcb
[16:46:59] [Server thread/INFO]: paul_bachmann[/-:49645] logged in with entity id 1031406 at ([world] 160.48703568048407, 77.0, 762.493386997606)
[16:46:59] [Server thread/INFO]: Peace09jan lost connection: Inactivity - 22 Minutes
[16:46:59] [Server thread/INFO]: Peace09jan left the game.
[16:46:59] [Server thread/INFO]: James_Bond_1712 lost connection: Inactivity - 22 Minutes
[16:46:59] [Server thread/INFO]: James_Bond_1712 left the game.
[16:46:59] [Netty Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.NullPointerException) occured in com.comphenix.protocol.injector.netty.ChannelInjector@3acb41e3.[m
[16:46:59] [Netty Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap$PlayerKey$1.apply(ConcurrentPlayerMap.java:41)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap$PlayerKey$1.apply(ConcurrentPlayerMap.java:38)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.cachePlayerKey(ConcurrentPlayerMap.java:196)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:209)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:29)
  	at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:148)
  	at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:131)
  	at com.comphenix.protocol.async.AsyncFilterManager.getSendingQueue(AsyncFilterManager.java:439)
  	at com.comphenix.protocol.async.AsyncFilterManager.enqueueSyncPacket(AsyncFilterManager.java:320)
  	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:640)
  	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:603)
  	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetReceived(NettyProtocolInjector.java:300)
  	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketReceiving(NettyProtocolInjector.java:266)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:501)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:241)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:240)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
  	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
  	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    io.netty.buffer.UnpooledHeapByteBuf@446b74f2[
      alloc=UnpooledByteBufAllocator(directByDefault: true)
      array={4,-64,125,-12,49,-47,-78,92,-58,64,87,0,0,0,0,0,0,-64,-127,-121,-22,-74,-61,-93,55,1}
      tmpNioBuf=<null>
      refCnt=1
      readerIndex=26
      writerIndex=26
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
      swappedBuf=<null>
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@6b21877d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3f2e6990
        packetListeners=[com.comphenix.protocol.async.NullPacketListener@58d80569, PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutNamedSoundEffect[41, legacy: 62]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@9e289b1, PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInFlying[3, legacy: 10]], gamephase=PLAYING, options=[]}], com.comphenix.protocol.async.NullPacketListener@194f0]
        packetInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector$5@48ffcf87
        playerInjection=com.comphenix.protocol.injector.netty.NettyProtocolInjector$4@1291cd82
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@224b1b54
        inputBufferedPackets=[PacketPlayInPosition[4, legacy: 11], PacketPlayInEntityAction[11, legacy: 19], PacketPlayInSteerVehicle[12, legacy: 27], PacketPlayInPositionLook[6, legacy: 13]]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@70ef3962
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@69a08ada
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@460ca00a
        reporter=com.comphenix.protocol.ProtocolLibrary$1@2afc2463
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-f234263-2db3ea2,minecraftVersion=1.8}
        library=ProtocolLib v3.6.3-SNAPSHOT
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6f30e820
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=6
        packetCreation=true
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector@1621ebb3
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@cf9401f
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.8.0)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@3fe0b9e0
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@3acb41e3[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@7652bc3c
      player=<null>
      updated=<null>
      playerConnection=<null>
      networkManager=net.minecraft.server.v1_8_R1.NetworkManager@31c443d4
      originalChannel=[id: 0xf2829ce3, /91.5.212.125:50116 => /78.143.5.146:25565]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=private io.netty.channel.Channel net.minecraft.server.v1_8_R1.NetworkManager.i], container=net.minecraft.server.v1_8_R1.NetworkManager@31c443d4, previous=[id: 0xf2829ce3, /91.5.212.125:50116 => /78.143.5.146:25565], current=[id: 0xf2829ce3, /91.5.212.125:50116 => /78.143.5.146:25565], previousLoaded=true, currentSet=false, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@793f1ccf
      vanillaDecoder=net.minecraft.server.v1_8_R1.PacketDecoder@1e7c9839
      vanillaEncoder=net.minecraft.server.v1_8_R1.PacketEncoder@5edd5d2
      protocolEncoder=com.comphenix.protocol.injector.netty.ChannelInjector$3@4170d108
      finishHandler=com.comphenix.protocol.injector.netty.ChannelInjector$4@55ab85c8
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.NettyProtocolInjector@1621ebb3
      processor=com.comphenix.protocol.injector.NetworkProcessor@3efa59c7
      injected=true
      closed=true
      cumulation=UnpooledHeapByteBuf(ridx: 26, widx: 26, cap: 26)
      singleDecode=false
      decodeWasNull=true
      first=true
      added=true
    ]
  Version:
    ProtocolLib v3.6.3-SNAPSHOT
  Server:
    git-Spigot-f234263-2db3ea2 (MC: 1.8)

[16:47:01] [Server thread/INFO]: Schneidertm issued server command: /tps
[16:47:12] [Server thread/INFO]: Schneidertm lost connection: Disconnected
[16:47:16] [User Authenticator #193/INFO]: UUID of player Schneidertm is 91bc7c66-c088-4d3d-b606-6eb3e962c969
[16:47:16] [Server thread/INFO]: [VanishNoPacket] Schneidertm disappeared.
[16:47:16] [Server thread/INFO]: [WorldGuard] Enabled no-drowning mode for Schneidertm (player is in group 'wg-amphibious')
[16:47:16] [Server thread/INFO]: Schneidertm[/-:5607] logged in with entity id 1033255 at ([world] 197.51796904789808, 82.48990476568316, -297.8363131272098)

```

**Comment by dmulloy2** [comment]
Should be fixed now.
