### ISSUE TITLE
Create packet not working with mojmap

### ISSUE THREAD

**Issue by Xiao-MoMi** [dmulloy2/ProtocolLib#2801]
- [ √ ] This issue is not solved in a development build

**Describe the bug**
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundAddEntityPacket
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.lambda$newPacket$2(StructureCache.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:103) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:113) ~[ProtocolLib.jar:?]

**To Reproduce**
PacketContainer entityPacket = new PacketContainer(PacketType.Play.Server.SPAWN_ENTITY);

**Version Info**
[dump-2024-02-17_17.05.12.txt](https://github.com/dmulloy2/ProtocolLib/files/14318291/dump-2024-02-17_17.05.12.txt)

**Comment by Xiao-MoMi** [comment]
After testing with paper, it's actually a problem with Mojmap
![image](https://github.com/dmulloy2/ProtocolLib/assets/70987828/1037c2f8-74d1-4eaa-ac1b-5c23cbfd2f17)
