### ISSUE TITLE
ProtocolLib v5.1.0 for mc version 1.20.4 not loading / failing 

### ISSUE THREAD

**Issue by DevSnox** [dmulloy2/ProtocolLib#2804]
2024-02-18 18:37:04 [17:37:04 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
2024-02-18 18:37:04   If this problem hasn't already been reported, please open a ticket
2024-02-18 18:37:04   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
2024-02-18 18:37:04   Stack Trace:
2024-02-18 18:37:04   java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
2024-02-18 18:37:04     at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
2024-02-18 18:37:04     at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
2024-02-18 18:37:04     at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
2024-02-18 18:37:04     at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
2024-02-18 18:37:04     at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
2024-02-18 18:37:04     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
2024-02-18 18:37:04     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
2024-02-18 18:37:04     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
2024-02-18 18:37:04     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
2024-02-18 18:37:04     at java.base/java.lang.Thread.run(Unknown Source)
2024-02-18 18:37:04   Dump:
2024-02-18 18:37:04   Parameters: 
2024-02-18 18:37:04     [NULL]
2024-02-18 18:37:04   Sender:
2024-02-18 18:37:04     com.comphenix.protocol.ProtocolLib@1507e3e9[
2024-02-18 18:37:04       statistics=<null>
2024-02-18 18:37:04       packetTask=<null>
2024-02-18 18:37:04       tickCounter=0
2024-02-18 18:37:04       configExpectedMod=-1
2024-02-18 18:37:04       updater=com.comphenix.protocol.updater.SpigotUpdater@2489bcf0
2024-02-18 18:37:04       redirectHandler=<null>
2024-02-18 18:37:04       scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@e3b1b23
2024-02-18 18:37:04       commandProtocol=<null>
2024-02-18 18:37:04       commandPacket=<null>
2024-02-18 18:37:04       commandFilter=<null>
2024-02-18 18:37:04       packetLogging=<null>
2024-02-18 18:37:04       skipDisable=false
2024-02-18 18:37:04       isEnabled=false
2024-02-18 18:37:04       loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@ee998f1
2024-02-18 18:37:04       server=CraftServer{serverName=Paper,serverVersion=git-Paper-429,minecraftVersion=1.20.4}
2024-02-18 18:37:04       file=plugins/ProtocolLib.jar
2024-02-18 18:37:04       description=org.bukkit.plugin.PluginDescriptionFile@5de554f5
2024-02-18 18:37:04       pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5de554f5
2024-02-18 18:37:04       dataFolder=plugins/ProtocolLib
2024-02-18 18:37:04       classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
2024-02-18 18:37:04       naggable=true
2024-02-18 18:37:04       newConfig=YamlConfiguration[path='', root='YamlConfiguration']
2024-02-18 18:37:04       configFile=plugins/ProtocolLib/config.yml
2024-02-18 18:37:04       logger=com.destroystokyo.paper.utils.PaperPluginLogger@7d47df16
2024-02-18 18:37:04       lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@3693dcc8
2024-02-18 18:37:04       allowsLifecycleRegistration=true
2024-02-18 18:37:04     ]
2024-02-18 18:37:04   Version:
2024-02-18 18:37:04     ProtocolLib v5.1.0
2024-02-18 18:37:04   Java Version:
2024-02-18 18:37:04     20.0.2
2024-02-18 18:37:04   Server:
2024-02-18 18:37:04     git-Paper-429 (MC: 1.20.4)

**Comment by DevSnox** [comment]
Solved through newest dev-build
