### ISSUE TITLE
Bug ProtocolLib wont load when i start the server

### ISSUE THREAD

**Issue by Mafiaproo** [dmulloy2/ProtocolLib#2805]
- [ ] This issue is not solved in a development build

**Describe the bug**
I wanted to install ProtocolLib, and when I install it and start the server, I get errors in the console.
And since I have some plugins that support prototolib but don't want to load, it crashes several other plugins. Basically, I wanted to install Image Frame, which needs protocolLib, but I'm getting errors.
Please help me, I really need these 2 plugins for my server, I can't do without them.

**To Reproduce**
1. Install PaperMC git-Paper-424 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 37df121)
2. install Prototollib
3. Start the server

` Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@69320d7d[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@49717cee
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@58e4fd42
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@39742101
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-424,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@200085f
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@200085f
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@6595a126
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@1f08e11
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-424 (MC: 1.20.4)`

**Expected behavior**
ProtocolLib has been loaded without any error and without crashing my others plugins

**Version Info**
PaperMC : git-Paper-424 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 37df121)
ProtocolLib : ProtocolLib 5.1.0

**Additional context**
(Nothing)

**Comment by lukalt** [comment]
Please use the latest development build from here: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/ for 1.20.4 support.
