### ISSUE TITLE
not working in 1.20.4

### ISSUE THREAD

**Issue by gabi21yt** [dmulloy2/ProtocolLib#2816]
S[02:32:47] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[02:32:58] [ServerMain/INFO]: Loaded 1174 recipes
[02:33:00] [ServerMain/INFO]: Loaded 1271 advancements
[02:33:01] [Server thread/INFO]: Starting minecraft server version 1.20.4
[02:33:01] [Server thread/WARN]: ****************************
[02:33:01] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[02:33:01] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[02:33:01] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[02:33:01] [Server thread/WARN]: ****************************
[02:33:01] [Server thread/INFO]: Loading properties
[02:33:01] [Server thread/INFO]: This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)
[02:33:03] [Server thread/INFO]: Server Ping Player Sample Count: 12
[02:33:03] [Server thread/INFO]: Using 4 threads for Netty based IO
[02:33:04] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[02:33:04] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[02:33:05] [Server thread/INFO]: Default game type: SURVIVAL
[02:33:05] [Server thread/INFO]: Generating keypair
[02:33:06] [Server thread/INFO]: Starting Minecraft server on *:25565
[02:33:06] [Server thread/INFO]: Using epoll channel type
[02:33:06] [Server thread/INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[02:33:06] [Server thread/INFO]: Paper: Using OpenSSL (Linux aarch64) cipher from Velocity.
[02:33:06] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[02:33:07] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[02:33:14] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@653889b5[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@788d22d7
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4ea157b2
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@33e279ea
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-435,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@33c3809
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@33c3809
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@67e9ff24
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@44a4b6e0
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-435 (MC: 1.20.4)

[02:33:14] [Server thread/INFO]: [Logger] Loading server plugin Logger v1.8.0.11
[02:33:14] [Server thread/INFO]: [ChunkLoader] Loading server plugin ChunkLoader v3.2.1
[02:33:14] [Server thread/INFO]: [Orebfuscator] Loading server plugin Orebfuscator v5.4.3
[02:33:14] [Server thread/INFO]: [TAB] Loading server plugin TAB v4.1.2
[02:33:14] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[02:33:14] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[02:33:14] [Server thread/ERROR]: ******************************************************
[02:33:14] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[02:33:14] [Server thread/ERROR]: *** Please use the built-in reload command!        ***
[02:33:14] [Server thread/ERROR]: ******************************************************
[02:33:14] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
[02:33:14] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[02:33:14] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[02:33:14] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[02:33:14] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[02:33:14] [Server thread/INFO]: Preparing level "world"
[02:33:16] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[02:33:22] [Server thread/INFO]: Time elapsed: 5933 ms
[02:33:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[02:33:22] [Server thread/INFO]: Time elapsed: 278 ms
[02:33:22] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[02:33:22] [Server thread/INFO]: Time elapsed: 361 ms
[02:33:22] [Server thread/INFO]: [Logger] Enabling Logger v1.8.0.11
[02:33:22] [Server thread/ERROR]: [Logger] Current version is unknown, using the latest known one.
[02:33:25] [Server thread/INFO]: [Logger] Â§5
|
Â§5|Â§b     __                               
Â§5|Â§b    / /   ____  ____ _____ ____  _____
Â§5|Â§b   / /   / __ \/ __ `/ __ `/ _ \/ ___/
Â§5|Â§b  / /___/ /_/ / /_/ / /_/ /  __/ /    
Â§5|Â§b /_____/\____/\__, /\__, /\___/_/     
Â§5|Â§b             /____//____/     Â§c1.8.0.11Â§e [ Bukkit Version ]        
Â§5|
Â§5|Â§6 This is a DEV Build, please report any issues!
Â§5|
Â§5|Â§f Discord Â§9https://discord.gg/MfR5mcpVfX
Â§5|
[02:33:25] [Server thread/INFO]: [Logger] Â§6Thanks to everyone's contributions that helped made this project possible!
[02:33:25] [Server thread/INFO]: [Logger] Plugin Enabled!
[02:33:25] [Server thread/INFO]: [ChunkLoader] Enabling ChunkLoader v3.2.1
[02:33:25] [Server thread/INFO]: ChunkLoader >> Enabled Paper version.
[02:33:25] [Server thread/INFO]: ChunkLoader >> messages_en file was loaded successfully.
[02:33:26] [Server thread/INFO]: ChunkLoader >> Chunk -86;-76;world was loaded correctly.
[02:33:26] [Server thread/INFO]: ChunkLoader >> Chunk -85;-76;world was loaded correctly.
[02:33:26] [Server thread/INFO]: ChunkLoader >> Chunk -85;-77;world was loaded correctly.
[02:33:26] [Server thread/INFO]: ChunkLoader >> Chunk -86;-77;world was loaded correctly.
[02:33:26] [Server thread/INFO]: 
[02:33:26] [Server thread/INFO]:  ChunkLoader use InventoryAPI developed by KayTeam
[02:33:26] [Server thread/INFO]: 
[02:33:26] [Server thread/INFO]:  Website: https://kayteam.org
[02:33:26] [Server thread/INFO]:  Github: https://github.com/KayTeam-Studio/inventory-api
[02:33:26] [Server thread/INFO]: 
[02:33:26] [Server thread/INFO]: 
[02:33:26] [Server thread/INFO]: * ChunkLoader Enabled
[02:33:26] [Server thread/INFO]: *
[02:33:26] [Server thread/INFO]: * Version: 3.2.1
[02:33:26] [Server thread/INFO]: * Author: KayTeam
[02:33:26] [Server thread/INFO]: * Website: https://kayteam.org
[02:33:26] [Server thread/INFO]: *
[02:33:26] [Server thread/INFO]: * I like the bread!
[02:33:26] [Server thread/INFO]: 
[02:33:26] [Server thread/INFO]: [Orebfuscator] Enabling Orebfuscator v5.4.3
[02:33:26] [Server thread/ERROR]: [Orebfuscator] An error occurred while enabling plugin
java.lang.RuntimeException: ProtocolLib can't be found or is disabled! Orebfuscator can't be enabled.
	at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:48) ~[orebfuscator-plugin-5.4.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-435]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-435]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-435]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-435]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-435]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[02:33:26] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.4.3
[02:33:26] [Server thread/INFO]: [TAB] Enabling TAB v4.1.2
[02:33:29] [Server thread/INFO]: [TAB] Enabled in 1496ms
[02:33:30] [Server thread/INFO]: Running delayed init tasks
[02:33:30] [Server thread/INFO]: Done (29.094s)! For help, type "help"
[02:33:30] [Server thread/INFO]: Timings Reset
[02:33:33] [Server thread/WARN]: [EntityLookup] Entity uuid already exists: 17a3ac9a-6dda-453e-8569-c8e3b3cbd676, mapped to EntityBat['Bat'/53, uuid='17a3ac9a-6dda-453e-8569-c8e3b3cbd676', l='ServerLevel[world]', x=-1351.74, y=1.98, z=-1223.63, cpos=[-85, -77], tl=1919, v=true], can't add EntityBat['Bat'/134, uuid='17a3ac9a-6dda-453e-8569-c8e3b3cbd676', l='ServerLevel[world]', x=-1342.53, y=0.56, z=-1222.20, cpos=[-84, -77], tl=2044, v=false]
[02:33:33] [Server thread/WARN]: [EntityLookup] Entity uuid already exists: 8fa68087-83b0-4d8d-80c2-698b85088844, mapped to EntityBat['Bat'/125, uuid='8fa68087-83b0-4d8d-80c2-698b85088844', l='ServerLevel[world]', x=-1354.49, y=32.40, z=-1184.43, cpos=[-85, -75], tl=1479, v=true], can't add EntityBat['Bat'/149, uuid='8fa68087-83b0-4d8d-80c2-698b85088844', l='ServerLevel[world]', x=-1355.71, y=32.69, z=-1183.42, cpos=[-85, -74], tl=1484, v=false]
[02:33:34] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3807ms or 76 ticks behind

**Comment by uncovery** [comment]
Same as #2820
