### ISSUE TITLE
[Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib. Purpur-2151 (MC: 1.20.4)

### ISSUE THREAD

**Issue by noslowdwn** [dmulloy2/ProtocolLib#2820]
[21:12:44] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib-5.1.0.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:311)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@268b7e52[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@53d7db92
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@462c0b5b
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@580042f3
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2151,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib-5.1.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@48628a26
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@48628a26
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib-5.1.0.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@347fe64d
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@378a302b
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.9
  Server:
    git-Purpur-2151 (MC: 1.20.4)

**Comment by uncovery** [comment]
Same here on spigot 1.20.4 and Java 17.0.10

```
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type inpu
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:435)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@59429319[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@62ed65a6
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@1b01e6b8
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@49d9bf87
      server=CraftServer{serverName=CraftBukkit,serverVersion=4054-Spigot-e9ec548-619936d,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@d87a284
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@9b3d033
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@1d06008e
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    4054-Spigot-e9ec548-619936d (MC: 1.20.4)

```

**Comment by uncovery** [comment]
Fixed in the latest build from here: https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/
