### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

### ISSUE THREAD

**Issue by KinglyShade** [dmulloy2/ProtocolLib#2821]
- [ ] This issue is not solved in a development build

**Describe the bug**
 java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

**To Reproduce**
1.start the server

**Expected behavior**
start paper I start the server and that happens

**Screenshots**
![imagen](https://github.com/dmulloy2/ProtocolLib/assets/150642678/ef040fa7-5dea-4c4c-9807-179f4792f465) 
![imagen](https://github.com/dmulloy2/ProtocolLib/assets/150642678/700b0bd5-212f-4f4f-b3d2-3c996a7606fe)

**Version Info**
[00:24:03 WARN]: Unexpected exception while parsing console command "protocol dump"
org.bukkit.command.CommandException: Cannot execute command 'protocol' in plugin ProtocolLib v5.1.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-435]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:984) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-435]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-435]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Additional context**
i start the server

**Comment by CSJZSN** [comment]
I'm having this issue as well

**Comment by uncovery** [comment]
same as #2820

**Comment by Harineko0** [comment]
same with
* Protocollib v5.1.0
* Paper-1.20.4-446

**Comment by CSJZSN** [comment]
> same as #2820

Thank you!
