### ISSUE TITLE
[ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.

### ISSUE THREAD

**Issue by FateGodI** [dmulloy2/ProtocolLib#2825]
[15:06:12 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[15:06:12 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[15:06:13 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:311)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@30ac98c1[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@12d84157
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@494f28e2
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7c6f94b6
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2151,minecraftVersion=1.20.4}
      file=plugins\[#300]【前置必须插件】ProtocolLib-5.1.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@74eec737
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@74eec737
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\[#300]【前置必须插件】ProtocolLib-5.1.0.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@34ee9a47
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@36bb2492
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.2
  Server:
    git-Purpur-2151 (MC: 1.20.4)

**Comment by FateGodI** [comment]
I still report errors when updating to purpur-1.204-2152.jar

**Comment by FateGodI** [comment]
I only inserted the ProtocolLib plugin and still encountered errors. Below is the error message：
[15:32:04 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[15:32:04 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[15:32:05 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at [#300]【前置必须插件】ProtocolLib-5.1.0.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:311)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@d4e7264[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@63c2fc87
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@46e982e2
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4e27ba2f
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2152,minecraftVersion=1.20.4}
      file=plugins\[#300]【前置必须插件】ProtocolLib-5.1.0.jar
      description=org.bukkit.plugin.PluginDescriptionFile@115bc738
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@115bc738
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\[#300]【前置必须插件】ProtocolLib-5.1.0.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@5669d31a
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@1944ace8
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.2
  Server:
    git-Purpur-2152 (MC: 1.20.4)

[15:32:05 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:32:05 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[15:32:05 ERROR]: ******************************************************
[15:32:05 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[15:32:05 ERROR]: *** Please use the built-in reload command!        ***
[15:32:05 ERROR]: ******************************************************
[15:32:05 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0

**Comment by KARONAGAMING** [comment]
same

**Comment by LuisOPOfficial** [comment]
no 1.20.4, 5.20 dependencies?

**Comment by tjw123-tjw** [comment]
i solved that problem 
you can go to https://ci.dmulloy2.net/job/ProtocolLib/ to see the newest (support 1.20.4)plugins 
我解决了，你去这个作者的编译站下最新版本就可以了。

**Comment by FateGodI** [comment]
> i solved that problem 
> you can go to https://ci.dmulloy2.net/job/ProtocolLib/ to see the newest (support 1.20.4)plugins 
> 我解决了，你去这个作者的编译站下最新版本就可以了。
> 

Thanks,and i'll take the time
谢了，我抽时间看下解决方案
