### ISSUE TITLE
internal evver

### ISSUE THREAD

**Issue by ThePro12335421** [dmulloy2/ProtocolLib#2827]
- [ ] This issue is not solved in a development build

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**
 Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7cbeb61e[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4617b69d
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4f90f607
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@257b75d1
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-435,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@19d08105
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@19d08105
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@463b6c58
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@2e3262aa
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    18.0.2.1
  Server:
    git-Paper-435 (MC: 1.20.4)

**Comment by ThePro12335421** [comment]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:833)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7cbeb61e[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4617b69d
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4f90f607
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@257b75d1
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-435,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@19d08105
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@19d08105
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@463b6c58
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@2e3262aa
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    18.0.2.1
  Server:
    git-Paper-435 (MC: 1.20.4)

**Comment by Ren-1337** [comment]
same prob here on Purpur 1.20.4 

dump : https://pastebin.com/HbRFVVTm
