### ISSUE TITLE
ProtocolLib 1.20.4

### ISSUE THREAD

**Issue by Mathildeuh** [dmulloy2/ProtocolLib#2832]
- [ ] This issue is not solved in a development build

**Describe the bug**
Just crash at start with an error log

**To Reproduce**
Install protocollib on 1.20.4

**Expected behavior**
Error log who said to report it

Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.reload(CraftServer.java:1112)
  	at org.bukkit.Bukkit.reload(Bukkit.java:1024)
  	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
  	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999)
  	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
  	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
  	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
  	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
  	at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
  	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
  	at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
  	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
  	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
  	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
  	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
  	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
  	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
  	at net.minecraft.server.TickTask.run(TickTask.java:18)
  	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
  	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
  	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1455)
  	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
  	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
  	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1432)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
  	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
  	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1333)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1222)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
  	at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@4f667617[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@c3969ff
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@31556a86
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@56958fcc
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-446,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6432e363
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@6432e363
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@27f5d3e8
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@5f290351
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-446 (MC: 1.20.4)

**Comment by PapiCapi** [comment]
You should try the latest dev build ( https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/ )

**Comment by MarkManFlame55** [comment]
Do I need to add this dev build on teh dependencies of the plugins? or the 5.1.0 version works well?

**Comment by blue-pinapple** [comment]
I didn't know where to put this, but I can't use dev builds because I'm on Aternos, is there? Do you know when this might be released?
