### ISSUE TITLE
Cannot load ProtocolLib at startup

### ISSUE THREAD

**Issue by Plexi09** [dmulloy2/ProtocolLib#2834]
I get this when i start my server and protocolLib doesn't works

```
[22:01:19] [Server thread/ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
at java.base/java.lang.Thread.run(Thread.java:840)
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@932699e[
statistics=<null>
packetTask=<null>
tickCounter=0
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@4d8ecbbd
redirectHandler=<null>
scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@357e84f1
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@5d34421a
server=CraftServer{serverName=Paper,serverVersion=git-Paper-318,minecraftVersion=1.20.2}
file=plugins/ProtocolLib (1).jar
description=org.bukkit.plugin.PluginDescriptionFile@7cb856cf
pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7cb856cf
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib (1).jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@427bbd99
]
Version:
ProtocolLib v5.1.0
Java Version:
17.0.9
Server:
git-Paper-318 (MC: 1.20.2)
```

**Comment by l3nnartt** [comment]
use the latest dev build
