### ISSUE TITLE
1.20.4 error

### ISSUE THREAD

**Issue by Head-BOB** [dmulloy2/ProtocolLib#2839]
[10.03 09:09:24] [Server]   Stack Trace:
[10.03 09:09:24] [Server]   java.lang.IllegalArgumentExceptionUnable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
[10.03 09:09:24] [Server]   	at ProtocolLib (7).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
[10.03 09:09:24] [Server]   	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
[10.03 09:09:24] [Server]   	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
[10.03 09:09:24] [Server]   	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
[10.03 09:09:24] [Server]   	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
[10.03 09:09:24] [Server]   	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
[10.03 09:09:24] [Server]   	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[10.03 09:09:24] [Server]   	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[10.03 09:09:24] [Server]   	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[10.03 09:09:24] [Server]   	at java.base/java.lang.Thread.run(Thread.java:833)
[10.03 09:09:24] [Server]   Dump:
[10.03 09:09:24] [Server]   Parameters
[10.03 09:09:24] [Server]     [NULL]
[10.03 09:09:24] [Server]   Sender:
[10.03 09:09:24] [Server]     com.comphenix.protocol.ProtocolLib@7e3e9ebe[
[10.03 09:09:24] [Server]       statistics=<null>
[10.03 09:09:24] [Server]       packetTask=<null>
[10.03 09:09:24] [Server]       tickCounter=0
[10.03 09:09:24] [Server]       configExpectedMod=-1
[10.03 09:09:24] [Server]       updater=com.comphenix.protocol.updater.SpigotUpdater@4440d86b
[10.03 09:09:24] [Server]       redirectHandler=<null>
[10.03 09:09:24] [Server]       scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@45098073
[10.03 09:09:24] [Server]       commandProtocol=<null>
[10.03 09:09:24] [Server]       commandPacket=<null>
[10.03 09:09:24] [Server]       commandFilter=<null>
[10.03 09:09:24] [Server]       packetLogging=<null>
[10.03 09:09:24] [Server]       skipDisable=false
[10.03 09:09:24] [Server]       isEnabled=false
[10.03 09:09:24] [Server]       loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7fada690
[10.03 09:09:24] [Server]       server=CraftServer{serverName=Paper,serverVersion=git-Paper-449,minecraftVersion=1.20.4}
[10.03 09:09:24] [Server]       file=plugins/ProtocolLib (7).jar
[10.03 09:09:24] [Server]       description=org.bukkit.plugin.PluginDescriptionFile@372d11e3
[10.03 09:09:24] [Server]       pluginMeta=org.bukkit.plugin.PluginDescriptionFile@372d11e3
[10.03 09:09:24] [Server]       dataFolder=plugins/ProtocolLib
[10.03 09:09:24] [Server]       classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib (7).jar}
[10.03 09:09:24] [Server]       naggable=true
[10.03 09:09:24] [Server]       newConfig=YamlConfiguration[path='', root='YamlConfiguration']
[10.03 09:09:24] [Server]       configFile=plugins/ProtocolLib/config.yml
[10.03 09:09:24] [Server]       logger=com.destroystokyo.paper.utils.PaperPluginLogger@2ca5bd1e
[10.03 09:09:24] [Server]       lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@39b9859b
[10.03 09:09:24] [Server]       allowsLifecycleRegistration=true
[10.03 09:09:24] [Server]     ]
[10.03 09:09:24] [Server]   Version:
[10.03 09:09:24] [Server]     ProtocolLib v5.1.0
[10.03 09:09:24] [Server]   Java Version:
[10.03 09:09:24] [Server]     17.0.8
[10.03 09:09:24] [Server]   Server:
[10.03 09:09:24] [Server]     git-Paper-(MC: 1.20.4)

**Expected behavior**

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by Head-BOB** [comment]
how do i fix this?

**Comment by aCrazyg1** [comment]
I have that issue too

**Comment by aCrazyg1** [comment]
i think it might just have issue with 1.20.4

**Comment by j4asper** [comment]
Use the latest dev build.
