### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by ragelqdev** [dmulloy2/ProtocolLib#2846]
**Stack Trace:**
```
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Sender:**
```
    com.comphenix.protocol.ProtocolLib@2d614b29[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@b4943c0
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@71fe874f
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@23cd7994
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-450,minecraftVersion=1.20.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@137b1504
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@137b1504
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@5f483434
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@1450c9ec
      allowsLifecycleRegistration=true
```

**Version:**
```
ProtocolLib v5.1.0
```

**Java Version: 21.0.2**
**Server: git-Paper-450 (MC: 1.20.4)**

**Comment by TheExotik** [comment]
Guess i have the same error

`[08:36:29 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:311)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@59a33b6d[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@130de3ec
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@31c340c6
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4123686d
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2158,minecraftVersion=1.20.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5139ab2e
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5139ab2e
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@5adb3b39
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@cbe2510
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.2
  Server:
    git-Purpur-2158 (MC: 1.20.4)`

**Comment by EromDarzok** [comment]
I think I have the same error on the server.

>[2K[02:03:07] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.1.0
>[2K[02:03:07] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
>[2K[02:03:08] [Server thread/ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
at com.comphenix.protocol.injector.PacketFilterManager.(PacketFilterManager.java:120)
at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:431)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:979)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296)
at java.base/java.lang.Thread.run(Thread.java:833)
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@57f8e934[
statistics=
packetTask=
tickCounter=0
configExpectedMod=-1
updater=
redirectHandler=
scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6305190
commandProtocol=
commandPacket=
commandFilter=
packetLogging=
skipDisable=false
isEnabled=false
loader=org.bukkit.plugin.java.JavaPluginLoader@4d70d16a
server=CraftServer{serverName=CraftBukkit,serverVersion=3976-Bukkit-b3b43a6,minecraftVersion=1.20.4}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@5188493f
dataFolder=plugins/ProtocolLib
classLoader=org.bukkit.plugin.java.PluginClassLoader@10fb2a1f
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=org.bukkit.plugin.PluginLogger@1e805e02
]
Version:
ProtocolLib v5.1.0
Java Version:
17.0.5
Server:
3976-Bukkit-b3b43a6 (MC: 1.20.4)

**Comment by ProudCactus741** [comment]
try to download the files from here ''https://itemsadder.devs.beer/first-install'' . It worked for me, and I had the same problem
download links are added in step one
good luck guys

**Comment by ragelqdev** [comment]
> try to download the files from here ''https://itemsadder.devs.beer/first-install'' . It worked for me, and I had the same problem download links are added in step one good luck guys

Thank you very much
