### ISSUE TITLE
ProtocolLibs Error

### ISSUE THREAD

**Issue by SinestroCZE** [dmulloy2/ProtocolLib#2861]
Hello. 
I have problem with ProtocolLibs on paper 1.20.4

Here is output from console:
07:13:42 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[07:13:42 WARN]: [ProtocolLib] Version (MC: 1.20.4) has not yet been tested! Proceed with caution.
[07:13:43 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@6596e3ae[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4226edae
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6d51d033
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7b3ca2c8
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-454,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@5cdb768d
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5cdb768d
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib (1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@21dc3aba
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@25914226
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Paper-454 (MC: 1.20.4)
[07:13:43 INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.45]

Here is the link, where I downloaded ProtocolLibs
[https://www.spigotmc.org/resources/protocollib.1997/](url)

**Comment by TheCalypso** [comment]
Hello, could you try using the last version of Protocolibs at https://ci.dmulloy2.net/job/ProtocolLib//lastBuild/ ?

**Comment by wasmake** [comment]
This error persist even on the latest build @TheCalypso

**Comment by EarthCow** [comment]
I had the same error and it does not occur for me on the latest build.
