### ISSUE TITLE
Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

### ISSUE THREAD

**Issue by CarnivoraCraft** [dmulloy2/ProtocolLib#2871]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:188)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:311)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7a309e0d[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@6bd3c239
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6e9c7d30
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3cde31b3
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2160,minecraftVersion=1.20.4}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@37d7d0bc
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@37d7d0bc
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@7731a3c4
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@3515c369
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    17.0.10
  Server:
    git-Purpur-2160 (MC: 1.20.4)

**Comment by Xytrizareal** [comment]
same issue with mine

**Comment by CoolGo1425** [comment]
same issue here

**Comment by CarnivoraCraft** [comment]
@CoolGo1425 @Xytrizareal resolved after puting dev version from https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Xytriza** [comment]
k
