### ISSUE TITLE
Updater Bug

### ISSUE THREAD

**Issue by mfnalex** [dmulloy2/ProtocolLib#289]
The updater is bugged, because dev.bukkit.org is down, the console is spammed every few seconds with this:
`[22:45:27] [Thread-30/WARN]: [ProtocolLib] The updater could not contact dev.bukkit.org for updating.
[22:45:27] [Thread-30/WARN]: [ProtocolLib] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
[22:45:27] [Thread-30/WARN]: java.io.IOException: Server returned HTTP response code: 522 for URL: https://api.curseforge.com/servermods/files?projectIds=45564
[22:45:27] [Thread-30/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
[22:45:27] [Thread-30/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[22:45:27] [Thread-30/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[22:45:27] [Thread-30/WARN]: 	at com.comphenix.protocol.updater.BukkitUpdater.read(BukkitUpdater.java:332)
[22:45:27] [Thread-30/WARN]: 	at com.comphenix.protocol.updater.BukkitUpdater$UpdateRunnable.run(BukkitUpdater.java:373)
[22:45:27] [Thread-30/WARN]: 	at java.lang.Thread.run(Thread.java:745)`
Latest Paperspigot, latest ProtocolLib

**Comment by dmulloy2** [comment]
Classic BukkitDev. That's interesting though, if you're using spigot or a variant it should check spigotmc.org

**Comment by dmulloy2** [comment]
Regardless, fixed in https://github.com/dmulloy2/ProtocolLib/commit/3ab2026d626353290e3d00b61598e8b121a525c8
