### ISSUE TITLE
ProtocolLib unable to load

### ISSUE THREAD

**Issue by Ranger2415** [dmulloy2/ProtocolLib#2902]
[07:24:34] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
  	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
  	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @cdfac82
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
  	at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
  	... 10 more

**Comment by ShamaIow** [comment]
Update to a recent JDK if someone have this issue, the answer is nowhere to be found since tickets are closed instantly.
