### ISSUE TITLE
ProtocolLib loading error

### ISSUE THREAD

**Issue by Dejf15** [dmulloy2/ProtocolLib#2906]
03:25:37[INFO] [ProtocolLib] Loading ProtocolLib v4.5.1
03:25:37[WARN] [ProtocolLib] Version (MC: 1.20.2) has not yet been tested! Proceed with caution.
03:25:37[ERROR] [ProtocolLib] INTERNAL ERROR: Cannot find listener thread in MinecraftServer.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}],
methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
}}
at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
at com.comphenix.protocol.utility.MinecraftReflection.getNetworkListenThreadClass(MinecraftReflection.java:1576)
at com.comphenix.protocol.injector.player.InjectedServerConnection.initializeListenerField(InjectedServerConnection.java:194)
at com.comphenix.protocol.injector.player.InjectedServerConnection.injectListenerThread(InjectedServerConnection.java:232)
at com.comphenix.protocol.injector.player.InjectedServerConnection.injectList(InjectedServerConnection.java:181)
at com.comphenix.protocol.injector.player.ProxyPlayerInjectionHandler.<init>(ProxyPlayerInjectionHandler.java:150)
at com.comphenix.protocol.injector.player.PlayerInjectorBuilder.buildHandler(PlayerInjectorBuilder.java:139)
at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:253)
at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
at java.base/java.lang.Thread.run(Unknown Source)
Dump:
Parameters:
net.minecraft.server.dedicated.DedicatedServer@5a573c92[
q=[]
r=<null>
t=<null>
u=net.minecraft.server.dedicated.DedicatedServerSettings@24d943f6
v=<null>
w=<null>
h=net.minecraft.world.level.storage.Convertable$ConversionSession@2b6cc984
i=net.minecraft.world.level.storage.WorldNBTStorage@3401a5cf
y=[]
z=net.minecraft.util.profiling.metrics.profiling.InactiveMetricsRecorder@2138e67d
A=net.minecraft.util.profiling.GameProfilerDisabled@1bae1ad4
B=net.minecraft.server.MinecraftServer$$Lambda$5229/0x00007f91189e5b70@5643d0cc
C=net.minecraft.server.MinecraftServer$$Lambda$5230/0x00007f91189e5db0@6fd53816
D=false
E=<null>
F=false
G=net.minecraft.server.network.ServerConnection@938309f
H=net.minecraft.server.Main$$Lambda$5228/0x00007f91189e4de0@622be3d6
I=<null>
J=<null>
K=net.minecraft.world.level.levelgen.LegacyRandomSource@2a268aef
L=com.mojang.datafixers.DataFixerUpper@6cf51235
M=
N=46050
O=net.minecraft.core.LayeredRegistryAccess@24017bfc
P={}
Q=net.minecraft.server.dedicated.DedicatedPlayerList@198909f9
R=true
S=false
T=0
j=DIRECT
U=false
V=false
W=true
X=false
Y=§8§l§m--<§e§l§m-----§r§l §6§lRosty§e§lSMP§r§l §e§l§m-----§8§l§m>--§r
§e⊏§6⚫§e⊐§r §f§lhttps://discord.gg/uchjrgd2Sk§r §e⊏§6⚫§e⊐
Z=0
k={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
aa=java.security.KeyPair@3d200017
ab=<null>
ac=false
ad=false
ae=0
l=Services[sessionService=com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService@7fb19351, servicesKeySet=com.mojang.authlib.yggdrasil.ServicesKeySet$$Lambda$3681/0x00007f91187ce3a0@2b873ccc, profileRepository=com.mojang.authlib.yggdrasil.Yggd
rasilGameProfileRepository@161ab113, profileCache=net.minecraft.server.players.UserCache@44015c31]
af=0
ag=Thread[Server thread,5,main]
ah=1223601630
ai=0
aj=false
ak=net.minecraft.server.packs.repository.ResourcePackRepository@25aa5f80
al=net.minecraft.server.ScoreboardServer@66fbf00f
am=<null>
an=net.minecraft.server.bossevents.BossBattleCustomData@2855c835
ao=net.minecraft.server.CustomFunctionData@54d70f78
ap=false
aq=0.0
ar=java.util.concurrent.ForkJoinPool@23761c3d[Running, parallelism = 3, size = 3, active = 0, running = 0, steals = 93, tasks = 0, submissions = 0]
as=<null>
at=ReloadableResources[resourceManager=net.minecraft.server.packs.resources.ResourceManager@1ab4ebd4, managers=net.minecraft.server.DataPackResources@1c268cd7]
au=net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager@765d53f7
m=net.minecraft.world.level.storage.WorldDataServer@319b0014
av=false
worldLoader=a[resources=net.minecraft.server.packs.resources.ResourceManager@1ab4ebd4, dataConfiguration=WorldDataConfiguration[dataPacks=net.minecraft.world.level.DataPackConfiguration@4687f41f, enabledFeatures=net.minecraft.world.flag.FeatureFlagSe
t@98c4e4d1], datapackWorldgen=net.minecraft.core.IRegistryCustom$a@312383b1, datapackDimensions=net.minecraft.core.IRegistryCustom$a@2dfdac89]
server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Spigot-2888990-d485cde,minecraftVersion=1.20.2}
options=joptsimple.OptionSet@3a6c239b
console=org.bukkit.craftbukkit.v1_20_R2.command.ColouredConsoleSender@27781a54
reader=jline.console.ConsoleReader@3d51b110
processQueue=[]
autosavePeriod=6000
vanillaCommandDispatcher=net.minecraft.commands.CommandDispatcher@501bfc65
forceTicks=false
recentTps={0.0,0.0,0.0}
hasStopped=false
stopLock=java.lang.Object@58d10a50
chatExecutor=java.util.concurrent.ThreadPoolExecutor@5c8fd8c9[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
b=0
b=Server
d=[]
e=0
]
Sender:
com.comphenix.protocol.injector.player.InjectedServerConnection@2c477f77[
listFields=[]
replacedLists=[]
netLoginInjector=com.comphenix.protocol.injector.player.NetLoginInjector@e2cb3a6
socketInjector=com.comphenix.protocol.injector.server.InputStreamReflectLookup@1a3f923d
socketType=LISTENER_THREAD
server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Spigot-2888990-d485cde,minecraftVersion=1.20.2}
reporter=com.comphenix.protocol.ProtocolLib$1@52162e43
hasAttempted=true
hasSuccess=false
minecraftServer=net.minecraft.server.dedicated.DedicatedServer@5a573c92
]
Version:
ProtocolLib v4.5.1
Java Version:
17.0.10
Server:
3950-Spigot-2888990-d485cde (MC: 1.20.2)
03:25:37[ERROR] [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
FieldAccessException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}],
methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
}}. Workaround failed too.
at com.comphenix.protocol.injector.packet.ProxyPacketInjector.initialize(ProxyPacketInjector.java:191)
at com.comphenix.protocol.injector.packet.ProxyPacketInjector.<init>(ProxyPacketInjector.java:164)
at com.comphenix.protocol.injector.packet.PacketInjectorBuilder.buildInjector(PacketInjectorBuilder.java:94)
at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:259)
at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.player.EntityHuman}],
methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.player.EntityHuman instanceof input, Index: 2}], paramCount=3}]
}}
at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460)
at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1065)
at com.comphenix.protocol.utility.MinecraftReflection.getPacketClass(MinecraftReflection.java:729)
at com.comphenix.protocol.injector.packet.ProxyPacketInjector$ArrayLookup.initialize(ProxyPacketInjector.java:115)
at com.comphenix.protocol.injector.packet.ProxyPacketInjector$ArrayLookup.<init>(ProxyPacketInjector.java:106)
at com.comphenix.protocol.injector.packet.ProxyPacketInjector.initialize(ProxyPacketInjector.java:188)
... 11 more
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@5283483f[
statistics=<null>
backgroundCompiler=<null>
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@545d70a6
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@11417810
redirectHandler=<null>
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=org.bukkit.plugin.java.JavaPluginLoader@2d7b57da
server=CraftServer{serverName=CraftBukkit,serverVersion=3950-Spigot-2888990-d485cde,minecraftVersion=1.20.2}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@74f8a7e2
dataFolder=plugins/ProtocolLib
classLoader=org.bukkit.plugin.java.PluginClassLoader@5d53c373
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=org.bukkit.plugin.PluginLogger@51045100
]
Version:
ProtocolLib v4.5.1
Java Version:
17.0.10
Server:
3950-Spigot-2888990-d485cde (MC: 1.20.2)

**Comment by Jeppa** [comment]
v4.5.1 ? realy?

**Comment by Dejf15** [comment]
> v4.5.1 ? realy?

wdym?

**Comment by Jeppa** [comment]
You should update ProtocolLib..
