### ISSUE TITLE
null initializing ProtocolLib v3.7.0 (Is it up to date?)

### ISSUE THREAD

**Issue by Eufranio** [dmulloy2/ProtocolLib#292]
When the plugin is starting, it throws this exception:
```
[22:43:54] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_7_R4.CraftServer/]: null initializing ProtocolLib v3.7.0 (Is it up to date?)
java.lang.NullPointerException
	at com.comphenix.protocol.ProtocolConfig.isDebug(ProtocolConfig.java:253) ~[?:?]
	at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:185) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:348) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]
```

Make sure you've done the following:
- [X] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues

I'm using Thermos 1514 B58 and ProtocolLib v3.7.0.

Description and relevant errors:

**Comment by dmulloy2** [comment]
Sorry, but 1.7.10 is no longer supported. At this point either 3.7.0 works or it doesn't.
