### ISSUE TITLE
Random EncoderException

### ISSUE THREAD

**Issue by SlimeDog** [dmulloy2/ProtocolLib#2923]
- [x] This issue is not solved in a development build

**Describe the bug**
EncoderException (see stack trace below)

**To Reproduce**
1. Start server
2. Read console/log

**Expected behavior**
Clean running

**Screenshots**
```
[15:04:23 ERROR]: Error sending packet clientbound/minecraft:disconnect (skippable? false)
io.netty.handler.codec.EncoderException: Sending unknown packet 'clientbound/minecraft:disconnect'
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:46) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.20.6.jar:git-Paper-61]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:749) ~[paper-1.20.6.jar:git-Paper-61]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.lambda$writeAndFlush$1(NettyChannelProxy.java:223) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.lambda$processPacketOutbound$2(NettyChannelProxy.java:266) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.processPacketOutbound(NettyChannelProxy.java:268) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:223) ~[ProtocolLib-5.2.1-b689.jar:?]
        at ProtocolLib-5.2.1-b689.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-5.2.1-b689.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:504) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.Connection.sendPacket(Connection.java:486) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.Connection.send(Connection.java:448) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.Connection.send(Connection.java:434) ~[paper-1.20.6.jar:git-Paper-61]
        at net.minecraft.network.Connection.exceptionCaught(Connection.java:220) ~[paper-1.20.6.jar:git-Paper-61]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:826) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**Version Info**
```
ProtocolLib Dump
Timestamp: 05/10/24 15:08:52

ProtocolLib Version: ProtocolLib v5.2.1-SNAPSHOT-689
Bukkit Version: 1.20.6-R0.1-SNAPSHOT
Server Version: git-Paper-61 (MC: 1.20.6)
Java Version: 22.0.1

ProtocolLib: com.comphenix.protocol.ProtocolLib@4dcd4d4f[
  statistics=<null>
  packetTask=com.comphenix.protocol.scheduler.DefaultTask@548f0475
  tickCounter=187837
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@3e95751c
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@1f6edf8e
  scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@30121750
  commandProtocol=com.comphenix.protocol.CommandProtocol@902778a
  commandPacket=com.comphenix.protocol.CommandPacket@1c2ace23
  commandFilter=com.comphenix.protocol.CommandFilter@7551e087
  packetLogging=com.comphenix.protocol.PacketLogging@55d9d1ea
  skipDisable=false
  isEnabled=true
  loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4ffd42fc
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-61,minecraftVersion=1.20.6}
  file=plugins/.paper-remapped/ProtocolLib-5.2.1-b689.jar
  description=org.bukkit.plugin.PluginDescriptionFile@44cba347
  pluginMeta=org.bukkit.plugin.PluginDescriptionFile@44cba347
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.1-SNAPSHOT-689, pluginEnabled=true, url=plugins/.paper-remapped/ProtocolLib-5.2.1-b689.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@22c5f749
  lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@3879baf9
  allowsLifecycleRegistration=false
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@21b1e72a[
  plugin=ProtocolLib v5.2.1-SNAPSHOT-689
  server=CraftServer{serverName=Paper,serverVersion=git-Paper-61,minecraftVersion=1.20.6}
  reporter=com.comphenix.protocol.ProtocolLib$1@596472d3
  minecraftVersion=(MC: 1.20.6)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5496b909
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@214d7f10
  inboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@feb54a4
  outboundListeners=com.comphenix.protocol.injector.SortedPacketListenerList@75635d60
  registeredListeners=[PacketAdapter[plugin=GraveEntitySpawn, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=ClientboundAddEn
tityPacket, id=1]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIG
HEST, packets=[ENTITY_METADATA[class=ClientboundSetEntityDataPacket, id=88]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapte
r[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[REL_ENTITY_MOVE_LOOK[class=PosRot, id=47], ENTITY_HEAD_ROTATION[class=Clientb
oundRotateHeadPacket, id=72], ENTITY_LOOK[class=Rot, id=48], ENTITY_TELEPORT[class=ClientboundTeleportEntityPacket, id=112]], gamephase=PLAYING, optio
ns=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=Client
boundPlayerInfoUpdatePacket, id=62]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ItemJoin, sending=EMPTY_WH
ITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[CLOSE_WINDOW[class=ServerboundContainerClosePacket, id=15], PICK_ITEM[class=Serverboun
dPickItemPacket, id=32], AUTO_RECIPE[class=ServerboundPlaceRecipePacket, id=34]], gamephase=PLAYING, options=[]]]]
  packetInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerPacketInjector@145cec34
  playerInjectionHandler=com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector@5e23b450
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@bb88544
  debug=false
  closed=false
  injected=true
]

Listeners:
ges.hooks.SimpleProtocolLibHook@7a8498e0[
  plugin=GraveEntitySpawn v1.15
  protocolManager=com.comphenix.protocol.injector.PacketFilterManager@21b1e72a
  toCheck=[]
  plugin=GraveEntitySpawn v1.15
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=ClientboundAddEntityPacket, id=1]], gamephase=PLAYING, options=[]]
]
net.citizensnpcs.ProtocolLibListener$1@34505a66[
  plugin=Citizens v2.0.34-SNAPSHOT (build 3416)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=ClientboundSetEntityDataPacket, id=88]], gamephase=PLAYING, opt
ions=[]]
]
net.citizensnpcs.ProtocolLibListener$3@1cb9b59e[
  plugin=Citizens v2.0.34-SNAPSHOT (build 3416)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[REL_ENTITY_MOVE_LOOK[class=PosRot, id=47], ENTITY_HEAD_ROTATION[class=ClientboundRota
teHeadPacket, id=72], ENTITY_LOOK[class=Rot, id=48], ENTITY_TELEPORT[class=ClientboundTeleportEntityPacket, id=112]], gamephase=PLAYING, options=[ASYN
C]]
]
net.citizensnpcs.ProtocolLibListener$2@44e047db[
  plugin=Citizens v2.0.34-SNAPSHOT (build 3416)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=62]], gamephase=PLAYING, opti
ons=[ASYNC]]
]
me.RockinChaos.itemjoin.core.utils.api.ProtocolAPI$1@2c23832e[
  plugin=ItemJoin v6.0.6-SNAPSHOT-b982
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[CLOSE_WINDOW[class=ServerboundContainerClosePacket, id=15], PICK_ITEM[class=Serverbo
undPickItemPacket, id=32], AUTO_RECIPE[class=ServerboundPlaceRecipePacket, id=34]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]

Plugins Using ProtocolLib:
GraveEntitySpawn by []
Citizens by [fullwall]
ItemJoin by [RockinChaos]
```

**Additional context**
No players connected since start-up (it's a test server).

**Comment by SlimeDog** [comment]
Seems to be resolved in later (ProtocolLib 5.3) releases.
