### ISSUE TITLE
Is it updated

### ISSUE THREAD

**Issue by TechTaco98** [dmulloy2/ProtocolLib#2924]
My server isn't loading protocol lib and I know I'm using the latest build of the plugin, but I've realized that it probably doesn't work on 1.20.6. Would that be the case? I am clueless and new to this

**Comment by TechTaco98** [comment]
tis is my server log
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
12.05 03:26:29 [Server] [INFO] at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
12.05 03:26:29 [Server] [INFO] at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
12.05 03:26:29 [Server] [INFO] at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
12.05 03:26:29 [Server] [INFO] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
12.05 03:26:29 [Server] [INFO] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
12.05 03:26:29 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:508)
12.05 03:26:29 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:287)
12.05 03:26:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1140)
12.05 03:26:29 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
12.05 03:26:29 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:1583)
12.05 03:26:29 [Server] [INFO] Dump:
12.05 03:26:29 [Server] [INFO] Parameters: 
12.05 03:26:29 [Server] [INFO] [NULL]
12.05 03:26:29 [Server] [INFO] Sender:
12.05 03:26:30 [Server] [INFO] com.comphenix.protocol.ProtocolLib@3549852c[
12.05 03:26:30 [Server] [INFO] statistics=<null>
12.05 03:26:30 [Server] [INFO] packetTask=<null>
12.05 03:26:30 [Server] [INFO] tickCounter=0
12.05 03:26:30 [Server] [INFO] configExpectedMod=-1
12.05 03:26:30 [Server] [INFO] updater=com.comphenix.protocol.updater.SpigotUpdater@3d9a8f8f
12.05 03:26:30 [Server] [INFO] redirectHandler=<null>
12.05 03:26:30 [Server] [INFO] scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@44831df5
12.05 03:26:30 [Server] [INFO] commandProtocol=<null>
12.05 03:26:30 [Server] [INFO] commandPacket=<null>
12.05 03:26:30 [Server] [INFO] commandFilter=<null>
12.05 03:26:30 [Server] [INFO] packetLogging=<null>
12.05 03:26:30 [Server] [INFO] skipDisable=false
12.05 03:26:30 [Server] [INFO] isEnabled=false
12.05 03:26:30 [Server] [INFO] loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@66402b6
12.05 03:26:30 [Server] [INFO] server=CraftServer{serverName=Paper,serverVersion=git-Paper-"812ccb9",minecraftVersion=1.20.6}
12.05 03:26:30 [Server] [INFO] file=plugins/ProtocolLib.jar
12.05 03:26:30 [Server] [INFO] description=org.bukkit.plugin.PluginDescriptionFile@17cb2a15
12.05 03:26:30 [Server] [INFO] pluginMeta=org.bukkit.plugin.PluginDescriptionFile@17cb2a15
12.05 03:26:30 [Server] [INFO] dataFolder=plugins/ProtocolLib
12.05 03:26:30 [Server] [INFO] classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/ProtocolLib.jar}
12.05 03:26:30 [Server] [INFO] naggable=true
12.05 03:26:30 [Server] [INFO] newConfig=YamlConfiguration[path='', root='YamlConfiguration']
12.05 03:26:30 [Server] [INFO] configFile=plugins/ProtocolLib/config.yml
12.05 03:26:30 [Server] [INFO] logger=com.destroystokyo.paper.utils.PaperPluginLogger@3a32ada9
12.05 03:26:30 [Server] [INFO] lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@4a3d0019
12.05 03:26:30 [Server] [INFO] allowsLifecycleRegistration=true
12.05 03:26:30 [Server] [INFO] ]
12.05 03:26:30 [Server] [INFO] Version:
12.05 03:26:30 [Server] [INFO] ProtocolLib v5.2.0-SNAPSHOT-679
12.05 03:26:30 [Server] [INFO] Java Version:
12.05 03:26:30 [Server] Startup21.0.2

**Comment by Jeppa** [comment]
You're not on latest dev build! 
But, even the latest DEV is not working under 1.20.6 without errors and issues...

**Comment by frqnny** [comment]
Yes, I also get a similar error on 1.20.6
`[01:28:28 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[01:28:28 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[01:28:29 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[01:28:29 WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
[01:28:32 ERROR]: [ProtocolLib] Assuming package version: v1_20_R1
[01:28:32 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:529)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@31b9d714[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@24e2a585
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@5b1cd77a
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@5d1e1be1
      server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-2203,minecraftVersion=1.20.6}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@16f03a16
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@16f03a16
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@258fa802
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@484f70cb
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    git-Purpur-2203 (MC: 1.20.6)`

**Comment by Jeppa** [comment]
You also didn't update to latest dev build!

**Comment by frqnny** [comment]
? It literally says
    ProtocolLib v5.2.0-SNAPSHOT-679
Maybe they could also put build numbers on the jars so I know which is the latest? But I got it off the jenkins, so.

**Comment by Jeppa** [comment]
> ? It literally says ProtocolLib v5.2.0-SNAPSHOT-679 Maybe they could also put build numbers on the jars so I know which is the latest? But I got it off the jenkins, so.

679 is something like five month old ...
latest is 689 (Jenkins)

**Comment by TechTaco98** [comment]
> > ? It literally says ProtocolLib v5.2.0-SNAPSHOT-679 Maybe they could also put build numbers on the jars so I know which is the latest? But I got it off the jenkins, so.
> 
> 679 is something like five month old ... latest is 689 (Jenkins)

Where would I find the new Jenkins build?

**Comment by Jeppa** [comment]
> Where would I find the new Jenkins build?

Where did you find the old jenkins build? Location has not changed...

**Comment by ineanto** [comment]
> > > ? It literally says ProtocolLib v5.2.0-SNAPSHOT-679 Maybe they could also put build numbers on the jars so I know which is the latest? But I got it off the jenkins, so.
> > 
> > 
> > 679 is something like five month old ... latest is 689 (Jenkins)
> 
> Where would I find the new Jenkins build?

You can find the latest Jenkins build [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar).
