### ISSUE TITLE
Devbuild 689 Error | Paper 1.20.6

### ISSUE THREAD

**Issue by drabspirit** [dmulloy2/ProtocolLib#2925]
**Describe the bug**
Running within a docker container, don't think its the cause but rather just the dev build. Saw some other reports saying they're having no issues with this devbuild.  
Log of ProtocolLib error
```
[01:45:50 WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
2024-05-13 01:45:55 >....
[01:45:55 ERROR]: [ProtocolLib] Assuming package version: v1_20_R1
2024-05-13 01:45:55 >....
[01:45:55 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
2024-05-13 01:45:55   If this problem hasn't already been reported, please open a ticket
2024-05-13 01:45:55   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
2024-05-13 01:45:55   Stack Trace:
2024-05-13 01:45:55   java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
2024-05-13 01:45:55     at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
2024-05-13 01:45:55     at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
2024-05-13 01:45:55     at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
2024-05-13 01:45:55     at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
2024-05-13 01:45:55     at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
2024-05-13 01:45:55     at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:515)
2024-05-13 01:45:55     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
2024-05-13 01:45:55     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142)
2024-05-13 01:45:55     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
2024-05-13 01:45:55     at java.base/java.lang.Thread.run(Unknown Source)
2024-05-13 01:45:55   Dump:
2024-05-13 01:45:55   Parameters: 
2024-05-13 01:45:55     [NULL]
2024-05-13 01:45:55   Sender:
2024-05-13 01:45:55     com.comphenix.protocol.ProtocolLib@5e1188d[
2024-05-13 01:45:55       statistics=<null>
2024-05-13 01:45:55       packetTask=<null>
2024-05-13 01:45:55       tickCounter=0
2024-05-13 01:45:55       configExpectedMod=-1
2024-05-13 01:45:55       updater=com.comphenix.protocol.updater.SpigotUpdater@3e7ce41
2024-05-13 01:45:55       redirectHandler=<null>
2024-05-13 01:45:55       scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@ecf8bc0
2024-05-13 01:45:55       commandProtocol=<null>
2024-05-13 01:45:55       commandPacket=<null>
2024-05-13 01:45:55       commandFilter=<null>
2024-05-13 01:45:55       packetLogging=<null>
2024-05-13 01:45:55       skipDisable=false
2024-05-13 01:45:55       isEnabled=false
2024-05-13 01:45:55       loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@29031f4d
2024-05-13 01:45:55       server=CraftServer{serverName=Paper,serverVersion=git-Paper-72,minecraftVersion=1.20.6}
2024-05-13 01:45:55       file=plugins/.paper-remapped/ProtocolLib.jar
2024-05-13 01:45:55       description=org.bukkit.plugin.PluginDescriptionFile@56f4f93d
2024-05-13 01:45:55       pluginMeta=org.bukkit.plugin.PluginDescriptionFile@56f4f93d
2024-05-13 01:45:55       dataFolder=plugins/ProtocolLib
2024-05-13 01:45:55       classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
2024-05-13 01:45:55       naggable=true
2024-05-13 01:45:55       newConfig=YamlConfiguration[path='', root='YamlConfiguration']
2024-05-13 01:45:55       configFile=plugins/ProtocolLib/config.yml
2024-05-13 01:45:55       logger=com.destroystokyo.paper.utils.PaperPluginLogger@26822fa0
2024-05-13 01:45:55       lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@5ccceb96
2024-05-13 01:45:55       allowsLifecycleRegistration=true
2024-05-13 01:45:55     ]
2024-05-13 01:45:55   Version:
2024-05-13 01:45:55     ProtocolLib v5.2.0-SNAPSHOT-679
2024-05-13 01:45:55   Java Version:
2024-05-13 01:45:55     21.0.3
2024-05-13 01:45:55   Server:
2024-05-13 01:45:55     git-Paper-72 (MC: 1.20.6)
2024-05-13 01:45:55 
2024-05-13 01:45:55 >....
```
full log: https://pastebin.com/r4X42d8F

**Comment by svesnav** [comment]
I have the same error

**Comment by Jeppa** [comment]
1st: title says : Devbuild 686
2nd: log says : ProtocolLib v5.2.0-SNAPSHOT-679
3rd: latest build since one week is 689 !!

Did you try latest build?

**Comment by drabspirit** [comment]
> 1st: title says : Devbuild 686 2nd: log says : ProtocolLib v5.2.0-SNAPSHOT-679 3rd: latest build since one week is 689 !!
> 
> Did you try latest build?

Super sorry! I made this report at 2am last night and mistyped version on title. 

https://ci.dmulloy2.net/job/ProtocolLib/689/artifact/build/libs/ProtocolLib.jar is the link my container is using :pray:

**Comment by Jeppa** [comment]
Yes, that link is build 689, but your error-log was with build 679 .
Please test with 589 again...
