### ISSUE TITLE
1.8.8 error plugin

### ISSUE THREAD

**Issue by AdrianoGSM** [dmulloy2/ProtocolLib#2949]
in version 1.8.8, I cannot use a version newer than 5.0.0, even with this version, using another plugin called viaversion, can I support versions above 1.19, such as 1.20, with this version of protocollib?

net.minecraft.server.v1_8_R3.ReportedException: Sending packet
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:949) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:791) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.Container.addSlotListener(Container.java:59) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityPlayer.syncInventory(EntityPlayer.java:177) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:189) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:150) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:60) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:461) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:183) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1017) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
        at net.minecraft.server.v1_8_R3.NetworkManager.writePacket(NetworkManager.java:399) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:314) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.NetworkManager.dispatchPacket(NetworkManager.java:311) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:287) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:270) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:935) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        ... 14 more

**Comment by DevNatan** [comment]
@AdrianoGSM I had this problem with ProtocolLib v5.2.0 + ViaVersion v4.9.3/4.10.0. I was able to run it using ProtocolLib v5.1.0 and ViaVersion v4.10.2. Also, after running the server for a while after these errors ^ it suddenly crashes.

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 24/05/2024 18:39
Description: Sending packet

java.lang.NullPointerException: type cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138)
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126)
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96)
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553)

-- Packet being sent --
Details:
	Packet class: net.minecraft.server.v1_8_R3.PacketPlayOutEntityTeleport
Stacktrace:
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:935)
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:194)
	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177)
```

**Comment by AdrianoGSM** [comment]
I can use protocollib 5.0.0 normally, without these errors, but it says it only supports up to 1.19, as I'm going to use viaversion to support up to 1.20, I need to know if this version of protocollib will give me a headache
