### ISSUE TITLE
ProtocolLib INTERNAL ERROR when enabling

### ISSUE THREAD

**Issue by Alexidians** [dmulloy2/ProtocolLib#2950]
- [x] This issue is not solved in a development build

**Describe the bug**
the protocolLib plugin dosent start due to an internal error:
[12:01:51] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:436)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7dd7735a[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@56f08021
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@10fb6406
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@23f0c034
      server=CraftServer{serverName=CraftBukkit,serverVersion=4172-Spigot-342f493-a437019,minecraftVersion=1.20.6}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6a6847f0
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@72153ef9
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@b0c45d8
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    4172-Spigot-342f493-a437019 (MC: 1.20.6)
    
    and warning before
    [12:01:49] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.

**To Reproduce**
1. Create a server on aternos
2. Set it to spigot
3. install the protocollib plugin
4. Start your server
5.wait for it to start
6.see the error that it wouldnt start

**Expected behavior**
The plugin would start and the other plugins using it as a dependancy would work.

**Screenshots**
none

**Version Info**
the plugin wont even start. so i cant even run the command ona  disabled plugin

**Additional context**
my server is running MC Spigot 1.20.6

**Comment by EuSouVoce** [comment]
you are **not** in the latest build

**Comment by Andrew4759** [comment]
i have the same issue but my server is running paper 1.20.6

**Comment by MarkGG8181** [comment]
same issue here, running paper 1.20.6-112-master@347bbe3 with these plugins: BetterTeams, GrimAC, ProtocolLib, PvPManager, voicechat

**Comment by KenterWasTaken** [comment]
Guys, please help with my issue! It's been 4 days! It's called "holograms messed up", and it's caused by ProtocolLib

**Comment by Jeppa** [comment]
like @EuSouVoce already mentioned: you are not using latest build... #679 is **NOT** the latest build!
And this was already mentioned here #2944 and here #2938 

And @KenterWasTaken : please stay on topic.. you've already opened an issue... this issue here has nothing to do with yours...

**Comment by KenterWasTaken** [comment]
@Jeppa nothing to do with mine? That's exactly the same problem I have??

**Comment by KenterWasTaken** [comment]
@Jeppa yea, but no one is answering my issue while I made it way before this one for example, yet it did r get a single reply!

**Comment by Janmm14** [comment]
@KenterWasTaken free software does not provide support guarantees.

**Comment by KenterWasTaken** [comment]
@Janmm14 this is long since fixed btw
