### ISSUE TITLE
Login and Logout errors

### ISSUE THREAD

**Issue by enigma072485** [dmulloy2/ProtocolLib#2953]
- [X ] This issue is not solved in a development build

**Describe the bug**
During login and logout from the server, I'm getting errors. Also sometimes when a user logs in they are getting disconnected, I wasn't sure it was ProtocolLib, but I started getting errors upon logout as well that specifically mention ProtocolLib. Since the login errors mention protocols and netty. I thought I would also mention it here to see if they are related. It's beyond my scope, if it's unrelated to ProtocolLib, hopefully you will be able to point me in the right direction. Thank you for your time and your assistance.
I know it mentions, Antipopup. I also reached out to them to see if it's their plugin messing up Protocollib, or the other way around. Just to cover my bases. 

`Console16:51:10
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.lambda$writeAndFlush$1(NettyChannelProxy.java:223) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.lambda$processPacketOutbound$2(NettyChannelProxy.java:266) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.processPacketOutbound(NettyChannelProxy.java:268) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:223) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
at net.minecraft.network.Connection.doSendPacket(Connection.java:504) ~[purpur-1.20.6.jar:1.20.6-2217-2842b97]
at net.minecraft.network.Connection.sendPacket(Connection.java:486) ~[purpur-1.20.6.jar:1.20.6-2217-2842b97]
at net.minecraft.network.Connection.send(Connection.java:448) ~[purpur-1.20.6.jar:1.20.6-2217-2842b97]
at net.minecraft.network.Connection.send(Connection.java:434) ~[purpur-1.20.6.jar:1.20.6-2217-2842b97]
at net.minecraft.network.Connection.exceptionCaught(Connection.java:220) ~[purpur-1.20.6.jar:1.20.6-2217-2842b97]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at AntiPopup-8.1.jar/com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.exceptionCaught(PacketEventsEncoder.java:128) ~[AntiPopup-8.1.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at AntiPopup-8.1.jar/com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsDecoder.exceptionCaught(PacketEventsDecoder.java:69) ~[AntiPopup-8.1.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:826) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

The second error only shows when a user tries to login... they have to try 2-3 times before it lets them in. Any thoughts are appreciated if it's not related to ProtocolLib.
`14:55:04
UUID of player USER is UUID
14:55:05
com.mojang.authlib.GameProfile@25764f73[id=UUID,name=USER,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcxNjgzOTUwNjYwNCwKICAicHJvZmlsZUlkIiA6ICI3YTJjZGVlNGNiMTE0OWI3OGNjNzI0ZDE0ZDg3MjIzOSIsCiAgInByb2ZpbGVOYW1lIiA6ICJSZWFwZXJSb3NlMTIwMCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MzJmNjQ0MWYzMmY2OGM2MjQyNmE5N2EzOTdkODFiZWE3MjA3OGM1ZTliMWUyOGZiODhiMzY5YjYzNGIwYWY3IgogICAgfQogIH0KfQ==, signature=yG2+BQELDsAQsD5eP7WgvElJytbq1hrPodc4VUYx0VboFYRkFlv4FRUDqHenfuhslKiX+kRP2CfQIjqaTgEEIBqOPZ7RoNFHeaGnxzoWjGc9dKJ1b6koHHImbbQZ/Zw+YXHWuHH9yko+3XOMSud8J5OpeTbNU9/uFgBbZCrSVQ7IpcaK/pwJNgwxCvTNk1aga+Dw36wEjzaPDBETA+NzEseuOv16AimRwkVgIJDuvOEam7BRVh1STm4KlfhD/TrwghpwtiCzuIak1LoeCg9vy3UQBz6oAlsGIZ7jehqODoqKGPuMSxGrHn8c8yoyeLe6cy6ohj5y1IU9raEbsIMTRtLbILb94tKwvLpaNIMwAZQU5L154xMHMKjhiUXdxVYwOH9thfdXBYfHFmfLA86spZaZ03BdDXyKGPzvJqTlUIM3+tZOYM6ROJoN+5Nzzs5SCBAtinGV5zGJt6MxQ/h7ze6oAKo5NrJl0v/+jawBR3UbvYMxt359+6Y5BzG8FrZeMIINtZHCYT+lh1FEQYfI7EFNBDQwtfaUkFCj55uopN6rdwaJ9AxbYAOgK4cN6ntTZgll9VIM3yJd6Y0a0mIIL8SO9vddHIMmh+1iq2k/5RRluJAyL6AyxNOQusLNy3q9CwJap+6Q5mPpzftYp6um8XquQiF0e/9k0fzlvw8ut5k=]]}]: lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Pipeline has no outbound protocol configured, can't process packet net.minecraft.network.protocol.common.ClientboundKeepAlivePacket@7e5de046`

**To Reproduce**
Happens randomly, but seems to be isolated to Logins and Logouts.

**Expected behavior**
No console errors?

**Screenshots**

**Version Info**
Purpur Version: 1.20.6-2217-2842b97 (MC: 1.20.6)*
ProtocolLib Version: ProtocolLib v5.2.1-SNAPSHOT-689
https://pastebin.com/wUdgdJ7u

**Additional context**

**Comment by supertakeru** [comment]
Also getting a similar issue.
https://pastebin.com/LgkSeanS
