### ISSUE TITLE
Error initializing plugin on 1.20.6 (on ProtocolLib ProtocolLib snapshot)

### ISSUE THREAD

**Issue by HydrolienF** [dmulloy2/ProtocolLib#2955]
- [x] This issue is not solved in a development build

**Describe the bug**
Plugin fail to load at startup of the server.

**To Reproduce**
1. Download paper-1.20.6-115.jar
2. Build ProtocolLib (b0c4b7fe45024e59505ed132d2df9d61fd5f405d)
3. Add ProtocolLib-5.2.1-SNAPSHOT.jar to the server plugins.
4. Launch server
5. See the error on plugin load.

**Expected behavior**
Plugin should load with succes.

**Version Info**
`/protocol dump` don't work. But I have Java 21, the 1st stable 1.20.6 version of paper and the last build for ProtocolLib.

**Comment by HydrolienF** [comment]
The stack trace
```java
[19:52:26 ERROR]: [ProtocolLib] Error initializing plugin 'ProtocolLib-5.2.1-SNAPSHOT.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/scaffold/subclass/ConstructorStrategy
        at ProtocolLib-5.2.1-SNAPSHOT.jar/com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:129) ~[ProtocolLib-5.2.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.scaffold.subclass.ConstructorStrategy
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more
```

**Comment by McJones9631** [comment]
Did not want to open another ticket for roughly the same issue, but here is my stack trace as well,   

Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.20.6-124-0fcf3e3 (MC: 1.20.6)


` Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@34be4d6c[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@335b84f8
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@75486ad2
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@a80f09d
      server=CraftServer{serverName=Paper,serverVersion=1.20.6-124-0fcf3e3,minecraftVersion=1.20.6}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7c8e9743
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7c8e9743
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@27c7934d
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@45460e46
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.20.6-124-0fcf3e3 (MC: 1.20.6)
`

**Comment by Jeppa** [comment]
@McJones9631 ProtocolLib v5.2.0-SNAPSHOT-679 is not the latest dev build...

**Comment by EuSouVoce** [comment]
As @Jeppa said, not in the latest, obtain it [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by 0utplay** [comment]
@HydrolienF it looks like you are not using the correct build task. You have to use `gradlew shadowJar`. This should give you a bigger jar that should work.

**Comment by HydrolienF** [comment]
@0utplay Ok thanks I will try and let you know.
