### ISSUE TITLE
ProtocolLib disables itself upon startup in 1.20.6

### ISSUE THREAD

**Issue by BuggyAl** [dmulloy2/ProtocolLib#2956]
- [X] This issue is not solved in a development build

**Describe the bug**
The latest ProtocolLib dev build (689) disables itself upon startup in 1.20.6
```
[18:13:14 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Detected a newer version of ProtocolLib (689.0.0) in plugin folder than the current (5.2.1-SNAPSHOT). Disabling.
        at ProtocolLib-689.jar//com.comphenix.protocol.ProtocolLib.checkConflictingVersions(ProtocolLib.java:460)
        at ProtocolLib-689.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:169)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)       
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@4ee35f3d[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=<null>
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@501aceb5
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=true
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4b31ec39
      server=CraftServer{serverName=Paper,serverVersion=1.20.6-115-9d6f2cc,minecraftVersion=1.20.6}
      file=plugins\.paper-remapped\ProtocolLib-689.jar
      description=org.bukkit.plugin.PluginDescriptionFile@18a19eb6
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@18a19eb6
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.1-SNAPSHOT-689, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib-689.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@61b4064f
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@deae461
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.1-SNAPSHOT-689
  Java Version:
    21.0.3
  Server:
    1.20.6-115-9d6f2cc (MC: 1.20.6)
```

**To Reproduce**
1. Install ProtocolLib dev build 689 and run the server
2. Observe error in console

**Expected behavior**
ProtocolLib launches with no errors in console.

**Version Info**
Command unavailable due to plugin being disabled
- Paper version 1.20.6-115-master@9d6f2cc (2024-05-28T14:55:16Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
- ProtocolLib 689 as found [here](https://ci.dmulloy2.net/job/ProtocolLib/689/).

**Comment by TwoPointInfinity** [comment]
following.

**Comment by EuSouVoce** [comment]
multiple jars in the folder, delete all and rename the file to just "ProtocolLib.jar"

**Comment by zazaserty** [comment]
I have the same issue on my server. And no, I do not have multiple jars. This is a direct incompatibility of the plugin with v1.20.6.

**Comment by BuggyAl** [comment]
The issue was solved for me by renaming the file, no extra jars were in the folder. I had previously renamed it to keep track of the version of the file.
