### ISSUE TITLE
Getting an issue on protocolLib it asked me to log it here soo...

### ISSUE THREAD

**Issue by ozimonnn** [dmulloy2/ProtocolLib#2957]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@40764130[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@a97788
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7224c96c
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1a0e0485
      server=CraftServer{serverName=Paper,serverVersion=1.20.6-124-0fcf3e3,minecraftVersion=1.20.6}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@208c02ff
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@208c02ff
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@2e9f49e4
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@65402641
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.20.6-124-0fcf3e3 (MC: 1.20.6)
this is what it asked to send here

**Comment by ozimonnn** [comment]
im not sure whats happening
but my server is a spigot 1.20.6

**Comment by EuSouVoce** [comment]
Not in the latest dev build, obtain the latest [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Comment by KenterWasTaken** [comment]
@Jeppa wth I've been waiting for days for you to answer me, no word! Literally, wth!

**Comment by Jeppa** [comment]
@KenterWasTaken Again: stay on topic... THIS is NOT the issue you have opened! It's #2948
Why do you answer in here? 

And you seem to be very unfriendly and cheeky!
I am not obliged to answer you!
If I answer you here, that's in my free time!

This plugin is not my project, I just gave you a few tips and tried to help....
And since this is a free plugin, noone is obliged to help you or solve your problems!

You have to be a little more patient, maybe someone can help you or fix the bug ...

**Comment by KenterWasTaken** [comment]
@Jeppa free time? Respectfully, I feel like it's weird that people say that "it's my free time" when it literally takes a second to answer someone. No, you are not obligated to help, but once you start helping, I am counting on you to help me, and what do you do? You just leave me hanging and go answer other questions, all you needed to say was "I don't know how to fix it then, sorry" and done! Not that hard!

**Comment by ozimonnn** [comment]
heya thanks a lot for the quick response but I downloaded the first version available on aternos...so it might need  to be updated on aternos?

**Comment by Jeppa** [comment]
Use the link that @EuSouVoce posted and get the latest dev build from there.

**Comment by ozimonnn** [comment]
will the dev build #694 worK?

**Comment by Jeppa** [comment]
Depents on what you are doing with it.
It's the next step, but still has issues with packet creation...

**Comment by ozimonnn** [comment]
my only requirement is to run orebfuscator thats all

**Comment by ozimonnn** [comment]
orebfuscator informed me that protocillib was a dependency thats why I installed it lol
