### ISSUE TITLE
Error when using the WrappedDataWatcher in 1.20.6 with ProtocolLib 5.2.1-SNAPSHOT-696

### ISSUE THREAD

**Issue by Muffin2Go** [dmulloy2/ProtocolLib#2964]
- [X] This issue is not solved in a development build

**Describe the bug**
I'm using the WrappedDataWatcher in my plugin to manipulate Packets, in the newest version it crashes on enable when i create a instance of the WrappedDataWatcher.

**To Reproduce**
1. Implement ProtocolLib to plugin
2. create WrappedDataWatcher
3. load plugin on server (papermc 1.20.6)
4. get error shown below

**Expected behavior**
It should just create the DataWrapper without throwing an error!

**Screenshots**
```
java.lang.NullPointerException: constructor
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:921) ~[guava-32.1.2-jre.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.MethodHandleHelper.getConstructorAccessor(MethodHandleHelper.java:70) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:167) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.Accessors.getConstructorAccessor(Accessors.java:145) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.WrappedDataWatcher.newHandle(WrappedDataWatcher.java:118) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:82) ~[ProtocolLib.jar:?]
```

**Version Info**
https://gist.github.com/Muffin2Go/b8e36e19abd72b32808d80ae936860a7

**Additional context**
Don't know

**Comment by Muffin2Go** [comment]
Seems to be fixed in the newest Dev Build 702
