### ISSUE TITLE
prtocolib Not working

### ISSUE THREAD

**Issue by Viper-dummy** [dmulloy2/ProtocolLib#2995]
it said to paste here this error. i am also using orebsfucator so i need protocolib

 Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1518af76[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4073268e
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@10c042e9
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@b8b62e2
      server=CraftServer{serverName=Paper,serverVersion=1.20.6-130-5d8e53d,minecraftVersion=1.20.6}
      file=plugins\.paper-remapped\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@22bbed41
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@22bbed41
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@1551ac7c
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@350c5f8f
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.20.6-130-5d8e53d (MC: 1.20.6)

**Comment by Jeppa** [comment]
> it said to paste here this error. i am also using orebsfucator so i need protocolib

Maybe it did... but you did not check if this is an old issue..
This was already mentioned many times before...

ProtocolLib v5.2.0-SNAPSHOT-679
is NOT compatible with
1.20.6-130-5d8e53d (MC: 1.20.6)

please update to latest dev build. ;)
