### ISSUE TITLE
ProtocolLib breaks Stackmob

### ISSUE THREAD

**Issue by andrewkm** [dmulloy2/ProtocolLib#2999]
Both https://github.com/Nathat23/StackMob-5/issues/288 & https://github.com/Nathat23/StackMob-5/issues/287 are being broken by the latest builds of ProtocolLib.

**Comment by dmulloy2** [comment]
```[08:08:24] [Server thread/WARN]: [StackMob] Task #79 for StackMob v5.8.10 generated an exception
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundAddEntityPacket - true - com.comphenix.protocol.wrappers.WrappedStreamCodec[handle=net.minecraft.network.codec.StreamCodec$5@19c8fa8]
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.lambda$newPacket$4(StructureCache.java:130) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:134) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:144) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:119) ~[ProtocolLib.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.spawnFakeArmorStand(ProtocolLibHook.java:68) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.spawnFakeArmorStand(ProtocolLibFakeArmorStand.java:26) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.TagHandler.newlyInRange(TagHandler.java:38) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:47) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.10.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]```

**Comment by andrewkm** [comment]
https://github.com/dmulloy2/ProtocolLib/commit/914bc9aa7f64be287041020ba2be804eb76eb292 has fixed https://github.com/Nathat23/StackMob-5/issues/288.

https://github.com/Nathat23/StackMob-5/issues/289 remains broken (1.20.6).

**Comment by andrewkm** [comment]
Stackmob issues are now fixed. :)
Tested against https://github.com/Nathat23/StackMob-5/commit/7e2dd33407d0c7b7dde411bd5ff87312b5744325 & https://github.com/dmulloy2/ProtocolLib/commit/389233f599b6d0008e607f8c498bfb152a130424
