### ISSUE TITLE
1.16.5 Join server exception + disconnect

### ISSUE THREAD

**Issue by EternalHuman** [dmulloy2/ProtocolLib#3026]
- [ ] This issue is not solved in a development build

**Describe the bug**
[Server thread/WARN]: Failed to handle packet for /***.**.**.**:46824
net.minecraft.server.v1_16_R3.ReportedException: Sending packet
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2041) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:2006) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:281) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:190) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:87) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:583) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1597) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.NullPointerException: type cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2033) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 12 more

**To Reproduce**
1. Join server

**Expected behavior**
-

**Screenshots**
-

**Version Info**
ProtocolLib Version: ProtocolLib v5.2.0-SNAPSHOT-679

**Additional context**

**Comment by Ingrim4** [comment]
Might be fixed with the latest dev build: https://ci.dmulloy2.net/job/ProtocolLib/. Can you confirm if that's the case?
