### ISSUE TITLE
INTERNAL ERROR

### ISSUE THREAD

**Issue by Nicouschulas** [dmulloy2/ProtocolLib#3031]
- [x] This issue is not solved in a development build

**Describe the bug**

[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@808df46[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@70b427da
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3e082465
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@5205472f
      server=CraftServer{serverName=Paper,serverVersion=1.21-21-0a1b133,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@58f06e06
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@58f06e06
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@237cdc7a
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@887b888
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21
  Server:
    1.21-21-0a1b133 (MC: 1.21)

**To Reproduce**
1. Go to 'newest Paper 1.21 build'
2. Click on 'start'
3. See error

**Expected behavior**

Can't load

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.

**Additional context**

**Comment by Jeppa** [comment]
Please update (!) ...

**Comment by LachCrafter** [comment]
It happens for me on the 1.20.6 version too.

**Comment by LachCrafter** [comment]
I resolved it using the latest build on the website: https://ci.dmulloy2.net/job/ProtocolLib/
