### ISSUE TITLE
Internel Error

### ISSUE THREAD

**Issue by LostUmbrella58** [dmulloy2/ProtocolLib#3037]
Console Error Logs:
[00:59:20 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ClassCastException: class java.util.AbstractMap$SimpleEntry cannot be cast to class java.lang.Integer (java.util.AbstractMap$SimpleEntry and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.comphenix.protocol.injector.packet.PacketRegistry.associatePackets(PacketRegistry.java:257)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:149)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:286)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:317)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:211)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at de.jpx3.intave.t6.a(t6.java:26)
        at de.jpx3.intave.t6.a(t6.java:11)
        at de.jpx3.intave.t6.b(t6.java:34)
        at de.jpx3.intave.IntavePlugin.onEnable(Native Method)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:264)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
        at java.base/java.lang.Thread.run(Thread.java:842)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3c41d05[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@74398383
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4e5900ac
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@3302a17e
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-21fe707-741a1bd,minecraftVersion=1.8.8}
      file=D:\饥饿游戏\饥饿游戏快速房\plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@28100237
      dataFolder=D:\饥饿游戏\饥饿游戏快速房\plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2fd4fb1a
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=D:\饥饿游戏\饥饿游戏快速房\plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@8e5661f
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    17.0.11
  Server:
    git-Spigot-21fe707-741a1bd (MC: 1.8.8)

[00:59:20 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[00:59:20 ERROR]: ******************************************************
[00:59:20 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[00:59:20 ERROR]: *** Please use the built-in reload command!        ***
[00:59:20 ERROR]: ******************************************************
[00:59:20 INFO]: [ProtocolLib] Disabling ProtocolLib v4.8.0
[00:59:20 ERROR]: Error occurred while enabling Intave v14.8.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/utility/MinecraftVersion
        at de.jpx3.intave.ld.<clinit>(ld.java:8) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at de.jpx3.intave.oy.b(oy.java) ~[?:?]
        at de.jpx3.intave.oy.d(oy.java) ~[?:?]
        at de.jpx3.intave.oy.a(oy.java) ~[?:?]
        at de.jpx3.intave.oy.a(oy.java) ~[?:?]
        at de.jpx3.intave.oy.a(oy.java) ~[?:?]
        at de.jpx3.intave.IntavePlugin.onEnable(Native Method) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:264) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.utility.MinecraftVersion
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8-1.9-SNAPSHOT.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 20 more

Server Version:
This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version Unknown-Version)

**Comment by derklaro** [comment]
As stated in the log: don't reload your server. And please note that the 4.8.0 version is no longer supported and will not receive any bug-fix updates anymore. Please switch to ProtocolLib v5 (if possible) to get support & updates.

**Comment by LostUmbrella58** [comment]
Thanks for replying!
However I might meet another issue...
[01:13:51 INFO]: [ProtocolLib] Loading ProtocolLib v5.2.0-SNAPSHOT-679
[01:13:52 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ClassCastException: class java.util.AbstractMap$SimpleEntry cannot be cast to class java.lang.Integer (java.util.AbstractMap$SimpleEntry and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.comphenix.protocol.injector.packet.PacketRegistry.associatePackets(PacketRegistry.java:296)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:159)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:336)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
        at java.base/java.lang.Thread.run(Thread.java:842)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@2199092c[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2a938b9b
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4254d484
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@5a117704
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-21fe707-741a1bd,minecraftVersion=1.8.8}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@31a66c77
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1c603c3e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@4b2f23e5
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    17.0.11
  Server:
    git-Spigot-21fe707-741a1bd (MC: 1.8.8)
