### ISSUE TITLE
The issue lies in the com.comphenix.protocol.injector.StructureCache.getStructure method, where the type parameter is null, causing the Preconditions.checkNotNull method to throw a NullPointerException.

### ISSUE THREAD

**Issue by nate981120** [dmulloy2/ProtocolLib#3044]
java.lang.NullPointerException: type cannot be null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
    at ProtocolLib.jar//com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138)
    at ProtocolLib.jar//com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
    at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
    at net.minecraft.network.Connection.sendPacket(Connection.java:449)
    at net.minecraft.network.Connection.send(Connection.java:392)
    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:243)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
    at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by JH3Y50N** [comment]
i too same problem.

**Comment by Ingrim4** [comment]
Please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/
