### ISSUE TITLE
clientbound/minecraft:set_objective (ProtocolLib for 1.20.6 - 1.21)  

### ISSUE THREAD

**Issue by ovp561** [dmulloy2/ProtocolLib#3051]
[02:03:22 INFO]: [Geyser-Spigot] Player connected with username Nour9080
[02:03:22 INFO]: [Geyser-Spigot] Nour9080 (logged in as: Nour9080) has connected to the Java server
[02:03:22 INFO]: [floodgate] Floodgate player logged in as Nour9080 joined (UUID: 00000000-0000-0000-0009-01fdfafb7c28)
[02:03:23 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[02:03:23 ERROR]: Error sending packet clientbound/minecraft:set_objective (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_objective'
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:750) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at TAB v4.1.6.jar/me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.6.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at GSit-1.9.5.jar/dev.geco.gsit.mcv.v1_20_5.util.PackageUtil$1.write(PackageUtil.java:91) ~[GSit-1.9.5.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at Geyser-Spigot.jar/org.geysermc.geyser.network.netty.ChannelWrapper.writeAndFlush(ChannelWrapper.java:219) ~[Geyser-Spigot.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:505) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class java.lang.Object cannot be cast to class net.minecraft.network.chat.numbers.NumberFormat (java.lang.Object is in module java.base of loader 'bootstrap'; net.minecraft.network.chat.numbers.NumberFormat is in unnamed module of loader java.net.URLClassLoader @5a10411)
        at net.minecraft.network.codec.StreamCodec$6.encode(StreamCodec.java:104) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:363) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:353) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.game.ClientboundSetObjectivePacket.write(ClientboundSetObjectivePacket.java:57) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        ... 51 more
[02:03:23 INFO]: [floodgate] Floodgate player logged in as Nour9080 disconnected
[02:03:23 INFO]: [Geyser-Spigot] Nour9080 has disconnected from the Java server because of Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_objective'
[02:03:23 INFO]: Nour9080[IP hidden] logged in with entity id 65 at ([world]196409.12, 42.0, 12890.586)
[02:03:23 INFO]: Nour9080 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_objective'
[02:03:23 WARN]: java.lang.ClassNotFoundException: mc.alk.arena.alib.battlebukkitlib.compat.v1_20_6.PlayerHandler
[02:03:23 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[02:03:23 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[02:03:23 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[02:03:23 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[02:03:23 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[02:03:23 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[02:03:23 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[02:03:23 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[02:03:23 WARN]:        at BattleArena.jar//mc.alk.arena.alib.battlebukkitlib.factory.HandlerFactory.getNewInstance(HandlerFactory.java:13)
[02:03:23 WARN]:        at BattleArena.jar//mc.alk.arena.alib.battlebukkitlib.factory.PlayerHandlerFactory.getNewInstance(PlayerHandlerFactory.java:10)
[02:03:23 WARN]:        at BattleArena.jar//mc.alk.arena.alib.battlebukkitlib.PlayerUtil.<clinit>(PlayerUtil.java:12)
[02:03:23 WARN]:        at BattleArena.jar//mc.alk.arena.util.PlayerUtil.getID(PlayerUtil.java:134)
[02:03:23 WARN]:        at BattleArena.jar//mc.alk.arena.controllers.PlayerController.hasArenaPlayer(PlayerController.java:73)
[02:03:23 WARN]:        at BattleArena.jar//mc.alk.arena.listeners.BAPlayerListener.onPlayerQuit(BAPlayerListener.java:86)
[02:03:23 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source)
[02:03:23 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[02:03:23 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[02:03:23 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:03:23 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:03:23 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[02:03:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[02:03:23 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:611)
[02:03:23 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:596)
[02:03:23 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2091)
[02:03:23 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2071)
[02:03:23 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2058)
[02:03:23 WARN]:        at net.minecraft.network.Connection.handleDisconnection(Connection.java:890)
[02:03:23 WARN]:        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:262)
[02:03:23 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801)
[02:03:23 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
[02:03:23 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
[02:03:23 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[02:03:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[02:03:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[02:03:23 WARN]: java.lang.ClassNotFoundException: Could not find net.minecraft.server.EntityPlayer
[02:03:23 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.NMSUtil.fixBukkitClass(NMSUtil.java:122)
[02:03:23 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.NMSUtil.<clinit>(NMSUtil.java:61)
[02:03:23 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:2025)
[02:03:23 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1931)
[02:03:23 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.lambda$PlayerQuitEvent$3(PlayerJoinLeaveListener.java:131)
[02:03:23 WARN]:        at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.util.SchedulerUtil.lambda$runTaskAsynchronously$1(SchedulerUtil.java:95)
[02:03:23 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217)
[02:03:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[02:03:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[02:03:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Ingrim4** [comment]
This is an issue caused by [GSit](https://github.com/gecolay/GSit) and doesn't have anything to do with ProtocolLib as far as I can tell. GSit probably just set a field inside the `ClientboundSetObjectivePacket` wrong so please report this to the plugin authors of GSit.

**Comment by se7enzx** [comment]
I have the same problem

**Comment by Ingrim4** [comment]
This issue is likely caused by [SimpleScore](https://github.com/r4g3baby/SimpleScore). Please try removing SimpleScore and see if the problem is resolved. If the issue is fixed after removing it, kindly report this to the SimpleScore author(s).

**Comment by wuliao697** [comment]
You could try this. https://github.com/r4g3baby/SimpleScore/issues/88
