### ISSUE TITLE
SimpleScore and ProtocolLib Bug

### ISSUE THREAD

**Issue by nate981120** [dmulloy2/ProtocolLib#3057]
[22:37:45 WARN]: [SimpleScore] Task #402560 for SimpleScore v3.12.4 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib (8).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib (8).jar:?]
        at com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:128) ~[SimpleScore-3.12.4.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.updateScoreboards(ScoreboardTask.kt:88) ~[SimpleScore-3.12.4.jar:?]
        at com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda$7(ScoreboardTask.kt:71) ~[SimpleScore-3.12.4.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Ingrim4** [comment]
Can you please create a protocol dump file using `/protocol dump` command on your server and send us the contents of the created dump file?

**Comment by Z1xus** [comment]
having same issue

<details>
  <summary>related server log</summary>
 
  
  ```
[22:37:56] [Netty Epoll Server IO #2/ERROR]: Error sending packet clientbound/minecraft:set_objective (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_objective'
	at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:771) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at TAB v4.1.8.jar/me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.8.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class java.lang.Object cannot be cast to class net.minecraft.network.chat.numbers.NumberFormat (java.lang.Object is in module java.base of loader 'bootstrap'; net.minecraft.network.chat.numbers.NumberFormat is in unnamed module of loader java.net.URLClassLoader @2ef1e4fa)
	at net.minecraft.network.codec.StreamCodec$6.encode(StreamCodec.java:104) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:363) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:353) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.protocol.game.ClientboundSetObjectivePacket.write(ClientboundSetObjectivePacket.java:57) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	... 50 more
[22:37:56] [Server thread/INFO]: Z1xus[/176.2.66.15:38763] logged in with entity id 3 at ([world]-4741.99941334709, 71.0, 5784.638188050603)
[22:37:56] [Server thread/WARN]: [SimpleScore] Task #3175 for SimpleScore v3.12.5 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at ProtocolLib.jar/com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318) ~[ProtocolLib.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.handlers.ProtocolScoreboard.updateScoreboard(ProtocolScoreboard.kt:154) ~[SimpleScore-3.12.5.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.updateScoreboards(ScoreboardTask.kt:89) ~[SimpleScore-3.12.5.jar:?]
	at SimpleScore-3.12.5.jar/com.r4g3baby.simplescore.scoreboard.tasks.ScoreboardTask.run$lambda$7(ScoreboardTask.kt:72) ~[SimpleScore-3.12.5.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1761) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2315-2a50638]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:37:56] [Server thread/INFO]: Z1xus lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_objective'

  ```
  
</details>

<details>
  <summary>output of /protocol dump</summary>
 
  
  ```
ProtocolLib Dump
Timestamp: 09/29/24 22:37:12

ProtocolLib Version: ProtocolLib v5.3.0-SNAPSHOT-732
Bukkit Version: 1.21.1-R0.1-SNAPSHOT
Server Version: 1.21.1-2315-2a50638 (MC: 1.21.1)
Java Version: 21.0.4

ProtocolLib: com.comphenix.protocol.ProtocolLib@dd3f001[
  statistics=com.comphenix.protocol.metrics.Statistics@2814890
  packetTask=com.comphenix.protocol.scheduler.DefaultTask@19432312
  tickCounter=1905
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@1c402f4a
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@e01873b
  scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@64c8ba3
  commandProtocol=com.comphenix.protocol.CommandProtocol@61773cb
  commandPacket=com.comphenix.protocol.CommandPacket@1b30263c
  commandFilter=com.comphenix.protocol.CommandFilter@190a523e
  packetLogging=com.comphenix.protocol.PacketLogging@7bf9c32f
  skipDisable=false
  isEnabled=true
  loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@464d6eb0
  server=CraftServer{serverName=Purpur,serverVersion=1.21.1-2315-2a50638,minecraftVersion=1.21.1}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@17069395
  pluginMeta=org.bukkit.plugin.PluginDescriptionFile@17069395
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.3.0-SNAPSHOT-732, pluginEnabled=true, url=plugins/ProtocolLib.jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@f4608f5
  lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@66f5ea27
  allowsLifecycleRegistration=false
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@45cc5757[
  plugin=ProtocolLib v5.3.0-SNAPSHOT-732
  server=CraftServer{serverName=Purpur,serverVersion=1.21.1-2315-2a50638,minecraftVersion=1.21.1}
  reporter=com.comphenix.protocol.ProtocolLib$1@79f409dd
  minecraftVersion=(MC: 1.21.1)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@46cab7b6
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@f27d99a
  mainThreadPacketTypes=com.comphenix.protocol.concurrent.PacketTypeListenerSet@287651c6
  inboundListeners=com.comphenix.protocol.injector.collection.InboundPacketListenerSet@71951ff4
  outboundListeners=com.comphenix.protocol.injector.collection.OutboundPacketListenerSet@62717177
  registeredListeners=[PacketAdapter[plugin=CMI, sending=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=ClientboundForgetLevelChunkPacket, id=33]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=InteractiveChat, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57], SET_TITLE_TEXT[class=ClientboundSetTitleTextPacket, id=101], SET_SUBTITLE_TEXT[class=ClientboundSetSubtitleTextPacket, id=99], DISGUISED_CHAT[class=ClientboundDisguisedChatPacket, id=30], SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108], SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=76]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuraSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=InteractiveChat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[CLIENT_INFORMATION[class=ServerboundClientInformationPacket, id=0]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=ServerboundPlayerAbilitiesPacket, id=35]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuraSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=76]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=ClientboundSetEntityMotionPacket, id=90], REL_ENTITY_MOVE[class=Pos, id=46], REL_ENTITY_MOVE_LOOK[class=PosRot, id=47]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=StatusOnly, id=29], POSITION_LOOK[class=PosRot, id=27], LOOK[class=Rot, id=28], POSITION[class=Pos, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=InteractiveChat, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=MONITOR, packets=[CHAT_COMMAND[class=ServerboundChatCommandPacket, id=4], CHAT_COMMAND_SIGNED[class=ServerboundChatCommandSignedPacket, id=5], CHAT[class=ServerboundChatPacket, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[PONG[class=ServerboundPongPacket, id=39]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=ClientboundKeepAlivePacket, id=38]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=ServerboundKeepAlivePacket, id=24]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[GROUND[class=StatusOnly, id=29], POSITION_LOOK[class=PosRot, id=27], LOOK[class=Rot, id=28], POSITION[class=Pos, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuraSkills, sending=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=InteractiveChat, sending=ListeningWhitelist[priority=HIGH, packets=[SERVER_DATA[class=ClientboundServerDataPacket, id=75]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.r4g3baby.simplescore.scoreboard.listeners.PacketListener@6005013d, PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=ClientboundExplodePacket, id=32]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=ClientboundContainerSetSlotPacket, id=21], WINDOW_ITEMS[class=ClientboundContainerSetContentPacket, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=InteractiveChat, sending=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=ClientboundCommandSuggestionsPacket, id=16]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST]]
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@532b9faa
  debug=false
  closed=false
  injected=true
]

Listeners:
com.Zrips.CMI.AllListeners.ProtocolEvent$1@5bec3fcc[
  plugin=CMI v9.7.6.4
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[UNLOAD_CHUNK[class=ClientboundForgetLevelChunkPacket, id=33]], gamephase=PLAYING, options=[]]
]
com.loohp.interactivechat.listeners.OutMessagePacket$1@10c9db48[
  plugin=InteractiveChat v4.2.12.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57], SET_TITLE_TEXT[class=ClientboundSetTitleTextPacket, id=101], SET_SUBTITLE_TEXT[class=ClientboundSetSubtitleTextPacket, id=99], DISGUISED_CHAT[class=ClientboundDisguisedChatPacket, id=30], SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108], SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=76]], gamephase=PLAYING, options=[]]
]
dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook$2@1ca888ab[
  plugin=AuraSkills v2.2.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=108]], gamephase=PLAYING, options=[]]
]
com.loohp.interactivechat.listeners.ClientSettingPacket$1@6f4e87c8[
  plugin=InteractiveChat v4.2.12.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CLIENT_INFORMATION[class=ServerboundClientInformationPacket, id=0]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.gmail.olexorus.themis.i@550d5f0b[
  t=com.gmail.olexorus.themis.y@775b04e
  plugin=Themis v0.16.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=ServerboundPlayerAbilitiesPacket, id=35]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook$1@63ce44a9[
  plugin=AuraSkills v2.2.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[SET_ACTION_BAR_TEXT[class=ClientboundSetActionBarTextPacket, id=76]], gamephase=PLAYING, options=[]]
]
com.gmail.olexorus.themis.ch@38673cad[
  S=com.comphenix.protocol.injector.PacketFilterManager@45cc5757
  plugin=Themis v0.16.1
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[ENTITY_VELOCITY[class=ClientboundSetEntityMotionPacket, id=90], REL_ENTITY_MOVE[class=Pos, id=46], REL_ENTITY_MOVE_LOOK[class=PosRot, id=47]], gamephase=PLAYING, options=[]]
]
com.gmail.olexorus.themis.I@7039c013[
  F=com.gmail.olexorus.themis.y@775b04e
  plugin=Themis v0.16.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[GROUND[class=StatusOnly, id=29], POSITION_LOOK[class=PosRot, id=27], LOOK[class=Rot, id=28], POSITION[class=Pos, id=26]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.loohp.interactivechat.listeners.RedispatchSignedPacket$1@7c8c109a[
  plugin=InteractiveChat v4.2.12.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CHAT_COMMAND[class=ServerboundChatCommandPacket, id=4], CHAT_COMMAND_SIGNED[class=ServerboundChatCommandSignedPacket, id=5], CHAT[class=ServerboundChatPacket, id=6]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.gmail.olexorus.themis.K@6e09797f[
  plugin=Themis v0.16.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[PONG[class=ServerboundPongPacket, id=39]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
com.gmail.olexorus.themis.e5@44bcbf4a[
  plugin=Themis v0.16.1
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=ServerboundKeepAlivePacket, id=24]], gamephase=PLAYING, options=[]]
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[KEEP_ALIVE[class=ClientboundKeepAlivePacket, id=38]], gamephase=PLAYING, options=[]]
]
com.gmail.olexorus.themis.eH@4175af43[
  plugin=Themis v0.16.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[GROUND[class=StatusOnly, id=29], POSITION_LOOK[class=PosRot, id=27], LOOK[class=Rot, id=28], POSITION[class=Pos, id=26]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
dev.aurelium.auraskills.bukkit.hooks.ProtocolLibHook$4@27f3f484[
  plugin=AuraSkills v2.2.3
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[CHAT[class=ClientboundPlayerChatPacket, id=57]], gamephase=PLAYING, options=[]]
]
com.loohp.interactivechat.listeners.RedispatchSignedPacket$2@26988b40[
  plugin=InteractiveChat v4.2.12.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGH, packets=[SERVER_DATA[class=ClientboundServerDataPacket, id=75]], gamephase=PLAYING, options=[]]
]
com.r4g3baby.simplescore.scoreboard.listeners.PacketListener@6005013d[
  protocolLibPlugin=ProtocolLib v5.3.0-SNAPSHOT-732
  sendingPackets=ListeningWhitelist[priority=HIGHEST, packets=[SCOREBOARD_DISPLAY_OBJECTIVE[class=ClientboundSetDisplayObjectivePacket, id=87], SCOREBOARD_OBJECTIVE[class=ClientboundSetObjectivePacket, id=94]], gamephase=PLAYING, options=[]]
  afterTrailsAndTailsDot2Update=true
]
com.gmail.olexorus.themis.eP@7c6285b[
  S=com.gmail.olexorus.themis.y@775b04e
  plugin=Themis v0.16.1
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=ClientboundExplodePacket, id=32]], gamephase=PLAYING, options=[]]
]
fr.xephi.authme.listener.protocollib.InventoryPacketAdapter@2810bace[
  logger=fr.xephi.authme.ConsoleLogger@514e7ed9
  playerCache=fr.xephi.authme.data.auth.PlayerCache@159e1269
  dataSource=fr.xephi.authme.datasource.CacheDataSource@69c3d3a8
  plugin=AuthMe v5.6.0-beta2-b2453
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=ClientboundContainerSetSlotPacket, id=21], WINDOW_ITEMS[class=ClientboundContainerSetContentPacket, id=19]], gamephase=PLAYING, options=[]]
]
com.loohp.interactivechat.listeners.OutTabCompletePacket$1@319c08e3[
  plugin=InteractiveChat v4.2.12.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[TAB_COMPLETE[class=ClientboundCommandSuggestionsPacket, id=16]], gamephase=PLAYING, options=[ASYNC]]
]

Plugins Using ProtocolLib:
AuthMe by [Xephi, sgdc3, DNx5, timvisee, games647, ljacqu, Gnat008]
AuraSkills by [Archyx]
Themis by [Olexorus]
SimpleScore by [R4G3_BABY]
InteractiveChat by [loohp]
CMI by [Zrips]

  ```
  
</details>
