### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CBM1014** [dmulloy2/ProtocolLib#306]
Stack Trace:
  java.lang.NullPointerException
  	at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:613)
  	at com.comphenix.protocol.ProtocolLib.access$600(ProtocolLib.java:66)
  	at com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:576)
  	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
  	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
  	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820)
  	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
  	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
  	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3eafbfb6[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@678d0c69
        packetListeners=[net.andylizi.colormotd.bukkit.listener.abstract@7b908542, PacketAdapter[plugin=Orebfuscator4, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInBlockDig[19, legacy: 7]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=Orebfuscator4, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutMapChunk[32, legacy: 33]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2b4e9693
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@4d9bec3d
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@e0ab837
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1eb03db
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5e4ee77b
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@246ccf31
        reporter=com.comphenix.protocol.ProtocolLib$1@4c26028b
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-1076,minecraftVersion=1.11.2}
        library=ProtocolLib v4.2.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4e1afcde
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=2
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@23fb08b8
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@711547e9
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.11.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@2c1bc1f0
        debug=false
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@64f4219d[
      statistics=com.comphenix.protocol.metrics.Statistics@941ceff
      backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@695bd656
      packetTask=5
      tickCounter=20
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@678d0c69
      configExpectedMod=1
      updater=com.comphenix.protocol.updater.BukkitUpdater@6f6cb501
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@518b0b3d
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-1076,minecraftVersion=1.11.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@10ebcbcb
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@246ccf31
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@2b0420f
    ]
  Version:
    ProtocolLib v4.2.0
  Java Version:
    1.8.0_121
  Server:
    git-Paper-1076 (MC: 1.11.2)

**Comment by dmulloy2** [comment]
Try the latest dev build here: http://ci.dmulloy2.net/job/ProtocolLib/
