### ISSUE TITLE
paper 1.21 error

### ISSUE THREAD

**Issue by SnaRad2020** [dmulloy2/ProtocolLib#3067]
here`s log

[10:37:43 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[10:37:43 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[10:37:45 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[10:37:45 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:168)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@63c07a8a[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@19b5dcd4
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7941f142
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3025db76
      server=CraftServer{serverName=Paper,serverVersion=1.21-39-aa8d38d,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@26b85891
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@26b85891
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@59ab8ffd
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@4a560c4f
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.3
  Server:
    1.21-39-aa8d38d (MC: 1.21)

[10:37:45 INFO]: [pv-addon-lavaplayer-lib] Loading server plugin pv-addon-lavaplayer-lib v1.0.9
[10:37:45 INFO]: [pv-addon-groups] Loading server plugin pv-addon-groups v1.0.3
[10:37:45 INFO]: [AuthMe] Loading server plugin AuthMe v5.6.0-bCUSTOM
[10:37:45 INFO]: [pv-addon-sculk] Loading server plugin pv-addon-sculk v1.0.0
[10:37:45 INFO]: [pv-addon-discs] Loading server plugin pv-addon-discs v1.0.6
[10:37:45 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:37:45 INFO]: [PlasmoVoice] Enabling PlasmoVoice v2.0.10
[10:37:46 INFO]: [PlasmoVoice] pv-addon-groups v1.0.3 by KPidS loaded
[10:37:46 INFO]: [PlasmoVoice] pv-addon-lavaplayer-lib v1.0.9 by Apehum loaded
[10:37:46 INFO]: [PlasmoVoice] pv-addon-sculk v1.0.0 by Apehum loaded
[10:37:46 INFO]: [PlasmoVoice] pv-addon-discs v1.0.6 by KPidS loaded
[10:37:46 INFO]: [PlasmoVoice] UDP server is started on /[0:0:0:0:0:0:0:0]:25565
[10:37:46 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[10:37:46 ERROR]: ******************************************************
[10:37:46 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[10:37:46 ERROR]: *** Please use the built-in reload command!        ***
[10:37:46 ERROR]: ******************************************************
[10:37:46 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
[10:37:46 INFO]: [pv-addon-lavaplayer-lib] Enabling pv-addon-lavaplayer-lib v1.0.9
[10:37:46 INFO]: [pv-addon-groups] Enabling pv-addon-groups v1.0.3
[10:37:46 INFO]: [pv-addon-sculk] Enabling pv-addon-sculk v1.0.0
[10:37:46 INFO]: [pv-addon-discs] Enabling pv-addon-discs v1.0.6
[10:37:47 ERROR]: Error occurred while enabling pv-addon-discs v1.0.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at pv-addon-discs-1.0.6.jar/su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:90) ~[pv-addon-discs-1.0.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:291) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 11 more

**Comment by Jeppa** [comment]
How about updating? ;)

**Comment by SnaRad2020** [comment]
[11:30:18 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[11:30:18 INFO]: [PlasmoVoice] Loading server plugin PlasmoVoice v2.0.10
[11:30:18 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[11:30:18 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[11:30:20 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[11:30:20 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@547f474a[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@2dd7b278
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@33ce59f
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3bbda255
      server=CraftServer{serverName=Paper,serverVersion=1.21-39-aa8d38d,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@a64abe8
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@a64abe8
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@1f05fa68
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@72310419
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-39-aa8d38d (MC: 1.21)

[11:30:20 INFO]: [pv-addon-lavaplayer-lib] Loading server plugin pv-addon-lavaplayer-lib v1.0.9
[11:30:20 INFO]: [pv-addon-groups] Loading server plugin pv-addon-groups v1.0.3
[11:30:20 INFO]: [AuthMe] Loading server plugin AuthMe v5.6.0-bCUSTOM
[11:30:20 INFO]: [pv-addon-sculk] Loading server plugin pv-addon-sculk v1.0.0
[11:30:20 INFO]: [pv-addon-discs] Loading server plugin pv-addon-discs v1.0.6
[11:30:20 INFO]: Server permissions file permissions.yml is empty, ignoring it
[11:30:20 INFO]: [PlasmoVoice] Enabling PlasmoVoice v2.0.10
[11:30:21 INFO]: [PlasmoVoice] pv-addon-groups v1.0.3 by KPidS loaded
[11:30:21 INFO]: [PlasmoVoice] pv-addon-lavaplayer-lib v1.0.9 by Apehum loaded
[11:30:21 INFO]: [PlasmoVoice] pv-addon-sculk v1.0.0 by Apehum loaded
[11:30:21 INFO]: [PlasmoVoice] pv-addon-discs v1.0.6 by KPidS loaded
[11:30:21 INFO]: [PlasmoVoice] UDP server is started on /[0:0:0:0:0:0:0:0]:25565
[11:30:21 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[11:30:21 ERROR]: ******************************************************
[11:30:21 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[11:30:21 ERROR]: *** Please use the built-in reload command!        ***
[11:30:21 ERROR]: ******************************************************
[11:30:21 INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679
[11:30:21 INFO]: [pv-addon-lavaplayer-lib] Enabling pv-addon-lavaplayer-lib v1.0.9
[11:30:21 INFO]: [pv-addon-groups] Enabling pv-addon-groups v1.0.3
[11:30:21 INFO]: [pv-addon-sculk] Enabling pv-addon-sculk v1.0.0
[11:30:21 INFO]: [pv-addon-discs] Enabling pv-addon-discs v1.0.6
[11:30:22 ERROR]: Error occurred while enabling pv-addon-discs v1.0.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at pv-addon-discs-1.0.6.jar/su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:90) ~[pv-addon-discs-1.0.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:291) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-39-aa8d38d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 11 more
[11:30:22 INFO]: [pv-addon-discs] Disabling pv-addon-discs v1.0.6

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/
