### ISSUE TITLE
DEV Build error on Minecraft Spigot 1.21

### ISSUE THREAD

**Issue by Nitrowut** [dmulloy2/ProtocolLib#3072]
```
Server is running CraftBukkit version 4248-Spigot-491f367-ae4f5a0 (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
(Version get from BuildTool)

[12:52:12] [Server thread/WARN]: [ProtocolLib] [ProtocolLib] Unable to retrieve current Minecraft version. Assuming (MC: 1.20.4)
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
        at com.comphenix.protocol.ProtocolConfig.getIgnoreVersionCheck(ProtocolConfig.java:297) ~[?:?]
        at com.comphenix.protocol.ProtocolLib.verifyMinecraftVersion(ProtocolLib.java:376) ~[?:?]
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:168) ~[?:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:461) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
```

![Screenshot 2024-07-01 125518](https://github.com/dmulloy2/ProtocolLib/assets/90637471/e8f5db87-0fc2-48cc-b86d-ccea27262d76)

**Comment by derklaro** [comment]
The `ignore version check` setting in the config file is not a boolean, but a list of strings (the minecraft version you want to ignore the check on).

**Comment by Nitrowut** [comment]
> The `ignore version check` setting in the config file is not a boolean, but a list of strings (the minecraft version you want to ignore the check on).

How to fix? Sorry I didn't understand

**Comment by Nitrowut** [comment]
> The `ignore version check` setting in the config file is not a boolean, but a list of strings (the minecraft version you want to ignore the check on).

I set the `ignore version check` to 1.20.4 and I got this (In screenshopt) I think it's fine now. Thanks

![image](https://github.com/dmulloy2/ProtocolLib/assets/90637471/2e7b4bdf-84cb-4854-86fb-49af133bde53)
