### ISSUE TITLE
Paper 1.21 Server not beeing able to load ProtocolLib

### ISSUE THREAD

**Issue by Gyxuu** [dmulloy2/ProtocolLib#3073]
Server not beeing able to load ProtocolLib and due to that other plugins too. My pc is more than capable to run both minecraft and the server so the error isnt my pc.

[14:12:27 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[14:12:29 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[14:12:29 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
        at java.base/java.lang.Thread.run(Thread.java:1570)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5cb2f3c5[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@18ac3f99
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@53cbcb92
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@2a9a7cec
      server=CraftServer{serverName=Paper,serverVersion=1.21-38-1f5db50,minecraftVersion=1.21}
      file=plugins\.paper-remapped\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1e28cce8
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1e28cce8
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@16dc7a10
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@30735a8f
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    22.0.1
  Server:
    1.21-38-1f5db50 (MC: 1.21)

**Comment by Gyxuu** [comment]
> I have the same issue

Should be fixed in the latest dev build: https://ci.dmulloy2.net/job/ProtocolLib/
I just tested it and it is marked as working and the other plugins dont spit out errors.
![image](https://github.com/dmulloy2/ProtocolLib/assets/168175217/b4dd0dc2-ffa9-40b5-bdf7-90d5d92212a7)

**Comment by Artcas2** [comment]
Thank you!

**Comment by bilgakhan** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/5024b155-ce63-49ae-b7b9-28642425690e">

**Comment by Artcas2** [comment]
> <img alt="image" width="1470" src="https://private-user-images.githubusercontent.com/87275043/374044903-5024b155-ce63-49ae-b7b9-28642425690e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDE0MDIsIm5iZiI6MTcyODU0MTEwMiwicGF0aCI6Ii84NzI3NTA0My8zNzQwNDQ5MDMtNTAyNGIxNTUtY2U2My00OWFlLWI3YjktMjg2NDI0MjU2OTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA2MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MDU4ODk3NzdiNTNkN2M3ZTJiZjRmZTViNmNlOTlkZjJlMTEzYmM4MWY0ZGFmYzM0ZGFkYzZlMWQ3ZDhlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jtvsMhmdINGmm_c00rfq0laHs7ptRk6zVwo0ojs6Juk">

It works for me
