### ISSUE TITLE
help please :(

### ISSUE THREAD

**Issue by Ayasticall** [dmulloy2/ProtocolLib#3084]
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:461)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236)
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@5aa1b66[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@25512164
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@70f57f83
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@75e61b11
      server=CraftServer{serverName=CraftBukkit,serverVersion=4226-Spigot-146439e-2889b3a,minecraftVersion=1.21}
      file=plugins\ProtocolLib new.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6bbfcd2f
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@20ad697b
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@44b72644
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    4226-Spigot-146439e-2889b3a (MC: 1.21)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Ayasticall** [comment]
i try, but it doesn't work, my nether always crashes my server

**Comment by Ingrim4** [comment]
Then please provide the error message that crashes your server because the one you initially send only occurs on outdated ProtocolLib.

**Comment by Ayasticall** [comment]
sorry I fixed the problem! thanks anyway
