### ISSUE TITLE
Error on start for 1.21 server

### ISSUE THREAD

**Issue by realzunker** [dmulloy2/ProtocolLib#3090]
Got this error when starting the server on 1.21 and it said to report it here so here it is. Error happens on latest spigot and github versions.

error: https://pastebin.com/RVr6XsX8

  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@b4c369f[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@758d8e1d
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@1f9fa6fd
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@32127326
      server=CraftServer{serverName=Paper,serverVersion=1.21-38-1f5db50,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@f17ead0
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@f17ead0
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@346f0b0b
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@1e15d5b4
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    1.21-38-1f5db50 (MC: 1.21)

**Comment by Aestheronaut** [comment]
same error here

**Comment by Jeppa** [comment]
You ProtocolLib is outdated!
Please update!

**Comment by jtwebhomer** [comment]
thats the protocol lib that is featured on the spigot website

**Comment by Jeppa** [comment]
The website clearly tells you which version to use for 1.20.6 or 1.21 --> latest dev build !
You can click that link or use the link here from the github page ...

**Comment by realzunker** [comment]
strange, couldve sworn i was using the latest version but i used that one and its working now
