### ISSUE TITLE
Error on paper 1.20.6 server with ProtocolLib

### ISSUE THREAD

**Issue by uertyk** [dmulloy2/ProtocolLib#3091]
- [ ] This issue is not solved in a development build

**Describe the bug**
The bug with 1.20.6 paper version , plugin stunning server....

**To Reproduce**
1. Go to 'start server on 1.20.6 paper'

**Expected behavior**

**Version Info**
[Provide your ProtocolLib install info with `/protocol dump` through pastebin.](https://www.spigotmc.org/resources/protocollib.1997/) this version , also latest version from paper 1.20.6

**Additional context**
Error:
-- Stack Trace:

java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}

at ProtocolLib (2).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)

at ProtocolLib (2).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)

at ProtocolLib (2).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)

at ProtocolLib (2).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)

at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)

at ProtocolLib (2).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)

at ProtocolLib (2).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)

at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)

at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)

at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)

at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)

at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:532)

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)

at java.base/java.lang.Thread.run(Thread.java:1570)

Dump:

Parameters:

[NULL]

Sender:

com.comphenix.protocol.ProtocolLib@192d5342[

statistics=<null>

packetTask=<null>

tickCounter=0

configExpectedMod=-1

updater=com.comphenix.protocol.updater.SpigotUpdater@ccb6657

redirectHandler=<null>

scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7f0f93cf

commandProtocol=<null>

commandPacket=<null>

commandFilter=<null>

packetLogging=<null>

skipDisable=false

isEnabled=false

loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@24e7aec8

server=CraftServer{serverName=Paper,serverVersion=1.20.6-148-20f5165,minecraftVersion=1.20.6}

file=plugins/.paper-remapped/ProtocolLib (2).jar

description=org.bukkit.plugin.PluginDescriptionFile@22363fe

pluginMeta=org.bukkit.plugin.PluginDescriptionFile@22363fe

dataFolder=plugins/ProtocolLib

classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib (2).jar}

naggable=true

newConfig=YamlConfiguration[path='', root='YamlConfiguration']

configFile=plugins/ProtocolLib/config.yml

logger=com.destroystokyo.paper.utils.PaperPluginLogger@19e12372

lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@65a3cae2

allowsLifecycleRegistration=true

]

Version:

ProtocolLib v5.2.0-SNAPSHOT-679

Java Version:

22.0.1

Server:

1.20.6-148-20f5165 (MC: 1.20.6)

**Comment by Jeppa** [comment]
Did you pay attention to the first line in you post?
'This issue is not solved in a development build'
==> YES, it is !
And there are 'hundreds' of identical issues posted here, always with the same answer:
You ProtocolLib is outdated!
Please update!

**Comment by UertyYT** [comment]
but latest version is 5.2.0!
And i downloaded it https://github.com/dmulloy2/ProtocolLib

**Comment by UertyYT** [comment]
> Did you pay attention to the first line in you post? 'This issue is not solved in a development build' ==> YES, it is ! And there are 'hundreds' of identical issues posted here, always with the same answer: You ProtocolLib is outdated! Please update!

but latest version is 5.2.0!
And i downloaded it https://github.com/dmulloy2/ProtocolLib

**Comment by Jeppa** [comment]
No, latest development build is 723 .
Link is on this github page...

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
