### ISSUE TITLE
Can't load protocollib on 1.12.2

### ISSUE THREAD

**Issue by Clexus** [dmulloy2/ProtocolLib#3101]
- [ ] This issue is not solved in a development build

**Describe the bug**
just the same as the title

**To Reproduce**
Download latest dev build
put it into /plugins folder
start the server
the server stop at "[ProtocolLib] Loading ProtocolLib v5.3.0-SNAPSHOT-723" and won't proceed

**Expected behavior**
Load

**Screenshots**
No need

**Version Info**
Can't

**Additional context**
No

**Comment by Ingrim4** [comment]
Could you please provide us with the following information to help us diagnose the problem?

1. **Server Version**: Run the command `/version` on your server and share the output with us.
2. **Debug Logs**: Enable the `debug` option in your ProtocolLib configuration file. After enabling it (setting it to `true`), restart your server and then upload the entire server log after the restart.

**Comment by Clexus** [comment]
```
> version
[20:50:51 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:50:51 INFO]: Checking version, please wait...
[20:50:53 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ci.destroystokyo.com/job/Paper/lastSuccessfulBuild/buildNumber
[20:50:53 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
[20:50:53 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
[20:50:53 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[20:50:53 WARN]:        at java.net.URL.openStream(URL.java:1093)
[20:50:53 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[20:50:53 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[20:50:53 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[20:50:53 WARN]:        at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:293)
[20:50:53 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:266)
[20:50:53 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:214)
[20:50:53 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:37)
[20:50:53 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:199)
[20:50:53 WARN]:        at java.lang.Thread.run(Thread.java:750)
[20:50:53 INFO]: Error obtaining version information
```
[2024-07-09-1.log](https://github.com/user-attachments/files/16194288/2024-07-09-1.log)

**Comment by Ingrim4** [comment]
I attempted to reproduce the issue but was unable to do so. Could you please try removing the other plugins and see if the problem persists? If removing the plugins resolves the issue, please reintroduce them one by one to identify which specific plugin is causing the conflict. Once identified, please report back with the details.

**Comment by Clexus** [comment]
> I attempted to reproduce the issue but was unable to do so. Could you please try removing the other plugins and see if the problem persists? If removing the plugins resolves the issue, please reintroduce them one by one to identify which specific plugin is causing the conflict. Once identified, please report back with the details.

Tried with only Protocollib
![image](https://github.com/user-attachments/assets/ebcd073e-5db4-483d-9660-daccfb44e1ce)

**Comment by Ingrim4** [comment]
Have you disabled outgoing connections and what java version are you using? e.g. `java --version`:
```txt
openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)
```

**Comment by Clexus** [comment]
> Have you disabled outgoing connections and what java version are you using? e.g. `java --version`:
> 
> ```
> openjdk 21.0.1 2023-10-17
> OpenJDK Runtime Environment (build 21.0.1+12-29)
> OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)
> ```

openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition 8.16.17) (build 1.8.0_382-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition 8.16.17) (build 25.382-b01, mixed mode)

**Comment by Clexus** [comment]
I can confirm it's about java version
Java 22 can run Protocollib
But Java 8 can't

**Comment by Ingrim4** [comment]
That's strange, can you for now use a newer Java version?

**Comment by Clexus** [comment]
> That's strange, can you for now use a newer Java version?

I'm using 5.1 now as 5.2 cause some crashing bugs

**Comment by Clexus** [comment]
still not fixed

**Comment by Clexus** [comment]
still not fixed

**Comment by Wind-Rise** [comment]
In fact, no one has tried to fix or understand this bug so far, which has resulted in me being unable to properly start the server using the Paper plugin.  
If you really don't want to fix it, why not just close this issue instead of leaving it hanging? It's already 2025 now, actually.
![Image](https://github.com/user-attachments/assets/260504b8-937e-480b-9252-3babc685ca10)
The plugin neither reports an error nor allows the server to continue running when loaded, remaining stuck in this state.

**Comment by Wind-Rise** [comment]
Received some good news.  
If you are really in a hurry to use the plugin, you can try the older version v4.4.0 [here](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.4.0). Based on my testing, it can run normally in the Paper server environment.

**Comment by Clexus** [comment]
still not fixed

**Comment by Wind-Rise** [comment]
Sorry I couldn't help you, but my problem has been temporarily resolved.  
Good luck, bro.
