### ISSUE TITLE
Invalid player data

### ISSUE THREAD

**Issue by gercsogamer** [dmulloy2/ProtocolLib#3105]
I cant join to my server, and I dont know what to do. Please help me. If I remove Protocollib everything works fine (but I need the plugin to use Itemadder)

Server version: 1.18.2
(Plugin updated)
Error:
java.lang.RuntimeException: Failed to find NMS class: WorldType
        at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$2(MinecraftReflection.java:1382) ~[ProtocolLib (5).jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1382) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getWorldTypeClass(MinecraftReflection.java:818) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.addConverter(BukkitConverters.java:1310) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1289) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1330) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:61) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:46) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:107) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:32) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.InjectionFactory.fromPlayer(InjectionFactory.java:96) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerPlayerInjector.updatePlayer(NetworkManagerPlayerInjector.java:69) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager$1.handleLogin(PacketFilterManager.java:463) ~[ProtocolLib (5).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1631]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:781) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:173) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:84) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1648) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[09:24:20 ERROR]: Couldn't place player in world
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2131) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2109) ~[?:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:280) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:215) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:196) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:84) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1648) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1631]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.0.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (5).jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2123) ~[?:?]
        ... 13 more
[09:24:21 INFO]: xxxx lost connection: Invalid player data

**Comment by Ingrim4** [comment]
Can you please create a protocol dump file using `/protocol dump` command on your server and send us the contents of the created dump file?

**Comment by gercsogamer** [comment]
> Can you please create a protocol dump file using `/protocol dump` command on your server and send us the contents of the created dump file?

Yes I send it here

[Uploading dump-2024-07-14_13.28.47.txt…]()

**Comment by Ingrim4** [comment]
Have you already tried the latest dev build of ProtocolLib that could fixe it: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by gercsogamer** [comment]
Sorry for not write for a long time, but our panel got hacked and deleted. Now almost everythings working fine but I got an error (but I can join)
[11:48:31 WARN]: java.net.UnknownHostException: s: Name or service not known
[11:48:31 WARN]:        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[11:48:31 WARN]:        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52)
[11:48:31 WARN]:        at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1211)
[11:48:31 WARN]:        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1828)
[11:48:31 WARN]:        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139)
[11:48:31 WARN]:        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
[11:48:31 WARN]:        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
[11:48:31 WARN]:        at java.base/java.net.InetAddress.getByName(InetAddress.java:1568)
[11:48:31 WARN]:        at IPLock.jar//net.c0dei.iplock.listener.PlayerLoginListener.onPlayerPreLogin(PlayerLoginListener.java:33)
[11:48:31 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source)
[11:48:31 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[11:48:31 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:48:31 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:48:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[11:48:31 WARN]:        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:417)
[11:48:31 WARN]:        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler$1.evaluate(ServerLoginPacketListenerImpl.java:414)
[11:48:31 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.util.Waitable.run(Waitable.java:24)
[11:48:31 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1571)
[11:48:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[11:48:31 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[11:48:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[11:48:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[11:48:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:48:31 INFO]: UUID of player gercso is 69cfb8f9-2610-3641-9650-403942c4699b
[11:48:32 INFO]: [TAB] [WARN] Player gercso's group (dev) is not in sorting list! Sorting list: owner,admin,mod,helper,builder,vip,default. Player will be sorted on the bottom.

**Comment by Ingrim4** [comment]
Don't know what's that about certainly isn't ProtocolLib. Error mentions something about a `IPLock.jar` maybe remove that.
