### ISSUE TITLE
ProtocolLib didn't load

### ISSUE THREAD

**Issue by TopazSlinky** [dmulloy2/ProtocolLib#3106]
[09:47:23] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:55)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:198)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:266)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
  	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:414)
  	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233)
  	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
  	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 0, banned: 0], return=Exact float, params=[{Type: match any: [interface net.minecraft.world.level.IMaterial], Index: null}]}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174)
  	at com.comphenix.protocol.utility.MinecraftReflection.getBlockClass(MinecraftReflection.java:1132)
  	at com.comphenix.protocol.reflect.StructureModifier.getDefaultGenerator(StructureModifier.java:83)
  	at com.comphenix.protocol.reflect.StructureModifier.<clinit>(StructureModifier.java:77)
  	... 14 more
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@27e8a72e[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@60dc610b
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@428092e8
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@6b98ee59
      server=CraftServer{serverName=CraftBukkit,serverVersion=3284a-Spigot-3892929-0ab8487,minecraftVersion=1.17.1}
      file=plugins/ProtocolLib (2).jar
      description=org.bukkit.plugin.PluginDescriptionFile@20d6bbd0
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@329e6060
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@4a41ba5f
    ]
  Version:
    ProtocolLib v4.3.0
  Java Version:
    17.0.6
  Server:
    3284a-Spigot-3892929-0ab8487 (MC: 1.17.1)

**Comment by TopazSlinky** [comment]
at start up i recived this error and i don't know how to resolve it

**Comment by Ingrim4** [comment]
Your version of ProtocolLib is outdated, can you please try the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
