### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by MrLouisDew** [dmulloy2/ProtocolLib#3107]
- [ ] This issue is not solved in a development build

**Describe the bug**
Error: 

```
[19:18:17] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[19:18:17] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[19:18:18] [Server thread/ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[19:18:18] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib (11).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib (11).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib (11).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib (11).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib (11).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib (11).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib (11).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:549)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@113d4c5c[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@113687a6
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6a927670
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@58697fd5
      server=CraftServer{serverName=Purpur,serverVersion=1.21-2258-ff19bcc,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib (11).jar
      description=org.bukkit.plugin.PluginDescriptionFile@8e173b6
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@8e173b6
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib (11).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@63c60676
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@7d8064fb
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-2258-ff19bcc (MC: 1.21)

```

**To Reproduce**
1. None

**Expected behavior**
ProtocolLib just loads

**Version Info**
ProtocolLib v5.2.0-SNAPSHOT-679

**Comment by cmetanka75911main** [comment]
Same here

**Comment by Jeppa** [comment]
Please have a look at all those other with the same error...
You have to update!

**Comment by Readopted** [comment]
> Please have a look at all those others with the same error... You have to update!

I am literally running the latest version.

**Comment by Jeppa** [comment]
The first line in your bug report: "This issue is not solved in a development build"  (while you didn't mark it.. ok)

Latest development build is build 723.
Your build is 679.
723 - 679 = 44 builds behind  --> so, you're outdated ! ;)

**Comment by Ingrim4** [comment]
@Jeppa, thank you for addressing the issues. I appreciate your effort. In the future, could you please provide the update link directly? Here's the link for reference: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/. Some users might not be familiar with GitHub or might find it easier to have the link readily available.

**Comment by Jeppa** [comment]
I know what you mean, but... those users made it here, good so far!
So the link is on the main page and they just have to read.

And I'm not sure if spoon feeding is the best solution.
Maybe "issue -> reading -> understanding -> trying -> working!"
is more usable than 
"issue -> asking -> spoonfeeding" ;)
