### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by Anuls** [dmulloy2/ProtocolLib#3112]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:435)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232)
  	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@2f2bb265[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@475d811a
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3597ab0e
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@1ada154
      server=CraftServer{serverName=CraftBukkit,serverVersion=4149-Spigot-e2c1eee-4e7d749,minecraftVersion=1.20.6}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5aeae0d5
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@558bef20
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@51f0f621
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    4149-Spigot-e2c1eee-4e7d749 (MC: 1.20.6)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
