### ISSUE TITLE
Bug in starting

### ISSUE THREAD

**Issue by Oleh2010** [dmulloy2/ProtocolLib#3136]
Hello, I have a problem starting the server, I have plugins that require protocollib and when starting it gives an error, I don’t know what this is connected with, here is the server log

> [10:49:08 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
> [10:49:08 WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
> [10:49:09 ERROR]: [ProtocolLib] Assuming package version: v1_20_R1
> [10:49:09 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
>   If this problem hasn't already been reported, please open a ticket
>   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
>   Stack Trace:
>   java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
>         at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
>         at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
>         at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
>         at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
>         at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
>         at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
>         at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
>         at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
>         at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
>         at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
>         at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
>         at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320)
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150)
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
>         at java.base/java.lang.Thread.run(Thread.java:1583)
>   Dump:
>   Parameters: 
>     [NULL]
>   Sender:
>     com.comphenix.protocol.ProtocolLib@65bc1557[
>       statistics=<null>
>       packetTask=<null>
>       tickCounter=0
>       configExpectedMod=-1
>       updater=com.comphenix.protocol.updater.SpigotUpdater@3a3b4512
>       redirectHandler=<null>
>       scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3fa8e9af
>       commandProtocol=<null>
>       commandPacket=<null>
>       commandFilter=<null>
>       packetLogging=<null>
>       skipDisable=false
>       isEnabled=false
>       loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@182bd8e2
>       server=CraftServer{serverName=Purpur,serverVersion=1.20.6-2233-0d6766e,minecraftVersion=1.20.6}
>       file=plugins/.paper-remapped/ProtocolLib (1).jar
>       description=org.bukkit.plugin.PluginDescriptionFile@66334163
>       pluginMeta=org.bukkit.plugin.PluginDescriptionFile@66334163
>       dataFolder=plugins/ProtocolLib
>       classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib (1).jar}
>       naggable=true
>       newConfig=YamlConfiguration[path='', root='YamlConfiguration']
>       configFile=plugins/ProtocolLib/config.yml
>       logger=com.destroystokyo.paper.utils.PaperPluginLogger@27473b77
>       lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@596efa5e
>       allowsLifecycleRegistration=true
>     ]
>   Version:
>     ProtocolLib v5.2.0-SNAPSHOT-679
>   Java Version:
>     21.0.2
>   Server:
>     1.20.6-2233-0d6766e (MC: 1.20.6)

**Comment by Oleh2010** [comment]
Sorry, i use 5.2.0. I close ticket
