### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by servicomcr** [dmulloy2/ProtocolLib#3146]
[19:07:42 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[19:07:42 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[19:07:47 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[19:07:47 ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:560)
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326)
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
at java.base/java.lang.Thread.run(Thread.java:1583)
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@4fece2a8[
statistics=<null>
packetTask=<null>
tickCounter=0
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@41428b16
redirectHandler=<null>
scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6913d834
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@120e8439
server=CraftServer{serverName=Purpur,serverVersion=1.21-2272-b2d1fea,minecraftVersion=1.21}
file=plugins/.paper-remapped/ProtocolLib (1).jar
description=org.bukkit.plugin.PluginDescriptionFile@3ea048aa
pluginMeta=org.bukkit.plugin.PluginDescriptionFile@3ea048aa
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib (1).jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@15dfb043
lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@6d87fbda
allowsLifecycleRegistration=true
]
Version:
ProtocolLib v5.2.0-SNAPSHOT-679
Java Version:
21.0.4
Server:
1.21-2272-b2d1fea (MC: 1.21)

**Comment by isArkaDarkTime** [comment]
I, too, have this problem! @dmulloy2 please update protocollib!

**Comment by isArkaDarkTime** [comment]
> I, too, have this problem! @dmulloy2 please update protocollib!

@servicomcr I downloaded last build from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/ and this help!

**Comment by legan100** [comment]
I have the same error. 
My server come from the nativ version 1.20.4 and I would like to update on the 1.21. on the new version I have this error. 
I used the Last Successful Build from jenkins. This didn't work. The same Error. I deleted the directory of the Plugin. Also the same error.
