### ISSUE TITLE
INTERNAL ERROR: Cannot load ProtocolLib

### ISSUE THREAD

**Issue by karkit7117** [dmulloy2/ProtocolLib#3149]
- [ v5.2.0-SNAPSHOT-679 ] This issue is not solved in a development build

**Describe the bug**
```
[12:53:31 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[12:53:32 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[12:53:36 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[12:53:36 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
        at java.base/java.lang.Thread.run(Thread.java:1570)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@57311e23[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@3f30afde
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@602f6e1d
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@67f3d019
      server=CraftServer{serverName=Paper,serverVersion=1.21-109-5a5035b,minecraftVersion=1.21}
      file=plugins\.paper-remapped\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7d836501
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7d836501
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@3341d5a
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@5b189bbf
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    22.0.1
  Server:
    1.21-109-5a5035b (MC: 1.21)

```

**Comment by Grosslukass** [comment]
Updating should fix the problem!

Use v5.3 for >= 1.20.5

![Screenshot 2024-07-28 205021](https://github.com/user-attachments/assets/b7f04608-3e21-4ad0-a4b6-7175e57f16a2)

https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by karkit7117** [comment]
> Updating should fix the problem!
> 
> Use v5.3 for >= 1.20.5
> 
> ![Screenshot 2024-07-28 205021](https://private-user-images.githubusercontent.com/34681399/352860948-b7f04608-3e21-4ad0-a4b6-7175e57f16a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTgyODQsIm5iZiI6MTcyMjI1Nzk4NCwicGF0aCI6Ii8zNDY4MTM5OS8zNTI4NjA5NDgtYjdmMDQ2MDgtM2UyMS00YWQwLWE0YjYtNzE3NWU1N2YxNmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEyNTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NjY1YzU1Y2YwMjBhMTNmMDRkZGJiODI1YzkyODYwOWQ0M2Y3MGFjMDgzODk2NzUzMTdkNWI0Njc2ODI5NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WburKM_HHG8Tbibgd3efYLv5WtM41TRgmP-E2xxY3E0)
> 
> https://ci.dmulloy2.net/job/ProtocolLib/

tnx . it's work
