### ISSUE TITLE
[MC 1.21] Error sending packet clientbound/minecraft:set_objective (skippable? false)

### ISSUE THREAD

**Issue by Reneshiii** [dmulloy2/ProtocolLib#3154]
I use Minecraft Paper Version 1.21. I installed ProtocolLib #726. If i try to join my server, i get kicked. If i delete ProtocolLib, i can join the server. If i paste plugins in the console, ProtocolLib is marked as green. This is the error i get, if I join the Server:

Error sending packet clientbound/minecraft:set_objective (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_objective'
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:762) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at TAB v4.1.6.jar/me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.6.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib (1).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib (1).jar:?]
        at ProtocolLib (1).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib (1).jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at ProtocolLib (1).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib (1).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class java.lang.Object cannot be cast to class net.minecraft.network.chat.numbers.NumberFormat (java.lang.Object is in module java.base of loader 'bootstrap'; net.minecraft.network.chat.numbers.NumberFormat is in unnamed module of loader java.net.URLClassLoader @41cf53f9)
        at net.minecraft.network.codec.StreamCodec$6.encode(StreamCodec.java:104) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:363) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:353) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.protocol.game.ClientboundSetObjectivePacket.write(ClientboundSetObjectivePacket.java:57) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.21.jar:1.21-66-99ae7bb]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.21.jar:1.21-66-99ae7bb]
        ... 45 more

**Comment by Ingrim4** [comment]
Can you please create a protocol dump file using `/protocol dump` command on your server and send us the contents of the created dump file?

**Comment by Reneshiii** [comment]
ProtocolLib Dump
Timestamp: 07/29/24 21:20:15

ProtocolLib Version: ProtocolLib v5.3.0-SNAPSHOT-726
Bukkit Version: 1.21-R0.1-SNAPSHOT
Server Version: 1.21-66-99ae7bb (MC: 1.21)
Java Version: 21.0.3

ProtocolLib: com.comphenix.protocol.ProtocolLib@1e6f93cd[
  statistics=com.comphenix.protocol.metrics.Statistics@492c146e
  packetTask=com.comphenix.protocol.scheduler.DefaultTask@326d08e8
  tickCounter=379209
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@4761bef9
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@25f2ac23
  scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@c545397
  commandProtocol=com.comphenix.protocol.CommandProtocol@562420bd
  commandPacket=com.comphenix.protocol.CommandPacket@1c78daf6
  commandFilter=com.comphenix.protocol.CommandFilter@2cdbfeee
  packetLogging=com.comphenix.protocol.PacketLogging@23dd809
  skipDisable=false
  isEnabled=true
  loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@75eb313b
  server=CraftServer{serverName=Paper,serverVersion=1.21-66-99ae7bb,minecraftVersion=1.21}
  file=plugins/ProtocolLib (1).jar
  description=org.bukkit.plugin.PluginDescriptionFile@5c414d89
  pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5c414d89
  dataFolder=plugins/ProtocolLib
  classLoader=PluginClassLoader{plugin=ProtocolLib v5.3.0-SNAPSHOT-726, pluginEnabled=true, url=plugins/ProtocolLib (1).jar}
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=com.destroystokyo.paper.utils.PaperPluginLogger@1c9eb640
  lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@448851f3
  allowsLifecycleRegistration=false
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@127371ee[
  plugin=ProtocolLib v5.3.0-SNAPSHOT-726
  server=CraftServer{serverName=Paper,serverVersion=1.21-66-99ae7bb,minecraftVersion=1.21}
  reporter=com.comphenix.protocol.ProtocolLib$1@234e14c3
  minecraftVersion=(MC: 1.21.0)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@4a0b8a5c
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4c0a4d27
  mainThreadPacketTypes=com.comphenix.protocol.concurrent.PacketTypeListenerSet@45ffb949
  inboundListeners=com.comphenix.protocol.injector.collection.InboundPacketListenerSet@16445539
  outboundListeners=com.comphenix.protocol.injector.collection.OutboundPacketListenerSet@b64c7
  registeredListeners=[com.r4g3baby.simplescore.scoreboard.listeners.PacketListener@30395c29, PacketAdapter[plugin=RealisticSeasons, sending=ListeningWhitelist[priority=NORMAL, packets=[MULTI_BLOCK_CHANGE[class=ClientboundSectionBlocksUpdatePacket, id=73]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=RealisticSeasons, sending=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_CHANGE[class=ClientboundBlockUpdatePacket, id=9]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@23044e77, PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=ClientboundSetEntityDataPacket, id=88]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=ServerboundChatPacket, id=6], CHAT_COMMAND[class=ServerboundChatCommandPacket, id=4]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=ClientboundLoginDisconnectPacket, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=ServerboundSignUpdatePacket, id=53]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=62]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_HEAD_ROTATION[class=ClientboundRotateHeadPacket, id=72], REL_ENTITY_MOVE_LOOK[class=PosRot, id=47], ENTITY_LOOK[class=Rot, id=48], ENTITY_TELEPORT[class=ClientboundTeleportEntityPacket, id=112]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST]]
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@1e767294
  debug=false
  closed=false
  injected=true
]

Listeners:
com.r4g3baby.simplescore.scoreboard.listeners.PacketListener@30395c29[
  protocolLibPlugin=ProtocolLib v5.3.0-SNAPSHOT-726
  sendingPackets=ListeningWhitelist[priority=HIGHEST, packets=[SCOREBOARD_DISPLAY_OBJECTIVE[class=ClientboundSetDisplayObjectivePacket, id=87], SCOREBOARD_OBJECTIVE[class=ClientboundSetObjectivePacket, id=94]], gamephase=PLAYING, options=[]]
  afterTrailsAndTailsDot2Update=true
]
me.casperge.realisticseasons.event.ChunkPacketEventProtocolLibAsync$2@2ad36003[
  plugin=RealisticSeasons v11.0.2
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[MULTI_BLOCK_CHANGE[class=ClientboundSectionBlocksUpdatePacket, id=73]], gamephase=PLAYING, options=[]]
]
me.casperge.realisticseasons.event.ChunkPacketEventProtocolLibAsync$1@4aad42df[
  plugin=RealisticSeasons v11.0.2
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[BLOCK_CHANGE[class=ClientboundBlockUpdatePacket, id=9]], gamephase=PLAYING, options=[]]
]
com.comphenix.protocol.async.NullPacketListener@23044e77[
  sendingWhitelist=ListeningWhitelist[priority=LOW, packets=[MAP_CHUNK[class=ClientboundLevelChunkWithLightPacket, id=39]], gamephase=PLAYING, options=[ASYNC]]
  receivingWhitelist=ListeningWhitelist[priority=LOW, packets=[], gamephase=PLAYING, options=[ASYNC]]
  plugin=RealisticSeasons v11.0.2
]
net.citizensnpcs.ProtocolLibListener$1@51fe5b8[
  plugin=Citizens v2.0.35-SNAPSHOT (build 3477)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=ClientboundSetEntityDataPacket, id=88]], gamephase=PLAYING, options=[]]
]
litebans.as@2317376e[
  b=litebans.V@1b1ed288
  a=litebans.U@77b4852f
  e=litebans.Y@4fce9238
  c=litebans.aE@73718e39
  i=LiteBans v2.15.1
  plugin=LiteBans v2.15.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=ServerboundChatPacket, id=6], CHAT_COMMAND[class=ServerboundChatCommandPacket, id=4]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
litebans.gI@22be43d7[
  c=litebans.Y@4fce9238
  b=LiteBans v2.15.1
  plugin=LiteBans v2.15.1
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=ClientboundLoginDisconnectPacket, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
com.bencodez.votingplugin.advancedcore.api.valuerequest.sign.SignMenu$1@39877ffb[
  plugin=VotingPlugin v6.17
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=ServerboundSignUpdatePacket, id=53]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
net.citizensnpcs.ProtocolLibListener$2@184389de[
  plugin=Citizens v2.0.35-SNAPSHOT (build 3477)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=ClientboundPlayerInfoUpdatePacket, id=62]], gamephase=PLAYING, options=[ASYNC]]
]
net.citizensnpcs.ProtocolLibListener$3@63ef94b2[
  plugin=Citizens v2.0.35-SNAPSHOT (build 3477)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_HEAD_ROTATION[class=ClientboundRotateHeadPacket, id=72], REL_ENTITY_MOVE_LOOK[class=PosRot, id=47], ENTITY_LOOK[class=Rot, id=48], ENTITY_TELEPORT[class=ClientboundTeleportEntityPacket, id=112]], gamephase=PLAYING, options=[ASYNC]]
]

Plugins Using ProtocolLib:
RealisticSeasons by []
Citizens by [fullwall]
VotingPlugin by [BenCodez]
SimpleScore by [R4G3_BABY]
LiteBans by [Ruan]

**Comment by Ingrim4** [comment]
This error is most likely caused by [SimpleScore](https://github.com/r4g3baby/SimpleScore) please report this the author(s) of SimpleScore.
