### ISSUE TITLE
Unable To Find a Field That Matches

### ISSUE THREAD

**Issue by ImMalkah** [dmulloy2/ProtocolLib#3156]
- [ ] This issue is not solved in a development build
- [ ] In the console, it said to open a ticket with the following stack trace:

Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@77ababe7[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@faf2f0c
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@25f1498d
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3f3460f3
      server=CraftServer{serverName=Paper,serverVersion=1.21-109-5a5035b,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@453a13dd
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@453a13dd
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@344da09b
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@5a7c0b7a
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-109-5a5035b (MC: 1.21)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by ImMalkah** [comment]
using the latest build works, thank you very much! You guys have 1.21 as supported but the download on spigot gives the non-working version by default.

**Comment by Ingrim4** [comment]
![image](https://github.com/user-attachments/assets/0d7921d0-96b3-42aa-802d-683b44b82b6f)
It does state to use the latest dev build for 1.20.5+
