### ISSUE TITLE
Plugin disabled

### ISSUE THREAD

**Issue by FewerElk** [dmulloy2/ProtocolLib#3159]
- [ ] This issue is not solved in a development build

**Describe the bug**
The plugin is disabled when the server starts

**To Reproduce**
1. Install protocollib on a 1.21 paper server
2. launch it
3. Get it disabled

**Expected behavior**
I expected a plugin that isn't disabled

**Screenshots**
nr

**Version Info**
I think it is v5.2.0-SNAPSHOT-679, it is in the disabled plugin error

**Additional context**
Plugin list : 
![image](https://github.com/user-attachments/assets/72244da4-a660-48de-a7b4-ee419ba13c0d)

**Comment by waheedullahkhan001** [comment]
```
[07:41:23 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[07:41:23 WARN]: [ProtocolLib] Version (MC: 1.21.0) has not yet been tested! Proceed with caution.
[07:41:26 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[07:41:26 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
       at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
       at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
       at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
       at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
       at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
       at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
       at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
       at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
       at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
       at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
       at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
       at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
       at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
       at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
       at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
       at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@16bd0164[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@12390d6
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7feb07b7
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4c4cd0ce
      server=CraftServer{serverName=Paper,serverVersion=1.21-119-100d75a,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@1526503c
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@1526503c
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@5fa9c123
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@2beeeb91
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-119-100d75a (MC: 1.21)
```

**Comment by FewerElk** [comment]
So what is the problem ?

**Comment by waheedullahkhan001** [comment]
I was just posting the stack due to which it gets disabled (it's above in the logs). I am having the same issue.

**Comment by Jeppa** [comment]
You are outdated...
please update !

**Comment by FewerElk** [comment]
I haven't this traceback. It says something about a plugin loader not supported but I haven't any plugin like that.

**Comment by Jeppa** [comment]
Which version did you update to?

**Comment by FewerElk** [comment]
Lastest

**Comment by FewerElk** [comment]
Oh, I just downloaded the lastest version for the dev builds and not from spigot and it seems to be working 👀
