### ISSUE TITLE
Plugin does not start up: 

### ISSUE THREAD

**Issue by Vinnipapi** [dmulloy2/ProtocolLib#3170]
[15:40:06 INFO]: [PlayerAnimator] Enabling PlayerAnimator vR1.2.7
[15:40:06 ERROR]: Error occurred while enabling PlayerAnimator vR1.2.7 (Is it up to date?)
java.lang.IllegalStateException: Version not supported
        at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorImpl.applyNMS(PlayerAnimatorImpl.java:78) ~[oraxen-1.179.0.jar:?]
        at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorImpl.<init>(PlayerAnimatorImpl.java:49) ~[oraxen-1.179.0.jar:?]
        at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorImpl.initialize(PlayerAnimatorImpl.java:24) ~[oraxen-1.179.0.jar:?]
        at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorPluginImpl.onEnable(PlayerAnimatorPluginImpl.java:11) ~[oraxen-1.179.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:40:06 INFO]: [PlayerAnimator] Disabling PlayerAnimator vR1.2.7

On the Spigot Website says 1.21 ist tested in the latest build but it do not load...

**Comment by Ingrim4** [comment]
The error you provided has nothing to do with ProtocolLib as far as I see it so I'm going to close this. Please contact the author(s) of `PlayerAnimator` with your issue.
