### ISSUE TITLE
java.lang.IllegalStateException: Recursive update

### ISSUE THREAD

**Issue by JainaGam3r45** [dmulloy2/ProtocolLib#3177]
[16:23:18 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalStateException: Recursive update
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763)
        at com.comphenix.protocol.injector.StructureCache.canCreateInstance(StructureCache.java:86)
        at com.comphenix.protocol.reflect.StructureModifier.generateDefaultFields(StructureModifier.java:149)
        at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:119)
        at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:103)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:150)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:556)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getStreamCodec(PacketRegistry.java:571)
        at com.comphenix.protocol.injector.StructureCache.determineBestCreator(StructureCache.java:127)
        at com.comphenix.protocol.injector.StructureCache.lambda$canCreateInstance$0(StructureCache.java:87)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at com.comphenix.protocol.injector.StructureCache.canCreateInstance(StructureCache.java:86)
        at com.comphenix.protocol.reflect.StructureModifier.generateDefaultFields(StructureModifier.java:149)
        at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:119)
        at com.comphenix.protocol.reflect.StructureModifier.<init>(StructureModifier.java:103)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createOldRegister(PacketRegistry.java:150)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:556)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:604)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:112)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:179)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:388)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:225)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620)
        at java.base/java.lang.Thread.run(Thread.java:840)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@28002543[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@cf3be00
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@676d39d9
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@18487145
      server=CraftServer{serverName=WindSpigot,serverVersion=WindSpigot Release v2.1.2,minecraftVersion=1.8.8}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7827e8fb
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1b655c9a
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@7cd59117
    ]
  Version:
    ProtocolLib v5.3.0-SNAPSHOT-726
  Java Version:
    17.0.11
  Server:
    WindSpigot Release v2.1.2 (MC: 1.8.8)

**Comment by LeDiamantRouge** [comment]
Same issue with windspigot
