### ISSUE TITLE
not start plugin

### ISSUE THREAD

**Issue by aliakbartnt** [dmulloy2/ProtocolLib#3178]
- [ ] This issue is not solved in a development build

**its consol log**
[14:12:44] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[14:12:44] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.20.6) has not yet been tested! Proceed with caution.
[14:12:49] [Server thread/ERROR]: [ProtocolLib] Assuming package version: v1_20_R1
[14:12:50] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7fa90429[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@5ee9617d
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6956bec5
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@48b8e867
      server=CraftServer{serverName=Purpur,serverVersion=1.20.6-2233-0d6766e,minecraftVersion=1.20.6}
      file=plugins\.paper-remapped\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@663a4abf
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@663a4abf
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@171dc63a
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@6f823ed2
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    1.20.6-2233-0d6766e (MC: 1.20.6)

**help me i download lastest**

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by aliakbartnt** [comment]
thx its fix
