### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tobyansah12** [dmulloy2/ProtocolLib#3188]
Stack Trace:
--
182 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
183 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
184 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
185 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
186 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
187 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
188 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
189 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
190 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
191 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
192 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
193 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
194 | at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
195 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
196 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
197 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
198 | at java.base/java.lang.Thread.run(Thread.java:1583)
199 | Dump:
200 | Parameters:
201 | [NULL]
202 | Sender:
203 | com.comphenix.protocol.ProtocolLib@760bf74e[
204 | statistics=<null>
205 | packetTask=<null>
206 | tickCounter=0
207 | configExpectedMod=-1
208 | updater=com.comphenix.protocol.updater.SpigotUpdater@64c1f3ab
209 | redirectHandler=<null>
210 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4d59c9fa
211 | commandProtocol=<null>
212 | commandPacket=<null>
213 | commandFilter=<null>
214 | packetLogging=<null>
215 | skipDisable=false
216 | isEnabled=false
217 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@2a23a2f3
218 | server=CraftServer{serverName=Paper,serverVersion=1.21-130-b1b5d4c,minecraftVersion=1.21}
219 | file=plugins/.paper-remapped/ProtocolLib.jar
220 | description=org.bukkit.plugin.PluginDescriptionFile@7e2b0fd8
221 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7e2b0fd8
222 | dataFolder=plugins/ProtocolLib
223 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
224 | naggable=true
225 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
226 | configFile=plugins/ProtocolLib/config.yml
227 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@1735e69d
228 | lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@60c86643
229 | allowsLifecycleRegistration=true
230 | ]
231 | Version:
232 | ProtocolLib v5.2.0-SNAPSHOT-679
233 | Java Version:
234 | 21.0.3
235 | Server:
236 | 1.21-130-b1b5d4c (MC: 1.21)

Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:[183](https://exaroton.com/log/#L183))
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@760bf74e[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@64c1f3ab
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4d59c9fa
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@2a23a2f3
      server=CraftServer{serverName=Paper,serverVersion=1.21-130-b1b5d4c,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7e2b0fd8
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7e2b0fd8
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@1735e69d
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@60c86643
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-130-b1b5d4c (MC: 1.21)

**Comment by captainion2119** [comment]
Hey, i'm getting the same error, the plugin isn't loading...

> Here is my server log:
```
[15:58:06 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[15:58:06 WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[15:58:07 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[15:58:07 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:1130)
        at org.bukkit.Bukkit.reload(Bukkit.java:1027)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:59)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000)
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985)
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526)
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
        at java.base/java.lang.Thread.run(Unknown Source)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@153eccf1[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@5ed491bd
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@3d6e87d2
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@23109056
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-13-7c9240f,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@c545ef5
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@c545ef5
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@e9f2e36
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@6fbd319b
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    1.21.1-13-7c9240f (MC: 1.21.1)
```

Hope this gets solved soon

**Comment by GreeningSiren** [comment]
Use dev build on >= 1.20.5

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by tobyansah12** [comment]
thank you yes it was fixed.
