### ISSUE TITLE
Unknown dependency ProtocolLib. Please download and install ProtocolLib to run this plugin.

### ISSUE THREAD

**Issue by conaticus** [dmulloy2/ProtocolLib#3192]
Hi, for some reason ProtocolLib is not being recognised by spigot. The build step works fine however when running the spigot server it displays this error:
```
[18:43:53] [Server thread/ERROR]: Could not load 'plugins\CivServer.jar'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency ProtocolLib. Please download and install ProtocolLib to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:280) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:122) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:453) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4195-b-Spigot-f6a4805-6524758]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

I have ensured that the dependency and repository is in the pom.xml as well as in the plugin.yml. I have also ran the maven compile step.

I also tried upgrading to newer versions (as I am currently testing 5.1.0) by updating the dependency version to 5.2.0-SNAPSHOT etc, however these presented the exact same error. What could be happening here? Thanks in advance!

Minecraft/spigot version: 1.20.6
ProtocolLib version: 5.1.0 / 5.2.0-SNAPSHOT / 5.3.0-SNAPSHOT
Java version: 21

**Comment by conaticus** [comment]
Solved it today. Had to do the following:
- Upgrade the dependency version to `5.3.0-SNAPSHOT` in the `pom.xml`
- Move the ProtocolLib.jar from the 5.3.0 build into the plugins directory
