### ISSUE TITLE
Updated from 5.2 to 5.3, unable to use normally

### ISSUE THREAD

**Issue by ByOuHuang** [dmulloy2/ProtocolLib#3193]
My server version is Spigot 1.8.8 and the latest version is WaterFall, There are no errors on the server, showing connection reset

io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No enum constant net.md_5.bungee.protocol.packet.ScoreboardObjective.HealthDisplay.
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
        at io.netty.channel.AbstractChannelHandlerContext

**Comment by Ingrim4** [comment]
Can you please create a protocol dump file using `/protocol dump` command on your server and send us the contents of the created dump file?

**Comment by ByOuHuang** [comment]
ProtocolLib Dump
Timestamp: 08/19/24 12:50:37

ProtocolLib Version: ProtocolLib v5.3.0-SNAPSHOT
Bukkit Version: 1.8.8-R0.1-SNAPSHOT
Server Version: git-PaperSpigot-445 (MC: 1.8.8)
Java Version: 11.0.24

ProtocolLib: com.comphenix.protocol.ProtocolLib@2cedfb1a[
  statistics=com.comphenix.protocol.metrics.Statistics@e482cc0
  packetTask=com.comphenix.protocol.scheduler.DefaultTask@6ef3c4ce
  tickCounter=4363
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@61c89e1e
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@22be9c16
  scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6d5f8aad
  commandProtocol=com.comphenix.protocol.CommandProtocol@1dfae67c
  commandPacket=com.comphenix.protocol.CommandPacket@3867b3b3
  commandFilter=com.comphenix.protocol.CommandFilter@6e6fd685
  packetLogging=com.comphenix.protocol.PacketLogging@7ff42307
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@20c307cf
  server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-445,minecraftVersion=1.8.8}
  file=plugins/[P]ProtocolLib1.jar
  description=org.bukkit.plugin.PluginDescriptionFile@7410fb6d
  dataFolder=plugins/ProtocolLib
  classLoader=org.bukkit.plugin.java.PluginClassLoader@1e13cd1b
  naggable=true
  ebean=<null>
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=org.bukkit.plugin.PluginLogger@3d89d64f
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@4cafaa89[
  plugin=ProtocolLib v5.3.0-SNAPSHOT
  server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-445,minecraftVersion=1.8.8}
  reporter=com.comphenix.protocol.ProtocolLib$1@3f97fbe2
  minecraftVersion=(MC: 1.8.8)
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@589ee632
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2b5668c0
  mainThreadPacketTypes=com.comphenix.protocol.concurrent.PacketTypeListenerSet@1a9c74c1
  inboundListeners=com.comphenix.protocol.injector.collection.InboundPacketListenerSet@1ad4d49b
  outboundListeners=com.comphenix.protocol.injector.collection.OutboundPacketListenerSet@35540e85
  registeredListeners=[PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=6]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=Core, sending=ListeningWhitelist[priority=LOWEST, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=16]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=PacketPlayInChat, id=6]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=62]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Core, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOWEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=11]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=72], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=48]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Citizens, sending=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=88]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@2ddc7087
  debug=false
  closed=false
  injected=true
]

Listeners:
litebans.as@36d1eaf2[
  b=litebans.V@541f2381
  a=litebans.U@68d35595
  e=litebans.Y@7d664e2c
  c=litebans.aE@3370514f
  i=LiteBans v2.15.1
  plugin=LiteBans v2.15.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=6]], gamephase=PLAYING, options=[ASYNC]]
  sendingWhitelist=EMPTY_WHITELIST
]
core.bukkit.module.nick.NickTab@1c66a2c2[
  protocolManager=com.comphenix.protocol.injector.PacketFilterManager@4cafaa89
  playerManage=core.bukkit.manage.PlayerManage@7f8f0a43
  targetName={}
  plugin=Core v1.0.0-SNAPSHOT
  connectionSide=BOTH
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[CHAT[class=PacketPlayInChat, id=6]], gamephase=PLAYING, options=[]]
  sendingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=16]], gamephase=PLAYING, options=[]]
]
net.citizensnpcs.ProtocolLibListener$2@258fece8[
  plugin=Citizens v2.0.32-SNAPSHOT (build 3124)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=62]], gamephase=PLAYING, options=[]]
]
core.bukkit.module.antitab.AntiTabAdapter@221ce0a[
  antiTab=[core.bukkit.entity.anticommand.AntiTab@1cf3efcf, core.bukkit.entity.anticommand.AntiTab@171c7a0]
  protocolManager=com.comphenix.protocol.injector.PacketFilterManager@4cafaa89
  plugin=Core v1.0.0-SNAPSHOT
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=LOWEST, packets=[TAB_COMPLETE[class=PacketPlayInTabComplete, id=11]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
net.citizensnpcs.ProtocolLibListener$3@662b9e55[
  plugin=Citizens v2.0.32-SNAPSHOT (build 3124)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=MONITOR, packets=[ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=72], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=48]], gamephase=PLAYING, options=[]]
]
litebans.gI@61b9bd46[
  c=litebans.Y@7d664e2c
  b=LiteBans v2.15.1
  plugin=LiteBans v2.15.1
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]]
]
net.citizensnpcs.ProtocolLibListener$1@636ba934[
  plugin=Citizens v2.0.32-SNAPSHOT (build 3124)
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=88]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
Citizens by [fullwall]
LiteBans by [Ruan]
Core by [Core Team]
