### ISSUE TITLE
Plug-ins cannot be loaded at Leaves1.21.1

### ISSUE THREAD

**Issue by BZxmxs** [dmulloy2/ProtocolLib#3199]
no
Report an error：
[20:04:10 信息]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[20:04:10 警告]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[20:04:12 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[20:04:12 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:550)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:296)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
        at java.base/java.lang.Thread.run(Thread.java:1570)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@e6e09db[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@19166bf4
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@67c889dc
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7ed9652a
      server=CraftServer{serverName=Leaves,serverVersion=1.21.1-53-595afb8,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4864746e
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4864746e
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@398d48ad
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@43217ad9
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    22.0.2
  Server:
    1.21.1-53-595afb8 (MC: 1.21.1)

**Comment by aysaoif** [comment]
bump!

```<html>
<body>
<!--StartFragment-->
[20:41:16] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
--
38 | [20:41:18] [Server thread/ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
39 | [20:41:18] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
40 | If this problem hasn't already been reported, please open a ticket
41 | at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
42 | Stack Trace:
43 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
44 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
45 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
46 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
47 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
48 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
49 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
50 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
51 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
52 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
53 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
54 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
55 | at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
56 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
57 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
58 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
59 | at java.base/java.lang.Thread.run(Thread.java:1583)
60 | Dump:
61 | Parameters:
62 | [NULL]
63 | Sender:
64 | com.comphenix.protocol.ProtocolLib@bb068f[
65 | statistics=<null>
66 | packetTask=<null>
67 | tickCounter=0
68 | configExpectedMod=-1
69 | updater=com.comphenix.protocol.updater.SpigotUpdater@4be4d0af
70 | redirectHandler=<null>
71 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@13332822
72 | commandProtocol=<null>
73 | commandPacket=<null>
74 | commandFilter=<null>
75 | packetLogging=<null>
76 | skipDisable=false
77 | isEnabled=false
78 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7958722f
79 | server=CraftServer{serverName=Paper,serverVersion=1.21.1-40-2fdb2e9,minecraftVersion=1.21.1}
80 | file=plugins/.paper-remapped/ProtocolLib.jar
81 | description=org.bukkit.plugin.PluginDescriptionFile@7230c0eb
82 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7230c0eb
83 | dataFolder=plugins/ProtocolLib
84 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
85 | naggable=true
86 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
87 | configFile=plugins/ProtocolLib/config.yml
88 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@2c140885
89 | lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@1e43553d
90 | allowsLifecycleRegistration=true
91 | ]
92 | Version:
93 | ProtocolLib v5.2.0-SNAPSHOT-679
94 | Java Version:
95 | 21.0.3
96 | Server:
97 | 1.21.1-40-2fdb2e9 (MC: 1.21.1)

<!--EndFragment-->
</body>
</html>[20:41:16] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[20:41:18] [Server thread/ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[20:41:18] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:[39](https://exaroton.com/log/#L39))
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:[40](https://exaroton.com/log/#L40))
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@bb068f[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4be4d0af
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@13332822
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7958722f
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-40-2fdb2e9,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7230c0eb
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7230c0eb
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@2c140885
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@1e[43](https://exaroton.com/log/#L43)553d
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21.1-40-2fdb2e9 (MC: 1.21.1)```

**Comment by Jan280808** [comment]
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3b53966b[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@587ca222
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7fbb9788
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@7d7e999d
      server=CraftServer{serverName=Paper,serverVersion=1.21-130-b1b5d4c,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@46c5675f
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@46c5675f
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@105cfeea
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@22bd2f3b
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21-130-b1b5d4c (MC: 1.21)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
