### ISSUE TITLE
Error Cannot enable ProtocolLib

### ISSUE THREAD

**Issue by TheKillHDmc** [dmulloy2/ProtocolLib#320]
Hello, when i try to load the plugin ( 4.2.1 and 4.2.0 ) i have this error

[23:26:41] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.2.1
[23:26:41] [Server thread/INFO]: Error Cannot enable ProtocolLib. (java.lang.LinkageError: loader constraint violation: when resolving method "com.comphenix.protocol.ProtocolLibrary.getErrorReporter()Lcom/comphenix/protocol/error/ErrorReporter;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/comphenix/protocol/utility/MinecraftReflection, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/comphenix/protocol/ProtocolLibrary, have different Class objects for the type com/comphenix/protocol/error/ErrorReporter used in the signature) occured in ProtocolLib v4.2.1.[m
[23:26:41] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.LinkageError: loader constraint violation: when resolving method "com.comphenix.protocol.ProtocolLibrary.getErrorReporter()Lcom/comphenix/protocol/error/ErrorReporter;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/comphenix/protocol/utility/MinecraftReflection, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/comphenix/protocol/ProtocolLibrary, have different Class objects for the type com/comphenix/protocol/error/ErrorReporter used in the signature
  	at com.comphenix.protocol.utility.MinecraftReflection.getClassSource(MinecraftReflection.java:2012)
  	at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:1978)
  	at com.comphenix.protocol.utility.MinecraftReflection.getCraftEntityClass(MinecraftReflection.java:1786)
  	at com.comphenix.protocol.utility.MinecraftReflection.handleLibigot(MinecraftReflection.java:290)
  	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftPackage(MinecraftReflection.java:219)
  	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1990)
  	at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:745)
  	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:289)
  	at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
  	at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
  	at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:387)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
  	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363)
  	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
  	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
  	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
  	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
  	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
  	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
  	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
  	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
  	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
  	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
  	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
  	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
  	at java.lang.Thread.run(Thread.java:745)
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@359a3c16[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@67125d6
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7f0259a7
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@3c644061
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-"8b18730",minecraftVersion=1.8.8}
      file=plugins/ProtocolLib (13).jar
      description=org.bukkit.plugin.PluginDescriptionFile@5d875d20
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@24c6e792
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@5ef4a36b
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_71
  Server:
    git-PaperSpigot-"8b18730" (MC: 1.8.8)

[23:26:41] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.2.1

**Comment by dmulloy2** [comment]
Does this occur during standard startup, i.e. no reloads, plugin loaders, etc?

**Comment by dmulloy2** [comment]
Any more info on this?
