### ISSUE TITLE
Error Occuring on 1.21 Paper Server. Plz Fix this

### ISSUE THREAD

**Issue by abusuhan26** [dmulloy2/ProtocolLib#3213]
**Version Info**
```
<html>
<body>
<!--StartFragment-->
Stack Trace:
--
132 | java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
133 | at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
134 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
135 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
136 | at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
137 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
138 | at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
139 | at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
140 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
141 | at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
142 | at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
143 | at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
144 | at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
145 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
146 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
147 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
148 | at java.base/java.lang.Thread.run(Thread.java:1570)
149 | Dump:
150 | Parameters:
151 | [NULL]
152 | Sender:
153 | com.comphenix.protocol.ProtocolLib@6c645ec0[
154 | statistics=<null>
155 | packetTask=<null>
156 | tickCounter=0
157 | configExpectedMod=-1
158 | updater=com.comphenix.protocol.updater.SpigotUpdater@5ea3f72d
159 | redirectHandler=<null>
160 | scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@107f3067
161 | commandProtocol=<null>
162 | commandPacket=<null>
163 | commandFilter=<null>
164 | packetLogging=<null>
165 | skipDisable=false
166 | isEnabled=false
167 | loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@770c58f2
168 | server=CraftServer{serverName=Paper,serverVersion=1.21.1-52-e08e667,minecraftVersion=1.21.1}
169 | file=plugins/.paper-remapped/ProtocolLib.jar
170 | description=org.bukkit.plugin.PluginDescriptionFile@6aa0992e
171 | pluginMeta=org.bukkit.plugin.PluginDescriptionFile@6aa0992e
172 | dataFolder=plugins/ProtocolLib
173 | classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
174 | naggable=true
175 | newConfig=YamlConfiguration[path='', root='YamlConfiguration']
176 | configFile=plugins/ProtocolLib/config.yml
177 | logger=com.destroystokyo.paper.utils.PaperPluginLogger@4fdffab7
178 | lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@684b60e7
179 | allowsLifecycleRegistration=true
180 | ]
181 | Version:
182 | ProtocolLib v5.2.0-SNAPSHOT-679
183 | Java Version:
184 | 22.0.2
185 | Server:
186 | 1.21.1-52-e08e667 (MC: 1.21.1)

<!--EndFragment-->
</body>
</html>
```

Help to fix this 
Make support for 1.21 Servers

**Comment by rayanbzd** [comment]
Try latest dev build here: https://ci.dmulloy2.net/job/ProtocolLib/
