### ISSUE TITLE
Server keeps disabling ProtocolLib

### ISSUE THREAD

**Issue by 6alpha9** [dmulloy2/ProtocolLib#3221]
running Ubuntu 24.04.1 LTS.

Here is step by step installation:

$ java --version
 openjdk 21.0.4 2024-07-16
 OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
 OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)

$ sudo wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
--2024-09-05 22:01:14--  https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
Resolving hub.spigotmc.org (hub.spigotmc.org)... 104.27.195.95, 104.27.196.95, 2606:4700:21::681b:c35f, ...
Connecting to hub.spigotmc.org (hub.spigotmc.org)|104.27.195.95|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3445743 (3.3M) [application/java-archive]
Saving to: ‘BuildTools.jar’

BuildTools.jar                100%[===============================================>]   3.29M  13.0MB/s    in 0.3s

2024-09-05 22:01:15 (13.0 MB/s) - ‘BuildTools.jar’ saved [3445743/3445743]

$ ls
BuildTools.jar

$ java -jar BuildTools.jar
Total Time: 2 minutes 37 seconds

Success! Everything completed successfully. Copying final .jar files now.
Copying spigot-1.21.1-R0.1-SNAPSHOT-bootstrap.jar to /home/misos/mc/spigot-1.21.1.jar
  - Saved as ./spigot-1.21.1.jar

$ ls
apache-maven-3.9.6  BuildTools.jar      Bukkit       Spigot             work
BuildData           BuildTools.log.txt  CraftBukkit  spigot-1.21.1.jar

$ sudo rm BuildTools.jar

$ java -Xmx2G -Xms1G -jar spigot-1.21.1.jar nogui

$ nano eula.txt

$ java -Xmx2G -Xms1G -jar spigot-1.21.1.jar nogui

>stop

$ cd plugins

$ sudo wget https://github.com/dmulloy2/ProtocolLib/releases/download/5.2.0/ProtocolLib.jar

$ cd ..

$ sudo java -Xmx2G -Xms1G -jar spigot-1.21.1.jar nogui
Unbundling libraries to /home/misos/mc/bundler
Starting server
Loading libraries, please wait...
[23:13:48] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[23:13:49] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[23:13:49] [ServerMain/INFO]: No existing world data, creating new world
[23:13:50] [ServerMain/INFO]: Loaded 1290 recipes
[23:13:48] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[23:13:49] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[23:13:49] [ServerMain/INFO]: No existing world data, creating new world
[23:13:50] [ServerMain/INFO]: Loaded 1290 recipes
[23:13:50] [Server thread/INFO]: Starting minecraft server version 1.21.1
[23:13:50] [Server thread/INFO]: Loading properties
[23:13:50] [Server thread/INFO]: This server is running CraftBukkit version 4306-Spigot-a759b62-bd8aded (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[23:13:51] [Server thread/INFO]: *** This version of Spigot contains changes to some enums. If you notice that plugins no longer work after updating, please report this to the developers of those plugins first. ***
[23:13:51] [Server thread/INFO]: *** If you cannot update those plugins, you can try setting `settings.compatibility.enum-compatibility-mode` to `true` in `bukkit.yml`. ***
[23:13:51] [Server thread/INFO]: Server Ping Player Sample Count: 12
[23:13:51] [Server thread/INFO]: Using 4 threads for Netty based IO
[23:13:51] [Server thread/INFO]: Debug logging is disabled
[23:13:51] [Server thread/INFO]: Default game type: SURVIVAL
[23:13:51] [Server thread/INFO]: Generating keypair
[23:13:51] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:13:51] [Server thread/INFO]: Using epoll channel type
[23:13:51] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.2.0-SNAPSHOT-679
[23:13:51] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[23:13:53] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:469)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236)
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@74dd2d54[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@427bca54
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@5f51f8c2
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@c17a14c
      server=CraftServer{serverName=CraftBukkit,serverVersion=4306-Spigot-a759b62-bd8aded,minecraftVersion=1.21.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@3a6bbb4c
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@7ecbbfcf
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@2bf9d410
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.4
  Server:
    4306-Spigot-a759b62-bd8aded (MC: 1.21.1)

[23:13:53] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[23:13:53] [Server thread/ERROR]: ******************************************************
[23:13:53] [Server thread/ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[23:13:53] [Server thread/ERROR]: *** Please use the built-in reload command!        ***
[23:13:53] [Server thread/ERROR]: ******************************************************
[23:13:53] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679
[23:13:53] [Server thread/INFO]: Preparing level "world"
[23:13:53] [Server thread/INFO]: -------- World Settings For [world] --------
[23:13:53] [Server thread/INFO]: View Distance: 10
[23:13:53] [Server thread/INFO]: Simulation Distance: 10
[23:13:53] [Server thread/INFO]: Item Despawn Rate: 6000
[23:13:53] [Server thread/INFO]: Item Merge Radius: 2.5
[23:13:53] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[23:13:53] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[23:13:53] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[23:13:53] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[23:13:53] [Server thread/INFO]: Experience Merge Radius: 3.0
[23:13:53] [Server thread/INFO]: Mob Spawn Range: 6
[23:13:53] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[23:13:53] [Server thread/INFO]: Max TNT Explosions: 100
[23:13:53] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[23:13:53] [Server thread/INFO]: Cactus Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Cane Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Melon Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Sapling Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Carrot Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Potato Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Wheat Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Vine Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Kelp Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[23:13:53] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[23:13:53] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[23:13:53] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[23:13:55] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[23:13:55] [Server thread/INFO]: View Distance: 10
[23:13:55] [Server thread/INFO]: Simulation Distance: 10
[23:13:55] [Server thread/INFO]: Item Despawn Rate: 6000
[23:13:55] [Server thread/INFO]: Item Merge Radius: 2.5
[23:13:55] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[23:13:55] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[23:13:55] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[23:13:55] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[23:13:55] [Server thread/INFO]: Experience Merge Radius: 3.0
[23:13:55] [Server thread/INFO]: Mob Spawn Range: 6
[23:13:55] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[23:13:55] [Server thread/INFO]: Max TNT Explosions: 100
[23:13:55] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[23:13:55] [Server thread/INFO]: Cactus Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Cane Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Melon Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Sapling Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Carrot Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Potato Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Wheat Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Vine Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Kelp Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[23:13:55] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[23:13:55] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[23:13:55] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[23:13:55] [Server thread/INFO]: View Distance: 10
[23:13:55] [Server thread/INFO]: Simulation Distance: 10
[23:13:55] [Server thread/INFO]: Item Despawn Rate: 6000
[23:13:55] [Server thread/INFO]: Item Merge Radius: 2.5
[23:13:55] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[23:13:55] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[23:13:55] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[23:13:55] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[23:13:55] [Server thread/INFO]: Experience Merge Radius: 3.0
[23:13:55] [Server thread/INFO]: Mob Spawn Range: 6
[23:13:55] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[23:13:55] [Server thread/INFO]: Max TNT Explosions: 100
[23:13:55] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[23:13:55] [Server thread/INFO]: Cactus Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Cane Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Melon Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Sapling Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Carrot Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Potato Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Wheat Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Vine Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Kelp Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[23:13:55] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[23:13:55] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[23:13:55] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[23:13:55] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:13:55] [Worker-Main-6/INFO]: Preparing spawn area: 2%
[23:13:56] [Worker-Main-2/INFO]: Preparing spawn area: 40%
[23:13:56] [Worker-Main-5/INFO]: Preparing spawn area: 40%
[23:13:57] [Worker-Main-5/INFO]: Preparing spawn area: 40%
[23:13:57] [Worker-Main-5/INFO]: Preparing spawn area: 46%
[23:13:58] [Worker-Main-6/INFO]: Preparing spawn area: 46%
[23:13:58] [Worker-Main-7/INFO]: Preparing spawn area: 67%
[23:13:59] [Worker-Main-2/INFO]: Preparing spawn area: 85%
[23:13:59] [Server thread/INFO]: Time elapsed: 3629 ms
[23:13:59] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[23:13:59] [Worker-Main-1/INFO]: Preparing spawn area: 4%
[23:13:59] [Worker-Main-7/INFO]: Preparing spawn area: 51%
[23:14:00] [Worker-Main-6/INFO]: Preparing spawn area: 51%
[23:14:00] [Worker-Main-3/INFO]: Preparing spawn area: 51%
[23:14:01] [Worker-Main-2/INFO]: Preparing spawn area: 51%
[23:14:01] [Server thread/INFO]: Time elapsed: 2334 ms
[23:14:01] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[23:14:01] [Worker-Main-6/INFO]: Preparing spawn area: 2%
[23:14:02] [Server thread/INFO]: Time elapsed: 426 ms
[23:14:02] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:14:02] [Server thread/INFO]: Done (8.420s)! For help, type "help"

>stop

$ cd plugins/
$ls
PluginMetrics  ProtocolLib  ProtocolLib.jar

[latest.txt](https://github.com/user-attachments/files/16901184/latest.txt)

**Comment by Jeppa** [comment]
You have to update...
1.21.x and build .679 won't work...
