### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by thisfeeling** [dmulloy2/ProtocolLib#3223]
**To Reproduce**
1. Start server 
2. See error
[21:00:17 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket                                                                                                      
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:                                                                                              
  Stack Trace:                                                                                                                                                            
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}                                                                                                                                                                       
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)                                                             
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)                                              
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)                                                     
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)                                           
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)                                                      
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)                                                       
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)                                                                               
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)                                               
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)                                               
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)                                                                     
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)                                                              
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)                                                                                           
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)                                                                            
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)                                                                                      
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)                                                                                   
        at java.base/java.lang.Thread.run(Thread.java:1583)                                                                                                               
  Dump:                                                                                                                                                                   
  Parameters:                                                                                                                                                             
    [NULL]                                                                                                                                                                
  Sender:                                                                                                                                                                 
    com.comphenix.protocol.ProtocolLib@5c6cff55[                                                                                                                          
      statistics=<null>                                                                                                                                                   
      packetTask=<null>                                                                                                                                                   
      tickCounter=0                                                                                                                                                       
      configExpectedMod=-1                                                                                                                                                
      updater=com.comphenix.protocol.updater.SpigotUpdater@51c67d0b                                                                                                       
      redirectHandler=<null>                                                                                                                                              
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@6aebb631                                                                                                
      commandProtocol=<null>                                                                                                                                              
      commandPacket=<null>                                                                                                                                                
      commandFilter=<null>                                                                                                                                                
      packetLogging=<null>                                                                                                                                                
      skipDisable=false                                                                                                                                                   
      isEnabled=false                                                                                                                                                     
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3cdc92cb                                                                                             
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-65-21f125f,minecraftVersion=1.21.1}                                                                        
      file=plugins/.paper-remapped/ProtocolLib.jar                                                                                                                        
      description=org.bukkit.plugin.PluginDescriptionFile@3ee69453                                                                                                        
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@3ee69453                                                                                                         
      dataFolder=plugins/ProtocolLib                                                                                                                                      
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}                             
      naggable=true                                                                                                                                                       
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']                                                                                                      
      configFile=plugins/ProtocolLib/config.yml                                                                                                                           
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@795c3b50                                                                                                     
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@5b7f357                                                                    
      allowsLifecycleRegistration=true                                                                                                                                    
    ]                                                                                                                                                                     
  Version:                                                                                                                                                                
    ProtocolLib v5.2.0-SNAPSHOT-679                                                                                                                                       
  Java Version:                                                                                                                                                           
    21.0.4                                                                                                                                                                
  Server:                                                                                                                                                                 
    1.21.1-65-21f125f (MC: 1.21.1)

**Comment by Av1vxBan** [comment]
same error my server is 1.21

**Comment by thisfeeling** [comment]
> As seen on https://www.spigotmc.org/resources/protocollib.1997/ `Use the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) for 1.20.6 and 1.21` `Use the [latest release](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.2.0) for 1.8 through 1.20.4 `

thank u
