### ISSUE TITLE
Couldnt load protocolib

### ISSUE THREAD

**Issue by xBanD3l** [dmulloy2/ProtocolLib#3227]
Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib(1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib(1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib(1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib(1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib(1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib(1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib(1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@688cea47[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@219a7f58
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2ecb77fe
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@3a9ca6e8
      server=CraftServer{serverName=Paper,serverVersion=1.21-124-df3b654,minecraftVersion=1.21}
      file=plugins/.paper-remapped/ProtocolLib(1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@5e46fe8b
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@5e46fe8b
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib(1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@72c7b46
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@68ab0590
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.4
  Server:
    1.21-124-df3b654 (MC: 1.21)

**Comment by kannaaqt** [comment]
i have this too

**Comment by Benj-HaRRison** [comment]
Same
bruh

**Comment by Av1vxBan** [comment]
I fixed it, Im not home rn of i rememebr i will comment how

**Comment by Av1vxBan** [comment]
Im pretty sure i just needed to update to the latest dev version but im not sure

**Comment by ineanto** [comment]
Update to the [latest dev build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/build/libs/ProtocolLib.jar) for Minecraft 1.20.5+.

**Comment by dzh1127** [comment]
You too

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
