### ISSUE TITLE
1.20.6 

### ISSUE THREAD

**Issue by srt0ns** [dmulloy2/ProtocolLib#3229]
If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:168)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:458)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232)
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@61d55101[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@65db3ba1
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@2ecd3342
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@29a895e2
      server=CraftServer{serverName=CraftBukkit,serverVersion=4195-Spigot-fcd94e2-f057cf4,minecraftVersion=1.20.6}
      file=plugins/ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@44a472c2
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1abc27f2
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@2e5be8a2
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.3
  Server:
    4195-Spigot-fcd94e2-f057cf4 (MC: 1.20.6)

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
