### ISSUE TITLE
I need help for this

### ISSUE THREAD

**Issue by ExtarDu** [dmulloy2/ProtocolLib#3236]
[09:56:27 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[09:56:27 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
        at java.base/java.lang.Thread.run(Thread.java:1570)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@7b7ef15e[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@40696232
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@4c119f60
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@6d34be77
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-83-2aaf436,minecraftVersion=1.21.1}
      file=plugins\.paper-remapped\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7a9fab59
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@7a9fab59
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@3120d073
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@19dc790
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    22.0.2
  Server:
    1.21.1-83-2aaf436 (MC: 1.21.1)

[09:56:27 INFO]: [Geyser-Spigot] Loading server plugin Geyser-Spigot v2.4.2-SNAPSHOT
[09:56:32 INFO]: [Geyser-Spigot] Loading extensions...
[09:56:32 INFO]: [Geyser-Spigot] Loaded 0 extension(s)
[09:56:32 INFO]: [AnimatedScoreboard] Loading server plugin AnimatedScoreboard v0.3.5
[09:56:32 INFO]: Server permissions file permissions.yml is empty, ignoring it
[09:56:32 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[09:56:32 ERROR]: ******************************************************
[09:56:32 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[09:56:32 ERROR]: *** Please use the built-in reload command!        ***
[09:56:32 ERROR]: ******************************************************
[09:56:32 INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679

**Comment by MagmaBro123** [comment]
See #3235.
