### ISSUE TITLE
Protocol lib error on 1.21.1 server

### ISSUE THREAD

**Issue by kubaaa203** [dmulloy2/ProtocolLib#3238]
- [ x ] This issue is not solved in a development build

**Describe the bug**
INTERNAL ERROR: Cannot load ProtocolLib.

**To Reproduce**
0. 'Put protocollib 5.2.0 into plugins folder'
1. Go to 'falix.net'
2. Click on 'start'
3. Scroll down to 'where it says protocolLib info in console'

**Expected behavior**
Plugin works, which is needed for other plugins to work

**Screenshots**

**Version Info**
https://pastebin.com/aWXbz8xF

**Additional context**
srr couldnt paste full error into pastebin for some reason so here it is: 
`[13:03:03] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[13:03:03] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[13:03:08] [Server thread/ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[13:03:08] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
  	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
  	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
  	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
  	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:560)
  	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329)
  	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@71a980cb[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@293d4cd4
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@14af3ee0
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@6002d26a
      server=CraftServer{serverName=Purpur,serverVersion=1.21.1-2308-8332fa4,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@666085b3
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@666085b3
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@331287ff
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@2cfe6ce
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21.1-2308-8332fa4 (MC: 1.21.1)`

**Comment by FandMC** [comment]
I also encountered the issue of 1.21.1 not being able to start. The following is a detailed log
[22:19:49 WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[22:19:53 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[22:19:53 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib (1).jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib (1).jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib (1).jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:551)
        at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:1137)
        at org.bukkit.Bukkit.reload(Bukkit.java:1038)
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:59)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1005)
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:990)
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:530)
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479)
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:327)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@76e43a32[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4a5d5ce7
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@1d3fca34
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@50811e8f
      server=CraftServer{serverName=Leaves,serverVersion=1.21.1-61-23c47a3,minecraftVersion=1.21.1}
      file=plugins\.paper-remapped\ProtocolLib (1).jar
      description=org.bukkit.plugin.PluginDescriptionFile@20cbc760
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@20cbc760
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins\.paper-remapped\ProtocolLib (1).jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@6ab999e6
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@56d94233
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.4
  Server:
    1.21.1-61-23c47a3 (MC: 1.21.1)
    
[22:20:08 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[22:20:08 ERROR]: ******************************************************
[22:20:08 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[22:20:08 ERROR]: *** Please use the built-in reload command!        ***
[22:20:08 ERROR]: ******************************************************
[22:20:08 INFO]: [ProtocolLib] Disabling ProtocolLib v5.2.0-SNAPSHOT-679
[22:20:08 ERROR]: [ProtocolLib] ╔══════════════════════════════════════════════════════════════════╗
[22:20:08 ERROR]: [ProtocolLib] ║                               WARNING                            ║
[22:20:08 ERROR]: [ProtocolLib] ║     RELOADING THE SERVER WHILE PROTOCOL LIB IS ENABLED MIGHT     ║
[22:20:08 ERROR]: [ProtocolLib] ║                    LEAD TO UNEXPECTED ERRORS!                    ║
[22:20:08 ERROR]: [ProtocolLib] ║                                                                  ║
[22:20:08 ERROR]: [ProtocolLib] ║     Consider to cleanly restart your server if you encounter     ║
[22:20:08 ERROR]: [ProtocolLib] ║    any issues related to Protocol Lib before opening an issue    ║
[22:20:08 ERROR]: [ProtocolLib] ║                            on GitHub!                            ║
[22:20:08 ERROR]: [ProtocolLib] ╚══════════════════════════════════════════════════════════════════╝

**Comment by kubaaa203** [comment]
> See #3235.

yeah same error but also no fix

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
