### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by 8QQTUDOU** [dmulloy2/ProtocolLib#3242]
[20:18:35 WARN]: [AdvancedMobArena] Task #6009 for AdvancedMobArena v7.18.2 generated an exception
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.events.PacketContainer.getNumberFormats()'
        at su.nightexpress.ama.arena.board.ArenaBoard.createObjectivePacket(ArenaBoard.java:89) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at su.nightexpress.ama.arena.board.ArenaBoard.create(ArenaBoard.java:114) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at su.nightexpress.ama.arena.impl.ArenaPlayer.addBoard(ArenaPlayer.java:395) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at su.nightexpress.ama.arena.impl.Arena.joinGame(Arena.java:974) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at su.nightexpress.ama.arena.impl.Arena.tickLobby(Arena.java:596) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at su.nightexpress.ama.arena.impl.Arena.tick(Arena.java:518) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at su.nightexpress.ama.arena.ArenaManager.lambda$tickArenas$2(ArenaManager.java:144) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1073) ~[?:?]
        at su.nightexpress.ama.arena.ArenaManager.tickArenas(ArenaManager.java:141) ~[[A][地下城]AdvancedMobArena-7.18.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Ingrim4** [comment]
Please ensure that you have installed the correct version of ProtocolLib for AdvancedMobArena. It seems that AdvancedMobArena is trying to call a method that doesn't exist in the version of ProtocolLib you're currently using.
