### ISSUE TITLE
Erorr plugin gets disabled

### ISSUE THREAD

**Issue by Saulencijus10** [dmulloy2/ProtocolLib#3261]
- [ ] This issue is not solved in a development build

**Describe the bug**
error

**To Reproduce**

**Expected behavior**
loads without errors

**Screenshots**

**Version Info**
Provide your ProtocolLib install info with `/protocol dump` through pastebin.
latest currently from spigot, i use on paper.

**Additional context**
 Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@78e6a755[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7dd0802d
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@30c14ccd
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@4911e7a5
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-116-e7e1ab5,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@71de874e
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@71de874e
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@7dbe3199
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@52e96c9b
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.3
  Server:
    1.21.1-116-e7e1ab5 (MC: 1.21.1)

**Comment by FewerElk** [comment]
I have the same issue on my server

**Comment by DeSinc** [comment]
> [Trnrr](https://github.com/Trnrr) commented [Oct 8, 2024](https://github.com/dmulloy2/ProtocolLib/issues/3264#issuecomment-2397740038)
> 
> Figured it out if you're using 1.21.1.. Download the latest dev build from their jenkins below. The spigot version isn't updated.. The downloaded version was 5.3.0 snapshot 732 and I no longer get the error.
> 
> https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

From issue #3264. this fixes the error
