### ISSUE TITLE
[11:34:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by Swurfyy** [dmulloy2/ProtocolLib#3277]
Hey, I get this error when starting up the server and want to report it:

[11:34:30 WARN]: [ProtocolLib] Version (MC: 1.21.1) has not yet been tested! Proceed with caution.
[11:34:34 ERROR]: [ProtocolLib] Assuming package version: v1_21_R1
[11:34:34 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@44fee364[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@4d005ac7
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@7e5675c0
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@41ccbf4e
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-DEV-4430e96,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4328c2e0
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4328c2e0
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@265f370d
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@4c53856a
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    1.21.1-DEV-4430e96 (MC: 1.21.1)
    
    Server version is 1.21.1

**Comment by digimbyte** [comment]
same deal with spigot 1.21.1
```
[ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
  	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
  	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
  	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.loadPlugins(CraftServer.java:469)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:236)
  	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@1f92142[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@45e7ea10
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@d5c20df
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@50755aed
      server=CraftServer{serverName=CraftBukkit,serverVersion=4290-Spigot-5a6439b-b95736b,minecraftVersion=1.21.1}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@44c83b5a
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@1821df7a
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@55ec640d
    ]
  Version:
    ProtocolLib v5.2.0-SNAPSHOT-679
  Java Version:
    21.0.2
  Server:
    4290-Spigot-5a6439b-b95736b (MC: 1.21.1)
    ```

**Comment by Jeppa** [comment]
PLEASE read all the other identical issue reports.
Exactly this error has been reported many many times and the solution is always the same: please UPDATE to latest dev build...! ;)

**Comment by digimbyte** [comment]
@Swurfyy @Magnetis1 
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
tried this?

**Comment by Swurfyy** [comment]
It works for me now, I indeed already downloaded the last dev build. Console was spamming me to report it, so I put in on here :p
