### ISSUE TITLE
Cannot load protocollib

### ISSUE THREAD

**Issue by Foxof7207** [dmulloy2/ProtocolLib#3283]
- [ ] This issue is not solved in a development build

**Describe the bug**
Unable to start protocollib

**To Reproduce**
1. Install protocolib
2. start a 1.21.1 server on purpur
5.  (tack Trace:
java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:183)
at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:334)
at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:369)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
at java.base/java.lang.Thread.run(Thread.java:1570)
Dump:
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLib@1a42fd32[
statistics=<null>
packetTask=<null>
tickCounter=0
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@186c557f
redirectHandler=<null>
scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@15ca802d
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=false
loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1598c2c4
server=CraftServer{serverName=Paper,serverVersion=1.21.1-122-4430e96,minecraftVersion=1.21.1}
file=plugins/.paper-remapped/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@4f9a865
pluginMeta=org.bukkit.plugin.PluginDescriptionFile@4f9a865
dataFolder=plugins/ProtocolLib
classLoader=PluginClassLoader{plugin=ProtocolLib v5.2.0-SNAPSHOT-679, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@4e051072
lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@29f86722
allowsLifecycleRegistration=true
]
Version:
ProtocolLib v5.2.0-SNAPSHOT-679
Java Version:
22.0.2
Server:
1.21.1-122-4430e96 (MC: 1.21.1)
[23:50:45 INFO]: [Veinminer] Loading server plugin Veinminer v2.1.5
[23:50:45 INFO]: [MelodyMine] Loading server plugin MelodyMine v2.0.5
[23:50:45 INFO]: [Veinminer-Enchantment] Loading server plugin Veinminer-Enchantment v2.1.5
[23:50:45 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.141
[23:50:45 INFO]: [pvp-toggle] Loading server plugin pvp-toggle v1.2.0
[23:50:45 INFO]: [FancyPhysics] Loading server plugin FancyPhysics v3.0.3
[23:50:45 INFO]: [SimpleClaimSystem] Loading server plugin SimpleClaimSystem v1.11.6.2
[23:50:45 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:50:45 INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679)

**Expected behavior**
Should work fine

**Screenshots**

**Version Info**
lastet from spigotmc

**Additional context**

**Comment by twojamama1** [comment]
i have the exact same problem

**Comment by Ingrim4** [comment]
Should be fixed in the latest release so please use the latest release and try again: https://github.com/dmulloy2/ProtocolLib/releases/latest
