### ISSUE TITLE
[11:15:51 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.

### ISSUE THREAD

**Issue by xiaozwl** [dmulloy2/ProtocolLib#3290]
If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 10000, banned: 1000], type={ type input instanceof interface java.util.Map }}
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.createNewRegister(PacketRegistry.java:168)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:292)
        at ProtocolLib.jar//com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:327)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:120)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:121)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:183)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
        at java.base/java.lang.Thread.run(Thread.java:1583)
  Dump:
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@415f1aa[
      statistics=<null>
      packetTask=<null>
      tickCounter=0
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@75929d06
      redirectHandler=<null>
      scheduler=com.comphenix.protocol.scheduler.DefaultScheduler@5e21babf
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@33085b84
      server=CraftServer{serverName=Paper,serverVersion=1.21.1-74-971a7a5,minecraftVersion=1.21.1}
      file=plugins/.paper-remapped/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@c5859fa
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@c5859fa
      dataFolder=plugins/ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v5.1.0, pluginEnabled=false, url=plugins/.paper-remapped/ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@345bb5a8
      lifecycleEventManager=io.papermc.paper.plugin.lifecycle.event.PaperLifecycleEventManager@5b32d09a
      allowsLifecycleRegistration=true
    ]
  Version:
    ProtocolLib v5.1.0
  Java Version:
    21.0.4
  Server:
    1.21.1-74-971a7a5 (MC: 1.21.1)

**Comment by Ingrim4** [comment]
Should be fixed in the latest release so please use the latest release and try again: https://github.com/dmulloy2/ProtocolLib/releases/latest
