### ISSUE TITLE
Input Handling in 1.21.2+

### ISSUE THREAD

**Issue by Ste3et** [dmulloy2/ProtocolLib#3299]
- [ x] This feature is not currently present in a development build

**Is your feature request related to a problem? Please describe.**
The `PacketType.Play.Client.STEER_VEHICLE` works internal with `net.minecraft.world.entity.player.Input` and the set/get methode inside PacketContainer is mising and there isn't a data type present.

**Describe the solution you'd like**
Please add an function to get the Player Input and work with an Wrapped Object

**Error Log Inside 1.21.2**
`[00:17:30] [Netty Epoll Server IO #0/ERROR]: [FurnitureLib] Unhandled exception occurred in onPacketReceiving(PacketEvent) for FurnitureLib
com.comphenix.protocol.reflect.FieldAccessException: Field index 1 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:247) ~[?:?]
        at de.Ste3et_C0st.FurnitureLib.Listener.FurnitureProtocolListener$1.onPacketReceiving(FurnitureProtocolListener.java:87) ~[?:?]
        at com.comphenix.protocol.injector.collection.InboundPacketListenerSet.invokeListener(InboundPacketListenerSet.java:25) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[?:?]
        at com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[?:?]
        at com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokeInboundPacketListeners(PacketFilterManager.java:509) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundInternal(NettyChannelInjector.java:455) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInbound(NettyChannelInjector.java:439) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:47) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]`

1.21.3 Internal Code from ServerboundPlayerInputPacket ![image](https://github.com/user-attachments/assets/9d4a5ad2-aa32-43f5-8acc-0c4a213034af)
1.21.1 Internal Code from ServerboundPlayerInputPacket ![image](https://github.com/user-attachments/assets/48ca6b11-5793-419f-be28-2ea698e00179)

**Comment by Brokkonaut** [comment]
Try something like this:
```
            PacketContainer packet = event.getPacket();
            InternalStructure input = packet.getStructures().read(0);
            boolean forward = input.getBooleans().read(0);
            boolean backward = input.getBooleans().read(1);
            boolean left = input.getBooleans().read(2);
            boolean right = input.getBooleans().read(3);
            boolean space = input.getBooleans().read(4);
            boolean shift = input.getBooleans().read(5);
```

**Comment by Lorenzo0111** [comment]
Yep, that works. Is the package still sent multiple times when i keep like W pressed?

**Comment by Ste3et** [comment]
> Try something like this:
> 
> ```
>             PacketContainer packet = event.getPacket();
>             InternalStructure input = packet.getStructures().read(0);
>             boolean forward = input.getBooleans().read(0);
>             boolean backward = input.getBooleans().read(1);
>             boolean left = input.getBooleans().read(2);
>             boolean right = input.getBooleans().read(3);
>             boolean space = input.getBooleans().read(4);
>             boolean shift = input.getBooleans().read(5);
> ```

Thank you @Brokkonaut i forget about it, atm i have so much trouble with my shool that i make simultaneously as my fulltime job

**Comment by TheCalypso** [comment]
Hello everyone !

Thank you very much for what you said, it helped me a lot. However, I have a problem, I cannot cancel the output of my player when he presses the sneak key. 

To give context, the player is on a sheep that is moving on its own and I want to cancel the dismount.

Could you help me? 

Thanks again for your help <3

```JAVA
static void packetListeners() {
    ProtocolLibrary.getProtocolManager().addPacketListener(
            new PacketAdapter(GMoutrun.getPlugin(), PacketType.Play.Client.STEER_VEHICLE) {
                @Override
                public void onPacketReceiving(PacketEvent event) {
                    PacketContainer packet = event.getPacket();
                    var sheepController = SheepController.get(event.getPlayer());
                    if(sheepController == null) return;
                    event.setCancelled(true);
                    InternalStructure input = packet.getStructures().read(0);
                    boolean left = input.getBooleans().read(2);
                    boolean right = input.getBooleans().read(3);
                    boolean space = input.getBooleans().read(4);
                    boolean shift = input.getBooleans().read(5);

                    float sideway = 0;
                    if (left) sideway++;
                    if (right) sideway--;

                    input.getBooleans().write(5, false);
                    packet.getModifier().writeDefaults();
                    sheepController.setSideway(sideway);
                }
            });
}
```

**Comment by TheCalypso** [comment]
update: I use EntityDismountEvent for cancel this event.
