### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by heper651** [dmulloy2/ProtocolLib#3309]
FieldAccessException: Field index 0 is out of bounds for length 0
        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:318)
        at oraxen-1.183.0.jar//io.th0rgal.oraxen.font.packets.ScoreboardPacketListener.onPacketSending(ScoreboardPacketListener.java:23)
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74)
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123)
        at ProtocolLib.jar//com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7)
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123)
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30)
        at ProtocolLib.jar//com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44)
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233)
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:433)
        at net.minecraft.network.NetworkManager$PacketSendAction.lambda$new$0(NetworkManager.java:961)
        at net.minecraft.network.NetworkManager$WrappedConsumer.accept(NetworkManager.java:945)
        at net.minecraft.network.NetworkManager.processQueue(NetworkManager.java:563)
        at net.minecraft.network.NetworkManager.flushQueue(NetworkManager.java:524)
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:413)
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.a(ServerCommonPacketListenerImpl.java:255)
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.b(ServerCommonPacketListenerImpl.java:240)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.core.volatilecode.v1_20_R3.VolatileEntityHandlerImpl.initTeams(VolatileEntityHandlerImpl.java:122)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.core.glow.GlowManager.lambda$load$0(GlowManager.java:35)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.Events.call(Events.java:103)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.core.players.PlayerManager.initProfile(PlayerManager.java:55)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.core.players.PlayerManager.initProfile(PlayerManager.java:29)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.storage.players.PlayerRepository.lambda$loadProfile$2(PlayerRepository.java:108)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToFunction.apply(Delegates.java:177)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise$ApplyRunnable.run(LuminePromise.java:684)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise.executeSync(LuminePromise.java:133)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise.lambda$thenApplySync$1(LuminePromise.java:364)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise.thenApplySync(LuminePromise.java:360)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.promise.Promise.thenAcceptSync(Promise.java:871)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.storage.players.PlayerRepository.loadProfile(PlayerRepository.java:96)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.storage.players.PlayerRepository.loadProfile(PlayerRepository.java:92)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.storage.players.PlayerRepository.lambda$load$0(PlayerRepository.java:54)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
        at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:345)
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:134)
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Brokkonaut** [comment]
probably caused by oraxen-1.183.0.jar
