### ISSUE TITLE
Error message on Join

### ISSUE THREAD

**Issue by Ste3et** [dmulloy2/ProtocolLib#331]
i used the new 1.12pre i know it needs time to update but here is a error message on joining:

`[13:43:38 INFO]: Error Unable to inject incoming channel [id: 0x883d665b, L:/127.0.0.1:25565 - R:/127.0.0.1:49438]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x883d665b, L:/127.0.0.1:25565 - R:/127.0.0.1:49438]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@33e30d57.
[13:43:38 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x883d665b, L:/127.0.0.1:25565 - R:/127.0.0.1:49438].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x883d665b, L:/127.0.0.1:25565 - R:/127.0.0.1:49438]
  	at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
  	at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
  	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
  	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
  	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
  	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
  	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
  	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
  	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  	at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1958f130[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@32c98cb4
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@17036dab
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@26fbfa74
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@78f44eea
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@6a6c16c
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@a448a26
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@3c6f9667
        reporter=com.comphenix.protocol.ProtocolLib$1@7315f940
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-429b0e3-5195487,minecraftVersion=1.12-pre2}
        library=ProtocolLib v4.2.2-SNAPSHOT-b357
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@19517332
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@33e30d57
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@52147250
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.0-pre2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@762780bd
        debug=true
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@33e30d57[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@1e638862
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@ede9705, container=net.minecraft.server.v1_12_R1.ServerConnection@c7c2e24, previous=[AbstractBootstrap$PendingRegistrationPromise@343f8320(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@46d16c04, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@3c4dbd64, container=net.minecraft.server.v1_12_R1.ServerConnection@c7c2e24, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@512da9c7
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@19431641
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@543ff821
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@548c95f
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@39972ba0
      invoker=com.comphenix.protocol.injector.PacketFilterManager@1958f130
      reporter=com.comphenix.protocol.ProtocolLib$1@7315f940
      debug=true
    ]
  Version:
    ProtocolLib v4.2.2-SNAPSHOT-b357
  Java Version:
    1.8.0_45
  Server:
    git-Spigot-429b0e3-5195487 (MC: 1.12-pre2)

[13:43:38 INFO]: UUID of player Ste3et_C0st is 10eabfae-1d87-3120-b9bc-cb16bfa6ce88`

this is  a error code without my FurnitureLib plugin and this is with my plugin:
`[13:46:56] [Netty Server IO #2/WARN]: Failed to initialize a channel. Closing: [id: 0x84c008ef, L:/127.0.0.1:25565 - R:/127.0.0.1:49455]
java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
	at com.comphenix.protocol.events.ListeningWhitelist.toString(ListeningWhitelist.java:241) ~[?:?]
	at java.lang.String.valueOf(Unknown Source) ~[?:1.8.0_45]
	at java.lang.StringBuilder.append(Unknown Source) ~[?:1.8.0_45]
	at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:273) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:246) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:251) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:285) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:257) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printIterables(PrettyPrinter.java:144) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:277) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:246) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:124) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:102) ~[?:?]
	at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:89) ~[?:?]
	at com.comphenix.protocol.error.DetailedErrorReporter.getStringDescription(DetailedErrorReporter.java:480) ~[?:?]
	at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:369) ~[?:?]
	at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63) ~[?:?]
	at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:149) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379) [spigot.jar:git-Spigot-429b0e3-5195487]
	at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159) [ProtocolLib%20(1).jar:4.2.2-SNAPSHOT-b357]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [spigot.jar:git-Spigot-429b0e3-5195487]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[13:46:56] [Netty Server IO #2/WARN]: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: null
	at net.minecraft.server.v1_12_R1.NetworkManager.close(NetworkManager.java:250) ~[spigot.jar:git-Spigot-429b0e3-5195487]
	at net.minecraft.server.v1_12_R1.NetworkManager.channelInactive(NetworkManager.java:106) ~[spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [spigot.jar:git-Spigot-429b0e3-5195487]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [spigot.jar:git-Spigot-429b0e3-5195487]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]`

i think the problem is not the FurnitureLib the plugin works but after an rejoin i become this error.

http://i.imgur.com/N0T6Vb7.png

**Comment by games647** [comment]
Please close this. This one is duplicate. There is already one ticket open about this issue #330
