### ISSUE TITLE
INTERNAL ERROR: Unable to inject incoming channel

### ISSUE THREAD

**Issue by Etienne-Wattebled** [dmulloy2/ProtocolLib#340]
Hello,

The last version of ProtocolLib doesn't work on Spigot 1.11.2 but the v-1 works.
I can't connect to server

[08:29:28] [Netty Epoll Server IO #2/INFO]: Error Unable to inject incoming channel [id: 0xf7b96e5a, /176.189.238.223:50270 => /94.23.210.145:27534]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3.[m
[08:29:28] [Netty Epoll Server IO #2/ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xf7b96e5a, /176.189.238.223:50270 => /94.23.210.145:27534].
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:279)
at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at java.lang.Thread.run(Thread.java:745)
Dump:
manager:
com.comphenix.protocol.injector.PacketFilterManager@4bc72240[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@22955b98
packetListeners=[com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@1ef51884, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@1a1ce6d8, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@1e1d7aea, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@4cb2c2ef]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f899ddc
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@78a9085
interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@752d7716
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7d6cbbb0
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2e58bebc
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@cf3020f
reporter=com.comphenix.protocol.ProtocolLib$1@7d851d4a
server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-3fb9445-6e3cec8,minecraftVersion=1.11.2}
library=ProtocolLib v4.2.1
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7ba7d6d1
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=4
packetCreation=false
spigotInjector=
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@83bf3a4
hasRecycleDistance=true
minecraftVersion=(MC: 1.11.2)
loginPackets=com.comphenix.protocol.injector.LoginPackets@15af8185
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3[
injected=true
closed=false
playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@6dbc5dd1
bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@4c8f7a48, container=net.minecraft.server.v1_11_R1.ServerConnection@43d2e4dd, previous=com.comphenix.protocol.injector.netty.BootstrapList@114b502d, current=com.comphenix.protocol.injector.netty.BootstrapList@1fa625cc, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@284c414a, container=net.minecraft.server.v1_11_R1.ServerConnection@43d2e4dd, previous=[net.minecraft.server.v1_11_R1.NetworkManager@45921dc0], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@37ed411a
networkManagers=[net.minecraft.server.v1_11_R1.NetworkManager@45921dc0]
sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@194b8a6e
reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@53c7de1c
mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@4ad670ca
bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@176e0d1b
invoker=com.comphenix.protocol.injector.PacketFilterManager@4bc72240
reporter=com.comphenix.protocol.ProtocolLib$1@7d851d4a
debug=false
]
Version:
ProtocolLib v4.2.1
Java Version:
1.8.0_112
Server:
git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
[08:29:28] [Server thread/INFO]: com.mojang.authlib.GameProfile@1508b3d0[id=,name=Dr_Titoune,properties={},legacy=false] (/176.189.238.223:50270) lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedGameProfile
[08:29:32] [Netty Epoll Server IO #3/INFO]: Error Unable to inject incoming channel [id: 0xfb2029a9, /176.189.238.223:50282 => /94.23.210.145:27534]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3.[m
[08:29:32] [Netty Epoll Server IO #3/ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xfb2029a9, /176.189.238.223:50282 => /94.23.210.145:27534].
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:279)
at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at java.lang.Thread.run(Thread.java:745)
Dump:
manager:
com.comphenix.protocol.injector.PacketFilterManager@4bc72240[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@22955b98
packetListeners=[com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@1ef51884, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@1a1ce6d8, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@1e1d7aea, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@4cb2c2ef]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f899ddc
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@78a9085
interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@752d7716
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7d6cbbb0
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2e58bebc
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@cf3020f
reporter=com.comphenix.protocol.ProtocolLib$1@7d851d4a
server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-3fb9445-6e3cec8,minecraftVersion=1.11.2}
library=ProtocolLib v4.2.1
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7ba7d6d1
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=4
packetCreation=false
spigotInjector=
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@83bf3a4
hasRecycleDistance=true
minecraftVersion=(MC: 1.11.2)
loginPackets=com.comphenix.protocol.injector.LoginPackets@15af8185
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3[
injected=true
closed=false
playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@6dbc5dd1
bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@4c8f7a48, container=net.minecraft.server.v1_11_R1.ServerConnection@43d2e4dd, previous=com.comphenix.protocol.injector.netty.BootstrapList@114b502d, current=com.comphenix.protocol.injector.netty.BootstrapList@1fa625cc, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@284c414a, container=net.minecraft.server.v1_11_R1.ServerConnection@43d2e4dd, previous=[net.minecraft.server.v1_11_R1.NetworkManager@634febdb], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@37ed411a
networkManagers=[net.minecraft.server.v1_11_R1.NetworkManager@634febdb]
sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@194b8a6e
reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@53c7de1c
mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@4ad670ca
bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@176e0d1b
invoker=com.comphenix.protocol.injector.PacketFilterManager@4bc72240
reporter=com.comphenix.protocol.ProtocolLib$1@7d851d4a
debug=false
]
Version:
ProtocolLib v4.2.1
Java Version:
1.8.0_112
Server:
git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
[08:29:33] [Netty Epoll Server IO #0/INFO]: Error Unable to inject incoming channel [id: 0x26c1a142, /176.189.238.223:50283 => /94.23.210.145:27534]. (java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3.[m
[08:29:33] [Netty Epoll Server IO #0/ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x26c1a142, /176.189.238.223:50283 => /94.23.210.145:27534].
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_decoder
at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:158)
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:279)
at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:412)
at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:251)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at com.comphenix.protocol.injector.netty.ProtocolInjector$3.channelRead(ProtocolInjector.java:171)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at com.comphenix.protocol.injector.netty.ProtocolInjector$3.channelRead(ProtocolInjector.java:171)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
at io.netty.channel.epoll.EpollServerSocketChannel$EpollServerSocketUnsafe.epollInReady(EpollServerSocketChannel.java:109)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at java.lang.Thread.run(Thread.java:745)
Dump:
manager:
com.comphenix.protocol.injector.PacketFilterManager@4bc72240[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@22955b98
packetListeners=[com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@1ef51884, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@1a1ce6d8, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@1e1d7aea, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@4cb2c2ef]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f899ddc
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@78a9085
interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@752d7716
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7d6cbbb0
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2e58bebc
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@cf3020f
reporter=com.comphenix.protocol.ProtocolLib$1@7d851d4a
server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-3fb9445-6e3cec8,minecraftVersion=1.11.2}
library=ProtocolLib v4.2.1
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7ba7d6d1
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=4
packetCreation=false
spigotInjector=
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@83bf3a4
hasRecycleDistance=true
minecraftVersion=(MC: 1.11.2)
loginPackets=com.comphenix.protocol.injector.LoginPackets@15af8185
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ProtocolInjector@1111c0d3[
injected=true
closed=false
playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@6dbc5dd1
bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@4c8f7a48, container=net.minecraft.server.v1_11_R1.ServerConnection@43d2e4dd, previous=com.comphenix.protocol.injector.netty.BootstrapList@114b502d, current=com.comphenix.protocol.injector.netty.BootstrapList@1fa625cc, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@284c414a, container=net.minecraft.server.v1_11_R1.ServerConnection@43d2e4dd, previous=[net.minecraft.server.v1_11_R1.NetworkManager@36ee4424], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@37ed411a
networkManagers=[net.minecraft.server.v1_11_R1.NetworkManager@36ee4424]
sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@194b8a6e
reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@53c7de1c
mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@4ad670ca
bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@176e0d1b
invoker=com.comphenix.protocol.injector.PacketFilterManager@4bc72240
reporter=com.comphenix.protocol.ProtocolLib$1@7d851d4a
debug=false
]
Version:
ProtocolLib v4.2.1
Java Version:
1.8.0_112
Server:
git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
[08:29:33] [Server thread/INFO]: com.mojang.authlib.GameProfile@572cb247[id=,name=Dr_Titoune,properties={},legacy=false] (/176.189.238.223:50283) lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedGameProfile

**Comment by PenguinNexus** [comment]
This is due to the latest Spigot build. Upgrade to http://ci.dmulloy2.net/job/ProtocolLib/lastBuild/
Fixed it for me.
