### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by MarineMCA** [dmulloy2/ProtocolLib#342]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues

Debug paste link:
[19:56:08] [Netty Epoll Server IO #0/INFO]: Error Unable to inject incoming channel [id: 0x9016c204, L:/64.94.100.51:25565 - R:/192.99.101.31:58190]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x9016c204, L:/64.94.100.51:25565 - R:/192.99.101.31:58190]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@1f78e369.
[19:56:08] [Netty Epoll Server IO #0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x9016c204, L:/64.94.100.51:25565 - R:/192.99.101.31:58190].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x9016c204, L:/64.94.100.51:25565 - R:/192.99.101.31:58190]
  	at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
  	at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
  	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
  	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
  	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
  	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
  	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
  	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
  	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:472)
  	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
  	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
  	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:85)
  	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:259)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector$3.channelRead(ProtocolInjector.java:171)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
  	at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:138)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  	at java.lang.Thread.run(Thread.java:745)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@16458e2c[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@8a49d3a
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2e85b764
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@41a02687
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@7b2ef471
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@57cfeb63
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@54f24869
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@15eb61dd
        reporter=com.comphenix.protocol.ProtocolLib$1@1426c86e
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-ede465d-bb4ae3b,minecraftVersion=1.12}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@309b4f73
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@1f78e369
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@ec5fc2f
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.0)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@3bbb5de
        debug=false

Description and relevant errors:

**Comment by dmulloy2** [comment]
> You're using the latest build for your server version

You're using 4.2.1, 1.12 support was added in 4.3.0.
