### ISSUE TITLE
Please update to 1.12 for Spigot

### ISSUE THREAD

**Issue by juliocoliveira** [dmulloy2/ProtocolLib#348]
```[10:14:12] [Netty Server IO #1/INFO]: Error Unable to inject incoming channel [id: 0x4adf73d9, L:/192.168.0.3:25565 - R:/192.168.0.6:51699]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x4adf73d9, L:/192.168.0.3:25565 - R:/192.168.0.6:51699]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@e13cd3.
[10:14:12] [Netty Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x4adf73d9, L:/192.168.0.3:25565 - R:/192.168.0.6:51699].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x4adf73d9, L:/192.168.0.3:25565 - R:/192.168.0.6:51699]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@abe82f[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1f5ae5b
        packetListeners=[com.comphenix.protocol.async.NullPacketListener@1d12312, com.comphenix.protocol.async.NullPacketListener@17c83f6]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f11935
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1b053b8
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@912331
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@d0c14e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1eb4350
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1eac7af
        reporter=com.comphenix.protocol.ProtocolLib$1@15f686
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-cd6ba67-f7d14f1,minecraftVersion=1.12}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@18ebc90
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=2
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@e13cd3
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3a722b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.0)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@29c110
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@e13cd3[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@11a8946
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@11dcfa8, container=net.minecraft.server.v1_12_R1.ServerConnection@422c74, previous=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@17fa24f, current=com.comphenix.protocol.injector.netty.BootstrapList@13d356b, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@e2d8ab, container=net.minecraft.server.v1_12_R1.ServerConnection@422c74, previous=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@18c604f, current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@15bcb2b
      networkManagers=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@18c604f
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1333b86
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1aa88cb
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1a01d29
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@219fa5
      invoker=com.comphenix.protocol.injector.PacketFilterManager@abe82f
      reporter=com.comphenix.protocol.ProtocolLib$1@15f686
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_65
  Server:
    git-Spigot-cd6ba67-f7d14f1 (MC: 1.12)

[10:14:22] [Netty Server IO #2/INFO]: Error Unable to inject incoming channel [id: 0xb3d71009, L:/192.168.0.3:25565 - R:/192.168.0.6:51701]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xb3d71009, L:/192.168.0.3:25565 - R:/192.168.0.6:51701]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@e13cd3.
[10:14:22] [Netty Server IO #2/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xb3d71009, L:/192.168.0.3:25565 - R:/192.168.0.6:51701].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xb3d71009, L:/192.168.0.3:25565 - R:/192.168.0.6:51701]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@abe82f[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1f5ae5b
        packetListeners=[com.comphenix.protocol.async.NullPacketListener@1d12312, com.comphenix.protocol.async.NullPacketListener@17c83f6]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1f11935
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1b053b8
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@912331
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@d0c14e
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1eb4350
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@1eac7af
        reporter=com.comphenix.protocol.ProtocolLib$1@15f686
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-cd6ba67-f7d14f1,minecraftVersion=1.12}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@18ebc90
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=2
        phasePlayingCount=2
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@e13cd3
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3a722b
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.0)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@29c110
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@e13cd3[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@11a8946
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@11dcfa8, container=net.minecraft.server.v1_12_R1.ServerConnection@422c74, previous=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@17fa24f, current=com.comphenix.protocol.injector.netty.BootstrapList@13d356b, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@e2d8ab, container=net.minecraft.server.v1_12_R1.ServerConnection@422c74, previous=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@18c604f, current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@15bcb2b
      networkManagers=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@18c604f
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1333b86
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1aa88cb
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1a01d29
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@219fa5
      invoker=com.comphenix.protocol.injector.PacketFilterManager@abe82f
      reporter=com.comphenix.protocol.ProtocolLib$1@15f686
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_65
  Server:
    git-Spigot-cd6ba67-f7d14f1 (MC: 1.12)
```

**Comment by games647** [comment]
Please follow the issue template:
>You're using the latest build for your server version

So update to 4.3 here: http://ci.dmulloy2.net/job/ProtocolLib/

**Comment by juliocoliveira** [comment]
Oh thanks, i got my version from the spigot resource forums.
I replaced with the one above, and now it works.
Thanks!
