### ISSUE TITLE
1.8.8 support

### ISSUE THREAD

**Issue by kamcio96** [dmulloy2/ProtocolLib#351]
```
[ProtocolLib] Loading ProtocolLib v4.3.0
```

```
[19:03:17 ERROR]: Error occurred while enabling TestNPCPlugin v1.0-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: Cannot find class DataWatcherRegistry
        at com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:90) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1991) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getDataWatcherRegistryClass(MinecraftReflection.java:1349) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.initialize(WrappedDataWatcher.java:978) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$Registry.get(WrappedDataWatcher.java:918) ~[?:?]
        at pl.kamcio96.npcplus.impl.SimpleNPC.createSpawnPackets(SimpleNPC.java:58) ~[?:?]
        at pl.kamcio96.npcplus.impl.AbstractNPC.init(AbstractNPC.java:46) ~[?:?]
        at pl.kamcio96.npcplus.impl.NPCManager.buildNPC(NPCManager.java:44) ~[?:?]
        at pl.kamcio96.npcplus.impl.SimpleNPCBuilder.build(SimpleNPCBuilder.java:60) ~[?:?]
        at pl.kamcio96.npcplus.test.TestNPCPlugin.onEnable(TestNPCPlugin.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.DataWatcherRegistry
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paperspigot-1.8.8-R0.1-SNAPSHOT.jar:git-PaperSpigot-4c7641d]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
        at com.comphenix.protocol.utility.ClassSource$1.loadClass(ClassSource.java:37) ~[?:?]
        at com.comphenix.protocol.utility.CachedPackage.getPackageClass(CachedPackage.java:81) ~[?:?]
        ... 20 more
[19:03:17 INFO]: [TestNPCPlugin] Disabling TestNPCPlugin v1.0-SNAPSHOT
[19:03:18 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:03:18 INFO]: Done (2,037s)! For help, type "help" or "?"
[19:03:18 INFO]: Timings Reset
>version
[19:08:25 INFO]: This server is running CraftBukkit version git-PaperSpigot-4c7641d (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

**Comment by dmulloy2** [comment]
This is an issue with the plugin using ProtocolLib, not ProtocolLib itself. It's using an API that's only supported in 1.9 and up

**Comment by kamcio96** [comment]
Okey, so how set metadata for 1.8.8 version? 😄

**Comment by TheSpeedCoder** [comment]
Use an older version of ProtocolLib

**Comment by kamcio96** [comment]
@TheSpeedCoder 
1.9+: `dataWatcher.setObject(13, WrappedDataWatcher.Registry.get(Byte.class), (byte) 126);`
1.8.x: `dataWatcher.setObject(13, (byte) 126);`

Thanks for help. @dmulloy2 My small sugestion is you can add that info to exception ;)
