### ISSUE TITLE
Protocol lib Kicking issue

### ISSUE THREAD

**Issue by DuckCraftPvP** [dmulloy2/ProtocolLib#352]
[13:59:16 INFO]: star_destroyer48 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

i am getting this error and everyone says its a protocol lib issue.

debug paste link: 
https://hastebin.com/aqohecokup.pl

**Comment by dmulloy2** [comment]
It's not necessarily a ProtocolLib issue, though it could be.

Enable `debug=true` in your server.properties to get a full stacktrace.

**Comment by DuckCraftPvP** [comment]
kk

**Comment by DuckCraftPvP** [comment]
dam this debug mode though

https://hastebin.com/qeyujijiru.md

**Comment by dmulloy2** [comment]
This is an issue with ViaBackwards, not ProtocolLib:

`[02:12:32 WARN]: Caused by: java.lang.NullPointerException
[02:12:32 WARN]:        at nl.matsv.viabackwards.api.rewriters.EntityRewriter.handleMeta(EntityRewriter.java:102)
[02:12:32 WARN]:        at nl.matsv.viabackwards.protocol.protocol1_12to1_11_1.packets.EntityPackets1_12.access$1300(EntityPackets1_12.java:40)`
