### ISSUE TITLE
ProtocolLib getting disabled on PaperSpigot 1.7/1.8

### ISSUE THREAD

**Issue by AzuryaTV** [dmulloy2/ProtocolLib#356]
[06:48:56 INFO]: [ProtocolLib] Loading ProtocolLib v4.3.0
[06:48:56 WARN]: [ProtocolLib] Version (MC: 1.7.10) is lower than the minimum (MC: 1.8.0)
[06:48:57 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:227)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:169)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelInboundHandler
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@3b6358e2[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@57cd2e57
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@7c1e84d9
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@5c1b48b6
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-1f7d532,minecraftVersion=1.7.10}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@7f880f40
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@6d2cddb2
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@489281df
    ]
  Version:
    ProtocolLib v4.3.0
  Java Version:
    1.8.0_131
  Server:
    git-PaperSpigot-1f7d532 (MC: 1.7.10)

[06:48:57 INFO]: [Reflex] Loading Reflex v10.0-3U
[06:48:57 INFO]: [ProtocolLib] Enabling ProtocolLib v4.3.0
[06:48:57 ERROR]: ******************************************************
[06:48:57 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[06:48:57 ERROR]: *** Please use the built-in reload command!        ***
[06:48:57 ERROR]: ******************************************************
[06:48:57 INFO]: [ProtocolLib] Disabling ProtocolLib v4.3.0

**Comment by dmulloy2** [comment]
> [ProtocolLib] Version (MC: 1.7.10) is lower than the minimum (MC: 1.8.0)

The latest version of ProtocolLib doesn't work with 1.7.x. Use 3.7.0.
