### ISSUE TITLE
protocolib bungee

### ISSUE THREAD

**Issue by MrSuricate2** [dmulloy2/ProtocolLib#359]
Debug paste link:

https://mega.nz/#!hAsF0IoL!PgU-pLqKFy120-ZQt6Aemr1E2xuiTe8e7twLs7yDdTU

Description and relevant errors:
`[13:33:18 WARN]: Failed to initialize a channel. Closing: [id: 0x65b15337, /82.254.109.39:51856 =› /5.135.100.145:25565]
java.lang.ExceptionInInitializerError
at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:205) ~[?:?]
at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:157) ~[?:?]
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:71) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.IllegalArgumentException: 'PROTOCOL' is already in use
at io.netty.util.UniqueName.‹init›(UniqueName.java:53) ~[gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.util.AttributeKey.‹init›(AttributeKey.java:47) ~[gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39) ~[gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at com.comphenix.protocol.injector.netty.ChannelInjector.‹clinit›(ChannelInjector.java:95) ~[?:?]
... 23 more
[13:33:18 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException
at net.minecraft.server.v1_10_R1.NetworkManager.close(NetworkManager.java:247) ~[gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at net.minecraft.server.v1_10_R1.NetworkManager.channelInactive(NetworkManager.java:106) ~[gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at io.ne
tty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [gbinvl_minecraft_spigot_1_10_2.jar:git-Spigot-570526c-c1b529e]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]`

**Comment by dmulloy2** [comment]
Did you `/reload` your server?

**Comment by MrSuricate2** [comment]
Yes, this error message keeps me from joining my server. Because I use bungeecord
