### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by davidjm6** [dmulloy2/ProtocolLib#37]
Unable to enable due to this error: http://pastebin.com/hywS9wBZ

Config: http://pastebin.com/eMSnAy0x

other plugins used: WorldBorder, WorldEdit, PluginManager, BOSEconomy, Vault, PermissionsEx, Multiverse-Core, Questioner, WorldGuard, HeadDrops, Announcer, CoreProtect, ClearLag, ProtocolLib, Votifier, mcMMO, GAListener, MoneyDrop, Essentials, EssentialsProtect, Towny, LibsDisguises, EssentialsSpawn, Multiverse-Portals, Multiverse-Inventories, SignShop, EchoPet, EnjinMinecraftPlugin

LibsDisguises also does not work as it requires ProtocolLib to function.

**Comment by dmulloy2** [comment]
Use the latest build from my Jenkins: http://ci.shadowvolt.com/job/ProtocolLib/

**Comment by davidjm6** [comment]
I thought I was using the latest build... I deleted protocollib from the server and put in build #72 which is the latest on Jenkins. I'm still getting the same error.

[19:10:10] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at http://dev.bukkit.org/server-mods/protocollib/ with the following data:
            ===== STACK TRACE =====
  java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelInboundHandler
  	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:264)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
  	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
  	at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216)
  	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:295)
  	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152)
  	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelInboundHandler
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
  	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  	... 8 more
            ===== DUMP =====
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLibrary@1f2bdd12[
      statistisc=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7e4cd909
      configExpectedMod=-1
      updater=com.comphenix.protocol.metrics.Updater@442e875c
      logger=org.bukkit.plugin.PluginLogger@4ab4919
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@5583f15e
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-a723278-5b92dc3,minecraftVersion=1.8}
      file=plugins/ProtocolLib-Spigot-3.6.0-SNAPSHOT.jar
      description=org.bukkit.plugin.PluginDescriptionFile@51a4bf7e
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2412c49e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@4ab4919
    ]
  Version:
    ProtocolLib v3.6.0-SNAPSHOT
  Server:
    git-Spigot-a723278-5b92dc3 (MC: 1.8)

**Comment by davidjm6** [comment]
That was on load. Here is on enable:

[19:10:11] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at http://dev.bukkit.org/server-mods/protocollib/ with the following data:
            ===== STACK TRACE =====
  java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:377)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
  	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355)
  	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315)
  	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:153)
  	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: com.comphenix.protocol.reflect.FieldAccessException: Field index must be within 0 - count
  	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:191)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:124)
  	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:59)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:80)
  	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:356)
  	at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
  	at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:56)
  	... 9 more
  Caused by: java.lang.IndexOutOfBoundsException: Out of bounds
  	... 16 more
            ===== DUMP =====
  Sender:
    com.comphenix.protocol.ProtocolLibrary@1f2bdd12[
      statistisc=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7e4cd909
      configExpectedMod=-1
      updater=com.comphenix.protocol.metrics.Updater@442e875c
      logger=org.bukkit.plugin.PluginLogger@4ab4919
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@5583f15e
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-a723278-5b92dc3,minecraftVersion=1.8}
      file=plugins/ProtocolLib-Spigot-3.6.0-SNAPSHOT.jar
      description=org.bukkit.plugin.PluginDescriptionFile@51a4bf7e
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2412c49e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@4ab4919
    ]
  Version:
    ProtocolLib v3.6.0-SNAPSHOT
  Server:
    git-Spigot-a723278-5b92dc3 (MC: 1.8)

**Comment by dmulloy2** [comment]
Still using the wrong version,

Version:
ProtocolLib v3.6.0-SNAPSHOT

is for 1.7.10.  Make sure you're using build 72 and don't have any other ProtocolLib or PacketWrapper jars.
