### ISSUE TITLE
Internal Error: Cannot enable ProtocolLib

### ISSUE THREAD

**Issue by TheAudioUnion** [dmulloy2/ProtocolLib#380]
[21:16:01 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.LinkageError: loader constraint violation: when resolving method "com.comphenix.protocol.PacketType.fromCurrent(Lcom/comphenix/protocol/PacketType$Protocol;Lcom/comphenix/protocol/PacketType$Sender;ILjava/lang/Class;)Lcom/comphenix/protocol/PacketType;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/comphenix/protocol/injector/netty/NettyProtocolRegistry, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/comphenix/protocol/PacketType, have different Class objects for the type com/comphenix/protocol/PacketType$Protocol used in the signature
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.associatePackets(NettyProtocolRegistry.java:94)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:84)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630)
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
        at java.lang.Thread.run(Unknown Source)
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@3a3d0043[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4cf21f17
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@25dd48f0
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@79e60929
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-9f26059-6aa0fa3,minecraftVersion=1.12}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@49bd8f77
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@68115b33
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@4f8e2acd
    ]
  Version:
    ProtocolLib v4.3.0
  Java Version:
    1.8.0_131
  Server:
    git-Spigot-9f26059-6aa0fa3 (MC: 1.12)

**Comment by dmulloy2** [comment]
> com.rylinaux.plugman

Don't use plugman with ProtocolLib.
