### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by checkplysgamer** [dmulloy2/ProtocolLib#40]
va:369) [Spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.jav
a:152) [Spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:458) [Spigot.jar:git-Spigot-1649]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28) [Spigot.jar:git-Spigot-1649]
Caused by: java.lang.UnsupportedClassVersionError: com/flyingblock/pcm/PcmMain :
 Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0
_71]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_71]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_
71]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:101) ~[Spigot.jar:git-Spigot-1649]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[Spigot.jar:git-Spigot-1649]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav
a:64) ~[Spigot.jar:git-Spigot-1649]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:129) ~[Spigot.jar:git-Spigot-1649]
        ... 6 more
[01:11:56 INFO]: [ProtocolLib] Loading ProtocolLib v3.6.2-SNAPSHOT
[01:11:56 INFO]: [ProtocolLib] Created default configuration.
[01:11:56 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilt
erManager.java:272)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(Pac
ketFilterBuilder.java:250)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilte
rBuilder.java:233)
        at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:20
2)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.ja
va:374)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.jav
a:152)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:458)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28)
  Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelInboundHa
ndler
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLibrary@46ed141f[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@f88bafd
      configExpectedMod=-1
      logger=org.bukkit.plugin.PluginLogger@59ac4002
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@1a1ee7c0
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1649,mi
necraftVersion=1.7.10}
      file=plugins\ProtocolLib (2).jar
      description=org.bukkit.plugin.PluginDescriptionFile@5589406a
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2a801fff
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@59ac4002
    ]
  Version:
    ProtocolLib v3.6.2-SNAPSHOT
  Server:
    git-Spigot-1649 (MC: 1.7.10)

[01:11:56 INFO]: [MinigamesLib] Loading MinigamesLib v1.13.1
[01:11:56 INFO]: [MGSkyWars] Loading MGSkyWars v1.5.2
[01:11:56 INFO]: [ProtocolLib] Enabling ProtocolLib v3.6.2-SNAPSHOT
[01:11:56 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:
355)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:417)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
a:476)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
java:394)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.jav
a:153)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:458)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28)
  Caused by: java.lang.NullPointerException
        at com.comphenix.protocol.reflect.FuzzyReflection.getConstructors(FuzzyR
eflection.java:599)
        at com.comphenix.protocol.reflect.FuzzyReflection.getConstructorList(Fuz
zyReflection.java:534)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructo
r(ChatExtensions.java:219)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions
.java:56)
        ... 9 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLibrary@46ed141f[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@f88bafd
      configExpectedMod=-1
      logger=org.bukkit.plugin.PluginLogger@59ac4002
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@1a1ee7c0
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1649,mi
necraftVersion=1.7.10}
      file=plugins\ProtocolLib (2).jar
      description=org.bukkit.plugin.PluginDescriptionFile@5589406a
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@2a801fff
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@59ac4002
    ]
  Version:
    ProtocolLib v3.6.2-SNAPSHOT
  Server:
    git-Spigot-1649 (MC: 1.7.10)

[01:11:56 INFO]: [ProtocolLib] Disabling ProtocolLib v3.6.2-SNAPSHOT
[01:11:56 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[01:11:56 INFO]: Preparing level "world"
[01:11:56 INFO]: -------- World Settings For [world] --------
[01:11:56 INFO]: View Distance: 10
[01:11:56 INFO]: Chunks to Grow per Tick: 650
[01:11:56 INFO]: Clear tick list: false
[01:11:56 INFO]: Experience Merge Radius: 3.0
[01:11:56 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[01:11:56 INFO]: Item Despawn Rate: 6000
[01:11:56 INFO]: Item Merge Radius: 2.5
[01:11:56 INFO]: Arrow Despawn Rate: 1200
[01:11:56 INFO]: Zombie Aggressive Towards Villager: true
[01:11:56 INFO]: Mob Spawn Range: 4
[01:11:56 INFO]: Anti X-Ray: true
[01:11:56 INFO]:        Engine Mode: 1
[01:11:56 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74,
82, 129, 130]
[01:11:56 INFO]:        Replace Blocks: [1, 5]
[01:11:56 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[01:11:56 INFO]: Alternative Hopper Ticking: false
[01:11:56 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[01:11:56 INFO]: Random Lighting Updates: false
[01:11:56 INFO]: Structure Info Saving: true
[01:11:56 INFO]: Max TNT Explosions: 100
[01:11:56 INFO]: Nerfing mobs spawned from spawners: false
[01:11:56 INFO]: Cactus Growth Modifier: 100%
[01:11:56 INFO]: Cane Growth Modifier: 100%
[01:11:56 INFO]: Melon Growth Modifier: 100%
[01:11:56 INFO]: Mushroom Growth Modifier: 100%
[01:11:56 INFO]: Pumpkin Growth Modifier: 100%
[01:11:56 INFO]: Sapling Growth Modifier: 100%
[01:11:56 INFO]: Wheat Growth Modifier: 100%
[01:11:56 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[01:11:56 INFO]: Sending up to 5 chunks per packet
[01:11:56 INFO]: Max Entity Collisions: 8
[01:11:56 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[01:11:56 INFO]: -------- World Settings For [world_nether] --------
[01:11:56 INFO]: View Distance: 10
[01:11:56 INFO]: Chunks to Grow per Tick: 650
[01:11:56 INFO]: Clear tick list: false
[01:11:56 INFO]: Experience Merge Radius: 3.0
[01:11:56 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[01:11:56 INFO]: Item Despawn Rate: 6000
[01:11:56 INFO]: Item Merge Radius: 2.5
[01:11:56 INFO]: Arrow Despawn Rate: 1200
[01:11:56 INFO]: Zombie Aggressive Towards Villager: true
[01:11:56 INFO]: Mob Spawn Range: 4
[01:11:56 INFO]: Anti X-Ray: true
[01:11:56 INFO]:        Engine Mode: 1
[01:11:56 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74,
82, 129, 130]
[01:11:56 INFO]:        Replace Blocks: [1, 5]
[01:11:56 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[01:11:56 INFO]: Alternative Hopper Ticking: false
[01:11:56 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[01:11:56 INFO]: Random Lighting Updates: false
[01:11:56 INFO]: Structure Info Saving: true
[01:11:56 INFO]: Max TNT Explosions: 100
[01:11:56 INFO]: Nerfing mobs spawned from spawners: false
[01:11:56 INFO]: Cactus Growth Modifier: 100%
[01:11:56 INFO]: Cane Growth Modifier: 100%
[01:11:56 INFO]: Melon Growth Modifier: 100%
[01:11:56 INFO]: Mushroom Growth Modifier: 100%
[01:11:56 INFO]: Pumpkin Growth Modifier: 100%
[01:11:56 INFO]: Sapling Growth Modifier: 100%
[01:11:56 INFO]: Wheat Growth Modifier: 100%
[01:11:56 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[01:11:56 INFO]: Sending up to 5 chunks per packet
[01:11:56 INFO]: Max Entity Collisions: 8
[01:11:56 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[01:11:56 INFO]: -------- World Settings For [world_the_end] --------
[01:11:56 INFO]: View Distance: 10
[01:11:56 INFO]: Chunks to Grow per Tick: 650
[01:11:56 INFO]: Clear tick list: false
[01:11:56 INFO]: Experience Merge Radius: 3.0
[01:11:56 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[01:11:56 INFO]: Item Despawn Rate: 6000
[01:11:56 INFO]: Item Merge Radius: 2.5
[01:11:56 INFO]: Arrow Despawn Rate: 1200
[01:11:56 INFO]: Zombie Aggressive Towards Villager: true
[01:11:56 INFO]: Mob Spawn Range: 4
[01:11:56 INFO]: Anti X-Ray: true
[01:11:56 INFO]:        Engine Mode: 1
[01:11:56 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74,
82, 129, 130]
[01:11:56 INFO]:        Replace Blocks: [1, 5]
[01:11:56 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[01:11:56 INFO]: Alternative Hopper Ticking: false
[01:11:56 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[01:11:56 INFO]: Random Lighting Updates: false
[01:11:56 INFO]: Structure Info Saving: true
[01:11:56 INFO]: Max TNT Explosions: 100
[01:11:56 INFO]: Nerfing mobs spawned from spawners: false
[01:11:56 INFO]: Cactus Growth Modifier: 100%
[01:11:56 INFO]: Cane Growth Modifier: 100%
[01:11:56 INFO]: Melon Growth Modifier: 100%
[01:11:56 INFO]: Mushroom Growth Modifier: 100%
[01:11:56 INFO]: Pumpkin Growth Modifier: 100%
[01:11:56 INFO]: Sapling Growth Modifier: 100%
[01:11:56 INFO]: Wheat Growth Modifier: 100%
[01:11:56 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[01:11:56 INFO]: Sending up to 5 chunks per packet
[01:11:56 INFO]: Max Entity Collisions: 8
[01:11:56 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[01:11:57 INFO]: Preparing start region for level 0 (Seed: -6543310926361983506)

[01:11:58 INFO]: Preparing spawn area: 76%
[01:11:58 INFO]: Preparing start region for level 1 (Seed: -6543310926361983506)

[01:11:58 INFO]: Preparing start region for level 2 (Seed: -6543310926361983506)

[01:11:58 INFO]: [MinigamesLib] Enabling MinigamesLib v1.13.1
[01:11:58 INFO]: Loaded MinigamesAPI. We're on v1_7_R4.
[01:11:58 ERROR]: [MinigamesLib] [MinigamesLib] - No Economy (Vault) dependency
found! Disabling Economy.
[01:11:59 INFO]: [MGSkyWars] Enabling MGSkyWars v1.5.2
[01:11:59 INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:11:59 INFO]: Done (2,611s)! For help, type "help" or "?"
>pl
[01:12:00 INFO]: Plugins (3): ProtocolLib, MinigamesLib, MGSkyWars
[01:12:01 INFO]: Found 0 arenas.
>

**Comment by dmulloy2** [comment]
Use [[http://ci.shadowvolt.com/job/ProtocolLib/10|Build 10]] for the protocol hack.
