### ISSUE TITLE
Unable to find NetworkManager

### ISSUE THREAD

**Issue by RenanMsV** [dmulloy2/ProtocolLib#407]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [ ] You're using the latest build for your server version : Yes
- [ ] This isn't an issue caused by another plugin : No
- [ ] You've checked for duplicate issues : Yes
- [ ] You didn't use `/reload` : Yes

Debug paste link:
 
```https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x33a02329, L:/158.69.116.80:40714 - R:/186.195.49.9:16026]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:311)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@6e12a49a[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5fd1900b
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@51882c3f
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@17c6cedc
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@6c0b9eca
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3f090a88
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2f703082
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2deb3fa7
        reporter=com.comphenix.protocol.ProtocolLib$1@e61bb9e
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Bukkit-9a1fc1e,minecraftVersion=1.12}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@49869941
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@436fb705
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@46901967
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.0)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@37f4c28e
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@436fb705[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@7a0f7ff3
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@130a1891, container=net.minecraft.server.v1_12_R1.ServerConnection@12fb0de4, previous=[AbstractBootstrap$PendingRegistrationPromise@67a950eb(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@3fdd2a36, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@7c5063cc, container=net.minecraft.server.v1_12_R1.ServerConnection@12fb0de4, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@360ec58f
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1b0de5ad
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@4dd7f060
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@32e6b415
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@72842d7b
      invoker=com.comphenix.protocol.injector.PacketFilterManager@6e12a49a
      reporter=com.comphenix.protocol.ProtocolLib$1@e61bb9e
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_112
  Server:
    git-Bukkit-9a1fc1e (MC: 1.12)```

Description and relevant errors:

**Comment by RenanMsV** [comment]
Works fine using ProtocolLib 4.3.0 version wich can be found here : https://www.spigotmc.org/resources/protocollib.1997/

Of course it works in Bukkit or Spigot as well. 

Version 4.3.0 can not be found here : https://dev.bukkit.org/projects/protocollib .
Maybe someone forgot to update there.
