### ISSUE TITLE
An error on Player join

### ISSUE THREAD

**Issue by nino3363** [dmulloy2/ProtocolLib#410]
java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xbf45af3e, L:/127.0.0.1:25565 - R:/127.0.0.1:54791]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@24db3faf[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1d1e85ca
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@26f86558
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3366b3a8
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@4e3dc42c
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@27e438f4
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@42534bf5
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2356c87e
        reporter=com.comphenix.protocol.ProtocolLib$1@442e4be4
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Bukkit-79e55b6,minecraftVersion=1.12.1}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@62374c07
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@271561da
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2b6b68
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.1)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@29b2c96b
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@271561da[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@46f311a
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@6c95b330, container=net.minecraft.server.v1_12_R1.ServerConnection@110fb859, previous=[AbstractBootstrap$PendingRegistrationPromise@5d6466ff(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@10f7e2a2, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@513acfbf, container=net.minecraft.server.v1_12_R1.ServerConnection@110fb859, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@3d9b78b1
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@4336b263
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@6cfbba55
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@6b3bd742
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@d837464
      invoker=com.comphenix.protocol.injector.PacketFilterManager@24db3faf
      reporter=com.comphenix.protocol.ProtocolLib$1@442e4be4
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_141
  Server:
    git-Bukkit-79e55b6 (MC: 1.12.1)

**Comment by games647** [comment]
Please try it with 4.3 located here: http://ci.dmulloy2.net/job/ProtocolLib/

**Comment by nino3363** [comment]
There is good gracias.
