### ISSUE TITLE
Error enabling ProtocolLib Spigot 1.8[LAST VERSION OF SPIGOT]

### ISSUE THREAD

**Issue by ElPapuh** [dmulloy2/ProtocolLib#414]
When i try to load ProtoclLib last update in Spigot,last update

this error appears:

[14:16:29 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.LinkageError: loader constraint violation: when resolving method "com.comphenix.protocol.ProtocolLibrary.getErrorReporter()Lcom/comphenix/protocol/error/ErrorReporter;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/comphenix/protocol/utility/MinecraftReflection, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/comphenix/protocol/ProtocolLibrary, have different Class objects for the type com/comphenix/protocol/error/ErrorReporter used in the signature
        at com.comphenix.protocol.utility.MinecraftReflection.getClassSource(MinecraftReflection.java:2012)
        at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:1978)
        at com.comphenix.protocol.utility.MinecraftReflection.getCraftEntityClass(MinecraftReflection.java:1786)
        at com.comphenix.protocol.utility.MinecraftReflection.handleLibigot(MinecraftReflection.java:290)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftPackage(MinecraftReflection.java:219)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1990)
        at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:745)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:58)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
        at java.lang.Thread.run(Unknown Source)
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@4f73a74[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@fb0656e
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@56cc63c1
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@eda92e1
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-c3c767f-33d5de3,minecraftVersion=1.8}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@4e910c43
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@451d5c7e
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@1695cc38
    ]
  Version:
    ProtocolLib v4.3.0
  Java Version:
    1.8.0_144
  Server:
    git-Spigot-c3c767f-33d5de3 (MC: 1.8)

**Comment by MiniDigger** [comment]
don't use plugman, do a full server restart.
