### ISSUE TITLE
incompatibility lilypad

### ISSUE THREAD

**Issue by anyperson** [dmulloy2/ProtocolLib#42]
https://github.com/LilyPad/Bukkit-CompatBungee/issues/1

The developer says that this is a problem ProtocolLib

[LilyPad-CompatBungee] Unhandled exception occured in onPacketSending(PacketEvent) for LilyPad-CompatBungee
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 0, Size: 0)
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:193) ~[ProtocolLib.jar:?]
        at lilypad.bukkit.compat.bungee.query.PacketToQueryIntercepter.onPacketSending(PacketToQueryIntercepter.java:32) ~[Bukkit-CompatBungee.jar:Unknown]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:368) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:334) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79) [ProtocolLib.jar:?]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1048) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.md_5.janus.Main.onPlayerMove(Main.java:93) [Janus.jar:?]
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:255) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
[04:18:19 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayOutCustomPayload@638c6165[
    a=BungeeCord
    b=UnpooledHeapByteBuf(ridx: 0, widx: 16, cap: 16/16)
  ]

Version #75 Jan 26

**Comment by dmulloy2** [comment]
This is an issue with LilyPad.  The payload byte array was replaced with the PacketDataSerializer in the payload classes:
````java
private String a;
private PacketDataSerializer b;
````
