### ISSUE TITLE
INTERNAL ERROR: Unable to inject incoming channel [id: 0xf94296e2, L:/**.**.**.**:43131 - R:/**.**.**.**:55129].

### ISSUE THREAD

**Issue by lunarenzox** [dmulloy2/ProtocolLib#431]
[12:08:29] [Netty Epoll Server IO #1/ERROR]: [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0xf94296e2, L:/172.17.0.6:43131 - R:/112.200.201.46:55129].
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xf94296e2, L:/172.17.0.6:43131 - R:/112.200.201.46:55129]
at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:226)
at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:392)
at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:379)
at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:311)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:748)
Dump:
manager:
com.comphenix.protocol.injector.PacketFilterManager@5938f7cd[
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@1c400fdd
packetListeners=[com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@691eea8f, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@588a74b3]
packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@137fb9dd
playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@72d35ab2
interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@6c4b5dba
inputBufferedPackets=[]
recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@70699909
sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1eb66788
hasClosed=false
classLoader=org.bukkit.plugin.java.PluginClassLoader@63c3a497
reporter=com.comphenix.protocol.ProtocolLib$1@76d8b826
server=CraftServer{serverName=CraftBukkit,serverVersion=git-Bukkit-9a1fc1e,minecraftVersion=1.12}
library=ProtocolLib v4.2.1
asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@7cd5f50b
knowsServerPackets=true
knowsClientPackets=true
phaseLoginCount=0
phasePlayingCount=3
packetCreation=false
spigotInjector=<null>
nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@35d4679b
pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@76dc8da8
hasRecycleDistance=true
minecraftVersion=(MC: 1.12.0)
loginPackets=com.comphenix.protocol.injector.LoginPackets@52c592f1
debug=false
]
Sender:
com.comphenix.protocol.injector.netty.ProtocolInjector@35d4679b[
injected=true
closed=false
playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@615396f0
bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@1ba2eb24, container=net.minecraft.server.v1_12_R1.ServerConnection@663b1ab6, previous=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@7fe079a2, current=com.comphenix.protocol.injector.netty.BootstrapList@6f855cff, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@637261e0, container=net.minecraft.server.v1_12_R1.ServerConnection@663b1ab6, previous=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@5d222992, current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@21f376fd
networkManagers=us.myles.ViaVersion.bukkit.platform.BukkitViaInjector$1@5d222992
sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@64d4b498
reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@1459a483
mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@58fb6123
bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@6205b05f
invoker=com.comphenix.protocol.injector.PacketFilterManager@5938f7cd
reporter=com.comphenix.protocol.ProtocolLib$1@76d8b826
debug=false
]
Version:
ProtocolLib v4.2.1
Java Version:
1.8.0_144
Server:
git-Bukkit-9a1fc1e (MC: 1.12)

**Comment by jolo613** [comment]
Same error have you figured out a way to fix? 👍

**Comment by keough99** [comment]
im having the same issue and its causing connection issues

**Comment by lunarenzox** [comment]
just download the protocollib spigot version

**Comment by beamerff** [comment]
same issue

**Comment by dmulloy2** [comment]
Update to 4.3.0 or 4.4.0.
