### ISSUE TITLE
Tribal's Issues

### ISSUE THREAD

**Issue by tribalknight** [dmulloy2/ProtocolLib#432]
java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0xb4e8d6ae, L:/192.99.38.169:41522 - R:/164.132.99.209:45496]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:235)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:401)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:388)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:476)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:255)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$3.channelRead(ProtocolInjector.java:171)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:120)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1f9da231[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7ae88392
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@74176949
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@3c4c7a38
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@4eb2dbaa
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@70f835fd
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3fea578a
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@5acf4f9b
        reporter=com.comphenix.protocol.ProtocolLib$1@602867f5
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-3d850ec-f46ccd7,minecraftVersion=1.12.2}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@9f912e2
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@42fc8450
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@345a1e9d
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@47685f62
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@42fc8450[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@5be1ea7d
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@19537c8d, container=net.minecraft.server.v1_12_R1.ServerConnection@1cc5b38a, previous=[AbstractBootstrap$PendingRegistrationPromise@4823106d(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@7c54d9af, previousLoaded=true, currentSet=true, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@7ee165bc
      networkManagers=[net.minecraft.server.v1_12_R1.NetworkManager@4f09c009, net.minecraft.server.v1_12_R1.NetworkManager@1f7911fd]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@45ba3a1c
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@30836b92
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@318bec03
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@662ae536
      invoker=com.comphenix.protocol.injector.PacketFilterManager@1f9da231
      reporter=com.comphenix.protocol.ProtocolLib$1@602867f5
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_112
  Server:
    git-Spigot-3d850ec-f46ccd7 (MC: 1.12.2)

[19:26:06 INFO]: <~Tribal> wot

I am new so I don't understand alot. All I know is that I insert issues.

**Comment by dmulloy2** [comment]
Update to 4.3.0 or 4.4.0.
