### ISSUE TITLE
Linkage Error

### ISSUE THREAD

**Issue by calebj320** [dmulloy2/ProtocolLib#437]
Debug: 
    https://pastebin.com/Eb3VFLt1
Description: I was setting my friends game mode to Creative Via Console and it spammed me with this Linken Error. It mentioned that "Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!" I am not using it for Multiple Server Instances.

**Comment by dmulloy2** [comment]
Gotta be honest, I haven't pinned this one down with any level of consistency. The multiple server thing worked for a few people

**Comment by kamcio96** [comment]
Same here:
```
[06:57:13] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to DosCraftCore v0.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:146) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:56) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "com/comphenix/protocol/events/PacketContainer"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_144]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_144]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_144]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_144]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_144]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_144]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	at pl.kamcio96.doscraft.doscraftcore.tab.PlayerTab.sendJoinPackets(PlayerTab.java:102) ~[?:?]
	at pl.kamcio96.doscraft.doscraftcore.tab.PlayerTab.update(PlayerTab.java:42) ~[?:?]
	at pl.kamcio96.doscraft.doscraftcore.data.DosCraftDataLoader.onJoin(DosCraftDataLoader.java:136) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paperspigot-1.8.8.jar:git-PaperSpigot-4c7641d]
	... 15 more
```
*PlayerTab.java:102*:
`PacketContainer packet = new PacketContainer(PacketType.Play.Server.PLAYER_INFO);`

**Comment by dmulloy2** [comment]
One potential cause of this is plugins including parts of ProtocolLib in their plugins

**Comment by kamcio96** [comment]
Definitely not. I have same plugins set on few servers (minigames) and it occurs randomly

**Comment by dmulloy2** [comment]
so your basis for rejecting a potential cause is that it happens (from your perspective) randomly?

**Comment by kamcio96** [comment]
Ohh, man. Really, Im working with plugins for ~4 years
Let's look into plugin list:
![img1](http://i.kamcio96.pl/aPZsi5lp8oCr.png)
`NoCheatPlus.jar` was downloaded from dev.bukkit page
One candidate is `kamcio-api.jar` (the size is larger than original plib, so it could contains it)

Okey, and now let's see the content:
![img1](http://i.kamcio96.pl/Ous3gp5CSLoy.png)

And `com` package:
![img1](http://i.kamcio96.pl/nyD2rPqXdub5.png)

Is it enough proof or should i find partial class shade?

**Comment by dmulloy2** [comment]
ok fine that wasn't it, you don't have to be a prick about it

**Comment by AlexDelpier02** [comment]
https://hastebin.com/unizajuxuq.md
I'm getting the same error. It should give problems with ProtocolSupport.
