### ISSUE TITLE
my players cannot connect to my server and get kicked by protocolib

### ISSUE THREAD

**Issue by beamerff** [dmulloy2/ProtocolLib#443]
it gives this error and says to report the issue 
[17:43:08 INFO]: Error Unable to inject incoming channel [id: 0x52d68ae9, L:/149.202.215.216:40244 - R:/39.44.152.91:59877]. (java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x52d68ae9, L:/149.202.215.216:40244 - R:/39.44.152.91:59877]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@40037d5c.
[17:43:08 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x52d68ae9, L:/149.202.215.216:40244 - R:/39.44.152.91:59877].
  **_If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:_**
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x52d68ae9, L:/149.202.215.216:40244 - R:/39.44.152.91:59877]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:235)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:401)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:388)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at java.lang.Thread.run(Thread.java:745)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@53627f2d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@571a1437
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@57da2635
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@5eb293d8
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@1ee90434
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@19551072
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1f3876e3
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@49bbc6bb
        reporter=com.comphenix.protocol.ProtocolLib$1@555e1a8f
        server=CraftServer{serverName=CraftBukkit,serverVersion=git-Bukkit-015bda4,minecraftVersion=1.12.2}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@32a72a3e
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@40037d5c
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@8d08b4e
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@1adf1f98
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@40037d5c[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@235ec474
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@162b38ac, container=net.minecraft.server.v1_12_R1.ServerConnection@43033379, previous=[AbstractBootstrap$PendingRegistrationPromise@5e543593(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@7c4f7dd5, previousLoaded=true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@336ec4a8, container=net.minecraft.server.v1_12_R1.ServerConnection@43033379, previous=[], current=null, previousLoaded=true, currentSet=false, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@692cb147
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@16abe95c
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@110d9f89
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@54835284
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@582967da
      invoker=com.comphenix.protocol.injector.PacketFilterManager@53627f2d
      reporter=com.comphenix.protocol.ProtocolLib$1@555e1a8f
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_112
  Server:
    git-Bukkit-015bda4 (MC: 1.12.2)

**Comment by dmulloy2** [comment]
Update to 4.3.0
