### ISSUE TITLE
PacketPlayInClientCommand Problems

### ISSUE THREAD

**Issue by aaomidi** [dmulloy2/ProtocolLib#46]
@EventHandler
        public void playerDeathEvent(PlayerDeathEvent event) {
            new BukkitRunnable() {
                @Override
                public void run() {
                    Player player = event.getEntity();

                    PacketContainer packetContainer = protocolManager.createPacket(PacketType.Play.Client.CLIENT_COMMAND);
                    packetContainer.getClientCommands()
                            .write(0, EnumWrappers.ClientCommand.PERFORM_RESPAWN);

                    try {
                        protocolManager.recieveClientPacket(player, packetContainer);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }.runTask(this);
        }

Throws a nice juicy error:
```
[17:04:04 WARN]: [PlayGround] Task #27 for PlayGround v1.0 generated an exception
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_25]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_25]
        at com.comphenix.protocol.wrappers.EnumWrappers.getEnum(EnumWrappers.java:100) ~[?:?]
        at com.comphenix.protocol.wrappers.EnumWrappers.initialize(EnumWrappers.java:76) ~[?:?]
        at com.comphenix.protocol.wrappers.EnumWrappers.getClientCommandClass(EnumWrappers.java:117) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.getClientCommands(PacketContainer.java:599) ~[?:?]
        at com.aaomidi.namechange.NameChange$1.run(NameChange.java:86) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-952179b-bc03b6f]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-952179b-bc03b6f]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-952179b-bc03b6f]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-bc03b6f]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-bc03b6f]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-bc03b6f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```

Error happens on 3.6.3

**Comment by aaomidi** [comment]
This is fixed in the latest dev build in CI.
