### ISSUE TITLE
Error Cannot update ProtocolLib. (java.lang.NullPointerException) occured in com.comphenix.protocol.updater.BukkitUpdater@133bb4b4

### ISSUE THREAD

**Issue by malonnnn** [dmulloy2/ProtocolLib#462]
Java:
```
$ java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

OS:  
```
$ uname -a
Linux localhost 4.15.12-x86_64-linode105 #1 SMP Thu Mar 22 02:13:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

Server:
```
ver
[13:05:19 INFO]: This server is running Paper version git-Paper-1391 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:05:19 INFO]: You are running the latest version
```

I get the following error about once a day

```
[12:57:34] [Thread-23/INFO]: Error Cannot update ProtocolLib. (java.lang.NullPointerException) occured in com.comphenix.protocol.updater.BukkitUpdater@133bb4b4.
[12:57:34] [Thread-23/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot update ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException
  	at java.io.StringReader.<init>(StringReader.java:50)
  	at org.json.simple.JSONValue.parse(JSONValue.java:50)
  	at com.comphenix.protocol.updater.BukkitUpdater.read(BukkitUpdater.java:335)
  	at com.comphenix.protocol.updater.BukkitUpdater$UpdateRunnable.run(BukkitUpdater.java:374)
  	at java.lang.Thread.run(Thread.java:748)
  Dump:
  Parameters: 
    com.comphenix.protocol.updater.BukkitUpdater$UpdateRunnable@617b04bf[
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1af4f371[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@12c898f5
        packetListeners=[PacketAdapter[plugin=LibsDisguises, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=10]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[BED[class=PacketPlayOutBed, id=48], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=54], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=39], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=40], COLLECT[class=PacketPlayOutCollect, id=75], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=76], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=78], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=63], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=3], SPAWN_ENTITY_PAINTING[class=PacketPlayOutSpawnEntityPainting, id=4], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=5], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=38], ANIMATION[class=PacketPlayOutAnimation, id=6], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=60], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=62]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=HIGH, packets=[ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=79], BED[class=PacketPlayOutBed, id=48], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=54], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=39], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=40], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=76], UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=78], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=63], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=5], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=38], ANIMATION[class=PacketPlayOutAnimation, id=6], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=60], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=61], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=62]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=73], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=27]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LibsDisguises, sending=ListeningWhitelist[priority=NORMAL, packets=[PLAYER_INFO[class=PacketPlayOutPlayerInfo, id=46]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=ChatControl, sending=ListeningWhitelist[priority=NORMAL, packets=[TAB_COMPLETE[class=PacketPlayOutTabComplete, id=14]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@2b2f28ef
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@310e5d97
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@cdc5fbc
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5a0561e2
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@83f421d
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@2db99489
        reporter=com.comphenix.protocol.ProtocolLib$1@4b1e5468
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-1391,minecraftVersion=1.12.2}
        library=ProtocolLib v4.4.0-SNAPSHOT-b390
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@542aac21
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=7
        packetCreation=true
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@35db2ed3
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@2a2becc0
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@292e69a2
        debug=false
      ]
  Sender:
    com.comphenix.protocol.updater.BukkitUpdater@133bb4b4[
      url=https://api.curseforge.com/servermods/files?projectIds=45564
      file=plugins/protocollib.jar
      thread=Thread[Thread-23,5,main]
      id=45564
      apiKey=<null>
      config=YamlConfiguration[path='', root='YamlConfiguration']
      updateFolder=update
      plugin=ProtocolLib v4.4.0-SNAPSHOT-b390
      versionName=<null>
      versionLink=<null>
      versionType=<null>
      versionGameVersion=<null>
      versionFileName=<null>
      type=NO_DOWNLOAD
      announce=true
      thread=<null>
      result=The updater found an update, and has readied it to be loaded the next time the server restarts/reloads.
      listeners=[com.comphenix.protocol.CommandProtocol$1@34960127]
    ]
  Version:
    ProtocolLib v4.4.0-SNAPSHOT-b390
  Java Version:
    1.8.0_161
  Server:
    git-Paper-1391 (MC: 1.12.2)

[12:57:34] [Server thread/INFO]: [ProtocolLib] The updater found an update, and has readied it to be loaded the next time the server restarts/reloads.
```

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/ProtocolLib/commit/1ddb7a00144cc90aa30057e5ede1595abaf7e795
