### ISSUE TITLE
IndexOutOfBounds with Custom Payload Packet

### ISSUE THREAD

**Issue by xdelsy** [dmulloy2/ProtocolLib#469]
https://pastebin.com/NaVP7Gv1

`[02:12:44] [Netty Epoll Server IO #2/INFO]: Error Unable to intercept a read client packet. (java.lang.IndexOutOfBoundsException: readerIndex: 13 (expected: 0 <= readerIndex <= writerIndex(0))) occured in com.comphenix.protocol.injector.netty.ChannelInjector@4c448e75. [m
[02:12:44] [Netty Epoll Server IO #2/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
 at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
 Stack Trace:
 java.lang.IndexOutOfBoundsException: readerIndex: 13 (expected: 0 <= readerIndex <= writerIndex(0))
   at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:73)
   at io.netty.buffer.AbstractByteBuf.resetReaderIndex(AbstractByteBuf.java:157)
   at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:537)
   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
   at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
   at java.lang.Thread.run(Thread.java:748)
 Dump:
 Parameters:
   io.netty.buffer.UnpooledHeapByteBuf@4cefd2e8[
     alloc=UnpooledByteBufAllocator(directByDefault: true)
array={14,1,0,14,0,0,1,0,0,54,1,0,0,10,0,0,10,0,17,86,105,97,82,101,119,105,110,100,49,95,56,116,111,49,95,57,2,0,4,100,97,116,97,0,0,9,0,4,108,111,114,101,8,0,0,0,2,0,43,-62,-89,55,-48,-108,-48,-66,-48,-79,-48,-80,-48,-78,-48,-69,-48,-75,-48,-67,-48,-72,-48,-75,32,-48,-72,32,-47,-125,-48,-76,-48,-80,-48,-69,-48,-75,-48,-67,-48,-72,-48,-75,0,17,-62,-89,55,-47,-126,-48,-66,-48,-78,-48,-80,-47,-128,-48,-66,-48,-78,8,0,11,100,105,115,112,108,97,121,78,97,109,101,0,42,-62,-89,102,-48,-93,-48,-65,-47,-128,-48,-80,-48,-78,-48,-69,-48,-75,-48,-67,-48,-72,-48,-75,32,-48,-68,-48,-80,-48,-77,-48,-80,-48,-73,-48,-72,-48,-67,-48,-66,-48,-68,2,0,2,105,100,0,54,0,10,0,7,100,105,115,112,108,97,121,9,0,4,76,111,114,101,8,0,0,0,2,0,43,-62,-89,55,-48,-108,-48,-66,-48,-79,-48,-80,-48,-78,-48,-69,-48,-75,-48,-67,-48,-72,-48,-75,32,-48,-72,32,-47,-125,-48,-76,-48,-80,-48,-69,-48,-75,-48,-67,-48,-72,-48,-75,0,17,-62,-89,55,-47,-126,-48,-66,-48,-78,-48,-80,-47,-128,-48,-66,-48,-78,8,0,4,78,97,109,101,0,42,-62,-89,102,-48,-93,-48,-65,-47,-128,-48,-80,-48,-78,-48,-69,-48,-75,-48,-67,-48,-72,-48,-75,32,-48,-68,-48,-80,-48,-77,-48,-80,-48,-73,-48,-72,-48,-67,-48,-66,-48,-68,0,0}
     tmpNioBuf=<null>
     refCnt=1
     readerIndex=0
     writerIndex=0
     markedReaderIndex=13
     markedWriterIndex=0
     maxCapacity=326
     swappedBuf=<null>
   ]
   manager:
     com.comphenix.protocol.injector.PacketFilterManager@7c3a618b[
       unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@579396d5
       packetListeners=[PacketAdapter[plugin=TShop, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInCloseWindow[8, legacy: 13], PacketPlayInWindowClick[7, legacy: 14], PacketPlayInCustomPayload[9, legacy: 23]], gamephase=PLAYING, options=[INTERCEPT_INPUT_BUFFER]}], PacketAdapter[plugin=MAVLibrary, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInUpdateSign[25, legacy: 18]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=React, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInKeepAlive[11, legacy: 0]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutSpawnEntityLiving[3, legacy: 15], PacketPlayOutSpawnEntity[0, legacy: 14], PacketPlayOutEntityMetadata[57, legacy: 28]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=CommonLib, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInChat[2, legacy: 1]], gamephase=PLAYING, options=[]}], PacketAdapter[plugin=React, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutKeepAlive[31, legacy: 0]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Spartan, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInTransaction[5, legacy: 15], PacketPlayInKeepAlive[11, legacy: 0], PacketPlayOutKeepAlive[31, legacy: 0], PacketPlayOutTransaction[17, legacy: 50]], gamephase=PLAYING, options=[]}, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInTransaction[5, legacy: 15], PacketPlayInKeepAlive[11, legacy: 0], PacketPlayOutKeepAlive[31, legacy: 0], PacketPlayOutTransaction[17, legacy: 50]], gamephase=PLAYING, options=[]}]]
       packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@7710cdf7
       playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@6534e71
       interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@102184ad
       inputBufferedPackets=[PacketPlayInCloseWindow[8, legacy: 13], PacketPlayInWindowClick[7, legacy: 14], PacketPlayInCustomPayload[9, legacy: 23]]
       recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@3d44a0b6
       sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4c4abd9c
       hasClosed=false
       classLoader=org.bukkit.plugin.java.PluginClassLoader@d1abdeb
reporter=com.comphenix.protocol.ProtocolLib$1@50f642a2
       server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-625bc00-186c351,minecraftVersion=1.11.2}
       library=ProtocolLib v4.2.0
       asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@5437f8c6
       knowsServerPackets=true
       knowsClientPackets=true
       phaseLoginCount=0
       phasePlayingCount=9
       packetCreation=true
       spigotInjector=<null>
       nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7d433e51
       pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@708af469
       hasRecycleDistance=true
       minecraftVersion=(MC: 1.11.2)
       loginPackets=com.comphenix.protocol.injector.LoginPackets@126fcc89
       debug=false
     ]
 Sender:
   com.comphenix.protocol.injector.netty.ChannelInjector@4c448e75[
     factory=com.comphenix.protocol.injector.netty.InjectionFactory@2811801a
     player=CraftPlayer{name=Trippsoul}
     updated=CraftPlayer{name=Trippsoul}
     playerName=Trippsoul
     playerConnection=net.minecraft.server.v1_11_R1.PlayerConnection@f9f00cd
     networkManager=net.minecraft.server.v1_11_R1.NetworkManager@63f88e33
     originalChannel=[id: 0x618c5dd3, *there was ip*]
     channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_11_R1.NetworkManager.channel], container=net.minecraft.server.v1_11_R1.NetworkManager@63f88e33, previous=[id: 0x618c5dd3, *there was ip*], current=com.comphenix.protocol.injector.netty.ChannelInjector$5@2f92d321, previousLoaded=true, currentSet=true, forceAccess=true]
     packetMarker={}
     currentEvent=<null>
     finalEvent=<null>
     scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@3d378d0e
     vanillaDecoder=us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler@de6c2b2
     vanillaEncoder=us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler@76743df6
     finishQueue=[]
     channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@7d433e51
     processor=com.comphenix.protocol.injector.NetworkProcessor@76f43da1
     injected=true
     closed=false
     cumulation=UnpooledHeapByteBuf(ridx: 0, widx: 0, cap: 326/326)
     singleDecode=false
     decodeWasNull=false
     first=true
     added=true
   ]
 Version:
   ProtocolLib v4.2.0
 Java Version:
   1.8.0_161
 Server:
   git-Spigot-625bc00-186c351 (MC: 1.11.2)`

**Comment by dmulloy2** [comment]
Not really sure why this would happen. Try updating to a dev build of ProtocolLib and let me know if it keeps happening.

**Comment by dmulloy2** [comment]
Looking into it further, it looks like the issue is caused by TShop trying to intercept the whole buffer for payload packets. I couldn't find the plugin online (custom?), but if it's absolutely necessary to intercept for the payload packet, there might be a workaround.

**Comment by xdelsy** [comment]
Perhaps everything is the same as written above. Also, tshop is a custom plugin that uses its own libraries, but the developer has stopped supporting this plugin.

I can not say which library the code or this adapter is. I'll try to find, but I can not exactly promise this :/
