### ISSUE TITLE
[1.12.2]ProtocolLib prevent players from logging in

### ISSUE THREAD

**Issue by keuin** [dmulloy2/ProtocolLib#474]
This morning I was configuring my new server and I installed a few plugins. After deleting two worlds with the plugin Multiverse-Core (the latest version), I couldn't login and if I remove all plugins except ProtocolLib I could do that, but there were some errors:

> [08:57:49 INFO]: Done (2.256s)! For help, type "help" or "?"
[08:57:49 INFO]: Timings Reset
[08:58:06 INFO]: Error Unable to inject incoming channel [id: 0x78355e28, L:/192.168.1.6:25565 - R:/192.168.1.1:6037]. (
java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x78355e28, L:/192.168.1.6:25565 - R:/192.168.
1.1:6037]) occured in com.comphenix.protocol.injector.netty.ProtocolInjector@3abad104.
[08:58:06 ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel [id: 0x78355e28, L:/192.168.1.6:2556
5 - R:/192.168.1.1:6037].
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find NetworkManager in [id: 0x78355e28, L:/192.168.1.6:25565 - R:/192.16
8.1.1:6037]
        at com.comphenix.protocol.injector.netty.InjectionFactory.findNetworkManager(InjectionFactory.java:209)
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromChannel(InjectionFactory.java:142)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$1.initChannel(ProtocolInjector.java:146)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:235)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:409)
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:396)
        at com.comphenix.protocol.injector.netty.ProtocolInjector$2.initChannel(ProtocolInjector.java:159)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Unknown Source)
  Dump:
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@481e5893[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@4f187e98
        packetListeners=[]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@5f6ce334
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@2c8cb1ce
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@166cbe0c
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@1a8cfee7
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2241dbc1
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@14ca6b4c
        reporter=com.comphenix.protocol.ProtocolLib$1@6b8a1c86
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-1441,minecraftVersion=1.12.2}
        library=ProtocolLib v4.2.1
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6563fd18
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=0
        packetCreation=false
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@3abad104
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@764be668
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.12.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@2ba20ad1
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ProtocolInjector@3abad104[
      injected=true
      closed=false
      playerFactory=com.comphenix.protocol.injector.server.TemporaryPlayerFactory@300b0232
      bootstrapFields=[VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAcces
sor@2639fb18, container=net.minecraft.server.v1_12_R1.ServerConnection@54a0f3fe, previous=[AbstractBootstrap$PendingRegi
strationPromise@1e5ebea(success)], current=com.comphenix.protocol.injector.netty.BootstrapList@14e811d5, previousLoaded=
true, currentSet=true, forceAccess=false], VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$Sy
nchronizedFieldAccessor@7de0d96b, container=net.minecraft.server.v1_12_R1.ServerConnection@54a0f3fe, previous=[], curren
t=com.comphenix.protocol.injector.netty.BootstrapList@2e8cea2a, previousLoaded=true, currentSet=true, forceAccess=false]
, VolatileField [accessor=com.comphenix.protocol.reflect.accessors.Accessors$SynchronizedFieldAccessor@18eeaa, container
=net.minecraft.server.v1_12_R1.ServerConnection@54a0f3fe, previous=[], current=null, previousLoaded=true, currentSet=fal
se, forceAccess=false]]
      injectionFactory=com.comphenix.protocol.injector.netty.InjectionFactory@54aa31c5
      networkManagers=[]
      sendingFilters=com.comphenix.protocol.concurrency.PacketTypeSet@2ffa81ba
      reveivedFilters=com.comphenix.protocol.concurrency.PacketTypeSet@666ef3d5
      mainThreadFilters=com.comphenix.protocol.concurrency.PacketTypeSet@21c43c0c
      bufferedPackets=com.comphenix.protocol.concurrency.PacketTypeSet@246505e8
      invoker=com.comphenix.protocol.injector.PacketFilterManager@481e5893
      reporter=com.comphenix.protocol.ProtocolLib$1@6b8a1c86
      debug=false
    ]
  Version:
    ProtocolLib v4.2.1
  Java Version:
    1.8.0_161
  Server:
    git-Paper-1441 (MC: 1.12.2)
[08:58:06 INFO]: UUID of player Keuin is a8abcd0a-cd65-3477-9b98-3a2da386f32c
[08:58:06 INFO]: Keuin[/192.168.1.1:6037] logged in with entity id 167 at ([world]-24.266283453684622, 78.0, 262.3296639343323)

P.S. 
1) All plugins and the spigot I'm using are latest.
2) Plugins I'm using are:

> AuthMe-5.4.0.jar
dynmap-2.5.jar
Multiverse-Core-2.5.0.jar
PlotSquared-3.5.0u2.jar
ProtocolLib.jar
WorldBorder.jar

**Comment by keuin** [comment]
This problem was caused by the wrong configuration of plugin Multiverse-Core. After deleting its data directory Multiverse-Core, the problem disappeared.
