### ISSUE TITLE
Crash Players on 1.8, if Spigot 1.12.2 

### ISSUE THREAD

**Issue by Modiexi** [dmulloy2/ProtocolLib#479]
Hello. 
I have Protocollib (Last build), and ProtocolSupport.
When player in 1.8 version touch player in 1.12.2, player has been kicked...
Sry for my English.
![image](https://user-images.githubusercontent.com/40461701/41716468-33920a76-755f-11e8-82c7-ceb32eb764f0.png)

**Comment by Modiexi** [comment]
[ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[15:08:36 WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_12_R1.PacketPlayOutSpawnEntityLiving@201c0ca4 to Mtest
java.lang.NullPointerException: player cannot be null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:50) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.getPlayerConnection(ChannelInjector.java:699) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:654) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.lambda$scheduleMainThread$1(ChannelInjector.java:483) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[15:08:36 WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[15:08:36 WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_12_R1.PacketPlayOutEntityTeleport@14004431 to Mtest
java.lang.NullPointerException: player cannot be null!
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:50) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.getPlayerConnection(ChannelInjector.java:699) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:654) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.lambda$scheduleMainThread$1(ChannelInjector.java:483) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-2f3ed3b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
