### ISSUE TITLE
Builds #404 and #405 Causing Libsdisguises errors just a heads up

### ISSUE THREAD

**Issue by axemwa** [dmulloy2/ProtocolLib#495]
Just a heads up
I think builds #404 and #405 are causing these errors for libsdisguises

![image](https://user-images.githubusercontent.com/37608633/43041705-46184786-8da7-11e8-9899-e52f0d667142.png)

**Comment by axemwa** [comment]
I realize that these are just experimental builds for 1.13 but thought I would inform you anyway just incase it still might be helpful

**Comment by dmulloy2** [comment]
Thanks, should be fixed in https://github.com/dmulloy2/ProtocolLib/commit/e827a3dd1f7f30cf1634f0e504f06be85df1399e

**Comment by axemwa** [comment]
Awesome thanx, that was quick! Great work 🥇

**Comment by mibby** [comment]
@dmulloy2 Issue not fully fixed with commit https://github.com/dmulloy2/ProtocolLib/commit/e827a3dd1f7f30cf1634f0e504f06be85df1399e?

This is with build 406.

```
[06:45:32] [Server thread/ERROR]: [LibsDisguises] Unhandled exception occured in onPacketSending(PacketEvent) for LibsDisguises
java.lang.NullPointerException: null
	at com.comphenix.protocol.utility.MinecraftReflection.getNullableNMS(MinecraftReflection.java:2027) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getFluidTypeClass(MinecraftReflection.java:1156) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.ImmutableDetector.isImmutable(ImmutableDetector.java:101) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.ImmutableDetector.canClone(ImmutableDetector.java:59) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.getFirstCloner(AggregateCloner.java:235) ~[?:?]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:252) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1051) ~[?:?]
	at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:48) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:200) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:148) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1184) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:163) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:947) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1509]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1509]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[06:45:32] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutEntityStatus@5753a61f[
    a=923
    b=23
  ]
```

Using build 403, everything seems fine.
