### ISSUE TITLE
ProtocolLib + FastLogin Error

### ISSUE THREAD

**Issue by shadoweG** [dmulloy2/ProtocolLib#497]
I have an error using ProtocolLib + FastLogin
McVer: Spigot 1.13 Latest
ProtocolLib; Latest for 1.13
When i trying to join console showing Error: https://pastebin.com/HuXEESpP
Is it the fault of ProtocolLib or FastLogin?

**Comment by pawel8273** [comment]
I am also having this error.
Server Version: Spigot 1.13 - build: 1681
ProtocolLib: build in CI : [#408 ](http://ci.dmulloy2.net/job/ProtocolLib/408/)

Console returned the following error: [https://pastebin.com/y9Cwd88G](https://pastebin.com/y9Cwd88G) 
What is at fault? Spigot, ProtocolLib or FastLogin? Maybe for example: ViaVersion, ViaBackwards or AuthMe?

**Comment by david50407** [comment]
Same here with null reference error
Spigot: 1.13 git-Spigot-0b44fa0-3599dbe
ProtocolLib: build 408 on CI

Log:
```
[20:05:56 WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_13_R1.PacketLoginOutEncryptionBegin@33ef708a to null
java.lang.IllegalArgumentException: Unable to find handle in net.minecraft.server.v1_13_R1.NetworkManager
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:261) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.comphenix.protocol.utility.MinecraftMethods.getNetworkManagerHandleMethod(MinecraftMethods.java:107) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:650) [ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:636) [ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) [ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) [ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) [ProtocolLib.jar:4.4.0-SNAPSHOT-b408]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.sentEncryptionRequest(ProtocolLibLoginSource.java:89) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.setOnlineMode(ProtocolLibLoginSource.java:49) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:51) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:16) [FastLogin.jar:?]
        at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:57) [FastLogin.jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:40) [FastLogin.jar:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.jar:git-Spigot-0b44fa0-3599dbe]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar:git-Spigot-0b44fa0-3599dbe]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
