### ISSUE TITLE
Players get disconnected

### ISSUE THREAD

**Issue by x1p** [dmulloy2/ProtocolLib#501]
Players get disconnected from the server he is on and does fallback to the lobby (hub). Error appears on server (and bungee).

Setup:
BungeeCord build 1344 (latest at this moment)
PaperSpigot 1.12.2 build 1528
Protocollib build 403
ViaVersion 1.4.2 build 221
ViaBackwards 2.3.2 dev 59

Error on server:
`
[22:59:21] [Server thread/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[22:59:21] [Server thread/WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_12_R1.PacketPlayOutSpawnEntityLiving@212e70cd to pikachme
java.lang.NullPointerException: player cannot be null!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.12.2.jar:git-Paper-1528]
	at com.comphenix.protocol.utility.MinecraftFields.getPlayerConnection(MinecraftFields.java:50) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.getPlayerConnection(ChannelInjector.java:697) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:652) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.lambda$scheduleMainThread$1(ChannelInjector.java:481) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1528]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1528]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) ~[patched_1.12.2.jar:git-Paper-1528]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1528]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1528]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1528]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
`
Error on bungee:
`
22:59:21 [SEVERE] [Player123123] <-> DownstreamBridge <-> [Creative] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by x1p** [comment]
Thanks for the quick response.
1.12 is dead imho.
