### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [dmulloy2/ProtocolLib#512]

**Comment by dmulloy2** [comment]
Should work as-is, no?

**Comment by libraryaddict** [comment]
Nothing broke in my update to 1.13.1, @TheIntelloBox can you elaborate on this?

**Comment by smmmadden** [comment]
Using Spigot 1.13.1 with ProtocolLib build 415 - we see this:
![image](https://user-images.githubusercontent.com/10309346/44637748-f5d3b300-a980-11e8-8323-27be944a3dfc.png)

**Comment by FrankHeijden** [comment]
b15:
```
[15:49:23] [Server thread/INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.29-dev
[15:49:23] [Server thread/ERROR]: Error occurred while enabling ProtocolSupport v4.29-dev (Is it up to date?)
java.lang.IllegalStateException: Access to implementation before detect
	at protocolsupport.zplatform.ServerPlatform.get(ServerPlatform.java:37) ~[?:?]
	at protocolsupport.ProtocolSupport.onEnable(ProtocolSupport.java:136) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[15:49:23] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0-SNAPSHOT-b415
[15:49:23] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
```

**Comment by MiniDigger** [comment]
@FrankHeijden your issue is not related to protocollib, report it to protocolsupport

**Comment by FrankHeijden** [comment]
damn. 😂 second time im confusing protocolsupport for plib

**Comment by smmmadden** [comment]
Using PaperSpigot Build 199 thru 209 (current) - seeing warning in log.
[09:06:58 INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0-SNAPSHOT-b415
[09:06:58 WARN]: [ProtocolLib] Version (MC: 1.13.1) has not yet been tested! Proceed with caution.
