### ISSUE TITLE
Erreur ProtocolLib

### ISSUE THREAD

**Issue by XxWill33xX** [dmulloy2/ProtocolLib#52]
Bonjour,

J'utilise actuellement ProtocolLib V3.6.0 (pour serveur 1.8 vu que je suis en 1.8) et j'ai des erreurs que je ne comprends pas, il apparaît en rouge sur la liste de plugins (/plugins), voici les erreurs:

[20:54:52] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.6.0-SNAPSHOT
[20:54:52] [Server thread/INFO]: [ProtocolLib] Created default configuration.
[20:54:52] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.8.0) has not yet been tested! Proceed with caution.
[20:54:52] [Server thread/WARN]: [ProtocolLib] [MinecraftReflection] Cannot find standard Minecraft library location. Assuming MCPC.
[20:54:53] [Server thread/ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at http://dev.bukkit.org/server-mods/protocollib/ with the following data:
===== STACK TRACE =====
java.lang.NoClassDefFoundError: net/minecraft/util/io/netty/channel/ChannelInboundHandler
at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:264)
at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBu​ilder.java:250)
at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.ja​va:233)
at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216)
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:296)
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152)
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.io.netty.channel.ChannelInboundHandler
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
... 8 more
===== DUMP =====
Parameters:
[NULL]
Sender:
com.comphenix.protocol.ProtocolLibrary@ad3a810[
statistisc=<null>
backgroundCompiler=<null>
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7317849d
configExpectedMod=-1
updater=com.comphenix.protocol.metrics.Updater@d039a73
logger=org.bukkit.plugin.PluginLogger@6790fab1
redirectHandler=<null>
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
skipDisable=false
isEnabled=false
loader=org.bukkit.plugin.java.JavaPluginLoader@42d2d985
server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-b73910a-726656b,minecraftVersion=1.8}
file=plugins/ProtocolLib-Spigot-3.6.0-SNAPSHOT.jar
description=org.bukkit.plugin.PluginDescriptionFile@5bbf1aae
dataFolder=plugins/ProtocolLib
classLoader=org.bukkit.plugin.java.PluginClassLoader@13709ce9
naggable=true
ebean=<null>
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=org.bukkit.plugin.PluginLogger@6790fab1
]
Version:
ProtocolLib v3.6.0-SNAPSHOT
Server:
git-Spigot-b73910a-726656b (MC: 1.8)

Pouvez-vous m'aider ?

**Comment by dmulloy2** [comment]
Make sure you're using the latest version of ProtocolLib from here: http://ci.shadowvolt.com/job/ProtocolLib/
