### ISSUE TITLE
1.13.1: WORLD_PARTICLES gives a NPE on Particle.fromHandle

### ISSUE THREAD

**Issue by kangarko** [dmulloy2/ProtocolLib#521]
Listening to sending the packet

```
PacketType.Play.Server.WORLD_PARTICLES
```

and doing

```
event.getPacket().getNewParticles().read(0)
```

results in the following error:

```
java.lang.NullPointerException
[18:04:48 WARN]: 	at com.comphenix.protocol.wrappers.WrappedParticle.fromHandle(WrappedParticle.java:94)
[18:04:48 WARN]: 	at com.comphenix.protocol.wrappers.Converters$3.getSpecific(Converters.java:92)
[18:04:48 WARN]: 	at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:39)
[18:04:48 WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227)
[18:04:48 WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
[18:04:48 WARN]: 	at me.kangarko.mp.listener.PacketListener$1.onPacketSending(PacketListener.java:31)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[18:04:48 WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[18:04:48 WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:200)
[18:04:48 WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:163)
[18:04:48 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1487)
[18:04:48 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1460)
```

ProtocolLib version 4.4.0-SNAPSHOT-b415
PaperSpigot git-Paper-245 (MC: 1.13.1)

**Comment by dmulloy2** [comment]
@kangarko issue should be fixed in latest dev build, let me know
