### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by goldberg012** [dmulloy2/ProtocolLib#53]
Stack Trace:
  java.lang.ExceptionInInitializerError
  	at com.comphenix.protocol.ProtocolLibrary.onEnable(ProtocolLibrary.java:356)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
  	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
  	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
  	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
  	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:459)
  	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136)
  	at net.minecraft.world.World.<init>(World.java:350)
  	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
  	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
  	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
  	at java.lang.Thread.run(Unknown Source)
  Caused by: java.lang.NullPointerException
  	at com.comphenix.protocol.reflect.FuzzyReflection.getConstructors(FuzzyReflection.java:599)
  	at com.comphenix.protocol.reflect.FuzzyReflection.getConstructorList(FuzzyReflection.java:534)
  	at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:219)
  	at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:56)
  	... 14 more
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLibrary@3c754214[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=<null>
      configExpectedMod=-1
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@56a4ab8f
      server=CraftServer{serverName=Cauldron-MCPC-Plus,serverVersion=git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213,minecraftVersion=1.7.10}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@23a0f423
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@6e431001
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@2ab42a71
    ]
  Version:
    ProtocolLib v3.6.3-SNAPSHOT
  Server:
    git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213 (MC: 1.7.10)

**Comment by dmulloy2** [comment]
Try using build 10 for 1.7.10: http://ci.shadowvolt.com/job/ProtocolLib/10/
