### ISSUE TITLE
Erro on loading on 1.13

### ISSUE THREAD

**Issue by zenandreas** [dmulloy2/ProtocolLib#532]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link:

[10:49:15] [Server thread/WARN]: 	at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:86)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[10:49:15] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1396)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1369)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(PlayerChunk.java:121)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:63)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:261)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:287)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:385)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[10:49:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[10:49:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

Description and relevant errors:

I have latest protocollib installed as well

**Comment by AngieC233** [comment]
Can confirmed having the same issues when server load up and stop. Using latest spigot version; protocoLib 4.4.0, tried latest version #422 from Jenkins. Same errors showing. Not sure if Orebfuscator that is causing the issue or ProtocoLib though.  
Here are the errors:
https://pastebin.com/KRTaX7fa
https://pastebin.com/F2BC2vn2
