### ISSUE TITLE
Unable to die falling from very high up in survival mode

### ISSUE THREAD

**Issue by smmmadden** [dmulloy2/ProtocolLib#536]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._
I tested in vanilla with 1.13.2 and no plugins and I was able to die from falling in less than 30 blocks.

Make sure you've done the following:
- [X ] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X ] You've checked for duplicate issues
- [X] You didn't use `/reload`
Same setup on PaperSpigot 1.13.1 works
PaperSpigot: 1.13.2 build 403 - I can enable fly in survival mode, go up to Y=300 and release to fall but NOT die.  Reported on PaperSpigot discord, and they believe it might be this plugin since its the only warning I got on startup.

Debug paste link:
nothing generated even with debug and detail set to true

Description and relevant errors: (just startup warning for ProtocolLib)
https://hastebin.com/oxigebanud.md

EDIT: after posting an error appeared.
[22:38:40 WARN]: [ProtocolLib] Could not submit plugin stats of ProtocolLib
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/submitData/bukkit
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_181]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_181]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_181]
        at com.comphenix.protocol.metrics.Metrics.sendData(Metrics.java:322) ~[?:?]
        at com.comphenix.protocol.metrics.Metrics.access$300(Metrics.java:38) ~[?:?]
        at com.comphenix.protocol.metrics.Metrics$2.run(Metrics.java:277) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by smmmadden** [comment]
closing - was able to rule out protocollib completely in a vanilla world with only luckperms and essentialsx.  So appears to be an essentialsx issue, not here.
