### ISSUE TITLE
error with plugins

### ISSUE THREAD

**Issue by Vulann** [dmulloy2/ProtocolLib#547]
Hello I meet the following error with the plugins, if I could have help to solve it! Thank you for bringing me an answer! :)

`[Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[Server thread/ERROR]: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/Plugin;)V from class com.comphenix.protocol.ProtocolLib initializing ProtocolLib v4.4.0 (Is it up to date?)
java.lang.IllegalAccessError: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/Plugin;)V from class com.comphenix.protocol.ProtocolLib
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:155) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [faction.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [faction.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by dmulloy2** [comment]
Working on a structural change to fix this in 4.5.0
