### ISSUE TITLE
[Craft Scheduler Thread - 3/WARN]: [Landlord] Failed to get resource info from spiget.org

### ISSUE THREAD

**Issue by bluebit27** [dmulloy2/ProtocolLib#548]
java.lang.NumberFormatException: For input string: ".79"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_72]
	at java.lang.Integer.parseInt(Integer.java:569) ~[?:1.8.0_72]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_72]
	at biz.princeps.landlord.util.Updater$1.updateAvailable(Updater.java:34) ~[Landlord-latest.jar:?]
	at org.inventivetalent.update.spiget.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:101) [Landlord-latest.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by bluebit27** [comment]
let me know when its fixed

**Comment by MiniDigger** [comment]
This has nothing to do with protocollib.
This error is caused by landlord.
