### ISSUE TITLE
Crash on login to server

### ISSUE THREAD

**Issue by Mayzone** [dmulloy2/ProtocolLib#549]
I use spigot 1.13.2 r1 because thats my only option with dhost
protocollib 4.4.0
`
[14:30:55] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ProtocolLib v4.4.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:344) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:54) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
Caused by: java.lang.NoClassDefFoundError: com.comphenix.protocol.injector.PacketConstructor (initialization failure)
at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96) ~[?:1.8.0_192]
at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]
at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]
at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.onPrePlayerJoin(PacketFilterManager.java:1007) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.access$600(PacketFilterManager.java:77) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager$4.onPrePlayerJoin(PacketFilterManager.java:981) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
... 14 more
Caused by: java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError
at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.(PacketConstructor.java:62) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.(PacketConstructor.java:45) ~[?:?]
at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]
at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]
at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:532) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:130) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
... 8 more
Caused by: java.lang.ExceptionInInitializerError
at java.lang.J9VMInternals.ensureError(J9VMInternals.java:146) ~[?:1.8.0_192]
at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:135) ~[?:1.8.0_192]
at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_192]
at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843) ~[?:1.8.0_192]
at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.(PacketConstructor.java:62) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.(PacketConstructor.java:45) ~[?:?]
at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]
at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]
at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:532) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:130) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
... 8 more
Caused by: java.lang.IllegalArgumentException: Unable to find findStatistic in net.minecraft.server.v1_13_R2.StatisticList
at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280) ~[?:?]
at com.comphenix.protocol.wrappers.WrappedStatistic.(WrappedStatistic.java:22) ~[?:?]
at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_192]
at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843) ~[?:1.8.0_192]
at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.(PacketConstructor.java:62) ~[?:?]
at com.comphenix.protocol.injector.PacketConstructor.(PacketConstructor.java:45) ~[?:?]
at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]
at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]
at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:532) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:130) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
... 8 more`

other errors i think holographicdisplay
`
[14:30:40] [Server thread/WARN]: [HolographicDisplays] Unable to get a stack trace element, please inform the developer. You will only see this error once and a fallback method will be used.
java.lang.NoSuchMethodException: java.lang.Throwable.getStackTraceDepth()
at java.lang.Class.newNoSuchMethodException(Class.java:562) ~[?:1.8.0_192]
at java.lang.Class.throwExceptionOrReturnNull(Class.java:1195) ~[?:1.8.0_192]
at java.lang.Class.getMethodHelper(Class.java:1259) ~[?:1.8.0_192]
at java.lang.Class.getDeclaredMethod(Class.java:931) ~[?:1.8.0_192]
at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.init(ReflectMethod.java:36) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectMethod.invoke(ReflectMethod.java:42) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.util.reflection.ReflectionUtils.getStackTraceElement(ReflectionUtils.java:58) [HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.EntityNMSArmorStand.getId(EntityNMSArmorStand.java:157) [HolographicDisplays.jar:?]
at net.minecraft.server.v1_13_R2.PacketPlayOutEntityTeleport.(SourceFile:22) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.EntityNMSArmorStand.setLocationNMS(EntityNMSArmorStand.java:222) [HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:112) [HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) [HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) [HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) [HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) [HolographicDisplays.jar:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

[14:30:40] [Server thread/WARN]: [HolographicDisplays] Task #50 for HolographicDisplays v2.3.1 generated an exception
java.lang.NoSuchMethodError: net/minecraft/server/v1_13_R2/WorldServer.getChunkProviderServer()Lnet/minecraft/server/v1_13_R2/ChunkProviderServer; (loaded from file:/home/minecraft/servers/mine206386/spigotmc-1.13.2-R0.1.jar by sun.misc.Launcher$AppClassLoader@9c2b4c3b) called from class com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl (loaded from file:/home/minecraft/servers/mine206386/plugins/HolographicDisplays.jar by org.bukkit.plugin.java.PluginClassLoader@2c95851c).
at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.addEntityToWorld(NmsManagerImpl.java:125) ~[?:?]
at com.gmail.filoghost.holographicdisplays.nms.v1_13_R2.NmsManagerImpl.spawnNMSArmorStand(NmsManagerImpl.java:113) ~[?:?]
at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.spawn(CraftTextLine.java:104) ~[?:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.spawnEntities(CraftHologram.java:314) ~[?:?]
at com.gmail.filoghost.holographicdisplays.object.CraftHologram.refreshAll(CraftHologram.java:261) ~[?:?]
at com.gmail.filoghost.holographicdisplays.task.StartupLoadHologramsTask.run(StartupLoadHologramsTask.java:38) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigotmc-1.13.2-R0.1.jar:git-Spigot-1dc156c-4b84363]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]
[14:30:40] [Server thread/INFO]: (RandomTP) 0 portals were loaded[m
[14:30:40] [Server thread/INFO]: (RandomTP) 0 sign was loaded[m
[14:30:40] [Server thread/INFO]: (RandomTP) plugin adapted to package v1_13_R2[m
[14:30:40] [Server thread/INFO]: (RandomTP) the plugin has been successfully loaded & enabled[m
[14:30:40] [Server thread/INFO]: [Jobs] Successfully linked with Vault.
[14:30:41] [Server thread/INFO]: FurnitureLib load Models(34): Barrels,BlackBoard,CactusPlant,Camera,CampChair,CandyCane,Catapult,Chair,ChristmasTree,Crossbow,Fence,FishTank,GraveStone,Hammock,HumanSkeleton,JB-Chair1,JB-Parkbank1,Lantern,Log,MailBox,SchoolChair,SchoolTable,SleepingBag,SnowGolem,Sofa,Sunshade,TV,Table,Tent1,TornJailBedA,TornTableB,Trunk,Wardrobe,WaxCandle[m
[14:30:41] [Server thread/INFO]: GroupManager - INFO - Bukkit Permissions Updated!
[14:30:43] [Server thread/INFO]: [Citizens] Loaded 4 NPCs.
[14:30:45] [Server thread/INFO]: [VotingPlugin] Successfully hooked into vault economy!
[14:30:45] [Server thread/INFO]: [VotingPlugin] Hooked into vault permissions
[14:30:47] [Craft Scheduler Thread - 10/INFO]: [VotingPlugin] VotingPlugin has an update available! Your Version: 5.16.1 New Version: 5.17.1 Use /av download to get the latest update!
[14:30:51] [User Authenticator #1/INFO]: UUID of player Mayzone is 26e81705-c68f-4d10-b67e-53aefa4890fe`

**Comment by Mayzone** [comment]
> ProtocolLib Dump
Timestamp: 12/18/18 15:38:37

ProtocolLib Version: ProtocolLib v4.4.0
Bukkit Version: 1.13.2-R0.1-SNAPSHOT
Server Version: git-Spigot-1dc156c-4b84363 (MC: 1.13.2)
Java Version: 1.8.0_192

ProtocolLib: com.comphenix.protocol.ProtocolLib@d8048e01[
  statistics=com.comphenix.protocol.metrics.Statistics@f23d5755
  backgroundCompiler=com.comphenix.protocol.reflect.compiler.BackgroundCompiler@7a15665
  packetTask=2
  tickCounter=20592
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@57d1f6c
  configExpectedMod=1
  updater=com.comphenix.protocol.updater.SpigotUpdater@f27b52e4
  redirectHandler=com.comphenix.protocol.ProtocolLib$2@3b0c60e7
  commandProtocol=com.comphenix.protocol.CommandProtocol@8816d446
  commandPacket=com.comphenix.protocol.CommandPacket@a660da88
  commandFilter=com.comphenix.protocol.CommandFilter@34f49496
  packetLogging=com.comphenix.protocol.PacketLogging@71e541cf
  skipDisable=false
  isEnabled=true
  loader=org.bukkit.plugin.java.JavaPluginLoader@a0951a79
  server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1dc156c-4b84363,minecraftVersion=1.13.2}
  file=plugins/ProtocolLib.jar
  description=org.bukkit.plugin.PluginDescriptionFile@e319ea17
  dataFolder=plugins/ProtocolLib
  classLoader=org.bukkit.plugin.java.PluginClassLoader@ad17d568
  naggable=true
  newConfig=YamlConfiguration[path='', root='YamlConfiguration']
  configFile=plugins/ProtocolLib/config.yml
  logger=org.bukkit.plugin.PluginLogger@71c00467
]
Manager: com.comphenix.protocol.injector.PacketFilterManager@bb6599e2[
  unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@57d1f6c
  packetListeners=[PacketAdapter[plugin=MobHunting, sending=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=21], SET_SLOT[class=PacketPlayOutSetSlot, id=23]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=38]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=FurnitureLib, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=MyPet, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=2]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=FurnitureLib, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=HIGHEST, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=26]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=MyPet, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=80], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=41], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=57], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=42], VEHICLE_MOVE[class=PacketPlayOutVehicleMove, id=43]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
  packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@310812b
  playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@65509363
  interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@61643c4e
  inputBufferedPackets=[]
  recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@fc95e6df
  sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@9f546213
  hasClosed=false
  classLoader=org.bukkit.plugin.java.PluginClassLoader@ad17d568
  reporter=com.comphenix.protocol.ProtocolLib$1@5deda311
  server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-1dc156c-4b84363,minecraftVersion=1.13.2}
  library=ProtocolLib v4.4.0
  asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@41ede313
  knowsServerPackets=true
  knowsClientPackets=true
  phaseLoginCount=0
  phasePlayingCount=7
  packetCreation=false
  spigotInjector=<null>
  nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@b9967dbc
  pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@71d100ed
  hasRecycleDistance=true
  minecraftVersion=(MC: 1.13.2)
  loginPackets=com.comphenix.protocol.injector.LoginPackets@8feaaee0
  debug=false
]

Listeners:
one.lindegaard.MobHunting.compatibility.ProtocolLibHelper$1@2ce089b0[
  plugin=MobHunting v6.5.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=21], SET_SLOT[class=PacketPlayOutSetSlot, id=23]], gamephase=PLAYING, options=[]]
]
com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Sign.SignMenu$1@c94d725a[
  plugin=VotingPlugin v5.17.1
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=38]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.Ste3et_C0st.FurnitureLib.Events.FurnitureEvents$1@7be3c184[
  plugin=FurnitureLib v2.0.5
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.Keyle.MyPet.util.hooks.ProtocolLibHook$1@4d82ad7a[
  plugin=MyPet v3.0
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
litebans.ey@3aac5137[
  plugin=LiteBans v2.3.9
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=2]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.Ste3et_C0st.FurnitureLib.Events.FurnitureEvents$2@ad67159b[
  plugin=FurnitureLib v2.0.5
  connectionSide=CLIENT_SIDE
  receivingWhitelist=ListeningWhitelist[priority=HIGHEST, packets=[STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=26]], gamephase=PLAYING, options=[]]
  sendingWhitelist=EMPTY_WHITELIST
]
de.Keyle.MyPet.util.hooks.ProtocolLibHook$2@e61aa294[
  plugin=MyPet v3.0
  connectionSide=SERVER_SIDE
  receivingWhitelist=EMPTY_WHITELIST
  sendingWhitelist=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=80], REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=41], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=57], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=42], VEHICLE_MOVE[class=PacketPlayOutVehicleMove, id=43]], gamephase=PLAYING, options=[]]
]

Plugins Using ProtocolLib:
VotingPlugin by [Ben12345rocks]
MyPet by [Keyle]
LiteBans by [Ruan]
FurnitureLib by [Ste3et_C0st]
MobHunting by [Rocologo]
