### ISSUE TITLE
Some NullPointerException

### ISSUE THREAD

**Issue by Avygeil** [dmulloy2/ProtocolLib#58]
Using build 83 for 1.8.3, I get errors that didn't happen previously, though the classes mentionned in the stacktrace don't seem to have changed.

Stacktrace :

```
java.lang.NullPointerException
	at com.comphenix.protocol.injector.netty.ChannelInjector.findChannelHandler(ChannelInjector.java:825) ~[?:?]
	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:77) ~[?:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector$4.sendServerPacket(NettyProtocolInjector.java:351) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:836) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:790) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:781) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.broadcastServerPacket(PacketFilterManager.java:713) ~[?:?]
	at com.avygeil.excalicube.module.custommessages.CustomMessages.updateTabHeaderAndFooter(CustomMessages.java:116) ~[?:?]
	at com.avygeil.excalicube.module.custommessages.CustomMessages$$Lambda$7/951348596.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-26dfd01-ad2f806]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-26dfd01-ad2f806]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-26dfd01-ad2f806]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [craftbukkit.jar:git-Spigot-26dfd01-ad2f806]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [craftbukkit.jar:git-Spigot-26dfd01-ad2f806]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-26dfd01-ad2f806]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

Related code :

```java
private void updateTabHeaderAndFooter() {
  final PacketContainer packet = packetManager.createPacket(PacketType.Play.Server.PLAYER_LIST_HEADER_FOOTER);
  packet.getChatComponents()
    .write(0, WrappedChatComponent.fromText(
      String.format(tabHeader, manager.getServer().getOnlinePlayers().size(),
        manager.getServer().getMaxPlayers())))
    .write(1, WrappedChatComponent.fromText(tabFooter));
  packetManager.broadcastServerPacket(packet);
}
 
@EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
public void onPlayerJoin(PlayerJoinEvent e) {
  e.setJoinMessage(ChatColor.GOLD + "[" + ChatColor.GREEN + "+" + ChatColor.GOLD + "] " + ChatColor.GRAY + e.getPlayer().getName());
  manager.runNextTick(this::updateTabHeaderAndFooter);
}
 
@EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
public void onPlayerQuit(PlayerQuitEvent e) {
  e.setQuitMessage(ChatColor.GOLD + "[" + ChatColor.RED + "-" + ChatColor.GOLD + "] " + ChatColor.GRAY + e.getPlayer().getName());
  manager.runNextTick(this::updateTabHeaderAndFooter);
}
```

This code updates the scoreboard as intended for about 45 minutes (varies), and then I get the stacktrace above on every player join/quit. It was working as expected in builds prior to 1.8.3, and some small debugging showed the values written to fields were correct.

Am I doing something wrong or is it ProtocolLib related?

**Comment by dmulloy2** [comment]
Use builds 86 and up for 1.8.3

**Comment by Avygeil** [comment]
Yeah I was using 86, sorry (don't know why I wrote 83). Anyway after more investigation that's not ProtocolLib's fault but CBWrapper's (it was messing with the spigot playerlist). After fixing said plugin it works now.
