### ISSUE TITLE
Error when placing down a sign on 1.13.2

### ISSUE THREAD

**Issue by LaserSlimeHD** [dmulloy2/ProtocolLib#596]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [X] This isn't an issue caused by another plugin
- [X] You've checked for duplicate issues
- [X] You didn't use `/reload`

Console error when placing down a sign.
Error: 
[14:35:20 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:200) [spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f09662d-494eef4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_13_R2.EntityPlayer.openSign(EntityPlayer.java:794) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:279) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1221) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[spigot.jar:git-Spigot-f09662d-494eef4]
        ... 5 more

**Comment by MiniDigger** [comment]
why would this be a protocollib issue? is it reproduceable without protocollib? what about protocollib but no other plugins?

**Comment by LaserSlimeHD** [comment]
It does only happen if protocollib is installed.

**Comment by dmulloy2** [comment]
Run `/protocol dump` and paste the output with pastebin. Could be a misbehaving plugin that uses PL.

**Comment by LaserSlimeHD** [comment]
I can´t reproduce it anymore. Both time (even when the error occurred) there were no other plugins except ProtocolLib installed. I think i´ll close this now.
