### ISSUE TITLE
Unable to find method scanPlayers with 1.14

### ISSUE THREAD

**Issue by LeonMangler** [dmulloy2/ProtocolLib#607]
Hey,
I'm getting an IllegalArgumentException when I try to use ProtocolLib's updateEntity() method to show a player with my vanish plugin on 1.14.
I'm using the latest spigot and the latest ProtocolLib build (build#8).

ProtocolLib dump: https://pastebin.com/f9mahg1d
Error message: https://pastebin.com/7Rxra4Ud

Thank you for your efforts in updating to 1.14!

**Comment by bundabrg** [comment]
I have the same issue. When attempting to hide a Citizens NPC it fails to find the scanMethods method.

Exception:
```
11:53:37 [INFO] [paper-1.14] java.lang.IllegalArgumentException: Unable to find method scanPlayers ([]) in class net.minecraft.server.v1_14_R1.EntityTrackerEntry.
11:53:37 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:87) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:86) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:70) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.accessors.Accessors.getMethodAccessor(Accessors.java:243) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.EntityUtilities.updateEntity(EntityUtilities.java:78) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.PacketFilterManager.updateEntity(PacketFilterManager.java:927) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at pl.betoncraft.betonquest.compatibility.protocollib.EntityHider.showEntity(EntityHider.java:286) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at pl.betoncraft.betonquest.compatibility.protocollib.NPCHider.applyVisibility(NPCHider.java:169) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at pl.betoncraft.betonquest.compatibility.protocollib.NPCHider.applyVisibility(NPCHider.java:207) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at pl.betoncraft.betonquest.compatibility.protocollib.NPCHider.run(NPCHider.java:128) ~[?:?]
11:53:37 [INFO] [paper-1.14]     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-129]
11:53:37 [INFO] [paper-1.14]     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-129]
11:53:37 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-129]
11:53:37 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-129]
11:53:37 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-129]
11:53:37 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-129]
11:53:37 [INFO] [paper-1.14]     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

Plugins
```
shared/plugins/1.14$ ls -al | tr -s " " | cut -d " " -f 9- | grep -v ^\\.

ActionHealth.jar -> ../all/ActionHealth-3.3.0.jar
BetonQuest.jar -> ../all/BetonQuest.jar
citizens.jar -> ../all/Citizens-2.0.25-b1721.jar
CoreProtect.jar -> ../all/CoreProtect-2.17.4.jar
dynmap.jar -> ../all/Dynmap-3.0-SNAPSHOT-spigot.jar
EffectLib.jar -> ../all/EffectLib-6.1.jar
FastLoginBukkit.jar -> ../all/FastLoginBukkit-build885.jar
Harbor.jar -> ../all/Harbor-1.5.jar
HeadsPlus.jar -> ../all/HeadsPlus-6.3.1.jar
Holograms.jar -> ../all/Holograms-2.7.jar
HolographicDisplays.jar -> ../all/HolographicDisplays-2.3.3-SNAPSHOT-b84.jar
LuckPerms-Bukkit.jar -> ../all/LuckPerms-Bukkit-4.4.25.jar
MySkin.jar -> ../all/MySkin-2.7.jar
NPCDestinations.jar -> ../all/NPCDestinations-Plugin-2.3.0-snapshot.jar
PlaceholderAPI.jar -> ../all/PlaceholderAPI-2.10.2.jar
ProtocolLib.jar -> ../all/ProtocolLib-b9.jar
UltimateChat.jar -> ../all/UltimateChat-1.8.9-b224-Universal.jar
Vault.jar -> ../all/Vault-1.7.2.jar
worldedit.jar -> ../all/worldedit-bukkit-7.0.0-SNAPSHOT-20190528.jar
WorldGuardExtraFlags.jar -> ../all/WorldGuardExtraFlags-4.1.2.jar
worldguard-legacy.jar -> ../all/worldguard-legacy-7.0.0-SNAPSHOT-20190528.jar
WorldResourcepacks.jar -> ../all/WorldResourcepacks-271.jar
```

I'm busying trying to compile protocolib to test some theories but is the scanMethod theory missing from NMS entirely under 1.14 or is it not finding one with the same type of parameters?

**Comment by bundabrg** [comment]
Had a closer look at the decompiled source of 1.14. Looks like 1.14 no longer has either scanPlayers, nor does it include support for canSee on the entity. Interestingly enough my test server (very lightly tested) still hides the NPC fine even with all the errors in the logs.
