### ISSUE TITLE
IllegalArgumentException 

### ISSUE THREAD

**Issue by NavidK0** [dmulloy2/ProtocolLib#63]
Error received:
```java
[19:03:17] [Server thread/ERROR]: [LibsDisguises] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for LibsDisguises
java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 0, banned: 1000], params=[{Type: class name of net\.minecraft\.(\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*\.)+\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*, Index: 0}, {Type: Exact class java.lang.String, Index: 1}, {Type: Exact int, Index: 2}, {Type: Exact int, Index: 3}, {Type: Exact int, Index: 4}]}
	at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:173) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getChunkPositionClass(MinecraftReflection.java:1192) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.getWrappedType(WrappedWatchableObject.java:354) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.getType(WrappedWatchableObject.java:147) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.setValue(WrappedWatchableObject.java:260) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.setValue(WrappedWatchableObject.java:247) ~[ProtocolLib.jar:?]
	at me.libraryaddict.disguise.utilities.PacketsManager$3.onPacketSending(PacketsManager.java:813) ~[LibsDisguises.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:368) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:334) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:192) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.NetworkManager.handle(NetworkManager.java:141) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.PlayerConnection.sendPacket(PlayerConnection.java:878) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:288) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.EntityTrackerEntry.b(EntityTrackerEntry.java:253) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.EntityTrackerEntry.track(EntityTrackerEntry.java:179) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.EntityTracker.updatePlayers(EntityTracker.java:177) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:798) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-beb883d-234e607]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-beb883d-234e607]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

When doing this in code:
```java
if (event.getPacketType() == PacketType.Play.Server.ENTITY_METADATA) {
                            event.setPacket(event.getPacket().deepClone());
                            for (WrappedWatchableObject watch : event.getPacket().getWatchableCollectionModifier().read(0)) {
                                if (watch.getIndex() == 0) {
                                    byte b = (Byte) watch.getValue();
                                    byte a = (byte) (b | 1 << 5);
                                    if ((b & 1 << 3) != 0)
                                        a = (byte) (a | 1 << 3);
                                    watch.setValue(a);
                                }
                            }
                        }
```
I've tried a number of things, including updating Spigot, and then looking through packet types, but I'm sure it's likely to do with the moving of classes and methods around.

**Comment by dmulloy2** [comment]
Same issue as #64
