### ISSUE TITLE
Consol told me to report this Error

### ISSUE THREAD

**Issue by merlinshaw** [dmulloy2/ProtocolLib#643]
`
[01:13:15] [Netty Epoll Server IO #1/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to intercept a read client packet.
[01:13:15] [Netty Epoll Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.NullPointerException) occured in com.comphenix.protocol.injector.netty.ChannelInjector@26c549e2.
[01:13:15] [Netty Epoll Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NullPointerException
  	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
  	at com.google.common.cache.LocalCache.put(LocalCache.java:4362)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.cachePlayerKey(ConcurrentPlayerMap.java:193)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:204)
  	at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:27)
  	at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:148)
  	at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:131)
  	at com.comphenix.protocol.async.AsyncFilterManager.getSendingQueue(AsyncFilterManager.java:442)
  	at com.comphenix.protocol.async.AsyncFilterManager.enqueueSyncPacket(AsyncFilterManager.java:324)
  	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:594)
  	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352)
  	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317)
  	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:506)
  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
  	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
  	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
  	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
  	at java.lang.Thread.run(Thread.java:748)
  Dump:
  Parameters: 
    io.netty.buffer.PooledUnsafeDirectByteBuf@4faa7edb[
      memoryAddress=140569565270080
      recyclerHandle=io.netty.util.Recycler$DefaultHandle@404ebbe3
      chunk=Chunk(4838153: 2%, 180224/16777216)
      handle=4611686022722357257
      memory=java.nio.DirectByteBuffer[pos=0 lim=16777216 cap=16777216]
      offset=73776
      length=34
      maxLength=48
      cache=io.netty.buffer.PoolThreadCache@18c36bbe
      tmpNioBuf=<null>
      allocator=PooledByteBufAllocator(directByDefault: true)
      refCnt=1
      readerIndex=34
      writerIndex=34
      markedReaderIndex=0
      markedWriterIndex=0
      maxCapacity=2147483647
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@173fc64d[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@15801c1d
        packetListeners=[com.comphenix.protocol.async.NullPacketListener@1fd3bd73, PacketAdapter[plugin=MobHunting, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.comphenix.protocol.async.NullPacketListener@7ad26289, PacketAdapter[plugin=Spartan, sending=ListeningWhitelist[priority=NORMAL, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7], TRANSACTION[class=PacketPlayOutTransaction, id=18], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=32]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[TRANSACTION[class=PacketPlayInTransaction, id=7], TRANSACTION[class=PacketPlayOutTransaction, id=18], KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=32]], gamephase=PLAYING, options=[]]], com.comphenix.protocol.async.NullPacketListener@2af8baa6]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@3247ccd
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@10b60f4
        interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@68efd336
        inputBufferedPackets=[POSITION[class=PacketPlayInPosition, id=17], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], STEER_VEHICLE[class=PacketPlayInSteerVehicle, id=28], ENTITY_ACTION[class=PacketPlayInEntityAction, id=27]]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7d1a4ac2
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@5df883b8
        hasClosed=false
        classLoader=org.bukkit.plugin.java.PluginClassLoader@29bef7cc
        reporter=com.comphenix.protocol.ProtocolLib$1@72e5433
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-107,minecraftVersion=1.14.2}
        library=ProtocolLib v4.5.0-SNAPSHOT
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@3e2d5532
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=7
        packetCreation=true
        spigotInjector=<null>
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@65dae540
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4d030c63
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.14.2)
        loginPackets=com.comphenix.protocol.injector.LoginPackets@42bf5d31
        debug=false
      ]
  Sender:
    com.comphenix.protocol.injector.netty.ChannelInjector@26c549e2[
      factory=com.comphenix.protocol.injector.netty.InjectionFactory@1487489f
      player=com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$8c2c1cff@41323e78
      updated=CraftPlayer{name=SinisterCraft}
      playerName=SinisterCraft
      playerConnection=<null>
      networkManager=net.minecraft.server.v1_14_R1.NetworkManager@795ca5ba
      originalChannel=[id: 0x9fbfd673, L:/127.0.0.1:25566 - R:/127.0.0.1:57871]
      channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_14_R1.NetworkManager.channel], container=net.minecraft.server.v1_14_R1.NetworkManager@795ca5ba, previous=[id: 0x9fbfd673, L:/127.0.0.1:25566 - R:/127.0.0.1:57871], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@174b25f5, previousLoaded=true, currentSet=true, forceAccess=true]
      packetMarker={}
      currentEvent=<null>
      finalEvent=<null>
      scheduleProcessPackets=java.lang.ThreadLocal$SuppliedThreadLocal@31fe0d0f
      vanillaDecoder=net.minecraft.server.v1_14_R1.PacketDecoder@520f6dfa
      vanillaEncoder=net.minecraft.server.v1_14_R1.PacketEncoder@68119335
      finishQueue=[]
      channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@65dae540
      processor=com.comphenix.protocol.injector.NetworkProcessor@67ec90f2
      injected=true
      closed=false
      cumulation=PooledUnsafeDirectByteBuf(ridx: 34, widx: 34, cap: 34)
      cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@4ea54148
      singleDecode=false
      decodeWasNull=false
      first=true
      decodeState=1
      discardAfterReads=16
      numReads=0
      added=true
    ]
  Version:
    ProtocolLib v4.5.0-SNAPSHOT
  Java Version:
    1.8.0_212
  Server:
    git-Paper-107 (MC: 1.14.2)

[01:13:16] [Server thread/INFO]: SinisterCraft[/97.121.180.0:57871] logged in with entity id 719 at ([Hub]65.50778667083507, 148.0, -4.703166563118261)`

**Comment by merlinshaw** [comment]
THe consol told me to report this error.

**Comment by dmulloy2** [comment]
Did this just recently start happening? i.e. by switching to 4.5.0 or MC 1.14.2?

**Comment by merlinshaw** [comment]
Id it stopped for awhile I posted another. Sorry i don't get updated when someone replies to these
