### ISSUE TITLE
Could not pass event PlayerJoinEvent to ProtocolLib v4.4.0

### ISSUE THREAD

**Issue by Slycraftmcs** [dmulloy2/ProtocolLib#646]
ERROR] Could not pass event PlayerJoinEvent to ProtocolLib v4.4.0

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:173) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoClassDefFoundError: com.comphenix.protocol.injector.PacketConstructor (initialization failure)

at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:98) ~[?:1.8.0_212]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:373) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerJoin(PacketFilterManager.java:1014) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$700(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerJoin(PacketFilterManager.java:986) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

... 13 more

Caused by: java.lang.BootstrapMethodError: java.lang.ExceptionInInitializerError

at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.PlayerList.attemptLogin(PlayerList.java:510) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:129) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

... 8 more

Caused by: java.lang.ExceptionInInitializerError

at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148) ~[?:1.8.0_212]

at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137) ~[?:1.8.0_212]

at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_212]

at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:838) ~[?:1.8.0_212]

at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.PlayerList.attemptLogin(PlayerList.java:510) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:129) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

... 8 more

Caused by: java.lang.IllegalArgumentException: Unable to find findStatistic in net.minecraft.server.v1_14_R1.StatisticList

at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280) ~[?:?]

at com.comphenix.protocol.wrappers.WrappedStatistic.<clinit>(WrappedStatistic.java:22) ~[?:?]

at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_212]

at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:838) ~[?:1.8.0_212]

at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012) ~[?:?]

at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62) ~[?:?]

at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45) ~[?:?]

at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100) ~[?:?]

at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29) ~[?:?]

at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]

at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]

at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.PlayerList.attemptLogin(PlayerList.java:510) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:129) ~[spigot-1.14.3.jar:git-Spigot-935adb3-a0e4747]

... 8 more

**Comment by dmulloy2** [comment]
Use a dev build
