### ISSUE TITLE
IT BROKE

### ISSUE THREAD

**Issue by keeganthomas** [dmulloy2/ProtocolLib#666]
i cannot load it

Error from my server service: 2019/08/10 17:00:23 [SEVERE] [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.ExceptionInInitializerError
at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1344)
at net.glowstone.GlowServer.start(GlowServer.java:770)
at net.glowstone.GlowServer.run(GlowServer.java:624)
at net.glowstone.GlowServer.main(GlowServer.java:488)
Caused by: java.lang.RuntimeException: Failed to find CraftBukkit class: entity.CraftPlayer
at com.comphenix.protocol.utility.MinecraftReflection.lambda$getCraftBukkitClass$0(MinecraftReflection.java:2012)
at java.util.Optional.orElseThrow(Optional.java:290)
at com.comphenix.protocol.utility.MinecraftReflection.getCraftBukkitClass(MinecraftReflection.java:2012)
at com.comphenix.protocol.utility.MinecraftReflection.getEntityPlayerClass(MinecraftReflection.java:588)
at com.comphenix.protocol.utility.MinecraftReflection.getPlayerConnectionClass(MinecraftReflection.java:1047)
at com.comphenix.protocol.utility.MinecraftReflection.getNetworkManagerClass(MinecraftReflection.java:1082)
at com.comphenix.protocol.utility.MinecraftReflection.getEnumProtocolClass(MinecraftReflection.java:758)
at com.comphenix.protocol.injector.netty.ProtocolRegistry.&lt;init&gt;(ProtocolRegistry.java:58)
at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.&lt;init&gt;(NettyProtocolRegistry.java:38)
at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
at com.comphenix.protocol.utility.ChatExtensions.&lt;clinit&gt;(ChatExtensions.java:55)
... 8 more
Dump:
Sender:
com.comphenix.protocol.ProtocolLib@463045fb[
statistics=&lt;null&gt;
backgroundCompiler=&lt;null&gt;
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@14457a95
configExpectedMod=-1
updater=com.comphenix.protocol.updater.BukkitUpdater@48567727
redirectHandler=&lt;null&gt;
commandProtocol=&lt;null&gt;
commandPacket=&lt;null&gt;
commandFilter=&lt;null&gt;
packetLogging=&lt;null&gt;
skipDisable=false
isEnabled=true
loader=org.bukkit.plugin.java.JavaPluginLoader@10e9a5fe
server=GlowServer{name=Glowstone,version=2018.10.0-SNAPSHOT.f8938f8 (MC: 1.12.2),minecraftVersion=1.12.2}
file=plugins/ProtocolLib.jar
description=org.bukkit.plugin.PluginDescriptionFile@1abcd059
dataFolder=plugins/ProtocolLib
classLoader=org.bukkit.plugin.java.PluginClassLoader@203e705e
naggable=true
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=com.destroystokyo.paper.utils.PaperPluginLogger@3c33fcf8
]
Version:
ProtocolLib v4.4.0
Java Version:
1.8.0_222
Server:
2018.10.0-SNAPSHOT.f8938f8 (MC: 1.12.2)

**Comment by dmulloy2** [comment]
ProtocolLib currently doesn't support Glowstone. There was a movement at some point but I'm not sure of its status at this point
