### ISSUE TITLE
Bug Protocollib Disabling

### ISSUE THREAD

**Issue by Zaynii** [dmulloy2/ProtocolLib#667]
hello I just had this error

[03:37:24] [Server thread/ERROR]: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/Plugin;)V from class com.comphenix.protocol.ProtocolLib initializing ProtocolLib v4.4.0 (Is it up to date?)
java.lang.IllegalAccessError: tried to access method com.comphenix.protocol.ProtocolLogger.init(Lorg/bukkit/plugin/Plugin;)V from class com.comphenix.protocol.ProtocolLib
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:155) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:303) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by dmulloy2** [comment]
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/
