### ISSUE TITLE
On server reload (dont know if you support it)

### ISSUE THREAD

**Issue by nimrod46** [dmulloy2/ProtocolLib#68]
NOTE: my plugin name is Economy, change the names to @@
01:06:34 [ERROR]   [ProtocolLib] INTERNAL ERROR: Cannot execute code in channel thread.
01:06:34 If this problem hasn't already been reported, please open a ticket
01:06:34 at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
01:06:34 Stack Trace:
01:06:34 java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_exception_handler
01:06:34 at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01:06:34 at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:125)
01:06:34 at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:119)
01:06:34 at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:255)
01:06:34 at com.comphenix.protocol.injector.netty.ChannelInjector$2.run(ChannelInjector.java:194)
01:06:34 at com.comphenix.protocol.injector.netty.ChannelInjector$9.run(ChannelInjector.java:811)
01:06:34 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
01:06:34 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
01:06:34 at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
01:06:34 at java.lang.Thread.run(Unknown Source)
01:06:34 Dump:
01:06:34 manager:
01:06:34 com.comphenix.protocol.injector.PacketFilterManager@69dd56b5[
01:06:34 unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7a2d5930
01:06:34 packetListeners=[PacketAdapter[plugin=Economy, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutNamedSoundEffect[41, legacy: 62]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Economy, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInEntityAction[11, legacy: 19]], gamephase=PLAYING, options=[]}]]
01:06:34 packetInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector$5@985cb30
01:06:34 playerInjection=com.comphenix.protocol.injector.netty.NettyProtocolInjector$4@3ecce9b7
01:06:34 interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@58289687
01:06:34 inputBufferedPackets=[]
01:06:34 recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@55ed344d
01:06:34 sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7216a98b
01:06:34 hasClosed=false
01:06:34 classLoader=org.bukkit.plugin.java.PluginClassLoader@2ae9a7b8
01:06:34 reporter=com.comphenix.protocol.ProtocolLibrary$1@1b471046
01:06:34 server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-dbe012b-61ef214,minecraftVersion=1.8.3}
01:06:34 library=ProtocolLib v3.6.3-SNAPSHOT-b106
01:06:34 asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@675d798c
01:06:34 knowsServerPackets=true
01:06:34 knowsClientPackets=true
01:06:34 phaseLoginCount=0
01:06:34 phasePlayingCount=2
01:06:34 packetCreation=false
01:06:34 spigotInjector=<null>
01:06:34 nettyInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector@4406c728
01:06:34 pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@148f0e3e
01:06:34 hasRecycleDistance=true
01:06:34 minecraftVersion=(MC: 1.8.3)
01:06:34 loginPackets=com.comphenix.protocol.injector.LoginPackets@5107e9e8
01:06:34 debug=false
01:06:34 ]
01:06:34 Sender:
01:06:34 com.comphenix.protocol.injector.netty.ChannelInjector@30f70fa2[
01:06:34 factory=com.comphenix.protocol.injector.netty.InjectionFactory@75d55826
01:06:34 player=CraftPlayer{name=@@}
01:06:35 updated=<null>
01:06:35 playerName=<null>
01:06:35 playerConnection=<null>
01:06:35 networkManager=net.minecraft.server.v1_8_R2.NetworkManager@7be07a89
01:06:35 originalChannel=[id: 0x91a97800, /109.186.184.104:54129 => /10.0.0.1:25565]
01:06:35 channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_8_R2.NetworkManager.k], container=net.minecraft.server.v1_8_R2.NetworkManager@7be07a89, previous=null, current=null, previousLoaded=false, currentSet=false, forceAccess=true]
01:06:35 packetMarker={}
01:06:35 currentEvent=<null>
01:06:35 finalEvent=<null>
01:06:35 scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@50f8b433
01:06:35 vanillaDecoder=net.minecraft.server.v1_8_R2.PacketDecoder@118f6c45
01:06:35 vanillaEncoder=net.minecraft.server.v1_8_R2.PacketEncoder@48e8a49c
01:06:35 protocolEncoder=com.comphenix.protocol.injector.netty.ChannelInjector$3@6d92c96d
01:06:35 finishHandler=com.comphenix.protocol.injector.netty.ChannelInjector$4@785ea1c0
01:06:35 finishQueue=[]
01:06:35 channelListener=com.comphenix.protocol.injector.netty.NettyProtocolInjector@4406c728
01:06:35 processor=com.comphenix.protocol.injector.NetworkProcessor@1f989d59
01:06:35 injected=false
01:06:35 closed=false
01:06:35 cumulation=<null>
01:06:35 singleDecode=false
01:06:35 decodeWasNull=false
01:06:35 first=false
01:06:35 added=true
01:06:35 ]
01:06:35 Version:
01:06:35 ProtocolLib v3.6.3-SNAPSHOT-b106
01:06:35 Server:
01:06:35 git-Spigot-dbe012b-61ef214 (MC: 1.8.3)
01:06:35 [ERROR]   [ProtocolLib] INTERNAL ERROR: Cannot execute code in channel thread.
01:06:35 If this problem hasn't already been reported, please open a ticket
01:06:35 at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
01:06:35 Stack Trace:
01:06:35 java.lang.IllegalArgumentException: Duplicate handler name: protocol_lib_exception_handler
01:06:35 at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:900)
01:06:35 at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:125)
01:06:35 at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:119)
01:06:35 at com.comphenix.protocol.injector.netty.ChannelInjector.inject(ChannelInjector.java:255)
01:06:35 at com.comphenix.protocol.injector.netty.ChannelInjector$2.run(ChannelInjector.java:194)
01:06:35 at com.comphenix.protocol.injector.netty.ChannelInjector$9.run(ChannelInjector.java:811)
01:06:35 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
01:06:35 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
01:06:35 at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
01:06:35 at java.lang.Thread.run(Unknown Source)
01:06:35 Dump:
01:06:35 manager:
01:06:35 com.comphenix.protocol.injector.PacketFilterManager@69dd56b5[
01:06:35 unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@7a2d5930
01:06:35 packetListeners=[PacketAdapter[plugin=Economy, sending=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayOutNamedSoundEffect[41, legacy: 62]], gamephase=PLAYING, options=[]}, receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Economy, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist{priority=NORMAL, packets=[PacketPlayInEntityAction[11, legacy: 19]], gamephase=PLAYING, options=[]}]]
01:06:35 packetInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector$5@985cb30
01:06:35 playerInjection=com.comphenix.protocol.injector.netty.NettyProtocolInjector$4@3ecce9b7
01:06:35 interceptWritePacket=com.comphenix.protocol.injector.packet.InterceptWritePacket@58289687
01:06:35 inputBufferedPackets=[]
01:06:35 recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@55ed344d
01:06:35 sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@7216a98b
01:06:35 hasClosed=false
01:06:35 classLoader=org.bukkit.plugin.java.PluginClassLoader@2ae9a7b8
01:06:35 reporter=com.comphenix.protocol.ProtocolLibrary$1@1b471046
01:06:35 server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-dbe012b-61ef214,minecraftVersion=1.8.3}
01:06:35 library=ProtocolLib v3.6.3-SNAPSHOT-b106
01:06:35 asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@675d798c
01:06:35 knowsServerPackets=true
01:06:35 knowsClientPackets=true
01:06:35 phaseLoginCount=0
01:06:35 phasePlayingCount=2
01:06:35 packetCreation=false
01:06:35 spigotInjector=<null>
01:06:35 nettyInjector=com.comphenix.protocol.injector.netty.NettyProtocolInjector@4406c728
01:06:35 pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@148f0e3e
01:06:35 hasRecycleDistance=true
01:06:35 minecraftVersion=(MC: 1.8.3)
01:06:35 loginPackets=com.comphenix.protocol.injector.LoginPackets@5107e9e8
01:06:35 debug=false
01:06:35 ]
01:06:35 Sender:
01:06:35 com.comphenix.protocol.injector.netty.ChannelInjector@56b3b796[
01:06:35 factory=com.comphenix.protocol.injector.netty.InjectionFactory@75d55826
01:06:35 player=CraftPlayer{name=@@}
01:06:35 updated=<null>
01:06:35 playerName=<null>
01:06:35 playerConnection=<null>
01:06:35 networkManager=net.minecraft.server.v1_8_R2.NetworkManager@79c8ce09
01:06:35 originalChannel=[id: 0x7e081e1b, /127.0.0.1:54585 => /127.0.0.1:25565]
01:06:35 channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.server.v1_8_R2.NetworkManager.k], container=net.minecraft.server.v1_8_R2.NetworkManager@79c8ce09, previous=null, current=null, previousLoaded=false, currentSet=false, forceAccess=true]
01:06:35 packetMarker={}
01:06:35 currentEvent=<null>
01:06:35 finalEvent=<null>
01:06:35 scheduleProcessPackets=com.comphenix.protocol.injector.netty.ChannelInjector$1@4041707e
01:06:35 vanillaDecoder=net.minecraft.server.v1_8_R2.PacketDecoder@1f0a1438
01:06:35 vanillaEncoder=net.minecraft.server.v1_8_R2.PacketEncoder@208d3956
01:06:35 protocolEncoder=com.comphenix.protocol.injector.netty.ChannelInjector$3@e4e559
01:06:35 finishHandler=com.comphenix.protocol.injector.netty.ChannelInjector$4@4bedb7bb
01:06:35 finishQueue=[]
01:06:35 channelListener=com.comphenix.protocol.injector.netty.NettyProtocolInjector@4406c728
01:06:35 processor=com.comphenix.protocol.injector.NetworkProcessor@4d071f64
01:06:35 injected=false
01:06:35 closed=false
01:06:35 cumulation=<null>
01:06:35 singleDecode=false
01:06:35 decodeWasNull=false
01:06:35 first=false
01:06:35 added=true
01:06:35 ]
01:06:35 Version:
01:06:35 ProtocolLib v3.6.3-SNAPSHOT-b106
01:06:35 Server:
01:06:35 git-Spigot-dbe012b-61ef214 (MC: 1.8.3)

**Comment by nimrod46** [comment]
yay THX!
