### ISSUE TITLE
Not Work in 1.14.4

### ISSUE THREAD

**Issue by boyphongsakorn** [dmulloy2/ProtocolLib#690]
[09:04:15] [Server thread/ERROR]: Could not load 'plugins/ProtocolLib.jar' in folder 'plugins'
--
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:168) ~[spigot-1.14.4.jar:git-Spigot-065a373-9aa7430]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:138) [spigot-1.14.4.jar:git-Spigot-065a373-9aa7430]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [spigot-1.14.4.jar:git-Spigot-065a373-9aa7430]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.14.4.jar:git-Spigot-065a373-9aa7430]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-065a373-9aa7430]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.FileNotFoundException: plugins/ProtocolLib.jar (Permission denied)
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_212]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_212]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_212]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_212]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:156) ~[spigot-1.14.4.jar:git-Spigot-065a373-9aa7430]
... 5 more

**Comment by MiniDigger** [comment]
check the file permissions. your server has no permission to read the protocollib.jar file. make sure you uploaded it using the right user or make it readable to the user that runs your server.
