### ISSUE TITLE
Cannot load ProtoclLib

### ISSUE THREAD

**Issue by 0ez0** [dmulloy2/ProtocolLib#698]
Stack Trace:
  java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:227)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:374)
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152)
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
  Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelInboundHandler
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more

**Comment by dmulloy2** [comment]
What version are you using?
