### ISSUE TITLE
LinkageError

### ISSUE THREAD

**Issue by jujubean23** [dmulloy2/ProtocolLib#700]
I'm getting a linkage error and I'm not sure why. I'm not using the jar for multiple server instances. It spams my console and I just want to figure out why.

Plugins: Core Protect, Player Heads, World Edit, Void Generator, Set Spawn, Chat Emotes, Clear Lag, Permissions Ex, Simple-Auto Save, Vault, Multiverse-Core, ProtocolLib, World Guard, Chest Shop, Essentials, Ultra Cosmetics, Holographic Displays, Super Vanish, Muliverse-Portals, Factions, TAB, and Chat Manager

Console spams this:
https://pastebin.com/GTTdnDqj

I'm on version 1.14.4 using the most recent update.

**Comment by SimonIT** [comment]
How do you solved this problem? I'm still getting this error with version 4.5.0 on 1.15.1
```
[14:38:24] [Server thread/WARN]: [ProtocolLib] Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!
[14:38:24] [Server thread/WARN]: [ProtocolLib] If you're getting this error for other reasons, please report it!
[14:38:24] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:297)
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[14:38:24] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:176)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:146)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1373)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1346)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerList.tick(PlayerList.java:695)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1033)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:380)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:934)
[14:38:24] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:788)
[14:38:24] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by SauROnmiKE** [comment]
Sorry for bumping this up again, but I also get this on a fresh installation of PaperSpigot and no solution found on any of the other issues here.

**Comment by MiniDigger** [comment]
what server software with what version?
what plugins?
