### ISSUE TITLE
Plugin does not work (red market by /pl)

### ISSUE THREAD

**Issue by reschiram** [dmulloy2/ProtocolLib#71]
[01:08:05] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.4.0
[01:08:05] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.8.0) has not yet been tested! Proceed with caution.
[01:08:05] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at http://dev.bukkit.org/server-mods/protocollib/ with the following data:
            ===== STACK TRACE =====
  java.lang.NoSuchMethodError com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/Cache;
      at com.comphenix.protocol.utility.MinecraftReflection.<clinit>(MinecraftReflection.java:155)
      at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:259)
      at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
      at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
      at com.comphenix.protocol.ProtocolLibrary.onLoad(ProtocolLibrary.java:216)
      at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:293)
      at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250)
      at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69)
      at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14)
      at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133)
      at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484)
      at java.lang.Thread.run(Unknown Source)
            ===== DUMP =====
  Parameters: 
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLibrary@251cff1b[
      statistisc=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@669ff4a0
      configExpectedMod=-1
      updater=com.comphenix.protocol.metrics.Updater@11491a1f
      logger=org.bukkit.plugin.PluginLogger@5b1795da
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@509fb979
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Bukkit-17a3db7,minecraftVersion=1.8}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@47b2f5c6
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@58bf1991
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@5b1795da
    ]
  Version:
    ProtocolLib v3.4.0
  Server:
    git-Bukkit-17a3db7 (MC: 1.8)

**Comment by dmulloy2** [comment]
You're using an outdated version of ProtocolLib. Grab the latest one here: http://ci.shadowvolt.com/job/ProtocolLib/

**Comment by reschiram** [comment]
thank you
