### ISSUE TITLE
Timings issue

### ISSUE THREAD

**Issue by CaoTrongThang** [dmulloy2/ProtocolLib#715]
First of all, sorry about my English

I think your plugin is having issue with timing, really hope you can fix it, thank you ~~"

[10:37:41 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[10:37:41 ERROR]: The server has not responded for 18 seconds! Creating thread dump
[10:37:41 ERROR]: ------------------------------
[10:37:41 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[10:37:41 ERROR]: ------------------------------
[10:37:45 ERROR]: Current Thread: Server thread
[10:37:45 ERROR]:       PID: 29 | Suspended: false | Native: false | State: TIMED_WAITING
[10:37:45 ERROR]:       Stack:
[10:37:45 ERROR]:               java.lang.Thread.sleep(Native Method)
[10:37:45 ERROR]:               net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:644)
[10:37:45 ERROR]:               java.lang.Thread.run(Unknown Source)
[10:37:45 ERROR]: ------------------------------
[10:37:45 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[10:37:45 ERROR]: ------------------------------
[10:39:00 INFO]: [BattlePass] Saving all player data...
[10:39:00 INFO]: [BattlePass] Finished saving all player data.
[10:45:40 INFO]: [BattlePass] Saving all player data...
[10:45:40 INFO]: [BattlePass] Finished saving all player data.
[10:52:20 INFO]: [BattlePass] Saving all player data...
[10:52:20 INFO]: [BattlePass] Finished saving all player data.
> timings paste
[10:53:32 INFO]: Preparing Timings Report...
[10:53:33 INFO]: View Timings Report: https://timings.aikar.co/?id=35a7caf6cec046cf8add4e016f968d52
[10:59:00 INFO]: [BattlePass] Saving all player data...
[10:59:00 INFO]: [BattlePass] Finished saving all player data.
> timings paste
[10:59:38 INFO]: Preparing Timings Report...
[10:59:59 INFO]: Error uploading timings, check your logs for more information
[10:59:59 ERROR]: Could not paste timings
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_231]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_231]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_231]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_231]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_231]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_231]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_231]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_231]
        at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_231]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:1.8.0_231]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:1.8.0_231]
        at co.aikar.timings.TimingsExport.run(TimingsExport.java:293) ~[spigot.jar:git-Paper-1618]

**Comment by dmulloy2** [comment]
You can disable metrics in the config

**Comment by CaoTrongThang** [comment]
Ok i'll try, please give me few days to test :D

**Comment by CaoTrongThang** [comment]
If i turn off metrics, is it do anything bad to my server? ~~"

**Comment by dmulloy2** [comment]
No. They're just for plugin developers and honestly I haven't looked at the ones for PL in a long time

**Comment by CaoTrongThang** [comment]
I think the error is gone, thank you very much :D
