### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by AFGAME** [dmulloy2/ProtocolLib#720]
Hello, i have 1 error, 
I would like to know where it comes from?

[18:32:14] [Server thread/ERROR]: null

org.bukkit.command.CommandException: Cannot execute command 'protocol' in plugin ProtocolLib v4.4.0 - plugin is disabled.

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]

at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]

at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]

at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot.jar:git-Spigot-518206a-a5b9c7b]

at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot.jar:git-Spigot-518206a-a5b9c7b]

at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by dmulloy2** [comment]
> plugin is disabled

The plugin is disabled for some reason. Was there an error on startup?
