### ISSUE TITLE
1.15 - Cannot load server and client packet list.

### ISSUE THREAD

**Issue by Jacob-Brink** [dmulloy2/ProtocolLib#728]
**When loading ProtocolLib, it "Cannot load server and client packet list"**
It then shows the following exception has occurred:
`com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:198) ~[ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:266) [ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250) [ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233) [ProtocolLib%20(1).jar:4.4.0-b421]
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213) [ProtocolLib%20(1).jar:4.4.0-b421]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) [spigot-1.15.jar:git-Spigot-047b6f8-61d4b09]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.15.jar:git-Spigot-047b6f8-61d4b09]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.jar:git-Spigot-047b6f8-61d4b09]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[10:49:02] [Server thread/WARN]: [ProtocolLib] Failed to register command PACKET: java.lang.ExceptionInInitializerError
`

**To Reproduce**
1. Download Paper 1.15 Jar.
2. Start Paper server with ProtocolLib.Jar in the plugins folder.
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/29411599/70851165-e58a6480-1e5f-11ea-8e6b-4bc7c9667157.png)

**Comment by dmulloy2** [comment]
Make sure you're using the latest dev build: http://ci.dmulloy2.net/job/ProtocolLib/

**Comment by Jacob-Brink** [comment]
That fixed it! Thanks!
