### ISSUE TITLE
No field with type java.util.Collection exists in class PacketPlayOutSpawnEntityLiving

### ISSUE THREAD

**Issue by fax1ty** [dmulloy2/ProtocolLib#745]
**Describe the bug**
```
[14:24:30 ERROR]: [UNKNOWN] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for UNKNOWN
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Collection exists in class PacketPlayOutSpawnEntityLiving.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at net.iso2013.peapi.packet.EntitySpawnPacketImpl.unwrap(EntitySpawnPacketImpl.java:88) ~[?:?]
        at net.iso2013.peapi.packet.EntityPacketImpl.unwrapFromType(EntityPacketImpl.java:40) ~[?:?]
        at net.iso2013.peapi.event.engine.listeners.EntityListener.onPacketSending(EntityListener.java:45) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1541) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1514) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:276) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1646) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1278) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:738) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1144) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-34]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**To Reproduce**
Just install ProtocolLib on 1.15.1

**Expected behavior**
???

**Version Info**
https://pastebin.com/qH0F9aUv

**Comment by MiniDigger** [comment]
one of your plugins (peapi by iso2013) needs to be updated. 
This is not a protocollib bug.
