### ISSUE TITLE
Error loading in paper 1.15

### ISSUE THREAD

**Issue by Doc94** [dmulloy2/ProtocolLib#755]
**Describe the bug**
In paper spigot when load the plugin this not start.

**To Reproduce**
1. Upload the plugin
2. Load the plugin (like server reset or plugman)
3. See error

**Version Info**
This server is running Paper version git-Paper-33 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Additional context**
`[03:20:52] [Server thread/ERROR]: Could not load 'plugins/ProtocolLib.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) ~[patched_1.15.1.jar:git-Paper-33]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.15.1.jar:git-Paper-33]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-33]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:171) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.1.jar:git-Paper-33]
	at com.comphenix.protocol.ProtocolLib.<init>(ProtocolLib.java:65) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.15.1.jar:git-Paper-33]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:174) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.1.jar:git-Paper-33]
	at me.mrdoc.minecraft.lebrelcraft.Core.<init>(Core.java:12) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.15.1.jar:git-Paper-33]
	... 6 more`

**Comment by MiniDigger** [comment]
Don't use plugman, restart the server properly.

If this error still occurs, upload your full startup log, most likely another plugin is including protocoollib or doing something stupid.

**Comment by Doc94** [comment]
Yes a plugin with the same classes... removed and working
