### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by xXLinkster17Xx** [dmulloy2/ProtocolLib#767]
**Describe the bug**
Whenever I try to type /essentials reload it cuts me off at /essentials rel with "Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer" and the console outputs this from ProtocolLib: https://pastebin.com/eX3qxweF

**To Reproduce**
1. Download latest release build for 1.15.2
2. Put in a server with essentials.
3. Try typing /essentials reload
4. Experience error.

**Expected behavior**
I expected it to work properly so I could use the ChatControl plugin.

**Screenshots**
https://i.imgur.com/0r90die.png

**Version Info**
https://pastebin.com/83kVzgRP

**Additional context**
No Additional Context.

**Comment by dmulloy2** [comment]
Can you provide the rest of that stack trace?

**Comment by marvinej** [comment]
I just got it by installing 4.5.1

```
java.lang.NoClassDefFoundError: com/comphenix/protocol/utility/MinecraftFields
at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976) ~[?:?]
at java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_V(VirtualHandle.java:85) ~[?:1.8.0_252]
at java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49) ~[?:1.8.0_252]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-309]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-309]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-309]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.PlayerList.attemptLogin(PlayerList.java:620) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:339) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:140) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1344) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-309]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-309]
at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]

```
