### ISSUE TITLE
Error - PaperSpigot 1.8.8

### ISSUE THREAD

**Issue by iJosePlay** [dmulloy2/ProtocolLib#792]
[ERROR] [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.

If this problem hasn't already been reported, please open a ticket

at https://github.com/dmulloy2/ProtocolLib/issues with the following data:

Stack Trace:

java.lang.NullPointerException

at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)

at com.google.common.cache.LocalCache.put(LocalCache.java:4143)

at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.cachePlayerKey(ConcurrentPlayerMap.java:196)

at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:207)

at com.comphenix.protocol.concurrency.ConcurrentPlayerMap.putIfAbsent(ConcurrentPlayerMap.java:28)

at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:148)

at com.comphenix.protocol.async.PlayerSendingHandler.getSendingQueue(PlayerSendingHandler.java:131)

at com.comphenix.protocol.async.AsyncFilterManager.getSendingQueue(AsyncFilterManager.java:442)

at com.comphenix.protocol.async.AsyncFilterManager.enqueueSyncPacket(AsyncFilterManager.java:324)

at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:594)

at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557)

at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352)

at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317)

at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533)

at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)

at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)

at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)

at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)

at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)

at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

at java.lang.Thread.run(Thread.java:813)

Dump:

Parameters:

io.netty.buffer.UnpooledHeapByteBuf@75eafa13[

alloc=UnpooledByteBufAllocator(directByDefault: true)

array={0,10,72,65,82,85,89,84,49,50,51,52}

tmpNioBuf=<null>

refCnt=1

readerIndex=12

writerIndex=12

markedReaderIndex=0

markedWriterIndex=0

maxCapacity=2147483647

swappedBuf=<null>

]

manager:

com.comphenix.protocol.injector.PacketFilterManager@56cd784e[

unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@b46d2555

**Comment by MiniDigger** [comment]
please fill out the issue template properly, your report is useless.

At least run /protocollib dump
