### ISSUE TITLE
IllegalArgumentException: Unable to find getNetworkManagers

### ISSUE THREAD

**Issue by barpec12** [dmulloy2/ProtocolLib#793]
**Describe the bug**
There is an issue, which occurs after one of the latest paperspigot patch - https://github.com/PaperMC/Paper/commit/c8dea96ee15de84b0624522a79c47b2bf8080bee

**To Reproduce**
Install https://www.spigotmc.org/resources/jsonapi-reloaded.69447/ and run.

**Version Info**
ProtocolLib v4.5.1-SNAPSHOT-b447

`[01:33:50] [Server thread/WARN]: java.lang.RuntimeException: Unable to inject channel futures.
[01:33:50] [Server thread/WARN]: 	at com.alecgorge.minecraft.jsonapi.packets.netty.NettyInjector.inject(NettyInjector.java:103)
[01:33:50] [Server thread/WARN]: 	at com.alecgorge.minecraft.jsonapi.packets.netty.JSONAPINettyInjector.<init>(JSONAPINettyInjector.java:18)
[01:33:50] [Server thread/WARN]: 	at com.alecgorge.minecraft.jsonapi.JSONAPI.onEnable(JSONAPI.java:512)
[01:33:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:33:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[01:33:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[01:33:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[01:33:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[01:33:50] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[01:33:50] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[01:33:50] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[01:33:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:33:50] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Unable to find getNetworkManagers in net.minecraft.server.v1_15_R1.ServerConnection
[01:33:50] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280)
[01:33:50] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.FuzzyReflection.invokeMethod(FuzzyReflection.java:328)
[01:33:50] [Server thread/WARN]: 	at com.alecgorge.minecraft.jsonapi.packets.netty.NettyInjector.inject(NettyInjector.java:83)
[01:33:50] [Server thread/WARN]: 	... 11 more`

**Comment by MiniDigger** [comment]
this is not a protocollib issue.
jsonapi just uses protocollibs fuzzy matching api to get a nms method, which got an ABI change in the linked patch.

the author needs to change this (NettyInjector.java:83):
```java
this.networkManagers = (List<Object>)FuzzyReflection.fromObject(serverConnection, true).invokeMethod((Object)null, "getNetworkManagers", (Class)List.class, new Object[] { serverConnection });
```
to not using list but collection.

**Comment by StylexTV** [comment]
> 
> 
> this is not a protocollib issue.
> jsonapi just uses protocollibs fuzzy matching api to get a nms method, which got an ABI change in the linked patch.
> 
> the author needs to change this (NettyInjector.java:83):
> 
> ```java
> this.networkManagers = (List<Object>)FuzzyReflection.fromObject(serverConnection, true).invokeMethod((Object)null, "getNetworkManagers", (Class)List.class, new Object[] { serverConnection });
> ```
> 
> to not using list but collection.

The newest paper spigot jar uses the "java.util.Queue" return type instead of collection or list.

**Comment by MiniDigger** [comment]
which luckily implements collection
