### ISSUE TITLE
compatibility between netty's versions

### ISSUE THREAD

**Issue by yiatzz** [dmulloy2/ProtocolLib#799]
[01:56:13 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.NoClassDefFoundError: io/netty/channel/ChannelInboundHandler
        at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:227)
        at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250)
        at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233)
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:340)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:203)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:576)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: io.netty.channel.ChannelInboundHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 8 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@41c3ecbf[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@731774e9
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@222392d
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=org.bukkit.plugin.java.JavaPluginLoader@91334af
      server=CraftServer{serverName=CloudSpigot,serverVersion=git-CloudSpigot-e2235a8,minecraftVersion=1.8.10}
      file=plugins/ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@5ab3529f
      dataFolder=plugins/ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@5d4c4f3a
      naggable=true
      ebean=<null>
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins/ProtocolLib/config.yml
      logger=org.bukkit.plugin.PluginLogger@5660ca2d
    ]
  Version:
    ProtocolLib v4.5.0
  Java Version:
    1.8.0_242
  Server:
    git-CloudSpigot-e2235a8 (MC: 1.8.10)

**Comment by MiniDigger** [comment]
please provide details.....

also, you cant expect protocollib to support modified servers. if you modify your server software, so are expected to fix issues yourself.
if there are things protocollib could do to make your life easier (and that also doesnt make shit worse for others), you could always PR those changes.

**Comment by yiatzz** [comment]
> please provide details.....
> 
> also, you cant expect protocollib to support modified servers. if you modify your server software, so are expected to fix issues yourself.
> if there are things protocollib could do to make your life easier (and that also doesnt make shit worse for others), you could always PR those changes.
> 
> edit: just found the project (https://github.com/Linux-4/CloudSpigot). the author is violating the copyright of mojang, msft and every contributor of bukkit, spigot and paper (including myself)

I understand, I already stopped using this server jar, thanks and sorry for the waste of time.

**Comment by yiatzz** [comment]
> please provide details.....
> 
> also, you cant expect protocollib to support modified servers. if you modify your server software, so are expected to fix issues yourself.
> if there are things protocollib could do to make your life easier (and that also doesnt make shit worse for others), you could always PR those changes.
> 
> edit: just found the project (https://github.com/Linux-4/CloudSpigot). the author is violating the copyright of mojang, msft and every contributor of bukkit, spigot and paper (including myself)

I understand, I already stopped using this server jar, thanks and sorry for the waste of time.
