### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by david890504** [dmulloy2/ProtocolLib#804]
[22:53:48 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.5 generated an exception while executing task 63
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$null$3(ExpansionCloudManager.java:190) ~[?:?]
        at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_241]
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:182) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-243]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-243]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by MiniDigger** [comment]
this is protocollibs issue tracker, not placeholdersapis issue tracker.

your issue has been fixed in a recent papi version anyways, just update
