### ISSUE TITLE
Unhandled exception occured in onSyncPacket()

### ISSUE THREAD

**Issue by DaddyKing3** [dmulloy2/ProtocolLib#81]
Hello, using:

git-Spigot-2ec6f06-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
ProtocolLib v3.6.3-SNAPSHOT-b117
LibsDisguises v8.3.1
PropHunt v1.44

The following exception is occurring and it doesn't have PropHunt in the stack:

[09:52:38] [Server thread/ERROR]: [PropHunt] Unhandled exception occured in onSyncPacket() for PropHunt
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:221) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:196) ~[ProtocolLib.jar:?]
	at me.tomski.blocks.ProtocolTask$1.onPacketReceiving(ProtocolTask.java:52) ~[PropHunt.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:643) [ProtocolLib.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$1000(AsyncListenerHandler.java:49) [ProtocolLib.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler$5.run(AsyncListenerHandler.java:442) [ProtocolLib.jar:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.3-201505020918.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.3-201505020918.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot-1.8.3-201505020918.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3-201505020918.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3-201505020918.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3-201505020918.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

Given PropHunt is not in the stack this looks like a defect, but I am not sure if it is ProtocolLib or if it is LibsDisguises?  Starting here since the last two stack frames are in ProtocolLib.

**Comment by DaddyKing3** [comment]
Wow, I was totally wrong, PropHunt is in the stack.  Please parson my silliness.  This is probably not ProtocolLib.
