### ISSUE TITLE
java.lang.IllegalArgumentException: Class class net.minecraft.server.v1_12_R1.PacketPlayOutOpenSignEditor is not a registered packet.

### ISSUE THREAD

**Issue by mckite** [dmulloy2/ProtocolLib#834]
[23:15:06] [Netty Server IO #1/WARN]: Error occured while handling packet sending
[23:15:06] [Netty Server IO #1/WARN]: java.lang.IllegalArgumentException: Class class net.minecraft.server.v1_12_R1.PacketPlayOutOpenSignEditor is not a registered packet.
[23:15:06] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.PacketType.fromClass(PacketType.java:926)
[23:15:06] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.events.PacketContainer.fromPacket(PacketContainer.java:188)

[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.th0rgal.hackedserver.utils.tinyprotocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:509)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[23:15:06] [Netty Server IO #1/WARN]: 	at com.gmail.thelimeglass.Utils.Packets.PacketListener$1.write(PacketListener.java:64)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[23:15:06] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[23:15:06] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[23:15:06] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[23:15:06] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[23:15:06] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by MiniDigger** [comment]
please fill out the issue template if you want to get help.

**Comment by dmulloy2** [comment]
Taking a wild guess it looks like you're trying to use a packet that doesn't exist on 1.12

**Comment by SladeHazard** [comment]
> Taking a wild guess it looks like you're trying to use a packet that doesn't exist on 1.12

also happens to me when using protocolsupport with protocolsupportlegacysupport:
https://hastebin.com/avucohiqez.md

**Comment by SladeHazard** [comment]
fixed by using protocollib 4.4.0! ugh but the auto updater thing..

**Comment by SladeHazard** [comment]
wait... can you please fix this in the latest version using 4.4.0 makes error with other plugins!
