### ISSUE TITLE
ProtocolLib 4.5.1 Issue

### ISSUE THREAD

**Issue by Peebbong** [dmulloy2/ProtocolLib#866]
[10:47:40] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.5.1
[10:47:40] [Server thread/INFO]: Error Cannot enable ProtocolLib. (java.lang.LinkageError: com/comphenix/protocol/PacketType$Play$Client) occured in ProtocolLib v4.5.1.
[10:47:40] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot enable ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.LinkageError: com/comphenix/protocol/PacketType$Play$Client
        at com.comphenix.protocol.PacketType.getLookup(PacketType.java:668)
        at com.comphenix.protocol.PacketType.fromCurrent(PacketType.java:876)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.associatePackets(NettyProtocolRegistry.java:207)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initializeNew(NettyProtocolRegistry.java:184)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:49)
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:43)
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
        at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:218)
        at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
        at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
        at java.lang.Thread.run(Unknown Source)
  Dump:
  Sender:
    com.comphenix.protocol.ProtocolLib@6e6b63f9[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@3a8d15ae
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@516257da
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=true
      loader=org.bukkit.plugin.java.JavaPluginLoader@35bd651c
      server=CraftServer{serverName=CraftBukkit,serverVersion=git-Spigot-2f5d615-cfeef75,minecraftVersion=1.15.2}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@6d8dbf12
      dataFolder=plugins\ProtocolLib
      classLoader=org.bukkit.plugin.java.PluginClassLoader@43f8b66c
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=org.bukkit.plugin.PluginLogger@7059ecb5
    ]
  Version:
    ProtocolLib v4.5.1
  Java Version:
    1.8.0_251
  Server:
    git-Spigot-2f5d615-cfeef75 (MC: 1.15.2)

**Comment by dmulloy2** [comment]
https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger
