### ISSUE TITLE
FieldAccessException

### ISSUE THREAD

**Issue by blakedj012** [dmulloy2/ProtocolLib#868]
**Describe the bug**
[09:06:23] [Server thread/WARN]: FieldAccessException: No field with type java.util.List exists in class PacketPlayOutWorldParticles.
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
[09:06:23] [Server thread/WARN]:        at com.lishid.orebfuscator.hook.ProtocolLibHandler$1.onPacketSending(ProtocolLibHandler.java:123)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[09:06:23] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336)
[09:06:23] [Server thread/WARN]:        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214)
[09:06:23] [Server thread/WARN]:        at net.minecraft.world.WorldServer.func_184159_a(WorldServer.java:1581)
[09:06:23] [Server thread/WARN]:        at net.minecraft.world.WorldServer.sendParticles(WorldServer.java:1564)
[09:06:23] [Server thread/WARN]:        at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:254)
[09:06:23] [Server thread/WARN]:        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:1018)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:858)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76)
[09:06:23] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[09:06:23] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[09:06:23] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[09:06:23] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[09:06:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:838)
[09:06:23] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[09:06:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775)
[09:06:23] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629)
[09:06:23] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
**To Reproduce**
Catserver 1.12.2 different plugins

**Version Info**
4.5.1 and latest dev version

**Comment by dmulloy2** [comment]
orefbuscator issue, not protocollib

**Comment by blakedj012** [comment]
[19:55:50] [Server thread/ERROR]: [CMI] Unhandled exception occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-8cf55c8]
        at net.minecraft.server.management.PlayerList.func_148537_a(PlayerList.java:1348) [pl.class:?]
        at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1496) [oo.class:?]
        at net.minecraft.world.World.func_72835_b(World.java:2869) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:289) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:55:50] [Server thread/ERROR]: Parameters:
  net.minecraft.network.play.server.SPacketChangeGameState@6e07705c[
    field_149140_b=8
    field_149141_c=0.19000003
  ]

[19:55:51] [Server thread/ERROR]: [CMI] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-8cf55c8]
        at net.minecraft.server.management.PlayerList.func_148537_a(PlayerList.java:1348) [pl.class:?]
        at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1496) [oo.class:?]
        at net.minecraft.world.World.func_72835_b(World.java:2869) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:289) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:55:53] [Server thread/ERROR]: [CMI] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
        at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
        at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-8cf55c8]
        at net.minecraft.server.management.PlayerList.func_148537_a(PlayerList.java:1348) [pl.class:?]
        at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1496) [oo.class:?]
        at net.minecraft.world.World.func_72835_b(World.java:2869) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:289) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]


No there are more plugins that have problems with protocollib

**Comment by NewbieOrange** [comment]
Build 461 should fix this issue.
