### ISSUE TITLE
FieldAccessException: No field with type java.util.Map exists in class EnumProtocol

### ISSUE THREAD

**Issue by mibby** [dmulloy2/ProtocolLib#879]
ProtocolLib dev 73
https://ci.lucko.me/job/ProtocolLib/73/

Broke in commit https://github.com/dmulloy2/ProtocolLib/commit/5183bd53b595e8cdcd3fa16a44d85f86d06fee5d or https://github.com/dmulloy2/ProtocolLib/commit/5f204d798cc08fa966a2a9b7ee918969b2ab7595?

Downgrading to dev 460 here doesn't have the problem.
https://ci.dmulloy2.net/job/ProtocolLib/

```
[17:38:21] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
[17:38:21] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.15.2) has not yet been tested! Proceed with caution.
[17:38:21] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] Cannot load server and client packet list.
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59) ~[?:?]
	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38) ~[?:?]
	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70) ~[?:?]
	at com.comphenix.protocol.injector.packet.PacketRegistry.getClientPacketTypes(PacketRegistry.java:198) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:266) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:250) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:233) ~[?:?]
	at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:213) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:365) ~[patched_1.15.2.jar:git-Tuinity-"126d3cc"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Tuinity-"126d3cc"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Tuinity-"126d3cc"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[17:38:21] [Server thread/WARN]: [ProtocolLib] Failed to register command PACKET: java.lang.ExceptionInInitializerError
```

**Comment by mibby** [comment]
My apologies, this seems to have actually been an issue with @lucko's jenkins build 73.
https://ci.lucko.me/job/ProtocolLib/73/

Using dev 42 in this jenkins doesn't have the problem.
https://ci.codemc.io/job/ThirdParty/job/ProtocolLib/42/

**Comment by dmulloy2** [comment]
wasn’t aware there were multiple jenkins lol. i always recommend mine, https://ci.dmulloy2.net/job/ProtocolLib

**Comment by mibby** [comment]
I was only fishing on other jenkins since the build failed. :)
