### ISSUE TITLE
NPE spam on 1.16.1

### ISSUE THREAD

**Issue by ghost** [dmulloy2/ProtocolLib#887]
**Describe the bug**
spam in console of error

**To Reproduce**
load server
[12:36:48 ERROR]: java.lang.NullPointerException
[12:36:48 WARN]: java.lang.NullPointerException
[12:36:48 WARN]:        at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
[12:36:48 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
[12:36:48 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[12:36:48 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[12:36:48 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[12:36:48 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:36:48 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[12:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[12:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[12:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[12:36:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[12:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:36:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:36:48 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[12:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:36:48 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[12:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[12:36:48 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:36:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:36:48 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:36:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:36:48 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:36:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by hyperdefined** [comment]
I see the same issue on my server.

**Comment by tkn0** [comment]
Same

**Comment by dmulloy2** [comment]
With the latest snapshot?

**Comment by DeJayDev** [comment]
Yes, tested on latest successful build 467. 

Full Stack: https://hastebin.com/raw/itemeneron

**Comment by dmulloy2** [comment]
@DeJayDev that hastebin link isn't working for me. Is it the same stack as above?

**Comment by eemunni** [comment]
I saw the same issue on my server when I went to supervanish :/

Tested on latest successful build 467: 
`[18:16:20 ERROR]: java.lang.NullPointerException
[18:16:20 WARN]: java.lang.NullPointerException
[18:16:20 WARN]:        at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:203)
[18:16:20 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayOutChat.b(PacketPlayOutChat.java:45)
[18:16:20 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[18:16:20 WARN]:        at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[18:16:20 WARN]:        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[18:16:20 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:16:20 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[18:16:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[18:16:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[18:16:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[18:16:20 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:16:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[18:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:16:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:16:20 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[18:16:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[18:16:20 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[18:16:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[18:16:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:16:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[18:16:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[18:16:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:16:20 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:16:20 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by DeJayDev** [comment]
@dmulloy2 I've retriggered the error (loading the plugin) and copied the error for this pastebin. It looks very different from everyone elses.

https://pastebin.com/UVmpZ7Xh

**Comment by dmulloy2** [comment]
So the issue with chat packets throwing a null pointer is that mojang added a new UUID field to chat messages (presumably to mute/identify other players?) that doesn't get set by default. It _seemed_ to be fixed in my testing with the latest dev build, but I can look into something else if that's not the case

@DeJayDev no idea what's going on with your error, but it's not related to this error. Where did you get your jar from?

**Comment by eemunni** [comment]
Ah yes! It works! Thank you so much :D

**Comment by ApeRover** [comment]
I had the same issue as emmunni using supervanish.  Latest dev build seems to have resolved it. Thanks a lot! :)
