### ISSUE TITLE
[1.16.1] NullPointerException WARN when doing /summon

### ISSUE THREAD

**Issue by AndiSlash0723** [dmulloy2/ProtocolLib#898]
**Describe the bug**
NullPointerException WARN when doing /summon on 1.16.1 Paper server

**To Reproduce**
Launch the server, use /summon to summon any mob as player.

**Expected behavior**
Doesnt affect the mob spawning but I expect having no errors

**Version Info**
https://pastebin.com/95PjzZaf

**Additional context**
https://pastebin.com/Y7nAKpEg
`[04:11:20 INFO]: AndiSlash0723 issued server command: /summon minecraft:zombie
[04:11:20 INFO]: IC DEBUG AndiSlash0723 4
[04:11:20 WARN]: java.lang.NullPointerException
[04:11:20 WARN]:        at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:58)
[04:11:20 WARN]:        at com.loohp.interactivechat.Listeners.ChatPackets$1.onPacketSending(ChatPackets.java:90)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[04:11:20 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.b(NetworkManager.java:288)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.dispatchPacket(NetworkManager.java:244)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.sendPacket(NetworkManager.java:220)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1630)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.EntityPlayer.a(EntityPlayer.java:1691)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.EntityPlayer.sendMessage(EntityPlayer.java:1687)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.CommandListenerWrapper.sendMessage(CommandListenerWrapper.java:204)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.CommandSummon.a(SourceFile:79)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.CommandSummon.c(SourceFile:41)
[04:11:20 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[04:11:20 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.CommandDispatcher.a(CommandDispatcher.java:180)
[04:11:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[04:11:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[04:11:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[04:11:20 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[04:11:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)`

Edit: Added pastebin link to the error message

**Comment by AndiSlash0723** [comment]
Sorry for the mess in the error code, i copied it to pastebin and heres the link:
https://pastebin.com/Y7nAKpEg

**Comment by dmulloy2** [comment]
Looks like an issue with InteractiveChat. Doesn't seem to be anything with PL

**Comment by AndiSlash0723** [comment]
I reported the issue to the the author of InteractiveChat and it turns out it's Spigot's problem :P
Anyway thanks for replying and I'm closing this issue. :)
