### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dementisimus** [dmulloy2/ProtocolLib#913]
1. just be the first one who joins the server

`
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 ERROR]: java.lang.NullPointerException
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]: java.lang.NullPointerException
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at net.minecraft.server.v1_16_R1.PacketDataSerializer.a(PacketDataSerializer.java:164)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at net.minecraft.server.v1_16_R1.PacketPlayOutPlayerInfo.b(SourceFile:97)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:42)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at net.minecraft.server.v1_16_R1.PacketEncoder.encode(PacketEncoder.java:12)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:57)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at protocolsupport.utils.netty.MessageToMessageCodec.write(MessageToMessageCodec.java:61)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 WARN]:         at java.base/java.lang.Thread.run(Thread.java:832)
[15.07 01:01:16.049] INFO: [Lobby-1] [01:01:07 INFO]: dementisimus lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
`

**Comment by dmulloy2** [comment]
Looks like some plugin (hard to tell which one) is sending a player info packet without some required data. Run `/protocol dump` and paste with pastebin so we can see which one

**Comment by dementisimus** [comment]
a plugin (not mine) issued this error. Im sorry!
