### ISSUE TITLE
stack trace

### ISSUE THREAD

**Issue by RealNitrone** [dmulloy2/ProtocolLib#914]
If this problem hasn't already been reported, please open a ticket
at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
Stack Trace:
java.lang.ExceptionInInitializerError
at com.comphenix.protocol.ProtocolLib.onEnable(ProtocolLib.java:374)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:493)
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:411)
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:180)
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:499)
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
Caused by: java.lang.NullPointerException
at com.comphenix.protocol.reflect.FuzzyReflection.getConstructors(FuzzyReflection.java:655)
at com.comphenix.protocol.reflect.FuzzyReflection.getConstructorList(FuzzyReflection.java:588)
at com.comphenix.protocol.utility.ChatExtensions.getJsonFormatConstructor(ChatExtensions.java:219)
at com.comphenix.protocol.utility.ChatExtensions.<clinit>(ChatExtensions.java:55)
... 9 more
Dump:
Sender:
com.comphenix.protocol.ProtocolLib@1d92065d[
statistics=<null>
backgroundCompiler=<null>
packetTask=-1
tickCounter=0
unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@5cdd71bd
configExpectedMod=-1
updater=com.comphenix.protocol.updater.SpigotUpdater@47a40133
redirectHandler=<null>
commandProtocol=<null>
commandPacket=<null>
commandFilter=<null>
packetLogging=<null>
skipDisable=false
isEnabled=true
loader=org.bukkit.plugin.java.JavaPluginLoader@5cacc8e6
server=CraftServer{serverName=CraftBukkit,serverVersion=git-PaperSpigot-b30b391,minecraftVersion=1.7.10}
file=plugins/ProtocolLib (2).jar
description=org.bukkit.plugin.PluginDescriptionFile@3ea6a98f
dataFolder=plugins/ProtocolLib
classLoader=org.bukkit.plugin.java.PluginClassLoader@51756452
naggable=true
ebean=<null>
newConfig=YamlConfiguration[path='', root='YamlConfiguration']
configFile=plugins/ProtocolLib/config.yml
logger=org.bukkit.plugin.PluginLogger@376a469d
]
Version:
ProtocolLib v4.5.0
Java Version:
1.8.0_242
Server:
git-PaperSpigot-b30b391 (MC: 1.7.10)

**Comment by patrick-mc** [comment]
v1.7 not supported after v3.7.0
please use https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
