### ISSUE TITLE
CommandProtocol error

### ISSUE THREAD

**Issue by Corenb** [dmulloy2/ProtocolLib#922]
**Version Info**
ProtocolLib v4.6.0-SNAPSHOT-b472
Error when perform /protocol dump :
```
[10:01:48 WARN]: Unexpected exception while parsing console command "protocol dump"
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.1.jar:git-Paper-123]
org.bukkit.command.CommandException: Unhandled exception executing command 'protocol' in plugin ProtocolLib v4.6.0-SNAPSHOT-b472
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-123]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-123]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-123]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756) ~[patched_1.16.1.jar:git-Paper-123]
        ... 9 more
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-123]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
        ... 9 more
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.error.Report
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-123]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-123]
        at com.comphenix.protocol.CommandBase.onCommand(CommandBase.java:84) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-123]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-123]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/error/Report
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-123]
        at com.comphenix.protocol.CommandBase.onCommand(CommandBase.java:84) ~[?:?]
java.lang.NoClassDefFoundError: com/comphenix/protocol/CommandProtocol$1
        at com.comphenix.protocol.CommandProtocol.performUpdate(CommandProtocol.java:123) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-123]
        at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:585) ~[?:?]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-123]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-123]
```

**Console Error**
```
[09:58:53 WARN]: [ProtocolLib] Task #8 for ProtocolLib v4.6.0-SNAPSHOT-b472 generated an exception
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-123]
java.lang.NoClassDefFoundError: com/comphenix/protocol/CommandProtocol$1
        at com.comphenix.protocol.CommandProtocol.performUpdate(CommandProtocol.java:123) ~[?:?]
        at com.comphenix.protocol.CommandProtocol.checkVersion(CommandProtocol.java:93) ~[?:?]
        at com.comphenix.protocol.ProtocolLib.checkUpdates(ProtocolLib.java:585) ~[?:?]
        at com.comphenix.protocol.ProtocolLib.access$600(ProtocolLib.java:58) ~[?:?]
        at com.comphenix.protocol.ProtocolLib$3.run(ProtocolLib.java:550) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-123]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-123]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-123]
        at com.comphenix.protocol.CommandProtocol.checkVersion(CommandProtocol.java:93) ~[?:?]

**Comment by dmulloy2** [comment]
Try this: https://github.com/dmulloy2/ProtocolLib/wiki/Common-Errors#illegalaccesserrornosuchmethoderror-for-protocollogger
