### ISSUE TITLE
1.16.2 MultiBlockChange

### ISSUE THREAD

**Issue by Huskehhh** [dmulloy2/ProtocolLib#941]
**Describe the bug**
It appears as though the MultiBlockChange packet has changed, and hasn't been changed in ProtocolLib

**To Reproduce**
- Start server with ProtocolLib and attempt to create MultiBlockChange packet

**Version Info**
ProtocolLib - b476, Paper 1.16.2

**Additional context**
Console:

```
[08:37:18 WARN]: Caused by: java.lang.RuntimeException: Unable to find MultiBlockChangeInfo (PacketPlayOutMultiBlockChange$MultiBlockChangeInfo)
[08:37:18 WARN]: 	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2101)
[08:37:18 WARN]: 	at com.comphenix.protocol.utility.MinecraftReflection.getMultiBlockChangeInfoClass(MinecraftReflection.java:1848)
[08:37:18 WARN]: 	at com.comphenix.protocol.wrappers.MultiBlockChangeInfo.<clinit>(MultiBlockChangeInfo.java:38)
[08:37:18 WARN]: 	... 13 more
```

Cheers!

**Comment by joehot200** [comment]
I have been able to duplicate this issue too.

![image](https://user-images.githubusercontent.com/6872507/90984516-58aab580-e56d-11ea-8c72-87555d01d696.png)
