### ISSUE TITLE
Class Not Found Exception: net.minecraft.server.v1_8_R3.AttributeSnapshot

### ISSUE THREAD

**Issue by NavidK0** [dmulloy2/ProtocolLib#96]
This one likes to come back every update. I believe it's the same issue as before and in the same location as before, all it should require is an update.

```
[18:51:03 WARN]: java.lang.RuntimeException: Cannot find class net.minecraft.server.v1_8_R3.AttributeSnapshot
[18:51:03 WARN]: at com.comphenix.protocol.utility.MinecraftReflection.getClass(MinecraftReflection.java:1891)
[18:51:03 WARN]: at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1912)
[18:51:03 WARN]: at com.comphenix.protocol.utility.MinecraftReflection.getAttributeSnapshotClass(MinecraftReflection.java:1540)
[18:51:03 WARN]: at com.comphenix.protocol.events.PacketContainer.getAttributeCollectionModifier(PacketContainer.java:488)
[18:51:03 WARN]: at me.libraryaddict.disguise.utilities.PacketsManager.transformPacket(PacketsManager.java:1287)
[18:51:03 WARN]: at me.libraryaddict.disguise.utilities.PacketsManager$5.onPacketSending(PacketsManager.java:1211)
[18:51:03 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[18:51:03 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[18:51:03 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:634)
[18:51:03 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:610)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:362)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:328)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:296)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110)
[18:51:03 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:79)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:880)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:352)
[18:51:03 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:51:03 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[18:51:03 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:51:03 WARN]: at java.lang.reflect.Method.invoke(Method.java:606)
[18:51:03 WARN]: at me.libraryaddict.disguise.utilities.DisguiseUtilities$8.run(DisguiseUtilities.java:812)
[18:51:03 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:51:03 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[18:51:03 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[18:51:03 WARN]: at java.lang.Thread.run(Thread.java:745)
[18:51:03 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.AttributeSnapshot
[18:51:03 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[18:51:03 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[18:51:03 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[18:51:03 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[18:51:03 WARN]: at com.comphenix.protocol.utility.MinecraftReflection.getClass(MinecraftReflection.java:1889)
[18:51:03 WARN]: ... 33 more
```

**Comment by dmulloy2** [comment]
I think that's an outdated version. Line 1540 is this: https://github.com/dmulloy2/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java#L1540

**Comment by dmulloy2** [comment]
If this is still an issue with the latest builds, I'd like to get it fixed before the 3.6.4 release.

**Comment by NavidK0** [comment]
I am currently using 3.6.4 with LibsDisguises. That stacktrace was posted by someone else, so they must still be using an outdated version.

**Comment by NavidK0** [comment]
Ok, I think this has been fixed as of the latest ProtocolLib versions.
