### ISSUE TITLE
Bad Plugin.yml

### ISSUE THREAD

**Issue by dumbninja22** [dmulloy2/ProtocolLib#97]
The latest build of ProtocolLib has an invalid plugin.yml.

Error:
[19:22:55] [Server thread/ERROR]: Could not load 'plugins\ProtocolLib.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_45]
    at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_45]
    at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_45]
    at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_45]
    at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot-1.8.7.jar:git-Spigot-b3c0272-7723b90]
    ... 5 more

**Comment by dmulloy2** [comment]
I don't know how you managed that one, are you downloading them from http://ci.shadowvolt.com/job/ProtocolLib/ ?

**Comment by westjet1** [comment]
Yes its the latest build from that Jenkins

**Comment by dmulloy2** [comment]
Usually ZipExceptions happen when the zip file (in this case the ProtocolLib jar) is corrupted. Try redownloading it.

**Comment by dumbninja22** [comment]
Oh ok then that might be it. Because my internet wa really slow as I was downloading ProtocolLib, that's probably it.
