### ISSUE TITLE
I get an error when trying to connect to the server

### ISSUE THREAD

**Issue by zlfn** [dmulloy2/ProtocolLib#975]
Whenever I try to connect to the server, an error occurs.

**error message**
[09:47:37 WARN]: Exception in thread "User Authenticator #1" java.lang.NoClassDefFoundError: Could not initialize class java.net.SocksSocketImpl
[09:47:37 WARN]: 	at java.base/java.net.Socket.setImpl(Socket.java:523)
[09:47:37 WARN]: 	at java.base/java.net.Socket.<init>(Socket.java:88)
[09:47:37 WARN]: 	at java.base/javax.net.ssl.SSLSocket.<init>(SSLSocket.java:162)
[09:47:37 WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.<init>(BaseSSLSocketImpl.java:61)
[09:47:37 WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:107)
[09:47:37 WARN]: 	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:72)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:413)
[09:47:37 WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:162)
[09:47:37 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[09:47:37 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[09:47:37 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[09:47:37 WARN]: 	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:130)
[09:47:37 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66)
[09:47:37 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.hasJoinedServer(YggdrasilMinecraftSessionService.java:100)
[09:47:37 WARN]: 	at net.minecraft.server.v1_15_R1.LoginListener$2.run(LoginListener.java:244)
[09:47:37 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[09:47:37 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[09:47:37 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**using system**
Ubuntu server 18.04
azureVM B2s (2*vcpu, 4Gib RAM)
OpenJDK 11.0.8
Paper-387

**Comment by zlfn** [comment]
No error occurred when using Java 1.8 version
